'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,read=n=>JSON.parse(fs.readFileSync(path.join(root,n),'utf8')),m=read('manifest.json'),s=read('studies.json').studies,sourceData=read('sources.json'),sources=sourceData.sources,c=read('comparisons.json'),bySource=new Map(sources.map(x=>[x.id,x])),byStudy=new Map(s.map(x=>[x.slug,x]));
const esc=x=>String(x).replace(/[&<>"']/g,v=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[v]));
function link(t,u){const url=new URL(u,'https://v5ma.github.io/theology-wiki/comparative-religion/egypt-emanation/moses-jesus-mammon/');if(url.protocol!=='https:')throw Error('Unsafe URL');return '<a href="'+esc(u)+'">'+esc(t)+'</a>';}
const p=t=>'<p>'+esc(t)+'</p>',refs=ids=>[...new Set(ids)].map(id=>{if(!bySource.has(id))throw Error('Missing source '+id);return '<p>'+link(bySource.get(id).title,'sources.html#'+id)+'</p>';}).join('');
const nav='<nav aria-label="Study navigation">'+link('Three studies','index.html')+link('Connections and limits','comparisons.html')+link('Sources','sources.html')+link('Egyptian Seed studies','../index.html')+link('Apocalyptic Repair Theology','../../../san-reader.html?page=apocalyptic-repair-theology')+link('Kenite hypothesis','../../../san-reader.html?page=kenite-hypothesis-and-yahweh-origins')+'</nav>';
function shell(title,summary,body,script=false){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+esc(summary)+'"><title>'+esc(title)+' | Theology Wiki</title><link rel="stylesheet" href="../../series.css"></head><body><a class="skip" href="#main">Skip to content</a><header><p class="eyebrow">THEOLOGY WIKI / MOSES, JESUS AND MAMMON / SEPTEMBER 18, 2026</p><h1>'+esc(title)+'</h1><p class="lede">'+esc(summary)+'</p>'+nav+'</header><main id="main">'+body+'</main><footer><p>The proposed alignment concerns responsibility, not proof that every source has the same afterlife doctrine. Scriptural portrayal, ancient reception, a historical genealogy and modern ethical application remain distinct.</p><p>'+link('Plain-text studies','READING.md')+' / '+link('Scope and preservation','README.md')+' / '+link('Local full-text index','index.json')+'</p></footer>'+(script?'<script src="reader.js"></script>':'')+'</body></html>\n';}
function controls(types){return '<div class="controls"><label>Search full study or record<input id="query" type="search"></label><label>Relationship<select id="kind"><option value="">All</option>'+[...new Set(types)].sort().map(t=>'<option value="'+esc(t)+'">'+esc(t)+'</option>').join('')+'</select></label><button id="reset" type="button">Reset</button></div><p id="count" role="status" aria-live="polite"></p><p id="empty" hidden>No matching records.</p>';}
const files=[];function write(n,t){fs.writeFileSync(path.join(root,n),t);files.push({path:n,sha256:crypto.createHash('sha256').update(t).digest('hex')});}
for(const study of s){for(const slug of study.related)if(!byStudy.has(slug))throw Error('Missing related study');const body=study.sections.map((x,i)=>'<section id="section-'+(i+1)+'"><h2>'+esc(x.title)+'</h2>'+x.paragraphs.map(p).join('')+'</section>').join('\n');const r=c.comparisons.filter(x=>x.study===study.slug);const related='<section><h2>Inspect the connections</h2>'+r.map(x=>'<p>'+link(x.title,'comparisons.html#'+x.id)+'. '+esc(x.type)+'.</p>').join('')+'</section>';const reading='<section><h2>Related studies</h2>'+study.related.map(slug=>'<p>'+link(byStudy.get(slug).title,slug+'.html')+'</p>').join('')+'</section>';write(study.slug+'.html',shell(study.title,study.summary,body+related+'<section id="sources"><h2>Sources for this study</h2>'+refs(study.sections.flatMap(x=>x.sources))+'</section>'+reading));}
const cards=s.map(x=>'<article class="filter-record" id="study-'+x.slug+'" data-kind="Developed study" data-search="'+esc(x.title+' '+x.summary+' '+x.sections.flatMap(y=>[y.title,...y.paragraphs]).join(' '))+'"><h2>'+link(x.title,x.slug+'.html')+'</h2>'+p(x.summary)+'</article>').join('\n');
write('index.html',shell(m.title,'A source-linked inquiry into the golden calf, divine-name traditions, Mosaic obligations, Jesus\'s use of Moses and Egyptian accounts of care beyond death.','<p class="notice">The richest connection is not a perfect opposition between civilizations: Egyptian inscriptions, Torah and Gospel narratives can all make a person\'s future answerable to the treatment of others. These studies preserve the proposed genealogy while identifying the actual textual bridges.</p>'+controls(['Developed study'])+cards+'<section><h2>Read across the Wiki</h2><p>'+link('Egyptian ascent and judgment','../egyptian-seed.html')+' / '+link('Egyptian-Iranian contact hypotheses','../egypt-iran-contact.html')+' / '+link('Moral time horizons','../moral-horizons-beyond-life.html')+' / '+link('Exodus chronology','../../../san-reader.html?page=moses-volcano-and-exodus-chronology')+'</p></section>',true));
const comparisons=c.comparisons.map(x=>{if(!byStudy.has(x.study))throw Error('Missing study');return '<article class="filter-record" id="'+x.id+'" data-kind="'+esc(x.type)+'"><p class="meta">'+esc(x.type)+'</p><h2>'+esc(x.title)+'</h2>'+p('From: '+x.from)+p('To: '+x.to)+p('Source record: '+x.finding)+p('Proposed inference: '+x.inference)+p('Limit or alternative: '+x.limit)+'<p>'+link('Read the argument',x.study+'.html')+'</p><details><summary>Source witnesses</summary>'+(x.sources.length?refs(x.sources):'<p>This is a proposed present-day application, not a newly sourced allegation about a person or project.</p>')+'</details></article>';}).join('\n');
write('comparisons.html',shell('Twelve connections and their limits',c.policy,controls(c.comparisons.map(x=>x.type))+comparisons,true));
write('sources.html',shell('Sources, passages and reading scope',sourceData.scope,sources.map(x=>'<article id="'+x.id+'"><p class="meta">'+esc(x.kind)+'</p><h2>'+esc(x.title)+'</h2>'+p('Locator: '+x.locator)+p(x.scope)+'<p>'+link('Open source',x.url)+'</p></article>').join('\n')+'<section><h2>Access limitations</h2>'+sourceData.access_limitations.map(p).join('')+'</section>'));
const search=s.map(x=>({slug:x.slug,title:x.title,summary:x.summary,text:x.sections.flatMap(y=>[y.title,...y.paragraphs]).join('\n'),url:x.slug+'.html'}));
write('index.json',JSON.stringify({schema_version:1,edition_date:m.edition_date,scope:m.scope,studies:search,comparisons:c.comparisons},null,2)+'\n');
write('READING.md','This is the plain-text counterpart of the three studies. Source testimony, historical hypotheses and ethical interpretations remain distinct. Source URLs are collected at the end of each study.\n\n'+s.map(x=>x.title+'\n\n'+x.summary+'\n\n'+x.sections.map(y=>y.title+'\n\n'+y.paragraphs.join('\n\n')).join('\n\n')+'\n\nSources: '+[...new Set(x.sections.flatMap(y=>y.sources))].map(id=>bySource.get(id).url).join(' ; ')).join('\n\n')+'\n');
const wordCount=s.flatMap(x=>x.sections.flatMap(y=>y.paragraphs)).join(' ').split(/\s+/).length;
fs.writeFileSync(path.join(root,'build-report.json'),JSON.stringify({schema_version:1,edition_date:m.edition_date,counts:{studies:s.length,comparisons:c.comparisons.length,sources:sources.length,study_words:wordCount,html_pages:files.filter(x=>x.path.endsWith('.html')).length},files},null,2)+'\n');console.log(JSON.stringify({studies:s.length,comparisons:c.comparisons.length,sources:sources.length,study_words:wordCount}));
