'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const read=n=>fs.readFileSync(path.join(__dirname,n),'utf8'),load=n=>JSON.parse(read(n)),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),p=load('apollo-update.json'),s=load('studies.json'),r=load('records.json'),src=load('sources.json');
test('Apollo additions are integrated into the existing study rather than a disconnected route',()=>{assert.equal(s.studies.length,3);const g=s.studies.find(x=>x.slug===p.target_study);assert.equal(g.sections.length,9);assert.deepEqual(g.sections.slice(4),p.additional_sections);assert.equal(g.sections[2].paragraphs[1],p.revised_artwork_paragraph);assert.ok(read('gold-apollo-and-fortresses.html').includes('Cratylus'));assert.ok(load('index.json').studies.find(x=>x.slug===p.target_study).text.includes('Phosphorus'));});
test('all thirteen new sources and four comparisons have exact registered identities',()=>{assert.equal(src.sources.length,43);assert.equal(r.comparisons.length,16);for(const x of p.new_sources){assert.deepEqual(src.sources.find(y=>y.id===x.id),x);assert.equal(x.reviewed_on,'2026-09-19');}for(const x of p.new_comparisons)assert.deepEqual(r.comparisons.find(y=>y.id===x.id),x);});
test('the older AI dates and non-Apollo studies remain unchanged',()=>{const base='theology-wiki/event-forecast-register/authority-imagery/',get=n=>JSON.parse(cp.execFileSync('git',['show',p.base_commit+':'+base+n],{encoding:'utf8'}));assert.deepEqual(r.timeline,get('records.json').timeline);const old=get('studies.json');for(const g of old.studies.filter(x=>x.slug!==p.target_study))assert.deepEqual(s.studies.find(x=>x.slug===g.slug),g);assert.deepEqual(src.sources.slice(0,30),get('sources.json').sources);assert.deepEqual(r.comparisons.slice(0,12),get('records.json').comparisons);});
test('the source distinctions and missing date evidence remain visible',()=>{const t=p.additional_sections.flatMap(x=>x.paragraphs).join(' ');for(const phrase of ['Apollyon','Apollon','five months','sixth trumpet','without displaying a year','Mullins','Eos','real estate'])assert.ok(t.includes(phrase),phrase);assert.ok(t.includes('not explicitly'));assert.ok(t.includes('commentator'));});
test('reapplying the addendum cannot duplicate it or quietly change reviewed files',()=>{const rec=load('apollo-revision-receipt.json');const before=Object.keys(rec.files).map(n=>sha(read(n)));cp.execFileSync(process.execPath,[path.join(__dirname,'apply-apollo.cjs')]);assert.deepEqual(Object.keys(rec.files).map(n=>sha(read(n))),before);assert.equal(rec.plan_sha256,sha(read('apollo-update.json')));assert.equal(rec.preserved_timeline_sha256,sha(JSON.stringify(r.timeline)));});
test('changes since the reviewed base stay within the intended module and its existing workflows',()=>{const root=path.resolve(__dirname,'../../..'),files=cp.execFileSync('git',['diff','--name-only',p.base_commit,'--'],{cwd:root,encoding:'utf8'}).trim().split('\n');assert.ok(files.length>0);for(const f of files)assert.ok(f.startsWith('theology-wiki/event-forecast-register/authority-imagery/')||['.github/workflows/theology-authority-imagery-integration.yml','.github/workflows/theology-authority-imagery-validation.yml'].includes(f),f);});
