'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,read=n=>JSON.parse(fs.readFileSync(path.join(root,n),'utf8')),m=read('manifest.json'),s=read('studies.json').studies,d=read('records.json'),sourceData=read('sources.json'),sources=sourceData.sources,bySource=new Map(sources.map(x=>[x.id,x])),byStudy=new Map(s.map(x=>[x.slug,x]));
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function link(label,url){if(new URL(url,'https://v5ma.github.io/theology-wiki/event-forecast-register/authority-imagery/').protocol!=='https:')throw Error('Unsupported URL');return '<a href="'+esc(url)+'">'+esc(label)+'</a>';}
const p=t=>'<p>'+esc(t)+'</p>';function refs(ids){return [...new Set(ids)].map(id=>{if(!bySource.has(id))throw Error('Unknown source '+id);return '<p>'+link(bySource.get(id).title,'sources.html#'+id)+'</p>';}).join('');}
const nav='<nav aria-label="Research navigation">'+link('Studies','index.html')+link('Dated policy record','timeline.html')+link('Comparison questions','comparisons.html')+link('Sources and access','sources.html')+link('Event register','../index.html')+link('First Beast article','../../san-reader.html?page=trump-first-beast-of-revelation')+'</nav>';
function shell(title,summary,body,script=false){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+esc(summary)+'"><title>'+esc(title)+' | Theology Wiki</title><link rel="stylesheet" href="../../comparative-religion/series.css"></head><body><a class="skip" href="#main">Skip to content</a><header><p class="eyebrow">THEOLOGY WIKI / AUTHORITY, IMAGERY AND SOURCES / SEPTEMBER 18, 2026</p><h1>'+esc(title)+'</h1><p class="lede">'+esc(summary)+'</p>'+nav+'</header><main id="main">'+body+'</main><footer><p>This source audit separates the author\'s theological framework from factual records, allegations and unresolved questions. No political actor or policy is scored, ranked or assigned a prophetic identity.</p><p>'+link('Edition notes','README.md')+' / '+link('Plain-text study export','READING.md')+' / '+link('Machine-readable data','index.json')+'</p></footer>'+(script?'<script src="reader.js"></script>':'')+'</body></html>\n';}
function controls(types){return '<div class="controls"><label>Search full text<input id="query" type="search"></label><label>Record type<select id="kind"><option value="">All</option>'+[...new Set(types)].sort().map(t=>'<option value="'+esc(t)+'">'+esc(t)+'</option>').join('')+'</select></label><button id="reset" type="button">Reset</button></div><p id="count" role="status" aria-live="polite"></p><p id="empty" hidden>No matching records.</p>';}
const files=[];function write(name,text){fs.writeFileSync(path.join(root,name),text);files.push({path:name,sha256:crypto.createHash('sha256').update(text).digest('hex')});}
for(const x of s){for(const r of x.related)if(!byStudy.has(r))throw Error('Unknown study');const body=x.sections.map((y,i)=>'<section id="section-'+(i+1)+'"><h2>'+esc(y.title)+'</h2>'+y.paragraphs.map(p).join('')+'</section>').join('\n');write(x.slug+'.html',shell(x.title,x.summary,body+'<section id="sources"><h2>Sources for this study</h2>'+refs(x.sections.flatMap(y=>y.source_ids))+'</section><section><h2>Related studies</h2>'+x.related.map(id=>'<p>'+link(byStudy.get(id).title,id+'.html')+'</p>').join('')+'</section>'));}
const cards=s.map(x=>'<article class="filter-record" id="study-'+x.slug+'" data-kind="Study" data-search="'+esc([x.title,x.summary,...x.sections.flatMap(y=>[y.title,...y.paragraphs])].join(' '))+'"><h2>'+link(x.title,x.slug+'.html')+'</h2>'+p(x.summary)+'</article>').join('\n');
write('index.html',shell(m.title,'Biblical actors, royal imagery, commercial allegiance and a dated record of AI advocacy and governmental action.','<p class="notice">'+esc(d.author_framework)+'</p>'+controls(['Study'])+cards+'<section><h2>Connected Wiki records</h2><p>'+link('Shared images and resumed X activity','../x-media/index.html')+' / '+link('Earlier contextual statement archive','../corpus-review/index.html')+' / '+link('Scripture concordance','../../scripture-concordance/index.html')+' / '+link('AI and scarcity notebook','../../research-expansion-20260918/index.html')+' / '+link('Moses, Jesus and Mammon','../../comparative-religion/egypt-emanation/moses-jesus-mammon/index.html')+'</p></section>',true));
const rows=[...d.timeline].sort((a,b)=>a.start_date.localeCompare(b.start_date)||a.id.localeCompare(b.id)).map(x=>'<article class="filter-record" id="'+x.id+'" data-kind="'+esc(x.kind)+'"><p class="meta">'+esc(x.start_date+(x.end_date!==x.start_date?' through '+x.end_date:''))+' / '+esc(x.kind)+'</p><h2>'+esc(x.title)+'</h2>'+p(x.record)+p('Scope: '+x.limit)+'<details><summary>Sources</summary>'+refs(x.source_ids)+'</details></article>').join('\n');
write('timeline.html',shell('AI-policy chronology and administrative dates','Publication windows and future deadlines are not interchangeable with completed actions.','<p class="notice">This is a dated record, not a finding of one covert campaign. Three future dates are administrative deadlines in a signed order, not prophetic predictions or completed outcomes.</p>'+controls(d.timeline.map(x=>x.kind))+rows,true));
write('comparisons.html',shell('Twelve comparison questions','Inspect what a proposed connection establishes and what still needs evidence.',controls(d.comparisons.map(x=>x.relation))+d.comparisons.map(x=>'<article class="filter-record" id="'+x.id+'" data-kind="'+esc(x.relation)+'"><p class="meta">'+esc(x.relation)+'</p><h2>'+esc(x.title)+'</h2>'+p(x.finding)+p('Question: '+x.question)+p('Limit: '+x.limit)+'<details><summary>Sources</summary>'+refs(x.source_ids)+'</details></article>').join('\n'),true));
write('sources.html',shell('Source witnesses and access limits',sourceData.policy,sources.map(x=>'<article id="'+x.id+'"><p class="meta">'+esc(x.kind)+'</p><h2>'+esc(x.title)+'</h2>'+p(x.scope)+'<p>'+link('Open source',x.url)+'</p></article>').join('\n')+'<section><h2>Unresolved source recovery</h2>'+sourceData.unresolved.map(p).join('')+'</section>'));
write('index.json',JSON.stringify({schema_version:1,edition_date:m.edition_date,scope:m.scope,studies:s.map(x=>({slug:x.slug,title:x.title,summary:x.summary,text:x.sections.flatMap(y=>[y.title,...y.paragraphs]).join('\n'),url:x.slug+'.html'})),timeline:d.timeline,comparisons:d.comparisons},null,2)+'\n');
write('READING.md','This is the plain-text counterpart of three studies. Primary evidence, reported statements, the author\'s interpretation and unresolved allegations remain distinct. Sources follow each study.\n\n'+s.map(x=>x.title+'\n\n'+x.summary+'\n\n'+x.sections.map(y=>y.title+'\n\n'+y.paragraphs.join('\n\n')).join('\n\n')+'\n\nSources: '+[...new Set(x.sections.flatMap(y=>y.source_ids))].map(id=>bySource.get(id).url).join(' ; ')).join('\n\n')+'\n');
const counts={studies:s.length,timeline:d.timeline.length,comparisons:d.comparisons.length,sources:sources.length,study_words:s.flatMap(x=>x.sections.flatMap(y=>y.paragraphs)).join(' ').split(/\s+/).length,html_pages:files.filter(x=>x.path.endsWith('.html')).length};fs.writeFileSync(path.join(root,'build-report.json'),JSON.stringify({schema_version:1,edition_date:m.edition_date,counts,files},null,2)+'\n');console.log(JSON.stringify(counts));
