/* A-Frame component owns the scene, simulation and input lifecycle. Browser
 * and Quest use the same arrows/enemies; tracked aiming is never synthesized. */
(function(){'use strict';
 const C=VesperCore,I=VesperInput,$=id=>document.getElementById(id),TYPES=['plain','cinder','frost','blink'],BIOMES=['HOLLOW CHOIR','COPPERWAKE','NIGHT GARDEN'];
 AFRAME.registerComponent('vesper-game',{
  init(){
   this.T=AFRAME.THREE;this.scene=this.el;this.rig=$('rig').object3D;this.head=$('head');this.art=VesperArt.create(this.T,this.scene);this.game=C.create('BELL-01');this.keys={};this.running=false;this.paused=false;this.practice=false;this.accumulator=0;this.charge=0;this.drawHeld=false;this.drawArmed=true;this.desktopDraw=0;this.yaw=0;this.pitch=0;this.latch=new I.BowLatch();this.hands={};this.prevButtons={};this.snapArmed=true;this.padArmed=false;this.padPrev=[];this.lastEvent=0;this.lastPhase='playing';this.banked=0;this.lastHud=-1;this.xr=false;this.menuSelection=0;this.nextTeleportFade=0;this.xrMenuRows=[];this.stats={drawCalls:0,triangles:0,builds:0};
   try{this.profile=I.cleanProfile(JSON.parse(localStorage.getItem('vesperfall-profile-v1')||'{}'));}catch{this.profile=I.cleanProfile({});}
   for(const side of ['left','right']){const hand=$(side+'-hand').object3D;this.art.mesh('ball','#9eafb6',hand,0,0,0,.04,.06,.075);this.art.mesh('cylinder','#425169',hand,0,-.055,.02,.043,.08,.043);hand.visible=false;}
   this.visualBow=this.art.bow();this.visualArrow=this.art.arrow();this.bowHolder=new this.T.Group();this.bowHolder.add(this.visualBow.group,this.visualArrow);this.scene.object3D.add(this.bowHolder);
   this.arrowPool=Array.from({length:48},()=>{const g=this.art.arrow();this.scene.object3D.add(g);g.visible=false;return g;});this.boltPool=Array.from({length:24},()=>{const m=new this.T.Mesh(new this.T.SphereGeometry(.09,8,6),this.art.mat('#ffa685',0,true));this.scene.object3D.add(m);m.visible=false;return m;});
   this.sparkPool=Array.from({length:32},()=>{const m=new this.T.Mesh(new this.T.OctahedronGeometry(.16),this.art.mat('#b8fbe0',0,true));this.scene.object3D.add(m);m.visible=false;return m;});
   this.teleLine=new this.T.Line(new this.T.BufferGeometry().setAttribute('position',new this.T.Float32BufferAttribute(new Float32Array(48*3),3)),new this.T.LineBasicMaterial({color:'#8cddcc'}));this.teleLine.frustumCulled=false;this.scene.object3D.add(this.teleLine);
   this.teleRing=new this.T.Mesh(new this.T.TorusGeometry(.4,.035,6,24),this.art.mat('#9dedce',0,true));this.teleRing.rotation.x=-Math.PI/2;this.scene.object3D.add(this.teleRing);
   this.xrPanel=this.makePanel();this.scene.object3D.add(this.xrPanel.mesh);this.xrPanel.mesh.visible=false;
   this.xrHud=this.makePanel(1024,192,1.0,.19);this.head.object3D.add(this.xrHud.mesh);this.xrHud.mesh.position.set(0,-.37,-1.05);this.xrHud.mesh.visible=false;
   this.blackout=new this.T.Mesh(new this.T.SphereGeometry(.2,12,8),new this.T.MeshBasicMaterial({color:'#101725',side:this.T.BackSide,transparent:true,opacity:0,depthTest:false}));this.blackout.renderOrder=9999;this.head.object3D.add(this.blackout);
   this.build();this.bindUI();this.scene.addEventListener('enter-vr',()=>this.enterXR());this.scene.addEventListener('exit-vr',()=>this.exitXR());
   this.scene.addEventListener('renderstart',()=>this.afterRenderReady(),{once:true});if(this.scene.renderer)this.afterRenderReady();
   window.Vesperfall={get state(){return this.component.game;},component:this,snapshot:()=>({version:C.VERSION,seed:this.game.world.seed,depth:this.game.world.depth,phase:this.game.phase,running:this.running,paused:this.paused,xr:this.xr,player:[...this.game.p],health:this.game.health,ammo:{...this.game.ammo},type:this.game.type,score:this.game.score,kills:this.game.kills,shots:this.game.shots,hits:this.game.hits,portalReady:this.game.portalReady,targets:[...this.game.targets],events:this.game.events.map(e=>({...e})),rooms:this.game.world.rooms.map(r=>({...r})),edges:this.game.world.edges.map(e=>[...e]),exit:this.game.world.exit,enemies:this.game.world.enemies.map(e=>({...e,p:[...e.p]})),draw:{charge:this.charge,held:this.drawHeld},stats:{...this.stats}})};
  },
  afterRenderReady(){if(this.rendererReady)return;this.rendererReady=true;this.scene.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));$('status').textContent='Ready. Desktop practice and experimental Quest WebXR.';this.scene.canvas.setAttribute('tabindex','0');
   if(window.isSecureContext&&navigator.xr)navigator.xr.isSessionSupported('immersive-vr').then(ok=>{this.canVR=ok;$('vr-button').disabled=!ok;$('vr-button').textContent=ok?'Enter VR · preview':'VR not available here';}).catch(()=>{$('vr-button').textContent='WebXR check failed';});else $('vr-button').textContent='Open in a WebXR browser';
   this.scene.canvas.addEventListener('contextmenu',e=>e.preventDefault());this.scene.canvas.addEventListener('pointerdown',e=>{if(!this.running||this.paused||this.xr)return;if(e.pointerType==='touch'){this.touchLook={x:e.clientX,y:e.clientY,id:e.pointerId};this.scene.canvas.setPointerCapture(e.pointerId);return;}if(e.button===0){this.drawArmed=true;this.drawHeld=true;if(!document.pointerLockElement)this.scene.canvas.requestPointerLock?.()?.catch?.(()=>{});}if(e.button===2)this.cancel();});
   this.scene.canvas.addEventListener('pointermove',e=>{if(e.pointerType!=='touch'||!this.touchLook||this.paused)return;this.yaw-=(e.clientX-this.touchLook.x)*.004;this.pitch=C.clamp(this.pitch-(e.clientY-this.touchLook.y)*.004,-1.25,1.25);this.touchLook={x:e.clientX,y:e.clientY,id:e.pointerId};});
   this.scene.canvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch')this.touchLook=null;});this.scene.canvas.addEventListener('pointercancel',()=>{this.touchLook=null;this.cancel();});
  },
  bindUI(){
   $('start').onclick=()=>this.start(false);$('practice').onclick=()=>this.start(true);$('resume').onclick=()=>this.setPaused(false);$('menu-button').onclick=()=>this.setPaused(!this.paused);$('vr-button').onclick=()=>{if(!this.canVR)return;this.cancel();this.scene.enterVR().catch(e=>{$('status').textContent='VR session was not started. '+e.message;});};
   $('unlock-heart').onclick=()=>this.unlock('heart',6);$('unlock-power').onclick=()=>this.unlock('power',10);
   $('handedness').onchange=()=>{this.latch.reset();this.cancel();};$('draw-length').onchange=()=>this.cancel();$('locomotion').onchange=()=>{this.cancel();this.snapArmed=false;};
   for(const b of document.querySelectorAll('[data-arrow]'))b.onclick=()=>this.setType(b.dataset.arrow);
   for(const b of document.querySelectorAll('[data-reward]'))b.onclick=()=>this.choose(b.dataset.reward);
   window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;
    if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();
    if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat&&this.running)this.setPaused(!this.paused);return;}
    if(!this.running||this.paused||this.xr)return;this.keys[e.code]=true;if(e.code==='Space'){if(!e.repeat)this.drawArmed=true;this.drawHeld=true;}
    if(!e.repeat){if(e.code==='KeyE')this.interact();if(e.code==='KeyM')$('map').hidden=!$('map').hidden;if(/^Digit[1-4]$/.test(e.code))this.setType(TYPES[Number(e.code.slice(-1))-1]);if(e.code==='KeyQ')this.cancel();}
   });
   window.addEventListener('keyup',e=>{this.keys[e.code]=false;if(e.code==='Space')this.drawHeld=false;});window.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'&&e.button===0)this.drawHeld=false;});
   window.addEventListener('mousemove',e=>{if(this.running&&!this.paused&&!this.xr&&document.pointerLockElement===this.scene.canvas){this.yaw-=e.movementX*.0023;this.pitch=C.clamp(this.pitch-e.movementY*.0023,-1.25,1.25);}});
   const release=()=>{this.keys={};this.touchLook=null;this.cancel();if(this.running&&!this.paused)this.setPaused(true);};window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden)release();});
   for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.keys[b.dataset.move]=true;};for(const n of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(n,()=>this.keys[b.dataset.move]=false);}
   const draw=$('touch-draw');draw.onpointerdown=e=>{e.preventDefault();draw.setPointerCapture(e.pointerId);this.drawArmed=true;this.drawHeld=true;};draw.onpointerup=()=>this.drawHeld=false;draw.onpointercancel=()=>this.cancel();$('touch-interact').onclick=()=>this.interact();this.menuUI();
  },
  makePanel(w=1024,h=768,width=1.55,height=1.16){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const texture=new this.T.CanvasTexture(canvas);texture.colorSpace=this.T.SRGBColorSpace;texture.minFilter=this.T.LinearFilter;const mesh=new this.T.Mesh(new this.T.PlaneGeometry(width,height),new this.T.MeshBasicMaterial({map:texture,side:this.T.DoubleSide,depthTest:false}));mesh.renderOrder=900;return {canvas,ctx:canvas.getContext('2d'),texture,mesh};},
  profileSave(){try{localStorage.setItem('vesperfall-profile-v1',JSON.stringify(this.profile));}catch{$('status').textContent='Local saving is unavailable; the run remains playable.';}},
  bank(){if(this.practice)return;this.profile.shards+=Math.max(0,this.game.kills-this.banked);this.banked=this.game.kills;this.profile.best=Math.max(this.profile.best,this.game.score);this.profile.depth=Math.max(this.profile.depth,this.game.world.depth);this.profileSave();},
  unlock(key,cost){if(this.profile[key]||this.profile.shards<cost)return;this.profile.shards-=cost;this.profile[key]=true;this.profileSave();this.menuUI();},
  start(practice){const text=$('seed').value.replace(/[^\w-]/g,'').slice(0,24)||'BELL-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36);$('seed').value=text;this.game=C.create(text,1,this.profile);this.banked=0;this.practice=practice;if(practice)this.game.world.enemies=[];this.running=true;this.lastPhase='playing';this.lastEvent=0;this.yaw=0;this.pitch=0;this.rig.rotation.y=0;this.snapArmed=false;this.build();this.setPaused(false);this.toast(practice?'Practice: ring the three targets. No progression is saved.':'Five wardens. One beacon. Your first bell.');},
  choose(type){const n=C.reward(this.game,type);if(!n)return;this.game=n;this.lastEvent=0;this.lastPhase='playing';this.yaw=this.pitch=0;this.rig.rotation.y=0;this.build();this.setPaused(false);this.toast('A new arrangement. '+BIOMES[(n.world.depth-1)%3]);},
  cancel(){this.drawHeld=false;this.drawArmed=false;this.desktopDraw=0;this.charge=0;this.latch.reset();this.teleLine.visible=this.teleRing.visible=false;},
  setPaused(yes){this.paused=!!yes;this.keys={};this.cancel();this.padArmed=false;document.exitPointerLock?.();this.menuSelection=0;this.menuUI();if(this.xr)this.placePanel();else if(!yes)this.scene.canvas?.focus({preventScroll:true});},
  menuUI(){const end=this.game.phase!=='playing';$('menu').classList.toggle('open',!this.running||this.paused||end);$('hud').hidden=!this.running||this.paused||end;$('resume').hidden=!this.running||end;$('reward').hidden=this.game.phase!=='reward';$('start').textContent=this.game.phase==='dead'?'Begin another run →':'Begin a new run →';$('menu-title').textContent=this.game.phase==='dead'?'The bell remembers.':this.game.phase==='reward'?'Choose your blessing.':this.running?'Take a breath.':'Answer the bell.';$('menu-message').textContent=this.game.phase==='reward'?'Your renown is banked. A new connected layout waits beyond this gate.':this.game.phase==='dead'?'The cloisters remain. Your earned renown can strengthen the next attempt.':'Defeat five wardens, open the beacon, and choose how the next run of rooms will challenge you.';$('profile').textContent=`Renown ${this.profile.shards} · best ${this.profile.best} · deepest sector ${this.profile.depth}`;for(const [key,cost]of[['heart',6],['power',10]]){const b=$('unlock-'+key);b.disabled=this.profile[key]||this.profile.shards<cost;b.textContent=this.profile[key]?(key==='heart'?'Heartglass unlocked':'Tempered limbs unlocked'):(key==='heart'?'Heartglass · 6 renown':'Tempered limbs · 10 renown');}this.drawMenu();},
  enterXR(){this.xr=true;this.pendingPanel=true;document.body.classList.add('immersive');this.cancel();this.keys={};this.head.object3D.position.set(0,0,0);this.prevButtons={};this.snapArmed=false;const session=this.scene.renderer.xr.getSession();session?.addEventListener('visibilitychange',()=>{if(session.visibilityState!=='visible')this.setPaused(true);});this.setPaused(true);},
  exitXR(){this.xr=false;document.body.classList.remove('immersive');this.cancel();this.hands={};for(const side of ['left','right'])$(side+'-hand').object3D.visible=false;this.head.object3D.position.set(0,1.65,0);this.head.components['look-controls'].yawObject.rotation.y=this.yaw;this.head.components['look-controls'].pitchObject.rotation.x=this.pitch;this.xrPanel.mesh.visible=this.xrHud.mesh.visible=false;this.blackout.material.opacity=0;this.setPaused(true);},
  placePanel(){const p=new this.T.Vector3(),q=new this.T.Quaternion();this.head.object3D.getWorldPosition(p);this.head.object3D.getWorldQuaternion(q);this.xrPanel.mesh.position.copy(p).add(new this.T.Vector3(0,0,-1.75).applyQuaternion(q));this.xrPanel.mesh.quaternion.copy(q);this.xrPanel.mesh.visible=true;this.drawMenu();},
  drawMenu(){if(!this.xrPanel)return;const {ctx:g,canvas:c,texture}=this.xrPanel;g.fillStyle='#132036';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#9f916f';g.lineWidth=7;g.strokeRect(12,12,c.width-24,c.height-24);g.textAlign='center';g.fillStyle='#ead5aa';g.font='56px Georgia';g.fillText('VESPERFALL',512,91);g.font='23px Arial';g.fillStyle='#bccdd2';g.fillText(this.game.phase==='reward'?'Choose a blessing for the next sector':this.game.phase==='dead'?'The bell remembers. Begin again.':'Experimental Quest preview · local-floor',512,145);
   this.xrMenuRows=this.game.phase==='reward'?[['Vitality · heal and +12 maximum','vitality'],['Tension · +12% arrow power','power'],['Provision · special arrows','supplies'],['Exit VR','exit']]:[[this.running&&this.game.phase==='playing'?'Resume run':'Begin run',this.running&&this.game.phase==='playing'?'resume':'start'],['New run · same seed','start'],['Bow hand: '+$('handedness').value,'hand'],['Movement: '+($('locomotion').value==='teleport'?'blink arrows':'slow stick'),'locomotion'],['Exit VR','exit']];
   this.xrMenuRows.forEach(([text],i)=>{g.fillStyle=i===this.menuSelection?'#42626a':'#263c50';g.fillRect(95,195+i*75,834,61);g.fillStyle='#f1e6d0';g.font='30px Arial';g.fillText(text,512,235+i*75);});g.font='18px Arial';g.fillStyle='#adbfcb';g.fillText('Point draw-hand controller + trigger, or left stick + trigger.',512,665);g.fillText('Bow-hand Y opens this panel. Exit VR is always available.',512,702);texture.needsUpdate=true;
  },
  menuAct(index){const action=this.xrMenuRows[index]?.[1];if(action==='resume')this.setPaused(false);else if(action==='start')this.start(false);else if(['vitality','power','supplies'].includes(action))this.choose(action);else if(action==='hand'){$('handedness').value=$('handedness').value==='left'?'right':'left';this.cancel();this.drawMenu();}else if(action==='locomotion'){$('locomotion').value=$('locomotion').value==='teleport'?'smooth':'teleport';this.drawMenu();}else if(action==='exit')this.scene.exitVR();},
  setType(type){if(!TYPES.includes(type))return;this.game.type=type;this.cancel();this.toast(type==='blink'?'Blink arrows move you only to clear floors.':type==='cinder'?'Cinder: a close burst around the impact.':type==='frost'?'Frost: slows an alerted warden.':'Standard arrows · unlimited');},
  interact(){if(this.practice){this.toast('Practice is unscored. Start a run from the pause menu.');return;}if(!C.interact(this.game))this.toast(this.game.portalReady?'Follow the open beacon on the map.':'The beacon opens when all five wardens fall.');},
  shoot(origin,dir,charge){if(!this.running||this.paused||this.game.phase!=='playing')return;const success=C.fire(this.game,origin,dir,charge);if(success)this.sound(210+charge*180,.15,.045);else if(charge>=.08)this.toast('No shot: check ammo, cover or blink cooldown.');},
  sound(freq,dur,vol){if(!$('audio').checked)return;try{this.audio??=new (window.AudioContext||window.webkitAudioContext)();this.audio.resume();const a=this.audio,o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.setValueAtTime(freq,a.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(50,freq*.48),a.currentTime+dur);g.gain.setValueAtTime(0,a.currentTime);g.gain.linearRampToValueAtTime(vol,a.currentTime+.007);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+dur+.01);o.onended=()=>{g.disconnect();o.disconnect();};}catch{}},
  toast(text){$('toast').textContent=text;$('toast').style.opacity='1';clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>$('toast').style.opacity='0',2200);},
  build(){if(this.worldArt)this.art.dispose(this.worldArt.group);if(this.entities){this.art.dispose(this.entities);}this.worldArt=this.art.world(this.game.world);$('world').setObject3D('mesh',this.worldArt.group);this.entities=new this.T.Group();this.scene.object3D.add(this.entities);this.enemyMeshes=this.game.world.enemies.map(e=>{const g=this.art.enemy(e.kind);this.entities.add(g);return g;});this.pickupMeshes=this.game.world.pickups.map(p=>{const g=new this.T.Group();this.entities.add(g);const color=p.kind==='health'?'#a8e7ba':p.kind==='frost'?'#96d4f0':'#f1b483';this.art.mesh('ball',color,g,0,0,0,.16,.23,.16);this.art.mesh('ring','#b8a574',g,0,0,0,.3,.3,.3);return g;});this.rig.position.set(...this.game.p);this.stats.builds++;this.stats.instances=this.worldArt.instances;},
  tracked(frame){const session=this.scene.renderer.xr.getSession(),ref=this.scene.renderer.xr.getReferenceSpace();if(!frame||!session||!ref){this.hands={};for(const side of ['left','right'])$(side+'-hand').object3D.visible=false;return;}
   const hands={};for(const src of session.inputSources){if(!['left','right'].includes(src.handedness)||!src.gripSpace||!src.gamepad)continue;const pose=frame.getPose(src.gripSpace,ref);if(!pose||pose.emulatedPosition)continue;const obj=$(src.handedness+'-hand').object3D;obj.position.copy(pose.transform.position);obj.quaternion.copy(pose.transform.orientation);obj.updateMatrixWorld(true);hands[src.handedness]={object:obj,source:src,p:obj.getWorldPosition(new this.T.Vector3()).toArray(),q:obj.getWorldQuaternion(new this.T.Quaternion()),buttons:src.gamepad.buttons.map(b=>!!b.pressed),axes:src.gamepad.axes};}
   this.hands=hands;for(const side of ['left','right'])$(side+'-hand').object3D.visible=!!hands[side];
  },
  turn(angle){const before=this.head.object3D.getWorldPosition(new this.T.Vector3());this.rig.rotation.y+=angle;this.rig.updateMatrixWorld(true);const after=this.head.object3D.getWorldPosition(new this.T.Vector3());this.rig.position.x+=before.x-after.x;this.rig.position.z+=before.z-after.z;},
  processXR(dt,head){this.tracked(this.scene.frame);if(this.pendingPanel&&head.y>.4&&Object.keys(this.hands).length){this.placePanel();this.pendingPanel=false;}const bowName=$('handedness').value,drawName=bowName==='left'?'right':'left',bow=this.hands[bowName],draw=this.hands[drawName];
   const rise=(name,i)=>this.hands[name]?.buttons[i]&&!this.prevButtons[name]?.[i];
   if(rise(bowName,5)){this.setPaused(!this.paused);}
   if(!this.running||this.paused||this.game.phase!=='playing'){
    this.latch.reset();if(!this.xrPanel.mesh.visible)this.placePanel();
    if(draw){const ray=new this.T.Raycaster(new this.T.Vector3(...draw.p),new this.T.Vector3(0,0,-1).applyQuaternion(draw.q)),hit=ray.intersectObject(this.xrPanel.mesh)[0];if(hit?.uv){const y=(1-hit.uv.y)*768,index=Math.floor((y-195)/75);if(index>=0&&index<this.xrMenuRows.length&&index!==this.menuSelection){this.menuSelection=index;this.drawMenu();}}
     const ay=I.deadzone(bow?.axes.at(-1)||0);if(Math.abs(ay)<.2)this.menuAxisReady=true;else if(this.menuAxisReady){this.menuSelection=(this.menuSelection+(ay>0?1:-1)+this.xrMenuRows.length)%this.xrMenuRows.length;this.menuAxisReady=false;this.drawMenu();}
     if(rise(drawName,0))this.menuAct(this.menuSelection);
    }
   }else{
    this.xrPanel.mesh.visible=false;
    if(!bow||!draw){this.latch.reset();this.charge=0;this.xrNotice='Both controllers need valid tracking.';}
    else{
     if(rise(drawName,4))this.setType(TYPES[(TYPES.indexOf(this.game.type)+1)%TYPES.length]);if(rise(drawName,5))this.setType(this.game.type==='blink'?'plain':'blink');if(rise(bowName,4))this.interact();
     const ax=draw.axes.length>=4?draw.axes[2]:draw.axes[0]||0;if(Math.abs(ax)<.25)this.snapArmed=true;else if(Math.abs(ax)>.7&&this.snapArmed){this.turn(ax>0?-Math.PI/6:Math.PI/6);this.snapArmed=false;this.cancel();}
     if($('locomotion').value==='smooth'&&!this.latch.drawing){const x=I.deadzone(bow.axes.length>=4?bow.axes[2]:bow.axes[0]),z=I.deadzone(bow.axes.at(-1));this.walkInput(x,z,dt,head,1.7);}
     const nock=new this.T.Vector3(0,0,.09).applyQuaternion(bow.q).add(new this.T.Vector3(...bow.p)).toArray();const allowed=!this.headBlocked;const r=this.latch.update(nock,draw.p,draw.buttons[0],allowed,Number($('draw-length').value));this.charge=r.charge;this.drawHeld=r.drawing;this.xrNotice=r.drawing?'Release trigger to loose.':allowed?'Bring draw hand to the bow, squeeze trigger, then pull.':'Step back from the wall.';if(r.shot)this.shoot(r.shot.origin,r.shot.direction,r.shot.charge);
    }
   }
   this.prevButtons=Object.fromEntries(Object.entries(this.hands).map(([k,v])=>[k,[...v.buttons]]));
  },
  walkInput(x,z,dt,head,speed){if(!Number.isFinite(x)||!Number.isFinite(z))return;const dir=new this.T.Vector3(0,0,-1).applyQuaternion(this.head.object3D.getWorldQuaternion(new this.T.Quaternion()));dir.y=0;dir.normalize();const right=new this.T.Vector3(-dir.z,0,dir.x);const move=right.multiplyScalar(x).addScaledVector(dir,-z);if(move.length()>1)move.normalize();const old=[...this.game.p];C.move(this.game,move.x*speed*dt,move.z*speed*dt);this.rig.position.x+=this.game.p[0]-old[0];this.rig.position.z+=this.game.p[2]-old[2];},
  standardPad(dt){if(this.xr)return;const pad=[...(navigator.getGamepads?.()||[])].find(p=>p?.connected&&p.mapping==='standard');if(!pad){if(this.hadPad&&this.running)this.setPaused(true);this.hadPad=false;this.padPrev=[];return;}this.hadPad=true;const b=pad.buttons.map(b=>b.pressed);if(!b.some(Boolean))this.padArmed=true;if(!this.padArmed){this.padPrev=b;return;}const edge=i=>b[i]&&!this.padPrev[i];if(edge(9))this.setPaused(!this.paused);if(!this.running||this.paused){if(edge(0)){if(this.running&&this.game.phase==='playing')this.setPaused(false);else this.start(false);}}else{this.yaw-=I.deadzone(pad.axes[2])*dt*1.5;this.pitch=C.clamp(this.pitch-I.deadzone(pad.axes[3])*dt*1.2,-1.25,1.25);this.walkInput(I.deadzone(pad.axes[0]),I.deadzone(pad.axes[1]),dt,null,2.5);this.drawHeld=b[7];if(edge(0))this.interact();if(edge(3))this.setType(TYPES[(TYPES.indexOf(this.game.type)+1)%4]);if(edge(1))this.setType(this.game.type==='blink'?'plain':'blink');if(edge(4))this.cancel();}this.padPrev=b;},
  desktop(dt){this.standardPad(dt);if(!this.running||this.paused||this.game.phase!=='playing')return;const k=this.keys;this.yaw+=((k.ArrowLeft?1:0)-(k.ArrowRight?1:0))*dt*1.25;this.pitch=C.clamp(this.pitch+((k.ArrowUp?1:0)-(k.ArrowDown?1:0))*dt*.9,-1.25,1.25);const look=this.head.components['look-controls'];look.yawObject.rotation.y=this.yaw;look.pitchObject.rotation.x=this.pitch;this.head.object3D.position.y=k.ControlLeft?.95:1.65;this.walkInput((k.KeyD?1:0)-(k.KeyA?1:0),(k.KeyS?1:0)-(k.KeyW?1:0),dt,null,k.ShiftLeft?3.6:2.5);
   if(!this.drawHeld&&this.desktopDraw===0)this.drawArmed=true;
   if(this.drawHeld&&this.drawArmed){this.desktopDraw=Math.min(1,this.desktopDraw+dt/1.1);this.charge=this.desktopDraw;}
   else if(!this.drawHeld&&this.desktopDraw>0){const dir=new this.T.Vector3(0,0,-1).applyQuaternion(this.head.object3D.getWorldQuaternion(new this.T.Quaternion())),origin=this.head.object3D.getWorldPosition(new this.T.Vector3()).addScaledVector(dir,.18);this.shoot(origin.toArray(),dir.toArray(),this.desktopDraw);this.desktopDraw=0;this.charge=0;}
  },
  bowVisual(){const T=this.T,headQ=this.head.object3D.getWorldQuaternion(new T.Quaternion()),headP=this.head.object3D.getWorldPosition(new T.Vector3()),hand=this.hands[$('handedness').value];
   if(this.xr){this.bowHolder.visible=!!hand&&this.running&&!this.paused&&this.game.phase==='playing';if(hand){this.bowHolder.position.set(...hand.p);this.bowHolder.quaternion.copy(hand.q);}}
   else{this.bowHolder.visible=this.running&&!this.paused&&this.game.phase==='playing';const side=$('handedness').value==='left'?-1:1;this.bowHolder.position.copy(headP).add(new T.Vector3(side*.24,-.22,-.48).applyQuaternion(headQ));this.bowHolder.quaternion.copy(headQ);this.visualBow.group.rotation.z=side*-.12;}
   const string=this.visualBow.string.geometry.attributes.position;string.setXYZ(1,0,0,.11+this.charge*.55);string.needsUpdate=true;this.visualArrow.visible=this.charge>.01;this.visualArrow.position.set(.025,0,-.04+this.charge*.4);this.visualArrow.quaternion.identity();
   // Show the physical draw hand as the pulled nock, independent of bow pose.
   if(this.xr&&hand&&this.drawHeld){const draw=this.hands[$('handedness').value==='left'?'right':'left'];if(draw){const local=this.bowHolder.worldToLocal(new T.Vector3(...draw.p));string.setXYZ(1,local.x,local.y,local.z);string.needsUpdate=true;const dir=new T.Vector3(0,0,.09).sub(local).normalize();this.visualArrow.position.copy(local).addScaledVector(dir,.32);this.visualArrow.quaternion.setFromUnitVectors(new T.Vector3(0,0,-1),dir);}}
  },
  teleportPreview(){const T=this.T;this.teleLine.visible=this.teleRing.visible=false;if(this.game.type!=='blink'||this.charge<.08||this.paused||!this.running)return;let origin,dir;
   if(this.xr&&this.latch.sample){origin=[...this.latch.sample.origin];dir=this.latch.sample.direction;}else if(!this.xr){origin=this.head.object3D.getWorldPosition(new T.Vector3()).toArray();dir=new T.Vector3(0,0,-1).applyQuaternion(this.head.object3D.getWorldQuaternion(new T.Quaternion())).toArray();}else return;
   const points=[],p=[...origin],v=C.mul(dir,7+this.charge*10);let dest=null;for(let i=0;i<48;i++){points.push([...p]);const old=[...p];v[1]-=C.G*.065;for(let k=0;k<3;k++)p[k]+=v[k]*.065;if(C.segmentBlocked(this.game.world,old,p))break;if(p[1]<=.02){const t=(old[1]-.02)/(old[1]-p[1]);dest=C.add(old,C.mul(C.sub(p,old),t));break;}}
   const a=this.teleLine.geometry.attributes.position;points.forEach((p,i)=>a.setXYZ(i,...p));a.needsUpdate=true;this.teleLine.geometry.setDrawRange(0,points.length);this.teleLine.visible=true;if(dest){const ok=C.walkable(this.game.world,dest,.42);this.teleRing.material=this.art.mat(ok?'#91edd0':'#f19b7d',0,true);this.teleRing.position.set(dest[0],.045,dest[2]);this.teleRing.visible=true;}
  },
  visuals(){const s=this.game;this.enemyMeshes.forEach((m,i)=>{const e=s.world.enemies[i];m.visible=!e.dead;if(e.dead)return;m.position.set(e.p[0],e.p[1]+Math.sin(s.time*2+i)*.06,e.p[2]);m.rotation.y=Math.atan2(s.p[0]-e.p[0],s.p[2]-e.p[2]);m.scale.setScalar((e.kind==='warden'?1.3:1)*(e.wind>0?1.05:1));});this.pickupMeshes.forEach((m,i)=>{const p=s.world.pickups[i];m.visible=!p.taken;m.position.set(p.p[0],p.p[1]+.12+Math.sin(s.time*2+i)*.06,p.p[2]);m.rotation.y=s.time*.6;});
   this.arrowPool.forEach((m,i)=>{const a=s.arrows[i];m.visible=!!a;if(a){m.position.set(...a.p);m.quaternion.setFromUnitVectors(new this.T.Vector3(0,0,-1),new this.T.Vector3(...a.v).normalize());}});this.boltPool.forEach((m,i)=>{const p=s.bolts[i];m.visible=!!p;if(p)m.position.set(...p.p);});this.sparkPool.forEach((m,i)=>{const p=s.sparks[i];m.visible=!!p;if(p){m.position.set(...p.p);m.scale.setScalar(Math.max(.1,p.life*4));m.rotation.set(s.time*3,s.time*4,0);}});
   this.worldArt.gate.rotation.z=s.portalReady?s.time*.2:0;this.worldArt.gate.children.forEach(m=>m.material=this.art.mat(s.portalReady?'#96e8d0':'#53667b',0,true));this.bowVisual();this.teleportPreview();
   for(const e of s.events.filter(e=>e.seq>this.lastEvent)){if(e.type==='hurt'){this.sound(100,.25,.04);this.toast('Hit · find cover or move from the incoming shot.');}if(e.type==='kill'){this.sound(740,.3,.06);this.toast('Warden silenced. +'+(e.kind==='warden'?'250':'100'));}if(e.type==='gate-open'&&!this.practice)this.toast('The beacon opens. Follow the green mark on your map.');if(e.type==='target')this.toast('A clear note. Practice target '+(e.id+1));if(e.type==='pickup')this.toast(e.kind==='health'?'Vitality restored.':e.kind+' arrows replenished.');if(e.type==='blink'){const local=this.head.object3D.position.clone().applyQuaternion(this.rig.quaternion);this.rig.position.set(s.p[0]-local.x,0,s.p[2]-local.z);$('fade').style.opacity='.95';clearTimeout(this.fadeTimer);this.fadeTimer=setTimeout(()=>$('fade').style.opacity='0',100);}}
   this.lastEvent=s.eventSeq||0;
  },
  hud(){const s=this.game,remaining=s.world.enemies.filter(e=>!e.dead).length;$('health').textContent=Math.ceil(s.health);$('health-bar').style.width=(s.health/s.maxHealth*100)+'%';$('score').textContent=s.score;$('chapter').textContent=`SECTOR ${s.world.depth} · ${BIOMES[(s.world.depth-1)%3]}`;$('objective').textContent=this.practice?'Practice · ring three targets':s.portalReady?'Find the open beacon':'Silence the wardens';$('tally').textContent=this.practice?`${s.targets.size} / 3 targets`:`${remaining} wardens remain`;$('draw-meter').querySelector('i').style.width=(this.charge*100)+'%';$('draw-meter').querySelector('span').textContent=this.drawHeld?'RELEASE TO LOOSE':'HOLD TO DRAW';for(const b of document.querySelectorAll('[data-arrow]')){b.classList.toggle('selected',b.dataset.arrow===s.type);b.querySelector('b').textContent=s.ammo[b.dataset.arrow]??'∞';}
   $('touch').hidden=this.xr||!this.running||this.paused||!matchMedia('(pointer: coarse)').matches;if(!$('touch').hidden)$('touch').style.display='flex';
   const map=$('map'),g=map.getContext('2d');if(!map.hidden){g.clearRect(0,0,240,220);const f=p=>[120+p[0]*3.4,38-p[2]*3.4];g.strokeStyle='#b9a983';g.lineWidth=3;for(const [a,b]of s.world.edges){const r=s.world.rooms[a],q=s.world.rooms[b];g.beginPath();g.moveTo(...f([r.x,0,r.z]));g.lineTo(...f([q.x,0,q.z]));g.stroke();}for(const r of s.world.rooms){const p=f([r.x,0,r.z]);g.fillStyle=r.id===s.world.exit?'#70bca6':'#5c6d88';g.fillRect(p[0]-17,p[1]-17,34,34);}for(const e of s.world.enemies)if(!e.dead){g.fillStyle='#e4a490';g.beginPath();g.arc(...f(e.p),4,0,7);g.fill();}g.fillStyle='#f7ead0';g.beginPath();g.arc(...f(s.p),4,0,7);g.fill();}
   if(this.xr){const {ctx:g,canvas:c,texture}=this.xrHud;g.fillStyle='#172638ee';g.fillRect(0,0,c.width,c.height);g.fillStyle='#e8d4aa';g.font='28px Georgia';g.textAlign='center';g.fillText(`SECTOR ${s.world.depth}   ·   VITALITY ${Math.ceil(s.health)}   ·   ${s.type.toUpperCase()} ${s.ammo[s.type]??'∞'}`,512,46);g.font='24px Arial';g.fillStyle='#bbdace';g.fillText(this.paused?'Use the spatial menu':this.practice?'Practice: '+s.targets.size+' / 3 targets':s.portalReady?'Beacon open · bow-hand X near it':`${remaining} wardens remain · bow-hand Y: menu`,512,90);g.font='20px Arial';g.fillText(this.xrNotice||'',512,137);g.fillStyle='#547981';g.fillRect(250,158,524,7);g.fillStyle='#e4c186';g.fillRect(250,158,524*this.charge,7);texture.needsUpdate=true;this.xrHud.mesh.visible=this.running&&!this.paused;}
  },
  tick(time,delta){if(!this.rendererReady)return;const dt=Math.min(.04,delta/1000||0);this.scene.object3D.updateMatrixWorld(true);const head=this.head.object3D.getWorldPosition(new this.T.Vector3());this.headBlocked=this.game.world.solids.some(b=>head.x>b.min[0]-.06&&head.x<b.max[0]+.06&&head.y>b.min[1]&&head.y<b.max[1]&&head.z>b.min[2]-.06&&head.z<b.max[2]+.06);
   if(this.xr){this.blackout.material.opacity=this.headBlocked?.98:0;this.processXR(dt,head);}else this.desktop(dt);
   if(this.running&&!this.paused&&this.game.phase==='playing'&&!document.hidden){
    const currentHead=this.head.object3D.getWorldPosition(new this.T.Vector3());
    if(this.xr&&!this.headBlocked&&C.walkable(this.game.world,[currentHead.x,0,currentHead.z])){this.game.p[0]=currentHead.x;this.game.p[2]=currentHead.z;}
    this.game.head=currentHead.toArray();this.accumulator=Math.min(.12,this.accumulator+dt);while(this.accumulator>=1/90){C.step(this.game,1/90,this.game.head);this.accumulator-=1/90;}
    if(this.game.phase!==this.lastPhase){this.bank();this.lastPhase=this.game.phase;this.paused=true;this.cancel();this.menuUI();if(this.xr)this.placePanel();}
   }
   this.visuals();if(time-this.lastHud>80){this.hud();this.lastHud=time;this.stats.drawCalls=this.scene.renderer.info.render.calls;this.stats.triangles=this.scene.renderer.info.render.triangles;}
  },
  // A-Frame owns play/pause lifecycle hooks; game menus must not remove tick.
  pause(){if(this.rendererReady)this.setPaused(true);},
  remove(){clearTimeout(this.toastTimer);clearTimeout(this.fadeTimer);this.audio?.close();}
 });
 window.addEventListener('error',e=>{const s=$('status');if(s)s.textContent='The game could not finish loading. '+e.message;});
})();
