/* Resonant Hunt / tracked physical interactions and diegetic UI.
 * Only the simulation clock slows; headset and controller poses stay live.
 * Browser/Xbox retain their complete menus and explicit reload fallback. */
(function(root){'use strict';
 function install(g){
  const T=g.T,C=VesperCore,M=RitualModel,$=id=>document.getElementById(id),types=['plain','cinder','frost','blink','volley','ricochet'],labels=['Standard','Cinder','Frost','Blink','Volley','Ricochet'],colors=['#ecd8af','#f3a568','#9adeee','#9be4ca','#d7b3e9','#d2e0fa'];
  const focus=new M.Focus(),reload=new M.ReloadGesture(),state={source:null,selected:0,palm:false,pull:null,target:null,busy:false,seenGame:null,clock:0,wristAt:0,hudAt:-1,lastHand:null,tip:'',reloadProgress:0};
  const panel=g.makePanel(768,384,.46,.23),quiver=g.makePanel(768,768,.72,.72);panel.mesh.name='Palm familiar / non-regenerating vitality';panel.mesh.material.depthTest=true;panel.mesh.renderOrder=50;panel.mesh.visible=false;quiver.mesh.name='Physical tactical quiver';quiver.mesh.visible=false;g.scene.object3D.add(panel.mesh,quiver.mesh);
  const familiar=new T.Group();familiar.name='Wrist lantern familiar';const gem=new T.Mesh(new T.OctahedronGeometry(.027),new T.MeshStandardMaterial({color:'#b3e8db',emissive:'#3b8e87',emissiveIntensity:.75,metalness:.3,roughness:.22}));familiar.add(gem);const ring=new T.Mesh(new T.TorusGeometry(.048,.002,4,32),new T.MeshBasicMaterial({color:'#ccb480',transparent:true,opacity:.8}));ring.rotation.x=Math.PI/2;familiar.add(ring);familiar.visible=false;g.scene.object3D.add(familiar);
  const targetRing=new T.Mesh(new T.TorusGeometry(.25,.012,4,30),new T.MeshBasicMaterial({color:'#b4f6d4',transparent:true,opacity:.8,depthWrite:false}));targetRing.visible=false;g.scene.object3D.add(targetRing);
  const tether=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineBasicMaterial({color:'#b4f6d4',transparent:true,opacity:.55}));tether.frustumCulled=false;tether.visible=false;g.scene.object3D.add(tether);
  const handle=g.art.mesh('box','#bea47a',g.arsenal.crossbow,0,.085,.07,.12,.035,.04);handle.name='Tracked crossbow winding handle';
  const prefs=document.createElement('fieldset');prefs.className='resonance-settings';prefs.innerHTML='<legend>Physical rituals / comfort</legend><label>Headset status <select id="wrist-display"><option value="palm">Palm-up familiar / no fixed HUD</option><option value="always">Always show the wrist display</option><option value="compact">Accessible compact HUD</option></select></label><label>Pickup interaction <select id="pickup-mode"><option value="pull">Point free hand / hold trigger to pull</option><option value="near">Proximity collection / accessible</option></select></label><label>Tactical quiver <select id="focus-slow"><option value="slow">Slow simulation / 3-second focus reserve</option><option value="real">Real-time selection</option></select></label><p>Quest: weapon trigger fires the crossbow. Hold the free-hand trigger near its rear handle, pull back 22 cm, then release to reload. Short draw uses 13 cm. Free-hand grip shields; weapon-hand grip shard-steps. Hold the free-hand lower face button for the quiver. Xbox: hold Y; use a stick or D-pad to select; release to equip. Keyboard: hold Tab. Room-scale poses never slow down.</p>';
  document.querySelector('.resonance-settings').after(prefs);
  const wheel=document.createElement('section');wheel.id='ritual-quiver';wheel.hidden=true;wheel.setAttribute('aria-label','Tactical arrow selection');wheel.innerHTML='<div class="quiver-disc"><h2>Tactical quiver</h2><p id="quiver-focus"></p><div id="quiver-options"></div><p>Stick or D-pad selects. Release Y / Tab to equip. B / Escape cancels.</p><button id="quiver-close">Cancel selection</button></div>';document.body.append(wheel);
  for(let i=0;i<types.length;i++){const b=document.createElement('button');b.dataset.ritualType=types[i];b.onclick=()=>{state.selected=i;close(true);};$('quiver-options').append(b);}
  $('quiver-close').onclick=()=>close(false);const openButton=document.createElement('button');openButton.id='quiver-button';openButton.textContent='Tab / Y - Tactical quiver';openButton.onclick=()=>focus.open?close(false):begin('touch');$('combat-tools').append(openButton);
  const active=()=>g.running&&!g.paused&&g.game.phase==='playing';
  function available(type){const s=g.game;return !(g.arMode&&type==='blink')&&(type!=='volley'||s.volleyUnlocked)&&(type!=='ricochet'||s.ricochetUnlocked)&&(!(type in s.ammo)||s.ammo[type]>0);}
  function reset(){focus.open=false;state.source=null;state.pull=null;state.target=null;state.busy=false;state.palm=false;state.reloadProgress=0;reload.reset();wheel.hidden=true;panel.mesh.visible=false;quiver.mesh.visible=false;targetRing.visible=false;tether.visible=false;familiar.visible=false;}
  const cancel=g.cancel.bind(g);g.cancel=function(){cancel();reset();};
  function begin(source,next=false){if(!active())return false;g.cancel();focus.open=true;state.source=source;state.selected=(Math.max(0,types.indexOf(g.game.type))+(next?1:0))%types.length;C.emit(g.game,'focus-open');drawQuiver();return true;}
  function close(commit){if(!focus.open)return;const type=types[state.selected];g.cancel();if(commit&&available(type)){g.setType(type);C.emit(g.game,'focus-select',{arrow:type});}else if(commit){g.toast('That arrow is empty or locked. Your previous arrow remains selected.');g.soundscape?.cue('denied');}}
  function select(index){if(index===state.selected)return;state.selected=(index+types.length)%types.length;g.soundscape?.cue('ui',null,{volume:.7});drawQuiver();}
  function drawQuiver(){
   const s=g.game,{ctx,canvas,texture}=quiver;ctx.clearRect(0,0,768,768);ctx.fillStyle='rgba(13,28,40,.94)';ctx.beginPath();ctx.arc(384,384,362,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b99c66';ctx.lineWidth=4;ctx.stroke();
   for(let i=0;i<types.length;i++){const a=i*Math.PI/3-Math.PI/2,x=384+Math.cos(a)*235,y=384+Math.sin(a)*235,on=state.selected===i,ok=available(types[i]);ctx.fillStyle=on?'#41666b':'#263c4c';ctx.beginPath();ctx.arc(x,y,101,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ok?colors[i]:'#69747e';ctx.lineWidth=on?5:1;ctx.stroke();ctx.textAlign='center';ctx.fillStyle=ok?colors[i]:'#8a949b';ctx.font='30px Georgia';ctx.fillText(labels[i],x,y-9,184);ctx.font='23px Arial';ctx.fillText(!ok?'EMPTY / LOCKED':types[i] in s.ammo?s.ammo[types[i]]+' arrows':'UNLIMITED',x,y+30,182);}
   ctx.textAlign='center';ctx.fillStyle='#eadcbd';ctx.font='29px Georgia';ctx.fillText('FOCUS',384,355);ctx.font='24px Arial';ctx.fillText(focus.slow&&focus.remaining>0?focus.remaining.toFixed(1)+' s reserve':'REAL TIME',384,392);ctx.font='19px Arial';ctx.fillText('Release to equip',384,426);texture.needsUpdate=true;
   $('quiver-focus').textContent=focus.slow&&focus.remaining>0?'Focus '+focus.remaining.toFixed(1)+' seconds. The world moves at 20% speed.':'The world is moving in real time.';
   for(const b of wheel.querySelectorAll('[data-ritual-type]')){const i=types.indexOf(b.dataset.ritualType);b.textContent=labels[i]+' / '+(available(types[i])?(s.ammo[types[i]]??'unlimited'):'empty or locked');b.classList.toggle('selected',i===state.selected);b.setAttribute('aria-pressed',String(i===state.selected));}
  }
  function padInput(dt,b,edge,pad){if(edge(3)&&!focus.open)begin('pad',true);if(!focus.open||state.source!=='pad')return false;
   if(edge(1)||edge(4)){close(false);return true;}if(edge(0)||!b[3]){close(true);return true;}
   const x=Math.abs(pad.axes[2]||0)>.3?pad.axes[2]:pad.axes[0]||0,y=Math.abs(pad.axes[3]||0)>.3?pad.axes[3]:pad.axes[1]||0;select(M.radialIndex(x,y,types.length,state.selected));if(edge(15))select(state.selected+1);if(edge(14))select(state.selected-1);if(edge(12))select(state.selected-1);if(edge(13))select(state.selected+1);g.drawHeld=false;C.shield(g.game,null);return true;
  }
  function xrInput(dt,bow,draw,rise,bowName,drawName){if(rise(drawName,4)&&!focus.open)begin('xr');if(!focus.open||state.source!=='xr')return false;
   if(draw.buttons[5]||bow.buttons[4]){close(false);return true;}if(!draw.buttons[4]){close(true);return true;}
   select(M.radialIndex(draw.axes.length>=4?draw.axes[2]:draw.axes[0]||0,draw.axes.at(-1)||0,types.length,state.selected));g.latch.reset();g.drawHeld=false;g.charge=0;C.shield(g.game,null);return true;
  }
  function ray(hand){let p=new T.Vector3(...hand.p),q=hand.q;const ref=g.scene.renderer.xr.getReferenceSpace(),pose=hand.source.targetRaySpace&&g.scene.frame?.getPose(hand.source.targetRaySpace,ref);if(pose){p.set(pose.transform.position.x,pose.transform.position.y,pose.transform.position.z).applyMatrix4(g.rig.matrixWorld);q=g.rig.getWorldQuaternion(new T.Quaternion()).multiply(new T.Quaternion().copy(pose.transform.orientation));}return {p,d:new T.Vector3(0,0,-1).applyQuaternion(q)};}
  function candidate(hand,handName){const r=ray(hand),palm=new T.Vector3(...M.palmNormal(hand.q,handName));let best=null,alignment=.965;for(let i=0;i<g.game.world.pickups.length;i++){const p=g.game.world.pickups[i];if(p.taken)continue;const delta=new T.Vector3(...p.p).sub(r.p),distance=delta.length();if(distance>7||distance<.06)continue;delta.normalize();const score=Math.max(delta.dot(r.d),delta.dot(palm)-.035);if(score<alignment||C.segmentBlocked(g.game.world,hand.p,p.p,.015))continue;alignment=score;best=i;}return best;}
  function interactXR(dt,bow,draw,rise,bowName,drawName){
   state.busy=false;state.target=null;if(!active()||g.headBlocked||g.game.shield||focus.open){state.pull=null;reload.reset();state.reloadProgress=0;return false;}
   const local=new T.Vector3(...draw.p).sub(new T.Vector3(...bow.p)).applyQuaternion(bow.q.clone().invert());
   if($('pickup-mode').value==='pull'&&!g.latch.drawing&&!reload.grabbed){state.target=candidate(draw,drawName);
    const nearNock=local.distanceTo(new T.Vector3(0,0,.09))<.25;
    if(rise(drawName,0)&&state.target!==null&&!nearNock){const p=g.game.world.pickups[state.target];state.pull={index:state.target,origin:[...p.p],point:[...p.p],progress:0};C.emit(g.game,'pickup-pull',{p:[...p.p]});g.latch.reset();}
   }
   if(state.pull){const pull=state.pull,p=g.game.world.pickups[pull.index];state.busy=true;if(!p||p.taken||!draw.buttons[0]||C.len(C.sub(pull.origin,draw.p))>7.5||C.segmentBlocked(g.game.world,pull.origin,draw.p,.02)){state.pull=null;state.busy=false;return false;}
    const v=C.sub(draw.p,pull.point),dist=C.len(v),travel=Math.min(dist,dt*5.2);pull.point=C.add(pull.point,C.mul(C.unit(v),travel));pull.progress=1-Math.min(1,C.len(C.sub(pull.point,draw.p))/(C.len(C.sub(pull.origin,draw.p))||1));state.target=pull.index;
    if(dist<.22){C.collectPickup(g.game,pull.index,draw.p,7);state.pull=null;state.target=null;state.busy=true;}return true;
   }
   const result=reload.update(local.toArray(),draw.buttons[0],g.game.weapon==='crossbow'&&!g.game.crossbow.loaded&&g.game.crossbow.reload===0,Number($('draw-length').value)<.5);state.reloadProgress=result.progress;state.busy=result.active;
   if(result.start){C.emit(g.game,'reload-grab');g.latch.reset();}if(result.complete){C.reload(g.game,true);state.busy=true;}
   return state.busy;
  }
  function prepare(dt){const s=g.game;if(state.seenGame!==s){reset();state.seenGame=s;focus.remaining=3;}state.clock+=dt;s.manualPickups=!!g.xr&&$('pickup-mode').value==='pull';focus.slow=$('focus-slow').value==='slow';focus.update(dt,active());if(g.xr&&(!g.hands.left||!g.hands.right)){state.pull=null;reload.reset();state.busy=false;}
   if(focus.open&&state.clock-state.wristAt>.1){drawQuiver();state.wristAt=state.clock;}
  }
  function wrist(){
   const s=g.game,mode=$('wrist-display').value,off=$('handedness').value==='left'?'right':'left',hand=g.hands[off],eye=g.head.object3D.getWorldPosition(new T.Vector3()),q=g.head.object3D.getWorldQuaternion(new T.Quaternion()),forward=new T.Vector3(0,0,-1).applyQuaternion(q);
   if(!g.xr||!active()||!hand||focus.open||s.shield||g.latch.drawing||state.busy){panel.mesh.visible=familiar.visible=false;state.palm=false;return;}
   state.palm=M.palmVisible(hand.p,hand.q,off,eye.toArray(),forward.toArray(),state.palm);panel.mesh.visible=(mode==='always'||mode==='palm'&&state.palm);familiar.visible=panel.mesh.visible;
   const normal=new T.Vector3(...M.palmNormal(hand.q,off));panel.mesh.position.set(...hand.p).addScaledVector(normal,.14).add(new T.Vector3(0,.1,0));panel.mesh.quaternion.copy(q);familiar.position.set(...hand.p).addScaledVector(normal,.095);gem.rotation.set(state.clock*.7,state.clock,0);ring.rotation.z=state.clock*.35;
   if(!panel.mesh.visible||state.clock-state.hudAt<.10)return;state.hudAt=state.clock;const {ctx,texture}=panel;ctx.clearRect(0,0,768,384);ctx.fillStyle='rgba(16,34,45,.93)';ctx.fillRect(8,8,752,368);ctx.strokeStyle='#b8a576';ctx.lineWidth=5;ctx.strokeRect(10,10,748,364);ctx.fillStyle='#ecdfbd';ctx.textAlign='center';ctx.font='28px Georgia';ctx.fillText('THE BELL REMEMBERS',384,52);ctx.font='47px Georgia';ctx.fillStyle=s.health<s.maxHealth*.25?'#f1aa90':'#c0edcf';ctx.fillText('HP '+Math.ceil(s.health)+' / '+s.maxHealth,384,113);ctx.font='28px Arial';ctx.fillStyle='#d2dee2';ctx.fillText('SCORE '+s.score+'    RENOWN '+g.profile.shards,384,163);ctx.fillText('GUARD '+Math.ceil(s.guard)+'    SHARDS '+s.shardCharges+'/'+s.maxShards,384,211);ctx.fillStyle='#eadbc0';ctx.fillText(s.type.toUpperCase()+' '+(s.ammo[s.type]??'unlimited'),384,257);ctx.font='21px Arial';ctx.fillStyle='#9ecbc7';ctx.fillText((g.soundscape?.caption||s.weapon==='crossbow'?(g.soundscape?.caption||(s.crossbow.loaded?'CROSSBOW READY':'PULL REAR HANDLE TO RELOAD')):'Raise your palm to remember.').slice(0,68),384,310,714);ctx.fillText('Hold free-hand lower face button: quiver',384,348,710);texture.needsUpdate=true;
  }
  function render(){
   wrist();wheel.hidden=g.xr||!focus.open;quiver.mesh.visible=g.xr&&focus.open&&active();
   if(quiver.mesh.visible){const hand=g.hands[$('handedness').value==='left'?'right':'left'],q=g.head.object3D.getWorldQuaternion(new T.Quaternion()),eye=g.head.object3D.getWorldPosition(new T.Vector3());quiver.mesh.position.copy(hand?new T.Vector3(...hand.p):eye).add(new T.Vector3(0,.22,-.35).applyQuaternion(q));if(quiver.mesh.position.distanceTo(eye)<.5)quiver.mesh.position.copy(eye).add(new T.Vector3(0,-.15,-.6).applyQuaternion(q));quiver.mesh.quaternion.copy(q);}
   if(g.xr&&$('wrist-display').value!=='compact'){g.xrHud.mesh.visible=false;for(const m of g.enemyMeshes){const plate=m.userData.hunt?.plate||m.userData.dominion?.plate;if(plate)plate.visible=false;}}
   const target=state.target===null?null:g.game.world.pickups[state.target];targetRing.visible=!!target&&!target.taken&&active()&&g.xr;targetRing.quaternion.copy(g.head.object3D.getWorldQuaternion(new T.Quaternion()));if(target)targetRing.position.set(...target.p);
   tether.visible=!!state.pull&&g.xr;const pull=state.pull,hand=g.hands[$('handedness').value==='left'?'right':'left'];if(pull&&hand){const m=g.pickupMeshes[pull.index];if(m)m.position.set(...pull.point);const a=tether.geometry.attributes.position;a.setXYZ(0,...pull.point);a.setXYZ(1,...hand.p);a.needsUpdate=true;targetRing.position.set(...pull.point);}
   handle.position.z=.07+state.reloadProgress*.22;
  }
  const visual=g.visuals.bind(g);g.visuals=function(){visual();render();};const hud=g.hud.bind(g);g.hud=function(){hud();if(g.xr&&$('wrist-display').value!=='compact')g.xrHud.mesh.visible=false;};
  function keydown(e){if(g.xr||!active()||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Tab'){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat&&!focus.open)begin('keyboard');}else if(focus.open){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();close(false);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();if(e.code==='Enter')close(true);else select(state.selected+(['ArrowLeft','ArrowUp'].includes(e.code)?-1:1));}}}
  function keyup(e){if(e.code==='Tab'&&state.source==='keyboard'){e.preventDefault();close(true);}}
  function wheelInput(e){if(!focus.open)return;e.preventDefault();select(state.selected+(e.deltaY>0?1:-1));}
  document.addEventListener('keydown',keydown,true);document.addEventListener('keyup',keyup,true);wheel.addEventListener('wheel',wheelInput,{passive:false});
  const pause=g.setPaused.bind(g);g.setPaused=function(value){reset();pause(value);};const remove=g.remove.bind(g);g.remove=function(){document.removeEventListener('keydown',keydown,true);document.removeEventListener('keyup',keyup,true);wheel.remove();for(const object of[panel.mesh,quiver.mesh,familiar,targetRing,tether]){object.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});object.removeFromParent();}remove();};
  return {state,focus,reload,panel,quiver,familiar,prepare,render,padInput,xrInput,interactXR,begin,close,available,get busy(){return state.busy;},timeScale:()=>focus.scale,desktopInput:()=>focus.open};
 }
 root.ResonanceRitual=Object.freeze({install});
})(globalThis);
