/* The canonical plan is read-only; browser edits are explicitly local. */
(async()=>{'use strict';const $=id=>document.getElementById(id),KEY='vesperfall-roadmap-v1';let edits={},nextOnly=false;
 try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))edits=raw;}catch{}
 const response=await fetch('./roadmap.json',{cache:'no-store'});if(!response.ok)throw Error('The committed roadmap could not be loaded.');const data=await response.json(),statuses=data.statuses;
 if(!Array.isArray(data.tasks)||!Array.isArray(statuses))throw Error('Unsupported roadmap format.');
 const known=new Set(data.tasks.map(t=>t.id));edits=Object.fromEntries(Object.entries(edits).filter(([id,s])=>known.has(id)&&statuses.includes(s)));
 $('revision').textContent='v'+data.version+' / '+data.updated+' / committed source';
 function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
 for(const [number,label] of [[data.tasks.length,'Tracked tasks'],[data.tasks.filter(t=>t.status==='Implemented').length,'Software tasks implemented'],[data.tasks.filter(t=>t.status==='Hardware QA').length,'Open physical-device gates'],[data.milestones.length,'Production milestones']]){const x=el('div',undefined,'metric');x.append(el('strong',number),el('span',label));$('summary').append(x);}
 for(const m of data.milestones){const box=el('article',undefined,'milestone');box.append(el('span',m.id+' / '+m.status),el('h3',m.name),el('p',m.goal),el('p','Exit gate: '+m.exit),el('p','Depends on: '+(m.depends.join(', ')||'Foundation')));$('milestones').append(box);const option=el('option',m.id+' / '+m.name);option.value=m.id;$('milestone').append(option);}
 for(const area of [...new Set(data.tasks.map(t=>t.area))].sort()){const o=el('option',area);o.value=area;$('area').append(o);}
 for(const r of data.releaseGates){const box=el('article');box.append(el('h3',r[0]+' / '+r[1]),el('p',r[3]),el('p',r[6]+' / '+r[5]));$('gate-list').append(box);}
 function visible(t){return (!$('search').value||JSON.stringify(t).toLowerCase().includes($('search').value.toLowerCase()))&&(!$('milestone').value||t.milestone===$('milestone').value)&&(!$('priority').value||t.priority===$('priority').value)&&(!$('area').value||t.area===$('area').value)&&(!nextOnly||data.nextRelease.focus.includes(t.id));}
 function draw(restoreId){$('board').replaceChildren();let count=0;for(const status of statuses){const tasks=data.tasks.filter(t=>($('view').value==='local'&&edits[t.id]||t.status)===status&&visible(t)).sort((a,b)=>a.priority.localeCompare(b.priority)||Number(a.id.slice(1))-Number(b.id.slice(1)));count+=tasks.length;const col=el('section',undefined,'column');col.append(el('h2',status+' / '+tasks.length));
   for(const t of tasks){const card=el('article');card.dataset.task=t.id;card.append(el('span',t.id+' / '+t.priority+' / '+t.milestone+' / '+t.area,'tag'),el('h3',t.title));for(const [label,text] of [['Why',t.why],['Acceptance',t.gate],['Depends on',t.depends.join(', ')||'No task prerequisite'],['Owner role',t.owner+' (assignment pending)'],['Evidence level',t.verification]]){const p=el('p');p.append(el('strong',label+': '),document.createTextNode(text));card.append(p);}
    if(t.evidence.length){const links=el('div');for(const path of t.evidence){if(!/^[\w./-]+$/.test(path)||path.includes('..'))continue;const a=el('a',path);a.href='./'+path;links.append(a);}card.append(links);}
    const label=el('label','Local status only'),select=el('select');select.id='task-'+t.id;select.setAttribute('aria-label','Local status for '+t.id);for(const s of statuses)select.append(el('option',s));select.value=edits[t.id]||t.status;select.onchange=()=>{edits[t.id]=select.value;try{localStorage.setItem(KEY,JSON.stringify(edits));$('status').textContent='Local edit saved. GitHub and the workbook are unchanged.';}catch{$('status').textContent='Local storage unavailable. Export your board to retain edits.';}$('view').value='local';draw(select.id);};label.append(select);card.append(label);col.append(card);
   }if(!tasks.length)col.append(el('p','No matching tasks.','empty'));$('board').append(col);
  }$('shown').textContent=count+' of '+data.tasks.length+' tasks shown'+(nextOnly?' / next combat slice':'');if(restoreId)$(restoreId)?.focus({preventScroll:true});}
 for(const id of ['search','milestone','priority','area','view'])$(id).addEventListener(id==='search'?'input':'change',()=>draw());
 function clear(){for(const id of ['search','milestone','priority','area'])$(id).value='';nextOnly=false;}
 $('clear').onclick=()=>{clear();draw();};$('next').onclick=()=>{clear();nextOnly=true;draw();};$('reset').onclick=()=>{edits={};try{localStorage.removeItem(KEY);}catch{}$('view').value='committed';$('status').textContent='Local status edits reset. Committed data and game saves are unchanged.';draw();};
 $('export').onclick=()=>{const exportData={...data,localPlanningExport:true,sourceVersion:data.version,tasks:data.tasks.map(t=>({...t,status:edits[t.id]||t.status,committedStatus:t.status}))};const url=URL.createObjectURL(new Blob([JSON.stringify(exportData,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='Vesperfall-local-production-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Exported a local planning copy, not a GitHub update.';};
 draw();window.VesperProduction=Object.freeze({version:data.version,taskCount:data.tasks.length,committed:data});
 // Standalone board navigation; does not read or write the game profile.
 let previous=[],armed=false,last=0,connected=false;
 function focusables(){return [...document.querySelectorAll('a,button,input,select,summary')].filter(x=>!x.disabled&&x.getClientRects().length);}
 function padTick(t){const p=[...(navigator.getGamepads?.()||[])].find(x=>x?.connected&&x.mapping==='standard');if(p){const b=p.buttons.map(x=>!!x.pressed||x.value>.5),edge=i=>b[i]&&!previous[i];if(!connected){$('play').focus();connected=true;}if(!b.some(Boolean)&&p.axes.every(x=>Math.abs(x)<.25))armed=true;if(armed){const a=focusables(),current=document.activeElement,i=a.indexOf(current);if(edge(12)||edge(13)){const dir=edge(13)?1:-1;a[(i+dir+a.length)%a.length]?.focus();}if((edge(14)||edge(15))&&current?.tagName==='SELECT'){const dir=edge(15)?1:-1;current.selectedIndex=(current.selectedIndex+dir+current.options.length)%current.options.length;current.dispatchEvent(new Event('change',{bubbles:true}));}if(edge(0)){if(current?.tagName==='SELECT'){current.selectedIndex=(current.selectedIndex+1)%current.options.length;current.dispatchEvent(new Event('change',{bubbles:true}));}else current?.click();}if(edge(1))location.assign('./index.html');if(t-last>40){if(b[7])window.scrollBy(0,48);if(b[6])window.scrollBy(0,-48);last=t;}}previous=b;}else{previous=[];armed=false;connected=false;}requestAnimationFrame(padTick);}
 requestAnimationFrame(padTick);
})().catch(e=>{document.getElementById('status').textContent=e.message;});
