/* Rosefire: reversible presentation-only extension. It never writes gameplay,
 * collision, score, checkpoints, audio, camera poses or the XR framebuffer. */
(function(){'use strict';const S=RosefireShaders,KEY='vesperfall-rosefire-v1';
 AFRAME.registerComponent('rosefire',{
  dependencies:['vesper-game','jewelglass'],
  init(){this.g=this.el.components['vesper-game'];this.T=AFRAME.THREE;this.started=false;this.disposed=false;},
  setup(){const T=this.T,g=this.g,j=g.jewelglass;if(this.started||!j?.started)return;this.started=true;this.j=j;this.world=null;this.lastEvent=0;this.lastSources=-1;this.patched=new Map();this.sources=[];this.errors=[];this.stats={builds:0,compiled:0,wakes:0,activeWakes:0,patchedMaterials:0,renderTargets:0};this.v=new T.Vector3();
   let raw={};try{raw=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{}this.options=S.settings(raw);
   this.uniforms={uRFTime:{value:0},uRFWet:{value:0},uRFRose:{value:0},uRFAnimated:{value:0},uRFDetail:{value:0},uRFPlayer:{value:new T.Vector3()},uRFSources:{value:Array.from({length:4},()=>new T.Vector4())}};
   this.sky=new T.ShaderMaterial({name:'Rosefire / twilight veil',vertexShader:S.skyVertex,fragmentShader:S.skyFragment,uniforms:{uTime:{value:0},uNight:{value:0},uCalm:{value:1},uDetail:{value:0}},side:T.BackSide,depthWrite:false});this.originalSky=j.sky.material;
   this.ward=new T.ShaderMaterial({name:'Rosefire / woven Wardglass',vertexShader:JewelShaders.vertex,fragmentShader:S.ward,uniforms:j.shieldMat.uniforms,transparent:true,depthWrite:false,depthTest:true,side:T.DoubleSide});
   this.root=new T.Group();this.root.name='Rosefire / bounded teleport wakes';this.el.object3D.add(this.root);this.wakeGeometry=new T.PlaneGeometry(2,2);this.wakes=Array.from({length:6},()=>{const material=new T.ShaderMaterial({name:'Rosefire / landing echo',vertexShader:JewelShaders.vertex,fragmentShader:S.wake,uniforms:{uAge:{value:2},uColor:{value:new T.Color('#77e7d6')}},transparent:true,depthTest:true,depthWrite:false,blending:T.AdditiveBlending});const mesh=new T.Mesh(this.wakeGeometry,material);mesh.rotation.x=-Math.PI/2;mesh.visible=false;mesh.name='Rosefire / actual landing only';this.root.add(mesh);return {mesh,born:-10};});this.wakeIndex=0;
   this.makeSettings();g.rosefire=this;this.rebuild();
  },
  makeSettings(){const box=document.createElement('details');box.id='rosefire-settings';box.innerHTML='<summary id="rosefire-summary">Rosefire / stone, stained light & ward shaders</summary><label>Shader profile <select id="rosefire-quality"><option value="off">Off / previous presentation</option><option value="balanced">Balanced / stained light & wet stone</option><option value="cinematic">Cinematic / twilight veil & fine ripples</option></select></label><label><input type="checkbox" id="rosefire-wet"> Rain-polished stone</label><label><input type="checkbox" id="rosefire-rose"> Stained-glass floor caustics</label><label><input type="checkbox" id="rosefire-ward"> Woven Wardglass shield</label><p id="rosefire-policy" role="status"></p><p>Artistic light projections and reusable environment reflections, not ray tracing or mirrors of enemies. No extra screen render. Classic materials disable Rosefire. Reduced effects freeze ambient motion and remove landing echoes. AR keeps only the equipment effect.</p>';
   this.j.settingsElement.after(box);this.box=box;const $=id=>document.getElementById(id);this.controls=[$('rosefire-quality'),$('rosefire-wet'),$('rosefire-rose'),$('rosefire-ward')];this.controls[0].value=this.options.mode;this.controls.slice(1).forEach((el,i)=>el.checked=this.options[['wet','rose','ward'][i]]);this.readout=$('rosefire-policy');
   this.onOptions=()=>{this.options=S.settings({mode:this.controls[0].value,wet:this.controls[1].checked,rose:this.controls[2].checked,ward:this.controls[3].checked});try{localStorage.setItem(KEY,JSON.stringify(this.options));}catch{this.readout.textContent='Shader preference is session-only; browser storage unavailable.';}this.signature='';};for(const el of this.controls)el.addEventListener('change',this.onOptions);
  },
  patchMaterial(m){if(!m?.isMeshStandardMaterial||this.patched.has(m))return;const self=this,original={compile:m.onBeforeCompile,key:m.customProgramCacheKey,env:m.envMap,intensity:m.envMapIntensity};this.patched.set(m,original);
   m.onBeforeCompile=function(shader,renderer){original.compile.call(this,shader,renderer);try{S.patch(shader,self.uniforms);self.stats.compiled++;}catch(e){self.errors.push(e.message);throw e;}};
   m.customProgramCacheKey=function(){return original.key.call(this)+'|rosefire-surface-v1';};m.needsUpdate=true;this.stats.patchedMaterials=this.patched.size;
  },
  rebuild(){const g=this.g,j=this.j,w=g.game.world;this.world=w;this.lastEvent=g.game.eventSeq||0;this.lastSources=-1;this.sources=[];this.stats.builds++;for(const a of this.wakes){a.mesh.visible=false;a.born=-Infinity;}
   if(!g.arMode){g.worldArt.group.traverse(o=>{const list=Array.isArray(o.material)?o.material:[o.material];for(const m of list)if(m?.name==='CC0 photographed cobblestones'||m?.name==='Dark paving'||o.geometry===g.art.geos.dominionPlane)this.patchMaterial(m);});
    for(const projection of j.projections||[]){const room=w.rooms.reduce((best,r)=>Math.hypot(r.x-projection.window.position.x,r.z-projection.window.position.z)<Math.hypot(best.x-projection.window.position.x,best.z-projection.window.position.z)?r:best,w.rooms[0]);this.sources.push([room.x,room.z,Math.min(room.w,room.d)*.38,projection.window.rotation.y]);}}
   this.signature='';
  },
  apply(){const g=this.g,j=this.j,p=this.current=S.policy(this.options,{xr:g.xr,ar:g.arMode,materialMode:j.options.mode,reduced:j.options.reduced,effects:j.options.effects});this.uniforms.uRFWet.value=p.wet?.83:0;this.uniforms.uRFRose.value=p.rose?.9:0;this.uniforms.uRFAnimated.value=p.animated?1:0;this.uniforms.uRFDetail.value=p.cinematic?1:0;
   const night=document.getElementById('lighting').value==='twilight';for(const [m,original]of this.patched){const env=p.wet?j.environments[night?1:0]:original.env;if(m.envMap!==env){m.envMap=env;m.needsUpdate=true;}m.envMapIntensity=p.wet?.62:original.intensity;}
   if(!p.wakes)for(const a of this.wakes)a.mesh.visible=false;this.readout.textContent=g.arMode?'AR: no sky, floor projections or landing effects / equipment only':!p.enabled?'Rosefire off / previous materials and shaders restored':g.xr?'Quest / WebXR: 2 nearby stained-light sources, 3 echoes maximum / no screen-space passes':p.cinematic?'Cinematic: wet stone, fine ripples, stained light, twilight veil and woven wards':'Balanced: wet stone, stained light, soft twilight veil and woven wards';
  },
  tick(){if(this.disposed)return;if(!this.started){this.setup();if(!this.started)return;}const g=this.g,j=this.j,s=g.game;if(j.world!==s.world)return;if(this.world!==s.world)this.rebuild();const sig=[this.options.mode,this.options.wet,this.options.rose,this.options.ward,j.options.mode,j.options.effects,j.options.reduced,g.xr,g.arMode,document.getElementById('lighting').value].join('/');if(sig!==this.signature){this.signature=sig;this.apply();}
   const p=this.current,t=s.time;this.uniforms.uRFTime.value=t;this.uniforms.uRFPlayer.value.fromArray(s.p);j.sky.material=p.sky?this.sky:this.originalSky;this.sky.uniforms.uTime.value=t;this.sky.uniforms.uNight.value=document.getElementById('lighting').value==='twilight'?1:0;this.sky.uniforms.uCalm.value=p.animated?0:1;this.sky.uniforms.uDetail.value=p.cinematic?1:0;
   g.arsenal.shield.children[0].material=p.ward?this.ward:j.current.enabled?j.shieldMat:j.originalShield;this.ward.uniforms.uCalm.value=p.animated?0:1;
   for(const {pool}of j.projections||[])pool.visible=j.current.enabled&&j.current.effects&&!p.rose;
   if(p.rose&&(t-this.lastSources>.25||this.lastSources<0)){this.lastSources=t;const selected=S.selectSources(this.sources,s.p,p.roseCount);this.uniforms.uRFSources.value.forEach((v,i)=>selected[i]?v.set(...selected[i]):v.set(0,0,0,0));}
   for(const e of s.events){if(e.seq<=this.lastEvent)continue;if(p.wakes&&['blink','shard'].includes(e.type)&&Array.isArray(e.p)&&e.p.every(Number.isFinite)){const a=this.wakes[this.wakeIndex++%p.maxWakes];a.born=t;a.mesh.position.set(e.p[0],e.p[1]+.035,e.p[2]);a.mesh.scale.setScalar(e.type==='blink'?1.25:.8);a.mesh.material.uniforms.uColor.value.set(e.type==='blink'?'#77e7d6':'#ecc777');a.mesh.visible=true;this.stats.wakes++;}}this.lastEvent=s.eventSeq||0;
   this.stats.activeWakes=0;for(let i=0;i<this.wakes.length;i++){const a=this.wakes[i],age=(t-a.born)/1.1;a.mesh.visible=p.wakes&&i<p.maxWakes&&age>=0&&age<1;if(a.mesh.visible){this.stats.activeWakes++;a.mesh.material.uniforms.uAge.value=age;}}this.root.visible=p.world;
  },
  remove(){this.disposed=true;if(!this.started)return;const j=this.j;for(const [m,old]of this.patched){m.onBeforeCompile=old.compile;m.customProgramCacheKey=old.key;m.envMap=old.env;m.envMapIntensity=old.intensity;m.needsUpdate=true;}j.sky.material=this.originalSky;this.g.arsenal.shield.children[0].material=j.current.enabled?j.shieldMat:j.originalShield;for(const {pool}of j.projections||[])pool.visible=j.current.enabled&&j.current.effects;for(const el of this.controls)el.removeEventListener('change',this.onOptions);for(const a of this.wakes)a.mesh.material.dispose();this.wakeGeometry.dispose();this.ward.dispose();this.sky.dispose();this.root.removeFromParent();this.box.remove();this.patched.clear();this.g.rosefire=null;}
 });
})();
