/* Tidelight flooded cloisters. Presentation-only: no collision or game-state mutation. */
(function(){'use strict';const S=TidelightShaders,KEY='vesperfall-tidelight-v1';
 AFRAME.registerComponent('tidelight',{
  dependencies:['vesper-game'],
  init(){this.g=this.el.components['vesper-game'];this.T=AFRAME.THREE;this.started=false;this.world=null;this.lastEvent=0;this.lastStep=[0,0];},
  setup(){if(this.started||!this.g?.game?.world)return;this.started=true;let raw={};try{raw=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{}this.options=S.settings(raw);this.root=new this.T.Group();this.root.name='Tidelight / flooded cloisters';this.el.object3D.add(this.root);this.surfaces=[];this.ripples=Array.from({length:10},()=>({x:0,z:0,born:-100}));this.rippleIndex=0;this.makeSettings();this.rebuild();this.g.tidelight=this;},
  makeSettings(){const d=document.createElement('details');d.id='tidelight-settings';d.innerHTML='<summary>Water / Tidelight flooded cloisters</summary><label>Water profile <select id="tidelight-quality"><option value="off">Off</option><option value="balanced">Balanced / Quest friendly</option><option value="cinematic">Cinematic / richer waves</option></select></label><label><input type="checkbox" id="tidelight-ripples"> Arrow + footstep ripples</label><label><input type="checkbox" id="tidelight-caustics"> Moving caustic highlights</label><p id="tidelight-policy" role="status"></p>';const anchor=document.getElementById('rosefire-settings')||document.querySelector('.settings');anchor.after(d);this.box=d;this.q=document.getElementById('tidelight-quality');this.r=document.getElementById('tidelight-ripples');this.c=document.getElementById('tidelight-caustics');this.readout=document.getElementById('tidelight-policy');this.q.value=this.options.mode;this.r.checked=this.options.ripples;this.c.checked=this.options.caustics;this.change=()=>{this.options=S.settings({mode:this.q.value,ripples:this.r.checked,caustics:this.c.checked});try{localStorage.setItem(KEY,JSON.stringify(this.options));}catch{}this.signature='';};for(const e of[this.q,this.r,this.c])e.addEventListener('change',this.change);},
  makeMaterial(){return new this.T.ShaderMaterial({name:'Tidelight / water',vertexShader:S.vertex,fragmentShader:S.fragment,transparent:true,depthWrite:false,side:this.T.DoubleSide,uniforms:{uTime:{value:0},uAnimated:{value:1},uDetail:{value:0},uOpacity:{value:.43},uCaustics:{value:1},uDeep:{value:new this.T.Color('#173b45')},uShallow:{value:new this.T.Color('#75a8a7')},uRipples:{value:Array.from({length:10},()=>new this.T.Vector4())}}});},
  rebuild(){const T=this.T,w=this.g.game.world;this.world=w;this.lastEvent=this.g.game.eventSeq||0;while(this.root.children.length){const o=this.root.children.pop();o.geometry?.dispose();o.material?.dispose();}this.surfaces=[];const candidates=w.rooms.filter(r=>r.planFamily==='court'||r.planFamily==='archive'||r.id===1);for(const r of candidates){if(r.id===1&&w.depth%2===0)continue;const inset=r.planFamily==='archive'?2.5:1.4,geo=new T.PlaneGeometry(Math.max(4,r.w-inset*2),Math.max(4,r.d-inset*2),20,20),mat=this.makeMaterial(),mesh=new T.Mesh(geo,mat);mesh.rotation.x=-Math.PI/2;mesh.position.set(r.x,.028,r.z);mesh.name='Tidelight / '+r.label;mesh.renderOrder=3;this.root.add(mesh);this.surfaces.push({mesh,room:r});}this.signature='';},
  inside(x,z,s){const r=s.room;return Math.abs(x-r.x)<r.w/2-1.0&&Math.abs(z-r.z)<r.d/2-1.0;},
  splash(x,z,t){if(!this.options.ripples)return;const s=this.surfaces.find(q=>this.inside(x,z,q));if(!s)return;const q=this.ripples[this.rippleIndex++%this.ripples.length];q.x=x;q.z=z;q.born=t;},
  apply(){const g=this.g,p=this.current=S.policy(this.options,{xr:g.xr,ar:g.arMode,reduced:g.jewelglass?.options?.reduced,effects:g.jewelglass?.options?.effects});this.root.visible=p.enabled;this.surfaces.forEach((s,i)=>{s.mesh.visible=p.enabled&&i<p.maxPools;s.mesh.material.uniforms.uAnimated.value=p.animated?1:0;s.mesh.material.uniforms.uDetail.value=p.detail?1:0;s.mesh.material.uniforms.uCaustics.value=p.caustics?1:0;s.mesh.material.uniforms.uOpacity.value=g.xr?.38:.45;});this.readout.textContent=g.arMode?'AR: flooded-world surfaces disabled for passthrough safety':g.xr?'Quest: bounded translucent water, 3 nearby authored pools maximum, no reflection render pass':p.detail?'Cinematic: finer waves, caustics and impact rings':'Balanced: translucent water, caustics and ripples';},
  tick(){if(!this.started){this.setup();if(!this.started)return;}const g=this.g,s=g.game;if(this.world!==s.world)this.rebuild();const sig=[this.options.mode,this.options.ripples,this.options.caustics,g.xr,g.arMode,g.jewelglass?.options?.reduced,g.jewelglass?.options?.effects].join('/');if(sig!==this.signature){this.signature=sig;this.apply();}const p=this.current,t=s.time;
   for(const e of s.events){if(e.seq<=this.lastEvent)continue;if(e.type==='impact'&&e.p)this.splash(e.p[0],e.p[2],t);if(['blink','shard'].includes(e.type)&&e.p)this.splash(e.p[0],e.p[2],t);}this.lastEvent=s.eventSeq||0;
   if(p.ripples&&p.enabled){const dx=s.p[0]-this.lastStep[0],dz=s.p[2]-this.lastStep[1];if(dx*dx+dz*dz>.75){this.splash(s.p[0],s.p[2],t);this.lastStep=[s.p[0],s.p[2]];}}
   const active=this.surfaces.map(q=>({q,d:Math.hypot(q.room.x-s.p[0],q.room.z-s.p[2])})).sort((a,b)=>a.d-b.d);for(const x of this.surfaces)x.mesh.visible=false;for(const x of active.slice(0,p.maxPools))x.q.mesh.visible=p.enabled&&x.d<44;
   for(const x of this.surfaces){const u=x.mesh.material.uniforms;u.uTime.value=t;u.uRipples.value.forEach((v,i)=>{const r=this.ripples[i],age=(t-r.born)/1.5;if(p.ripples&&age>=0&&age<1)v.set(r.x,r.z,age,1);else v.set(0,0,0,0);});}
  },
  remove(){if(!this.started)return;for(const e of[this.q,this.r,this.c])e.removeEventListener('change',this.change);for(const s of this.surfaces){s.mesh.geometry.dispose();s.mesh.material.dispose();}this.root.removeFromParent();this.box.remove();this.g.tidelight=null;}
 });
})();
