import {test} from 'node:test';import assert from 'node:assert/strict';
import {initial,blocked} from '../model.mjs';
import {street,distance,add,mul,tangent,norm,dot,cross,point} from '../world.mjs';
import {CITY,coordinates,cityCollision,sightBlocked,clearedForCity} from '../city-world.mjs';
import * as C from '../city-model.mjs';
function tick(s,c,n=1,input={}){for(let i=0;i<n;i++)C.stepCity(s,c,input,1/60);}
function walk(s,c,t,x=0){const to=street(t,x);for(let i=0;i<12000;i++){if(distance(s.n,to)<.4){tick(s,c,70);return;}const direction=tangent(add(to,mul(s.n,-1)),s.n);tick(s,c,1,{direction});}throw Error('Blocked route '+JSON.stringify({s:coordinates(s.n),to:[t,x]}));}
function hack(s,c,id){C.scan(s,c);const nodes=C.candidates(s,c);assert.ok(nodes.some(n=>n.id===id),'in scan range '+id);for(let i=0;i<nodes.length&&C.selectedDevice(s,c)?.id!==id;i++)C.cycleDevice(s,c);tick(s,c,210,{hack:true});}
function drive(s,c,t,x){const to=street(t,x);for(let i=0;i<15000;i++){const v=c.vehicles.find(v=>v.id===c.car),d=distance(s.n,to);if(d<1){tick(s,c,90,{brake:true});return;}const dir=tangent(add(to,mul(s.n,-1)),s.n),angle=Math.atan2(dot(s.n,cross(v.f,dir)),dot(v.f,dir)),limit=Math.abs(angle)>.3?2.8:Math.min(8,Math.sqrt(d*3));tick(s,c,1,{throttle:v.speed>limit+.2?-1:v.speed<limit?1:0,steer:Math.abs(angle)<.018?0:angle>0?-1:1});}throw Error('Car route failed '+JSON.stringify({at:coordinates(s.n),to:[t,x]}));}
test('Adding the city keeps the same close-world coordinates and original neighborhood clear',()=>{for(const n of [street(0),street(60),street(100)])assert.equal(clearedForCity(n),false);assert.equal(CITY.roads.length,7);assert.equal(CITY.devices.length,6);});
test('Initial city progress is separate and read-only inspection cannot mutate it',()=>{const s=initial(),c=C.initialCity(),q=C.cityInspect(s,c);q.drone.n[0]=90;q.vehicles[0].n[0]=90;assert.notEqual(c.vehicles[0].n[0],90);assert.equal(c.credits,80);assert.equal(c.completed,false);});
test('All authored roads have clear floor space except their intentional closed checkpoint',()=>{for(const r of CITY.roads)for(let i=0;i<=60;i++){const n=street(r.a[0]+(r.b[0]-r.a[0])*i/60,r.a[1]+(r.b[1]-r.a[1])*i/60);assert.equal(!!blocked(n),false,r.id+' '+i);}});
test('The checkpoint physically blocks a car and a low drone, but not flight above the fence',()=>{const n=street(170,25);assert.ok(cityCollision(n,.4,0,false));assert.ok(cityCollision(n,.4,1,false));assert.equal(cityCollision(n,.4,4,false),undefined);assert.equal(cityCollision(n,.4,0,true),undefined);});
test('Solid cover occludes sight and linking; flight above a fence restores line of sight',()=>{assert.ok(sightBlocked(street(169,25),1.5,street(174,25),1.5,false));assert.equal(sightBlocked(street(169,25),5,street(174,25),5,false),false);assert.ok(sightBlocked(street(180,21),1,street(180,25),1,true));});
test('A normal actor collects the kit, contacts the crew, uses the rear alley and returns with evidence',()=>{const s=initial(),c=C.initialCity();C.startAssignment(s,c);walk(s,c,-9,-4.2);C.interactCity(s,c);assert.equal(c.stage,1);walk(s,c,105);walk(s,c,116);walk(s,c,116,12);C.interactCity(s,c);assert.equal(c.stage,2);walk(s,c,116,25);walk(s,c,154,25);walk(s,c,158,25);walk(s,c,158,13);walk(s,c,195,13);walk(s,c,195,24);walk(s,c,192,24);hack(s,c,'evidence');assert.equal(c.stage,3);assert.equal(c.approach,'on foot');assert.equal(c.gate,false);walk(s,c,206,25);walk(s,c,206,57);C.interactCity(s,c);assert.equal(c.stage,4);walk(s,c,206,25);walk(s,c,195,25);walk(s,c,195,13);walk(s,c,158,13);walk(s,c,158,25);walk(s,c,116,25);walk(s,c,116);walk(s,c,0);walk(s,c,-9,-4.2);tick(s,c,650);C.interactCity(s,c);assert.equal(c.completed,true);const steps=s.steps;tick(s,c,300);assert.equal(s.steps,steps+300);assert.equal(c.events.filter(e=>e.type==='published').length,1);});
test('The parked press car can be reached, entered, steered to the junction and exited safely',()=>{const s=initial(),c=C.initialCity();walk(s,c,18,3.4);assert.ok(C.mount(s,c));assert.equal(c.car,'press');drive(s,c,33,0);drive(s,c,107,0);drive(s,c,116,0);drive(s,c,116,25);assert.ok(c.driven>70);C.mount(s,c);assert.equal(c.car,null);assert.equal(s.ride,false);assert.equal(!!blocked(s.n),false);});
test('A remote drone flies through a closed checkpoint and links the terminal while its body stays outside',()=>{const s=initial(),c=C.initialCity({active:true,stage:2});s.n=street(165,25);s.north=tangent([0,0,-1],s.n);const body=[...s.n];C.droneAction(s,c);const to=street(190,24);for(let i=0;i<700&&distance(c.drone.n,to)>1;i++)tick(s,c,1,{direction:tangent(add(to,mul(c.drone.n,-1)),c.drone.n)});assert.ok(distance(c.drone.n,to)<2);hack(s,c,'evidence');assert.equal(c.approach,'drone');assert.equal(c.stage,3);assert.deepEqual(s.n,body);assert.equal(c.gate,false);C.droneAction(s,c);assert.deepEqual(s.n,body);});
test('Scan alone cannot hack; H requires range, clear sight and uninterrupted dwell',()=>{const s=initial(),c=C.initialCity();s.n=street(150,24);C.scan(s,c);tick(s,c,180);assert.equal(c.power,false);tick(s,c,180,{hack:true});assert.equal(c.power,false);s.n=street(156,24);C.scan(s,c);tick(s,c,25,{hack:true});tick(s,c,1);assert.equal(c.progress,0);hack(s,c,'power');assert.equal(c.power,true);});
test('The power junction unlocks gate control; a gate hack without power is refused',()=>{const s=initial(),c=C.initialCity({active:true,stage:2});s.n=street(167,23);hack(s,c,'gate');assert.equal(c.gate,false);s.n=street(156,24);hack(s,c,'power');s.n=street(167,23);hack(s,c,'gate');assert.equal(c.gate,true);});
test('A hacked moving car is stopped in actual simulation state, not a copied scan target',()=>{const s=initial(),c=C.initialCity();s.n=street(130,24);hack(s,c,'taxi');const v=c.vehicles[1];assert.ok(v.stopped>10);assert.equal(v.speed,0);});
test('Drone range, altitude and battery are bounded; depleted battery returns the feed, not the body',()=>{const s=initial(),c=C.initialCity();C.droneAction(s,c);const before=[...s.n];tick(s,c,1200,{direction:[1,0,0],rise:true});assert.ok(distance(s.n,c.drone.n)<=48.01);assert.equal(c.drone.lift,14);c.drone.battery=.01;tick(s,c,3);assert.equal(c.drone.active,false);assert.deepEqual(s.n,before);});
test('Visible surveillance grows a trace; solid cover and time out of sight let it decay',()=>{const s=initial(),c=C.initialCity({active:true,stage:2});s.n=street(183,25.3);tick(s,c,220);assert.ok(c.trace>.1);s.n=street(158,13);tick(s,c,1000);assert.equal(c.trace,0);});
test('Crouching uses a shorter sight height behind a real cover object',()=>{assert.ok(sightBlocked(street(180,20),1,street(180,26),1,true));assert.equal(sightBlocked(street(180,20),2,street(180,26),2,true),false);const s=initial(),c=C.initialCity();c.crouch=true;tick(s,c,90,{direction:s.north});assert.ok(s.speed<2);});
test('Nonlethal pulse consumes energy, disables nearby patrols and raises trace',()=>{const s=initial(),c=C.initialCity({active:true,stage:2});s.n=street(184,25);C.pulse(s,c);assert.equal(c.energy,70);assert.ok(c.guards[0].stun>0);assert.ok(c.trace>0);assert.equal(c.alarmEver,true);});
test('Garage transactions require presence and funds; nitro cannot be double purchased',()=>{const s=initial(),c=C.initialCity();assert.equal(C.garageAction(s,c,'nitro'),false);s.n=[...CITY.garage.n];assert.ok(C.garageAction(s,c,'nitro'));assert.equal(c.credits,20);assert.equal(C.garageAction(s,c,'nitro'),false);c.vehicles[0].fuel=0;assert.ok(C.garageAction(s,c,'service'));assert.equal(c.credits,0);assert.equal(c.vehicles[0].fuel,100);assert.equal(C.garageAction(s,c,'service'),false);});
test('Side dispatches and paper-credit grants cannot be farmed by repeated interaction or reload',()=>{const s=initial(),c=C.initialCity();s.n=CITY.jobs[0].n;C.interactCity(s,c);const credits=c.credits;C.interactCity(s,c);assert.equal(c.credits,credits);s.delivered.add('cabin');tick(s,c,3);assert.equal(c.credits,credits+10);const loaded=C.initialCity(C.readCitySave(JSON.stringify(C.citySave(c))));tick(s,loaded,3);assert.equal(loaded.credits,c.credits);});
test('Malformed city saves, fake IDs and impossible stage flags cannot inject coordinates or unlimited credit',()=>{assert.equal(C.readCitySave('{bad'),null);assert.equal(C.readCitySave('x'.repeat(8000)),null);const c=C.initialCity(C.readCitySave(JSON.stringify({v:1,stage:1,completed:true,credits:1e99,jobs:['bad'],car:'bad',n:[99,99,99]})));assert.equal(c.completed,false);assert.equal(c.car,null);assert.equal(c.jobs.size,0);assert.equal(c.credits,100000);});
test('The harbor crossing remains a visible above-water traversable surface',()=>{for(let x=27;x<58;x++)assert.ok(Math.hypot(...point(street(206,x)))>109.62);});
