import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {gameplayInputIsNeutral} from '../controller-neutral.mjs';
const makePad=()=>({axes:[0,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))});
test('Neutral gamepad is ready but a missing source is not',()=>{assert.equal(gameplayInputIsNeutral(makePad()),true);assert.equal(gameplayInputIsNeutral(null),false);});
test('Partially held LT and RT cannot rearm before the gameplay threshold releases',()=>{for(const index of [6,7])for(const value of [.201,.3,.5,1]){const pad=makePad();pad.buttons[index]={pressed:false,value};assert.equal(gameplayInputIsNeutral(pad),false,`${index}: ${value}`);}const pad=makePad();pad.buttons[7].value=.2;assert.equal(gameplayInputIsNeutral(pad),true);});
test('All four sticks must be within the actual gameplay dead zone',()=>{for(let i=0;i<4;i++)for(const value of [-1,-.18,-.161,.161,.18,1]){const pad=makePad();pad.axes[i]=value;assert.equal(gameplayInputIsNeutral(pad),false);}const pad=makePad();pad.axes=[.16,-.16,0,0];assert.equal(gameplayInputIsNeutral(pad),true);});
test('Digital actions and invalid analog samples cannot rearm gameplay',()=>{for(let i=0;i<17;i++){const pad=makePad();pad.buttons[i].pressed=true;assert.equal(gameplayInputIsNeutral(pad),false);}for(const value of [NaN,Infinity]){const pad=makePad();pad.axes[0]=value;assert.equal(gameplayInputIsNeutral(pad),false);pad.axes[0]=0;pad.buttons[7].value=value;assert.equal(gameplayInputIsNeutral(pad),false);}});
test('Real controller menu rearm uses the independently tested neutral guard',()=>{const source=readFileSync(new URL('../controller.mjs',import.meta.url),'utf8');assert.match(source,/import \{gameplayInputIsNeutral\} from '\.\/controller-neutral\.mjs'/);assert.match(source,/if\(!gameplayReady\)\{clear\(\);if\(!gameplayInputIsNeutral\(pad\)\)/);});
