import {test} from 'node:test';import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';
import {initial,saveData,readSave,SAVE_KEY,LEGACY_SAVE_KEY,WORLD,point,street} from '../model.mjs';
import {createSaveVault,VAULT_KEYS,validSave} from '../save-vault.mjs';
import {createCourier} from '../vehicles.mjs';import {solveTwoBone,createGroundedMotion} from '../grounded-motion.mjs';
import {pinchPressed,xrAxes,buttonPressed} from '../xr-input.mjs';
const sample=(count=0)=>{const s=initial();for(const h of WORLD.homes.slice(0,count))s.delivered.add(h.id);return JSON.stringify(saveData(s));};
function memory(seed={}){const map=new Map(Object.entries(seed));return {map,getItem:k=>map.get(k)||null,setItem(k,v){map.set(k,v);},removeItem(k){map.delete(k);}};}

test('Vault keeps the historical v1 keys and does not touch sibling storage',()=>{const m=memory({sibling:'keep'}),v=createSaveVault(m);v.load();assert.equal(v.commit(sample(1)),true);assert.equal(SAVE_KEY,'svgn.paper-delivery-3d.v1');assert.equal(m.map.get('sibling'),'keep');assert.ok([...m.map.keys()].every(k=>k==='sibling'||Object.values(VAULT_KEYS).includes(k)));});
test('Vault round trips old saves, contracts, finish state and rewards',()=>{const s=initial();s.jobs.earned=321;const raw=JSON.stringify(saveData(s)),m=memory({[SAVE_KEY]:raw}),v=createSaveVault(m);assert.deepEqual(v.load(),readSave(raw));assert.equal(v.commit(raw),true);assert.equal(m.getItem(SAVE_KEY),raw);});
test('Last known good backup is written before primary changes',()=>{const a=sample(1),b=sample(2),m=memory({[SAVE_KEY]:a}),v=createSaveVault(m);v.load();assert.ok(v.commit(b));assert.equal(m.getItem(VAULT_KEYS.backup),a);assert.equal(m.getItem(SAVE_KEY),b);assert.equal(m.getItem(VAULT_KEYS.pending),null);});
test('Corrupt primary recovers backup and retains unreadable original',()=>{const a=sample(2),m=memory({[SAVE_KEY]:'{bad',[VAULT_KEYS.backup]:a}),v=createSaveVault(m);assert.equal(v.load().delivered.length,2);assert.ok(v.commit(a));assert.equal(m.getItem(VAULT_KEYS.quarantine),'{bad');assert.equal(m.getItem(VAULT_KEYS.backup),a);});
test('Interrupted primary write leaves committed progress intact',()=>{const a=sample(1),b=sample(2),m=memory({[SAVE_KEY]:a}),v=createSaveVault(m);v.load();const set=m.setItem;m.setItem=(k,v)=>{if(k===SAVE_KEY)throw Error('interrupted');set(k,v);};assert.equal(v.commit(b),false);assert.equal(m.getItem(SAVE_KEY),a);assert.equal(m.getItem(VAULT_KEYS.backup),a);assert.equal(m.getItem(VAULT_KEYS.pending),b);assert.equal(createSaveVault(m).load().delivered.length,1);});
test('Interrupted transaction can recover staging when primary is invalid',()=>{const m=memory({[SAVE_KEY]:'bad',[VAULT_KEYS.pending]:sample(3)}),v=createSaveVault(m);assert.equal(v.load().delivered.length,3);assert.match(v.inspect().status,/interrupted/);});
test('Quota failure while making backup cannot overwrite primary',()=>{const a=sample(1),m=memory({[SAVE_KEY]:a}),v=createSaveVault(m);v.load();m.setItem=()=>{throw Error('quota');};assert.equal(v.commit(sample(2)),false);assert.equal(m.getItem(SAVE_KEY),a);assert.match(v.inspect().status,/could not finish/);});
test('Failed read blocks autosave instead of replacing an unseen existing save',()=>{const m=memory({[SAVE_KEY]:sample(4)});const get=m.getItem;m.getItem=()=>{throw Error('security');};const v=createSaveVault(m);v.load();m.getItem=get;assert.equal(v.commit(sample()),false);assert.equal(readSave(m.getItem(SAVE_KEY)).delivered.length,4);});
test('All unreadable slots are retained until an explicit recovery decision',()=>{const m=memory({[SAVE_KEY]:'broken'}),v=createSaveVault(m);assert.equal(v.load(),null);assert.equal(v.commit(sample()),false);assert.equal(m.getItem(SAVE_KEY),'broken');assert.ok(v.commit(sample(1),{explicit:true}));assert.equal(m.getItem(VAULT_KEYS.quarantine),'broken');});
test('Future saves are read-only even when a legacy backup exists',()=>{const raw='{"v":2,"secretFutureField":42}',m=memory({[SAVE_KEY]:raw,[LEGACY_SAVE_KEY]:sample(1)}),v=createSaveVault(m);assert.equal(v.load(),null);assert.equal(v.commit(sample()),false);assert.equal(m.getItem(SAVE_KEY),raw);});
test('Legacy migration is additive and original slot remains unchanged',()=>{const raw=sample(3),m=memory({[LEGACY_SAVE_KEY]:raw}),v=createSaveVault(m);assert.equal(v.load().delivered.length,3);assert.ok(v.commit(raw));assert.equal(m.getItem(LEGACY_SAVE_KEY),raw);});
test('Import validation rejects oversized, corrupt and future data',()=>{for(const raw of ['{','null','{"v":9}','x'.repeat(64001)])assert.equal(validSave(raw),false);assert.ok(validSave(sample()));});
test('Failed verification of primary write is never reported as saved',()=>{const m=memory(),v=createSaveVault(m);v.load();const set=m.setItem;m.setItem=(k,x)=>set(k,k===SAVE_KEY?'corrupt':x);assert.equal(v.commit(sample()),false);assert.ok(validSave(m.getItem(VAULT_KEYS.pending)));});
test('Two-bone IK preserves both segment lengths and stable bend direction',()=>{const root=new T.Vector3(0,.96,0);for(let i=0;i<100;i++){const q=solveTwoBone(root,new T.Vector3(.1,.2+Math.sin(i)*.15,-.1),.42,.43);assert.ok(Math.abs(root.distanceTo(q.knee)-.42)<1e-9);assert.ok(Math.abs(q.knee.distanceTo(q.end)-.43)<1e-9);assert.ok(Number.isFinite(q.knee.z));}});
test('IK handles coincident and unreachable targets without NaN or hyperextension',()=>{const root=new T.Vector3();for(const t of [new T.Vector3(),new T.Vector3(0,-100,0),new T.Vector3(0,0,-.8)]){const q=solveTwoBone(root,t,.42,.43,new T.Vector3(0,0,-1));assert.ok(q.end.length()<.85);assert.ok(q.knee.toArray().every(Number.isFinite));}});
function hero(){const rig=createCourier(new T.Group()),motion=createGroundedMotion(rig),s=initial();s.n=street(0);rig.g.position.set(...point(s.n,.1));rig.g.updateMatrixWorld(true);return {rig,motion,s};}
test('Courier has a measured head and articulated arm/leg chains',()=>{const {rig,motion}=hero();assert.equal(rig.legChains.length,2);assert.equal(rig.armChains.length,2);assert.equal(rig.pedals.length,2);assert.ok(motion.inspect().height/motion.inspect().headHeight>7);});
test('A stopped courier does not keep cycling its legs',()=>{const {motion,s}=hero();motion.update(s,'unicycle',.2);const first=motion.inspect();for(let i=0;i<60;i++){s.time+=1/60;motion.update(s,'unicycle',1/60);}assert.equal(motion.inspect().phase,first.phase);assert.deepEqual(motion.inspect().targetFeet,first.targetFeet);});
test('Planted targets remain fixed in world coordinates under root translation',()=>{const {motion,rig,s}=hero();s.speed=.5;motion.update(s,'unicycle',.2);const before=motion.inspect().worldTargets[0];rig.g.position.x+=.025;rig.g.updateMatrixWorld(true);s.distance+=.025;motion.update(s,'unicycle',1/60);assert.deepEqual(motion.inspect().worldTargets[0],before);});
test('Teleport and airborne transitions release stale foot locks',()=>{const {motion,rig,s}=hero();motion.update(s,'unicycle',.2);rig.g.position.x+=20;motion.update(s,'unicycle',.2);assert.ok(motion.inspect().worldTargets[0][0]>19);s.lift=1;motion.update(s,'unicycle',.2);assert.deepEqual(motion.inspect().contacts,[false,false]);});
test('Bicycle pedals stop with distance and knees remain finite in all travel modes',()=>{const {motion,rig,s}=hero();for(const mode of ['bicycle','unicycle','boat','walk']){s.ride=!['boat','walk'].includes(mode);s.tide.boat=mode==='boat';for(let i=0;i<80;i++){s.distance=i*.03;s.speed=2;motion.update(s,mode,1/60);assert.ok(rig.legChains.every(c=>c.end.position.toArray().every(Number.isFinite)));}}});
test('Pinch uses hysteresis and releases on missing pose',()=>{assert.equal(pinchPressed(.023),true);assert.equal(pinchPressed(.03),false);assert.equal(pinchPressed(.03,true),true);assert.equal(pinchPressed(.04,true),false);assert.equal(pinchPressed(NaN,true),false);});
test('XR sticks handle both two- and four-axis devices with dead zones',()=>{assert.deepEqual(xrAxes({axes:[0,0,.1,-.1]}),{x:0,y:-0});assert.equal(xrAxes({axes:[0,0,1,-1]}).y,1);assert.equal(xrAxes({axes:[-1,1]}).x,-1);assert.equal(buttonPressed({buttons:[{value:.8}]},0),true);assert.equal(buttonPressed(null,0),false);});
