import assert from "node:assert/strict";

import { PIECE_CARDS } from "../piece-card-data.mjs";
import {
  computeCardTargets,
  renderPieceCardSvg
} from "../piece-card-renderer.mjs";

const chancellor = PIECE_CARDS.chancellor;
const zebra = PIECE_CARDS.zebra;
const targets = computeCardTargets(chancellor);
const zebraTargets = computeCardTargets(zebra);

assert.deepEqual(
  targets.knightLeap,
  ["b3", "b5", "c2", "c6", "e2", "e6", "f3", "f5"],
  "Chancellor knight dots must stay on the exact legal knight targets from d4"
);

assert.deepEqual(
  targets.rookRider,
  ["a4", "b4", "c4", "d1", "d2", "d3", "d5", "d6", "d7", "d8", "e4", "f4", "g4", "h4"],
  "Chancellor rook rays must stay on exact rank/file targets from d4"
);

const svg = renderPieceCardSvg(chancellor);
const zebraSvg = renderPieceCardSvg(zebra);

for (const target of targets.knightLeap) {
  assert.match(svg, new RegExp(`>${target}<`), `card SVG must label ${target}`);
}

assert.match(svg, /Knight<\/text>/, "card must include a knight target readback row");
assert.match(svg, /Rook<\/text>/, "card must include a rook target readback row");
assert.match(svg, /CHANCELLOR/, "rook+knight card must be labeled Chancellor, not Dragon");
assert.doesNotMatch(svg, />DRAGON<\/text>/, "rook+knight compound card must not use Dragon as its title");
assert.match(svg, /Rules layer generated by deterministic SVG from movement data/, "card must declare deterministic rendering");

assert.deepEqual(
  zebraTargets.zebraLeap,
  ["a2", "a6", "b1", "b7", "f1", "f7", "g2", "g6"],
  "Zebra dots must stay on the exact legal 3-by-2 targets from d4"
);

for (const target of zebraTargets.zebraLeap) {
  assert.match(zebraSvg, new RegExp(`>${target}<`), `Zebra card SVG must label ${target}`);
}

assert.match(zebraSvg, /Zebra<\/text>/, "Zebra card must include a Zebra target readback row");
assert.doesNotMatch(zebraSvg, /green = rook lines/, "Zebra card must not inherit Dragon's rook legend");
assert.match(zebraSvg, /red = zebra jumps/, "Zebra card must render the Zebra legend");

console.log("warledger-piece-card-contract: PASS");
