import {makeWorld,newState,readSave,saveData,SAVE_KEY,VERSION,R,step,interact,toggleRide,target,nearest,distance,dot,cross,unit,tangent,notice} from './model.mjs';
import {createScene} from './scene.mjs';
const $=id=>document.getElementById(id),world=makeWorld(),keys=new Set();let stored=null,storageOK=true;try{stored=readSave(localStorage.getItem(SAVE_KEY),world);}catch{storageOK=false;}
let state=newState(stored),scene,playing=false,paused=false,view=0,acc=0,last=0,lastUI=0,look=0,drag=null,jump=false,lastSave='',closed=false;
function save(){const value=JSON.stringify(saveData(state));if(lastSave===value)return;try{localStorage.setItem(SAVE_KEY,value);lastSave=value;}catch{storageOK=false;}}
function clear(){keys.clear();jump=false;look=0;acc=0;document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));}
function pause(){if(!playing)return;paused=true;clear();if(!$('pause-dialog').open&&!$('atlas-dialog').open)$('pause-dialog').showModal();}
function resume(){if(closed)return;paused=false;clear();$('world').focus({preventScroll:true});}
function map(){if(!playing)return;paused=true;clear();drawMap();$('atlas-dialog').showModal();}
function action(kind){if(!playing||paused)return;switch(kind){case'interact':interact(state,world);save();break;case'ride':toggleRide(state);break;case'jump':jump=true;break;}}
$('start').onclick=()=>{playing=true;paused=false;view=1;clear();$('title').hidden=true;$('hud').hidden=false;$('world').focus();};$('pause').onclick=pause;$('atlas').onclick=map;$('resume').onclick=()=>$('pause-dialog').close();$('close-atlas').onclick=()=>$('atlas-dialog').close();$('view').onclick=()=>{view=(view+1)%3;notice(state,['Whole planet view','Adventure view','Close following view'][view]);};
for(const id of['pause-dialog','atlas-dialog'])$(id).addEventListener('close',resume);
$('reset').onclick=()=>{if(!confirm('Reset only Little Planet’s parcels, discoveries and beacons? Your other SVGN games are not affected.'))return;state=newState();lastSave='';save();$('pause-dialog').close();scene.update(0,state,{view,snap:true});};
window.addEventListener('keydown',e=>{if(!playing||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;
 if(!e.repeat&&(e.code==='Escape'||e.code==='KeyP'||e.code==='KeyM')){e.preventDefault();if($('atlas-dialog').open)$('atlas-dialog').close();else if($('pause-dialog').open)$('pause-dialog').close();else if(e.code==='KeyM')map();else pause();return;}
 if(paused)return;if(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyE','KeyF','KeyV','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;
 if(e.code==='KeyE')action('interact');if(e.code==='KeyF')action('ride');if(e.code==='Space')action('jump');if(e.code==='KeyV')$('view').click();
});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(playing)pause();else clear();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause();});
if(matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0)document.body.classList.add('touch');
for(const b of document.querySelectorAll('[data-hold]')){b.onpointerdown=e=>{if(paused||!playing)return;e.preventDefault();keys.add(b.dataset.hold);b.classList.add('held');b.setPointerCapture(e.pointerId);};for(const type of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>{keys.delete(b.dataset.hold);b.classList.remove('held');});}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>action(b.dataset.action);
$('world').onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX};$('world').setPointerCapture(e.pointerId);};$('world').onpointermove=e=>{if(drag?.id===e.pointerId){look-=(e.clientX-drag.x)*.004;drag.x=e.clientX;}};for(const type of['pointerup','pointercancel','lostpointercapture'])$('world').addEventListener(type,()=>drag=null);
$('world').addEventListener('wheel',e=>{e.preventDefault();view=Math.max(0,Math.min(2,view+(e.deltaY<0?1:-1)));},{passive:false});
function input(){return {throttle:Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),steer:Number(keys.has('KeyA')||keys.has('ArrowLeft'))-Number(keys.has('KeyD')||keys.has('ArrowRight')),boost:keys.has('ShiftLeft')||keys.has('ShiftRight'),jump};}
function drawMap(){const c=$('map'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const r=145;
 for(const [cx,sign]of[[225,1],[675,-1]]){g.fillStyle='#668f70';g.beginPath();g.arc(cx,175,r,0,7);g.fill();g.strokeStyle='#9cb89a';g.lineWidth=1;g.stroke();const visible=n=>n[1]*sign>=0,xy=n=>[cx+n[0]*r*sign,175+n[2]*r];
  g.strokeStyle='#ebd194';g.lineWidth=3;for(const p of world.paths){g.beginPath();let begun=false;for(const n of p.nodes){if(!visible(n)){begun=false;continue;}const q=xy(n);if(!begun)g.moveTo(...q);else g.lineTo(...q);begun=true;}g.stroke();}
  for(const s of world.stops){if(!visible(s.n))continue;const q=xy(s.n);g.fillStyle=state.delivered.has(s.id)?'#aff0ce':s.delivery?'#ffd980':'#d6e6b5';g.beginPath();g.arc(...q,6,0,7);g.fill();g.font='10px system-ui';g.textAlign='center';g.fillStyle='#102c39';g.fillText(s.name,q[0],q[1]-12);}
  for(const b of world.beacons){if(!visible(b.n))continue;const q=xy(b.n);g.fillStyle=state.lit.has(b.id)?'#fff0a4':'#90d4cd';g.fillRect(q[0]-4,q[1]-4,8,8);}
  if(visible(state.n)){const q=xy(state.n);g.strokeStyle='#fff9d7';g.lineWidth=3;g.beginPath();g.arc(...q,10,0,7);g.stroke();g.fillStyle='#ce7154';g.beginPath();g.arc(...q,6,0,7);g.fill();}
  g.fillStyle='#cee0d6';g.font='600 11px system-ui';g.textAlign='center';g.fillText(sign===1?'HOME HEMISPHERE':'FAR HEMISPHERE',cx,20);
 }
 $('places').replaceChildren();for(const s of world.stops){const d=document.createElement('div'),b=document.createElement('strong');b.textContent=state.visited.has(s.id)?s.name:'Unexplored neighborhood';d.append(b);d.append(document.createTextNode(state.delivered.has(s.id)?'Parcel delivered':s.delivery?'A neighbor is waiting':state.visited.has(s.id)?'Discovered':'Follow the path to discover'));$('places').append(d);}}
function ui(){const set=(id,t)=>{if($(id).textContent!==t)$(id).textContent=t;},near=nearest(state,world),goal=target(state,world),district=world.stops.reduce((a,b)=>distance(state.n,a.n)<distance(state.n,b.n)?a:b);
 set('objective',state.completed?'A world of good news.':state.delivered.size===4?'Bring the story home.':'A little good news.');set('quest-detail',state.completed?'First round complete. Keep exploring, find all neighborhoods and relight the three beacons.':state.delivered.size===4?'Return to Mira at the Post Office. You can go either way around.':'Deliver four parcels. Walk or cycle along the gold path; E interacts nearby.');set('parcels',state.delivered.size+' / 4');set('stamps',String(state.collected.size));set('beacons',state.lit.size+' / 3');set('district',district.name.toUpperCase());set('ride-name',state.mode==='bike'?'Courier bicycle':'On foot');set('context',near?(near.type==='beacon'?'E · Restore '+near.name:near.delivery&&!state.delivered.has(near.id)?'E · Deliver to '+near.person:'E · Talk to '+near.person):'Follow the curved path, or explore a trail. F switches your ride.');set('target-name',state.completed?'Keep exploring':goal.name);set('target-distance',Math.round(distance(state.n,goal.n))+' m around the surface');set('save-status',storageOK?'Progress saved on this device.':'Storage unavailable — this session is not saved.');
 const dir=tangent(state.n,goal.n),angle=Math.atan2(dot(state.n,cross(state.f,dir)),dot(state.f,dir));$('arrow').style.transform=`rotate(${-angle}rad)`;
 set('toast',state.toast);$('toast').classList.toggle('visible',state.toastT>0);if($('atlas-dialog').open)drawMap();}
function frame(now){requestAnimationFrame(frame);const dt=last?Math.min(.1,(now-last)/1000):0;last=now;const controls=input();if(playing&&!paused&&!closed){acc=Math.min(.16,acc+dt);while(acc>=1/60){step(state,world,controls,1/60);jump=false;controls.jump=false;acc-=1/60;}save();}else acc=0;
 if(now-lastUI>100){ui();lastUI=now;}scene.update(dt,state,{view,lookDelta:look,steer:controls.steer});look=0;}
try{scene=createScene($('world'),world,state);window.addEventListener('resize',()=>scene.resize());$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();closed=true;pause();$('failure').hidden=false;$('failure-message').textContent='The graphics context was interrupted. Reload to return home; saved progress is retained.';});
 Object.defineProperty(window,'LittlePlanet',{value:Object.freeze({inspect:()=>({version:VERSION,running:playing&&!paused&&!closed,paused,n:[...state.n],f:[...state.f],speed:state.speed,mode:state.mode,lift:state.lift,steps:state.steps,distance:state.distance,delivered:[...state.delivered],visited:[...state.visited],lit:[...state.lit],collected:[...state.collected],completed:state.completed,events:state.events.map(e=>({...e})),target:{id:target(state,world).id,n:[...target(state,world).n]},near:nearest(state,world)?.id||null,camera:view,render:scene.inspect()})})});
 $('start').disabled=false;$('start').textContent=stored?'Continue your little adventure →':'Set out around the planet →';ui();requestAnimationFrame(frame);
}catch(e){console.error(e);$('failure').hidden=false;$('failure-message').textContent=String(e.message||e)+'. This game needs WebGL2 and HTTP hosting.';}
