import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,serialize,parse,tick,action,lineClear,blocked,support,floorHeight,surfaces} from './core.mjs';
import {trackStory,storyTarget} from './city.mjs';
import {campaignState,campaignRuntime,campaignCanGlide,parseCampaign,CAMPAIGN_CASES} from './campaign.mjs';
const idle=(s,n=60,input={})=>{for(let i=0;i<n;i++)tick(s,input,1/60);};
function seed(){const s=fresh();s.watch={v:1,tracking:false,stage:4,route:'roof',credits:180};return s;}
function unlock(s,...ids){s.campaign.completed=[...ids];s.campaign.credits=ids.reduce((n,id)=>n+({flight:150,predator:180,interiors:160,freeflow:200,finale:260}[id]||0),0);for(const id of ids){const c=CAMPAIGN_CASES.find(x=>x.id===id);s.campaign.progress[id]=c.steps.length;}}
function near(s,t){s.x=t.x;s.y=t.y;s.z=t.z;action(s,'interact');}
test('Campaign is additive, gated behind Night Watch, and parses old saves',()=>{const s=fresh();assert.equal(campaignState(s).active,null);const old=serialize(s);delete old.campaign;assert.equal(parse(old).campaign.credits,0);assert.throws(()=>parseCampaign({v:2}));});
test('Rooftop Run unlocks glide without changing chapter credits',()=>{const s=seed();trackStory(s,'campaign:flight');let t=storyTarget(s);near(s,t);t=storyTarget(s);near(s,t);assert.ok(campaignCanGlide(s));t=storyTarget(s);near(s,t);const r=campaignRuntime(s);s.x=-7;s.y=5.1;s.z=-4.5;s.yaw=Math.PI/2;s.vy=4.3;const before=s.distance;idle(s,30,{glide:true});assert.ok(s.distance>before+1.2);assert.ok(s.vy<4.3&&s.vy>=-1.2);s.x=-11.5;s.y=4.4;s.z=-4.5;s.vy=0;idle(s,2,{glide:true});assert.equal(r.glideLanded,true);near(s,storyTarget(s));near(s,storyTarget(s));assert.ok(campaignState(s).completed.includes('flight'));assert.equal(s.credits,0);assert.equal(s.watch.credits,180);});
test('Body holster actions select tools without durable transient serialization',()=>{const s=seed();unlock(s,'flight');trackStory(s,'campaign:predator');action(s,'holster-smoke');assert.equal(campaignRuntime(s).selected,'smoke');assert.equal(campaignRuntime(s).holsterDraws,1);assert.ok(!JSON.stringify(serialize(s)).includes('holsterDraws'));});
test('Predator patrols expose awareness and permit a behind silent takedown',()=>{const s=seed();unlock(s,'flight');trackStory(s,'campaign:predator');campaignState(s).progress.predator=2;const r=campaignRuntime(s),e=r.enemies[0];s.x=e.x;s.y=e.y;s.z=e.z-1.1;e.yaw=0;action(s,'interact');assert.equal(e.hp,0);assert.equal(r.takedowns,1);});
test('Freeflow strike lunges across a clear lane and damages on arrival',()=>{const s=seed();unlock(s,'flight','predator','interiors');trackStory(s,'campaign:freeflow');campaignState(s).progress.freeflow=1;const r=campaignRuntime(s),e=r.enemies.find(x=>x.id==='flow-4');s.x=e.x;s.y=e.y;s.z=e.z-4;const ray={origin:{x:s.x,y:1,z:s.z},direction:{x:0,y:0,z:1}};action(s,'strike',ray);assert.ok(r.lunge);idle(s,30,{guard:true});assert.equal(r.lunge,null);assert.ok(e.hp<3);});
test('Shield requires counter, pulse, or rear angle before ordinary flow damage',()=>{const s=seed();unlock(s,'flight','predator','interiors');trackStory(s,'campaign:freeflow');campaignState(s).progress.freeflow=1;const r=campaignRuntime(s),e=r.enemies.find(x=>x.role==='Shield');s.x=e.x;s.y=e.y;s.z=e.z+1.5;const hp=e.hp,ray={origin:{x:s.x,y:1,z:s.z},direction:{x:0,y:0,z:-1}};action(s,'strike',ray);assert.equal(e.hp,hp);action(s,'holster-pulse');action(s,'tool',ray);assert.ok(e.stun>0);idle(s,30,{guard:true});action(s,'strike',ray);assert.ok(e.hp<hp);});
test('Campaign completion ledger is exact and malformed totals are rejected',()=>{const good={v:1,active:null,progress:{flight:5},completed:['flight'],credits:150,route:'stealth'};assert.equal(parseCampaign(good).credits,150);assert.throws(()=>parseCampaign({...good,credits:0}));assert.throws(()=>parseCampaign({...good,completed:['unknown']}));});
test('All campaign cases have distinct purposes and real target sequences',()=>{assert.equal(CAMPAIGN_CASES.length,5);for(const c of CAMPAIGN_CASES){assert.ok(c.steps.length>=4);assert.ok(c.summary.length>30);const ids=new Set(c.steps.map(s=>s.id));assert.equal(ids.size,c.steps.length);}});
test('Freeflow counters require a freshly raised guard, not indefinite holding',()=>{const s=seed();unlock(s,'flight','predator','interiors');trackStory(s,'campaign:freeflow');campaignState(s).progress.freeflow=1;const r=campaignRuntime(s),e=r.enemies[0];s.x=e.x;s.y=e.y;s.z=e.z+1.4;idle(s,180,{guard:true});const n=r.counters;idle(s,180,{guard:true});assert.equal(r.counters,n);tick(s,{guard:false},1/60);for(let i=0;i<400&&r.counters===n;i++){const cue=e.phase==='windup'&&e.timer>.3;tick(s,{guard:cue},1/60);}assert.ok(r.counters>n);});

test('A walking arrival cannot bypass the required cape glide',()=>{const s=seed();trackStory(s,'campaign:flight');campaignState(s).progress.flight=3;const t=storyTarget(s);s.x=t.x;s.y=t.y;s.z=t.z;action(s,'interact');assert.equal(s.campaign.progress.flight,3);assert.equal(s.campaign.credits,0);});
