import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,tick,action,serialize,parse,blocked,interiorBuildings} from './core.mjs';
import {residents,stories,trackStory,storyTarget,parseCity,cityState} from './city.mjs';
import {missionOptions,navigation} from './navigation.mjs';
// Input-only walking driver. No actor or objective assignments manufacture completion.
function walk(s,x,z){for(let i=0;i<14000;i++){const dx=x-s.x,dz=z-s.z,d=Math.hypot(dx,dz);tick(s,{x:d>.16?dx/d:0,z:d>.16?dz/d:0,brake:d<=.16},1/60);if(d<.22&&s.speed<.05)return;}throw Error(`Cannot walk to ${x},${z}; at ${s.x},${s.y},${s.z}`);}
const path=(s,points)=>points.forEach(([x,z])=>walk(s,x,z));
const north=[[-23,13],[-23,-7],[-21,-13.5],[-10,-13.5],[6,-13.5]];
const loft=[[-12.5,8.2],[-12.5,5.2],[-12.5,-3.7],[-6,-3.5],[6,-3.5],[12,-3.5],[12,0]];
const routes={ada:[[-12.5,8.2],[-12.5,6],[-9.5,6],[-9.5,4.5]],bea:[[-20.5,10],[-20.5,4],[-20.5,0]],tomas:[...north.slice(0,4),[-10,-17.5],[-12,-17.5]],lin:[...north,[10,-13.5],[18,-12.5],[18,-17]],otis:[...north,[7.1,-13],[7.1,-10.5]],sal:loft};
function visit(s,id){path(s,routes[id]);assert.equal(s.ride,'foot');const r=residents.find(r=>r.id===id);assert.ok(Math.hypot(s.x-r.x,s.y-r.y,s.z-r.z)<.4);}
function hub(s,id){path(s,[...routes[id]].reverse());walk(s,-12,15);}
function target(s,points){path(s,points);const t=storyTarget(s);assert.ok(t);assert.ok(Math.hypot(s.x-t.x,s.y-t.y,s.z-t.z)<1.8,t.label);action(s,'interact');}
test('All six new residents can be reached from the unchanged depot by real walking',()=>{for(const r of residents){const s=fresh();visit(s,r.id);trackStory(s,stories.find(m=>m.giver===r.id).id);action(s,'interact');assert.ok(Object.values(s.city.progress).includes(0),r.id);}});
test('All previously solid prototype building blocks have actual interior floors and walkable doorways',()=>{for(const b of interiorBuildings){const s=fresh();assert.equal(blocked(s,b.x,0,b.z+b.d/2),false,b.id+' doorway');assert.equal(blocked(s,b.x,0,b.z),false,b.id+' interior');assert.equal(blocked(s,b.x-b.w/2,0,b.z),true,b.id+' sidewall');}});
test('Old layout-1 saves load with an empty additive ledger; original 600-credit contract is unchanged',()=>{const s=fresh(),old=serialize(s);delete old.city;const p=parse(old);assert.deepEqual(p.city,{v:1,active:null,progress:{},completed:[],credits:0});assert.equal(p.credits,0);assert.equal(serialize(p).layout,1);});
test('Future, forged and duplicate resident reward ledgers are refused rather than reset',()=>{for(const city of [{v:2},{v:1,active:null,progress:{},completed:[],credits:90},{v:1,active:null,progress:{press:3},completed:['press','press'],credits:180}])assert.throws(()=>parseCity(city));});
test('Mission tracking exposes a next target and does not assign inventory or stage progress',()=>{const s=fresh();const before=serialize(s);trackStory(s,'radio');const t=storyTarget(s);assert.equal(t.id,'meet-sal');assert.equal(navigation(s).level,'UPSTAIRS');assert.deepEqual(s.city.progress,{});assert.equal(s.parcel,before.parcel);assert.equal(s.credits,before.credits);trackStory(s,'main');assert.equal(storyTarget(s).x,-12);assert.equal(missionOptions(s).filter(m=>m.disabled).length,1);});
test('Printer mission is completed by a real round trip through two interiors and the depot',()=>{const s=fresh();visit(s,'ada');trackStory(s,'press');action(s,'interact');hub(s,'ada');visit(s,'tomas');target(s,[[-9,-17]]);path(s,[[-10,-17.5]]);hub(s,'tomas');visit(s,'ada');target(s,[[-9.6,1.5]]);path(s,[[-9.5,4.5]]);hub(s,'ada');target(s,[[-8.5,15.5]]);assert.deepEqual(s.city.completed,['press']);assert.equal(s.city.credits,90);assert.equal(s.credits,0);action(s,'interact');assert.equal(s.city.credits,90);assert.equal(parse(serialize(s)).city.credits,90);});
test('Rooftop radio mission uses actual stair ascent and a return to its resident',()=>{const s=fresh();visit(s,'sal');trackStory(s,'radio');action(s,'interact');target(s,[[12,-3.5],[6,-3.5],[-6,-3.5],[-10,-4.5]]);target(s,[[-6,-3.5],[6,-3.5],[12,-3.5],[19,0]]);target(s,[[12,0]]);assert.deepEqual(s.city.completed,['radio']);assert.equal(s.city.credits,100);});
test('Kitchen mission crosses both banks and visits greenhouse, kitchen and storehouse',()=>{const s=fresh();visit(s,'bea');trackStory(s,'kitchen');action(s,'interact');hub(s,'bea');visit(s,'lin');action(s,'interact');hub(s,'lin');visit(s,'bea');target(s,[[-20.5,-1.8]]);path(s,[[-20.5,0]]);hub(s,'bea');visit(s,'tomas');action(s,'interact');assert.deepEqual(s.city.completed,['kitchen']);assert.equal(s.city.credits,80);});
test('Water job changes the actual canal support, requires returning out of it and restores boating',()=>{const s=fresh();visit(s,'otis');trackStory(s,'water');action(s,'interact');target(s,[[5.8,-13]]);for(let i=0;i<130;i++)tick(s,{},1/60);assert.equal(s.water,'low');target(s,[[-.5,-14],[-.5,-7]]);assert.ok(s.y< -1.9);target(s,[[-.5,-14],[5.8,-13]]);for(let i=0;i<130;i++)tick(s,{},1/60);assert.equal(s.water,'high');action(s,'interact');target(s,[[7.1,-10.5]]);assert.deepEqual(s.city.completed,['water']);});
test('Boost release actively stops bicycle movement, does not latch, and permits normal walking afterward',()=>{const s=fresh();action(s,'ride');for(let i=0;i<30;i++)tick(s,{x:-1,boost:true},1/60);assert.ok(s.speed>8);for(let i=0;i<35;i++)tick(s,{},1/60);assert.equal(s.speed,0);const before=s.x;for(let i=0;i<60;i++)tick(s,{},1/60);assert.equal(s.x,before);action(s,'ride');for(let i=0;i<15;i++)tick(s,{z:1},1/60);assert.ok(s.speed>1);assert.equal('boostHeld' in serialize(s),false);});
test('Lantern story reuses an actual repaired connection and keeps its award separate from the original chapter',()=>{const s=fresh();visit(s,'tomas');trackStory(s,'lamps');action(s,'interact');hub(s,'tomas');path(s,north);target(s,[[6,8],[14,8],[14,6]]);target(s,[[14,8],[6,8],[6,-8]]);assert.ok(s.hoist);target(s,[[6,8],[14,8],[14,6]]);path(s,[[14,8],[6,8],[6,-13.5],...north.slice(0,4).reverse()]);target(s,[[-23,-7],[-23,5],[-20.5,4]]);assert.deepEqual(s.city.completed,['lamps']);assert.equal(s.city.credits,120);assert.equal(s.credits,0);});
test('Rooftop garden and cross-ward letters both complete through genuine room-to-room traversal',()=>{for(const job of ['garden','letters']){const s=fresh();const giver=job==='garden'?'lin':'ada';visit(s,giver);trackStory(s,job);action(s,'interact');hub(s,giver);
 if(job==='garden'){target(s,[...loft.slice(0,3),[-14.5,-4.4]]);path(s,[[-12.5,-3.7],[-12.5,5.2],[-12.5,8.2],[-12,15]]);visit(s,'bea');target(s,[[-20.5,-1.8]]);walk(s,-20.5,0);hub(s,'bea');visit(s,'lin');action(s,'interact');}
 else{visit(s,'sal');action(s,'interact');hub(s,'sal');visit(s,'lin');action(s,'interact');hub(s,'lin');visit(s,'tomas');action(s,'interact');}
 assert.deepEqual(s.city.completed,[job]);assert.equal(s.city.credits,stories.find(m=>m.id===job).reward);}});
test('Multi-story progress is retained when changing tracked jobs; gathering requires earned completions',()=>{const s=fresh();trackStory(s,'gathering');assert.equal(s.city.active,null);visit(s,'ada');trackStory(s,'press');action(s,'interact');trackStory(s,'letters');action(s,'interact');assert.equal(s.city.progress.press,0);assert.equal(s.city.progress.letters,0);assert.deepEqual(parse(serialize(s)).city,s.city);});
test('The gathering unlocks after three actually completed stories and ends at the familiar receiving court',()=>{
 const s=fresh();visit(s,'sal');trackStory(s,'radio');action(s,'interact');target(s,[[12,-3.5],[6,-3.5],[-6,-3.5],[-10,-4.5]]);target(s,[[-6,-3.5],[6,-3.5],[12,-3.5],[19,0]]);target(s,[[12,0]]);hub(s,'sal');
 visit(s,'ada');trackStory(s,'press');action(s,'interact');hub(s,'ada');visit(s,'tomas');target(s,[[-9,-17]]);walk(s,-10,-17.5);hub(s,'tomas');visit(s,'ada');target(s,[[-9.6,1.5]]);walk(s,-9.5,4.5);hub(s,'ada');target(s,[[-8.5,15.5]]);walk(s,-12,15);
 visit(s,'ada');trackStory(s,'letters');action(s,'interact');hub(s,'ada');visit(s,'sal');action(s,'interact');hub(s,'sal');visit(s,'lin');action(s,'interact');hub(s,'lin');visit(s,'tomas');action(s,'interact');hub(s,'tomas');assert.equal(s.city.completed.length,3);
 visit(s,'sal');trackStory(s,'gathering');action(s,'interact');hub(s,'sal');visit(s,'bea');action(s,'interact');hub(s,'bea');visit(s,'lin');action(s,'interact');target(s,[[18,-12.5],[6,-13.5],[6,8],[6.5,8]]);
 assert.ok(s.city.completed.includes('gathering'));assert.equal(s.city.credits,435);assert.equal(s.credits,0);const p=parse(serialize(s));action(p,'interact');assert.equal(p.city.credits,435);
});
