import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,tick,action,serialize,parse,save,load,SAVE_KEY,blocked,complete,fixtures,floors,floorHeight,nearby,lineClear} from './core.mjs';
import {openingState,panelsFor,setPanel} from '../design/chapter-contract.mjs';
function travel(s,x,z){for(let i=0;i<15000;i++){const dx=x-s.x,dz=z-s.z,d=Math.hypot(dx,dz);tick(s,{x:d>.2?dx/d:0,z:d>.2?dz/d:0,brake:d<=.2},1/60);if(d<.24&&s.speed<.05)return;}throw Error(`Cannot reach ${x},${z}: ${s.x},${s.y},${s.z} ride=${s.ride}`);}
function run(path){const s=fresh();travel(s,-12,15);action(s,'interact');assert.ok(s.parcel);for(const [x,z]of path)travel(s,x,z);return s;}
const street=[[-23,13],[-23,-7],[-21,-13.5],[6,-13.5],[6,8],[14,8],[14,6]];
const roof=[[-12.5,8.2],[-12.5,5.2],[-12.5,-3.7],[-6,-3.5],[6,-3.5],[12,-3.5],[19.5,1.5],[19.5,10.5],[16,10.5],[14,8],[14,6]];
function finish(s){action(s,'interact');assert.ok(s.delivered);travel(s,14,8);travel(s,6,8);travel(s,5,18);travel(s,4.5,18);action(s,'interact');assert.ok(s.gate);travel(s,0,18);travel(s,-12,15);action(s,'interact');assert.equal(s.credits,600);action(s,'interact');assert.equal(s.credits,600);assert.ok(s.claimed);return s;}
test('Real metre-space street route, far-side gate and exactly-once return reward',()=>finish(run(street)));
test('Real print stair, elevated bridge, loading loft and down stair traverse',()=>{const s=run(roof.slice(0,7));assert.ok(s.y>4.3);for(const [x,z]of roof.slice(7))travel(s,x,z);assert.ok(s.y<.1);finish(s);});
test('Canal route boards, traverses, docks and reaches receiving bench',()=>{const s=run([[-4.4,13]]);action(s,'ride');assert.equal(s.ride,'boat');travel(s,-.5,-11.5);action(s,'ride');assert.equal(s.ride,'foot');travel(s,6,-13);travel(s,6,8);travel(s,14,8);travel(s,14,6);finish(s);});
test('Reversible sluice changes actual support and enables maintenance route',()=>{const s=run(street.slice(0,4));travel(s,5.8,-13);action(s,'interact');assert.ok(s.transition);for(let i=0;i<130;i++)tick(s,{},1/60);assert.equal(s.water,'low');travel(s,-.5,-14);travel(s,-.5,-8);assert.ok(s.y< -1.9);travel(s,-.5,10);travel(s,-.5,16);assert.ok(s.y>-.1);travel(s,-.5,-14);travel(s,5.8,-13);action(s,'interact');for(let i=0;i<130;i++)tick(s,{},1/60);assert.equal(s.water,'high');});
test('Hoist repaired from pump gallery provides a real alternate floor connection',()=>{const s=run(street.slice(0,4));travel(s,6,-8);action(s,'interact');assert.ok(s.hoist);travel(s,6.8,-3.5);action(s,'interact');assert.ok(s.lift);for(let i=0;i<130;i++)tick(s,{},1/60);assert.equal(s.y,4.4);assert.equal(s.lift,null);});
test('Latched door cannot be opened from depot side; distant interact cannot deliver',()=>{const s=fresh();s.parcel=true;travel(s,1.6,18);action(s,'interact');assert.equal(s.gate,false);assert.equal(s.delivered,false);assert.ok(blocked(s,3,0,18));});
test('Overlook does not allow delivery through a wall or from above',()=>{const s=fresh();s.parcel=true;s.x=14;s.y=4.4;s.z=6;action(s,'interact');assert.equal(s.delivered,false);assert.equal(lineClear(s,{x:8,y:1,z:0},{x:12,y:1,z:0}),false);});
test('Bicycle cannot ride up public stairs',()=>{const s=fresh();action(s,'ride');travel(s,-12.5,8.2);for(let i=0;i<150;i++)tick(s,{x:0,z:-1},1/60);assert.equal(s.y,0);assert.ok(s.z>4.5);});
test('World bounds stop walking; fall recovery keeps mission flags',()=>{const s=fresh();s.parcel=true;s.x=23;s.z=19;for(let i=0;i<100;i++)tick(s,{x:1,z:0},1/60);assert.ok(s.x<24);s.y=-10;tick(s,{},1/60);assert.ok(s.y>=0);assert.ok(s.parcel);});
test('Pending water change is safely cancelled by a second interaction and reload',()=>{const s=fresh();s.x=5.8;s.z=-13;action(s,'interact');assert.ok(s.transition);action(s,'interact');assert.equal(s.transition,null);action(s,'interact');const p=parse(serialize(s));assert.equal(p.transition,null);assert.equal(p.water,'high');});
test('Save round trip keeps layout, flags and exactly-once reward',()=>{const s=finish(run(street)),p=parse(serialize(s));assert.equal(p.gate,true);assert.equal(p.credits,600);assert.ok(complete(p));});
function store(){const data=new Map([['svgn.paper-delivery-3d.v1','UNCHANGED ORIGINAL']]);return {data,getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
test('Transactions and backups never touch original-world save',()=>{const m=store(),s=fresh();assert.ok(save(s,m).ok);s.parcel=true;assert.ok(save(s,m).ok);assert.equal(m.getItem('svgn.paper-delivery-3d.v1'),'UNCHANGED ORIGINAL');assert.equal(parse(m.getItem(SAVE_KEY+'.backup')).parcel,false);assert.equal(load(m).state.parcel,true);});
test('Future layout and malformed original block saves rather than silently overwrite',()=>{for(const raw of ['{"v":99}','not-json']){const m=store();m.setItem(SAVE_KEY,raw);assert.ok(load(m).blocked);assert.equal(save(fresh(),m).ok,false);assert.equal(m.getItem(SAVE_KEY),raw);}});
test('Quota exception leaves valid old progress intact',()=>{const m=store(),s=fresh();save(s,m);const old=m.getItem(SAVE_KEY);m.setItem=()=>{throw Error('QuotaExceededError');};s.parcel=true;assert.equal(save(s,m).ok,false);assert.equal(m.getItem(SAVE_KEY),old);});
test('All three openings and switches always leave a presentation aperture',()=>{for(const from of ['both','top','front','bad'])for(const panel of ['top','front'])for(const open of [true,false]){const p=panelsFor(setPanel(from,panel,open));assert.ok(p.topOpen||p.frontOpen);}assert.equal(openingState('bad'),'both');});
test('Surface data is finite and ground/roof geometry has real height separation',()=>{for(const f of floors){assert.ok(f.w>0&&f.d>0);assert.ok(Number.isFinite(floorHeight(f,f.z)));}assert.ok(floors.some(f=>f.y>4));assert.ok(floors.some(f=>f.low));});

test('Throwing never substitutes for parcel handoff or a mechanism action',()=>{const s=fresh();s.x=14;s.z=6;s.parcel=true;action(s,'throw');assert.equal(s.delivered,false);assert.ok(s.paper);});
test('Water transition rechecks the channel before changing its support',()=>{const s=fresh();s.water='low';s.x=5.8;s.z=-13;action(s,'interact');s.x=-.5;s.z=0;s.y=-2;for(let i=0;i<130;i++)tick(s,{},1/60);assert.equal(s.water,'low');assert.equal(s.transition,null);});
test('Autosave during a recovery fall records a valid safe landing',()=>{const s=fresh(),m=store();s.y=-4;s.parcel=true;assert.ok(save(s,m).ok);assert.equal(load(m).state.y,0);assert.equal(load(m).state.parcel,true);});
