import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,tick,action,serialize,parse,save,load,blocked,lineClear,SAVE_KEY} from './core.mjs';
import {QUAY,marketState,resetMarket,advanceMarket,requestPass,marketBlocks,marketStatus,marketActor} from './market.mjs';
const run=(s,n=1,input={})=>{for(let i=0;i<n;i++)tick(s,input,1/60);};
function go(s,x,z,limit=20000){
 for(let i=0;i<limit;i++){const dx=x-s.x,dz=z-s.z,d=Math.hypot(dx,dz);tick(s,{x:d>.18?dx/d:0,z:d>.18?dz/d:0,boost:true,brake:d<=.18},1/60);if(d<.24&&s.speed<.05)return;}
 throw Error(`No arrival at ${x},${z}: ${s.x},${s.y},${s.z}`);
}
function approach(){const s=fresh();go(s,-12,15);action(s,'interact');action(s,'ride');for(const p of [[-23,13],[-23,-7],[-21,-13.5],[-5,-13.5]])go(s,...p);return s;}
function waitLoading(s){for(let i=0;i<2400;i++){const m=marketState(s);if(m.phase==='loading'&&m.timer<.08)return;run(s);}throw Error('No recurring loading opportunity');}
test('Local signal cannot teleport the cart or work from the depot',()=>{const s=fresh(),m=marketState(s),z=m.z;action(s,'bell');assert.equal(m.accepted,0);assert.equal(m.z,z);assert.equal(m.request,0);});
test('Routine recurs, moves continuously and gives at least a usable clear phase',()=>{const s=fresh(),states=new Set();let last=marketState(s).z;for(let i=0;i<2400;i++){run(s);const m=marketState(s);states.add(m.phase);assert.ok(Math.abs(m.z-last)<=QUAY.speed/60+1e-8);last=m.z;}assert.deepEqual([...states].sort(),['clear','loading','returning','withdrawing']);});
test('An occupied return lane makes the porter withdraw instead of crushing or deadlocking',()=>{const s=fresh();s.x=1.201;s.z=-13.5;resetMarket(s);const m=marketState(s);m.z=-16;m.phase='returning';const before=serialize(s);let movedAway=false;for(let i=0;i<400;i++){advanceMarket(s,1/60);movedAway ||= m.phase==='withdrawing';}assert.ok(movedAway);assert.equal(s.x,before.x);assert.equal(s.z,before.z);});
test('A courier stopped just outside collision does not pin the withdrawing cart',()=>{for(const x of[-1.201,1.201]){const s=fresh();s.x=x;s.z=-13.5;const m=resetMarket(s);m.z=QUAY.loadingZ;m.phase='withdrawing';for(let i=0;i<180;i++)advanceMarket(s,1/60);assert.ok(m.z<-16.35);}});
test('Both a person and a bicycle collide with the visible cart; elevated routes do not',()=>{for(const ride of['foot','bicycle']){const s=fresh();s.ride=ride;assert.ok(marketBlocks(s,0,0,QUAY.loadingZ));assert.equal(marketBlocks(s,0,4.4,QUAY.loadingZ),false);assert.equal(marketBlocks(s,2,0,QUAY.loadingZ),false);}});
test('A saved courier on the new stop is not moved or spawned inside the cart',()=>{const s=fresh();s.x=0;s.z=QUAY.loadingZ;const old=serialize(s),p=parse(old);assert.equal(p.x,old.x);assert.equal(p.z,old.z);assert.equal(p.market.phase,'clear');assert.equal(marketBlocks(p,p.x,p.y,p.z),false);});
test('Transient requests, metrics and cart phase never enter the v1 save ledger',()=>{const s=fresh();marketState(s).signals=500;s.market.request=8;const p=serialize(s);assert.equal('market' in p,false);assert.equal(p.layout,1);assert.equal(p.chapter,'lantern-ward-01');const next=parse({...p,market:{phase:'bogus'},porterYield:999});assert.equal(next.market.signals,0);assert.equal(next.market.request,0);});
test('Local X signal works mounted without opening a menu and moves the actual cart',()=>{const s=approach();waitLoading(s);const m=marketState(s),z=m.z;action(s,'interact');assert.equal(m.accepted,1);assert.equal(m.z,z);run(s,30);assert.ok(m.z<z);assert.equal(s.ride,'bicycle');go(s,6,-13.5);assert.ok(marketStatus(s));assert.ok(s.parcel);assert.equal(s.credits,0);});
test('Unsignaled crossing remains completable by a patient rider',()=>{const s=approach();waitLoading(s);go(s,6,-13.5);assert.equal(s.market.accepted,0);assert.equal(s.ride,'bicycle');assert.ok(s.x>5.7);});
test('Marked north loop bypasses every loading phase without signal or dismount',()=>{for(const delay of[0,1.5,4,6,8,10]){const s=approach();waitLoading(s);run(s,Math.round(delay*60));for(const p of[[-1.85,-13.5],[-1.85,-20],[1.85,-20],[1.85,-14],[6,-14]])go(s,...p);assert.equal(s.ride,'bicycle');assert.equal(s.market.accepted,0);assert.ok(s.x>5.7);}});
test('Roof observation has a real sightline to the loading crossing',()=>{const s=fresh();assert.ok(lineClear(s,{x:-7,y:5.5,z:-4},{x:0,y:1.5,z:-14.05}));assert.equal(marketBlocks(s,0,4.4,-14.05),false);});
test('Cart and porter occupy the same inspected metre-space in every read',()=>{const s=fresh();run(s,360);assert.equal(marketActor(s).z,marketState(s).z-1.05);const before=JSON.stringify(serialize(s));for(let i=0;i<30;i++)marketStatus(s);assert.equal(JSON.stringify(serialize(s)),before);});
