import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,action,tick,serialize,parse,save,load,SAVE_KEY,blocked,lineClear,support,floorHeight,surfaces} from './core.mjs';
import {trackStory,storyTarget} from './city.mjs';
import {watchState,watchRuntime,watchInspect,parseWatch,validGrapple,GRAPPLE_ANCHORS} from './watch.mjs';
const api={blocked,lineClear,support,floorHeight,surfaces};
const idle=(s,n=60,input={})=>{for(let i=0;i<n;i++)tick(s,input,1/60);};
function travel(s,x,z){for(let i=0;i<8000;i++){const dx=x-s.x,dz=z-s.z,d=Math.hypot(dx,dz);tick(s,{x:d>.2?dx/d:0,z:d>.2?dz/d:0,brake:d<=.2,guard:true},1/60);if(d<.24&&s.speed<.05)return;}throw Error(`Cannot reach ${x},${z}: ${s.x},${s.y},${s.z}`);}
function startCase(){const s=fresh();trackStory(s,'watch');travel(s,-10,14);action(s,'interact');assert.equal(s.watch.stage,1);return s;}
function clue(s){travel(s,-12.5,8.2);travel(s,-12.5,6);travel(s,-9.6,6);travel(s,-9.6,2.3);action(s,'scan');assert.equal(s.watch.stage,2);}
function returnHome(s){travel(s,19.5,1.5);travel(s,19.5,10.5);travel(s,16,10.5);travel(s,14,8);travel(s,6,8);travel(s,4.5,18);action(s,'interact');assert.ok(s.gate);travel(s,0,18);travel(s,-10,14);action(s,'interact');assert.equal(s.watch.stage,4);assert.equal(s.watch.credits,180);action(s,'interact');assert.equal(s.watch.credits,180);}
test('Real-input investigation, rooftop route and return resolve without combat',()=>{const s=startCase();clue(s);travel(s,-12.5,5.2);travel(s,-12.5,-3.7);travel(s,-6,-3.5);travel(s,6,-3.5);travel(s,12,-3.5);travel(s,12,-2.2);action(s,'interact');assert.equal(s.watch.stage,3);assert.equal(watchInspect(s).strikes,0);returnHome(s);const p=parse(serialize(s));assert.equal(p.watch.credits,180);assert.equal(p.credits,0);assert.equal(p.city.credits,0);});
test('Kit enables a real safe grapple; airborne serialization restores its departure',()=>{const s=startCase();clue(s);assert.ok(validGrapple(s,GRAPPLE_ANCHORS[0],api));const from=[s.x,s.y,s.z];action(s,'grapple');assert.ok(watchRuntime(s).travel);idle(s,15);const m=new Map(),store={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};assert.ok(save(s,store).ok);const p=load(store).state;assert.deepEqual([p.x,p.y,p.z],from);idle(s,60);assert.equal(watchRuntime(s).travel,null);assert.equal(s.y,4.4);assert.equal(s.x,GRAPPLE_ANCHORS[0].x);assert.ok(s.distance>8);});
test('Explicit grapple geometry fixtures reject floor undersides, out-of-range and riding',()=>{const s=fresh();s.watch.stage=1;s.x=11;s.z=0;assert.equal(validGrapple(s,GRAPPLE_ANCHORS[1],api),false);s.x=-10;s.z=14;assert.equal(validGrapple(s,GRAPPLE_ANCHORS[0],api),false);s.x=-9.6;s.z=2.3;s.ride='bicycle';assert.equal(validGrapple(s,GRAPPLE_ANCHORS[0],api),false);});
test('Real-input ground encounter requires counter/pulse, disables both machines and retains reward',()=>{const s=startCase();action(s,'watch-route');for(const [x,z]of[[-23,13],[-23,-7],[-21,-13.5],[5,-13.5]])travel(s,x,z);action(s,'scan');assert.equal(s.watch.stage,2);
 // The driver aims at read-only observed targets, then issues real movement,
 // guard, pulse and strike inputs. It does not alter HP or actor coordinates.
 for(let i=0;i<2400&&watchRuntime(s).sentries.some(e=>e.hp>0);i++){
  const e=watchRuntime(s).sentries.filter(e=>e.hp>0).sort((a,b)=>Math.hypot(s.x-a.x,s.z-a.z)-Math.hypot(s.x-b.x,s.z-b.z))[0];
  const dx=e.x-s.x,dz=e.z-s.z,d=Math.hypot(dx,dz);const ray={origin:{x:s.x,y:s.y+1,z:s.z},direction:{x:dx/(d||1),y:0,z:dz/(d||1)}};
  tick(s,{x:d>1.35?dx/d:0,z:d>1.35?dz/d:0,guard:true},1/60);action(s,'pulse',ray);action(s,'strike',ray);
 }
 assert.ok(watchRuntime(s).sentries.every(e=>e.hp===0));travel(s,6.5,-9.8);action(s,'interact');assert.equal(s.watch.stage,3);travel(s,6,8);travel(s,4.5,18);action(s,'interact');travel(s,0,18);travel(s,-10,14);action(s,'interact');assert.equal(s.watch.credits,180);assert.ok(watchRuntime(s).strikes>=6);});
test('Safety and combat fixtures: no civilian targeting, no damage outside tracked optional case, shield rule',()=>{const s=fresh();action(s,'strike');idle(s,180);assert.equal(watchRuntime(s).health,5);assert.equal(s.watch.credits,0);s.watch={v:1,tracking:true,stage:2,route:'ground',credits:0};const r=watchRuntime(s),e=r.sentries[1];s.x=e.x;s.z=e.z+1.5;action(s,'strike');assert.equal(e.hp,3);action(s,'pulse');idle(s,25,{guard:true});action(s,'strike');assert.ok(e.hp<3);trackStory(s,'main');const hp=r.health;idle(s,600);assert.equal(r.health,hp);});
test('Setback recovery is an explicit action and never erases other earned work',()=>{const s=startCase();const r=watchRuntime(s);s.parcel=true;s.watch.stage=2;r.knockedOut=true;r.health=0;const before=serialize(s);idle(s,60,{x:1});assert.equal(s.x,before.x);action(s,'watch-recover');assert.equal(r.health,5);assert.equal(s.parcel,true);assert.equal(s.watch.stage,2);assert.equal(s.watch.credits,0);});
test('Old saves initialize optional case; malformed/future Watch ledger blocks rather than downgrades',()=>{const old=serialize(fresh());delete old.watch;assert.equal(parse(old).watch.stage,0);for(const w of[{v:2},{v:1,stage:4,credits:0,route:'roof',tracking:false},{v:1,stage:2,credits:180,route:'roof',tracking:true}])assert.throws(()=>parse({...old,watch:w}));assert.throws(()=>parse({...old,watch:{v:1,stage:2,credits:0,route:'roof',tracking:true},city:{v:1,active:'press',completed:[],progress:{},credits:0}}));});
test('Tracking a case grants no kit, clues, currency or inventory and shares one objective',()=>{const s=fresh();const before=serialize(s);trackStory(s,'watch');assert.equal(s.watch.stage,0);assert.equal(s.watch.credits,0);assert.equal(storyTarget(s).id,'watch-desk');trackStory(s,'press');assert.equal(s.watch.tracking,false);assert.equal(s.parcel,before.parcel);assert.equal(s.credits,before.credits);assert.equal(s.city.credits,before.city.credits);});
test('Combat transients, smoke, tracker poses and cooldowns never enter saved data',()=>{const s=startCase();action(s,'smoke');const text=JSON.stringify(serialize(s));assert.ok(!text.includes('sentries'));assert.ok(!text.includes('cooldown'));assert.ok(!text.includes('health'));const p=parse(text);assert.equal(watchRuntime(p).smoke,0);assert.equal(watchRuntime(p).health,5);});

test('Restored relay remains visibly disabled after a legitimate completed-case reload',()=>{const s=startCase();clue(s);travel(s,-12.5,5.2);travel(s,-12.5,-3.7);travel(s,-6,-3.5);travel(s,6,-3.5);travel(s,12,-3.5);action(s,'interact');assert.equal(s.watch.stage,3);const p=parse(serialize(s));assert.ok(watchRuntime(p).sentries.every(e=>e.hp===0&&e.phase==='disabled'));});

test('Counter timing fixture distinguishes a fresh guard from an indefinitely held block',()=>{const s=fresh();s.watch={v:1,tracking:true,stage:2,route:'ground',credits:0};const r=watchRuntime(s),e=r.sentries[0];s.x=e.x;s.z=e.z+1.4;idle(s,100,{guard:true});const n=r.counters;idle(s,180,{guard:true});assert.equal(r.counters,n);assert.equal(r.health,5);tick(s,{guard:false},1/60);for(let i=0;i<400&&r.counters===n;i++){const cue=e.phase==='windup'&&e.timer>.3;tick(s,{guard:cue},1/60);}assert.ok(r.counters>n);});
