/* Independent cubic handles are the authoring source; sampled points remain the
 * backwards-compatible collision format. Import/export never silently fits a path. */
(function(root){'use strict';
 const copy=v=>JSON.parse(JSON.stringify(v)),mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t),dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
 const MODES=['corner','smooth','symmetric'];
 const node=(p,i=[0,0],o=[0,0],mode='corner')=>({p:[...p],i:[...i],o:[...o],mode});
 const plus=(a,b)=>[a[0]+b[0],a[1]+b[1]],minus=(a,b)=>[a[0]-b[0],a[1]-b[1]];
 function valid(nodes){if(!Array.isArray(nodes)||nodes.length<2||nodes.length>1024)throw Error('A Bezier path requires 2-1024 anchors.');for(const n of nodes)if(!MODES.includes(n.mode)||![n.p,n.i,n.o].every(a=>Array.isArray(a)&&a.length===2&&a.every(v=>Number.isFinite(v)&&Math.abs(v)<=50000)))throw Error('Invalid Bezier anchor or tangent.');return nodes;}
 function controls(a,b){return [a.p,plus(a.p,a.o),plus(b.p,b.i),b.p];}
 function evaluate(c,t){const a=mix(c[0],c[1],t),b=mix(c[1],c[2],t),d=mix(c[2],c[3],t);return mix(mix(a,b,t),mix(b,d,t),t);}
 function sample(nodes){valid(nodes);const pts=[[...nodes[0].p]];for(let j=1;j<nodes.length;j++){const c=controls(nodes[j-1],nodes[j]),len=dist(c[0],c[1])+dist(c[1],c[2])+dist(c[2],c[3]);const n=Math.max(4,Math.min(96,Math.ceil(len/9)));for(let i=1;i<=n;i++){const q=evaluate(c,i/n);if(dist(q,pts.at(-1))>.00001)pts.push(q);}}if(pts.length>6000)throw Error('Curve exceeds 6000 samples; use fewer anchors.');return pts;}
 function rebuild(p){p.points=sample(p.bezier);p.anchors=null;return p;}
 function split(nodes,index,t=.5){valid(nodes);if(index<0||index>=nodes.length-1||t<=0||t>=1)throw Error('Choose an internal point of a segment.');const a=nodes[index],b=nodes[index+1],c=controls(a,b),ab=mix(c[0],c[1],t),bc=mix(c[1],c[2],t),cd=mix(c[2],c[3],t),abc=mix(ab,bc,t),bcd=mix(bc,cd,t),p=mix(abc,bcd,t);a.o=minus(ab,a.p);b.i=minus(cd,b.p);a.mode=b.mode='smooth';nodes.splice(index+1,0,node(p,minus(abc,p),minus(bcd,p),'smooth'));return index+1;}
 function handle(n,which,v,breakAlignment=false){n[which]=[...v];if(breakAlignment)n.mode='corner';const other=which==='i'?'o':'i';if(n.mode==='symmetric')n[other]=[-v[0],-v[1]];else if(n.mode==='smooth'){const r=Math.hypot(...n[other]),l=Math.hypot(...v);if(l>1e-9)n[other]=[-v[0]*r/l,-v[1]*r/l];}return n;}
 function mode(n,value){if(!MODES.includes(value))throw Error('Unknown anchor mode.');n.mode=value;if(value!=='corner'){let o=n.o;if(Math.hypot(...o)<.001)o=[-n.i[0],-n.i[1]];handle(n,'o',o);}return n;}
 function arc(cx,cy,rx,ry,start,sweep){if(![cx,cy,rx,ry,start,sweep].every(Number.isFinite)||rx<1||ry<1||Math.abs(sweep)<1||Math.abs(sweep)>360)throw Error('Arc radius must be positive; sweep is 1-360 degrees.');const count=Math.ceil(Math.abs(sweep)/90),step=sweep/count*Math.PI/180,first=start*Math.PI/180,nodes=[];for(let j=0;j<=count;j++){const a=first+j*step,p=[cx+rx*Math.cos(a),cy+ry*Math.sin(a)],k=4/3*Math.tan(step/4),v=[-Math.sin(a)*rx*k,Math.cos(a)*ry*k];nodes.push(node(p,j?[ -v[0],-v[1]]:[0,0],j<count?v:[0,0],'smooth'));}return nodes;}
 function fromPolyline(points){/* Exact straight segments, never an unreported fit. */return points.map((p,j)=>node(p,j?minus(mix(p,points[j-1],1/3),p):[0,0],j<points.length-1?minus(mix(p,points[j+1],1/3),p):[0,0],'corner'));}
 function convert(p){if(p.bezier)return p;if(p.anchors){p.bezier=p.anchors.map(a=>node(a.slice(0,2),[-a[2],-a[3]],[a[2],a[3]],'symmetric'));}else p.bezier=fromPolyline(p.points);return rebuild(p);}
 function fit(p,tolerance=3){/* Explicit optional approximation, committed as one undoable edit. */const pts=p.points;function reduce(a){if(a.length<=2)return a;const x=a[0],y=a.at(-1),dx=y[0]-x[0],dy=y[1]-x[1],l=dx*dx+dy*dy;let best=-1,at=0;for(let i=1;i<a.length-1;i++){const t=Math.max(0,Math.min(1,((a[i][0]-x[0])*dx+(a[i][1]-x[1])*dy)/(l||1))),d=Math.hypot(a[i][0]-x[0]-t*dx,a[i][1]-x[1]-t*dy);if(d>best){best=d;at=i;}}return best<=tolerance?[x,y]:reduce(a.slice(0,at+1)).slice(0,-1).concat(reduce(a.slice(at)));}const reduced=reduce(pts);p.bezier=reduced.map((a,j)=>{const before=reduced[Math.max(0,j-1)],after=reduced[Math.min(reduced.length-1,j+1)],v=[(after[0]-before[0])/6,(after[1]-before[1])/6];return node(a,j?[-v[0],-v[1]]:[0,0],j<reduced.length-1?v:[0,0],'smooth');});delete p.arc;return rebuild(p);}
 function transform(p,op,bounds){if(!p.bezier)return false;const {dx=0,dy=0,angle=0,sx=1,sy=1}=op,b=bounds||{x:0,y:0,w:0,h:0},o=op.origin||[b.x+b.w/2,b.y+b.h/2],c=Math.cos(angle),s=Math.sin(angle),vector=q=>[q[0]*sx*c-q[1]*sy*s,q[0]*sx*s+q[1]*sy*c];for(const n of p.bezier){n.p=plus(plus(vector(minus(n.p,o)),o),[dx,dy]);n.i=vector(n.i);n.o=vector(n.o);}if(p.arc){const center=plus(plus(vector(minus(p.arc.center,o)),o),[dx,dy]);if(angle||sx<0||sy<0){delete p.arc;}else Object.assign(p.arc,{center,rx:p.arc.rx*sx,ry:p.arc.ry*sy});}rebuild(p);return true;}
 function reverse(p){if(!p.bezier)return false;p.bezier.reverse();for(const a of p.bezier)[a.i,a.o]=[a.o,a.i];delete p.arc;rebuild(p);return true;}
 const API={node,MODES,valid,sample,evaluate,controls,split,handle,mode,arc,convert,fit,rebuild,transform,reverse,copy};root.BezierCore=Object.freeze(API);if(typeof module!=='undefined')module.exports=API;
 if(!root.WorkshopCore)return;const W=root.WorkshopCore;
 const newParts=[['arc45','Eighth arc',45],['arc72','Fifth arc',72],['arc90','Quarter arc',90],['arc180','Half arc',180],['arc270','Three-quarter arc',270]].map(([id,name,sweep])=>({id,name,sweep,hint:`Editable ${sweep}-degree Bezier arc; independent tangents.`}));
 function validate(d){W.validate(d);for(const p of d.paths){if(p.bezier)valid(p.bezier);if(p.arc&&(!['rx','ry','start','sweep'].every(k=>Number.isFinite(p.arc[k])&&Math.abs(p.arc[k])<=50000)||!Array.isArray(p.arc.center)||p.arc.center.length!==2||!p.arc.center.every(v=>Number.isFinite(v)&&Math.abs(v)<=50000)||p.arc.rx<1||p.arc.ry<1||Math.abs(p.arc.sweep)<1||Math.abs(p.arc.sweep)>360))throw Error('Invalid arc settings.');}return d;}
 root.WorkshopCore=Object.freeze({...W,PARTS:[...W.PARTS,...newParts],validate,
  piece(id,x,y){const spec=newParts.find(p=>p.id===id);if(!spec)return W.piece(id,x,y);const p={points:[],anchors:null,meta:{version:1,kind:'open',id:'piece',stage:0,begin:0,end:1,label:spec.name},arc:{center:[x,y-130],rx:130,ry:130,start:90,sweep:-spec.sweep}};p.bezier=arc(...p.arc.center,p.arc.rx,p.arc.ry,p.arc.start,p.arc.sweep);return rebuild(p);},
  decode(code){const d=W.decode(code);const author=d.extra.cb;if(author!==undefined){if(!Array.isArray(author)||author.length>d.paths.length)throw Error('Invalid Bezier metadata.');author.forEach((b,i)=>{if(!b)return;valid(b.nodes);d.paths[i].bezier=copy(b.nodes);if(b.arc)d.paths[i].arc=copy(b.arc);const points=sample(b.nodes);if(points.length!==d.paths[i].points.length||points.some((q,k)=>dist(q,d.paths[i].points[k])>.01)){delete d.paths[i].bezier;delete d.paths[i].arc;}});}return validate(d);},
  encode(d){validate(d);const shadow={...d,extra:{...d.extra}};delete shadow.extra.cb;const code=W.encode(shadow);if(!d.paths.some(p=>p.bezier))return code;const [a,b]=code.split('.'),meta=JSON.parse(decodeURIComponent(escape(atob(a))));meta.cb=d.paths.map(p=>p.bezier?{nodes:p.bezier,...(p.arc?{arc:p.arc}:{})}:null);return btoa(unescape(encodeURIComponent(JSON.stringify(meta))))+'.'+b;},
  transform(p,op){if(!transform(p,op,W.bounds([p])))W.transform(p,op);return p;},
  deform(p,index,dx,dy){delete p.bezier;delete p.arc;return W.deform(p,index,dx,dy);},
  join(d,ids){ids.forEach(i=>{delete d.paths[i].bezier;delete d.paths[i].arc;});return W.join(d,ids);}
 });
})(globalThis);
