/* Read-only route rehearsal on the real Workshop document. No analysis plays
 * the game, alters the draft, or grants a successful runtime completion. */
(function(){'use strict';function boot(){
 const state={report:null,code:null,route:'sky',busy:false,stale:true};const host=document.createElement('section');host.id='phrase-coach';host.innerHTML='<h2>Flow Coach</h2><p>Trace a complete ride, not just a line between nearby ramps.</p><select id="phrase-route" aria-label="Route to rehearse"></select><button id="phrase-analyze">Rehearse current draft</button><label><input id="phrase-overlay" type="checkbox" checked> Show the carried-state trail</label><p id="phrase-status" role="status">Model rehearsal is not a human fun rating or a live playthrough.</p><button id="phrase-export">Export rehearsal</button><p class="phrase-scope">A 20px rider envelope, drawn road bodies, and actual rail/flight/grapple equations are checked. Enemies, road-entry timing and browser rendering need live playtesting.</p>';
 document.querySelector('.maker-inspector').prepend(host);const select=host.querySelector('select');for(const r of PhraseData.routes){const op=document.createElement('option');op.value=r.id;op.textContent=r.name;select.append(op);}
 const stage=document.getElementById('maker-canvas').parentElement,c=document.createElement('canvas');c.id='phrase-trace';c.setAttribute('aria-hidden','true');stage.append(c);const ctx=c.getContext('2d');
 function current(){const s=RouteWorkshop.state;return s.history?.items[s.history.index]||null;}
 function status(text){document.getElementById('phrase-status').textContent=text;}
 function analyze(){const s=RouteWorkshop.state;if(!s.doc||state.busy)return;state.busy=true;state.stale=true;status('Rehearsing the full route with carried position and velocity...');const code=current(),route=PhraseData.routes.find(r=>r.id===select.value);requestAnimationFrame(()=>{try{
   if(s.doc.paths.some(p=>p.meta?.kind!=='open'))throw Error('Timed full-loop pieces need a separate controller; they are not marked verified by this open-road rehearsal.');
   if(!s.doc.paths.some(p=>p.meta?.id===route.entry))throw Error('This route entrance is absent. Load Sunrise Borough to inspect its authored routes.');
   const report=PhrasePlayback.run(s.doc.paths,{...route,solidRoads:true,ground:s.doc.extra.gp?.ground*36||2160,width:s.doc.w*36});state.report=report;state.code=code;state.route=route.id;state.stale=current()!==code;
   const exact=route.expected.every(id=>report.visited.includes(id)),brushes=report.events.filter(e=>e.type==='brush').length;
   status(`${report.completed?'Returns to road':'Does not finish the modeled route'} / ${report.visited.length} surfaces / ${brushes} rail-body bumps / ${exact?'intended sequence reached':'intended sequence incomplete'}. This is a geometry rehearsal, not a live finish.`);
  }catch(e){state.report=null;status(e.message);}finally{state.busy=false;}});}
 document.getElementById('phrase-analyze').onclick=analyze;select.onchange=()=>{state.stale=true;status('Route changed. Rehearse to show its own carried-state path.');};
 document.getElementById('phrase-export').onclick=()=>{if(!state.report||state.stale){status('Rehearse the current draft before exporting evidence.');return;}const blob=new Blob([JSON.stringify({scope:'Geometry-only carried-state rehearsal; not a native browser completion',route:state.route,report:state.report},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='route-rehearsal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const render=window.render;window.render=function(){render();if(!RouteWorkshop.active)return;const s=RouteWorkshop.state,stale=!!s.drag||state.code!==current();if(stale&&!state.stale&&state.report){state.stale=true;status('Draft changed. The old path is invalid; rehearse again.');}
  const r=c.parentElement.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(r.width*dpr)||c.height!==Math.round(r.height*dpr)){c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);
  if(!state.report||state.stale||!document.getElementById('phrase-overlay').checked)return;ctx.save();ctx.scale(s.view.zoom,s.view.zoom);ctx.translate(-s.view.x,-s.view.y);ctx.lineWidth=2.2/s.view.zoom;ctx.strokeStyle='#80eedb';ctx.setLineDash([8/s.view.zoom,5/s.view.zoom]);ctx.beginPath();state.report.trace.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();ctx.setLineDash([]);
  for(let i=15;i<state.report.trace.length;i+=28){const p=state.report.trace[i],a=state.report.trace[i-1],angle=Math.atan2(p[1]-a[1],p[0]-a[0]),k=7/s.view.zoom;ctx.fillStyle='#defbdc';ctx.beginPath();ctx.moveTo(p[0]+Math.cos(angle)*k,p[1]+Math.sin(angle)*k);ctx.lineTo(p[0]+Math.cos(angle+2.5)*k,p[1]+Math.sin(angle+2.5)*k);ctx.lineTo(p[0]+Math.cos(angle-2.5)*k,p[1]+Math.sin(angle-2.5)*k);ctx.fill();}ctx.restore();
 };
 window.FlowCoach={state,analyze};
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();
