/* Seated stereo diorama of the existing game, not a new game or save system.
 * Controller and native hand-select rays use the same real DOM actions.
 * Three r177's XRManager requires its WebGL backend: entry is explicit.
 */
import * as T from './vendor/three.webgpu.js';
import {addOverlay,POINTER_ORDER} from './xr-overlay.mjs';
import {protectOpaqueXRFramebuffer} from './xr-webgl-compat.mjs';
let restoreFramebuffer=()=>{};
import {mappedPad,sourcesNeutral,pointInRects} from './xr-input-core.mjs';
const $=id=>document.getElementById(id),panel=()=>window.SkyCycleFlightDeck?.topPanel(),fd=()=>window.SkyCycleFlightDeck;
let session=null,starting=false,presenting=false,neutral=true,renderer=null,originalRender=null,originalScene=null,oldView=null;
let xrScene=null,anchor=null,world=null,camera=null,ui=null,texture=null,context=null,canvas=null,reference=null,rects=[],page=0,lastPanel=null,lastUI=0,lastFrame=null,recenter=true;
let held=new Set(),suppressed=new Set(),presses=new Map(),visuals=new Map(),ctxSource=null,ctxDown=false,frameCount=0,eyeCount=0,errorText='';
const ctl=new T.Matrix4(),rotation=new T.Quaternion(),raycaster=new T.Raycaster(),vector=new T.Vector3(),forward=new T.Vector3(0,0,-1);
const guide=document.createElement('dialog');guide.id='sky-xr-guide';guide.setAttribute('aria-labelledby','sky-xr-title');guide.style.cssText='max-width:560px;width:90%;background:#13263b;color:#f0f6ff;border:1px solid #8edccc;border-radius:16px;padding:22px';
guide.innerHTML='<h2 id="sky-xr-title">Quest / immersive XR</h2><p>A seated, side-on 3D diorama of Sky Cycle. Your saves and original routes stay in the same game. XR does not add first-person swimming.</p><p>Left stick: ride / reel. Right A: jump. Right trigger: paper. Right grip: whip. Left trigger: boost. Left X: nearby interaction. Right B: pause / back. Left Y: Flight Deck.</p><p>Point either controller and squeeze its trigger to choose a menu item. With hand tracking, point and pinch to choose; hold a Ride arrow to move. The in-world action bar supplies jump, boost, paper, whip, use and pause. Release before changing screens.</p><p>XR uses the WebGL renderer. Switching from WebGPU reloads the page and restarts the current route without banking unfinished progress. Save unsaved Workshop work first. Keep enough clear space and remain seated.</p><p id="sky-xr-status" role="status">Checking immersive support...</p><div style="display:flex;gap:12px;flex-wrap:wrap"><button id="sky-xr-enter" class="delivery-btn" disabled>Enter XR</button><button id="sky-xr-cancel" class="delivery-btn">Back</button></div>';
document.body.append(guide);$('sky-xr-cancel').onclick=()=>guide.close();guide.addEventListener('cancel',e=>{e.preventDefault();guide.close();});
function status(text){errorText=text;$('sky-xr-status').textContent=text;}
async function support(){try{const ok=!!navigator.xr&&await navigator.xr.isSessionSupported('immersive-vr');$('sky-xr-enter').disabled=!ok;status(ok?'Tracked controllers and hand tracking are supported by this implementation. Physical Quest 3 qualification remains open.':'Immersive VR is unavailable in this browser. Ordinary keyboard, touch and Xbox play are unchanged.');}catch(e){status('XR support could not be checked: '+e.message);}}
function show(){if(presenting)return;if(!guide.open){if(window.__delivery?.state&&!__delivery.paused&&!__delivery.state.menu)__delivery.act('pause');guide.showModal();$('sky-xr-cancel').focus();}support();}
function mount(){for(const [id,selector]of[['sky-xr-open','#delivery-header .actions'],['sky-xr-pause','#delivery-pause .delivery-pause-card'],['sky-xr-deck','#flight-deck .fd-actions']]){const root=document.querySelector(selector);if(root&&!$(id)){const b=document.createElement('button');b.id=id;b.className='delivery-btn';b.textContent='Quest / XR';b.onclick=show;root.append(b);}}}
mount();
function release(){held.clear();presses.clear();suppressed.clear();ctxDown=false;neutral=true;fd()?.resetInput();}
function pause(){if(window.__delivery?.state&&!__delivery.state.menu&&!__delivery.paused)__delivery.act('pause');release();}
function disposeObject(root){const geometries=new Set(),materials=new Set();root?.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])if(m)materials.add(m);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}
function makeStage(){xrScene=new T.Scene();xrScene.background=new T.Color('#112239');anchor=new T.Group();xrScene.add(anchor);world=new T.Group();world.scale.setScalar(.0025);anchor.add(world);world.add(originalScene);camera=new T.PerspectiveCamera(55,1,.05,30);xrScene.add(camera);
 canvas=document.createElement('canvas');canvas.width=1200;canvas.height=900;context=canvas.getContext('2d');texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;ui=new T.Mesh(new T.PlaneGeometry(1.5,1.125),new T.MeshBasicNodeMaterial({map:texture,transparent:false,depthTest:false,depthWrite:false}));ui.renderOrder=9999;ui.frustumCulled=false;addOverlay(T,anchor,ui);ui.position.set(0,-.15,-1.45);lastPanel=null;recenter=true;}
function text(s,x,y,max,width=1060,font=23){context.font=`${font}px sans-serif`;const lines=[];let line='';for(const word of String(s).replace(/\s+/g,' ').split(' ')){if(context.measureText(line+' '+word).width>width&&line){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);for(let i=0;i<Math.min(lines.length,max);i++)context.fillText(lines[i],x,y+i*(font+7));return Math.min(lines.length,max)*(font+7);}
function button(label,x,y,w,h,action,hover=null){context.fillStyle='#23425c';context.fillRect(x,y,w,h);context.strokeStyle='#8edccc';context.lineWidth=2;context.strokeRect(x,y,w,h);context.fillStyle='#f4fbff';text(label,x+14,y+31,2,w-24,22);rects.push({x,y,w,h,label,action,hover});}
function makeMenu(now,force=false){const current=panel();if(current!==lastPanel){lastPanel=current;page=0;release();lastUI=0;}if(!force&&now-lastUI<200)return;lastUI=now;rects=[];context.fillStyle='#132b40';context.fillRect(0,0,1200,900);context.fillStyle='#f4fbff';
 if(current){ui.position.set(0,-.08,-1.8);ui.scale.setScalar(.95);const title=current.querySelector('h1,h2,h3')?.textContent||current.getAttribute('aria-label')||'Sky Cycle menu';text(title,35,44,1,1090,29);
  const elements=(fd()?.controls(current)||[]).filter(el=>el.id!=='sky-xr-enter');
  const entries=[];for(const el of elements){let label=el.textContent?.trim()||el.getAttribute('aria-label')||el.name||el.id;if(el.matches('input[type="range"],select')){label=el.getAttribute('aria-label')||current.querySelector(`label[for="${CSS.escape(el.id)}"]`)?.textContent||el.id;for(const dir of [-1,1])entries.push({el,label:`${label}: ${el.value} ${dir<0?'minus':'plus'}`,fn:()=>{if(el instanceof HTMLSelectElement){const opts=[...el.options].map((o,i)=>!o.disabled?i:-1).filter(i=>i>=0);el.selectedIndex=opts[Math.max(0,Math.min(opts.length-1,opts.indexOf(el.selectedIndex)+dir))];}else{el.value=String(Math.max(Number(el.min||0),Math.min(Number(el.max||100),Number(el.value)+dir*(Number(el.step)||1))));}el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}});}else if(el.tagName==='A')entries.push({el,label:label+' (exit XR to open)',fn:()=>status('Exit XR before following an external link.')});else entries.push({el,label,fn:()=>{if(!el.disabled){el.focus();el.click();}}});}
  const pages=Math.max(1,Math.ceil(entries.length/6));
  const paragraphs=[...current.querySelectorAll('p')].filter(el=>el.getClientRects().length>0).map(el=>el.textContent.trim()).join(' ');
  const chunks=paragraphs.match(/.{1,270}(?:\s|$)/g)||[paragraphs];page=Math.min(page,Math.max(pages,chunks.length)-1);const desc=chunks[Math.min(page,chunks.length-1)]||'';
  text(desc,35,90,5,1120,22);
  entries.slice(page*6,page*6+6).forEach((e,i)=>button(e.label,35,270+i*77,1130,67,()=>{if(panel()===current&&!elements.find(el=>el.textContent?.trim()===e.label)?.disabled)e.fn();},()=>e.el?.focus({preventScroll:true})));
  button('Previous',35,742,330,62,()=>{page=(page-1+Math.max(pages,chunks.length))%Math.max(pages,chunks.length);});button(`Page ${page+1} / ${Math.max(pages,chunks.length)} - Next`,380,742,435,62,()=>{page=(page+1)%Math.max(pages,chunks.length);});button('Back',830,742,335,62,()=>fd()?.back(current));
 }else{ui.position.set(0,-.45,-1.6);ui.scale.setScalar(.8);text('SKY CYCLE / seated riding',35,50,1,1100,30);text('Point + hold a Ride arrow. Pinch or trigger to choose. Keep hands clear of the headset.',35,100,2,1100,24);
  const items=[['Ride left','left'],['Ride right','right'],['Jump','jump'],['Paper','paper'],['Whip','whip'],['Boost','boost'],['Use nearby','use'],['Pause','pause'],['Portal atlas','portal']];
  items.forEach(([label,id],i)=>button(label,35+(i%3)*382,220+Math.floor(i/3)*153,365,130,id));
 }
 button('Recenter',35,828,530,58,()=>{recenter=true;});button('Exit XR',585,828,580,58,()=>{pause();session?.end().catch(e=>status(e.message));});texture.needsUpdate=true;
}
function tracked(source){let entry=visuals.get(source);if(entry)return entry;
 const root=new T.Group();xrScene.add(root);const ray=new T.Mesh(new T.CylinderGeometry(.002,.002,1,6),new T.MeshBasicNodeMaterial({color:source.handedness==='left'?'#79dacb':'#ffc878'}));ray.rotation.x=Math.PI/2;ray.position.z=-.5;root.add(ray);
 const grip=new T.Mesh(new T.SphereGeometry(.016,8,6),new T.MeshBasicNodeMaterial({color:'#e5f7ff'}));xrScene.add(grip);const joints=[];
 if(source.hand){const g=new T.SphereGeometry(1,6,4),mat=new T.MeshBasicNodeMaterial({color:'#a5e8dd'});for(let i=0;i<25;i++){const m=new T.Mesh(g,mat);xrScene.add(m);joints.push(m);}}
 const dot=new T.Mesh(new T.SphereGeometry(.009,8,6),new T.MeshBasicNodeMaterial({color:'#ffffff',depthTest:false}));addOverlay(T,xrScene,dot,POINTER_ORDER);entry={root,grip,joints,dot,ray};visuals.set(source,entry);return entry;
}
function poseObject(object,pose){object.visible=!!pose;if(pose){object.matrix.fromArray(pose.transform.matrix);object.matrix.decompose(object.position,object.quaternion,object.scale);}}
function updateTracking(frame){for(const [source,v] of visuals)if(![...session.inputSources].includes(source)){xrScene.remove(v.root,v.grip,v.dot.parent,...v.joints);disposeObject(v.dot);disposeObject(v.root);disposeObject(v.grip);for(const j of v.joints)disposeObject(j);visuals.delete(source);}
 for(const source of session.inputSources){const v=tracked(source);poseObject(v.root,frame.getPose(source.targetRaySpace,reference));poseObject(v.grip,source.gripSpace?frame.getPose(source.gripSpace,reference):null);const r=hit(source,frame);v.dot.visible=!!r;if(r){v.dot.position.copy(raycaster.ray.at(raycaster.ray.origin.distanceTo(lastHit),vector));const len=raycaster.ray.origin.distanceTo(lastHit);v.ray.scale.y=len;v.ray.position.z=-len/2;if(v.hover!==r.label){v.hover=r.label;r.hover?.();}}else{v.hover=null;v.ray.scale.y=1.4;v.ray.position.z=-.7;}if(source.hand){let i=0;for(const joint of source.hand.values()){const j=v.joints[i++];if(!j)break;const p=frame.getJointPose?.(joint,reference);poseObject(j,p);if(p)j.scale.setScalar(Math.max(.003,Math.min(.015,p.radius||.005)));}for(;i<v.joints.length;i++)v.joints[i].visible=false;}}
}
const lastHit=new T.Vector3();
function hit(source,frame){if(!ui||!frame||!reference)return null;const pose=frame.getPose(source.targetRaySpace,reference);if(!pose)return null;ctl.fromArray(pose.transform.matrix);ctl.decompose(raycaster.ray.origin,rotation,vector);raycaster.ray.direction.copy(forward).applyQuaternion(rotation);xrScene.updateMatrixWorld(true);const h=raycaster.intersectObject(ui,false)[0];if(h)lastHit.copy(h.point);return h?.uv?pointInRects(h.uv.x*1200,(1-h.uv.y)*900,rects):null;}
function selectStart(e){if(!presenting)return;const r=hit(e.inputSource,e.frame||lastFrame);if(!r)return;suppressed.add(e.inputSource);const generation=panel();
 if(typeof r.action==='string'){if(r.action==='use')window.SkyCycleBathhouse?.interact();else if(r.action==='portal')window.SkyCyclePortals?.show();else{held.add(r.action);presses.set(e.inputSource,{action:r.action,generation});}}
 else r.action();lastUI=0;
}
function selectEnd(e){suppressed.delete(e.inputSource);const p=presses.get(e.inputSource);if(p)held.delete(p.action);presses.delete(e.inputSource);}
function frame(now,f){if(!presenting||!f)return;try{lastFrame=f;reference=renderer.xr.getReferenceSpace();const viewer=f.getViewerPose(reference);if(!viewer){pause();return;}
  if(recenter){const tr=viewer.transform;anchor.position.set(tr.position.x,tr.position.y,tr.position.z);const q=tr.orientation;rotation.set(q.x,q.y,q.z,q.w);vector.copy(forward).applyQuaternion(rotation);anchor.rotation.set(0,Math.atan2(-vector.x,-vector.z),0);recenter=false;}
  const sources=[...session.inputSources];if(neutral&&sourcesNeutral(sources))neutral=false;
  const left=sources.find(s=>!s.hand&&s.handedness==='left'&&s.gamepad?.mapping==='xr-standard');const down=!!left?.gamepad?.buttons[4]?.pressed;if(!panel()&&!neutral&&down&&!ctxDown)window.SkyCycleBathhouse?.interact();ctxDown=down;ctxSource=left;
  window.pollGamepad?.();window.tick();
  if(originalScene.fog){xrScene.fog=originalScene.fog.clone();xrScene.fog.near*=.0025;xrScene.fog.far*=.0025;}
  if(typeof player!=='undefined'&&player){world.position.set(-(player.x+13)*.0025,-.05+(player.y+15)*.0025,-2.4);}
  makeMenu(now);updateTracking(f);originalRender.call(renderer,xrScene,camera);frameCount++;eyeCount=viewer.views.length;
 }catch(e){status('XR stopped safely: '+e.message);pause();session?.end().catch(()=>{});}}
async function finish(){if(!presenting&&!starting)return;presenting=false;starting=false;release();restoreFramebuffer();restoreFramebuffer=()=>{};if(renderer){await renderer.setAnimationLoop(null);renderer.xr.enabled=false;if(originalRender)renderer.render=originalRender;}
 if(originalScene){world?.remove(originalScene);originalScene.updateMatrixWorld(true);}if(xrScene)disposeObject(xrScene);texture?.dispose();visuals.clear();if(oldView&&window.__delivery?.state.view!==oldView)__delivery.act('view');
 session=null;reference=null;lastFrame=null;world=null;xrScene=null;ui=null;rects=[];pause();status('XR ended. Resume from the normal pause screen.');}
async function enter(){if(starting||presenting)return;if(window.RouteWorkshop?.state.dirty){status('Save or discard the Workshop draft before entering XR. Nothing was reloaded.');return;}
 renderer=window.__merged?.renderer;if(!renderer||!window.__gpuReady){status('The 3D renderer is not ready. Ordinary play is still available.');return;}
 if(!renderer.backend.isWebGLBackend){const url=new URL(location.href);url.searchParams.set('xr','1');const route=window.DeliveryCampaign?.routes[window.__delivery?.state.route];if(route&&window.SkyCyclePortals?.destinations.some(d=>d.id===route.id))url.searchParams.set('destination',route.id);location.assign(url.href);return;}
 starting=true;$('sky-xr-enter').disabled=true;let acquired=null;
 try{acquired=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['hand-tracking','local-floor']});session=acquired;originalScene=__merged.scene;originalRender=renderer.render;restoreFramebuffer=protectOpaqueXRFramebuffer(renderer);oldView=__delivery.state.view;if(oldView!=='3d')__delivery.act('view');guide.close();makeStage();release();renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local');await renderer.setAnimationLoop(frame);await renderer.xr.setSession(session);presenting=true;starting=false;renderer.render=function(scene,cam){if(!presenting)return originalRender.call(this,scene,cam);};session.addEventListener('selectstart',selectStart);session.addEventListener('selectend',selectEnd);session.addEventListener('inputsourceschange',e=>{release();if(e.removed?.length)pause();});session.addEventListener('visibilitychange',()=>{if(session.visibilityState!=='visible')pause();});session.addEventListener('end',finish,{once:true});status('XR active.');
 }catch(e){const reason='XR could not start: '+e.message;try{await acquired?.end();}catch{}await finish();status(reason);}finally{$('sky-xr-enter').disabled=false;}
}
$('sky-xr-enter').onclick=enter;window.addEventListener('pagehide',()=>{pause();session?.end().catch(()=>{});});
window.SkyCycleXR=Object.freeze({version:'0.21.0',get presenting(){return presenting;},show,getGamepad(){return presenting?mappedPad([...session.inputSources],{panel:!!panel(),suppressed,held,enabled:!neutral&&session.visibilityState==='visible'}):null;},get diagnostics(){return {presenting,frames:frameCount,eyes:eyeCount,trackedSources:visuals.size,handJoints:[...visuals.values()].reduce((n,v)=>n+v.joints.filter(j=>j.visible).length,0),neutral,error:errorText,buttons:rects.map(({label,x,y,w,h})=>({label,x,y,w,h})),page,uiMatrix:ui?.matrixWorld.elements.slice(),ownedScene:!!world?.children.includes(originalScene)};}});
support();
