/* Same-origin reception evidence, with no storage or account writes. */
(async()=>{
'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label={trump:'Donald Trump',reagan:'Ronald Reagan',context:'Textual context'};
const stages={injury:'Injury',appearance:'Perceived appearance',reception:'Audience response',providence:'Divine attribution',mission:'Claimed mission',allegiance:'Changed allegiance',accountability:'Accountability',repair:'Repair'};
let data,visible=[],printState=null;
const message=t=>{$('#rx-status').textContent=t;};
const date=r=>r.date?(r.date+(r.dateEnd?' to '+r.dateEnd:'')):'No modern event date';
function validate(d){
 if(!d||d.version!=='2026-09-08-reception-1'||!Array.isArray(d.records)||!Array.isArray(d.sources)||!Array.isArray(d.tasks))throw Error('Invalid evidence edition.');
 const all=new Set();for(const r of [...d.records,...d.sources,...d.tasks]){if(!r||typeof r.id!=='string'||!/^[a-z0-9-]+$/i.test(r.id)||all.has(r.id))throw Error('Invalid or duplicate record identity.');all.add(r.id);}
 const sources=new Set(d.sources.map(s=>s.id));
 for(const s of d.sources){const u=new URL(s.url);if(u.protocol!=='https:'||u.username||u.password)throw Error('Unsafe source address.');}
 for(const r of d.records){if(!Object.hasOwn(label,r.person)||!Object.hasOwn(stages,r.stage)||!Array.isArray(r.sourceIds)||!r.sourceIds.length||!r.sourceIds.every(id=>sources.has(id)))throw Error('Invalid evidence reference.');for(const key of ['title','observation','contribution','countercase','next','kind'])if(typeof r[key]!=='string')throw Error('Missing evidence text.');for(const key of ['date','dateEnd'])if(r[key]!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(r[key]))throw Error('Invalid date.');if(r.dateEnd&&(!r.date||r.dateEnd<r.date))throw Error('Invalid date interval.');}
 const p=d.survey;if(!p||!sources.has(p.sourceId)||!Number.isInteger(p.sample)||p.sample<=0||!Number.isInteger(p.republicanSample)||p.republicanSample<=0)throw Error('Invalid survey denominator.');
 for(const item of p.items)for(const k of ['overall','republican'])if(!Number.isFinite(item[k])||item[k]<0||item[k]>100)throw Error('Invalid survey percentage.');return d;
}
const source=id=>data.sources.find(s=>s.id===id);
function card(r){return `<article class="rx-card" id="rx-${r.id}"><span class="tag">${esc(label[r.person])} / ${esc(r.kind)}</span><h3>${esc(r.title)}</h3><p class="rx-small">${esc(date(r))} / ${esc(stages[r.stage])}</p><p><strong>Observed or stated:</strong> ${esc(r.observation)}</p><p><strong>Contribution:</strong> ${esc(r.contribution)}</p><p><strong>Countercase:</strong> ${esc(r.countercase)}</p><details><summary>Next test and source trail</summary><p>${esc(r.next)}</p>${r.sourceIds.map(id=>`<p><a href="#rx-source-${id}">${esc(source(id).title)}</a><br><span class="rx-small">Source family: ${esc(source(id).family)}</span></p>`).join('')}</details><a data-rx-link="${r.id}" href="#rx-${r.id}">Open this evidence record</a></article>`;}
function filters(){return {person:$('#rx-person').value,stage:$('#rx-stage').value,q:$('#rx-query').value.trim().toLowerCase()};}
function setURL(){try{const u=new URL(location.href);for(const [k,v]of Object.entries(filters())){if(v&&v!=='all')u.searchParams.set('rx-'+k,v);else u.searchParams.delete('rx-'+k);}history.replaceState({},'',u);}catch{/* Reading/filtering still works. */}}
function draw(sync=true){const f=filters();visible=data.records.filter(r=>(f.person==='all'||r.person===f.person)&&(f.stage==='all'||r.stage===f.stage)&&(!f.q||[r.title,r.kind,r.observation,r.contribution,r.countercase,r.next,label[r.person],...r.sourceIds.map(id=>source(id).title)].join(' ').toLowerCase().includes(f.q)));$('#rx-records').innerHTML=visible.map(card).join('')||'<p>No records match. Reset or shorten the query.</p>';const families=new Set(visible.flatMap(r=>r.sourceIds.map(id=>source(id).family)));message(`${visible.length} of ${data.records.length} records / ${families.size} source families in this selection. Families are not independent proofs.`);if(sync)setURL();}
function reveal(){let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{return;}if(!id.startsWith('rx-'))return;const record=data.records.find(r=>'rx-'+r.id===id);if(!record)return;$('#rx-person').value='all';$('#rx-stage').value='all';$('#rx-query').value='';draw(false);const el=document.getElementById(id);el.querySelector('details').open=true;el.setAttribute('tabindex','-1');el.focus({preventScroll:true});el.scrollIntoView({block:'start'});setURL();}
function supplements(){
 const p=data.survey;$('#rx-survey-body').innerHTML=`<div class="scroll"><table><caption>${esc(p.population)}, ${esc(p.fieldDate)}. Separate agreement items.</caption><thead><tr><th scope="col">Question summary</th><th scope="col">Overall, N=${p.sample}</th><th scope="col">Republicans, N=${p.republicanSample}</th></tr></thead><tbody>${p.items.map(x=>`<tr><td>${esc(x.label)}<br><small>${esc(x.id)}</small></td><td>${x.overall}%</td><td>${x.republican}%</td></tr>`).join('')}</tbody></table></div><p class="rx-small">${esc(p.method)} Published margins at 95% confidence: overall plus or minus ${p.overallMarginPoints} percentage points; Republicans plus or minus ${p.republicanMarginPoints} points. These are sampling margins, not uncertainty estimates for a theological interpretation.</p><p>${esc(p.constraint)}</p><a href="#rx-source-${p.sourceId}">Open methodology and page locators</a>`;
 $('#rx-comparison-body').innerHTML=`<div class="scroll"><table class="rx-compare"><caption>Documented parts and unestablished steps in the selected cases</caption><thead><tr><th scope="col">Question</th><th scope="col">Trump dossier</th><th scope="col">Reagan dossier</th></tr></thead><tbody>${Object.entries(stages).map(([stage,name])=>`<tr><th scope="row">${esc(name)}</th>${['trump','reagan'].map(person=>{const rs=data.records.filter(r=>r.person===person&&r.stage===stage);return `<td>${rs.length?rs.map(r=>`<p><a data-rx-link="${r.id}" href="#rx-${r.id}">${esc(r.title)}</a></p>`).join(''):'Not established by an entry in this selected dossier.'}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;
 $('#rx-tasks').innerHTML=data.tasks.map(t=>`<details><summary>${esc(t.id+' / '+t.state+' / '+t.work)}</summary><p>${esc(t.done)}</p></details>`).join('');
 $('#rx-sources').innerHTML=data.sources.map(s=>`<section class="rx-source" id="rx-source-${s.id}"><h3><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></h3><p>${esc(s.kind)} / ${esc(s.date||'Publication or composition date not established')}</p><p>${esc(s.access)}</p><p class="rx-small">Locator: ${esc(s.locator)}. Source family: ${esc(s.family)}. Consulted: 2026-09-08.</p></section>`).join('');
}
try{const r=await fetch('./reception/study.json',{cache:'no-store'});if(!r.ok)throw Error('Evidence returned HTTP '+r.status);data=validate(await r.json());supplements();const u=new URL(location.href);for(const k of ['person','stage']){const el=$('#rx-'+k),v=u.searchParams.get('rx-'+k);if([...el.options].some(x=>x.value===v))el.value=v;}$('#rx-query').value=(u.searchParams.get('rx-q')||'').slice(0,300);draw();reveal();for(const b of document.querySelectorAll('#rx-actions button'))b.disabled=false;document.body.dataset.receptionReady='true';}catch(e){message('Evidence could not load: '+e.message+' The complete argument, source guide and public JSON remain available.');return;}
for(const id of ['person','stage'])$('#rx-'+id).addEventListener('change',()=>{draw();});$('#rx-query').addEventListener('input',()=>draw());
$('#rx-reset').onclick=()=>{$('#rx-person').value='all';$('#rx-stage').value='all';$('#rx-query').value='';draw();};
window.addEventListener('hashchange',reveal);
document.addEventListener('click',e=>{const a=e.target.closest('[data-rx-link]');if(!a)return;const target='#rx-'+a.dataset.rxLink;if(location.hash===target)reveal();});
$('#rx-export').onclick=()=>{const sourceIds=new Set(visible.flatMap(r=>r.sourceIds));const payload={version:data.version,scope:data.scope,selection:filters(),records:visible,sources:data.sources.filter(s=>sourceIds.has(s.id)),survey:sourceIds.has(data.survey.sourceId)?data.survey:null};const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.href=url;a.download='theology-reception-evidence.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);};
function beforePrint(){if(printState)return;printState={html:$('#rx-records').innerHTML,status:$('#rx-status').textContent};$('#rx-records').innerHTML=data.records.map(card).join('');document.querySelectorAll('#rx-records details').forEach(d=>d.open=true);message('Complete reception dossier prepared for printing.');}
function afterPrint(){if(!printState)return;$('#rx-records').innerHTML=printState.html;message(printState.status);printState=null;}
window.addEventListener('beforeprint',beforePrint);window.addEventListener('afterprint',afterPrint);$('#rx-print').onclick=()=>window.print();
})();
