'use strict';
const fs=require('node:fs'),path=require('node:path');
const plan=require('./roadmap.json');
const ref=(id,title,url,scope)=>({id,title,url,scope,accessed:'2026-09-05'});
const references=[
 ref("melch-kim2018","Dong-Hyuk Kim (2018), The Messiah of Aaron and Israel: Do We See Single or Double?, Korean Journal of Old Testament Studies 24(1), 190-213","https://journal.kci.go.kr/ksots/archive/articleView?artiId=ART002331289","Journal metadata, English abstract and bibliography consulted. DOI 10.24333/jkots.2018.24.1.190. The abstract establishes the dispute about the singular Damascus Document expression and states its argument for two figures. The full Korean article and the cited critical editions were not collated. This is current editorial research, not a recovered author acknowledgment."),
 ref('melch-genesis14','Genesis 14:18-20, World English Bible','https://ebible.org/engwebp/GEN14.htm','Primary chapter consulted. The encounter, blessing and tithe are kept separate from later lineage claims.'),
 ref('melch-psalm110','Psalm 110, World English Bible','https://ebible.org/engwebp/PSA110.htm','Primary psalm consulted, especially verses 1-7. Royal and judicial language is retained alongside the priestly address.'),
 ref('melch-hebrews7','Hebrews 7, World English Bible','https://ebible.org/engwebp/HEB07.htm','Primary chapter consulted, especially verses 1-17 and 23-28. Textual resemblance, descent and continuing priesthood are distinguished.'),
 ref('melch-williams2023','Logan Williams (2023), Melchizedek, the Son of Man, and Eschatological Jubilee','https://journals.sagepub.com/doi/10.1177/0142064X231191176','Full-text HTML consulted, particularly the author\'s translation of 11Q13 II 2-9 and discussion of II 6 and 13. His active-agent reading is distinguished from the critical edition he disputes. The critical edition itself has not been collated in this pass. This is current editorial research, not a recovered author acknowledgment.'),
 ref('melch-giversen-pearson','Melchizedek, translated by Soren Giversen and Birger A. Pearson','https://www.gnosis.org/naghamm/melchiz.html','Online translation retrieved in the indexed full-text result; direct-page retrieval failed. Marked lacunae are retained in the interpretation. The online notice requests published-edition citations for academic work; printed page/line collation remains open. Credit is for a textual source used by this edition, not a claimed personal influence on Micah.')
];
const article={slug:'melchizedek-priesthood-and-transmission',title:'Melchizedek: priesthood, release and transmission',category:'origins',kind:'Developed article',updated:plan.updated,summary:'A passage-level comparison of Genesis, Psalm 110, 11Q13, Hebrews and Nag Hammadi, preserving the distinction between a shared role and a demonstrated historical carrier.',claimType:'Textual comparison and historical transmission inquiry',sourceIds:['2656'],externalSources:references.map(r=>r.id),attribution:'AI-assisted editorial synthesis and development of the author\'s explicit Melchizedek research questions. Historical proposals, consulted scholarly interpretations and new conceptual comparisons are distinct; none is presented as an invented author quotation.',body:fs.readFileSync(path.join(__dirname,'roadmap-articles/melchizedek-priesthood-and-transmission.md'),'utf8')};
const relations=[
 ['tor-thomas-and-gnostic-transmission',article.slug,'develops','The passage comparison carries out the requested Melchizedek sub-investigation without replacing the broader Teacher, Thomas and Gnostic reconstruction.'],
 [article.slug,'jesus-teacher-of-righteousness-hypothesis','distinguishes','Shared priestly language is relevant to the reconstruction but does not by itself establish the identity or genealogy of a historical teacher.'],
 [article.slug,'sacred-inheritance-and-rival-continuations','applies','Different texts can retain a recognizable priestly figure while changing how the figure authorizes a community.'],
 [article.slug,'apocalyptic-repair-theology','compares','Release from captivity motivates a philosophical comparison with repair; thematic usefulness is not proof of an uninterrupted genealogy.'],
 [article.slug,'divine-will-and-self-authorizing-power','connects','The source of legitimate authority and its relationship to an agent\'s desires remain separate questions.'],
 ['research-roadmap','source-coverage','documents','Coverage records identify actual article links and selected anchors, not a speculative count of sources already read.'],
 ['research-roadmap','book-contents','organizes','The deliverable sequence points to chapter routes without declaring the manuscript completed.']
].map(([from,to,type,why])=>({from,to,type,why,origin:'Editorial relationship'}));
const anchors=[{from:article.slug,sourceId:'2656',turn:63,why:'The author asks for prior research and proposed Egyptian/Ethiopian transmission connections.'},{from:article.slug,sourceId:'2656',turn:82,why:'The author explicitly asks about Melchizedek across the New Testament, Qumran and Gnostic material.'},{from:article.slug,sourceId:'2656',turn:84,why:'The author asks how Davidic and Zadokite lines relate to the Melchizedek question.'}];
const evidence=[
 {id:'genesis',title:'Genesis encounter',passage:'Genesis 14:18-20',reference:'melch-genesis14',role:'King-priest who blesses Abram and receives a tithe.',comparison:'Recognition of sacred authority is narrated before later explanations of institutional descent.',limit:'The passage does not supply an Aaronic or Zadokite genealogy or a transmission route to Qumran.'},
 {id:'psalm',title:'Royal priestly address',passage:'Psalm 110:1-7, especially verse 4',reference:'melch-psalm110',role:'An enduring priestly appointment in a royal and judicial setting.',comparison:'The figure authorizes a role; the surrounding enemy/judgment language must not be omitted.',limit:'A later reading of the royal address is not automatically the original setting of composition.'},
 {id:'qumran',title:'11QMelchizedek',passage:'11Q13 column II, lines 2-9 and 13, through Williams 2023',reference:'melch-williams2023',role:'Release, restoration and atonement in the consulted scholarly reading.',comparison:'Williams argues for an active subject in II 6 rather than an indefinite rendering; this affects the distribution of authority.',limit:'This reading is disputed. Access to a translation and argument does not constitute independent collation of the damaged manuscript.'},
 {id:'hebrews',title:'Continuing priesthood',passage:'Hebrews 7:1-17 and 23-28',reference:'melch-hebrews7',role:'Interpretive superiority and enduring intercession, distinguished from ordinary Levitical qualification.',comparison:'The letter uses the inherited figure to reason about a different basis of authority.',limit:'Textual likeness and a continuing role are not evidence that Teacher, James and Jesus are one historical individual.'},
 {id:'nag-hammadi',title:'Melchizedek tractate',passage:'Nag Hammadi Codex IX,1; online translation, paragraphs on embodiment and the image of the high priest',reference:'melch-giversen-pearson',role:'Exalted priestly language with ritual participation and explicit embodiment language.',comparison:'The anti-docetic passage complicates a universal equation of Gnostic salvation with rejection of the body.',limit:'Extensive gaps prevent an effortless continuous reconstruction. Exact printed page/line citations remain a task.'}
];
module.exports={plan,version:plan.version,updated:plan.updated,articles:[article],references,relations,anchors,evidence};
