import test from 'node:test';
import assert from 'node:assert/strict';
import {sanitize,profile,newRun,observe,settle,guidance,districtAt} from '../route-compass-core.mjs';
const cells=new Uint8Array(100*70);cells[59*100+43]=13;cells[59*100+78]=13;
const rail=[[650,2000],[965,2080]];rail.sky={id:'loop-0',optional:true,label:'Practice ramp'};
const source={kind:'ground',width:100,goal:{x:95},gp:{sections:[{x:0,name:'Post Office Green',scene:'village'},{x:34,name:'Market Lanes',scene:'market'},{x:76,name:'Loopside Park',scene:'park'}]},cells,ct:[rail]};
const info={id:'first-neighborhood',name:'Sunrise Borough'};
const p=()=>profile(source,info);
test('only ground adventures with real district data are accepted',()=>{assert.equal(profile({...source,kind:'sky'},info),null);assert.equal(profile({...source,gp:{}},info),null);assert.equal(profile(source,{id:'../bad'}),null);assert.equal(profile({...source,width:NaN},info),null);});
test('profile preserves labels without mutating course data',()=>{const before=JSON.stringify(source);assert.equal(p().sections.length,3);assert.equal(p().rails[0].name,'Practice ramp');assert.equal(JSON.stringify(source),before);});
test('checkpoint locations come from checkpoint tiles',()=>assert.deepEqual(p().checkpoints,[1548,2808]));
test('district boundaries choose the receiving district',()=>{assert.equal(districtAt(p(),1223).id,'district:0');assert.equal(districtAt(p(),1224).id,'district:1');});
test('guidance explains road and optional line without controlling input',()=>{const g=guidance(p(),500);assert.equal(g.rail.name,'Practice ramp');assert.equal(g.next.name,'Market Lanes');assert.equal(g.checkpoint,1548);});
test('progress clamps at both ends and rejects invalid positions',()=>{assert.equal(guidance(p(),-100).percent,0);assert.equal(guidance(p(),9999).percent,100);assert.equal(guidance(p(),NaN),null);});
test('observations do not award skipped districts',()=>{const r=newRun(p());observe(r,110);observe(r,2900);assert.deepEqual([...r.seen],['district:0','district:2']);});
test('only known optional tracks create rail stamps',()=>{const r=newRun(p());observe(r,700,'fake');assert.equal(r.seen.size,1);observe(r,700,'loop-0');assert(r.seen.has('rail:loop-0'));});
test('repeated observations remain unique',()=>{const r=newRun(p());observe(r,110);observe(r,120);assert.equal(r.seen.size,1);assert.equal(r.steps,2);});
test('bad positions and finished runs do not create observations',()=>{const r=newRun(p());observe(r,NaN);observe(r,99999);assert.equal(r.steps,0);r.finished=true;observe(r,110);assert.equal(r.steps,0);});
test('a rejected engine finish banks nothing',()=>{const r=newRun(p());observe(r,110);const s=settle({},r,false);assert.equal(s.banked,false);assert.equal(Object.keys(s.records).length,0);assert.equal(r.finished,false);});
test('an unobserved route cannot bank stamps',()=>assert.equal(settle({},newRun(p()),true).banked,false));
test('an accepted finish banks observations exactly once',()=>{const r=newRun(p());observe(r,110);const s=settle({},r,true);assert.deepEqual(s.fresh,['district:0']);assert.equal(s.records[info.id].finishes,1);assert.equal(settle(s.records,r,true).banked,false);});
test('replays union discoveries and preserve prior route records',()=>{const r=newRun(p());observe(r,1400);const s=settle({'first-neighborhood':{stamps:['district:0'],finishes:2},'canal-choices':{stamps:['district:1'],finishes:3}},r,true);assert.deepEqual(s.records[info.id].stamps,['district:0','district:1']);assert.equal(s.records['canal-choices'].finishes,3);});
test('forged observation identifiers do not become banked stamps',()=>{const r=newRun(p());observe(r,110);r.seen.add('rail:fake');assert.deepEqual(settle({},r,true).records[info.id].stamps,['district:0']);});
test('sanitization bounds malformed persisted data and prototype keys',()=>{const raw=JSON.parse('{"__proto__":{"stamps":["district:0"]},"first-neighborhood":{"stamps":["district:0","district:0","<script>"],"finishes":-8}}');const s=sanitize(raw);assert.equal(Object.getPrototypeOf(s),null);assert.equal(Object.keys(s).length,1);assert.deepEqual(s[info.id].stamps,['district:0']);assert.equal(s[info.id].finishes,0);});
test('new runs reset provisional discoveries, not persisted records',()=>{const r=newRun(p());observe(r,110);assert.equal(newRun(p()).seen.size,0);assert.equal(r.seen.size,1);});
