import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {preference,routeByID,entryGate,entryURL,pendingEntry,clearEntryURL} from '../route-entry-core.mjs';
const routes=[{id:'first-neighborhood',name:'Sunrise Borough'},{id:'canal-choices',name:'Waterwheel Boulevard'}];
const input={routes,id:'canal-choices',mode:'ar',ready:true,supported:{ar:true,vr:true}};
test('Route IDs resolve without assuming campaign index',()=>{assert.equal(routeByID(routes,'canal-choices').index,1);assert.equal(routeByID([...routes].reverse(),'canal-choices').index,0);assert.equal(routeByID(routes,'unknown'),null);});
for(const mode of ['ar','vr','screen'])test('Only explicit valid preferences persist: '+mode,()=>assert.deepEqual(preference({mode,route:88}),{version:1,mode}));
test('Invalid preferences never silently select an immersive mode',()=>{assert.equal(preference(null).mode,null);assert.equal(preference({mode:'iframe'}).mode,null);});
for(const [changes,reason]of [[{id:'missing'},'available'],[{mode:'magic'},'available'],[{ready:false},'loading'],[{protectedDraft:true},'Workshop'],[{busy:true},'progress'],[{supported:{ar:false}},'unavailable']])test('Guard prevents replacement: '+reason+JSON.stringify(changes),()=>{const r=entryGate({...input,...changes});assert(!r.ok);assert(r.reason.includes(reason));});
test('Screen remains explicit when AR is unavailable',()=>assert.equal(entryGate({...input,mode:'screen',supported:{ar:false}}).action,'start'));
for(const [change,action]of [[{},'enter'],[{webgl:false},'reload'],[{currentMode:'immersive-ar'},'start'],[{currentMode:'immersive-vr'},'switch'],[{currentMode:'immersive-ar',mode:'screen'},'leave']])test('Entry lifecycle '+action,()=>assert.equal(entryGate({...input,...change}).action,action));
test('WebGL reload retains stable ID and removes conflicting destination',()=>{const url=entryURL('https://example.test/game/?destination=tideglass-baths&foo=1','canal-choices','ar');assert.deepEqual(pendingEntry(url,routes),{id:'canal-choices',mode:'ar'});const q=new URL(url);assert.equal(q.searchParams.get('xr'),'1');assert.equal(q.searchParams.get('foo'),'1');assert(!q.searchParams.has('destination'));assert.equal(q.origin,'https://example.test');});
test('Unknown URL instructions do not select arbitrary game or mode',()=>{assert.equal(pendingEntry('https://example.test/?scRoute=unknown&scMode=ar',routes),null);assert.equal(pendingEntry('https://example.test/?scRoute=canal-choices&scMode=iframe',routes),null);assert.throws(()=>entryURL('https://example.test','canal-choices','iframe'));});
test('Consuming pending entry preserves all unowned URL parts',()=>assert.equal(clearEntryURL('https://example.test/game/?xr=1&scRoute=canal-choices&scMode=ar&foo=1#editor'),'https://example.test/game/?xr=1&foo=1#editor'));
test('Route entry creates sibling buttons and retains original controller input owner',()=>{const s=readFileSync(new URL('../route-entry.js',import.meta.url),'utf8');assert(s.includes('card.before(wrap);wrap.append(card)'));assert(s.includes('wrap.append(row,info)'));assert(!s.includes('localStorage.clear'));assert(!s.includes('requestAnimationFrame'));assert(!s.includes('player.x='));assert(s.includes('serial++;busy=false'));});
test('Immersive entry reports actual success after original lifecycle setup',()=>{const s=readFileSync(new URL('../xr-play.js',import.meta.url),'utf8');const f=s.slice(s.indexOf('async function enter('),s.indexOf('// Route cards share'));assert(f.indexOf('requestSession')<f.indexOf('setAnimationLoop(frame)'));assert(f.indexOf('setAnimationLoop(frame)')<f.indexOf('renderer.xr.setSession'));assert(f.indexOf('return true')>f.indexOf('presenting=true'));assert(f.includes('return false;'));});

test('Headset footer uses the visible release identity instead of a stale hardcoded build',()=>{const s=readFileSync(new URL('../xr-play.js',import.meta.url),'utf8');assert(s.includes("window.PaperDeliveryRelease?.version||'0.27.0'"));assert(!s.includes("text('v0.26.2 |"));});
