import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {DEFAULTS,STORE,sanitize,transientGain,createNoticeState,admitNotice,waterEvents,ambienceGain,waterSamples} from '../sensory-core.mjs';
import {createWaterAudio} from '../water-audio.mjs';
const bath={route:'tideglass-baths',epoch:1,active:true,opened:false,drain:0};
test('New comfort defaults do not require or mutate old saves',()=>{assert.equal(STORE,'svgn.skycycle.sensory.v1');assert.deepEqual(sanitize(null),DEFAULTS);assert(Object.isFrozen(DEFAULTS));});
test('Malformed preferences are bounded and unknown names are rejected',()=>{for(const v of [false,[],{},'bad',null])assert.deepEqual(sanitize(v),DEFAULTS);assert.deepEqual(sanitize({notices:'off',transients:'__proto__',ambience:Infinity}),DEFAULTS);assert.equal(sanitize({ambience:-4}).ambience,0);assert.equal(sanitize({ambience:4}).ambience,1);assert.equal(sanitize({ambience:'1'}).ambience,.35);assert.equal(sanitize({transients:{toString:'bad'}}).transients,'soft');});
test('All intensity choices remain explicitly ordered and finite',()=>{assert.equal(transientGain({transients:'gentle'}),.35);assert.equal(transientGain({transients:'soft'}),.65);assert.equal(transientGain({transients:'full'}),1);});
test('Balanced notices rate-limit different messages and duplicate keys',()=>{const s=createNoticeState();assert(admitNotice(s,'arrive',0,DEFAULTS));assert(!admitNotice(s,'gate',4000,DEFAULTS));assert(admitNotice(s,'gate',4500,DEFAULTS));assert(!admitNotice(s,'arrive',9000,DEFAULTS));assert(admitNotice(s,'arrive',13500,DEFAULTS));});
test('Quiet notices are less frequent and essential-only suppresses optional notices',()=>{const s=createNoticeState();const p={notices:'quiet'};assert(admitNotice(s,'one',0,p));assert(!admitNotice(s,'two',11999,p));assert(admitNotice(s,'two',12000,p));assert(!admitNotice(s,'three',24000,{notices:'essential'}));});
test('Critical notice ownership blocks optional replacement but does not queue old messages',()=>{const s=createNoticeState();s.essentialUntil=2200;assert(!admitNotice(s,'one',1000,DEFAULTS));assert(admitNotice(s,'two',2200,DEFAULTS));assert.equal(s.shown,1);assert.equal(s.suppressed,1);});
test('Notice history is bounded during arbitrarily long sessions',()=>{const s=createNoticeState();for(let i=0;i<10000;i++)admitNotice(s,'notice-'+i,i*5000,DEFAULTS);assert.equal(s.keys.size,32);assert.equal(s.shown,10000);});
test('Bad timestamps and clock rewind cannot flood notices',()=>{const s=createNoticeState();assert(!admitNotice(s,'one',NaN,DEFAULTS));assert(admitNotice(s,'one',10000,DEFAULTS));assert(!admitNotice(s,'two',0,DEFAULTS));});
test('Water arrival, opening and reveal cues are edge triggered',()=>{assert.deepEqual(waterEvents(null,bath),['arrival']);const opened={...bath,opened:true,drain:1};assert.deepEqual(waterEvents(bath,opened),['sluice']);assert.deepEqual(waterEvents(opened,opened),[]);const ready={...opened,drain:150};assert.deepEqual(waterEvents(opened,ready),['waterline']);assert.deepEqual(waterEvents(ready,ready),[]);});
test('Pause, background, unrelated chapters and old-run transitions do not generate stale cues',()=>{assert.deepEqual(waterEvents(bath,{...bath,opened:true,active:false}),[]);assert.deepEqual(waterEvents(bath,{...bath,route:'first-neighborhood',opened:true,drain:150}),[]);assert.deepEqual(waterEvents({...bath,opened:true,drain:150},{...bath,epoch:2}),['arrival']);});
test('Sound observation does not mutate live simulation samples',()=>{const before=Object.freeze({...bath});const after=Object.freeze({...bath,opened:true,drain:150});waterEvents(before,after);assert.deepEqual(before,bath);});
test('Ambience requires an active water route and audible running shared effects bus',()=>{const mix={muted:false,effects:.36,state:'running'};assert(Math.abs(ambienceGain(bath,DEFAULTS,mix)-.042)<1e-12);for(const change of [{muted:true},{effects:0},{state:'suspended'},{state:'closed'}])assert.equal(ambienceGain(bath,DEFAULTS,{...mix,...change}),0);assert.equal(ambienceGain({...bath,active:false},DEFAULTS,mix),0);assert.equal(ambienceGain({...bath,route:'first-neighborhood'},DEFAULTS,mix),0);assert.equal(ambienceGain(bath,{ambience:0},mix),0);});
test('Water texture has finite non-silent bounded samples and a quiet seamless endpoint',()=>{const a=waterSamples(8000),b=waterSamples(8000);assert.deepEqual(a,b);assert.equal(a.length,32000);assert(a.every(Number.isFinite));assert(a[0]===0);assert(a.at(-1)===0);const peak=Math.max(...a.map(Math.abs));const rms=Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length);assert(peak<.7&&rms>.01&&rms<.2);assert(Math.abs(a.at(-2)-a.at(-1))<.0001);assert.throws(()=>waterSamples(999999));});
function fakeAudio(){
 const nodes=[],context={currentTime:10,state:'running'};
 const param=()=>({value:0,calls:[],setValueAtTime(...a){this.value=a[0];this.calls.push(['set',...a]);},linearRampToValueAtTime(...a){this.value=a[0];this.calls.push(['ramp',...a]);},exponentialRampToValueAtTime(...a){this.value=a[0];},cancelScheduledValues(){},setTargetAtTime(...a){this.value=a[0];}});
 const node=kind=>{const n={kind,gain:param(),frequency:param(),Q:param(),delayTime:param(),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),edges:[],connect(other){this.edges.push(other);},disconnect(){this.edges=[];this.disconnected=true;},start(){this.started=true;},stop(){this.stopped=true;}};nodes.push(n);return n;};
 Object.assign(context,{createGain:()=>node('gain'),createBufferSource:()=>node('buffer'),createBiquadFilter:()=>node('filter'),createDelay:()=>node('delay'),createOscillator:()=>node('osc'),createDynamicsCompressor:()=>node('compressor'),createBuffer:(channels,length,rate)=>({channels,length,rate,copyToChannel(){}}),destination:node('destination')});
 return {context,nodes,node};
}
test('Ambience owns exactly two sources and never accumulates nodes on gain changes',()=>{const f=fakeAudio(),a=createWaterAudio(f.context,f.context.destination);a.setLevel(.04);assert.equal(a.diagnostics.sources,2);const count=f.nodes.length;for(let i=0;i<100;i++)a.setLevel(.08);assert.equal(f.nodes.length,count);assert.equal(a.diagnostics.starts,1);a.dispose();assert.equal(a.diagnostics.sources,0);assert(f.nodes.filter(n=>n.started).every(n=>n.stopped&&n.disconnected));});
test('Muting, pause and route exit release every owned audio node; resume is single-owner',()=>{const f=fakeAudio(),a=createWaterAudio(f.context,f.context.destination);for(let i=0;i<10;i++){a.setLevel(.04);a.setLevel(0);assert.equal(a.diagnostics.nodes,0);}a.setLevel(.04);f.context.state='suspended';a.setLevel(.04);assert.equal(a.diagnostics.sources,0);f.context.state='running';a.setLevel(.04);assert.equal(a.diagnostics.sources,2);a.dispose();a.setLevel(.04);assert.equal(a.diagnostics.sources,0);});
test('Partially constructed audio graphs are cleaned up on allocation failure',()=>{const f=fakeAudio();f.context.createDelay=()=>{throw Error('allocation failed');};const a=createWaterAudio(f.context,f.context.destination);assert.throws(()=>a.setLevel(.04));assert.equal(a.diagnostics.nodes,0);assert(f.nodes.filter(n=>n.kind!=='destination').every(n=>n.disconnected));});
function soundtrack(){
 const f=fakeAudio(),events={};const c={console,Float32Array,Map,Set,Math,Number,Object,Event:class{constructor(type){this.type=type;}},ac:()=>f.context,muted:false,mode:'play',musicName:'off',music:{timer:null},SONGS:{},AdventureScore:{SONGS:{}},stopMusic(){},localStorage:{getItem:()=>null,setItem(){}},document:{hidden:false,readyState:'loading',getElementById:()=>null,addEventListener(){}},addEventListener:(n,fn)=>events[n]=fn,dispatchEvent(){},clearInterval(){},setTimeout(){}};c.window=c;c.globalThis=c;vm.runInNewContext(fs.readFileSync(new URL('../soundtrack.js',import.meta.url),'utf8'),c);return {f,c,events};
}
test('Existing mixer caps overlapping effect oscillators at eight',()=>{const {f,c}=soundtrack();for(let i=0;i<100;i++)c.beep(100+i,.2);assert.equal(f.nodes.filter(n=>n.kind==='osc'&&n.started).length,8);});
test('Duplicate effect bursts are bounded without dropping different pitches',()=>{const {f,c}=soundtrack();for(let i=0;i<100;i++)c.beep(300,.2);c.beep(400,.2);assert.equal(f.nodes.filter(n=>n.kind==='osc'&&n.started).length,2);});
test('Invalid, hidden, suspended and muted effect requests do not allocate voices',()=>{const {f,c}=soundtrack();for(const args of [[NaN,.2],[200,Infinity],[200,-1],[200,.1,'sine',-1]])c.beep(...args);c.muted=true;c.beep(200,.2);c.muted=false;c.document.hidden=true;c.beep(200,.2);c.document.hidden=false;f.context.state='suspended';c.beep(200,.2);assert.equal(f.nodes.filter(n=>n.kind==='osc').length,0);});
test('Effect intensity changes the attack gain, while the shared music mixer is unchanged',()=>{const {f,c}=soundtrack();c.SkyCycleSensory={intensity:.35};c.beep(300,.2,'sine',.1);const ramps=f.nodes.flatMap(n=>n.gain.calls).filter(c=>c[0]==='ramp');assert(Math.abs(ramps[0][1]-.035)<1e-12);assert.equal(f.nodes.filter(n=>n.kind==='compressor').length,1);});
test('Completed voices release their budget; page exit stops remaining effects',()=>{const {f,c,events}=soundtrack();for(let i=0;i<8;i++)c.beep(300+i,.2);for(const n of f.nodes.filter(n=>n.kind==='osc'))n.onended();c.beep(900,.2);assert.equal(f.nodes.filter(n=>n.kind==='osc').length,9);events.pagehide();assert(f.nodes.filter(n=>n.kind==='osc').every(n=>n.disconnected));});
test('New presentation modules do not write gameplay state or create additional music contexts',()=>{for(const name of ['sensory-core.mjs','sensory.js','water-audio.mjs']){const code=fs.readFileSync(new URL('../'+name,import.meta.url),'utf8');assert(!/player\.(x|y|vx|vy)\s*=(?!=)|won\s*=|new\s+(?:window\.)?AudioContext\b|localStorage\.(?:clear|removeItem)/.test(code));}const bridge=fs.readFileSync(new URL('../sensory.js',import.meta.url),'utf8');assert.equal((bridge.match(/localStorage\.setItem\(STORE/g)||[]).length,1);});
