import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import fs from 'node:fs';
import {buildCourse,ID,REVISION,RECORD,IDS,CUES,floorAt,recordKey,recordRoute,isLayout} from '../waterwheel-core.mjs';
import {profile,newRun,observe,settle as stampSettle} from '../route-compass-core.mjs';
import {settle as careerSettle} from '../flight-deck-core.mjs';
const require=createRequire(import.meta.url),F=require('../../../tests/helpers/flow-fixture.cjs'),c=F.context(),original=c.GroundCampaign.make(1,F.T),code=c.GroundCampaign.encode(original),data=buildCourse(original,F.T,c.FlowRoutes.path);
test('Waterwheel revises only its stable authored route, preserving original source and other chapters',()=>{assert.equal(data.id,ID);assert.equal(data.layoutRevision,REVISION);assert.equal(data.recordId,RECORD);assert.equal(c.GroundCampaign.encode(original),code);for(const n of[0,2]){const d=c.GroundCampaign.make(n,F.T);assert.equal(buildCourse(d,F.T,c.FlowRoutes.path),d);}});
test('Every column has physical ground with at most one-tile rise and no holes',()=>{for(let x=0;x<data.width;x++){const y=floorAt(x);assert.equal(data.cells[y*data.width+x],F.T.STEEL);if(x)assert(Math.abs(y-floorAt(x-1))<=1);for(let j=y;j<data.height;j++)assert.equal(data.cells[j*data.width+x],F.T.STEEL);}assert.equal(data.gp.quota,0);assert.equal(data.gp.requiredGrapples,0);assert.equal(data.gp.minTransfers,0);});
test('All ordinary deliveries and checkpoints have real standing ground',()=>{for(const x of data.roadBoxes)assert.equal(data.cells[(floorAt(x)-1)*data.width+x],F.T.MAILBOX);const checks=[...data.cells].map((v,i)=>v===F.T.CHECK?i:-1).filter(i=>i>=0);assert.equal(checks.length,6);for(const i of checks)assert.equal(Math.floor(i/data.width),floorAt(i%data.width)-1);});
test('Readable safe practice and express entry are clear of road patrols and premature mandatory pegs',()=>{assert.equal(data.ct.length,9);assert.equal(new Set(data.ct.map(p=>p.sky.id)).size,9);assert.equal([...data.cells].filter(x=>x===F.T.PEG).length,0);for(const p of data.ct)assert(p.every(v=>v.every(Number.isFinite)));assert(CUES.some(c=>c.id==='fork'&&c.x<2700));});
test('A classic source exports and edited documents round-trip without a migration',()=>{const doc=c.WorkshopCore.decode(code);assert(doc.paths.length>data.ct.length);const revised=c.WorkshopCore.decode(c.GroundCampaign.encode(data)),encoded=c.WorkshopCore.encode(revised),copy=c.WorkshopCore.decode(encoded);assert.equal(copy.extra.gp.layoutRevision,REVISION);assert.equal(copy.paths.length,9);assert.equal(c.GroundCampaign.encode(original),code);});
test('Layout keys distinguish old times and stamps without changing route identity',()=>{assert.equal(recordKey({id:ID}),ID);assert.equal(recordKey(data),RECORD);const a=recordRoute(data);assert.equal(a.id,RECORD);assert.equal(a.baseID,ID);assert.equal(data.id,ID);const p=profile(data,a),run=newRun(p);observe(run,300,'ww-quay');const old={[ID]:{stamps:['district:0','rail:loop-1'],finishes:7}},before=JSON.stringify(old),out=stampSettle(old,run,true);assert.equal(JSON.stringify(old),before);assert.deepEqual(out.records[ID],old[ID]);assert.equal(out.records[RECORD].finishes,1);assert(!out.records[RECORD].stamps.includes('rail:loop-1'));});
test('Career awards on the new layout retain earlier-layout awards and do not inherit their best time',()=>{const old={[ID]:{badges:['finish','clean'],finishes:3,best:1}},run={id:RECORD,name:'Waterwheel',total:11,delivered:0,frames:3600,incidents:0,airmail:0,nitro:0,par:250,finished:true};const out=careerSettle(old,run);assert.deepEqual(out.records[ID].badges,['finish','clean']);assert.equal(out.records[ID].best,1);assert.equal(out.records[RECORD].best,60);});
test('Malformed imported landmark metadata fails closed',()=>{assert(isLayout(data));for(const landmark of [{x:NaN,y:5,radius:100},{x:5,y:5,radius:1e9},null])assert(!isLayout({...data,gp:{...data.gp,waterwheel:{...data.gp.waterwheel,landmark}}}));});
test('Runtime remains visual/observational with no new physics or forced progression writes',()=>{const s=fs.readFileSync(new URL('../waterwheel.js',import.meta.url),'utf8');assert(!/player\.(?:x|y|vx|vy|speed)\s*=|\bwon\s*=|localStorage\.(?:clear|removeItem)/.test(s));assert(s.includes('classicCode'));});
// These are declared model recipes, not native gameplay. One initial road jump
// is seeded; every subsequent catch carries the previous velocity/contact.
const rc=F.context();rc.GroundCampaign={...rc.GroundCampaign,make:()=>data};
for(const speed of[5,6,7.5,9])for(const offset of[90,120,150,180])test(`express carried state ${speed}, launch ${offset}`,()=>{const r=F.replay(rc,{entry:IDS[0]},{speed,offset});assert.equal(r.exit,'road');assert.deepEqual(r.visits,[...IDS,'ww-east']);assert.deepEqual(r.warnings,[]);assert(r.frames.at(-1).x<9036);});
for(const remaining of[80,95,110,125,140])test(`braking ${remaining} before the lip selects the lower canal line`,()=>{const r=F.replay(rc,{entry:IDS[0],brake:{surface:IDS[0],remaining}},{remaining});assert.equal(r.exit,'road');assert.deepEqual(r.visits,['ww-rise','ww-low']);assert.deepEqual(r.warnings,[]);assert(r.frames.at(-1).x<3800);});
for(const speed of[5,7.5,9])for(const offset of[90,120,150])test(`short Post Quay detour ${speed}/${offset} returns before Mill Lane`,()=>{const r=F.replay(rc,{entry:'ww-quay'},{speed,offset});assert.equal(r.exit,'road');assert.deepEqual(r.visits,['ww-quay']);assert.deepEqual(r.warnings,[]);assert(r.frames.at(-1).x<1404);});
