import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {build,paths,groundRow,REGIONS,TRANSFERS,recordKey} from '../waterwheel-layout-core.mjs';
const require=createRequire(import.meta.url),{context,T}=require('../../../tests/helpers/flow-fixture.cjs');
const c=context(),d=build(T);
test('Waterwheel preview is deterministic and explicitly not a campaign replacement',()=>{assert.deepEqual(build(T),d);assert.equal(d.id,'canal-choices');assert.equal(d.gp.waterwheel.preview,true);assert.equal(d.gp.waterwheel.revision,2);assert.equal(d.quota,0);assert.equal(d.requiredGrapples,0);});
test('Ground-only removes sky geometry, not the ground adventure',()=>{const g=build(T,{groundOnly:true});assert.deepEqual(g.cells,d.cells);assert.equal(g.ct.length,0);assert(!g.gp.skyNetwork);assert.deepEqual(g.gp.sections,d.gp.sections);assert.deepEqual(g.boxes,d.boxes);});
test('Every column has a supported road, with at most one-tile terrace steps',()=>{for(let x=0;x<256;x++){const y=groundRow(x);assert.equal(d.cells[y*256+x],T.STEEL);if(x)assert(Math.abs(y-groundRow(x-1))<=1);for(let yy=y;yy<70;yy++)assert.equal(d.cells[yy*256+x],T.STEEL);}});
test('The complete road has start, finish, twelve deliveries, five checkpoints and separated encounters',()=>{const n=v=>[...d.cells].filter(x=>x===v).length;assert.equal(n(T.START),1);assert.equal(n(T.GOAL),1);assert.equal(n(T.MAILBOX),12);assert.equal(n(T.CHECK),5);assert.equal(n(T.BLOOP),4);assert.equal(n(T.SHIELD),4);assert.equal(n(T.PEG),0);});
test('Seven named districts and a wheelhouse landmark have ordered positions',()=>{assert.equal(REGIONS.length,7);assert(REGIONS.every((r,i)=>i===0||r.x>REGIONS[i-1].x));assert.equal(d.gp.waterwheel.landmark.x,7930);});
test('Each candidate transfer names recovery and an onward state without claiming universal reachability',()=>{for(const t of TRANSFERS){assert.equal(t.status,'candidate');assert(t.receiver&&t.onward);assert(t.recovery.length===2&&t.recovery[0]<t.recovery[1]);}});
test('Preview builds do not mutate existing campaign builders or IDs',()=>{const before=[0,1,2,3,4,5,6].map(i=>c.DeliveryCampaign.encode(c.DeliveryCampaign.build(i,T)));build(T);build(T,{groundOnly:true});assert.deepEqual(before,[0,1,2,3,4,5,6].map(i=>c.DeliveryCampaign.encode(c.DeliveryCampaign.build(i,T))));});
test('Original editor roundtrip retains all tiles, paths and layout-revision metadata',()=>{const a=c.WorkshopCore.decode(c.GroundCampaign.encode(d)),b=c.WorkshopCore.decode(c.WorkshopCore.encode(a));assert.equal(b.paths.length,7);assert.deepEqual([...b.cells],[...d.cells]);assert.equal(b.extra.gp.waterwheel.revision,2);assert.equal(b.extra.gp.waterwheel.preview,true);assert.equal(b.extra.gp.waterwheel.transfers.length,5);assert.deepEqual(Array.from(b.paths,p=>p.meta.id),paths().map(p=>p.sky.id));assert.equal(c.WorkshopCore.check(b).errors.length,0);});
test('Authoring rejects missing tile definitions and produces finite separated samples',()=>{assert.throws(()=>build({}),TypeError);const ps=paths();assert.equal(new Set(ps.map(p=>p.sky.id)).size,7);for(const p of ps){assert(p.length>60&&p.every(q=>q.length===2&&q.every(Number.isFinite)));assert(p.every(q=>q[0]>=0&&q[0]<256*36&&q[1]>=0&&q[1]<2160));}});
test('Revision key policy preserves the old record key and separates future timed layouts',()=>{assert.equal(recordKey('canal-choices',1),'canal-choices');assert.equal(recordKey('canal-choices',2),'canal-choices-r2');for(const [id,r] of [['',2],['../bad',1],['canal-choices',0],['canal-choices',NaN],['canal-choices',2.5]])assert.throws(()=>recordKey(id,r),TypeError);});
// Explicit jump seeds are model evidence, not native starts or complete gameplay.
// Position/velocity are carried continuously after the single initial seed.
for(const entry of ['ww-porch','ww-runway'])for(const speed of [5,7.5,10])for(const offset of [90,120,150])for(const mode of ['forgiving','precision'])test(`Waterwheel carried-state ${entry} speed=${speed} offset=${offset} ${mode}`,()=>{
 const fork=c.RailGripCore.create();fork.grip.configure({mode});const K=fork.physics,rails=d.ct.map(x=>K.rail(x,x.sky)),r=rails.find(x=>x.sky.id===entry),x=r.pts[0][0]-offset;
 const p={x,y:groundRow(Math.floor(x/36))*36-30,w:26,h:30,vx:speed,vy:-13,trackCD:0,_airTicks:0,onGround:false,roll:0};let entered=false,from=null,landing=null;const visits=[];
 for(let i=0;i<1500;i++){const old={x:p.x,y:p.y};if(p.trackCD>0)p.trackCD--;if(p.track){const tr=p.track;if(K.ride(p,{right:true})){from=tr.sky.id;p._airTicks=0;}}else{if(!entered){p.vy=Math.min(13,p.vy+.55);p.x+=p.vx;p.y+=p.vy;}else K.flight(p,{right:true});p._airTicks++;const hit=K.catchRail(p,old,rails,from);if(hit){entered=true;visits.push(hit.tr.sky.id);from=null;p._airTicks=0;}}assert([p.x,p.y,p.vx,p.vy].every(Number.isFinite));if(!p.track&&p.y+p.h>=groundRow(Math.floor(p.x/36))*36){landing=p.x;break;}if(p.x<0||p.x>256*36||p.y<0)break;}
 if(entry==='ww-porch'){assert.deepEqual(visits,['ww-porch']);assert(landing>1480&&landing<2300,'Porch must return before the express entrance');}
 else{assert.deepEqual(visits,['ww-runway','ww-crescent','ww-gallery','ww-finish']);assert(landing>8550&&landing<9036,'Main chain must return to road before depot goal');}
});
