"""Apply exact reviewed authorial substitutions only to generated editorial prose."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
replacements={
"This library develops Micah Blumberg's inquiries through source-linked arguments and preserved conversations.":"This library develops my inquiries through source-linked arguments and preserved conversations.",
"The developed articles are editorial syntheses of selected discussions by Micah Blumberg. They preserve his proposals and corrections without treating everything generated by the AI as his position.":"The developed articles present my arguments in a revised authorial edition of selected discussions. I distinguish the proposals and corrections from statements generated by the AI rather than treating every reply as my position.",
"A conversation can contain a strong initial proposal, a misleading AI paraphrase and a later correction by the author. [[apocalyptic-repair-theology|Apocalyptic Repair Theology]] provides a concrete example: Micah objects when a real historical warning is reduced to a purely gradual or symbolic repair process.":"A conversation can contain a strong initial proposal, a misleading AI paraphrase and a later correction. In [[apocalyptic-repair-theology|Apocalyptic Repair Theology]], I reject the reduction of a real historical warning to a purely gradual or symbolic repair process.",
"a search match does not by itself identify the author's belief":"a search match does not by itself identify my position",
"not the author's original preregistration":"not a recovered original preregistration of my predictions",
"An environmental catastrophe may later have been narrated as selecting firstborns; the author explicitly denies that natural famine itself selects birth order.":"An environmental catastrophe may later have been narrated as selecting firstborns; I distinguish that narration from a natural famine that does not itself select birth order.",
"recordings of the author, or completed manuscript chapters":"recordings of my voice, or completed manuscript chapters",
"it is not a newly recovered quotation by Micah":"it is not a newly recovered quotation from an older conversation",
"Micah can approve a voice and presentation style before the final book and series adopt them. The current implementation does not clone his voice or publish private SAN manuscript content.":"I will choose a voice and presentation style before adopting them for the final book and series. The current implementation does not clone my voice or publish private SAN manuscript content.",
"an acknowledged influence in the author's older conversations":"an acknowledged influence in my older conversations",
"That further explanation is identified as the author's theological inference.":"That further explanation is my theological inference.",
"not a claimed personal influence on Micah":"not a claimed personal influence on my earlier research",
"proof that this 2026 page was the source of Micah's 2025 statements":"proof that this 2026 page was the source of my 2025 statements",
"The author's published political-theological interpretation. The First/Second Beast passage":"My published political-theological interpretation. The First/Second Beast passage"
}
p=root/'editorial/authorial-presentation.json';assert not p.exists();p.write_text(json.dumps(replacements,indent=2,ensure_ascii=False)+'\n')
p=root/'editorial/authorial.cjs';s=p.read_text();old="module.exports={...data,articles,reword};";assert s.count(old)==1
s=s.replace(old,"const presentation=require('./authorial-presentation.json');\n// Only generated editorial prose passes through this exact, reviewed map.\nfunction present(text){for(const [old,replacement] of Object.entries(presentation))text=text.split(old).join(replacement);return text;}\nmodule.exports={...data,articles,reword,present};")
p.write_text(s)
p=root/'tools/build.cjs';s=p.read_text();old="  row.readMinutes=Math.max(1,Math.ceil(body.split(/\\s+/).length/200));";assert s.count(old)==1;s=s.replace(old,"  body=H.present(body);\n"+old);p.write_text(s)
p=root/'editorial/AUTHORIAL-VOICE.md';s=p.read_text();s+='\nGenerated navigator introductions and source-access prose use the exact reviewed substitutions in authorial-presentation.json, applied only inside the generated-page builder. This also keeps the research-method, product-plan, forecast and source-access prose in authorial voice without editing archived turns, source records, biblical names or other scholars\' attribution. Canonical article bodies remain unchanged by that presentation map.\n';p.write_text(s)
p=root/'tests/authorial.test.cjs';s=p.read_text();s+='''
test('Generated navigation and source-access prose do not turn the author back into a character',()=>{const bad=/Micah Blumberg's inquiries|Micah can approve|Micah objects|Micah's 2025 statements|the author's theological inference|his proposals and corrections/;for(const p of pages.filter(p=>p.editionGenerated||p.slug==='home')){const text=fs.readFileSync(path.join(ROOT,'content',p.path),'utf8');assert(!bad.test(text),p.slug);}for(const a of H.articles)assert.equal(H.present(a.body),a.body,a.slug);});
''';p.write_text(s)
Path(__file__).unlink()
