'use strict';
const fs=require('node:fs'),path=require('node:path');
function validate(plan,slugs){
 const errors=[],ids=new Set(),phases=new Set(plan.phases.map(p=>p.id));
 for(const t of plan.tasks){if(!/^[a-z0-9-]+$/.test(t.id)||ids.has(t.id))errors.push('Duplicate or invalid task '+t.id);ids.add(t.id);if(!plan.statuses.includes(t.status)||!phases.has(t.phase))errors.push('Unknown status/phase '+t.id);if(!t.acceptance||!t.owner||!t.priority)errors.push('Incomplete task '+t.id);if(t.status==='Verified output'&&!t.evidence.length)errors.push('Missing completion evidence '+t.id);for(const p of t.pages)if(slugs&&!slugs.has(p))errors.push('Unknown roadmap page '+p);if(t.targetDate!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(t.targetDate))errors.push('Invalid target date '+t.id);}
 const byId=new Map(plan.tasks.map(t=>[t.id,t]));for(const t of plan.tasks)for(const d of t.dependsOn)if(!byId.has(d)||d===t.id)errors.push('Unknown/self dependency '+t.id+':'+d);
 const done=new Set(),active=new Set();function visit(id){if(done.has(id)||!byId.has(id))return;if(active.has(id)){errors.push('Dependency cycle '+id);return;}active.add(id);for(const d of byId.get(id).dependsOn)visit(d);active.delete(id);done.add(id);}for(const t of plan.tasks)visit(t.id);
 return errors;
}
function build({root,plan,pages,foundations,anchors}){
 const slugs=new Set(pages.map(p=>p.slug)),errors=validate(plan,slugs);if(errors.length)throw Error(errors.join('\n'));
 const byId=new Map(plan.tasks.map(t=>[t.id,t])),developed=pages.filter(p=>p.kind==='Developed article');
 const tasks=plan.tasks.map(t=>{const unmet=t.dependsOn.filter(d=>byId.get(d).status!=='Verified output');return {...t,unmetDependencies:unmet,dependencyState:unmet.length?'Prerequisites open':'Prerequisites met',readyToStart:!unmet.length&&t.status==='Not started'};});
 const chapters=foundations.parts.flatMap(part=>part.chapters.map(c=>({...c,partId:part.id,partTitle:part.title,manuscriptStatus:'Not assessed as a manuscript chapter',taskIds:tasks.filter(t=>t.chapters.includes(c.id)).map(t=>t.id),articleCount:c.pages.filter(s=>developed.some(p=>p.slug===s)).length,sourceSlugs:[...new Set(developed.filter(p=>c.pages.includes(p.slug)).flatMap(p=>(p.references||[]).map(r=>r.slug)))],authorApproved:false})));
 const coverage=pages.filter(p=>p.sourceFile).map(p=>{const linked=developed.filter(a=>(a.references||[]).some(r=>r.slug===p.slug));const selected=[...new Set(anchors.filter(a=>a.to===p.slug).map(a=>a.turn))].sort((a,b)=>a-b);return {slug:p.slug,title:p.title,sourceFile:p.sourceFile,sha256:p.sourceSha256,bytes:p.sourceBytes,exportStartDate:p.date,turnCount:p.turnCount,articles:linked.map(a=>a.slug),chapters:chapters.filter(c=>c.pages.some(s=>linked.some(a=>a.slug===s))).map(c=>c.id),selectedTurns:selected,coverage:linked.length?'Linked to developed article':'No developed-article link recorded',readingStatus:'Not inferred',sourceURL:'https://v5ma.github.io/theology-wiki/san-reader.html?page='+encodeURIComponent(p.slug)};}).sort((a,b)=>a.title.localeCompare(b.title));
 const result={...plan,tasks,chapters,summary:{tasks:tasks.length,verifiedOutputs:tasks.filter(t=>t.status==='Verified output').length,readyToStart:tasks.filter(t=>t.readyToStart).length,dependencyEdges:tasks.reduce((n,t)=>n+t.dependsOn.length,0),chapterRoutes:chapters.length,sourceRecords:coverage.length,sourcesLinkedToArticles:coverage.filter(c=>c.articles.length).length,sourcesWithSelectedTurns:coverage.filter(c=>c.selectedTurns.length).length},coveragePolicy:'Coverage means recorded links and selected source-turn anchors. It does not measure how much has been read, quality, originality, completeness, or author approval. Export-start dates do not date every later turn.',workbook:'./planning/Theology-Research-Plan.xlsx'};
 const write=(p,obj)=>fs.writeFileSync(path.join(root,p),JSON.stringify(obj,null,2)+'\n');write('data/roadmap.json',result);write('data/source-coverage.json',{version:plan.version,policy:result.coveragePolicy,rows:coverage});return result;
}
module.exports={validate,build};
