const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const dir=__dirname+'/../mario-maker-clone/svgn-paper-route/',S=require(dir+'adventure-score.js');
const s={TextEncoder,btoa,atob,escape,unescape,stepPlayer(){}};vm.createContext(s);
for(const f of ['campaign.js','sky-routes.js','grapple-core.js','open-course.js','ground-courses.js'])vm.runInContext(fs.readFileSync(dir+f,'utf8'),s);
const raw=fs.readFileSync(dir+'index.html','utf8').match(/const T = \{([\s\S]+?)\n\};/)[1].replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\n]*/g,'');const T=vm.runInNewContext('({'+raw+'})');
for(let n=0;n<3;n++){
 test('Story '+(n+1)+' is longer, populated, and finish-only',()=>{const d=s.GroundCampaign.make(n,T);assert.equal(d.width,[224,256,288][n]);assert.equal(d.quota,0);assert.equal(d.gp.finishOnly,true);assert.ok(d.ct.length>=8);assert.ok(d.ct.some(p=>p.sky.fullLoop));assert.ok(d.gp.cast.length>=5);assert.ok(d.gp.sections.length>=6);for(const id of [T.BLOOP,T.HOVER,T.SHIELD,T.NITRO,T.STAR,T.QBLOCK])assert.ok(d.cells.includes(id));assert.ok(d.cells.filter(x=>x===T.GEAR).length>60);assert.equal(d.cells.filter(x=>x===T.GOAL).length,1);assert.equal(d.cells.filter(x=>x===T.START).length,1);for(let x=0;x<d.width;x++)assert.equal(d.cells[d.ground*d.width+x],T.STEEL);assert.ok(!d.cells.includes(T.LAVA));assert.ok(!d.cells.includes(T.SPIKE));});
 test('Story '+(n+1)+' survives native code serialization',()=>{const d=s.GroundCampaign.make(n,T),[meta,data]=s.GroundCampaign.encode(d).split('.');const m=JSON.parse(decodeURIComponent(escape(atob(meta))));assert.equal(m.gp.cast.length,5);assert.equal(m.gp.sections.length,6+n);assert.equal(m.m,['morning','canal','garden'][n]);assert.equal(m.gp.quota,0);const a=atob(data),cells=[];for(let i=0;i<a.length;i+=2)for(let j=0;j<a.charCodeAt(i+1);j++)cells.push(a.charCodeAt(i));assert.deepEqual(cells,Array.from(d.cells));});
}
test('Optional full loop follows an actual full circle and physical open exit',()=>{const d=s.GroundCampaign.make(0,T),p=d.ct.find(t=>t.sky.fullLoop);const rail=s.GrappleCore.rail(p,p.sky),player={track:rail,trackS:1,speed:3,w:26,h:30,roll:0};let high=false,exit=false;for(let i=0;i<500;i++){const r=s.GrappleCore.ride(player,{right:true});if(player.y<d.ground*36-260)high=true;if(r){exit=true;break;}}assert.ok(high&&exit);assert.ok(player.vx>0);});
test('Expert route IDs and loop requirements remain unchanged',()=>{assert.equal(s.DeliveryCampaign.build(0,T).stages,4);assert.equal(s.DeliveryCampaign.routes[3].id,'hookline-run');assert.deepEqual(Array.from(s.GroundCampaign.order),[4,5,6,3,0,1,2]);});
for(const id of Object.keys(S.SONGS))test(id+' is a 48-bar varied, finite original score with headroom',()=>{const a=S.arrangement(id),r=S.render(id,12000);assert.equal(a.bars,48);assert.ok(a.seconds>85);assert.ok(a.events.length>1000);assert.ok(new Set(a.events.map(e=>e.part)).size>=8);assert.ok(a.events.every(e=>e.beat>=0&&e.beat<a.bars*4&&e.len>0));assert.ok(r.left.every(Number.isFinite)&&r.right.every(Number.isFinite));assert.ok(r.stats.peak<.81&&r.stats.peak>.1);assert.ok(r.stats.rms>.02&&r.stats.rms<.2);assert.ok(r.left.some((v,i)=>Math.abs(v-r.right[i])>.001));});
test('Unknown soundtrack IDs and unreasonable rates are rejected',()=>{assert.throws(()=>S.render('bad'));assert.throws(()=>S.render('morning',1e9));});
