const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path').join(__dirname,'../mario-maker-clone/svgn-paper-route/');
const s={TextEncoder,btoa,atob,escape,unescape,stepPlayer(){}};vm.createContext(s);
for(const f of['campaign.js','sky-routes.js','grapple-core.js','open-course.js','ground-courses.js'])vm.runInContext(fs.readFileSync(path+f,'utf8'),s);
const T={STEEL:1,START:15,GOAL:8,CHECK:13,MAILBOX:63,PEG:60,GEAR:5};
for(let i=0;i<3;i++){
 test('Intro '+(i+1)+' has an uninterrupted, safe, finishable ground route',()=>{const d=s.GroundCampaign.make(i,T);for(let x=0;x<d.width;x++){assert.equal(d.cells[d.ground*d.width+x],1);assert.ok([0,15,8,13,63].includes(d.cells[(d.ground-1)*d.width+x]));}assert.equal(d.stages,0);assert.equal(d.minTransfers,0);assert.equal(d.requiredGrapples,0);assert.ok(d.roadBoxes.length>=d.quota);assert.equal(d.cells.filter(v=>v===T.START).length,1);assert.equal(d.cells.filter(v=>v===T.GOAL).length,1);});
 test('Intro '+(i+1)+' has optional raised finite geometry and serialized beginner rules',()=>{const d=s.GroundCampaign.make(i,T);assert.ok(d.ct.every(p=>p.sky.optional&&p.every(q=>q.every(Number.isFinite))));assert.ok(d.ct.every(p=>Math.max(...p.map(q=>q[1]))<=d.ground*36-70));const [m,raw]=s.GroundCampaign.encode(d).split('.');const meta=JSON.parse(decodeURIComponent(escape(atob(m))));assert.equal(meta.gp.groundStart,true);assert.equal(meta.gp.requiredGrapples,0);const a=atob(raw),tiles=[];for(let j=0;j<a.length;j+=2)for(let k=0;k<a.charCodeAt(j+1);k++)tiles.push(a.charCodeAt(j));assert.deepEqual(tiles,Array.from(d.cells));});
}
test('Existing expert course IDs and builds remain intact',()=>{assert.deepEqual(Array.from(s.GroundCampaign.order),[4,5,6,3,0,1,2]);assert.equal(s.DeliveryCampaign.routes.length,7);assert.equal(s.DeliveryCampaign.build(0,T).stages,4);assert.equal(s.DeliveryCampaign.build(3,T).requiredGrapples,1);});
test('Intro routes teach increasingly higher options without adding forced traps',()=>{const d=[0,1,2].map(i=>s.GroundCampaign.make(i,T));assert.ok(d[0].width<d[1].width&&d[1].width<d[2].width);assert.equal(d[0].ct.length,1);assert.equal(d[1].ct.length,3);assert.equal(d[2].ct.length,4);assert.equal(d[0].cells.filter(v=>v===60).length,0);assert.equal(d[2].cells.filter(v=>v===60).length,3);assert.throws(()=>s.GroundCampaign.make(9,T));});
