import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {move,nearest,readClues,animalPose,SPAWN,LIMIT,LAKE} from '../dino-atlas/expedition-core.js';
import {DINOS} from '../dino-atlas/core.js';
import * as THREE from '../dino-atlas/vendor/three.module.js';
import {makeDinosaur,makeExplorer} from '../dino-atlas/dino-models.js';
const text=await readFile(new URL('../mario-maker-clone/svgn-paper-route/campaign.js',import.meta.url),'utf8');
const sandbox={TextEncoder,btoa};vm.createContext(sandbox);vm.runInContext(text,sandbox);const C=sandbox.DeliveryCampaign;
const base=await readFile(new URL('../mario-maker-clone/svgn-paper-route/index.html',import.meta.url),'utf8');
const ids=base.match(/const T = \{([\s\S]+?)\n\};/)[1].replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\n]*/g,'');
const T=vm.runInNewContext('({'+ids+'})');
test('Campaign levels have ground, one spawn, one goal, and all advertised mailboxes',()=>{for(let i=0;i<3;i++){const r=C.build(i,T);assert.equal(r.cells.length,r.width*r.height);assert.equal(r.cells.filter(t=>t===T.START).length,1);assert.equal(r.cells.filter(t=>t===T.GOAL).length,1);assert.equal(r.cells.filter(t=>t===T.MAILBOX).length,r.mail.length);assert.ok(r.quota<=r.mail.length);for(let x=0;x<r.width;x++)assert.ok([T.STEEL,T.CONVR].includes(r.cells[r.ground*r.width+x]));}});
test('Campaign serialization round trips every tile',()=>{for(let i=0;i<3;i++){const r=C.build(i,T),[m,c]=C.encode(r).split('.'),meta=JSON.parse(atob(m)),raw=atob(c);const cells=[];for(let j=0;j<raw.length;j+=2)for(let n=0;n<raw.charCodeAt(j+1);n++)cells.push(raw.charCodeAt(j));assert.deepEqual(cells,Array.from(r.cells));assert.equal(meta.w,r.width);assert.equal(meta.h,r.height);}});
test('Medals require all mailboxes and a clean target-time run for gold',()=>{assert.equal(C.medal({delivered:6,total:6,seconds:70,par:85,attempts:1}),'gold');assert.equal(C.medal({delivered:6,total:6,seconds:70,par:85,attempts:2}),'silver');assert.equal(C.medal({delivered:4,total:6,seconds:20,par:85,attempts:1}),'bronze');});
test('Corrupt or blocked local records do not break the campaign',()=>{assert.equal(Object.keys(C.loadRecords({getItem(){throw Error('blocked')}})).length,0);assert.equal(Object.keys(C.loadRecords({getItem:()=>'{bad'})).length,0);});
test('Explorer movement is normalized and bounded',()=>{const p=move({...SPAWN},1,1,.05);assert.ok(Math.hypot(p.x-SPAWN.x,p.z-SPAWN.z)<=.351);for(let i=0;i<1000;i++){const q=move({x:LIMIT,z:0},1,1,.1);assert.ok(Math.hypot(q.x,q.z)<=LIMIT+.0001);}});
test('Explorer cannot enter the lake',()=>{const q=move({x:LAKE.x,z:LAKE.z},0,1,.1);assert.ok(Math.hypot(q.x-LAKE.x,q.z-LAKE.z)>=LAKE.r+.99);});
test('Only nearby evidence can be inspected',()=>{assert.equal(nearest({x:0,z:0},[{id:'far',x:15,z:0}]),null);assert.equal(nearest({x:0,z:0},[{id:'near',x:3,z:0}]).id,'near');});
test('Clue saves are whitelisted and animal poses change with time',()=>{assert.equal(readClues({getItem:()=>JSON.stringify(['jurassic:tracks','unknown','jurassic:tracks'])}).size,1);assert.notDeepEqual(animalPose(0,0),animalPose(0,5));});
test('Every new 3D dinosaur and explorer has finite nonempty geometry',()=>{for(const group of [...DINOS.map(d=>makeDinosaur(THREE,d)),makeExplorer(THREE)]){let n=0;group.traverse(o=>{if(o.geometry){n++;const a=o.geometry.getAttribute('position').array;assert.ok(a.length);assert.ok(a.every(Number.isFinite));}});assert.ok(n>=9);}});
