const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root=__dirname+'/../mario-maker-clone/svgn-paper-route/';
const s={btoa,atob,TextEncoder,escape,unescape,stepPlayer(){}};vm.createContext(s);
for(const f of ['campaign.js','sky-routes.js','grapple-core.js','open-course.js','ground-courses.js','sky-network-layout.js','sky-network-art.js'])vm.runInContext(fs.readFileSync(root+f,'utf8'),s,{filename:f});
const T={STEEL:1,BRICK:2,CRATE:3,GEAR:5,SPRING:6,PLAT:7,GOAL:8,BCRATE:9,CHECK:13,START:15,BLOOP:16,SHELL:17,HOVER:18,NITRO:27,BIKEDOCK:36,SHIELD:43,STAR:44,PEG:60,MAILBOX:63,QBLOCK:84};
for(let n=0;n<3;n++){
 test('Chapter '+(n+1)+' is a multi-height connected world rather than a row of rings',()=>{const d=s.GroundCampaign.make(n,T),net=d.gp.skyNetwork;assert.ok(d.ct.length>=40);assert.ok(new Set(d.ct.map(p=>p.sky.shape)).size>=8);assert.ok(d.ct.some(p=>p.sky.tier===1)&&d.ct.some(p=>p.sky.tier===3));const ys=d.ct.flatMap(p=>p.map(q=>q[1]));assert.ok(Math.max(...ys)-Math.min(...ys)>1100);assert.ok(net.mainIDs.length>=6);assert.ok(net.pegCount>=30);for(const p of d.ct){assert.ok(p.sky.network&&p.sky.optional);assert.ok(p.flat().every(Number.isFinite));}for(const sec of net.sectors)assert.ok(d.ct.filter(p=>p.sky.sector===Number(sec.id.split('-')[1])).length>=5);});
 test('Chapter '+(n+1)+' retains the complete ground, finish and encounter systems',()=>{const d=s.GroundCampaign.make(n,T);for(let x=0;x<d.width;x++)assert.equal(d.cells[d.ground*d.width+x],T.STEEL);assert.equal(d.quota,0);assert.equal(d.stages,0);assert.equal(d.requiredGrapples,0);assert.ok(d.gp.finishOnly);assert.equal(d.cells.filter(v=>v===T.GOAL).length,1);assert.equal(d.cells.filter(v=>v===T.START).length,1);assert.ok(d.cells.includes(T.BLOOP)&&d.cells.includes(T.STAR));});
 test('Chapter '+(n+1)+' exports all tracks and network metadata in native level codes',()=>{const d=s.GroundCampaign.make(n,T),code=s.GroundCampaign.encode(d),meta=JSON.parse(decodeURIComponent(escape(atob(code.split('.')[0]))));assert.equal(meta.ct.length,d.ct.length);assert.equal(meta.cm.length,d.ct.length);assert.equal(meta.gp.skyNetwork.mainIDs.length,d.gp.skyNetwork.mainIDs.length);assert.ok(meta.cm.every(m=>m.network));});
}
test('A normal throttled ride makes at least five detached transfers along the main upper route',()=>{const d=s.GroundCampaign.make(0,T),K=s.GrappleCore,rails=d.ct.filter(p=>d.gp.skyNetwork.mainIDs.includes(p.sky.id)).map(p=>{const t=K.rail(p);t.sky=p.sky;return t;});const p={w:26,h:30,x:0,y:0,vx:0,vy:0,speed:0,track:rails[0],trackS:1,trackCD:0,dir:1,onGround:true};K.pose(p,p.track,p.trackS);let from=null,catches=0,air=0,totalAir=0;for(let i=0;i<1800;i++){if(p.track){const t=p.track,r=K.ride(p,{right:true});if(r?.exit){from=t.sky.id;air=0;}}else{const old={x:p.x,y:p.y};if(p.trackCD>0)p.trackCD--;K.flight(p,{right:true});air++;const hit=K.catchRail(p,old,rails,from);if(hit){assert.ok(air>3);catches++;totalAir+=air;from=null;}}if(catches>=5)break;}assert.ok(catches>=5);assert.ok(totalAir>100);assert.ok(p.y<1500);});
test('Joined road sections have finite bounded miter frames',()=>{const d=s.GroundCampaign.make(0,T);for(const p of d.ct)for(const f of s.SkyNetworkArt.sectionFrames(p)){assert.ok(Object.values(f).every(Number.isFinite));assert.ok(f.miter>=1&&f.miter<=1.65);}});
test('Expert course identifiers and their explicit challenge rules are preserved',()=>{assert.equal(s.DeliveryCampaign.routes.length,7);assert.equal(s.DeliveryCampaign.routes[0].id,'sky-first-flight');assert.equal(s.DeliveryCampaign.build(0,T).stages,4);assert.equal(s.DeliveryCampaign.build(3,T).requiredGrapples,1);assert.deepEqual(Array.from(s.GroundCampaign.order),[4,5,6,3,0,1,2]);});
