"""Native HTTP editor acceptance. All changes go through actual editor controls.
Only observations use page.evaluate; no player state or editor documents are set.
"""
import json,os,time
from pathlib import Path
from urllib.parse import urlparse
from playwright.sync_api import sync_playwright
MODE=os.getenv('WORKSHOP_SUITE','authoring')
OUT=Path('test-output')/('workshop-'+MODE);OUT.mkdir(parents=True,exist_ok=True)
BASE=os.getenv('TEST_BASE_URL','http://127.0.0.1:4173').rstrip('/')
checks=[];errors=[];console=[]
def check(ok,label):
    assert ok,label
    checks.append(label);print('PASS: '+label,flush=True)
def code(page):return page.evaluate('WorkshopCore.encode(RouteWorkshop.state.doc)')
def point(page,x,y):
    v=page.evaluate('({...RouteWorkshop.state.view})');b=page.locator('#maker-canvas').bounding_box()
    return b['x']+(x-v['x'])*v['zoom'],b['y']+(y-v['y'])*v['zoom']
def click_world(page,x,y):
    a,b=point(page,x,y);page.mouse.click(a,b)
def action(page,name):page.locator(f'#route-workshop [data-mk="{name}"]').click()
def wait_editor(page):page.wait_for_function('window.RouteWorkshop?.active&&RouteWorkshop.state.doc')
with sync_playwright() as p:
    kw={'headless':True,'args':['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}
    if os.getenv('CHROMIUM_PATH'):kw['executable_path']=os.environ['CHROMIUM_PATH']
    browser=p.chromium.launch(**kw)
    ctx=browser.new_context(viewport={'width':1440,'height':960},service_workers='block',record_video_dir=str(OUT/'video'),accept_downloads=True)
    ctx.add_init_script("localStorage.setItem('sprocket_muted','1')")
    host=urlparse(BASE).hostname
    ctx.route('**/*',lambda r:r.continue_() if urlparse(r.request.url).hostname==host or r.request.url.startswith(('data:','blob:')) else r.abort())
    page=ctx.new_page();page.set_default_timeout(90000)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda m:console.append(m.text) if m.type=='error' else None)
    page.on('dialog',lambda d:d.accept())
    try:
        page.goto(BASE+'/mario-maker-clone/svgn-paper-route/index.html',wait_until='domcontentloaded')
        page.wait_for_function('window.RouteWorkshop&&window.__gpuReady===true')
        legacy=page.evaluate('levelCode()');records=page.evaluate('localStorage.getItem("svgn_delivery_records_v1")');credits=page.evaluate('credits')
        persistent_before=page.evaluate('Object.fromEntries(["sprocket_ghosts","sprocket_ledger_buf","sprocket_pack_beaten","sprocket_credits"].map(k=>[k,localStorage.getItem(k)]))')
        page.locator('#delivery-header [data-delivery="editor"]').click();wait_editor(page)
        check(page.evaluate('RouteWorkshop.state.doc.paths.length===30'),'Create opens the full connected-world Workshop, not the old palette')
        check(page.evaluate('RouteWorkshop.state.doc.extra.gp.cast.length>0&&RouteWorkshop.state.doc.extra.gp.skyNetwork.pegCount===5'),'The complete world preserves native characters and all peg metadata')
        check(page.locator('#maker-pieces [data-piece]').count()==8,'Open ramps, partial loops, bowls, shelves and full loops are available as editable parts')
        page.screenshot(path=str(OUT/'editor-overview.png'))
        if MODE=='authoring':
            page.locator('#maker-sector').select_option('0')
            page.screenshot(path=str(OUT/'editor-neighborhood.png'))
            page.locator('#maker-outline [data-track="0"]').click()
            before=code(page);before_meta=page.evaluate('JSON.stringify(RouteWorkshop.state.doc.paths[0].meta)')
            bounds=page.evaluate('WorkshopCore.bounds([RouteWorkshop.state.doc.paths[0]])')
            page.locator('#maker-x').fill(str(round(bounds['x'])+36));page.locator('#maker-x').press('Tab')
            check(page.evaluate('WorkshopCore.bounds([RouteWorkshop.state.doc.paths[0]]).x')==round(bounds['x'])+36,'Inspector moves the actual roadway coordinates')
            check(page.evaluate('JSON.stringify(RouteWorkshop.state.doc.paths[0].meta)')==before_meta,'Moving a network piece retains its stable identity and movement metadata')
            action(page,'undo');check(code(page)==before,'Undo restores the entire document, not just tile paint')
            action(page,'redo');moved=code(page);check(moved!=before,'Redo restores a transformed curve')
            action(page,'duplicate');check(page.evaluate('RouteWorkshop.state.doc.paths.length')==31,'Duplicate creates a new independently identified track')
            check(page.evaluate('new Set(RouteWorkshop.state.doc.paths.map(p=>p.meta.id)).size')==31,'Duplicated network tracks do not reuse checkpoint identities')
            action(page,'rotateleft');action(page,'flip');transformed=code(page)
            page.locator('#maker-canvas').focus();page.keyboard.press('Control+z');page.keyboard.press('Control+y')
            check(code(page)==transformed,'Keyboard undo and redo match toolbar history')
            page.locator('#maker-handles').check();action(page,'focus')
            xy=page.evaluate('(()=>{const p=RouteWorkshop.state.doc.paths[[...RouteWorkshop.state.selected][0]];return p.points[Math.round((p.points.length-1)/2)];})()')
            a,b=point(page,*xy);before_handle=code(page)
            page.mouse.move(a,b);page.mouse.down();page.mouse.move(a+28,b-30,steps=6);page.mouse.up()
            check(code(page)!=before_handle,'Dragging a visible shape handle reshapes the actual polyline')
            action(page,'undo');check(code(page)==before_handle,'Shape edits have an undoable document snapshot')
            page.locator('#maker-name').fill('My connected sky workshop');page.locator('#maker-name').press('Tab')
            action(page,'save');saved=code(page)
            check(page.evaluate('JSON.parse(localStorage.getItem("svgn_route_workshop_library_v2")).length')==1,'Save writes a named draft without touching campaign records')
            with page.expect_download() as info:action(page,'export')
            download=info.value;download.save_as(OUT/'authored-world.route');check((OUT/'authored-world.route').read_text()==saved,'Portable export is the exact authored native level code')
            action(page,'starter');check(page.evaluate('RouteWorkshop.state.doc.paths.length')==2,'A fresh beginner template keeps the ground and adds optional upper paths')
            page.locator('#maker-file').set_input_files(OUT/'authored-world.route')
            page.wait_for_function('RouteWorkshop.state.doc.paths.length===31')
            check(code(page)==saved,'Import retains every track, terrain tile, neighbor and soundtrack field')
            page.locator('#maker-file').set_input_files({'name':'bad.route','mimeType':'text/plain','buffer':b'not a level'})
            page.wait_for_function('document.getElementById("maker-status").innerText.includes("Expected")')
            check(code(page)==saved,'Rejected imports leave the current draft intact')
            action(page,'starter');action(page,'fit')
            page.locator('#maker-tiles [data-tile="60"]').click();click_world(page,32*36+18,54*36+18)
            check(page.evaluate('RouteWorkshop.state.doc.cells[54*96+32]')==60,'Peg placement edits a real native peg tile')
            page.locator('#route-workshop [data-tool="select"]').click();click_world(page,32*36+18,54*36+18)
            page.locator('#maker-canvas').focus();page.keyboard.press('ArrowRight')
            check(page.evaluate('RouteWorkshop.state.doc.cells[54*96+33]===60&&RouteWorkshop.state.doc.cells[54*96+32]===0'),'Selecting and nudging a peg moves the actual object')
            page.locator('#maker-tiles [data-tile="2"]').click();a,b=point(page,1500,1980);c,d=point(page,1650,1980)
            page.mouse.move(a,b);page.mouse.down();page.mouse.move(c,d,steps=2);page.mouse.up()
            check(page.evaluate('Array.from(RouteWorkshop.state.doc.cells.slice(55*96+41,55*96+46)).every(x=>x===2)'),'Fast terrain painting fills every tile along the stroke')
            page.locator('#maker-add-neighbor').click();click_world(page,46*36,59*36-20)
            page.locator('#maker-neighbor-name').fill('Pip');page.locator('#maker-neighbor-name').press('Tab')
            page.locator('#maker-neighbor-text').fill('The lower street and upper ramps both lead forward.');page.locator('#maker-neighbor-text').press('Tab')
            check(page.evaluate('RouteWorkshop.state.doc.extra.gp.cast[0].name')=='Pip','Postal characters and their actual in-game dialogue are editable')
            page.locator('#maker-music').select_option('garden');action(page,'save')
            check(page.evaluate('JSON.parse(localStorage.getItem("svgn_route_workshop_library_v2")).length')==2,'The library preserves separate drafts instead of overwriting the previous world')
            draft=code(page)
            page.locator('#maker-name').fill('Temporary unsaved rename');page.locator('#maker-name').press('Tab');page.wait_for_timeout(800)
            page.locator('#maker-canvas').focus();page.keyboard.press('Control+z')
            check(code(page)==draft,'Undo also updates the recovery snapshot instead of resurrecting discarded edits')
            page.reload(wait_until='domcontentloaded');page.wait_for_function('window.RouteWorkshop&&window.__gpuReady===true');page.locator('#delivery-header [data-delivery="editor"]').click();wait_editor(page)
            check(code(page)==draft,'The last saved/recovery draft survives a page reload')
            page.locator('#maker-name').fill('Recovered neighborhood');page.locator('#maker-name').press('Control+s')
            check(page.evaluate('JSON.parse(localStorage.getItem("svgn_route_workshop_library_v2"))[0].name')=='Recovered neighborhood','Ctrl+S saves pending text-field edits')
            check(page.evaluate('JSON.parse(localStorage.getItem("svgn_route_workshop_library_v2")).length')==2,'Saving a recovered draft updates its existing library slot')
            page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(200)
            check(not page.evaluate('document.documentElement.scrollWidth>innerWidth'),'The Workshop fits a phone-width viewport')
            page.locator('#maker-inspector-toggle').click();check(page.locator('.maker-inspector').is_visible(),'Small screens retain accessible properties instead of losing edit controls')
            page.screenshot(path=str(OUT/'editor-mobile-properties.png'))
            page.locator('#maker-inspector-close').click();check(not page.locator('.maker-inspector').is_visible(),'Phone properties can be closed to resume canvas editing')
            page.screenshot(path=str(OUT/'editor-mobile.png'))
            check(page.evaluate('mode==="edit"&&!__delivery.paused'),'Editor keyboard inputs did not accidentally start or pause gameplay')
        else:
            action(page,'starter');action(page,'fit')
            page.locator('#maker-name').fill('Playtest neighborhood');page.locator('#maker-name').press('Tab')
            page.locator('#maker-tiles [data-tile="5"]').click();click_world(page,10*36+18,59*36+18)
            page.locator('#maker-tiles [data-tile="43"]').click();click_world(page,12*36+18,59*36+18)
            page.locator('#maker-tiles [data-tile="8"]').click();click_world(page,48*36+18,59*36+18)
            page.locator('#maker-music').select_option('canal')
            before=code(page);view=page.evaluate('({...RouteWorkshop.state.view})');hist=page.evaluate('RouteWorkshop.state.history.index')
            page.screenshot(path=str(OUT/'starter-authored.png'))
            action(page,'test');page.wait_for_function('RouteWorkshop.testing&&__ground.active()&&player.onGround&&__merged.camera.isPerspectiveCamera',timeout=90000)
            check(page.evaluate('grid[59*LW+12]===T.SHIELD&&grid[59*LW+48]===T.GOAL&&musicName==="canal"'),'3D playtest loads the authored shield, relocated finish and chosen soundtrack')
            check(page.evaluate('__delivery.state.route===-1&&__sky.state.data.stages===0'),'Custom playtests remain optional-route adventures, not campaign record attempts')
            page.locator('#cv').focus();page.keyboard.down('KeyD');page.wait_for_function('player.shield',timeout=120000)
            check(page.evaluate('player.shield'),'The shield placed through the editor is collected by the real rider')
            check(page.evaluate('gears>0&&pg(10,59)===T.EMPTY'),'The placed envelope is collected and counted in the real run')
            page.screenshot(path=str(OUT/'actual-3d-playtest.png'))
            page.wait_for_function('won',timeout=180000);page.keyboard.up('KeyD')
            check(page.evaluate('won&&tries===1&&__adventure.state.transition===null'),'Reaching the edited finish completes the test without jumping to a featured campaign level')
            check(page.evaluate('credits')>credits,'A real finish payout changes only temporary preview coins')
            page.locator('#maker-return').click();wait_editor(page)
            check(code(page)==before,'Return from real gameplay restores the exact unmodified draft')
            check(page.evaluate('({...RouteWorkshop.state.view})')==view,'Returning keeps the editor viewport')
            check(page.evaluate('RouteWorkshop.state.history.index')==hist,'Playtest does not reset undo history')
            check(page.evaluate('credits')==credits,'Test collectibles do not alter persistent campaign coins')
            page.locator('#maker-route').select_option('4');action(page,'route');action(page,'test')
            page.wait_for_function('RouteWorkshop.testing&&__network.active()&&player.onGround',timeout=90000)
            check(page.evaluate('tracks.filter(t=>t.sky?.network).length===46&&__ground.meta.skyNetwork.pegCount===5'),'The connected-world copy loads all 46 roadways and 38 pegs in the actual engine')
            page.locator('#cv').focus();page.keyboard.down('KeyD');page.wait_for_function('player.x>630',timeout=120000);page.keyboard.down('Space');page.wait_for_function('!!player.track',timeout=90000);page.keyboard.up('Space');page.keyboard.up('KeyD')
            check(page.evaluate('!!player.track?.sky.network'),'The rider catches an editable upper roadway through a normal jump')
            page.screenshot(path=str(OUT/'full-world-playtest.png'))
            page.locator('#maker-return').click();wait_editor(page);check(page.evaluate('RouteWorkshop.state.doc.paths.length===30'),'Returning keeps the entire connected-world document intact')
            action(page,'legacy');check(page.evaluate('mode==="edit"&&!RouteWorkshop.active&&customTracks.length===46'),'The original advanced editor remains available with the same complete track data')
            check(page.locator('#palette .pal').count()>50,'Existing advanced tile tools are retained')
        check(page.evaluate('localStorage.getItem("svgn_delivery_records_v1")')==records,'Authoring and preview leave existing campaign medal records unchanged')
        check(page.evaluate('Object.fromEntries(["sprocket_ghosts","sprocket_ledger_buf","sprocket_pack_beaten","sprocket_credits"].map(k=>[k,localStorage.getItem(k)]))')==persistent_before,'Preview and authoring do not write persistent ghosts, win logs, pack records or coins')
        check(not errors,'No uncaught JavaScript errors in the tested editor flow')
        fatal=[e for e in console if any(t in e for t in ['GL_INVALID','VALIDATION','shader error','CommandBuffer'])]
        check(not fatal,'No detected GPU validation errors during native preview')
        (OUT/'report.json').write_text(json.dumps({'suite':MODE,'passed':len(checks),'checks':checks,'errors':errors,'gpu_errors':fatal,'scope':'Edits through UI, native HTTP perspective preview, and read-only inspection. No rider-state writes. Software rendering, not a physical-device performance claim.'},indent=2))
    except Exception as e:
        try:state=page.evaluate('({mode,testing:RouteWorkshop.testing,active:RouteWorkshop.active,name:RouteWorkshop.state.doc?.name,tracks:RouteWorkshop.state.doc?.paths.length,status:document.getElementById("maker-status")?.textContent})')
        except:state=None
        (OUT/'failure.json').write_text(json.dumps({'error':str(e),'checks':checks,'errors':errors,'state':state,'console':console[-20:]},indent=2))
        try:page.screenshot(path=str(OUT/'failure.png'),full_page=True)
        except:pass
        raise
    finally:ctx.close();browser.close()
