import test from 'node:test';import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';import {initPhysics,ParkPhysics} from '../ranger-physics.js';
import {buildTidegate} from '../tidegate-world.js';import {TidegateFleet} from '../tidegate-actors.js';import {emptyDistrict,applyDistrict} from '../tidegate-core.js';
// A canvas stub is only for labels during geometry construction. Rapier bodies,
// movement, walls and ramps below are real, not a rendered/graphics acceptance.
globalThis.document={createElement(){return {width:1024,height:256,getContext(){return new Proxy({measureText:t=>({width:t.length*18})},{get:(o,k)=>k in o?o[k]:()=>{}});}};}};
await initPhysics();
function setup(){const state=emptyDistrict(),physics=new ParkPhysics(),scene=new T.Scene(),world=buildTidegate(scene,physics,state),fleet=new TidegateFleet(physics,world,state,()=>{});return {state,physics,world,fleet};}
function tick(g,v={},n=1){for(let i=0;i<n;i++){g.world.update(1/60,0,g.state,g.fleet.position,false);g.fleet.step(v,1/60,0,0);g.physics.world.step();g.fleet.after(1/60);}}
function walk(g,x,z){let arrived=false;for(let i=0;i<2800;i++){const p=g.fleet.position,dx=x-p.x,dz=z-p.z,d=Math.hypot(dx,dz);if(d<.7){arrived=true;break;}tick(g,{x:dx/d,z:-dz/d});}assert.ok(arrived,`Real walk blocked on way to ${x},${z}, at ${JSON.stringify(g.fleet.position)}`);tick(g,{},20);}
test('Authored high route, feeder, pump-house aisle and permanent bridge are physically connected',()=>{const g=setup();try{tick(g,{},60);for(const [x,z] of [[-34,43],[-25,43],[-25,15],[-48,-12],[-35,-22],[-35,-26]])walk(g,x,z);assert.ok(g.fleet.position.y>6,'Overlook is an actual elevated route');for(const [x,z] of [[-35,-30],[-35,-38],[-12,-36],[12,-36],[35,-36],[57,-36],[58,-18],[51,-18]])walk(g,x,z);applyDistrict(g.state,'feed');for(const [x,z] of [[58,-18],[58,20],[48,21],[44,10],[39,10],[30,10],[30,8]])walk(g,x,z);assert.ok(g.fleet.position.x<42&&g.fleet.position.z<16,'Inside real pump house');applyDistrict(g.state,'repair');for(const [x,z] of [[33,10],[33,19],[18,26]])walk(g,x,z);assert.ok(applyDistrict(g.state,'bridge').changed);for(const [x,z] of [[14,24],[0,24],[-17,24],[-28,27],[-37,29]])walk(g,x,z);assert.ok(applyDistrict(g.state,'report').changed);}finally{g.physics.world.free();}});
test('Closed river crossing is blocked by actual character motion without trapping the upper route',()=>{const g=setup();try{g.fleet.person.setActive(true,{x:-13,y:1.2,z:24});tick(g,{x:1},300);assert.ok(g.fleet.position.x<-9);g.state.gearbox=true;g.state.bridge=true;tick(g,{x:1},330);assert.ok(g.fleet.position.x>9);}finally{g.physics.world.free();}});
