import test from 'node:test';import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';import {initPhysics,ParkPhysics} from '../ranger-physics.js';
import {buildTidegate} from '../tidegate-world.js';import {TidegateFleet} from '../tidegate-actors.js';import {emptyDistrict,applyDistrict} from '../tidegate-core.js';
// A canvas stub is only for labels during geometry construction. Rapier bodies,
// movement, walls and ramps below are real, not a rendered/graphics acceptance.
globalThis.document={createElement(){return {width:1024,height:256,getContext(){return new Proxy({measureText:t=>({width:t.length*18})},{get:(o,k)=>k in o?o[k]:()=>{}});}};}};
await initPhysics();
function setup(){const state=emptyDistrict(),physics=new ParkPhysics(),scene=new T.Scene(),world=buildTidegate(scene,physics,state),fleet=new TidegateFleet(physics,world,state,()=>{});return {state,physics,world,fleet};}
function tick(g,v={},n=1){for(let i=0;i<n;i++){g.world.update(1/60,0,g.state,g.fleet.position,false);g.fleet.step(v,1/60,0,0);g.physics.world.step();g.fleet.after(1/60);}}
function walk(g,x,z){let arrived=false;for(let i=0;i<2800;i++){const p=g.fleet.position,dx=x-p.x,dz=z-p.z,d=Math.hypot(dx,dz);if(d<.7){arrived=true;break;}tick(g,{x:dx/d,z:-dz/d});}assert.ok(arrived,`Real walk blocked on way to ${x},${z}, at ${JSON.stringify(g.fleet.position)}`);tick(g,{},20);}
test('Authored high route, feeder, pump-house aisle and permanent bridge are physically connected',()=>{const g=setup();try{tick(g,{},60);for(const [x,z] of [[-34,43],[-25,43],[-25,15],[-48,-12],[-35,-22],[-35,-26]])walk(g,x,z);assert.ok(g.fleet.position.y>6,'Overlook is an actual elevated route');for(const [x,z] of [[-35,-30],[-35,-38],[-12,-36],[12,-36],[35,-36],[57,-36],[58,-18],[51,-18]])walk(g,x,z);applyDistrict(g.state,'feed');for(const [x,z] of [[58,-18],[58,20],[48,21],[44,10],[39,10],[30,10],[30,8]])walk(g,x,z);assert.ok(g.fleet.position.x<42&&g.fleet.position.z<16,'Inside real pump house');applyDistrict(g.state,'repair');for(const [x,z] of [[33,10],[33,19],[18,26]])walk(g,x,z);assert.ok(applyDistrict(g.state,'bridge').changed);for(const [x,z] of [[14,24],[0,24],[-17,24],[-28,27],[-37,29]])walk(g,x,z);assert.ok(applyDistrict(g.state,'report').changed);}finally{g.physics.world.free();}});
test('Closed river crossing is blocked by actual character motion without trapping the upper route',()=>{const g=setup();try{g.fleet.person.setActive(true,{x:-13,y:1.2,z:24});tick(g,{x:1},300);assert.ok(g.fleet.position.x<-9);g.state.gearbox=true;g.state.bridge=true;tick(g,{x:1},330);assert.ok(g.fleet.position.x>9);}finally{g.physics.world.free();}});
test('Patrol boat is boardable from the west landing and reaches the physical roof route from the east landing',()=>{const g=setup();try{tick(g,{},60);for(const p of [[-34,43],[-25,43],[-14,38],[-12,38]])walk(g,...p);assert.equal(g.fleet.nearest()?.id,'boat');assert.equal(g.fleet.board(),true);for(let i=0;i<600;i++){const e=Math.atan2(Math.sin(Math.PI/2-g.fleet.actor.heading),Math.cos(Math.PI/2-g.fleet.actor.heading));tick(g,{steer:Math.max(-1,Math.min(1,e*3)),throttle:Math.abs(e)<.1&&g.fleet.position.x<6?1:0});}tick(g,{brake:true},120);assert.ok(g.fleet.position.x>6);assert.equal(g.fleet.board(),true);assert.equal(g.fleet.mode,'foot');assert.ok(g.fleet.position.x>9);for(const p of [[24,38],[57,24],[57,20],[48,20],[48,18],[48,3.4],[48,1],[47.5,-3.5],[51.2,-2],[51.2,14],[41,14],[38,14]])walk(g,...p);assert.ok(g.fleet.position.y>9,'Ramp meets roof without an oversized platform lip');assert.equal(g.state.gearbox,false,'Neither boat arrival nor roof arrival auto-completes hands-on work');}finally{g.physics.world.free();}});
test('Helicopter retains a real flight and safe rooftop disembark without completing the objective remotely',()=>{const g=setup();try{tick(g,{},60);walk(g,-35,43);walk(g,-53,43);assert.equal(g.fleet.nearest()?.id,'helicopter');assert.equal(g.fleet.board(),true);tick(g,{climb:1},80);tick(g,{},220);assert.ok(g.fleet.position.y>12);for(let i=0;i<1600;i++){const p=g.fleet.position,dx=38-p.x,dz=14-p.z,d=Math.hypot(dx,dz);tick(g,d>1?{x:dx/d,z:-dz/d}:{});if(d<1&&g.fleet.actor.speed<.3)break;}tick(g,{climb:-1},90);tick(g,{},300);assert.ok(g.fleet.position.y>8&&g.fleet.position.y<10);assert.equal(g.fleet.board(),true);assert.equal(g.fleet.mode,'foot');assert.ok(g.fleet.position.y>9);assert.equal(g.state.gearbox,false);assert.equal(g.state.bridge,false);}finally{g.physics.world.free();}});

test('Service doorway clears the precise ramp-side position that blocked the native controller tour',()=>{const g=setup();try{tick(g,{},60);g.fleet.person.setActive(true,{x:43.845916748046875,y:.7897158265113831,z:10.393089294433594});tick(g,{x:-1},90);assert.ok(g.fleet.position.x<39,'The captured native stuck position must enter the doorway without a jump or reset');}finally{g.physics.world.free();}});
