"""Seed the canonical production workbook once; never overwrite later status edits."""
from pathlib import Path
import json
P=Path(__file__).resolve().parents[1]
if (P/'production/roadmap.json').exists():
 print('Production record already exists; preserving edits.');raise SystemExit(0)
M=[('M0','Stop fighting the game','Measured control, save and performance baseline.','Approve a 10-minute high-speed route on a named desktop and physical Xbox controller.'),('M1','One exceptional neighborhood','A coherent Homecoming vertical slice before more map expansion.','Approve one street, hero character, vehicle, interior and a compelling 15-minute play experience.'),('M2','A city with a reason to exist','Distinct districts, useful buildings and believable activity.','Explore without relying on repeated delivery templates or empty distance.'),('M3','A campaign worth finishing','Authored missions, progression, consequences and replay depth.','Fresh players can describe the story and choose a next activity without coaching.'),('M4','Production-grade presentation','Consistent art, animation, acoustics and accessibility.','Approve actual gameplay reference shots, controller sessions and listening tests.'),('M5','Release readiness','Reliable builds, recovery, licensing and sustained hardware testing.','Pass the named device matrix, license audit, soak test and rollback drill.')]
# ID|milestone|priority|status|title|acceptance|next action|dependencies
ROWS='''MOVE-01|M0|P0|verified|Continuous acceleration and explicit braking|90 simulated seconds at full acceleration without energy-induced drops; coasting preserves speed; LT/B/Ctrl stops. This does not certify physical input latency.|Retest after every physics change.|
MOVE-02|M0|P0|implemented|Speed-consistent camera and reduced motion|Camera FOV and chase distance follow actual speed rather than whether RT is held. Reduced motion removes speed effects.|Run Homecoming acceptance, then request real-device feel approval.|MOVE-01
INPUT-01|M0|P0|verified|Correct camera axes and persistent options|Right looks right and up looks up. Axis inversion, sensitivity, audio sliders and B-to-return exist. Evidence uses standard-mapping emulation, not physical Xbox hardware.|Complete a Windows/browser plus real Xbox controller session.|
PERF-01|M0|P0|implemented|Local frame-time report|A bounded 600-frame window records p95/p99 interval, CPU submission p95, intervals over 50 ms and simulation/wall ratio. Pauses excluded; no automatic upload.|Capture results on actual target hardware.|
PERF-02|M0|P0|needs-playtest|Named desktop 60 fps gate|Proposed target: 1920x1080 on RTX 2060-class hardware, warmed 10-minute route, mean >=59 fps, p95 <=18 ms, p99 <=25 ms, fewer than 1 percent of intervals over 50 ms. Record CPU, GPU, browser, quality and power mode. These are project targets, not external certification requirements.|Run a real-machine benchmark and explicitly review the targets; software-rendered results cannot pass this gate.|PERF-01
PERF-03|M0|P0|partial|Streaming and stable frame pacing|No uncapped per-frame world construction. A 30-minute multi-district session must reach stable memory and geometry counts. Rendering must not silently run simulation in slow motion.|Profile chunk creation, GPU uploads, garbage collection and low-power 30 fps pacing.|PERF-01
SAVE-01|M0|P0|verified|Preserve the existing game and save identities|Original v1 slot and mission IDs remain. Old saves load; contracts, times and finishes round-trip; sibling game storage is not touched.|Test additive Homecoming fields and interrupted-write recovery.|
SAVE-02|M0|P0|planned|Recoverable save transactions|Maintain a last-known-good backup with schema migrations and clear recovery. Corrupt storage, quota failures and interrupted writes must not silently erase progress.|Implement transactional backup and import/export with controller-friendly errors.|SAVE-01
SLICE-01|M1|P0|implemented|Homecoming story journal and named neighbors|Five local contracts gain authored introductions and debriefs. Old completed contracts count; an unrelated active contract is not replaced without explicit consent.|Validate the chapter and measure actual duration. Fifteen minutes is a target, not a measured claim.|SAVE-01
SLICE-02|M1|P0|implemented|Common Ground changes with your work|An authored plaza includes Maya, cafe furniture and a pergola. Cleanup removes litter; repairs restore bulbs; photos fill decorative postcard panels; garden/workshop choice changes props. Changes survive reload.|Check all visual states in actual game captures and obtain art approval.|SLICE-01
SLICE-03|M1|P0|implemented|A physical homecoming finale|Return to Maya after all five projects. The 500-credit reward and finish unlock are awarded once; remote or repeated claims cannot duplicate rewards.|Test completion, reload and repeated claims.|SLICE-01 SLICE-02
ART-01|M1|P0|partial|Foreground courier quality|Approve consistent human scale, face, eyes, hands, clothing, backpack straps and grounded shoes. No visible intersections in standing, running, riding and jumping.|Replace primitive rig with an original or licensed skinned hero and authored animations.|
ART-02|M1|P0|partial|Bicycle and unicycle hero assets|Correct axles, pedals, grips and foot contacts; believable steering, suspension and braking. Approve turntables and riding captures at normal camera distance.|Build hero meshes, LODs and contact-aware animation.|ART-01
ART-03|M1|P0|partial|Human-scale architecture and materials|Approve one two-story house, cafe and apartment with believable doors, windows and floor heights. Materials, trim and shadows retain quality across presets.|Replace enlarged placeholders with measured authored building kits.|
PLAY-01|M1|P1|planned|One fully playable interior|A cafe/workshop needs an accessible entrance, usable counter, collision, a meaningful activity, and a reliable exit with controller, keyboard and touch.|Validate one interior before repeating it across the city.|ART-03 INPUT-01
SLICE-04|M1|P0|needs-playtest|Vertical-slice fun and presentation approval|At least three fresh-player sessions record confusion, time to first action, exploration and abandonment. The user explicitly approves or rejects the reference-quality street and character.|Record observations and actual captures rather than self-awarded quality grades.|SLICE-03 ART-01 ART-02 ART-03 PLAY-01
WORLD-01|M2|P1|partial|Road topology and readable navigation|All six sphere faces connect. Centerlines, sidewalks, signs and collisions agree. Seams, intersections and mission approaches work at speed.|Drive every seam and add road-following routes instead of compass-only navigation.|
WORLD-02|M2|P1|partial|Distinct coastal districts|Twenty-four names are not twenty-four distinct experiences. Each district needs a landmark, architecture, terrain or lighting identity, and activity mix.|Author a downtown, marina, neighborhood and industrial district before scaling further.|SLICE-04
WORLD-03|M2|P1|planned|Useful houses and public buildings|Every building family needs an appropriate encounter or activity; important buildings need interiors. Empty shells remain labeled scenery rather than advertised as interactive homes.|Create an activity registry, schedules, entrances and usable world markers.|PLAY-01 WORLD-02
WORLD-04|M2|P1|partial|Traffic that understands streets|Cars move continuously, but must eventually follow lanes, stop at signals, avoid one another and yield visibly without secretly braking the player.|Implement intersections, queueing, right of way and safe player interaction.|
WORLD-05|M2|P1|partial|Residents with purpose|Residents, joggers and cyclists exist; add destinations, idles, conversation and crossing behavior rather than only looping around scenery.|Author bounded schedules, contextual interactions and crowd reactions.|PERF-03
WORLD-06|M2|P2|planned|Parks, rooftops and alternate routes|Provide street-speed, low-risk sidewalk and stunt/rooftop routes through the slice, each with tested entrances, exits and recovery.|Prototype short interconnected routes, not isolated scenery.|SLICE-04 WORLD-01
DESIGN-01|M3|P1|partial|Depth rather than mission-count inflation|The 102 contracts are variants of six systems, not 102 authored stories. New content must add decisions, encounter variation and consequences.|Deepen one family, playtest it, then expand.|
DESIGN-02|M3|P1|partial|Connected authored campaign|Homecoming is the first optional arc. Later chapters need distinct characters, purposeful objectives, debriefs and world consequences.|Use first-arc feedback to outline two genuinely different follow-up arcs.|SLICE-04
DESIGN-03|M3|P1|partial|Fair progression and replay|Credits and cosmetics persist. Duplicate events cannot create repeated rewards. Speed and basic access never require a purchase.|Balance rewards, add milestone goals and test replay results.|
DESIGN-04|M3|P1|planned|Navigation that teaches without overwhelming|A fresh player finds a first task within 60 seconds, follows a road-safe route and distinguishes story, side jobs and free exploration.|Add local minimap, compact journal and optional route guidance; test with fresh players.|WORLD-01 SLICE-04
DESIGN-05|M3|P2|planned|Difficulty and assistance|Timing assistance, race recovery, readable scoring and no mandatory repeated-button strain. Assists preserve story access.|Add persistent steering, timing, objective and retry assists.|INPUT-01
AUDIO-01|M4|P0|verified|Independent levels and bounded score|One music transport; independent master, music, effects and ambience; quiet mix and mute; bounded voices. This verifies behavior, not soundtrack production quality.|Audit every future cue against mixer levels and density limits.|
AUDIO-02|M4|P1|partial|A polished score with quiet space|Original procedural music exists. It should develop across exploration, work and celebration without intrusive repetition or competing compositions.|Compose longer arrangements, improve instruments and review 20 minutes of listening.|AUDIO-01
AUDIO-03|M4|P1|partial|Spatial Foley and ambience|Distance and direction should match sources. Tires, motors and crowds must not mask essential cues; repetitive notification bursts must stay bounded.|Add source-based emitters, useful occlusion and measured mix headroom.|AUDIO-01 WORLD-05
AUDIO-04|M4|P1|planned|Dialogue and captions|Written dialogue is not voice acting. Any recorded speech needs captions, a separate voice level and no audio-only essential information.|Decide licensed voice production or text-only presentation; add captions and voice bus before speech.|DESIGN-02
ART-04|M4|P1|planned|Unified art bible and approved reference shots|Agree on palette, material response, scale and identity across buildings, hero, vehicles and nature. Compare actual gameplay, never concept images passed off as builds.|Create measured reference sheets and approved before/after captures.|SLICE-04
ART-05|M4|P1|partial|Stable lighting and reflections|No camera-driven sun rotation, blown highlights, flickering depth or shimmering shadows. Tone mapping and quality presets retain intended appearance.|Review contact shadows, distant visibility and temporal stability on target hardware.|PERF-02
ART-06|M4|P2|planned|Time of day and weather with purpose|Day/night and weather are optional future work, not shipped features. They must help mood or play without breaking readability or frame targets.|Prototype a constrained sunset variant after daytime quality is stable.|ART-05 PERF-02
ACCESS-01|M4|P0|partial|Controller-complete gameplay and menus|Every feature including errors, confirmations, story, checklist and settings must be reachable and dismissible without a mouse after browser audio unlock. No gameplay input behind dialogs.|Run physical Xbox tests including disconnect, reconnect and multiple pads.|INPUT-01
ACCESS-02|M4|P1|planned|Remapping and input alternatives|Support per-action keyboard/gamepad remapping, adjustable dead zones, hold/toggle alternatives and conflict-safe defaults. Essential actions need touch equivalents.|Build an input-action layer rather than more hard-coded mappings.|ACCESS-01
ACCESS-03|M4|P1|partial|Readable and comfortable presentation|Text scales without clipping; objectives are not color-only; speed effects can be reduced; long panels scroll by controller. Screen narration is not implemented.|Audit contrast, captions, text scaling, reduced motion and screen-reader access.|
QA-01|M5|P0|verified|Automated model and controller evidence|The previous release has 77 passing model tests and an emulated-controller browser journey. Retain actual results; failed or skipped tests are never reported as passed.|Run new Homecoming acceptance and retain evidence before publishing.|
QA-02|M5|P0|needs-playtest|Physical hardware matrix|Record Windows Chrome/Edge with Xbox USB and Bluetooth plus low-power and touch devices. Include sustained speed, menus, saves and audio.|Fill production/hardware-matrix.md with actual measured sessions.|PERF-02 ACCESS-01
QA-03|M5|P0|partial|Context loss and asset-failure recovery|Graphics loss pauses safely and recovers with saves retained. Missing art falls back explicitly. New plaza and audio must survive the same path.|Add injected context loss, storage failures and missing-texture tests.|
QA-04|M5|P0|planned|Extended soak and memory gate|A 30-minute multi-district session has no uncaught exceptions, runaway voices, increasing geometry counts or stuck inputs. Compare a second lap.|Automate route-driven soak and record a real-device review.|PERF-03 AUDIO-01
BUILD-01|M5|P0|verified|Publish real source, not an unmerged candidate|v0.7 is on master with a successful Pages deployment. Every next release preserves concurrent games, records a commit and checks live modules.|Apply this definition to v0.8 with a fresh release receipt.|
BUILD-02|M5|P0|planned|A repeatable release gate|Run model, browser, asset, visual and live checks before completion. Archive evidence, support reversible rollback and never force-push over sibling games.|Consolidate one-off workflows into a scoped release pipeline.|QA-01 QA-03
LEGAL-01|M5|P0|partial|Licensed and reproducible assets|The existing CC0 register retains sources and hashes. Every new model, texture, sound and voice needs provenance and redistribution rights.|Audit new assets, credits and reproduction for every milestone.|
SHIP-01|M5|P0|blocked|Evidence-based quality approval|Do not call the game AAA because a checklist exists or a counter is large. All P0 gates, critical defects, approved art/play and actual hardware results must be resolved.|Close prerequisite gates and obtain explicit user quality approval.|SLICE-04 PERF-02 SAVE-02 ACCESS-01 QA-02 QA-04 LEGAL-01 BUILD-02'''
old='https://github.com/v5ma/v5ma.github.io/actions/runs/34667786481'
evidence={'MOVE-01':['../tests/coastal.test.mjs',old],'INPUT-01':['../controller.mjs',old],'SAVE-01':['../tests/coastal.test.mjs',old],'AUDIO-01':['../coastal-audio.mjs',old],'QA-01':[old],'BUILD-01':['https://github.com/v5ma/v5ma.github.io/actions/runs/34668030978'],'MOVE-02':['../frame-health.mjs'],'PERF-01':['../frame-health.mjs'],'SLICE-01':['../homecoming.mjs'],'SLICE-02':['../homecoming-view.mjs'],'SLICE-03':['../homecoming.mjs'],'LEGAL-01':['../assets/street-art/asset-register.json']}
items=[]
for line in ROWS.splitlines():
 id,m,priority,status,title,acceptance,next,deps=line.split('|');owner='Art / animation' if id.startswith('ART') else 'Real-device QA / user' if status=='needs-playtest' else 'Design / engineering' if id.startswith(('SLICE','DESIGN','WORLD')) else 'Audio / engineering' if id.startswith('AUDIO') else 'Engineering / QA'
 items.append(dict(id=id,milestone=m,priority=priority,status=status,title=title,acceptance=acceptance,next=next,dependencies=deps.split(),evidence=evidence.get(id,[]),owner=owner,lastReviewed='2026-09-11'))
D=dict(schema=1,version='0.8.0',title='Neighborhood Missions: path to a production-quality title',reviewed='2026-09-11',currentMilestone='M1',qualityClaim='Stylized browser-game vertical slice. AAA-quality ambition, not AAA certification.',statusDefinitions={'verified':'A narrow acceptance criterion has recorded automated evidence; not human art approval or physical hardware certification.','implemented':'Code is integrated; specific acceptance or release evidence remains to be recorded.','partial':'A baseline exists, but the full production criterion is not met.','planned':'No complete implementation yet.','needs-playtest':'Requires real hardware or human evaluation; automated tests cannot substitute.','blocked':'Cannot pass until prerequisites and approvals are complete.'},milestones=[dict(id=i,title=t,exitCriterion=e,humanGate=h) for i,t,e,h in M],items=items,sources=[{'title':'WebGL best practices / Mozilla MDN','url':'https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices','use':'Batching, bounded resources, avoiding synchronous stalls and cleanup. Numerical frame targets here are our project targets, not MDN requirements.'},{'title':'Xbox Accessibility Guideline 105 / Microsoft','url':'https://learn.microsoft.com/en-us/gaming/accessibility/xbox-accessibility-guidelines/105','use':'Independent audio controls and essential cue audibility.'},{'title':'Making games accessible / Microsoft','url':'https://learn.microsoft.com/en-us/windows/uwp/gaming/accessibility-for-games','use':'Remapping, input alternatives and perceptual/cognitive accessibility.'}])
(P/'production/roadmap.json').write_text(json.dumps(D,indent=2)+'\n')
(P/'production/hardware-matrix.md').write_text('''# Real-device acceptance matrix

No physical device session has been signed off for Homecoming. Chromium/SwiftShader automation tests behavior, not the performance of the user's PC or a physical controller.

## Proposed desktop reference

Windows Chrome/Edge, 1920x1080, RTX 2060-class GPU and Xbox controller. This is a proposed target, not a claim about the user's current machine.

CPU/GPU and memory: Not recorded.
Browser and OS version: Not recorded.
Controller model, firmware and connection: Not recorded.
Quality and power mode: Not recorded.
Route and duration: Not recorded; target a warmed 10-minute ride and 30-minute soak.
Average fps, p95, p99, intervals over 50 ms and simulation/wall ratio: Not recorded.
Controller-only start, menus, sliders, repair, photo, journal, reset cancellation, disconnect/reconnect: Not recorded.
Audio overload, accessibility, approval, observed defects and date: Not recorded.

## Additional coverage

Low-power Windows integrated graphics: Untested.
Xbox Bluetooth and USB separately: Untested.
Android Chrome touch and gamepad: Untested.
iOS Safari touch: Untested.
macOS browser and controller: Untested.
Failure recovery on physical hardware: Untested.

## Recording results

Use Menu / Ride performance report / Show and copy the report. Share only information the tester agrees to share. No telemetry is uploaded automatically. Add measured sessions as production/evidence/hardware-YYYYMMDD-device.md. Failed, incomplete and skipped sessions remain recorded as such.
''')
print('Seeded',len(items),'production checklist items.')
