/* Actual Three.js geometry reproduces mixed normalized Uint16 RGBA and
 * absent-color primitives in the imported furniture and metal material. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';import {compatibleGeometry,batchStatic} from '../art-batch.mjs';
function geometry(color=true){const g=new T.BoxGeometry(1,1,1);if(color){const colors=new Uint16Array(g.attributes.position.count*4).fill(65535);colors[0]=32768;g.setAttribute('color',new T.Uint16BufferAttribute(colors,4,true));}return g;}
test('Normalized RGBA and absent colors become compatible without losing alpha',()=>{const source=geometry(),g=compatibleGeometry(source,new T.Matrix4());assert.equal(g.attributes.color.itemSize,4);assert.equal(g.attributes.color.normalized,false);assert.ok(g.attributes.color.array instanceof Float32Array);assert.ok(Math.abs(g.attributes.color.getX(0)-.50000763)<1e-6);assert.equal(g.attributes.color.getW(0),1);const noColor=compatibleGeometry(geometry(false),new T.Matrix4());assert.equal(noColor.attributes.color.itemSize,4);assert.equal(noColor.attributes.color.getW(0),1);assert.ok(source.attributes.color.array instanceof Uint16Array);});
test('Furniture and candle primitives sharing one material batch successfully',()=>{const g=new T.Group(),material=new T.MeshStandardMaterial({vertexColors:true}),a=new T.Mesh(geometry(),material),b=new T.Mesh(geometry(false),material);b.position.x=3;g.add(a,b);g.position.set(20,4,10);batchStatic(g);assert.equal(g.children.length,1);const mesh=g.children[0];mesh.geometry.computeBoundingBox();assert.equal(mesh.geometry.boundingBox.max.x,3.5);assert.equal(mesh.geometry.boundingBox.min.x,-.5);assert.equal(mesh.geometry.attributes.color.itemSize,4);assert.equal(mesh.geometry.index.count,72);assert.ok(mesh.geometry.attributes.position.count<72);});
test('Rejected ambiguous multi-material primitives cannot erase a source group',()=>{const g=new T.Group(),a=new T.Mesh(geometry(),[new T.MeshBasicMaterial()]);g.add(a);assert.throws(()=>batchStatic(g),/one material/);assert.equal(g.children[0],a);});
test('Indexing reduces repeated vertex transforms without changing rendered positions, normals, colors or UVs',()=>{const material=new T.MeshStandardMaterial({vertexColors:true}),group=new T.Group();for(let i=0;i<6;i++){const mesh=new T.Mesh(geometry(),material);mesh.position.x=i*2;group.add(mesh);}const before=[];group.updateMatrixWorld(true);for(const mesh of group.children){const g=compatibleGeometry(mesh.geometry,mesh.matrixWorld);before.push(g);}
 const expected={};for(const key of ['position','normal','uv','color'])expected[key]=before.flatMap(g=>[...g.attributes[key].array]);batchStatic(group);const result=group.children[0].geometry;assert.ok(result.index);const expanded=result.toNonIndexed();for(const key of Object.keys(expected)){const actual=[...expanded.attributes[key].array];assert.equal(actual.length,expected[key].length);assert.ok(actual.every((v,i)=>Math.abs(v-expected[key][i])<1e-6),key);}assert.ok(result.attributes.position.count<expanded.attributes.position.count*.8);});
