import {test} from 'node:test';import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';
import {createCameraOcclusion} from '../camera-occlusion.mjs';
import {createCameraSafety} from '../camera-safety.mjs';
function fixture(){const scene=new T.Scene(),source=new T.MeshStandardMaterial(),book=new T.Group(),mesh=new T.Mesh(new T.BoxGeometry(2,2,.6),source);book.name='test bookcase';book.userData.cameraOccluder=true;book.add(mesh);scene.add(book);return {scene,source,book,mesh,occlusion:createCameraOcclusion(scene)};}
test('Camera inside a real bookcase cuts away that object even without a surface ray hit',()=>{const f=fixture(),p={x:0,y:0,z:0};const r=f.occlusion.update(p,{x:0,y:0,z:.2},1/60);assert.equal(r.faded,1);assert.equal(f.mesh.material.opacity,.1);assert.equal(f.source.opacity,1);assert.notEqual(f.mesh.material,f.source);});
test('Only the obstructing shelf fades, not a neighbor sharing its source material',()=>{const f=fixture(),other=new T.Mesh(new T.BoxGeometry(),f.source);other.position.x=8;f.scene.add(other);f.occlusion.update({x:0,y:0,z:-2},{x:0,y:0,z:2},1/60);assert.equal(other.material.opacity,1);assert.equal(other.material.transparent,false);});
test('Clear views recover the original material without allocating per-frame fade copies',()=>{const f=fixture();f.occlusion.update({x:0,y:0,z:-2},{x:0,y:0,z:2},.1);const copy=f.mesh.material;for(let i=0;i<100;i++)f.occlusion.update({x:4,y:0,z:0},{x:6,y:0,z:0},.1);assert.equal(f.mesh.material,f.source);f.occlusion.update({x:0,y:0,z:-2},{x:0,y:0,z:2},.1);assert.equal(f.mesh.material,copy);});
test('Hidden replacement furniture does not trigger an invisible occlusion',()=>{const f=fixture();f.book.visible=false;assert.equal(f.occlusion.update({x:0,y:0,z:-2},{x:0,y:0,z:2},.1).faded,0);});
test('Later loaded art and quality-tier changes get private cutaway materials',()=>{const f=fixture();f.occlusion.update({x:4,y:0,z:0},{x:6,y:0,z:0},.1,false);const tier=new T.MeshBasicMaterial();f.mesh.material=tier;f.occlusion.update({x:0,y:0,z:0},{x:0,y:0,z:2},.1,true);assert.notEqual(f.mesh.material,tier);assert.equal(tier.transparent,false);assert.equal(tier.opacity,1);});
test('Walking across rooftop room footprints retains a continuous camera history',()=>{const c=createCameraSafety({colliders:[],rooms:[],doorPaths:[]},()=>0),a={x:0,y:17,z:0},b={x:0,y:18,z:-5};c.update(a,b,{level:3,roomId:'a',dt:.1});c.update(a,b,{level:3,roomId:null,dt:.1});assert.equal(c.inspect().transition,false);});
