/* Analytic camera fixtures are not physical-device or browser playthroughs. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {segmentBox,clipBoom,corridorFraction,createCameraSafety} from '../camera-safety.mjs';
import {makeWorld,heightAt,newState,saveData} from '../model.mjs';
const box={id:'thin wall',min:{x:-.05,y:0,z:-2},max:{x:.05,y:5,z:2}},a={x:2,y:2,z:0},b={x:-2,y:2,z:0};
test('Continuous trace catches a thin wall even when both endpoints are outside it',()=>{const r=clipBoom(a,b,[box]);assert.equal(r.obstacle,'thin wall');assert.ok(r.position.x>.27);assert.ok(segmentBox(a,b,box));});
test('Diagonal corners use radius clearance and return the first of multiple obstructions',()=>{const far={...box,id:'far',min:{x:-3,y:0,z:-4},max:{x:-2.9,y:5,z:4}};const r=clipBoom(a,{x:-5,y:2,z:1},[far,box]);assert.equal(r.obstacle,'thin wall');assert.ok(r.position.x>.27);});
test('Parallel and zero-length rays stay finite without manufacturing a hit',()=>{assert.equal(segmentBox({x:2,y:1,z:0},{x:2,y:4,z:0},box),null);assert.deepEqual(clipBoom(a,a,[box]).position,a);assert.equal(segmentBox({x:NaN,y:0,z:0},b,box),null);assert.throws(()=>clipBoom(a,{x:NaN,y:0,z:0},[]),TypeError);});
test('An obstacle below or above the boom does not act as an infinite wall',()=>{const r=clipBoom({...a,y:16},{...b,y:16},[box]);assert.equal(r.fraction,1);});
test('Passage unions allow connected corners but do not bridge an empty gap',()=>{const from={x:0,y:-8,z:0},to={x:8,y:-8,z:0};assert.equal(corridorFraction(from,to,[{x:2,z:0,hx:3,hz:2},{x:6,z:0,hx:3,hz:2}]),1);assert.ok(corridorFraction(from,to,[{x:0,z:0,hx:2,hz:2},{x:8,z:0,hx:2,hz:2}])<.25);});
const world=makeWorld();
test('Street camera cannot cross the actual workshop back wall',()=>{const c=createCameraSafety(world,heightAt),y=heightAt(-30,24),p=c.update({x:-30,y:y+1.45,z:24},{x:-36,y:y+3,z:24},{level:0,dt:1/60});assert.ok(p.x>-30.84);assert.equal(c.inspect().obstacle,'workshop-back');});
test('All 49 upper rooms, attics and cellars constrain the camera inside their own walls',()=>{const c=createCameraSafety(world,heightAt);for(const h of world.rooms)for(const level of[-1,1,2])for(const dx of[-1,1]){const ground=heightAt(h.x,h.z)+(level<0?-5:level*3.8);const p=c.update({x:h.x,y:ground+1.45,z:h.z},{x:h.x+dx*20,y:ground+6,z:h.z+20},{level,roomId:h.id,ground,dt:1/60,snap:true});assert.ok(Math.abs(p.x-h.x)<h.hx-.5,h.id);assert.ok(Math.abs(p.z-h.z)<h.hz-.5,h.id);assert.ok(p.y<ground+3.46);}});
test('Changing floors resets the camera history without interpolating through the intervening storey',()=>{const c=createCameraSafety(world,heightAt);c.update(a,b,{level:0,dt:.1});const ground=heightAt(-24.5,24)+7.6;const p=c.update({x:-24.5,y:ground+1.45,z:24},{x:-24.5,y:ground+3,z:20},{level:2,roomId:'workshop',ground,dt:1/60});assert.ok(p.y>ground+.4);assert.ok(c.inspect().transition);});
test('Rooftop camera is not clipped by invisible street house walls',()=>{const c=createCameraSafety(world,heightAt),y=heightAt(-30,24)+15;const r=c.update({x:-30,y:y+1.45,z:24},{x:-36,y:y+3,z:24},{level:3,dt:.1});assert.equal(r.x,-36);assert.equal(c.inspect().obstacle,null);});
test('Smoothing is re-clipped immediately when a wall moves between the camera and player',()=>{const w={colliders:[{id:'wall',x:0,z:0,hx:.05,hz:5}],rooms:[],doorPaths:[]},c=createCameraSafety(w,()=>0);c.update({x:-2,y:2,z:0},{x:-5,y:3,z:0},{level:0,dt:.1});const p=c.update({x:2,y:2,z:0},{x:5,y:3,z:0},{level:0,dt:1/60});assert.ok(p.x>.27);});
test('Camera eases outward after obstruction clears instead of snapping to full distance',()=>{const w={colliders:[{id:'wall',x:0,z:0,hx:.05,hz:1}],rooms:[],doorPaths:[]},c=createCameraSafety(w,()=>0);c.update(a,b,{level:0,dt:1/60});const p=c.update({...a,z:4},{...b,z:4},{level:0,dt:1/60});assert.ok(p.x>b.x);assert.ok(c.inspect().valid);});
test('Paused camera stays stable and scene solving leaves adventure data unchanged',()=>{const c=createCameraSafety(world,heightAt),s=newState(),before=JSON.stringify(saveData(s));const anchor={x:2,y:2,z:-6},desired={x:2,y:4,z:-12};const p=c.update(anchor,desired,{level:0,dt:.1});for(let i=0;i<50;i++)assert.deepEqual(c.update(anchor,desired,{level:0,dt:0}),p);assert.equal(JSON.stringify(saveData(s)),before);});
