/* Declared physical-state fixtures. Actual controller journey is separate. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeWorld,newState,step,saveData,readSave} from '../model.mjs';
import {attachFrontier,enterBadlands,leaveBadlands,frontierAction,frontierBlocked,CAMP,CONTRACTS} from '../frontier-core.mjs';
import {POOL,WATER_CONTROL,WATER_LENS,cisternState,poolFloor,poolBlocked,waterDepth,cisternOptions} from '../cistern-core.mjs';
const world=makeWorld(),at=(s,p)=>{s.x=p.x;s.z=p.z;s.speed=0;s.lift=0;};
const tick=(s,n=60,input={})=>{for(let i=0;i<n;i++)step(s,world,input,1/60);};
function field(){const s=attachFrontier(newState());s.mode='foot';at(s,{x:0,z:-17});enterBadlands(s);frontierAction(s,world,'accept:cistern');at(s,WATER_CONTROL);return s;}
function action(s,a){return frontierAction(s,world,'water:'+a);}
function drain(s){action(s,'read');for(let i=0;i<3;i++)action(s,'valve:'+i);assert.ok(action(s,'apply').ok);tick(s,420);}
test('Legacy frontier saves initialize a flooded, unstarted cistern without changing prior records',()=>{const s=field();const old=saveData(s);delete old.frontier.cistern;old.frontier.reported=['survey'];old.credits=45;const data=readSave(JSON.stringify(old),world),r=attachFrontier(newState(data),data.frontier);assert.equal(r.frontier.cistern.phase,0);assert.equal(r.frontier.cistern.surface,POOL.high);assert.equal(r.credits,45);assert.deepEqual(r.frontier.reported,['survey']);});
test('Malformed cistern state cannot introduce arbitrary water heights or phases',()=>{const c=cisternState({version:1,phase:99,mask:NaN,surface:Infinity});assert.equal(c.phase,0);assert.equal(c.surface,POOL.high);assert.equal(c.mask,1);assert.equal(cisternState({version:2,phase:5}).phase,0);assert.equal(cisternState({version:1,phase:2,mask:7}).mask,6);});
test('The new fourth contract leaves all three previous rewards unchanged',()=>{assert.deepEqual(CONTRACTS.filter(c=>c.id!=='cistern').map(c=>c.reward),[45,65,90]);assert.equal(CONTRACTS.find(c=>c.id==='cistern').reward,80);});
test('Pool ground, ramp and rim correspond to distinct physical positions',()=>{assert.equal(poolFloor(POOL.x,33),-2);assert.equal(poolFloor(POOL.x,23),-1);assert.equal(poolFloor(POOL.x,16),null);assert.ok(poolBlocked(POOL.x+POOL.hx,30));assert.ok(poolBlocked(POOL.x,40));assert.equal(poolBlocked(POOL.x,20,.33),false);});
test('Deep pool prevents walking through water before the sluices are solved',()=>{const s=field();assert.ok(frontierBlocked(POOL.x,33,.33,s));at(s,{x:POOL.x,z:19});tick(s,240,{throttle:1,moveYaw:0});assert.ok(s.z<22.2);assert.equal(s.health,100);});
test('Remote valve manipulation, riding and stale arbitrary actions are rejected',()=>{const s=field();s.x+=30;assert.equal(action(s,'read').ok,false);at(s,WATER_CONTROL);s.mode='bike';assert.equal(action(s,'read').ok,false);s.mode='foot';assert.equal(action(s,'valve:99').ok,false);assert.equal(action(s,'refill-now').ok,false);});
test('Correct drain pattern is explicit; wrong attempts consume nothing and do not skip the puzzle',()=>{const s=field();action(s,'read');const before=s.credits;assert.equal(action(s,'apply').ok,false);assert.equal(s.frontier.cistern.phase,1);assert.equal(s.credits,before);const opts=cisternOptions(s,'cistern');assert.equal(opts.length,4);assert.ok(opts[0].text.includes('INLET: OPEN'));});
test('Draining takes actual simulation time and a paused scene cannot change water level',()=>{const s=field();action(s,'read');for(let i=0;i<3;i++)action(s,'valve:'+i);action(s,'apply');const c=s.frontier.cistern;assert.equal(c.surface,POOL.high);tick(s,60);assert.ok(c.surface<POOL.high&&c.surface>POOL.low);const y=c.surface;for(let i=0;i<100;i++)cisternOptions(s,'cistern');assert.equal(c.surface,y);tick(s,420);assert.equal(c.surface,POOL.low);});
test('After draining the real ramp allows wading to the lens and shallow travel is slower',()=>{const s=field();drain(s);at(s,{x:POOL.x,z:19});tick(s,240,{throttle:1,moveYaw:0});assert.ok(s.z>27);assert.ok(s.speed<3);assert.ok(waterDepth(s)<.4);assert.equal(frontierBlocked(POOL.x,33,.33,s),false);});
test('Lens recovery requires the physical floor, completed drain, proximity and no airborne shortcut',()=>{const s=field();at(s,WATER_LENS);assert.equal(action(s,'recover').ok,false);at(s,WATER_CONTROL);drain(s);assert.equal(action(s,'recover').ok,false);at(s,WATER_LENS);s.lift=1;assert.equal(action(s,'recover').ok,false);s.lift=0;assert.ok(action(s,'recover').ok);assert.equal(s.frontier.cistern.phase,3);assert.equal(action(s,'recover').ok,false);});
test('Refilling cannot trap a player: it requires returning to the dry control platform',()=>{const s=field();drain(s);at(s,WATER_LENS);action(s,'recover');assert.equal(action(s,'valve:0').ok,false);assert.equal(action(s,'apply').ok,false);at(s,WATER_CONTROL);for(let i=0;i<3;i++)action(s,'valve:'+i);assert.ok(action(s,'apply').ok);assert.equal(s.frontier.cistern.phase,4);tick(s,420);assert.equal(s.frontier.cistern.phase,5);assert.equal(s.frontier.cistern.surface,POOL.high);});
test('Finished hydraulics pay only one physical return reward, without combat or new audio events',()=>{const s=field();drain(s);at(s,WATER_LENS);action(s,'recover');at(s,WATER_CONTROL);for(let i=0;i<3;i++)action(s,'valve:'+i);action(s,'apply');tick(s,420);assert.equal(frontierAction(s,world,'report:cistern').ok,false);at(s,CAMP);leaveBadlands(s);assert.ok(frontierAction(s,world,'report:cistern').ok);assert.equal(s.credits,80);assert.equal(s.life.xp,180);assert.equal(frontierAction(s,world,'report:cistern').ok,false);assert.equal(s.credits,80);assert.deepEqual(s.frontier.defeated,[]);assert.deepEqual(s.events,[]);});
test('Each hydraulic checkpoint round-trips through the original save and resumes from safe town',()=>{const s=field();for(const a of['read','valve:0','valve:1','valve:2','apply']){action(s,a);const data=readSave(JSON.stringify(saveData(s)),world),r=attachFrontier(newState(data),data.frontier);assert.equal(r.frontier.zone,'town');assert.equal(r.frontier.cistern.phase,s.frontier.cistern.phase);assert.equal(r.frontier.cistern.mask,s.frontier.cistern.mask);assert.equal(r.mission,0);assert.equal(r.credits,0);}});
