/* Explicit state fixtures; native keyboard/UI acceptance is separate. */
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeWorld,newState,step,saveData,readSave,recover} from '../model.mjs';
import {cycleState,saveCycle,cycleAction,cycleStep,cycleModifiers,bikeSpecification,ROAD_GATES,cancelRoadTest} from '../cycle-core.mjs';
import {nearbyChoices,guideEntries} from '../city-core.mjs';
const w=makeWorld(),tick=(s,i={},n=60)=>{for(let k=0;k<n;k++)step(s,w,i,1/60);};
function bench(){const s=newState();s.mode='foot';s.x=-22;s.z=212;s.speed=0;s.street.done=['fitting'];s.credits=160;return s;}
function pass(s,gate){const p=ROAD_GATES[gate];s.x=p.x;s.z=p.z;s.mode='bike';s.speed=3;cycleStep(s,{x:p.x,z:p.z-.2},1/60);}
function finish(s){for(let i=0;i<4;i++)pass(s,i);const p=ROAD_GATES[4];s.x=p.x;s.z=p.z;s.speed=.2;s.lift=0;cycleStep(s,{x:p.x,z:p.z-.02},1/60);}
test('Old saves keep quest/city/street progress and get stock cycle equipment',()=>{const old=saveData(newState());delete old.cycle;old.credits=105;old.city.rewarded=true;old.city.circuit=3;old.street.done=['fitting'];const s=newState(readSave(JSON.stringify(old),w));assert.equal(s.credits,105);assert.equal(s.city.circuit,3);assert.ok(s.street.done.includes('fitting'));assert.deepEqual(cycleModifiers(s),{accel:1,top:1,brake:1});});
test('Nearby and the guide expose a bench in the same smith room without removing other choices',()=>{const s=bench(),rows=nearbyChoices(s,w);assert.ok(rows.some(p=>p.kind==='work'&&p.id==='fitting')===false);assert.ok(rows.some(p=>p.kind==='service'&&p.id==='cycleworks'));assert.ok(guideEntries(s,w).some(p=>p.id==='cycleworks'));s.life.inside='workshop';assert.ok(!nearbyChoices(s,w).some(p=>p.id==='cycleworks'));});
test('Tuning requires completed fitting, foot state, proximity and the correct floor',()=>{const s=bench();for(const change of [{mode:'bike'},{x:0},{speed:3}]){const t={...s,...change};assert.equal(cycleAction(t,w,'gear:sprint').ok,false);}s.life.inside='workshop';assert.equal(cycleAction(s,w,'gear:sprint').ok,false);s.life.inside=null;s.street.done=[];assert.equal(cycleAction(s,w,'gear:sprint').ok,false);});
test('Purchases charge once, swapping owned parts is free, and unknown actions do nothing',()=>{const s=bench();assert.ok(cycleAction(s,w,'gear:sprint').ok);assert.equal(s.credits,130);assert.ok(cycleAction(s,w,'gear:stock').ok);assert.ok(cycleAction(s,w,'gear:sprint').ok);assert.equal(s.credits,130);const before=JSON.stringify(saveData(s));assert.equal(cycleAction(s,w,'__proto__:stock').ok,false);assert.equal(cycleAction(s,w,'gear:sprint:extra').ok,false);assert.equal(JSON.stringify(saveData(s)),before);s.credits=0;assert.equal(cycleAction(s,w,'brake:lever').ok,false);assert.equal(s.cycle.brake,'stock');});
test('Sprint and cruise changes are real tradeoffs, not hidden across-the-board upgrades',()=>{const a=newState(),b=newState(),c=newState();b.cycle.gear='sprint';c.cycle.gear='cruise';const sp=bikeSpecification(a),bs=bikeSpecification(b),cs=bikeSpecification(c);assert.ok(bs.accel>sp.accel&&bs.top<sp.top);assert.ok(cs.accel<sp.accel&&cs.top>sp.top);for(const s of[a,b,c])tick(s,{throttle:1},60);assert.ok(b.speed>a.speed&&a.speed>c.speed);});
test('The improved dedicated brake slows the actual bicycle more strongly',()=>{const a=newState(),b=newState();a.speed=b.speed=9;a.x=b.x=0;a.z=b.z=270;b.cycle.brake='lever';for(const s of[a,b])tick(s,{brake:true},20);assert.ok(b.speed<a.speed*.6);assert.ok(b.distance<a.distance);});
test('Carriage motion remains identical under bicycle gearing and brake changes',()=>{const a=newState(),b=newState();for(const s of[a,b]){s.mode='car';s.x=0;s.z=270;}b.cycle.gear='cruise';b.cycle.brake='lever';for(const input of[{throttle:1},{throttle:1,steer:.2},{brake:true}]){tick(a,input,20);tick(b,input,20);for(const k of['x','z','yaw','speed','health'])assert.equal(a[k],b[k],k);}});
test('All three bicycle variants retain their capacity identity while gearing scales motion',()=>{const s=bench();for(const bike of['standard','courier','cargo']){s.life.bike=bike;s.cycle.gear='stock';const base=bikeSpecification(s);s.cycle.gear='sprint';const tuned=bikeSpecification(s);assert.equal(tuned.top,base.top*.88);assert.equal(tuned.accel,base.accel*1.25);assert.equal(s.life.bike,bike);}});
test('Road tests only start at the bench and cannot manufacture an instant report',()=>{const s=bench();assert.ok(cycleAction(s,w,'start').ok);assert.equal(s.cycle.active.gate,0);assert.equal(cycleAction(s,w,'report').ok,false);assert.equal(cycleAction(s,w,'finish:river').ok,false);});
test('Ordered swept checkpoint movement is necessary and rejects foot, carriage, jumps in position and skipping',()=>{const s=bench();cycleAction(s,w,'start');s.mode='car';s.x=0;s.z=220;s.speed=3;cycleStep(s,{x:0,z:219.8},1/60);assert.equal(s.cycle.active.gate,0);s.mode='bike';cycleStep(s,{x:0,z:100},1/60);assert.equal(s.cycle.active.gate,0);s.z=259;s.speed=0;cycleStep(s,{x:0,z:258.9},1/60);assert.equal(s.cycle.active.gate,0);pass(s,0);assert.equal(s.cycle.active.gate,1);pass(s,2);assert.equal(s.cycle.active.gate,1);});
test('Stopping ring checks speed and grounded contact before preserving the result',()=>{const s=bench();cycleAction(s,w,'start');for(let i=0;i<4;i++)pass(s,i);s.x=0;s.z=259;s.speed=9;cycleStep(s,{x:0,z:258.9},1/60);assert.equal(s.cycle.pending,null);s.speed=0;s.lift=1;cycleStep(s,{x:0,z:259},1/60);assert.equal(s.cycle.pending,null);s.lift=0;cycleStep(s,{x:0,z:259},1/60);assert.ok(s.cycle.pending);assert.equal(s.cycle.active,null);});
test('Rewards require an actual return report and pay once; repeat practice stores a best time',()=>{const s=bench();cycleAction(s,w,'start');finish(s);assert.equal(s.credits,160);assert.equal(cycleAction(s,w,'report').ok,false);s.x=-22;s.z=212;s.mode='foot';const xp=s.life.xp;assert.ok(cycleAction(s,w,'report').ok);assert.equal(s.credits,185);assert.equal(s.life.xp,xp+40);assert.ok(cycleAction(s,w,'start').ok);finish(s);s.x=-22;s.z=212;s.mode='foot';cycleAction(s,w,'report');assert.equal(s.credits,185);assert.equal(s.life.xp,xp+40);assert.ok(s.cycle.best!==null);});
test('Reload preserves purchases, pending finished results and paid status, never an in-progress race',()=>{const s=bench();cycleAction(s,w,'finish:river');cycleAction(s,w,'start');pass(s,0);let t=newState(readSave(JSON.stringify(saveData(s)),w));assert.equal(t.cycle.active,null);assert.equal(t.cycle.finish,'river');for(let i=1;i<4;i++)pass(s,i);s.x=0;s.z=259;s.speed=0;cycleStep(s,{x:0,z:259},1/60);t=newState(readSave(JSON.stringify(saveData(s)),w));assert.deepEqual(t.cycle.pending,s.cycle.pending);assert.equal(t.cycle.rewarded,false);});
test('Cancellation and recovery retain earlier missions and do not award or charge currency',()=>{const s=bench();s.completed=true;s.life.quests.ink=3;cycleAction(s,w,'start');assert.ok(cancelRoadTest(s));assert.equal(s.credits,160);cycleAction(s,w,'start');recover(s);assert.equal(s.cycle.active,null);assert.equal(s.completed,true);assert.equal(s.life.quests.ink,3);assert.equal(s.credits,160);});
test('Malformed new data cannot equip unowned parts or inject arbitrary members',()=>{const c=cycleState({version:1,gear:'cruise',finish:'<script>',best:Infinity,owned:{gear:['__proto__'],brake:null,finish:['river']},active:{gate:999},pending:{seconds:-2}});assert.equal(c.gear,'stock');assert.equal(c.finish,'terracotta');assert.equal(c.best,null);assert.equal(c.active,null);assert.equal(c.pending,null);assert.deepEqual(c.owned.gear,['stock']);assert.equal(saveCycle(c).version,1);});
