/* Model fixtures, not browser playthroughs. Coordinates below deliberately
 * exercise authorization, all rooms and the network graph in isolation. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeWorld,newState,saveData,readSave,blocked,step,attack,enterExit,recover} from '../model.mjs';
import {roomAt,targets,use} from '../life-core.mjs';
import {freshDoors,doorLevel,doorElevation,doorSites,nearbyDoors,useDoor,doorOptions,networkContains,doorsBlocked,doorsStep,doorTarget,trackDoor,dodgeDoor} from '../doors-core.mjs';
import {deadzone,buttonEdges} from '../gamepad.mjs';
const w=makeWorld();const foot=()=>{const s=newState();s.mode='foot';s.life.flags.garden=true;return s;};
function at(s,h,level,p){s.mode='foot';s.speed=0;s.life.inside=null;s.doors.level=level;s.doors.room=level===0||level===3||level===-2?null:h.id;s.x=p.x;s.z=p.z;}
function perform(s,h,level,p,id,action='use'){at(s,h,level,p);const result=useDoor(s,w,id,action);assert.ok(result.ok,id+' '+action+': '+result.text);return result;}
function tick(s,n=60,input={}){for(let i=0;i<n;i++)step(s,w,input,1/60);}
test('All 49 retained house footprints have open thresholds, solid backs and a house commission',()=>{assert.equal(w.houses.length,49);assert.equal(w.rooms.length,49);assert.equal(w.doorHomes.length,49);const s=foot();for(const h of w.doorHomes){assert.ok(!blocked(h.door.x,h.door.z,.33,w,s),h.id);assert.ok(blocked(h.x+h.side*(h.hx-.2),h.z,.33,w,s),h.id+' back');at(s,h,0,h.desk);assert.ok(nearbyDoors(s,w).some(p=>p.action==='home'),h.id+' desk');}});
test('Every house has physically reachable up/down interactions on four floors',()=>{const s=foot();for(const h of w.doorHomes){for(const level of[-1,0,1,2]){at(s,h,level,h.upperStair);if(level>=0){assert.ok(!blocked(s.x,s.z,.33,w,s),h.id+' up');assert.ok(doorSites(s,w).some(p=>p.action==='up'),h.id+' up site');}at(s,h,level,h.stairs);assert.ok(!blocked(s.x,s.z,.33,w,s),h.id+' down');if(level>0)assert.ok(doorSites(s,w).some(p=>p.action==='down'));}}});
test('Every upstairs stair/hatch transition lands inside its walkable destination and keeps parked rides',()=>{const s=foot(),vehicles=JSON.stringify(s.vehicle);for(const h of w.doorHomes){for(const level of[0,1,2]){perform(s,h,level,h.upperStair,'up:'+h.id);assert.equal(doorLevel(s),level+1);assert.ok(!blocked(s.x,s.z,.33,w,s),h.id+' arrival');}perform(s,h,3,h.upperStair,'roofexit:'+h.id);assert.equal(doorLevel(s),2);for(const level of[2,1]){perform(s,h,level,h.stairs,'down:'+h.id);assert.equal(doorLevel(s),level-1);}if(!h.cellar){perform(s,h,0,h.stairs,'down:'+h.id);assert.equal(doorLevel(s),-1);perform(s,h,-1,h.hatch,'tunnel:'+h.id);assert.equal(doorLevel(s),-2);perform(s,h,-2,h.hatch,'cellexit:'+h.id);assert.equal(doorLevel(s),-1);perform(s,h,-1,h.stairs,'up:'+h.id);assert.equal(doorLevel(s),0);}}assert.equal(JSON.stringify(s.vehicle),vehicles);});
test('Ground, upper, attic and network actions cannot be invoked from a different floor or remotely',()=>{const s=foot(),h=w.doorHomes[0];at(s,h,1,h.desk);assert.equal(useDoor(s,w,'desk:'+h.id,'accept').ok,false);at(s,h,0,{x:0,z:0});assert.equal(useDoor(s,w,'desk:'+h.id,'accept').ok,false);at(s,h,1,h.station);assert.equal(use(s,w,'leonardo','start:ink').ok,false);assert.equal(targets(s,w).length,0);assert.equal(enterExit(s,w),false);});
test('All eight household craft patterns complete through correct floors and pay exactly once',()=>{const s=foot();for(const h of w.doorHomes){perform(s,h,0,h.desk,'desk:'+h.id,'accept');const before=s.credits;at(s,h,1,h.station);const wrong=((h.index%8)%3+1)%3;assert.equal(useDoor(s,w,'work:'+h.id,'choice:'+wrong).ok,false);assert.equal(s.doors.homes[h.id],1);perform(s,h,1,h.station,'work:'+h.id,'choice:'+((h.index%8)%3));s.doors.defeated.push(...w.doorEnemies.filter(e=>e.room===h.id).map(e=>e.id));perform(s,h,2,h.station,'work:'+h.id,'finish');perform(s,h,0,h.desk,'desk:'+h.id,'report');assert.equal(s.credits,before+25);assert.equal(useDoor(s,w,'desk:'+h.id,'report').ok,false);}assert.equal(Object.values(s.doors.homes).filter(n=>n===4).length,49);});
test('House rest is reusable but cooldown-bound and never awards money',()=>{const s=foot(),h=w.doorHomes[0];s.doors.homes[h.id]=4;at(s,h,0,h.desk);s.health=1;assert.ok(useDoor(s,w,'desk:'+h.id,'rest').ok);assert.equal(s.health,100);assert.equal(useDoor(s,w,'desk:'+h.id,'rest').ok,false);assert.equal(s.credits,0);});
test('Connected route graph reaches every house; geometry includes each complete row and column',()=>{for(const h of w.doorHomes){assert.ok(networkContains(w,h.x,h.z));assert.ok(networkContains(w,h.upperStair.x,h.upperStair.z));}for(const p of w.doorPaths){for(let k=0;k<=20;k++){const x=p.x+(p.hx>p.hz?(k/20-.5)*2*(p.hx-.5):0),z=p.z+(p.hz>=p.hx?(k/20-.5)*2*(p.hz-.5):0);assert.ok(networkContains(w,x,z),JSON.stringify({p,x,z}));}}});
test('Network outside edges block movement and both layers respect original northern gate',()=>{const s=foot();s.life.flags.garden=false;for(const level of[3,-2]){at(s,w.doorHomes[0],level,{x:-24.5,z:405});assert.ok(doorsBlocked(s,w,-24.5,405,.33));assert.ok(doorsBlocked(s,w,147,250,.33));s.life.flags.garden=true;assert.equal(doorsBlocked(s,w,-24.5,405,.33),false);s.life.flags.garden=false;}assert.equal(doorElevation({...s,doors:{level:3}}),15);});
test('Undercity cannot bypass the locked original inn cellar',()=>{const s=foot(),h=w.doorHomes.find(h=>h.id==='inn');at(s,h,-2,h.hatch);assert.equal(useDoor(s,w,'cellexit:inn','use').ok,false);assert.equal(doorLevel(s),-2);s.life.quests.cat=3;assert.ok(useDoor(s,w,'cellexit:inn','use').ok);assert.equal(s.life.inside,'inn');});
test('All six adventures enforce prerequisite stages and complete with one-time physical report rewards',()=>{const s=foot();for(const q of w.doorAdventures){const before=s.credits;for(const p of q.stages){const h=w.doorHomes.find(h=>h.id===p.room)||w.doorHomes[0];at(s,h,p.level,p);if(p.wins){assert.equal(useDoor(s,w,'adventure:'+q.id,'use').ok,false);s.doors.defeated=w.doorEnemies.slice(0,p.wins).map(e=>e.id);}if(p.homes){assert.equal(useDoor(s,w,'adventure:'+q.id,'use').ok,false);for(const h of w.doorHomes.slice(0,p.homes))s.doors.homes[h.id]=4;}assert.ok(useDoor(s,w,'adventure:'+q.id,'use').ok);}assert.equal(s.credits,before+q.florins);assert.equal(useDoor(s,w,'adventure:'+q.id,'use').ok,false);}});
test('Tracking chooses an intermediate stair or doorway and does not teleport or reward',()=>{const s=foot(),h=w.doorHomes[0];s.doors.homes[h.id]=1;at(s,h,0,h.desk);const before={x:s.x,z:s.z,credits:s.credits};assert.ok(trackDoor(s,w,'home',h.id));const t=doorTarget(s,w);assert.equal(t.x,h.upperStair.x);assert.deepEqual({x:s.x,z:s.z,credits:s.credits},before);assert.equal(trackDoor(s,w,'home','unknown'),false);});
test('Humanoid rivals patrol/chase only on their own layer, with telegraphed braceable strikes',()=>{const s=foot();doorsStep(s,w,.01);assert.equal(s.doors.enemies.length,18);const e=s.doors.enemies[0];at(s,w.doorHomes[0],e.level,{x:e.x,z:e.z+2});const health=s.health;doorsStep(s,w,.01);assert.equal(e.phase,'windup');assert.equal(s.health,health);s.guarding=true;for(let i=0;i<60;i++)doorsStep(s,w,1/60);assert.equal(s.health,health-2);assert.equal(e.phase,'recover');});
test('Actual staff attacks defeat an in-range rival once and keep original folio state separate',()=>{const s=foot();doorsStep(s,w,.01);const e=s.doors.enemies[0];at(s,w.doorHomes[0],e.level,{x:e.x,z:e.z+2});const before=s.credits;for(let i=0;i<4;i++){s.attackCD=0;attack(s,w);}assert.equal(e.hp,0);assert.ok(s.doors.defeated.includes(e.id));assert.equal(s.credits,before+12);assert.equal(s.defeated,false);s.attackCD=0;attack(s,w);assert.equal(s.credits,before+12);});
test('Dodge moves through collision-checked simulation, has invulnerability and cannot spam',()=>{const s=foot(),h=w.doorHomes[0];at(s,h,1,{x:h.x,z:h.z});const z=s.z;assert.ok(dodgeDoor(s));assert.equal(dodgeDoor(s),false);tick(s,8);assert.ok(s.z>z+.5);assert.ok(s.inv>0);});
test('Old save survives additive fields; full new progress fits bounded persistence without indoor respawn',()=>{const s=foot();s.credits=987;s.deliveries.add('mail-0');s.life.quests.ink=3;s.cycle.finish='brass';for(const h of w.doorHomes)s.doors.homes[h.id]=4;for(const q of w.doorAdventures)s.doors.adventures[q.id]=q.stages.length;s.doors.defeated=w.doorEnemies.map(e=>e.id);s.doors.level=2;s.doors.room='workshop';const raw=JSON.stringify(saveData(s));assert.ok(raw.length<32768);const r=newState(readSave(raw,w));assert.equal(r.credits,987);assert.equal(r.life.quests.ink,3);assert.equal(Object.keys(r.doors.homes).length,49);assert.equal(r.doors.defeated.length,18);assert.equal(r.doors.level,0);assert.equal(r.x,2);const old=saveData(s);delete old.doors;const older=newState(readSave(JSON.stringify(old),w));assert.equal(older.credits,987);assert.deepEqual(older.doors.homes,{});recover(r);assert.equal(r.doors.level,0);assert.equal(Object.keys(r.doors.homes).length,49);});
test('Malformed expansion fields, repeated IDs and invented commands are bounded',()=>{const d=freshDoors({version:1,homes:{workshop:-1,bogus:4},adventures:{survey:90},defeated:['guild-rival-0','guild-rival-0',null],tracked:{kind:'teleport',id:'workshop'},level:3});assert.deepEqual(d.homes,{});assert.deepEqual(d.adventures,{});assert.deepEqual(d.defeated,['guild-rival-0']);assert.equal(d.tracked,null);assert.equal(d.level,0);});
test('Controller deadzone and edge handling avoid drift, repeat activation and invalid axes',()=>{assert.equal(deadzone(.1),0);assert.equal(deadzone(NaN),0);assert.equal(deadzone(-1),-1);assert.equal(deadzone(1),1);assert.ok(deadzone(.6)>0);assert.deepEqual(buttonEdges([false,true,false],[true,true,false]),[true,false,false]);});
