import {test} from 'node:test';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';
import {createCampaignState,requestedCampaign} from '../campaign-entry.mjs';import {newState,saveData,readSave,makeWorld} from '../model.mjs';
import {deskPreferences,deskPlacement,createFieldDesk} from '../xr-field-desk.mjs';import {beginXRPass,restoreXRPass} from '../xr-frame-pass.mjs';import {centeredWorldMatrix} from '../world-portal.mjs';
const world=makeWorld();
test('Normal and old legacy URLs enter the full Vinci adventure, never the Quarter prototype',()=>{for(const q of ['', '?xr=old','?district=legacy']){const s=createCampaignState(null,q);assert.equal(s.quarter.active,false);assert.equal(s.mode,'bike');assert.equal(s.x,2);assert.equal(requestedCampaign(q),'vinci');}});
test('Quarter archive is deliberately selected and retains its actual scene/recovery',()=>{const s=createCampaignState(null,'?district=quarter');assert.equal(s.quarter.active,true);assert.equal(s.mode,'foot');assert.equal(s.x,-20);});
test('Main entry does not destroy an existing Quarter save, observations or paid rewards',()=>{const original=createCampaignState(null,'?district=quarter');original.quarter.parcel=original.quarter.reported=original.quarter.archOpen=true;original.quarter.delivery=3;original.credits=75;original.life.xp=160;const raw=readSave(JSON.stringify(saveData(original)),world),before=JSON.stringify(raw),main=createCampaignState(raw);assert.equal(main.quarter.active,false);assert.equal(main.quarter.delivery,3);assert.equal(main.credits,75);assert.equal(main.life.xp,160);assert.equal(JSON.stringify(raw),before);const restored=createCampaignState(readSave(JSON.stringify(saveData(main)),world),'?district=quarter');assert.equal(restored.quarter.reported,true);assert.equal(restored.quarter.archOpen,true);assert.equal(restored.credits,75);assert.equal(restored.quarter.delivery,3);});
test('Old campaign accomplishment IDs and the original outer save version round-trip unchanged',()=>{const s=newState();s.deliveries.add('mail-0');s.credits=129;s.relay=true;const raw=readSave(JSON.stringify(saveData(s)),world),main=createCampaignState(raw);assert.equal(saveData(main).version,2);assert.deepEqual([...main.deliveries],['mail-0']);assert.equal(main.credits,129);assert.equal(main.relay,true);});
test('Desk settings are bounded, malformed storage is safe and no room position is stored',()=>{const v=deskPreferences({height:9,distance:NaN,scale:Infinity,status:'head',x:100,yaw:1});assert.deepEqual(Object.keys(v),['height','distance','scale','status']);assert.equal(v.height,1.6);assert.equal(v.distance,1.3);assert.equal(v.scale,.74);assert.equal(v.status,'wrist');});
test('Desk placement is upright despite tracked pitch and roll and supports local-floor fallback',()=>{const q=new T.Quaternion().setFromEuler(new T.Euler(.4,.5,.3,'YXZ')),pose={transform:{position:{x:3,y:1.2,z:2},orientation:q}},p=deskPlacement(pose,deskPreferences(),'local');assert.ok(Math.abs(p.y-.68)<1e-9);assert.ok(Math.abs(p.yaw-.5)<1e-9);assert.equal(p.floor,-.40000000000000013);});
test('Spatial rendering does not bind the theatre texture or assume a null compositor target',()=>{const target={isXRRenderTarget:true},theatre={},calls=[],r={xr:{enabled:true},getRenderTarget:()=>target,getViewport:v=>v.set(0,0,1280,800),getScissor:v=>v.set(0,0,1280,800),getScissorTest:()=>false,setRenderTarget:v=>calls.push(v),setViewport(){},setScissor(){},setScissorTest(){}};const state=beginXRPass(r,theatre,true);assert.equal(r.xr.enabled,false);assert.equal(state.target,target);restoreXRPass(r,state);assert.equal(r.xr.enabled,true);assert.deepEqual(calls,[]);});
test('Theatre rendering restores the exact opaque XR target rather than the browser canvas',()=>{const target={isXRRenderTarget:true},theatre={},calls=[];let current=target;const r={xr:{enabled:true},getRenderTarget:()=>current,getViewport:v=>v.set(0,0,1280,800),getScissor:v=>v.set(0,0,1280,800),getScissorTest:()=>false,setRenderTarget:v=>{calls.push(v);current=v;},setViewport(){},setScissor(){},setScissorTest(){}};restoreXRPass(r,beginXRPass(r,theatre,false));assert.deepEqual(calls,[theatre,target]);});
test('Horizontal world rotation keeps world up stable at every heading and actor elevation',()=>{for(const yaw of [0,.3,1,3,-2]){const a={x:20,y:3.2,z:77},m=centeredWorldMatrix(a,.08,yaw,0),up=new T.Vector3(0,1,0).transformDirection(m);assert.ok(up.distanceTo(new T.Vector3(0,1,0))<1e-12);assert.ok(new T.Vector3(a.x,a.y,a.z).applyMatrix4(m).length()<1e-12);}});
test('Nested desk pages keep one stationary placement, adjustable controls never move game state',()=>{const old=globalThis.document,storage=globalThis.localStorage;const context=new Proxy({},{get:()=>()=>{}});globalThis.document={createElement:()=>({getContext:()=>context}),getElementById:()=>null};globalThis.localStorage={getItem:()=>null,setItem(){}};try{const scene=new T.Scene(),stage=new T.Group();scene.add(stage);const panel=new T.Mesh(new T.PlaneGeometry(1.1,1.65),new T.MeshBasicMaterial());stage.add(panel);const s=createCampaignState(),before=JSON.stringify(saveData(s)),desk=createFieldDesk({panel,stage,getState:()=>s,back(){}}),pose={transform:{position:{x:0,y:1.6,z:0},orientation:new T.Quaternion()}};desk.update(true,{},true,pose);const original=desk.inspect();pose.transform.position.x=.2;desk.update(true,{nested:true},true,pose);assert.deepEqual(desk.inspect().matrix,original.matrix);assert.equal(desk.inspect().placements,1);assert.ok(desk.modify('raise'));assert.ok(Math.abs(desk.inspect().preferences.height-1.18)<1e-12);assert.equal(JSON.stringify(saveData(s)),before);desk.update(true,null,false,pose);assert.equal(desk.inspect().visible,false);desk.update(false,null,false,null);assert.equal(panel.parent,stage);}finally{globalThis.document=old;if(storage===undefined)delete globalThis.localStorage;else globalThis.localStorage=storage;}});

test('Enlarging and lowering cannot bury the desk controls below the reference floor',()=>{for(const height of[-9,.7,1,1.6,Infinity])for(const scale of[.6,.74,.96,9]){const p=deskPreferences({height,scale});assert.ok(p.height-p.scale*1.364>=.06);assert.ok(p.height<=1.6);}});
