import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeWorld,newState,saveData,readSave,step,attack} from '../model.mjs';
import {chooseTool,fireTool,aimTarget,validTargets,resonanceInput,resonanceStep} from '../resonance-core.mjs';
import {cast} from '../life-core.mjs';
import {doorsStep} from '../doors-core.mjs';
import {CONTRACTS,MONSTERS,FRONTIER_SITES,TRAIL_NODES,TRAIL_EDGES,TOWN_GATE,CAMP,BADLANDS,FRONTIER_SOLIDS,frontierState,enterBadlands,leaveBadlands,frontierAction,frontierBlocked,frontierSight,frontierTarget,targetFrontier,nearbyFrontier,contractComplete,strikeFrontier,stepFrontier,useDressing} from '../frontier-core.mjs';
const w=makeWorld(),actions={attack,throwPaper:()=>false,cast};
const foot=()=>{const s=newState();s.mode='foot';return s;};
function atGate(s){s.mode='foot';s.x=TOWN_GATE.x;s.z=TOWN_GATE.z;s.speed=0;s.doors.level=0;s.doors.room=null;s.life.inside=null;}
function bad(){const s=foot();atGate(s);assert.ok(enterBadlands(s).ok);return s;}
function tickFrontier(s,seconds,input={}){for(let i=0;i<Math.ceil(seconds*60);i++)step(s,w,input,1/60);}

test('Old saves add a bounded town-region record without changing earlier progress',()=>{const s=newState();s.credits=432;s.life.quests.ink=2;s.doors.homes.workshop=3;const old=saveData(s);delete old.frontier;const r=newState(readSave(JSON.stringify(old),w));assert.equal(r.frontier.zone,'town');assert.equal(r.credits,432);assert.equal(r.life.quests.ink,2);assert.equal(r.doors.homes.workshop,3);assert.equal(r.frontier.defeated.length,0);});
test('Malformed frontier records cannot inject contracts, monsters or unbounded cargo',()=>{const f=frontierState({version:1,accepted:['fake','survey','survey'],reported:['bad'],visited:['ridge','fake'],defeated:['hollow-scout','player'],cargo:{ore:99999,resin:-1},store:{ore:Infinity,resin:10000},dressings:99,selected:'https://bad'});assert.deepEqual(f.accepted,['survey']);assert.deepEqual(f.visited,['ridge']);assert.deepEqual(f.defeated,['hollow-scout']);assert.equal(f.cargo.ore,0);assert.equal(f.store.resin,0);assert.equal(f.dressings,2);assert.equal(f.selected,'ridge');assert.equal(f.zone,'town');});
test('The first badlands is one connected three-loop trail network with bounded ruins',()=>{const adj=TRAIL_NODES.map(()=>[]);for(const [a,b]of TRAIL_EDGES){adj[a].push(b);adj[b].push(a);}const seen=new Set([0]),q=[0];while(q.length){const n=q.shift();for(const x of adj[n])if(!seen.has(x)){seen.add(x);q.push(x);}}assert.equal(seen.size,TRAIL_NODES.length);assert.ok(TRAIL_EDGES.length-TRAIL_NODES.length+1>=3);for(const [x,z]of TRAIL_NODES)assert.equal(frontierBlocked(x,z,.2),false);for(const b of FRONTIER_SOLIDS)assert.equal(frontierBlocked(b.x,b.z,.33),true);assert.equal(frontierBlocked(BADLANDS.minX-1,80),true);});
test('Entering Cinder Hollow requires the real safe-town gate, on foot, while stopped',()=>{const s=foot();assert.equal(enterBadlands(s).ok,false);atGate(s);s.mode='bike';assert.equal(enterBadlands(s).ok,false);s.mode='foot';s.speed=2;assert.equal(enterBadlands(s).ok,false);s.speed=0;s.cycle.active={};assert.equal(enterBadlands(s).ok,false);s.cycle.active=null;const before={credits:s.credits,quests:JSON.stringify(s.life.quests)};assert.ok(enterBadlands(s).ok);assert.equal(s.frontier.zone,'badlands');assert.equal(s.frontier.enemies.length,7);assert.deepEqual({credits:s.credits,quests:JSON.stringify(s.life.quests)},before);assert.ok(Math.hypot(s.x-CAMP.x,s.z-CAMP.z)<.1);});
test('Vinci is authoritative safe town: staff, sling and old rivals cannot damage anyone',()=>{const s=foot();s.x=w.bandit.x;s.z=w.bandit.z+2;const hp=s.banditHP;assert.equal(attack(s,w),false);assert.equal(s.banditHP,hp);chooseTool(s,'sling');assert.equal(fireTool(s,w,actions),false);assert.equal(validTargets(s,w).length,0);const health=s.health;s.doors.enemies=[];doorsStep(s,w,.01);const e=s.doors.enemies[0];s.doors.level=e.level;s.doors.room=e.room;s.x=e.x;s.z=e.z+2;for(let i=0;i<120;i++)doorsStep(s,w,1/60);assert.equal(s.health,health);assert.equal(e.phase,'patrol');});
test('Original folio watchman has a peaceful safe-town migration that preserves the old one-time score gate',()=>{const s=foot();s.mission=2;s.relay=true;atGate(s);s.x=w.bandit.x;s.z=w.bandit.z;assert.ok(nearbyFrontier(s,w).some(p=>p.id==='parley-folio'));assert.ok(frontierAction(s,w,'parley-folio').ok);assert.equal(s.defeated,true);assert.equal(s.banditHP,0);assert.equal(s.score,150);assert.equal(frontierAction(s,w,'parley-folio').ok,false);assert.equal(s.score,150);});
test('Existing Open Doors rivals accept a town truce and preserve their old one-time adventure counters',()=>{const s=foot();doorsStep(s,w,.01);const e=s.doors.enemies[0];s.doors.level=e.level;s.doors.room=e.room;s.x=e.x;s.z=e.z;s.speed=0;const before=s.credits;assert.ok(nearbyFrontier(s,w).some(p=>p.id==='parley:'+e.id));assert.ok(frontierAction(s,w,'parley:'+e.id).ok);assert.ok(s.doors.defeated.includes(e.id));assert.equal(s.credits,before+12);assert.equal(frontierAction(s,w,'parley:'+e.id).ok,false);assert.equal(s.credits,before+12);});
test('Gate Camp is a sanctuary and monsters leash back toward their own territory',()=>{const s=bad(),health=s.health;s.frontier.enemies[0].x=CAMP.x+3;s.frontier.enemies[0].z=CAMP.z;for(let i=0;i<180;i++)stepFrontier(s,w,{},1/60);assert.equal(s.health,health);assert.notEqual(s.frontier.enemies[0].phase,'windup');s.x=300;s.z=70;const m=s.frontier.enemies[0];m.x=300;m.z=73;for(let i=0;i<100;i++)stepFrontier(s,w,{},1/60);assert.ok(['windup','recover','chase'].includes(m.phase));});
test('Badlands attacks are telegraphed and staff combat damages only frontier monsters',()=>{const s=bad();s.x=300;s.z=64;const m=s.frontier.enemies.find(e=>e.id==='hollow-scout');m.x=300;m.z=66;const health=s.health;for(let i=0;i<80;i++)stepFrontier(s,w,{},1/60);assert.ok(m.phase==='windup'||m.phase==='recover'||s.health<health);const hp=m.hp;s.attackCD=0;assert.ok(strikeFrontier(s));assert.ok(m.hp<hp);assert.equal(s.banditHP,100);});
test('Sling aim locks onto visible monsters and travelling pellets can defeat them',()=>{const s=bad();chooseTool(s,'sling');s.x=300;s.z=55;s.yaw=0;const m=s.frontier.enemies.find(e=>e.id==='hollow-scout');m.x=300;m.z=62;assert.equal(aimTarget(s,w,0)?.id,m.id);for(let i=0;i<240&&m.hp>0;i++)step(s,w,{aim:true,fire:true,cameraYaw:0},1/60);assert.equal(m.hp,0);assert.ok(s.frontier.defeated.includes(m.id));assert.ok(s.frontier.cargo.ore>=1);});
test('Survey contract requires physical route visits and reports only at the safe-town gate',()=>{const s=bad();assert.ok(frontierAction(s,w,'accept:survey').ok);for(const id of['ridge','orchard','court']){const p=FRONTIER_SITES.find(x=>x.id===id);s.x=p.x;s.z=p.z;s.speed=0;assert.ok(frontierAction(s,w,'site:'+id).ok);}assert.ok(contractComplete(s,'survey'));assert.equal(frontierAction(s,w,'report:survey').ok,false);s.x=CAMP.x;s.z=CAMP.z;s.speed=0;assert.ok(leaveBadlands(s).ok);atGate(s);const before=s.credits;assert.ok(frontierAction(s,w,'report:survey').ok);assert.equal(s.credits,before+45);assert.equal(frontierAction(s,w,'report:survey').ok,false);assert.equal(s.credits,before+45);});
test('The field case cannot be recovered before the Hollow Warden yields',()=>{const s=bad();frontierAction(s,w,'accept:folio');const p=FRONTIER_SITES.find(p=>p.id==='case');s.x=p.x;s.z=p.z;s.speed=0;assert.equal(frontierAction(s,w,'site:case').ok,false);const m=s.frontier.enemies.find(e=>e.id==='hollow-warden');m.x=s.x;m.z=s.z+2;while(m.hp>0){s.attackCD=0;strikeFrontier(s);}assert.ok(frontierAction(s,w,'site:case').ok);assert.equal(s.frontier.relic,true);assert.ok(contractComplete(s,'folio'));});
test('Finite salvage banks only in town and dressings have a real bounded recipe and no full-health waste',()=>{const s=bad();for(const id of['resin-west','resin-east','ore']){const p=FRONTIER_SITES.find(p=>p.id===id);s.x=p.x;s.z=p.z;s.speed=0;assert.ok(frontierAction(s,w,'site:'+id).ok);assert.equal(frontierAction(s,w,'site:'+id).ok,false);}assert.ok(s.frontier.cargo.ore>=2&&s.frontier.cargo.resin>=4);assert.equal(frontierAction(s,w,'bank').ok,false);s.x=CAMP.x;s.z=CAMP.z;s.speed=0;leaveBadlands(s);atGate(s);assert.ok(frontierAction(s,w,'bank').ok);s.frontier.dressings=0;const ore=s.frontier.store.ore,resin=s.frontier.store.resin;assert.ok(frontierAction(s,w,'craft').ok);assert.equal(s.frontier.store.ore,ore-1);assert.equal(s.frontier.store.resin,resin-2);assert.equal(s.frontier.dressings,1);assert.equal(useDressing(s).ok,false);assert.equal(s.frontier.dressings,1);s.health=50;assert.ok(useDressing(s).ok);assert.equal(s.health,85);assert.equal(s.frontier.dressings,0);});
test('Rescue and reload never strand the player in combat or erase badlands progress/cargo',()=>{const s=bad();s.frontier.visited.push('ridge');s.frontier.cargo.resin=3;s.frontier.defeated.push('hollow-scout');s.health=0;stepFrontier(s,w,{},1/60);assert.equal(s.frontier.zone,'town');assert.equal(s.health,100);assert.deepEqual(s.frontier.visited,['ridge']);const raw=JSON.stringify(saveData(s));const r=newState(readSave(raw,w));assert.equal(r.frontier.zone,'town');assert.deepEqual(r.frontier.visited,['ridge']);assert.equal(r.frontier.cargo.resin,3);assert.ok(r.frontier.defeated.includes('hollow-scout'));});
test('Frontier tracking is observation only and never teleports, pays or completes a contract',()=>{const s=bad(),before={x:s.x,z:s.z,credits:s.credits,visited:[...s.frontier.visited]};assert.ok(targetFrontier(s,'court'));const t=frontierTarget(s);assert.equal(t.id,'court');assert.deepEqual({x:s.x,z:s.z,credits:s.credits,visited:[...s.frontier.visited]},before);});
