/* Declared model fixtures, not native playthroughs. The app installs the same
 * adapter on every real load/reset; legacy reducer fixtures remain separate. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeWorld,newState,readSave,saveData,step,attack,enterExit,recover,throwPaper,activeTarget} from '../model.mjs';
import {attachFrontier,frontierState,saveFrontier,inBadlands,safeTown,enterBadlands,leaveBadlands,frontierAction,hurtMonster,nearbyFrontier,frontierBlocked,frontierSight,refreshMonsters,CONTRACTS,MONSTERS,TRAIL_NODES,TRAIL_EDGES,FRONTIER_SITES,TOWN_GATE,CAMP} from '../frontier-core.mjs';
import {chooseTool,fireTool,reloadSling,validTargets,resonanceInput,resonanceStep} from '../resonance-core.mjs';
import {hitDoorEnemy} from '../doors-core.mjs';import {hitRocco,PEOPLE,stats,cast} from '../life-core.mjs';
const w=makeWorld(),fresh=()=>attachFrontier(newState()),tick=(s,n=60,input={})=>{for(let i=0;i<n;i++)step(s,w,input,1/60);};
function gate(s=fresh()){s.mode='foot';s.x=0;s.z=-17;s.speed=0;return s;}
function field(){const s=gate();assert.ok(enterBadlands(s).ok);return s;}
function at(s,p){s.x=p.x;s.z=p.z;s.speed=0;}
test('Unknown frontier save values are bounded, deduplicated and always resume safely in town',()=>{const f=frontierState({version:1,zone:'badlands',enemies:[{hp:Infinity}],defeated:['hollow-scout','hollow-scout','unknown'],cargo:{ore:Infinity,resin:-1},dressings:999,reported:['unknown']});assert.equal(f.zone,'town');assert.deepEqual(f.enemies,[]);assert.deepEqual(f.defeated,['hollow-scout']);assert.equal(f.cargo.ore,0);assert.equal(f.dressings,2);assert.deepEqual(f.reported,[]);});
test('Every field station and enemy spawn is collision-clear inside its actual bounded region',()=>{for(const p of[...FRONTIER_SITES,...MONSTERS])assert.equal(frontierBlocked(p.x,p.z,.34),false,p.id);assert.ok(frontierBlocked(NaN,0));assert.ok(frontierBlocked(300,200));});
test('All nineteen route segments are physically clear; the graph has multiple connected loops',()=>{assert.equal(TRAIL_EDGES.length,19);const seen=new Set([0]);while(true){let grew=false;for(const [a,b]of TRAIL_EDGES){if(seen.has(a)&&!seen.has(b)){seen.add(b);grew=true;}if(seen.has(b)&&!seen.has(a)){seen.add(a);grew=true;}}if(!grew)break;}assert.equal(seen.size,TRAIL_NODES.length);assert.ok(TRAIL_EDGES.length>TRAIL_NODES.length);for(const [a,b]of TRAIL_EDGES){const [x,z]=TRAIL_NODES[a],[xx,zz]=TRAIL_NODES[b];for(let i=0;i<=100;i++)assert.equal(frontierBlocked(x+(xx-x)*i/100,z+(zz-z)*i/100,.35),false,`${a}-${b} at ${i}`);}});
test('Town gate requires actual proximity, stopped foot travel and no active road test',()=>{const s=fresh();assert.equal(enterBadlands(s).ok,false);gate(s);s.speed=3;assert.equal(enterBadlands(s).ok,false);s.speed=0;s.cycle.active={gate:0};assert.equal(enterBadlands(s).ok,false);s.cycle.active=null;assert.ok(enterBadlands(s).ok);assert.equal(s.frontier.enemies.length,7);});
test('Entering and leaving clear both types of projectile, lock-on and stale cover; vehicles stay parked',()=>{const s=gate(),vehicles=JSON.stringify(s.vehicle);s.shots=[{life:5}];s.resonance.projectiles=[{life:5}];enterBadlands(s);assert.equal(s.shots.length,0);assert.equal(s.resonance.projectiles.length,0);s.resonance.lock='hollow-scout';s.resonance.cover={x:0,z:0};assert.ok(leaveBadlands(s).ok);assert.equal(s.resonance.lock,null);assert.equal(s.resonance.cover,null);assert.equal(JSON.stringify(s.vehicle),vehicles);});
test('Remote travel, remote gathering and remote banking are rejected',()=>{const s=field();s.x=320;s.z=50;assert.equal(leaveBadlands(s).ok,false);assert.equal(frontierAction(s,w,'site:ridge').ok,false);assert.equal(frontierAction(s,w,'bank').ok,false);});
test('Marking objectives does not teleport, charge, heal or grant quest progression',()=>{const s=gate(),before=[s.x,s.z,s.credits,s.health,s.mission];assert.ok(frontierAction(s,w,'track:gate').ok);assert.equal(activeTarget(s,w).z,-17);assert.deepEqual([s.x,s.z,s.credits,s.health,s.mission],before);});
test('All town combat layers suppress outgoing staff and incoming attacks without granting a victory',()=>{const s=gate();at(s,w.bandit);s.health=53;tick(s,600);assert.equal(s.health,53);assert.equal(attack(s,w),false);assert.equal(s.defeated,false);s.doors.level=3;const e=s.doors.enemies.find(e=>e.level===3);at(s,e);tick(s,600);assert.equal(s.health,53);assert.equal(hitDoorEnemy(s,w),false);assert.equal(s.doors.defeated.length,0);});
test('Rocco stays peaceful but his warrant and evidence still control the investigation',()=>{const s=gate();s.life.inside='inn';at(s,PEOPLE.find(p=>p.id==='rocco'));tick(s,600);assert.equal(s.health,100);assert.equal(s.life.flags.rocco,undefined);assert.equal(hitRocco(s,w),false);assert.equal(s.life.attackPending,false);assert.deepEqual(validTargets(s,w),[]);});
test('Town sling shots cannot injure rivals or receive hostile lock-on',()=>{const s=gate();at(s,w.bandit);s.z-=3;chooseTool(s,'sling');tick(s,180,{aim:true,cameraYaw:0,fire:true});assert.equal(s.banditHP,100);assert.equal(s.defeated,false);assert.equal(s.resonance.lock,null);});
test('Town restitution validates original folio stage and pays its old reward once',()=>{const s=gate();at(s,w.bandit);tick(s);assert.equal(frontierAction(s,w,'parley-folio').ok,false);s.mission=2;assert.ok(frontierAction(s,w,'parley-folio').ok);assert.equal(s.score,150);assert.equal(s.defeated,true);assert.equal(s.folio,false);assert.equal(frontierAction(s,w,'parley-folio').ok,false);assert.equal(s.score,150);});
test('A truce resolves actual attic or route rival requirements, once and only nearby',()=>{const s=gate();tick(s);const m=s.doors.enemies.find(e=>e.level===2);s.doors.level=2;s.doors.room=m.room;at(s,m);assert.ok(nearbyFrontier(s,w).some(p=>p.id==='parley:'+m.id));assert.ok(frontierAction(s,w,'parley:'+m.id).ok);assert.equal(s.credits,12);assert.ok(s.doors.defeated.includes(m.id));assert.equal(frontierAction(s,w,'parley:'+m.id).ok,false);assert.equal(s.credits,12);});
test('Safe camp is protected in both directions, so the player cannot farm monsters from sanctuary',()=>{const s=field(),m=s.frontier.enemies[0];m.x=300;m.z=30;assert.equal(hurtMonster(s,m.id,50),false);tick(s,600);assert.equal(s.health,100);assert.equal(m.hp,m.maxHP);s.z=45;m.z=31;assert.equal(hurtMonster(s,m.id,50),false);});
test('Real finite projectiles and staff attacks work against field monsters outside sanctuary',()=>{const s=field();s.z=43;chooseTool(s,'sling');for(let i=0;i<160;i++)step(s,w,{aim:true,cameraYaw:0,fire:true},1/60);assert.ok(s.frontier.defeated.includes('hollow-scout'));assert.ok(s.resonance.ready<6);assert.equal(s.frontier.cargo.ore,1);assert.equal(s.credits,0);});
test('Reload transfers finite reserve, and gate transition cannot carry a live projectile into town',()=>{const s=field();s.z=43;chooseTool(s,'sling');tick(s,5,{fire:true,aim:true,cameraYaw:0});const reserve=s.resonance.reserve;assert.ok(reloadSling(s));tick(s,90);assert.equal(s.resonance.ready,6);assert.equal(s.resonance.reserve,reserve-1);at(s,CAMP);leaveBadlands(s);assert.equal(s.resonance.projectiles.length,0);});
test('Monsters telegraph, deal real damage outside camp, and Y consumes a dressing only when useful',()=>{const s=field();s.z=62;tick(s,360);assert.ok(s.health<100);const n=s.frontier.dressings;assert.ok(enterExit(s,w));assert.equal(s.frontier.dressings,n-1);assert.equal(s.health,100);assert.equal(enterExit(s,w),false);assert.equal(s.frontier.dressings,n-1);});
test('Enemy attacks respect ruins and return toward home when the player disengages',()=>{const s=field(),m=s.frontier.enemies[0];s.x=300;s.z=60;tick(s,20);const z=m.z;s.x=375;s.z=185;tick(s,500);assert.ok(Math.hypot(m.x-m.homeX,m.z-m.homeZ)<.7);assert.ok(frontierSight({x:300,z:50},{x:300,z:60}));assert.equal(frontierSight({x:250,z:73},{x:270,z:73}),false);});
test('Survey contracts are optional peaceful travel and pay only at the town gate',()=>{const s=field();assert.ok(frontierAction(s,w,'accept:survey').ok);for(const id of['ridge','orchard','court']){const p=FRONTIER_SITES.find(p=>p.id===id);at(s,p);assert.ok(frontierAction(s,w,'site:'+id).ok);}assert.equal(s.frontier.defeated.length,0);assert.equal(frontierAction(s,w,'report:survey').ok,false);at(s,CAMP);leaveBadlands(s);assert.ok(frontierAction(s,w,'report:survey').ok);assert.equal(s.credits,45);assert.equal(frontierAction(s,w,'report:survey').ok,false);assert.equal(s.credits,45);});
test('Guarded case cannot be collected early; monster loot is awarded exactly once',()=>{const s=field();at(s,FRONTIER_SITES.find(p=>p.id==='case'));assert.equal(frontierAction(s,w,'site:case').ok,false);const m=s.frontier.enemies.find(m=>m.id==='hollow-warden');hurtMonster(s,m.id,100);hurtMonster(s,m.id,100);assert.ok(frontierAction(s,w,'site:case').ok);assert.equal(s.frontier.cargo.ore,2);assert.equal(hurtMonster(s,m.id,100),false);assert.equal(s.frontier.cargo.ore,2);});
test('Sources are finite, cargo banks in town, and crafting spends the advertised resources',()=>{const s=field();for(const id of['resin-west','ore']){at(s,FRONTIER_SITES.find(p=>p.id===id));assert.ok(frontierAction(s,w,'site:'+id).ok);assert.equal(frontierAction(s,w,'site:'+id).ok,false);}at(s,CAMP);leaveBadlands(s);frontierAction(s,w,'bank');assert.deepEqual(s.frontier.cargo,{ore:0,resin:0});assert.deepEqual(s.frontier.store,{ore:2,resin:2});assert.ok(frontierAction(s,w,'craft').ok);assert.equal(s.frontier.dressings,3);assert.deepEqual(s.frontier.store,{ore:1,resin:0});assert.equal(frontierAction(s,w,'craft').ok,false);});
test('Field defeat returns to the town without losing cargo, money, completed quests or parked vehicles',()=>{const s=field();s.credits=123;s.frontier.cargo.ore=7;s.doors.homes.workshop=4;const vehicles=JSON.stringify(s.vehicle);s.z=62;s.health=1;tick(s,360);assert.ok(safeTown(s));assert.equal(s.health,100);assert.equal(s.credits,123);assert.equal(s.frontier.cargo.ore,7);assert.equal(s.doors.homes.workshop,4);assert.equal(JSON.stringify(s.vehicle),vehicles);});
test('The original recover action also leaves the field safely',()=>{const s=field();s.frontier.cargo.resin=4;s.z=170;recover(s);assert.ok(safeTown(s));assert.equal(s.frontier.cargo.resin,4);assert.equal(s.mode,'foot');});
test('Save/load keeps old house cases, profile equipment and banked progress with no duplicate reward',()=>{const s=field();s.doors.stories.cases.lamplighter={stage:6,route:'roof',mask:5,resolution:'amber'};s.frontier.defeated=['hollow-scout'];s.frontier.cargo.ore=1;s.frontier.reported=['survey'];s.frontier.accepted=['survey'];s.credits=45;chooseTool(s,'sling');const data=readSave(JSON.stringify(saveData(s)),w),loaded=attachFrontier(newState(data),data.frontier);assert.ok(safeTown(loaded));assert.equal(loaded.resonance.tool,'sling');assert.equal(loaded.frontier.cargo.ore,1);assert.equal(loaded.credits,45);assert.equal(loaded.doors.stories.cases.lamplighter.resolution,'amber');gate(loaded);enterBadlands(loaded);assert.equal(loaded.frontier.enemies[0].hp,0);assert.equal(loaded.frontier.cargo.ore,1);});
test('Badlands input cannot operate distant town nodes, throw deliveries, or mutate parked vehicles',()=>{const s=field();s.x=300;s.z=180;const vehicles=JSON.stringify(s.vehicle);tick(s,200,{hack:true,leftPaper:true,rightPaper:true});assert.equal(s.relay,false);assert.equal(s.deliveries.size,0);assert.equal(throwPaper(s,w,1),false);assert.equal(JSON.stringify(s.vehicle),vehicles);});
