/* Deterministic interaction fixtures deliberately place the actor. Native
 * keyboard/touch journeys are tested independently; these are not replays. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeWorld,newState,step,scan,blocked,attack,saveData,readSave,enterExit,refill,recover,VERSION} from '../model.mjs';
import {ROOMS,QUESTS,PEOPLE,CATS,targets,use,stats,points,spend,cast,done,saveLife,readLife,roomAt,grant,nearest,personAt,mapTarget} from '../life-core.mjs';
const w=makeWorld(),tick=(s,input={},n=60)=>{for(let i=0;i<n;i++)step(s,w,input,1/60);};
function near(s,id){const original=PEOPLE.find(p=>p.id===id)||targets(s,w).find(p=>p.id===id);if(original?.inside!==undefined)s.life.inside=original.inside;else if(!id.startsWith('up-'))s.life.inside=null;let t=targets(s,w).find(p=>p.id===id);if(!t){for(const inside of [null,'workshop','inn']){s.life.inside=inside;t=targets(s,w).find(p=>p.id===id);if(t)break;}}assert.ok(t,'Target '+id+' exists in its correct space');s.mode='foot';s.speed=0;s.x=t.x;s.z=t.z-.4;return t;}
function perform(s,id,action){near(s,id);const r=use(s,w,id,action);assert.ok(r.ok,id+'/'+action+': '+r.text);return r;}
function allProgress(){const s=newState();
 perform(s,'leonardo','start:ink');perform(s,'ada','progress:ink');perform(s,'leonardo','progress:ink');
 perform(s,'beatrice','start:cat');perform(s,'pippa','pet');perform(s,'beatrice','progress:cat');
 perform(s,'ada','start:lantern');perform(s,'down-workshop','stairs');for(const x of['leaf','water','star'])perform(s,'prism','rune:'+x);perform(s,'prism','progress:lantern');perform(s,'up-workshop','stairs');perform(s,'ada','progress:lantern');
 perform(s,'mayor','start:receipts');perform(s,'lucia','progress:receipts');perform(s,'down-inn','stairs');near(s,'ledger');assert.ok(cast(s));perform(s,'ledger','progress:receipts');perform(s,'rocco','progress:receipts');perform(s,'up-inn','stairs');perform(s,'mayor','progress:receipts');
 perform(s,'bartolo','start:orchard');perform(s,'down-workshop','stairs');perform(s,'cog','progress:orchard');perform(s,'up-workshop','stairs');s.x=11.3;s.z=190;s.speed=0;scan(s);tick(s,{hack:true},140);assert.ok(s.relay);perform(s,'pump','progress:orchard');perform(s,'bartolo','progress:orchard');
 perform(s,'luca','start:courier');for(const id of['stamp-west','stamp-east','stamp-market','luca'])perform(s,id,'progress:courier');
 perform(s,'isabella','start:pigments');for(const id of['pigment-red','pigment-blue','pigment-gold','isabella'])perform(s,id,'progress:pigments');
 perform(s,'sofia','start:lenses');for(const id of['lens-east','lens-west','sofia'])perform(s,id,'progress:lenses');
 perform(s,'leonardo','start:sky');for(const id of['isabella','wind','sofia','leonardo'])perform(s,id,'progress:sky');return s;
}
test('Every new commission can progress through its dependency chain using actual interaction rules',()=>{const s=allProgress();assert.equal(QUESTS.length,9);assert.ok(QUESTS.every(q=>done(s.life,q.id)));assert.equal(s.life.flags.garden,true);assert.equal(s.life.flags.airframe,true);assert.equal(s.life.partner,null);assert.equal(s.completed,false,'Side quests do not fake completion of the original folio story');});
test('Quest rewards are awarded once, including after save/reload',()=>{const s=allProgress(),before=s.credits,xp=s.life.xp;near(s,'leonardo');assert.equal(use(s,w,'leonardo','progress:sky').ok,false);const saved=readSave(JSON.stringify(saveData(s)),w),r=newState(saved);near(r,'leonardo');assert.equal(use(r,w,'leonardo','progress:sky').ok,false);assert.equal(r.credits,before);assert.equal(r.life.xp,xp);});
test('Version 0.2 saves retain the first commission and safely initialize the expansion',()=>{const old={version:2,folio:true,defeated:true,upgraded:true,completed:true,relay:true,score:1200,credits:375,deliveries:['mail-0','mail-1','mail-2','mail-3']};const parsed=readSave(JSON.stringify(old),w),s=newState(parsed);assert.equal(s.completed,true);assert.equal(s.mission,4);assert.equal(s.credits,375);assert.equal(s.life.xp,0);tick(s,{},1);assert.equal(s.life.xp,210);const restored=newState(readSave(JSON.stringify(saveData(s)),w));tick(restored,{},120);assert.equal(restored.life.xp,210);});
test('Original ground map and delivery targets stay; the north extension is mission locked',()=>{const s=newState();assert.equal(w.originalHouseCount,45);assert.equal(w.houses.length,49);assert.equal(w.mailboxes.filter(x=>x.route).length,6);assert.equal(w.limits.zMax,566);s.mode='bike';assert.ok(blocked(0,407,.5,w,s));assert.ok(blocked(50,407,.5,w,s));s.life.flags.garden=true;assert.equal(blocked(0,407,.5,w,s),false);assert.equal(blocked(50,407,.5,w,s),true);assert.equal(blocked(0,553,.5,w,s),false);});
test('Every retained interior has a physically clear doorway and solid rear wall',()=>{const s=newState();s.mode='foot';assert.equal(w.rooms.length,6);for(const r of w.rooms){s.life.flags.garden=true;s.life.inside=null;assert.equal(blocked(r.door.x,r.door.z,.33,w,s),false,r.id+' entrance');assert.equal(blocked(r.x,r.z,.33,w,s),false,r.id+' center');assert.equal(blocked(r.x+r.side*(r.hx-.2),r.z,.33,w,s),true,r.id+' rear');s.x=r.x;s.z=r.z;assert.equal(roomAt(s,w).id,r.id);s.mode='bike';assert.equal(blocked(r.x,r.z,.5,w,s),true);s.mode='foot';}});
test('Basement transition requires its stairs, leaves the bike parked, and returns via the same building',()=>{const s=newState(),vehicle=JSON.stringify(s.vehicle);const r=perform(s,'down-workshop','stairs');assert.ok(r.close);assert.equal(s.life.inside,'workshop');assert.equal(s.mode,'foot');assert.equal(JSON.stringify(s.vehicle),vehicle);const room=w.rooms.find(r=>r.id==='workshop');assert.equal(blocked(room.x+50,room.z,.33,w,s),true);tick(s,{throttle:1},30);perform(s,'up-workshop','stairs');assert.equal(s.life.inside,null);assert.equal(JSON.stringify(s.vehicle),vehicle);});
test('The inn cellar cannot be entered before helping its owner',()=>{const s=newState();near(s,'down-inn');assert.equal(use(s,w,'down-inn','stairs').ok,false);assert.equal(s.life.inside,null);perform(s,'beatrice','start:cat');perform(s,'pippa','pet');perform(s,'beatrice','progress:cat');perform(s,'down-inn','stairs');assert.equal(s.life.inside,'inn');});
test('Three-symbol puzzle has a clue sequence and rejects an incorrect order',()=>{const s=newState();perform(s,'down-workshop','stairs');perform(s,'prism','rune:water');assert.deepEqual(s.life.runes,[]);assert.equal(s.life.flags.prism,undefined);for(const x of['leaf','water','star'])perform(s,'prism','rune:'+x);assert.ok(s.life.flags.prism);near(s,'prism');assert.equal(use(s,w,'prism','progress:lantern').ok,false,'Finding an item does not manufacture an unaccepted quest');});
test('Hidden evidence needs a warrant and an active, resource-costed Lantern spell',()=>{const s=newState();s.life.flags.lantern=true;s.life.inside='inn';s.mode='foot';s.life.quests.receipts=2;near(s,'ledger');assert.equal(use(s,w,'ledger','progress:receipts').ok,false);s.life.flags.warrant=true;assert.equal(use(s,w,'ledger','progress:receipts').ok,false);const focus=s.life.focus;assert.ok(cast(s));assert.equal(s.life.focus,focus-18);assert.equal(cast(s),false);assert.equal(use(s,w,'ledger','progress:receipts').ok,true);assert.ok(s.life.flags.ledger);});
test('The garden pump requires the original waterwheel as well as the charter and cog',()=>{const s=newState();s.life.quests.orchard=2;near(s,'pump');for(const key of['charter','cog']){assert.equal(use(s,w,'pump','progress:orchard').ok,false);s.life.flags[key]=true;}assert.equal(use(s,w,'pump','progress:orchard').ok,false);s.relay=true;assert.ok(use(s,w,'pump','progress:orchard').ok);assert.ok(s.life.flags.garden);});
test('Named people and objects cannot be activated remotely or from the wrong floor',()=>{const s=newState();assert.equal(use(s,w,'ada','start:lantern').ok,false);near(s,'neri');s.life.inside=null;assert.equal(use(s,w,'neri','anything').ok,false);near(s,'leonardo');s.mode='bike';assert.equal(use(s,w,'leonardo','start:ink').ok,false);});
test('Attributes spend finite level points and have concrete health, focus and riding effects',()=>{const s=newState();assert.equal(spend(s,'vitality'),false);grant(s,'quest-ink',650);assert.equal(stats(s).level,5);assert.equal(points(s.life),4);for(const key of['vitality','riding','ingenuity','empathy'])assert.ok(spend(s,key));assert.equal(points(s.life),0);assert.equal(spend(s,'vitality'),false);assert.equal(stats(s).maxHealth,112);assert.equal(stats(s).maxFocus,75);assert.equal(stats(s).rideBonus,.6);assert.equal(stats(s).discount,.97);refill(s);assert.equal(s.health,112);});
test('Courier and cargo variants are unlocked, purchased and equipped at the smith only',()=>{const s=newState();s.credits=300;near(s,'bartolo');assert.equal(use(s,w,'bartolo','buy:courier').ok,false);s.life.quests.courier=QUESTS.find(q=>q.id==='courier').stages.length+1;perform(s,'bartolo','buy:courier');assert.equal(s.credits,215);perform(s,'bartolo','buy:courier');assert.equal(s.credits,215);s.life.quests.ink=3;perform(s,'bartolo','buy:cargo');assert.equal(s.credits,140);refill(s);assert.equal(s.papers,30);assert.equal(stats(s).maxPapers,30);});
test('New bicycle gearing changes motion without replacing analogue steering',()=>{const a=newState(),b=newState(),c=newState();b.life.bike='courier';c.life.bike='cargo';for(const s of[a,b,c]){s.x=1;s.z=270;tick(s,{throttle:1},90);}assert.ok(b.distance>a.distance&&a.distance>c.distance);});
test('Adults can choose a mutual relationship after a commission, or remain friends without losing rewards',()=>{const s=allProgress(),credits=s.credits,xp=s.life.xp;perform(s,'isabella','chat');perform(s,'isabella','date');assert.equal(s.life.partner,'isabella');const point=personAt(PEOPLE.find(p=>p.id==='isabella'),s);assert.equal(point.z,464);perform(s,'sofia','chat');near(s,'sofia');assert.equal(use(s,w,'sofia','date').ok,false);perform(s,'isabella','friends');assert.equal(s.life.partner,null);assert.equal(s.credits,credits);assert.equal(s.life.xp,xp);assert.ok(PEOPLE.filter(p=>p.romance).every(p=>p.age>=18));});
test('Gifts cannot be farmed and do not by themselves unlock romance',()=>{const s=newState();s.credits=100;perform(s,'isabella','gift');const n=s.life.friends.isabella;near(s,'isabella');assert.equal(use(s,w,'isabella','gift').ok,false);assert.equal(use(s,w,'isabella','date').ok,false);assert.equal(s.life.friends.isabella,n);});
test('The optional cat companion follows over time without being moved by the map',()=>{const s=newState();s.life.cat=true;s.life.petX=91;s.life.petZ=202;s.x=80;s.z=205;const d=Math.hypot(s.life.petX-s.x,s.life.petZ-s.z);tick(s,{},30);assert.ok(Math.hypot(s.life.petX-s.x,s.life.petZ-s.z)<d);const before=JSON.stringify(s);mapTarget(s,w);assert.equal(JSON.stringify(s),before);});
test('Recovery exits a cellar while preserving quests, relationships and equipped bikes',()=>{const s=allProgress();s.life.inside='inn';s.life.bike='courier';const quests=JSON.stringify(s.life.quests);recover(s);assert.equal(s.life.inside,null);assert.equal(JSON.stringify(s.life.quests),quests);assert.equal(s.life.bike,'courier');assert.equal(s.mode,'bike');});
test('Invalid or oversized progression fields cannot add arbitrary objects or overspend attribute points',()=>{const l=readLife({version:1,xp:-1,attrs:{riding:900},paid:['bad','mail-1'],owned:['spaceship'],partner:'minor',quests:{ink:9999},flags:{unlimited:true}});assert.equal(l.xp,0);assert.equal(l.attrs.riding,0);assert.deepEqual(l.owned,['standard']);assert.equal(l.partner,null);assert.equal(l.quests.ink,undefined);assert.equal(l.flags.unlimited,undefined);});
