import {test} from 'node:test';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';
import {boxInterval,seesFragment,centeredWorldMatrix,faceOpacity,PortalMaterials,patchShader} from '../world-portal.mjs';
import {createWorldView} from '../world-view.mjs';import {quarterObjective} from '../quarter-goal.mjs';import {quarterState} from '../quarter-core.mjs';
const size={width:2,height:1,depth:2},inverse=new T.Matrix4().makeTranslation(0,0,2),v=(x,y,z)=>new T.Vector3(x,y,z);
test('Portal preserves world depth beyond its rear wall, rejects outside rays and foreground geometry',()=>{assert.ok(seesFragment(v(0,.5,0),v(0,.5,-30),inverse,size));assert.equal(seesFragment(v(0,.5,0),v(9,.5,-2),inverse,size),false);assert.equal(seesFragment(v(0,.5,0),v(0,.5,-.1),inverse,size),false);});
test('Parallel, inside-box and distinct-eye rays have finite correct classifications',()=>{assert.equal(boxInterval(v(2,.5,0),v(0,0,-1),size),null);assert.equal(boxInterval(v(0,.5,0),v(0,0,-1),size).enter,0);assert.equal(boxInterval(v(NaN,0,0),v(1,0,0),size),null);const point=v(3,.5,-3);assert.notEqual(seesFragment(v(-.3,.5,0),point,inverse,size),seesFragment(v(.3,.5,0),point,inverse,size));});
test('Full actor position and height map to the fixed exhibit center under every chase-camera rotation',()=>{for(const yaw of[0,.8,-2,Math.PI])for(const a of[v(0,0,0),v(-20,3.2,-13),v(300,-6,400)]){const p=a.clone().applyMatrix4(centeredWorldMatrix(a,.08,yaw));assert.ok(p.length()<1e-10);}});
test('Near panes are transparent from front, sides, rear and above; far panes are only lightly tinted',()=>{for(const normal of[v(1,0,0),v(-1,0,0),v(0,0,1),v(0,0,-1),v(0,1,0)]){const point=normal.clone();assert.equal(faceOpacity(normal.clone().multiplyScalar(3),normal,point),0);assert.equal(faceOpacity(normal.clone().multiplyScalar(-3),normal,point),.025);assert.equal(faceOpacity(v(0,0,0),normal,point,false),0);}});
test('Wrapping preserves custom hooks, final instanced projection and restores hooks on disposal',()=>{const m=new T.MeshBasicMaterial(),old=m.onBeforeCompile;let called=false;m.onBeforeCompile=s=>{called=true;s.fragmentShader=s.fragmentShader.replace('gl_FragColor','/* existing hook */gl_FragColor');};const hook=m.onBeforeCompile,p=new PortalMaterials();p.attach(m);const s={uniforms:{},vertexShader:'void main(){gl_Position=projectionMatrix*vec4(1.);}',fragmentShader:'void main(){gl_FragColor=vec4(1.);}'};m.onBeforeCompile(s,{});assert.ok(called);assert.ok(s.fragmentShader.includes('existing hook'));assert.ok(s.vertexShader.includes('inverse(projectionMatrix)*gl_Position'));assert.ok(s.fragmentShader.includes('cameraPosition'));p.active=true;assert.equal(s.uniforms.guildPortalEnabled.value,1);p.dispose();assert.equal(m.onBeforeCompile,hook);assert.equal(s.uniforms.guildPortalEnabled.value,0);m.dispose();});
test('Whole-scene adoption includes new effects and restores child order and avatar visibility',()=>{const scene=new T.Scene(),avatar=new T.Group();avatar.userData.guildControlled=true;avatar.position.set(30,4,10);const sky=new T.Group();sky.userData.xrBackdrop=true;scene.add(avatar,sky);const state={x:30,z:10,quarter:{active:false}},view={scene,spatial:{setPresentation(){},setSkipRender(){}},headBlocked:()=>false},provider=createWorldView(view,()=>state);assert.deepEqual(provider.anchor(),{x:30,y:4,z:10});const added=new T.Group();scene.add(added);const before=[...scene.children];provider.acquire('first-person');assert.equal(avatar.visible,false);assert.equal(sky.visible,false);assert.equal(provider.root.children.length,3);provider.release();assert.deepEqual(scene.children,before);assert.equal(avatar.visible,true);assert.equal(sky.visible,true);});
test('Hidden legacy player cannot become the frontier presentation anchor',()=>{const scene=new T.Scene(),hidden=new T.Group(),old=new T.Group(),current=new T.Group();old.userData.guildControlled=current.userData.guildControlled=true;old.position.y=99;current.position.y=3;hidden.visible=false;hidden.add(old);scene.add(hidden,current);const provider=createWorldView({scene},()=>({x:2,z:5}));assert.equal(provider.anchor().y,3);});
test('Map guidance exposes the next goal even on another floor without mutating saves',()=>{const q=quarterState({active:true}),s={x:-20,z:-13,quarter:q};const before=JSON.stringify(s),g=quarterObjective(s);assert.equal(g.id,'parcel');assert.equal(g.layer,'upper');assert.equal(g.vertical,'above you');assert.equal(JSON.stringify(s),before);});
test('Map goal follows legal return, spindle custody, finishing and completed exploration',()=>{const q=quarterState({active:true,parcel:true}),s={x:-20,z:-13,quarter:q};assert.equal(quarterObjective(s).id,'workshop');q.reported=true;q.delivery=1;assert.equal(quarterObjective(s).id,'precision');q.porterOrder='requested';q.porter={carrying:true,x:10,y:3.2,z:13};assert.equal(quarterObjective(s).id,'porter');assert.equal(quarterObjective(s).x,10);q.delivery=2;assert.equal(quarterObjective(s).id,'loft');q.delivery=3;assert.equal(quarterObjective(s).id,'town');assert.ok(quarterObjective(s).optional);});

test('Portal restores ordinary chase-camera avatar fade rather than inheriting an almost invisible player',()=>{const scene=new T.Scene(),m=new T.MeshBasicMaterial({opacity:.16,transparent:true,depthWrite:false}),a=new T.Mesh(new T.BoxGeometry(),m);a.userData.guildControlled=true;scene.add(a);const world=createWorldView({scene},()=>({x:0,z:0}));world.acquire('diorama');assert.equal(m.opacity,1);assert.equal(m.depthWrite,true);world.release();assert.equal(m.opacity,.16);assert.equal(m.transparent,true);assert.equal(m.depthWrite,false);});
