/* Explicit model fixtures. These are not browser journeys or hardware tests. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeWorld,newState,step,saveData,readSave,refill,trade,attack,throwPaper} from '../model.mjs';
import {cast} from '../life-core.mjs';
import {resonanceState,chooseTool,chooseDiscipline,specialAbility,reloadSling,fireTool,clearShot,aimTarget,validTargets,toggleCover,resonanceInput} from '../resonance-core.mjs';
import {audioPreferences,consolePreferences,radialIndex,scoreFor,spatialMix,surfaceFor,MUSIC} from '../resonance-data.mjs';
const w=makeWorld(),actions={attack,throwPaper,cast};
const foot=()=>{const s=newState();s.mode='foot';return s;};
const legacyFoot=()=>{const s=foot();delete s.frontier;return s;};
function tick(s,seconds=1,input={}){for(let n=0;n<Math.round(seconds*60);n++)step(s,w,input,1/60);}
function guardFixture(){const s=legacyFoot();s.x=80;s.z=320;s.yaw=0;chooseTool(s,'sling');return s;}
test('Old saves initialize new equipment without changing earlier money, commissions or namespace',()=>{const s=newState();s.credits=1234;s.life.quests.ink=2;s.doors.homes.workshop=3;const v=saveData(s);delete v.resonance;const loaded=newState(readSave(JSON.stringify(v),w));assert.equal(loaded.credits,1234);assert.equal(loaded.life.quests.ink,2);assert.equal(loaded.doors.homes.workshop,3);assert.equal(loaded.resonance.ready,6);});
test('Equipment and preferences reject arbitrary identities, NaN, infinite levels and invalid counts',()=>{const c=resonanceState({version:1,tool:'gun',ready:NaN,reserve:999999,variants:{sling:Infinity},discipline:'other'});assert.equal(c.tool,'staff');assert.equal(c.ready,6);assert.equal(c.reserve,36);assert.equal(c.variants.sling,0);assert.equal(c.discipline,'courier');const p=audioPreferences({master:99,effects:-4,music:NaN,station:'http://untrusted',range:'fake'});assert.equal(p.master,1);assert.equal(p.effects,0);assert.equal(p.music,.52);assert.equal(p.station,'auto');assert.equal(consolePreferences({profile:'unknown'}).profile,'console');});
test('Each valid tool variant can be selected but no invented arsenal can be equipped',()=>{const s=foot();assert.ok(chooseTool(s,'sling',1));assert.equal(chooseTool(s,'sling',2),false);assert.equal(chooseTool(s,'gun'),false);assert.equal(s.resonance.tool,'sling');});
test('Legacy sling ammo reducer retains six-shot bounded reload behavior',()=>{const s=legacyFoot();chooseTool(s,'sling');for(let n=0;n<6;n++){assert.ok(fireTool(s,w,actions));assert.equal(fireTool(s,w,actions),false);tick(s,.45);}assert.equal(s.resonance.ready,0);assert.equal(fireTool(s,w,actions),false);assert.ok(reloadSling(s));assert.equal(reloadSling(s),false);tick(s,.7);assert.equal(s.resonance.ready,0);tick(s,.7);assert.equal(s.resonance.ready,6);assert.equal(s.resonance.reserve,30);});
test('Reload uses the last available pellets and an empty reserve cannot create ammo',()=>{const s=foot();chooseTool(s,'sling');s.resonance.ready=0;s.resonance.reserve=2;assert.ok(reloadSling(s));tick(s,1.5);assert.equal(s.resonance.ready,2);assert.equal(s.resonance.reserve,0);assert.equal(reloadSling(s),false);});
test('Camera-aligned free aim and optional lock-on select enemies, never residents',()=>{const s=guardFixture();assert.equal(aimTarget(s,w,0)?.id,'folio-guard');assert.equal(aimTarget(s,w,Math.PI),null);assert.equal(aimTarget(s,w,0,false),null);assert.ok(validTargets(s,w).every(t=>['rival','guard','rocco'].includes(t.kind)));});
test('Actual travelling pellets hit the guard, yield once, and do not auto-complete the folio quest',()=>{const s=guardFixture();for(let i=0;i<4;i++){step(s,w,{aim:true,cameraYaw:0},1/60);assert.ok(fireTool(s,w,actions));assert.equal(s.resonance.projectiles.length,1);tick(s,.55,{aim:true,cameraYaw:0});}assert.equal(s.banditHP,0);assert.equal(s.defeated,true);assert.equal(s.score,150);assert.equal(s.folio,false);assert.equal(s.completed,false);tick(s,2,{fire:true});assert.equal(s.score,150);});
test('A projectile cannot be spawned beyond a thin wall and damage a target through it',()=>{const s=guardFixture();s.x=80;s.z=326;const thin={id:'fixture-wall',x:80,z:326.25,hx:3,hz:.08};const ww={...w,colliders:[...w.colliders,thin]};assert.equal(clearShot(s,ww,s,{x:80,z:330}),false);step(s,ww,{aim:true,cameraYaw:0},1/60);assert.equal(s.resonance.lock,null);fireTool(s,ww,actions);for(let i=0;i<50;i++)step(s,ww,{},1/60);assert.equal(s.banditHP,100);assert.equal(s.resonance.projectiles.length,0);});
test('Targets and projectiles cannot leak between a house, attic and street',()=>{const s=guardFixture();step(s,w,{},1/60);fireTool(s,w,actions);s.doors.level=1;s.doors.room='workshop';s.x=-24.5;s.z=24;tick(s,.1);assert.equal(s.resonance.projectiles.length,0);assert.equal(validTargets(s,w).some(t=>t.id==='folio-guard'),false);});
test('Legacy heavy staff reducer retains its slower stronger strike tradeoff',()=>{const a=legacyFoot(),b=legacyFoot();for(const s of[a,b]){s.x=80;s.z=328;step(s,w,{},1/60);}chooseTool(a,'staff',0);chooseTool(b,'staff',1);fireTool(a,w,actions);fireTool(b,w,actions);assert.ok(b.banditHP<a.banditHP);assert.ok(b.attackCD>a.attackCD);});
test('Selected letters still use the original delivery reducer and inventory',()=>{const s=foot();chooseTool(s,'letters',1);const n=s.papers;assert.ok(fireTool(s,w,actions));assert.equal(s.papers,n-1);assert.equal(s.shots.length,1);assert.equal(s.events.at(-1).type,'throw');});
test('Selecting the Lantern does not grant the existing earned Lantern power',()=>{const s=foot();chooseTool(s,'lantern');fireTool(s,w,actions);assert.equal(s.life.flags.lantern,undefined);assert.equal(s.life.aura,0);});
test('Cover requires a real nearby obstacle and ends after moving away',()=>{const s=foot();assert.equal(toggleCover(s,w),false);const box=w.colliders[0];s.x=box.x+box.hx+.8;s.z=box.z;assert.ok(toggleCover(s,w));assert.ok(resonanceInput(s,w,{},1/60).guard);s.x+=4;resonanceInput(s,w,{},1/60);assert.equal(s.resonance.cover,null);});
test('Guard energy depletes and cannot remain permanently active by holding aim',()=>{const s=foot();let input;for(let i=0;i<650;i++)input=resonanceInput(s,w,{aim:true},1/60);assert.equal(s.resonance.guardTired,true);assert.equal(input.guard,false);for(let i=0;i<90;i++)resonanceInput(s,w,{},1/60);assert.equal(s.resonance.guardTired,false);});
test('Special abilities cost focus, obey a cooldown and persist only the chosen discipline',()=>{const s=foot();assert.ok(chooseDiscipline(s,w,'warden'));s.health=50;assert.ok(specialAbility(s));assert.equal(s.life.focus,20);assert.equal(specialAbility(s),false);tick(s,3);assert.ok(s.health>55);assert.ok(s.resonance.special>0);const loaded=newState(readSave(JSON.stringify(saveData(s)),w));assert.equal(loaded.resonance.discipline,'warden');assert.equal(loaded.resonance.special,0);});
test('Discipline cannot be switched mid-threat or during an active ability',()=>{const s=guardFixture();assert.equal(chooseDiscipline(s,w,'warden'),false);s.z=290;assert.ok(chooseDiscipline(s,w,'artificer'));specialAbility(s);assert.equal(chooseDiscipline(s,w,'courier'),false);});
test('Artificer focus provides faster reload and real mechanism scan',()=>{const s=foot();chooseDiscipline(s,w,'artificer');chooseTool(s,'sling');s.resonance.ready=0;specialAbility(s);assert.ok(s.scan>0);reloadSling(s);assert.equal(s.resonance.reload,.5);tick(s,.6);assert.equal(s.resonance.ready,6);});
test('Camera-relative movement changes the travel vector while aiming keeps the target-facing yaw',()=>{const s=foot();const x=s.x;tick(s,.5,{throttle:1,moveYaw:Math.PI/2,cameraYaw:0,aim:true});assert.ok(s.x>x+1);assert.equal(s.yaw,0);});
test('Workshop and paid market supplies refill pellets without affecting other saved progress',()=>{const s=foot();s.resonance.ready=0;s.resonance.reserve=0;s.doors.homes.workshop=4;refill(s);assert.equal(s.resonance.reserve,36);s.x=w.shop.x;s.z=w.shop.z;s.credits=20;s.resonance.reserve=0;assert.ok(trade(s,w,'supplies'));assert.equal(s.credits,0);assert.equal(s.resonance.reserve,36);assert.equal(s.doors.homes.workshop,4);});
test('Radial pointing is stable inside the dead zone and supports all sectors',()=>{assert.equal(radialIndex(0,0,4,2),2);assert.equal(radialIndex(0,-1,4),0);assert.equal(radialIndex(1,0,4),1);assert.equal(radialIndex(0,1,4),2);assert.equal(radialIndex(-1,0,4),3);assert.equal(radialIndex(NaN,1,4,2),2);});
test('Adaptive score differentiates day, night, interiors, undercity and pursuit',()=>{assert.equal(MUSIC.length,5);assert.equal(scoreFor({z:20}),'vinci');assert.equal(scoreFor({z:170}),'market');assert.equal(scoreFor({minute:1200}),'lamplight');assert.equal(scoreFor({room:'workshop'}),'lamplight');assert.equal(scoreFor({level:-2}),'underways');assert.equal(scoreFor({danger:true,level:-1}),'pursuit');});
test('Spatial effects attenuate with distance and mono centers direction',()=>{const l={x:0,z:0,yaw:0};assert.ok(spatialMix(l,{x:2,z:0}).pan<0);assert.ok(spatialMix(l,{x:40,z:0}).gain<spatialMix(l,{x:2,z:0}).gain);assert.equal(spatialMix(l,{x:20,z:0},24,true).pan,0);assert.equal(spatialMix(l,{x:NaN,z:0}).gain,0);});
test('Footstep materials follow playable ground and real building layers',()=>{const s=foot();assert.equal(surfaceFor(s,w),'stone');s.x=-24.5;s.z=24;assert.equal(surfaceFor(s,w),'wood');s.doors.level=-2;assert.equal(surfaceFor(s,w),'stone');s.doors.level=3;assert.equal(surfaceFor(s,w),'wood');});
