import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeWorld,newState,saveData,readSave,activeTarget,missionText,step,enterExit,blocked} from '../model.mjs';
import {createCampaignState} from '../campaign-entry.mjs';
import {roadState,ROAD_NODES,ROAD_ITEMS,roadNear,roadTarget,reviewRoadAction,commitRoadReview} from '../road-core.mjs';
import {createRoadStorage} from '../road-storage.mjs';
import {createRoadTravel} from '../road-travel.mjs';
// Unit fixtures intentionally set locations/resources. Browser journeys do not.
const world=makeWorld(),state=()=>createCampaignState();
const at=(s,id)=>{const n=ROAD_NODES.find(n=>n.id===id);s.mode='foot';s.speed=0;s.x=n.x;s.z=n.z;};
function act(s,action,save=()=>true){const q=reviewRoadAction(s,action);assert.equal(q.ok,true,q.error);const result=commitRoadReview(s,q,save);assert.equal(result.ok,true,result.error);return q;}
function charter(s){for(const [id,action]of [['guild','accept'],['maps','recover-chart'],['maps','identify-chart'],['glass','craft-signal'],['gate','install'],['guild','report']]){at(s,id);act(s,action);}}
test('A new satchel is additive; ordinary original mission remains selected until requested',()=>{const s=state();assert.equal(s.road.stage,0);assert.equal(s.road.tracking,false);assert.equal(saveData(s).version,2);assert.equal(roadTarget(s),null);});
test('Complete charter has fixed custody, real itinerary, visible repair and one-time rewards',()=>{const s=state();const old=saveData(s);charter(s);assert.equal(s.credits,50);assert.equal(s.road.stage,6);assert.deepEqual(s.road.items,{route:1,seal:1});assert.equal(s.road.receipts.length,6);assert.equal(reviewRoadAction(s,'report').ok,false);assert.equal(s.completed,old.completed);assert.deepEqual([...s.deliveries],old.deliveries);});
for(const id of ROAD_NODES.map(n=>n.id))test('Interaction point is on valid ordinary street ground: '+id,()=>{const s=state();at(s,id);assert.equal(blocked(s.x,s.z,.33,world,s),false);assert.equal(roadNear(s,id),true);});
test('Story objectives change to the next real station rather than remain on an old merchant marker',()=>{const s=state();act(s,'mark:maps');at(s,'guild');act(s,'accept');assert.equal(activeTarget(s,world).id,'maps');at(s,'maps');act(s,'recover-chart');act(s,'identify-chart');assert.equal(activeTarget(s,world).id,'glass');assert.match(missionText(s).title,/craft/i);act(s,'untrack');assert.equal(roadTarget(s),null);});
test('Every story stage survives existing v2 save and normal campaign reconstruction',()=>{let s=state();for(const [id,action]of [['guild','accept'],['maps','recover-chart'],['maps','identify-chart'],['glass','craft-signal'],['gate','install'],['guild','report']]){at(s,id);act(s,action);const data=saveData(s);s=createCampaignState(readSave(JSON.stringify(data),world));assert.deepEqual(saveData(s).road,data.road);}});
test('No purchase can consume, sell or replace bound quest custody',()=>{const s=state();at(s,'guild');act(s,'accept');at(s,'table');for(const id of ['parcel','chart','route','signal','seal'])for(const kind of ['buy','sell'])assert.equal(reviewRoadAction(s,kind+':'+id).ok,false);act(s,'buy:tonic');assert.equal(s.road.items.parcel,1);});
test('Exact buy/sell review does not mutate; confirmed exchanges have integer balances and receipts',()=>{const s=state();s.credits=20;at(s,'table');const before=JSON.stringify(s);const q=reviewRoadAction(s,'buy:tonic');assert.equal(JSON.stringify(s),before);assert.equal(q.after,8);assert.equal(commitRoadReview(s,q,()=>true).ok,true);assert.equal(s.road.items.tonic,1);act(s,'sell:tonic');assert.equal(s.credits,13);assert.equal(s.road.items.tonic,undefined);});
test('Confirming twice cannot duplicate an item or repeat a charge',()=>{const s=state();s.credits=20;at(s,'table');const q=reviewRoadAction(s,'buy:tonic');assert.equal(commitRoadReview(s,q,()=>true).ok,true);const after=JSON.stringify(s);assert.equal(commitRoadReview(s,q,()=>true).ok,false);assert.equal(JSON.stringify(s),after);});
test('Changed offers and changed balances require a fresh review',()=>{const s=state();s.credits=20;at(s,'table');const q=reviewRoadAction(s,'buy:tonic');s.credits++;assert.equal(commitRoadReview(s,q,()=>true).ok,false);const fresh=reviewRoadAction(s,'buy:tonic');assert.equal(commitRoadReview(s,{...fresh,after:999},()=>true).ok,false);});
test('A transaction cannot finish after moving away or entering another floor',()=>{const s=state();s.credits=20;at(s,'table');const q=reviewRoadAction(s,'buy:tonic');s.doors.level=1;assert.equal(commitRoadReview(s,q,()=>true).ok,false);s.doors.level=0;s.x+=10;assert.equal(commitRoadReview(s,q,()=>true).ok,false);});
for(const save of [()=>false,()=>{throw Error('quota');},null])test('No durable save means no inventory or currency mutation',()=>{const s=state();s.credits=20;at(s,'table');const q=reviewRoadAction(s,'buy:tonic'),before=JSON.stringify(s);assert.equal(commitRoadReview(s,q,save).ok,false);assert.equal(JSON.stringify(s),before);});
test('Insufficient money, stock and stack space cannot partially mutate',()=>{const s=state();at(s,'table');for(const action of ['buy:tonic','sell:tonic','craft:tonic'])assert.equal(reviewRoadAction(s,action).ok,false);s.credits=100;s.road.items.tonic=99;assert.equal(reviewRoadAction(s,'buy:tonic').ok,false);assert.equal(s.credits,100);});
test('Workshops consume the reviewed recipe and never invent a quest signal',()=>{const s=state();at(s,'table');s.road.items={herbs:2,linen:1};act(s,'craft:tonic');assert.deepEqual(s.road.items,{tonic:1});at(s,'glass');s.road.items={glass:2,brass:1};act(s,'craft:lens');assert.deepEqual(s.road.items,{lens:1});assert.equal(s.road.stage,0);});
test('Tonic respects existing vitality progression and is not consumed at full health',()=>{const s=state();s.life.attrs.vitality=2;s.health=120;s.road.items.tonic=2;act(s,'use:tonic');assert.equal(s.health,124);assert.equal(s.road.items.tonic,1);assert.equal(reviewRoadAction(s,'use:tonic').ok,false);s.health=0;assert.equal(reviewRoadAction(s,'use:tonic').ok,false);});
test('Unknown and oversized save fields are rejected; stage reconstructs bound custody',()=>{const r=roadState({version:1,stage:4,items:{signal:99,parcel:44,tonic:Infinity,evil:1,herbs:3},receipts:Array(100).fill({id:1,action:'a',summary:'b',balance:0})});assert.deepEqual(r.items,{herbs:3,route:1,signal:1});assert.equal(r.receipts.length,12);assert.equal(roadState({version:2,stage:6}).stage,0);});
test('The expanded save stays below the original maximum length and retains legacy data',()=>{const s=state();charter(s);for(const id of Object.keys(ROAD_ITEMS))if(!ROAD_ITEMS[id].bound)s.road.items[id]=99;s.road.receipts=Array.from({length:12},(_,i)=>({id:i,action:'a'.repeat(79),summary:'b'.repeat(599),balance:100}));const raw=JSON.stringify(saveData(s));assert.ok(raw.length<32768);assert.ok(readSave(raw,world));});
test('Vesperfall visits do not turn a URL into earned rewards or change an active road test',()=>{const s=state();charter(s);at(s,'gate');s.cycle.active={};assert.equal(reviewRoadAction(s,'depart').ok,false);s.cycle.active=null;act(s,'depart');const coins=s.credits;act(s,'returned');assert.equal(s.credits,coins);assert.equal(s.road.returned,true);assert.equal(reviewRoadAction(s,'returned').ok,false);});
test('Local durable writer refuses stale tabs and write failures',()=>{let raw=null;const storage={getItem:()=>raw,setItem:(_,v)=>{raw=v;}};const store=createRoadStorage({storage,key:'k',serialize:JSON.stringify});store.write({a:1});raw='external';assert.throws(()=>store.write({a:2}),/Another tab/);assert.equal(raw,'external');});
test('A cleared storage record is a conflict, not an empty purse to overwrite',()=>{let raw='old';const store=createRoadStorage({storage:{getItem:()=>raw,setItem:()=>assert.fail()},key:'k',initialRaw:'old',serialize:JSON.stringify});raw=null;assert.throws(()=>store.write({}),/Another tab/);});
test('Explicit travel saves, ends XR, then navigates only to a fixed same-origin destination',async()=>{const order=[],session=new EventTarget();session.end=async()=>{order.push('end');session.dispatchEvent(new Event('end'));};const t=createRoadTravel({save:()=>{order.push('save');return true;},getSession:()=>session,navigate:u=>order.push(u),baseURL:'https://v5ma.github.io/leonardos-guild/'});assert.equal((await t.go('vesperfall')).ok,true);assert.deepEqual(order,['save','end','https://v5ma.github.io/vesperfall/?from=vinci']);});
test('Failed saves or failed session shutdown never navigate',async()=>{for(const failure of ['save','end']){const t=createRoadTravel({save:()=>failure!=='save',getSession:()=>({addEventListener(){},removeEventListener(){},end:()=>Promise.reject(Error('no exit'))}),navigate:()=>assert.fail(),baseURL:'https://v5ma.github.io/vesperfall/'});assert.equal((await t.go('vinci')).ok,false);}});
test('Unknown travel and repeated activation cannot navigate to arbitrary destinations',async()=>{let resume;const gate=new Promise(r=>resume=r);let navigations=0;const t=createRoadTravel({save:async()=>{await gate;return true;},getSession:()=>null,navigate:()=>navigations++,baseURL:'https://v5ma.github.io/vesperfall/'});assert.equal((await t.go('https://evil.test')).ok,false);const a=t.go('vinci');assert.equal((await t.go('vinci')).ok,false);resume();await a;assert.equal(navigations,1);});
test('A fresh rider can dismount and complete every charter step using the actual movement/collision model',()=>{
 const s=state();assert.equal(enterExit(s,world),true);assert.equal(s.mode,'foot');
 function walk(x,z){for(let i=0;i<6000;i++){const dx=x-s.x,dz=z-s.z,d=Math.hypot(dx,dz);if(d<.8){for(let j=0;j<45;j++)step(s,world,{},1/60);return;}const a=(Math.atan2(dx,dz)-s.yaw+Math.PI*3)%(Math.PI*2)-Math.PI;step(s,world,{steer:Math.abs(a)<.03?0:-Math.sign(a)*Math.min(1,.18+Math.abs(a)*.7),throttle:Math.abs(a)>.7?0:Math.min(.95,.25+d*.12)},1/60);}assert.fail('Blocked route to '+[x,z]+' from '+[s.x,s.z]);}
 for(const [node,action]of [['guild','accept'],['maps','recover-chart'],['maps','identify-chart'],['glass','craft-signal'],['gate','install'],['guild','report']]){
  const n=ROAD_NODES.find(n=>n.id===node);walk(0,s.z);walk(0,n.z);walk(n.x,n.z);act(s,action);
 }
 assert.equal(s.road.stage,6);assert.ok(s.steps>1000);assert.equal(s.credits,50);
});
