/* Explicit DOM adapter fixtures, not native browser/headset evidence. */
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRoadUI} from '../road-ui.mjs';
import {installVinciReturn} from '../vesperfall-return.mjs';
import {createCampaignState} from '../campaign-entry.mjs';
function documentFixture(){
 class E extends EventTarget {constructor(tag){super();this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attributes={};this.open=false;this.textContent='';}append(...es){this.children.push(...es);for(const e of es)e.parentNode=this;}replaceChildren(...es){this.children=[];this.append(...es);}setAttribute(k,v){this.attributes[k]=v;}focus(){doc.activeElement=this;}showModal(){this.open=true;}close(){this.open=false;this.dispatchEvent(new Event('close'));}}
 const doc={body:new E('body'),createElement:t=>new E(t),getElementById(id){const find=e=>e.id===id?e:e.children.map(find).find(Boolean);return find(this.body);}};return doc;
}
function fixture(t){const before=globalThis.document,doc=documentFixture();globalThis.document=doc;t.after(()=>{if(before===undefined)delete globalThis.document;else globalThis.document=before;});const s=createCampaignState();s.mode='foot';s.x=10.8;s.z=24;s.credits=20;const pauses=[];let fail=false;const ui=createRoadUI({getState:()=>s,playing:()=>true,setPause:p=>pauses.push(p),persist:()=>!fail,onChange(){},travel:{go:async()=>({ok:true})},legacyJournal(){},legacyFrontier(){}});return {doc,s,ui,pauses,fail:()=>{fail=true;},click:id=>doc.getElementById(id).onclick()};}
test('Actual road UI reviews exact goods and cancel defaults to keeping inventory',t=>{const f=fixture(t);f.ui.open('shops');f.click('road-buy-tonic');assert.equal(f.doc.getElementById('road-review').open,true);assert.equal(f.doc.activeElement.id,'road-review-cancel');assert.equal(f.s.credits,20);f.click('road-review-cancel');assert.equal(f.s.credits,20);assert.equal(f.s.road.items.tonic,undefined);});
test('Actual road UI commits one reviewed merchant exchange and shows the receipt',async t=>{const f=fixture(t);f.ui.open('shops');f.click('road-buy-tonic');await f.click('road-review-confirm');assert.equal(f.s.credits,8);assert.equal(f.s.road.items.tonic,1);assert.equal(f.doc.getElementById('road-review').open,false);assert.equal(f.doc.getElementById('road-dialog').open,true);assert.equal(f.s.road.receipts.length,1);});
test('Actual road UI save failure leaves a visible error and no spend',async t=>{const f=fixture(t);f.ui.open('shops');f.click('road-buy-tonic');f.fail();await f.click('road-review-confirm');assert.equal(f.s.credits,20);assert.match(f.doc.getElementById('road-review-status').textContent,/Not completed/);assert.equal(f.doc.getElementById('road-review').open,true);assert.equal(f.doc.getElementById('road-review-confirm').disabled,true);});
test('Actual road UI supports page changes and separate review/main Back operations',t=>{const f=fixture(t);f.ui.open();f.click('road-tab-pack');assert.equal(f.ui.inspect().tab,'pack');f.click('road-tab-shops');f.click('road-buy-tonic');assert.equal(f.ui.close(),true);assert.equal(f.doc.getElementById('road-dialog').open,true);assert.equal(f.ui.close(),true);assert.equal(f.doc.getElementById('road-dialog').open,false);assert.equal(f.ui.close(),false);});
function vesper(){const doc=documentFixture(),host=doc.createElement('section');host.id='pilgrim-rest';doc.body.append(host);const calls=[];let confirm=null;const g={game:{},practice:false,arMode:false,menuSelection:0,checkpoint:{flush:()=>{calls.push('save');return true;}},setPaused:p=>calls.push('pause'),scene:{renderer:{xr:{getSession:()=>null}}},dominionControls:{state:{xrScreen:'saved'},confirm:(a,b,f)=>{confirm=f;},notice:m=>calls.push(m)},xrPanel:{ctx:new Proxy({},{get:()=>()=>{},set:()=>true}),texture:{}},drawMenu(){this.xrMenuRows=Array.from({length:5},(_,i)=>['Original '+i,()=>{}]);this.menuSelection=Math.min(this.menuSelection,4);}};installVinciReturn(g,{document:doc,location:{href:'https://v5ma.github.io/vesperfall/?from=vinci',assign:u=>calls.push(u)}});return {doc,g,calls,confirm:()=>confirm()};}
test('Vesperfall adapter retains original saved-menu rows and adds a real sixth return action',()=>{const f=vesper();f.g.drawMenu();assert.equal(f.g.xrMenuRows.length,6);assert.equal(f.g.xrMenuRows[4][0],'Original 4');assert.match(f.g.xrMenuRows[5][0],/Return to Vinci/);f.g.dominionControls.state.xrScreen='main';f.g.drawMenu();assert.equal(f.g.xrMenuRows.length,5);});
test('Vesperfall return requires explicit confirmation and persists before navigation',async()=>{const f=vesper();f.doc.getElementById('vinci-return').onclick();assert.deepEqual(f.calls,[]);await f.confirm();assert.deepEqual(f.calls,['pause','save','https://v5ma.github.io/leonardos-guild/?journey=return']);});
test('Vesperfall adapter refuses to leave when its authoritative local checkpoint fails',async()=>{const f=vesper();f.g.checkpoint.flush=()=>false;f.g.vinciReturn.ask();await f.confirm();assert.equal(f.calls.some(x=>x.startsWith('https:')),false);assert.match(f.calls.at(-1),/Stayed in Vesperfall/);});
test('Unselected new content does not intercept an existing legacy interaction',t=>{const f=fixture(t);assert.equal(f.ui.interact(),false);f.s.road.tracking=true;assert.equal(f.ui.interact(),true);});

test('Vesperfall return selection survives the original five-row clamp',()=>{const f=vesper();f.g.menuSelection=5;f.g.drawMenu();assert.equal(f.g.menuSelection,5);f.g.drawMenu();assert.equal(f.g.menuSelection,5);assert.match(f.g.xrMenuRows[f.g.menuSelection][0],/Return to Vinci/);});
