/* Explicit model fixtures, not claims of native controller playthroughs. */
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeWorld,newState,saveData,readSave,blocked} from '../model.mjs';
import {doorSites,doorOptions,useDoor,doorTarget,trackDoor,inDoorSpace} from '../doors-core.mjs';
import {STORY_IDS,storyState,storyProgress,storySites,storyOptions,storyPlace,storyClues,useStory,storyOutcomes} from '../stories-core.mjs';
const w=makeWorld();
const state=()=>{const s=newState();s.mode='foot';return s;};
function at(s,id){const q=w.stories.find(q=>q.id===id),p=storyPlace(s,w,q);assert.ok(p);s.x=p.x;s.z=p.z;s.speed=0;s.life.inside=null;s.doors.level=p.level;s.doors.room=[0,3,-2].includes(p.level)?null:p.room;return 'story:'+id;}
function act(s,id,action){return useDoor(s,w,at(s,id),action);}
function lampToInstall(s,route){assert.ok(act(s,'lamplighter','accept').ok);assert.ok(act(s,'lamplighter',route).ok);assert.ok(act(s,'lamplighter','observe').ok);for(const i of route==='roof'?[0,2]:[1])assert.ok(act(s,'lamplighter','shutter:'+i).ok);assert.ok(act(s,'lamplighter','test').ok);}
function ledgerToSettle(s,route){for(const a of['accept',route,'observe','shared-work'])assert.ok(act(s,'ledger',a).ok);}
test('Two authored six-step cases are distinct from the six retained adventures and 49 household jobs',()=>{assert.equal(w.stories.length,2);assert.equal(w.doorAdventures.length,6);assert.equal(w.doorHomes.length,49);for(const q of w.stories){assert.equal(q.steps.length,6);assert.equal(q.places.length,6);assert.ok(q.notes.length>=3);}});
test('Old saves retain all earlier data and initialize cases without starting or rewarding them',()=>{const s=state();s.credits=831;s.doors.homes.workshop=4;s.doors.adventures.survey=2;const old=saveData(s);delete old.doors.stories;const r=newState(readSave(JSON.stringify(old),w));assert.equal(r.credits,831);assert.equal(r.doors.homes.workshop,4);assert.equal(r.doors.adventures.survey,2);assert.equal(storyProgress(r,'lamplighter').stage,0);});
test('Case validator discards unknown fields, unbounded stages and inconsistent route/outcome state',()=>{const r=storyState({version:1,cases:{lamplighter:{stage:100,route:'fly',mask:999,resolution:'money'},ledger:{stage:6,route:null,resolution:'shared'},injected:{stage:6}}});assert.deepEqual(Object.keys(r.cases),[...STORY_IDS]);assert.equal(r.cases.lamplighter.stage,0);assert.equal(r.cases.ledger.stage,1);assert.equal(r.cases.ledger.resolution,null);assert.equal(storyState({version:9}).cases.ledger.stage,0);});
test('Every stage and route has an actual collision-clear station below the original northern gate',()=>{for(const id of STORY_IDS)for(const route of['roof','cellar'])for(let stage=0;stage<6;stage++){const s=state();Object.assign(s.doors.stories.cases[id],{stage,route});at(s,id);assert.ok(inDoorSpace(s,storyPlace(s,w,w.stories.find(q=>q.id===id)),w));assert.equal(blocked(s.x,s.z,.33,w,s,true),false,id+' '+route+' '+stage);assert.ok(s.z<404);}});
test('Story actions use the existing controller nearby chooser and reject remote, riding and wrong-floor calls',()=>{const s=state(),id=at(s,'lamplighter');assert.ok(doorSites(s,w).some(p=>p.id===id));assert.ok(doorOptions(s,w,storySites(s,w)[0]).some(o=>o.id==='accept'));s.x+=20;assert.equal(useStory(s,w,id,'accept').ok,false);at(s,'lamplighter');s.mode='bike';assert.equal(useDoor(s,w,id,'accept').ok,false);s.mode='foot';s.doors.level=2;assert.equal(useStory(s,w,id,'accept').ok,false);at(s,'lamplighter');s.speed=2;assert.equal(useStory(s,w,id,'accept').ok,false);});
test('Rooftop lamp route requires its copied pattern and costs no resources for a mistake',()=>{const s=state();for(const a of['accept','roof','observe'])act(s,'lamplighter',a);const credits=s.credits;assert.equal(act(s,'lamplighter','test').ok,false);assert.equal(storyProgress(s,'lamplighter').stage,3);assert.equal(s.credits,credits);act(s,'lamplighter','shutter:0');act(s,'lamplighter','shutter:2');assert.ok(act(s,'lamplighter','test').ok);assert.equal(storyProgress(s,'lamplighter').mask,5);});
test('Cellar route uses a different station, pattern and retained evidence',()=>{const s=state();for(const a of['accept','cellar','observe'])act(s,'lamplighter',a);assert.ok(storyClues(s,w.stories[0]).at(-1).includes('CENTER open'));act(s,'lamplighter','shutter:1');assert.ok(act(s,'lamplighter','test').ok);assert.equal(storyProgress(s,'lamplighter').mask,2);});
test('Both lamp colors persist as visible outcomes before the physical return pays once',()=>{for(const color of['amber','ivory']){const s=state();lampToInstall(s,'roof');act(s,'lamplighter',color);assert.equal(storyOutcomes(s,w).lamp,color);assert.equal(s.credits,0);assert.ok(act(s,'lamplighter','report').ok);assert.equal(s.credits,60);assert.equal(s.life.xp,170);assert.equal(useStory(s,w,'story:lamplighter','report').ok,false);assert.equal(s.credits,60);}});
test('Ledger conclusions require copied independent evidence; wrong accusations do not advance or charge',()=>{const s=state();for(const a of['accept','cellar','observe'])act(s,'ledger',a);assert.equal(act(s,'ledger','theft').ok,false);assert.equal(act(s,'ledger','double-pay').ok,false);assert.equal(storyProgress(s,'ledger').stage,3);assert.equal(s.credits,0);assert.ok(act(s,'ledger','shared-work').ok);});
test('Both peaceful ledger endings persist with equal one-time rewards and no forced combat',()=>{for(const route of['roof','cellar'])for(const ending of['credit','shared']){const s=state();ledgerToSettle(s,route);act(s,'ledger',ending);assert.equal(storyOutcomes(s,w).ledger,ending);assert.equal(s.credits,0);act(s,'ledger','report');assert.equal(s.credits,55);assert.equal(s.life.xp,160);assert.equal(s.doors.defeated.length,0);assert.equal(useStory(s,w,'story:ledger','report').ok,false);}});
test('Every partial story step round-trips through the original save key without paying or changing old quests',()=>{for(const id of STORY_IDS){const s=state(),actions=id==='lamplighter'?['accept','roof','observe','shutter:0','shutter:2','test','amber','report']:['accept','cellar','observe','shared-work','shared','report'];for(const a of actions){act(s,id,a);const r=newState(readSave(JSON.stringify(saveData(s)),w));assert.deepEqual(r.doors.stories,s.doors.stories);assert.deepEqual(r.doors.tracked,s.doors.tracked);assert.equal(r.credits,s.credits);assert.equal(r.mission,0);assert.equal(r.doors.level,0);}}});
test('Story tracking is observation only and chooses a doorway or stair rather than moving the actor',()=>{const s=state(),before=[s.x,s.z,s.credits];assert.ok(trackDoor(s,w,'story','ledger'));const target=doorTarget(s,w);assert.ok(Number.isFinite(target.x)&&Number.isFinite(target.z));assert.deepEqual([s.x,s.z,s.credits],before);assert.equal(trackDoor(s,w,'story','fake'),false);});
test('Stale actions, invented shutter indices and repeated confirmation cannot skip stages',()=>{const s=state();act(s,'lamplighter','accept');assert.equal(act(s,'lamplighter','accept').ok,false);act(s,'lamplighter','roof');act(s,'lamplighter','observe');assert.equal(act(s,'lamplighter','shutter:33').ok,false);assert.equal(storyProgress(s,'lamplighter').mask,0);});
test('Story updates and puzzle toggles do not add automatic sound events or repeatable rewards',()=>{const s=state();lampToInstall(s,'cellar');act(s,'lamplighter','amber');act(s,'lamplighter','report');ledgerToSettle(s,'cellar');act(s,'ledger','shared');act(s,'ledger','report');assert.equal(s.events.length,0);assert.equal(s.credits,115);assert.equal(s.life.xp,330);});
