/* Explicit state fixtures for the authored activity graph; not native replays. */
import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeWorld,newState,saveData,readSave,blocked,step} from '../model.mjs';
import {STREET_SITES,STREET_JOBS,STREET_MAP,JOB_MAP,streetState,streetSave,currentSite,work,nearby,notes} from '../street-core.mjs';
const w=makeWorld();
function ready(){const s=newState();s.mode='foot';s.speed=0;s.life.flags.garden=s.life.flags.lantern=true;s.life.quests.pigments=5;s.life.partner='isabella';s.life.aura=7;return s;}
function approach(s,p){s.life.inside=p.inside||null;for(const radius of[.6,1,1.7,2.4])for(let i=0;i<32;i++){s.x=p.x+Math.cos(i*Math.PI/16)*radius;s.z=p.z+Math.sin(i*Math.PI/16)*radius;if(!blocked(s.x,s.z,.33,w,s)&&nearby(s,w)?.id===p.id)return true;}return false;}
function perform(s,j){for(let n=0;n<j.sites.length;n++){const p=currentSite(s,j);assert.ok(approach(s,p),p.id);const acts=n<j.sites.length-1?['continue']:j.answer?j.answer:j.kind==='palette'?[j.options[1]]:j.kind==='lantern'?['read']:['continue'];for(const a of acts){const r=work(s,w,j.id,a);assert.ok(r.ok,j.id+': '+r.text);}}}
test('22 activities have unique identities, complete place references and accessible interactions',()=>{assert.equal(STREET_JOBS.length,22);assert.equal(new Set(STREET_JOBS.map(j=>j.id)).size,22);const s=ready();for(const p of STREET_SITES)assert.ok(approach(s,p),p.id+' has a walkable unambiguous approach');for(const j of STREET_JOBS)assert.ok(j.sites.every(id=>STREET_MAP.has(id)));});
test('All 22 encounter rules complete at their correct place, floor, prerequisites and inputs',()=>{const s=ready(),old=JSON.stringify(s.life.quests),cash=s.credits,xp=s.life.xp;for(const j of STREET_JOBS)perform(s,j);assert.equal(s.street.done.length,22);assert.equal(s.credits,cash+STREET_JOBS.reduce((a,j)=>a+j.coins,0));assert.equal(s.life.xp,xp+STREET_JOBS.reduce((a,j)=>a+j.xp,0));assert.equal(JSON.stringify(s.life.quests),old);assert.equal(s.completed,false);assert.equal(notes(s).length,22);});
test('Completed encounters survive reload without repeat payouts or clearing old quests',()=>{const s=ready();s.life.quests.ink=3;s.credits=77;s.completed=true;s.defeated=true;s.folio=true;perform(s,JOB_MAP.get('cart'));const old=saveData(s),r=newState(readSave(JSON.stringify(old),w));assert.equal(r.completed,true);assert.equal(r.life.quests.ink,3);assert.deepEqual(r.street.done,['cart']);r.mode='foot';approach(r,STREET_MAP.get('cart'));const xp=r.life.xp,cash=r.credits;assert.equal(work(r,w,'cart','wheel').ok,false);assert.equal(r.life.xp,xp);assert.equal(r.credits,cash);});
test('Old v0.3 saves initialize empty street state without loss of progress or rewards',()=>{const s=ready();s.life.quests.ink=3;s.credits=321;const old=saveData(s);delete old.street;const r=newState(readSave(JSON.stringify(old),w));assert.equal(r.credits,321);assert.equal(r.life.quests.ink,3);assert.equal(r.street.done.length,0);});
test('Wrong actions and reset do not charge money or create rewards',()=>{const s=ready(),j=JOB_MAP.get('cart');approach(s,currentSite(s,j));assert.equal(work(s,w,j.id,'wheel').ok,false);assert.equal(s.street.sequence.length,0);assert.ok(work(s,w,j.id,'brace').ok);assert.ok(work(s,w,j.id,'reset').ok);assert.equal(s.street.sequence.length,0);assert.equal(s.credits,0);assert.equal(s.life.xp,0);assert.equal(s.street.done.length,0);});
test('A valid action fails remotely, while riding, on the wrong floor or behind a locked gate',()=>{const s=ready();s.x=0;s.z=-6;assert.equal(work(s,w,'cart','brace').ok,false);approach(s,STREET_MAP.get('cart'));s.mode='bike';assert.equal(work(s,w,'cart','brace').ok,false);s.mode='foot';s.life.inside='inn';assert.equal(work(s,w,'cart','brace').ok,false);approach(s,STREET_MAP.get('garden-work'));s.life.flags.garden=false;assert.equal(work(s,w,'gardenbench','clean').ok,false);});
test('Lantern observations need the learned ability and its active effect on the correct floor',()=>{const s=ready();approach(s,STREET_MAP.get('cellar-sign'));s.life.flags.lantern=false;assert.equal(work(s,w,'marks','read').ok,false);s.life.flags.lantern=true;s.life.aura=0;assert.equal(work(s,w,'marks','read').ok,false);s.life.aura=3;assert.ok(work(s,w,'marks','read').ok);assert.ok(s.street.done.includes('marks'));});
test('Investigation requires both discoveries and the evidence-based report',()=>{const s=ready(),j=JOB_MAP.get('seal');for(let i=0;i<3;i++){approach(s,currentSite(s,j));assert.ok(work(s,w,j.id,'continue').ok);}approach(s,currentSite(s,j));assert.equal(work(s,w,j.id,'accuse the apprentice').ok,false);assert.equal(s.street.done.length,0);assert.ok(work(s,w,j.id,'report the wrong address').finished);});
test('Recipe requires gathered ingredients in sequence and produces an actual restorative result',()=>{const s=ready(),j=JOB_MAP.get('tonic');approach(s,currentSite(s,j));assert.equal(work(s,w,j.id,'water').ok,false);s.health=17;perform(s,j);assert.equal(s.health,100);assert.ok(s.street.done.includes('tonic'));});
test('Music has two distinct playable written sequences without requiring an audio device',()=>{const a=JOB_MAP.get('tune'),b=JOB_MAP.get('innmusic');assert.notDeepEqual(a.answer,b.answer);const s=ready();perform(s,a);perform(s,b);assert.equal(s.street.done.length,2);});
test('Palette choices are saved; optional outings require an existing adult partner',()=>{const s=ready();perform(s,JOB_MAP.get('exhibition'));assert.equal(s.street.choices.exhibition,'cool river blue');assert.equal(streetState(streetSave(s.street)).choices.exhibition,'cool river blue');approach(s,STREET_MAP.get('outing'));s.life.partner=null;assert.equal(work(s,w,'walk','continue').ok,false);});
test('Invalid state is bounded, ignores foreign identifiers and discards half-entered puzzles',()=>{const s=streetState({version:1,done:['unknown','cart','cart'],progress:{cart:900,foreign:3},discovered:['unknown','cart'],choices:{exhibition:'javascript:alert(1)'},sequence:['brace'],clock:Infinity});assert.deepEqual(s.done,['cart']);assert.equal(s.progress.cart,1);assert.equal(s.progress.foreign,undefined);assert.deepEqual(s.discovered,['cart']);assert.equal(s.choices.exhibition,undefined);assert.equal(s.sequence.length,0);assert.equal(s.clock,0);});
test('Walking by a discovered activity does not start it, remove supplies or award progress',()=>{const s=ready();approach(s,STREET_MAP.get('cart'));const cash=s.credits;step(s,w,{},1/60);assert.ok(s.street.discovered.includes('cart'));assert.equal(s.street.done.length,0);assert.deepEqual(s.street.progress,{});assert.equal(s.credits,cash);});
