import {clearShot,coverObject} from '../resonance-core.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {makeWorld,step,enterExit,saveData,readSave,blocked,activeTarget} from '../model.mjs';
import {createCampaignState} from '../campaign-entry.mjs';
import {enterBadlands,leaveBadlands,frontierBlocked,frontierSight,TRAIL_NODES,TRAIL_EDGES,MONSTERS} from '../frontier-core.mjs';
import {vaultState,nearVaultNode,reviewVaultAction,commitVaultAction,vaultInventory,vaultTarget} from '../vault-core.mjs';
import {VAULT_LAYOUT,VAULT_NODES,VAULT_WALLS,opticalOpen,serviceOpen,vaultBlocked} from '../vault-data.mjs';
const world=makeWorld();
function act(s,a,persist=()=>true){const q=reviewVaultAction(s,a);assert.equal(q.ok,true,q.error+' / '+a);const r=commitVaultAction(s,q,persist);assert.equal(r.ok,true,r.error);return r;}
// Labelled unit fixtures: placements here test rejection rules, not playthroughs.
function fixture(node='bench'){const s=createCampaignState();s.mode='foot';s.frontier.zone='badlands';const n=VAULT_NODES.find(n=>n.id===node);s.x=n.x;s.z=n.z;return s;}
function at(s,node){const n=VAULT_NODES.find(n=>n.id===node);s.x=n.x;s.z=n.z;s.speed=0;}
test('New and old adventures have an additive dormant Vault record and unchanged save key/version',()=>{const s=createCampaignState();assert.equal(s.vault.accepted,false);assert.equal(vaultTarget(s),null);assert.equal(saveData(s).version,2);assert.equal(s.mode,'bike');assert.equal(s.quarter.active,false);assert.equal(s.frontier.zone,'town');});
test('Unknown, malformed and oversized Vault state cannot create tool quantities or unsupported layouts',()=>{assert.equal(vaultState({version:1,layout:'wrong',accepted:true}).accepted,false);const v=vaultState({version:1,layout:VAULT_LAYOUT,accepted:true,mirror:99,lens:'duplicated',weight:'negative',reported:true,notes:Array(100).fill('bad'),revision:-1});assert.equal(v.mirror,0);assert.deepEqual(v.notes,[]);assert.equal(v.reported,false);assert.equal(v.lens,'pack');assert.equal(v.weight,'pack');});
test('Every named mechanism has a collision-free approach and cannot be used while riding or jumping',()=>{for(const n of VAULT_NODES){const s=fixture(n.id);assert.equal(frontierBlocked(s.x,s.z,.33,s),false,n.id);assert.equal(nearVaultNode(s)?.id,n.id);s.mode='bike';assert.equal(nearVaultNode(s),null);s.mode='foot';s.lift=1;assert.equal(nearVaultNode(s),null);}});
test('The original Cinder Hollow trails are not cut by the new survey masonry',()=>{for(const [a,b]of TRAIL_EDGES){const [ax,az]=TRAIL_NODES[a],[bx,bz]=TRAIL_NODES[b];for(let t=0;t<=1;t+=.02)assert.equal(vaultBlocked(ax+(bx-ax)*t,az+(bz-az)*t,.33),false);}});
test('A loan has exactly one lens and one weight, no fee, and cannot be accepted twice',()=>{const s=fixture();act(s,'accept');assert.equal(s.credits,0);assert.equal(vaultInventory(s.vault).length,2);assert.equal(reviewVaultAction(s,'accept').ok,false);});
test('Wrong tool leaves the mechanism and custody unchanged, with an actionable explanation',()=>{const s=fixture();act(s,'accept');act(s,'equip:weight');at(s,'emitter');const before=JSON.stringify(s.vault),q=reviewVaultAction(s,'emitter');assert.equal(q.ok,false);assert.match(q.error,/inspection lens/);assert.equal(JSON.stringify(s.vault),before);});
test('A socket transfers the one tool, and a second use retrieves that same tool',()=>{const s=fixture();act(s,'accept');at(s,'emitter');act(s,'emitter');assert.equal(s.vault.lens,'emitter');assert.equal(reviewVaultAction(s,'equip:lens').ok,false);act(s,'emitter');assert.equal(s.vault.lens,'pack');assert.equal(s.vault.tool,'lens');});
test('The optical gate follows all three actual puzzle conditions, not a visited waypoint',()=>{const s=fixture();act(s,'accept');at(s,'mirror');act(s,'mirror');assert.equal(opticalOpen(s.vault),false);at(s,'emitter');act(s,'emitter');act(s,'equip:weight');at(s,'shutter');act(s,'shutter');assert.equal(opticalOpen(s.vault),true);assert.equal(frontierBlocked(370,25,.33,s),false);act(s,'shutter');assert.equal(opticalOpen(s.vault),false);assert.equal(frontierBlocked(370,25,.33,s),true);});
test('The service route reuses the single weight and does not require the lens or inscription',()=>{const s=fixture();act(s,'accept');act(s,'equip:weight');at(s,'service');act(s,'service');assert.equal(serviceOpen(s.vault),true);assert.equal(opticalOpen(s.vault),false);assert.equal(frontierBlocked(350,36,.33,s),false);at(s,'shutter');assert.match(reviewVaultAction(s,'shutter').error,/only counterweight/);});
test('Clues require the carried lens; optional caretaker evidence has its own custody',()=>{const s=fixture();act(s,'accept');at(s,'inscription');act(s,'inspect');assert.deepEqual(s.vault.notes,['inscription']);at(s,'account');act(s,'account');assert.deepEqual(s.vault.notes,['inscription','account']);at(s,'emitter');act(s,'emitter');at(s,'inscription');assert.equal(reviewVaultAction(s,'inspect').ok,false);});
test('Objects cannot be used through the closed wall or from the far side of a gate',()=>{const s=fixture();act(s,'accept');s.x=345;s.z=19.1;assert.notEqual(nearVaultNode(s)?.id,'inscription');s.x=369;s.z=28;assert.notEqual(nearVaultNode(s)?.id,'latch');});
for(const save of [()=>false,()=>{throw Error('quota');},null])test('Failed durable write leaves the loan and balance untouched',()=>{const s=fixture(),q=reviewVaultAction(s,'accept'),before=JSON.stringify(s);assert.equal(commitVaultAction(s,q,save).ok,false);assert.equal(JSON.stringify(s),before);});
test('Review is pure; stale review, changed location and double confirmation cannot duplicate actions',()=>{const s=fixture(),before=JSON.stringify(s),q=reviewVaultAction(s,'accept');assert.equal(JSON.stringify(s),before);s.x+=20;assert.equal(commitVaultAction(s,q,()=>true).ok,false);at(s,'bench');assert.equal(commitVaultAction(s,q,()=>true).ok,true);assert.equal(commitVaultAction(s,q,()=>true).ok,false);});
test('Inside latch makes both returns permanent and survives normal save reconstruction',()=>{const s=fixture();act(s,'accept');at(s,'latch');act(s,'latch');assert.ok(opticalOpen(s.vault)&&serviceOpen(s.vault));const fresh=createCampaignState(readSave(JSON.stringify(saveData(s)),world));assert.ok(opticalOpen(fresh.vault)&&serviceOpen(fresh.vault));assert.equal(fresh.frontier.zone,'town');});
test('Reward requires a physical town report, respects capacity, and never pays twice',()=>{const s=fixture();act(s,'accept');at(s,'record');act(s,'record');assert.equal(reviewVaultAction(s,'report').ok,false);s.frontier.zone='town';s.x=-8;s.z=3;s.credits=10000000;assert.equal(reviewVaultAction(s,'report').ok,false);s.credits=0;act(s,'report');assert.equal(s.credits,40);assert.equal(reviewVaultAction(s,'report').ok,false);const saved=createCampaignState(readSave(JSON.stringify(saveData(s)),world));assert.equal(saved.vault.reported,true);assert.equal(saved.credits,40);});
test('Survey location cannot authorize town trading or mutate original story custody',()=>{const s=fixture(),road=structuredClone(s.road),quarter=saveData(s).quarter;act(s,'accept');at(s,'record');act(s,'record');assert.deepEqual(s.road,road);assert.deepEqual(saveData(s).quarter,quarter);assert.deepEqual([...s.deliveries],[]);});
// The two full model journeys below use only original movement, collision and
// gate actions. No assignment to actor coordinates, money, health or quest flags.
function walker(s){
 const walk=(x,z)=>{for(let i=0;i<6000;i++){const dx=x-s.x,dz=z-s.z,d=Math.hypot(dx,dz);if(d<.55){for(let j=0;j<45;j++)step(s,world,{},1/60);return;}const a=(Math.atan2(dx,dz)-s.yaw+Math.PI*3)%(Math.PI*2)-Math.PI;step(s,world,{steer:Math.abs(a)<.025?0:-Math.sign(a)*Math.min(1,.18+Math.abs(a)*.7),throttle:Math.abs(a)>.55?0:Math.min(.95,.2+d*.1)},1/60);}assert.fail('Blocked actual route to '+[x,z]+' from '+[s.x,s.z]);};
 return (...points)=>{for(const [x,z]of points)walk(x,z);};
}
for(const route of ['optical','service'])test('Ordinary movement completes '+route+' route, opens shortcut, returns to Vinci and reports once',()=>{
 const s=createCampaignState(),walk=walker(s);assert.equal(enterExit(s,world),true);walk([0,3],[-8,3]);act(s,'accept');assert.equal(activeTarget(s,world).id,'vault-gate');walk([0,3],[0,-17]);assert.equal(enterBadlands(s).ok,true);walk([320,20],[324,25],[331,25]);
 if(route==='optical'){
  walk([334,25],[334,14],[345,14]);act(s,'inspect');walk([354,14],[363,14]);act(s,'account');walk([362,25],[350,25],[339,25]);act(s,'emitter');act(s,'equip:weight');walk([347,25],[347,28]);act(s,'shutter');walk([347,25],[362,25],[362,28]);act(s,'mirror');assert.equal(opticalOpen(s.vault),true);walk([362,25],[374,25],[381,25]);
 }else{
  act(s,'equip:weight');walk([336,25],[336,36],[347,36]);act(s,'service');walk([355,36],[382,36],[382,25]);assert.equal(opticalOpen(s.vault),false);
 }
 act(s,'record');walk([374,25],[374,28]);act(s,'latch');walk([374,25],[324,25],[320,20],[300,20]);assert.equal(leaveBadlands(s).ok,true);walk([0,3],[-8,3]);act(s,'report');assert.equal(s.credits,40);assert.equal(s.vault.reported,true);assert.equal(s.health,100);assert.equal(s.frontier.defeated.length,0);assert.equal(reviewVaultAction(s,'report').ok,false);
 const recovered=createCampaignState(readSave(JSON.stringify(saveData(s)),world));assert.deepEqual(recovered.vault,s.vault);assert.equal(recovered.credits,40);
});
test('Real application routes keyboard, touch and existing XR/Xbox interaction to the survey',()=>{const s=readFileSync(new URL('../app.mjs',import.meta.url),'utf8');assert.match(s,/vaultUI\?\.interact\(\)/);assert.match(s,/createVaultUI/);assert.match(s,/vaultUI\?\.drawMap/);assert.match(s,/vaultTitle\.disabled=false/);assert.match(s,/vaultUI:.*inspect/);const inv=readFileSync(new URL('../road-ui.mjs',import.meta.url),'utf8');assert.match(inv,/vaultInventory\(s.vault\)/);});

test('Sight, shots and cover use the same actual Vault barriers as movement',()=>{const s=fixture();act(s,'accept');const a={x:367,z:25},b={x:373,z:25};assert.equal(frontierSight(a,b,s),false);assert.equal(clearShot(s,world,a,b),false);at(s,'latch');act(s,'latch');assert.equal(frontierSight(a,b,s),true);assert.equal(clearShot(s,world,a,b),true);s.x=369;s.z=20.5;assert.ok(coverObject(s,world));});
