"""Reproducible public-domain art intake. Network is BUILD TIME ONLY.
Only named models from the creators' free Standard editions are redistributed.
No Blender scripts or executable content from archives are run.
"""
from pathlib import Path, PurePosixPath
import hashlib, json, urllib.request, zipfile, io, os
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets'/'quaternius';OUT.mkdir(parents=True,exist_ok=True)
PACKS={
 'props':{'url':'https://opengameart.org/sites/default/files/fantasy_props_megakitstandard.zip','page':'https://quaternius.com/packs/fantasypropsmegakit.html','sha256':'0bc1e5843c9f245c44bda82f97f738b09f88fe51bb34d2a69a7847a969f868e3','folder':'Exports/glTF/','models':['Stall_Empty','Stall_Cart_Empty','Barrel','Barrel_Apples','Bookcase_2','BookGroup_Medium_1','Workbench','Shelf_Small_Bottles','Cauldron','Chair_1','Table_Large','CandleStick_Triple','Lantern_Wall','FarmCrate_Apple','FarmCrate_Carrot','Pot_1','Potion_1','Scroll_1','Anvil_Log','Whetstone','Bench']},
 'village':{'url':'https://opengameart.org/sites/default/files/medieval_village_megakitstandard.zip','page':'https://quaternius.com/packs/medievalvillagemegakit.html','sha256':'58c3e1b9713ee85749ade230c36e1195af5d96951435532b4411e993b46387bd','folder':'glTF/','models':['Wall_Plaster_Straight','Wall_Plaster_Window_Wide_Round','Wall_Plaster_Door_Round','Wall_UnevenBrick_Straight','Roof_RoundTiles_6x8','Roof_Front_Brick6','Prop_Vine1','Prop_Vine4','Prop_Chimney','Balcony_Cross_Straight','Door_1_Round']}}
def digest(b):return hashlib.sha256(b).hexdigest()
def fetch(url):
 with urllib.request.urlopen(urllib.request.Request(url,headers={'User-Agent':'SVGN-Guild-Asset-Build/1.0'}),timeout=120) as r:return r.read(220000000)
def blob(archive,p):
 p=PurePosixPath(p)
 if '..' in p.parts or p.is_absolute():raise ValueError('Unsafe archive path')
 return archive.read(str(p))
manifest={'license':'CC0-1.0','creator':'Quaternius','purpose':'Curated redistributable assets for the existing Leonardo city. No paid Source/Pro models or shaders.','textures':'Shared 512px PNG maps; sRGB base colors, linear normal and ORM data. No images generated by AI.','packs':{},'models':{},'files':{}}
for kit,pack in PACKS.items():
 cache=os.environ.get('GUILD_ART_CACHE');cached=Path(cache)/(kit+'.zip') if cache else None
 raw=cached.read_bytes() if cached and cached.exists() else fetch(pack['url'])
 assert digest(raw)==pack['sha256'],f'Upstream archive changed: inspect deliberately ({kit})'
 path=OUT/kit;path.mkdir(exist_ok=True)
 with zipfile.ZipFile(io.BytesIO(raw)) as z:
  license=z.read('License_Standard.txt');assert b'CC0 1.0' in license;(path/'LICENSE.txt').write_bytes(license)
  manifest['packs'][kit]={k:pack[k] for k in ['url','page','sha256']}
  for name in pack['models']:
   full=pack['folder']+name+'.gltf';original=z.read(full);gltf=json.loads(original)
   assert not gltf.get('skins') and all('matrix' not in n and 'rotation' not in n and 'translation' not in n and 'scale' not in n for n in gltf['nodes']),name
   bufferHashes={}
   for buff in gltf.get('buffers',[]):
    uri=buff['uri'];data=blob(z,pack['folder']+uri);assert len(data)==buff['byteLength'];(path/uri).write_bytes(data);bufferHashes[uri]=digest(data)
   for image in gltf.get('images',[]):
    uri=image['uri'];target=path/uri
    if not target.exists():
     source=blob(z,pack['folder']+uri if pack['folder']+uri in z.namelist() else 'Textures/'+uri);im=Image.open(io.BytesIO(source));im.thumbnail((512,512),Image.Resampling.LANCZOS)
     if 'A' not in im.getbands():im=im.convert('RGB')
     im.save(target,format='PNG',optimize=True)
   for mat in gltf.get('materials',[]):
    tex=mat.get('pbrMetallicRoughness',{}).get('metallicRoughnessTexture')
    if tex and '_ORM' in gltf['images'][gltf['textures'][tex['index']]['source']]['name']:mat['occlusionTexture']={'index':tex['index'],'strength':.65}
   gltf.setdefault('asset',{})['copyright']='Quaternius / CC0-1.0; see ASSET-REGISTER.json'
   (path/(name+'.gltf')).write_text(json.dumps(gltf,separators=(',',':')))
   primitives=[p for m in gltf['meshes'] for p in m['primitives']];positions=[gltf['accessors'][p['attributes']['POSITION']] for p in primitives]
   manifest['models'][kit+'/'+name]={'sourceFile':full,'upstreamModelSHA256':digest(original),'bufferSHA256':bufferHashes,'path':f'assets/quaternius/{kit}/{name}.gltf','triangles':sum(gltf['accessors'][p['indices']]['count']//3 for p in primitives),'min':[min(a['min'][i] for a in positions) for i in range(3)],'max':[max(a['max'][i] for a in positions) for i in range(3)]}
for path in sorted(OUT.rglob('*')):
 if path.is_file():manifest['files'][str(path.relative_to(ROOT))]={'sha256':digest(path.read_bytes()),'bytes':path.stat().st_size}
manifest['totalBytes']=sum(x['bytes'] for x in manifest['files'].values())
(ROOT/'ASSET-REGISTER.json').write_text(json.dumps(manifest,indent=2))
vendor=ROOT/'vendor';assert "const REVISION = '177'" in (vendor/'three.core.js').read_text()
receipts={}
for filename,url in [('GLTFLoader.js','https://raw.githubusercontent.com/mrdoob/three.js/r177/examples/jsm/loaders/GLTFLoader.js'),('BufferGeometryUtils.js','https://raw.githubusercontent.com/mrdoob/three.js/r177/examples/jsm/utils/BufferGeometryUtils.js'),('THREE-LICENSE.txt','https://raw.githubusercontent.com/mrdoob/three.js/r177/LICENSE')]:
 data=fetch(url);text=data.decode().replace("from 'three'","from './three.module.js'").replace("from '../utils/BufferGeometryUtils.js'","from './BufferGeometryUtils.js'")
 (vendor/filename).write_text(text);receipts[filename]={'url':url,'upstreamSHA256':digest(data),'modifiedSHA256':digest(text.encode()),'modification':'Relative imports to existing local pinned Three.js; otherwise unchanged.'}
(vendor/'gltf-provenance.json').write_text(json.dumps(receipts,indent=2))
print(f'Prepared {len(manifest["models"])} named CC0 models and shared textures: {manifest["totalBytes"]:,} bytes.')
