/* Pure HTML view fragments used by the existing Nearby dialog. */
import {GEARS,BRAKES,FINISHES,ROAD_GATES,bikeSpecification} from './cycle-core.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderCycleBench(s){
 const c=s.cycle,spec=bikeSpecification(s),parts=[['gear','Gearing',GEARS],['brake','Brake lever',BRAKES],['finish','Frame enamel',FINISHES]];
 return `<p>Your ${esc(s.life.bike)} bicycle keeps its identity. Fit owned parts free; return to the original setup at any time outside an active test. The carriage is unaffected.</p><div class="cycle-spec"><b>${(spec.top*3.6).toFixed(1)} km/h</b><span>pedal limit</span><b>${(spec.boost*3.6).toFixed(1)} km/h</b><span>boost limit</span><b>${spec.accel.toFixed(1)}</b><span>acceleration</span></div><p>Sprint gears pull away faster but lower top speed. Cruise gears trade acceleration for speed. The long-pull lever improves the dedicated Brake action: Z on keyboard, or hold Brake on touch. Space still hops.</p>`+
 parts.map(([kind,title,items])=>`<section class="cycle-parts"><h3>${title}</h3><div class="city-options">`+Object.entries(items).map(([id,p])=>`<button data-city-action="${kind}:${id}" ${(c.active||c.pending)?'disabled':''}><small>${c[kind]===id?'FITTED':c.owned[kind].includes(id)?'OWNED / REFIT FREE':p.price+' FLORINS'}</small><strong>${p.color?`<i class="cycle-swatch" style="background:${p.color}"></i>`:''}${p.name}</strong><span>${kind==='gear'?`Acceleration ${Math.round(p.accel*100)}% / speed ${Math.round(p.top*100)}%`:kind==='brake'?`Brake strength ${Math.round(p.rate*100)}%`:'Visible on your bicycle and the workshop display'}</span></button>`).join('')+'</div></section>').join('')+
 `<h3>Bartolo's optional road test</h3><p>Ride five marked stages on the existing central road, then stop in the final ring. There is no entry fee, forced deadline or race against traffic. Return here for a one-time 40 XP / 25 florins. Later runs record a personal best only. Damage and old missions behave normally.</p>`+
 (c.pending?`<p>Completed: ${c.pending.seconds.toFixed(1)} seconds. Report before changing parts.</p><button data-city-action="report">Report the completed road test</button>`:c.active?'<p>Your test is marked outside. Close the menu, mount your bicycle and follow the rings.</p>':'<button data-city-action="start">Mark a road test / no entry fee</button>')+
 '<button data-city-tab="roadtest">Road test progress and cancellation</button>';
}
export function renderRoadTest(s){const c=s.cycle;
 return `<p>An optional test of your actual bicycle setup, not a fast-travel route. Start at Bartolo's tuning bench after A Better Fit. Time starts when you ride north through the first ring, not while walking back to your parked bicycle.</p><p>${c.best===null?'No best time yet.':`Personal best: ${c.best.toFixed(1)} seconds.`} ${c.active?`Active time: ${c.active.seconds.toFixed(1)} seconds.`:''}</p><ol class="cycle-gates">`+ROAD_GATES.map((g,i)=>`<li class="${c.active?.gate===i?'current':''}">${g.name}${c.active?.gate>i?' / passed':''}</li>`).join('')+'</ol>'+ (c.pending?'<p>Your clean stop is recorded. Ride back and report inside Bartolo\'s shop.</p>':'')+(c.active?'<button data-cycle-cancel>Cancel this attempt / no penalty</button>':'')+'<button data-city-route="service:cycleworks">Mark Bartolo\'s open shop doorway</button>';
}
