/* Cinder Hollow: original bounded region layer, no reference-game assets.
 * One renderer, reversible visibility, seven actors and cached static geometry. */
import * as T from './vendor/three.module.js';
import {Batch,unit,label} from './art.mjs';
import {createPersonRig,createActorFade} from './character-rig.mjs';
import {animatePerson,inspectMotion} from './character-motion.mjs';
import {createCameraSafety} from './camera-safety.mjs';
import {FRONTIER_SITES,FRONTIER_SOLIDS,MONSTERS,CAMP,TOWN_GATE,frontierTarget,frontierHeight,TRAIL_NODES,TRAIL_EDGES} from './frontier-core.mjs';
export function createFrontierArt({scene,camera,renderer,m,heightAt}){
 const root=new T.Group();root.name='Cinder Hollow';root.visible=false;scene.add(root);
 const townGate=new T.Group();townGate.name='Expedition gate';townGate.position.set(TOWN_GATE.x,heightAt(TOWN_GATE.x,TOWN_GATE.z),TOWN_GATE.z);scene.add(townGate);
 function arch(parent,x,y,z,text){const b=new Batch();for(const sign of[-1,1]){b.box(x+sign*3.5,y+1.8,z,1,3.6,1.2,'#808177');b.box(x+sign*3.5,y+3.6,z,1.3,.3,1.5,'#b9aa89');}b.box(x,y+4,z,8.3,.4,1,'#89765f');b.finish(parent,m.trim,'Open region arch');return label(parent,text,x,y+3,z,4.3,.85,0,'#385253');}
 arch(townGate,0,0,0,'CINDER HOLLOW\nX / EXPEDITIONS');
 const geo=new T.PlaneGeometry(196,200,40,40);geo.rotateX(-Math.PI/2);geo.translate(300,0,100);const v=geo.attributes.position;for(let i=0;i<v.count;i++)v.setY(i,frontierHeight(v.getX(i),v.getZ(i))-.09);geo.computeVertexNormals();root.add(new T.Mesh(geo,new T.MeshStandardMaterial({color:'#53615e',roughness:1})));
 const paths=new Batch(),stone=new Batch(),grass=new Batch(),wood=new Batch();
 for(const [ai,bi] of TRAIL_EDGES){const [x,z]=TRAIL_NODES[ai],[xx,zz]=TRAIL_NODES[bi],dx=xx-x,dz=zz-z,L=Math.hypot(dx,dz),nx=-dz/L*2.2,nz=dx/L*2.2,n=Math.ceil(L/4);for(let i=0;i<n;i++){const at=t=>[x+dx*t,frontierHeight(x+dx*t,z+dz*t)+.035,z+dz*t],a=at(i/n),b=at((i+1)/n),p=[a[0]+nx,a[1],a[2]+nz],q=[b[0]+nx,b[1],b[2]+nz],r=[b[0]-nx,b[1],b[2]-nz],s=[a[0]-nx,a[1],a[2]-nz];paths.tri(p,q,r,'#979686');paths.tri(p,r,s,'#979686');}}
 for(const b of FRONTIER_SOLIDS){const y=frontierHeight(b.x,b.z);stone.box(b.x,y+b.h/2,b.z,b.hx*2,b.h,b.hz*2,'#727c86');stone.box(b.x,y+b.h,b.z,b.hx*2+.12,.14,b.hz*2+.12,'#b7b3a8');}
 for(let z=6;z<193;z+=10)for(const x of[204,396])stone.ball(x,2.8,z,4,5+(z%3),6,'#4d5a72');
 for(let x=208;x<392;x+=10)for(const z of[2,196])stone.ball(x,2.8,z,6,4.5,4,'#4d5a72');
 for(const x of[283,317])for(const z of[147,159,180]){const y=frontierHeight(x,z);stone.box(x,y+.3,z,2,.6,2,'#a0a09b');stone.add(unit.cyl,x,y+1.8,z,.65,2.5,.65,'#8c949a');stone.box(x,y+3.2,z,1.6,.25,1.6,'#bab0a3');}
 stone.box(300,5.25,168,24,.6,1.35,'#9c929e');
 for(const [x,z]of[[224,65],[224,108],[229,137],[375,79],[378,137],[271,180]]){const y=frontierHeight(x,z);stone.box(x,y+.3,z,2,.6,3.5,'#929390');stone.box(x,y+1.1,z+1.5,1.5,1.5,.3,'#b6ad9c');}
 for(let i=0;i<15;i++){const x=371+i%3*4,z=68+Math.floor(i/3)*10,y=frontierHeight(x,z);wood.rod([x,y,z],[x+.3,y+3,z],.13,'#6b625a');wood.rod([x+.2,y+1.8,z],[x-1,y+3.4,z+.4],.08,'#6b625a');wood.rod([x+.2,y+2.3,z],[x+1,y+3.5,z-.4],.08,'#6b625a');grass.ball(x,y+3,z,1.3,.5,.9,'#596f64');}
 for(let i=0;i<260;i++){const x=211+(i*31.79)%178,z=10+(i*19.43)%178;if(TRAIL_NODES.some(p=>Math.hypot(x-p[0],z-p[1])<4))continue;const y=frontierHeight(x,z);grass.tri([x-.25,y,z],[x+.22,y,z],[x-.1,y+.7,z],'#778276');grass.tri([x,y,z-.23],[x,y,z+.2],[x+.1,y+.85,z],'#627971');}
 paths.finish(root,m.trim,'Connected ridge, causeway and orchard paths');stone.finish(root,m.wall,'Court ruins, crags and graves');wood.finish(root,m.trim,'Abandoned orchard trunks');grass.finish(root,m.trim,'Orchard canopy and grass');
 arch(root,300,frontierHeight(300,20),17,'GATE CAMP\nX / RETURN TO VINCI');
 const campRing=new T.Mesh(new T.RingGeometry(17.7,18,64),new T.MeshBasicMaterial({color:'#b9d9a2',transparent:true,opacity:.45,side:T.DoubleSide}));campRing.rotation.x=-Math.PI/2;campRing.position.set(300,.25,20);root.add(campRing);
 const markers=[];for(const p of FRONTIER_SITES.filter(p=>p.kind!=='exit')){const g=new T.Group(),b=new Batch();g.position.set(p.x,frontierHeight(p.x,p.z),p.z);if(p.kind==='beacon'){b.box(0,.75,0,.8,1.5,.65,'#a8afa9');b.box(0,1.5,0,1,.16,.8,'#ddcb95');}else if(p.kind==='relic'){b.box(0,.5,0,1.3,.8,.8,'#806544');b.box(0,.95,0,1.4,.13,.9,'#ccb07b');}else b.ball(0,.4,0,.8,.5,.7,p.kind==='ore'?'#9aa5ae':'#78927c');b.finish(g,m.trim,p.name);const tag=label(g,p.name+'\nX / INSPECT',0,2.1,0,3.2,.62,0,'#384d59');root.add(g);markers.push({p,g,tag});}
 root.add(new T.HemisphereLight('#becdea','#53635c',2.2));const sun=new T.DirectionalLight('#c1c5dd',1.7);sun.position.set(240,70,70);root.add(sun);
 const flames=[];for(const [x,z]of[[295,24],[305,24],[292,158],[308,158]]){const y=frontierHeight(x,z),b=new Batch();b.rod([x,y,z],[x,y+1.5,z],.12,'#665959');b.add(unit.ring,x,y+1.4,z,.35,.35,.35,'#b9a083',Math.PI/2);b.finish(root,m.trim,'Signal brazier');const flame=new T.Mesh(new T.OctahedronGeometry(.36),new T.MeshBasicMaterial({color:'#ffdba6'}));flame.position.set(x,y+1.85,z);root.add(flame);flames.push(flame);}
 const warm=new T.PointLight('#ffd099',7,25,1.5);warm.position.set(300,3,24);root.add(warm);
 const player=createPersonRig(m),fade=createActorFade(player);root.add(player.root);const stick=new Batch();stick.rod([0,-.6,0],[0,1.1,0],.043,'#d5b883');const staff=stick.finish(player.handSockets[1],m.trim,'Field staff');const sling=new T.Mesh(new T.TorusGeometry(.13,.02,5,14),new T.MeshStandardMaterial({color:'#d2b780'}));player.handSockets[0].add(sling);
 const creatures=new Map(),q=new T.Quaternion();for(const def of MONSTERS){let actor;if(def.kind==='wisp'){actor={root:new T.Group()};actor.core=new T.Mesh(new T.OctahedronGeometry(.55),new T.MeshStandardMaterial({color:'#afcfc5',emissive:'#4b847c',emissiveIntensity:.5}));actor.core.position.y=1.1;actor.root.add(actor.core);}else{actor=createPersonRig(m,'bandit');const armor=new Batch();armor.box(0,.25,.23,.5,.46,.08,'#89979c');armor.ball(0,.82,.02,.20,.19,.18,'#8c969a');armor.box(0,.8,.2,.24,.06,.035,'#d3d6ab');armor.finish(actor.root.guildRig.torso,m.trim,'Hollow armor');const blade=new Batch();blade.rod([0,-.1,0],[0,.9,0],.035,'#d5d7c8');blade.rod([-.16,0,0],[.16,0,0],.03,'#ccb48b');blade.finish(actor.handSockets[1],m.trim,'Sentinel blade');if(def.kind==='warden')actor.root.scale.setScalar(1.25);}
 const tag=label(actor.root,def.name,0,2.7,0,3.1,.5,0,'#504955');const bar=new T.Mesh(new T.PlaneGeometry(1.3,.08),new T.MeshBasicMaterial({color:'#bad18b',side:T.DoubleSide}));bar.position.y=2.3;actor.root.add(bar);root.add(actor.root);creatures.set(def.id,{...actor,tag,bar});}
 const ring=new T.Mesh(new T.RingGeometry(1.2,1.32,24),new T.MeshBasicMaterial({color:'#f4dea7',side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;root.add(ring);
 const pg=new T.SphereGeometry(.07,6,4),pm=new T.MeshBasicMaterial({color:'#ffebbe'}),pellets=Array.from({length:12},()=>{const p=new T.Mesh(pg,pm);p.visible=false;root.add(p);return p;});
 const safety=createCameraSafety({colliders:FRONTIER_SOLIDS.map(b=>({...b,cameraHeight:b.h})),rooms:[],gates:[],doorPaths:[]},frontierHeight);
 let active=false,background=null,fog=null,last={},visibility=new Map();
 function deactivate(s){if(active){for(const [o,v]of visibility)o.visible=v;scene.background=background;scene.fog=fog;root.visible=false;active=false;safety.reset();}townGate.visible=!s.doors?.level&&!s.life?.inside;}
 function update(s,dt,{yaw=s.yaw,pitch=0,distance=1,snap=false,quality='high'}={}){
  if(!active){active=true;visibility.clear();for(const o of scene.children)if(o!==root){visibility.set(o,o.visible);o.visible=false;}background=scene.background;fog=scene.fog;scene.background=new T.Color('#39475e');scene.fog=new T.Fog('#6a7891',55,185);root.visible=true;safety.reset();}
  const y=frontierHeight(s.x,s.z),aim=s.resonance.aim,follow=(aim?2.7:7)*distance,anchor={x:s.x,y:y+1.45+s.lift,z:s.z},wanted={x:s.x-Math.sin(yaw)*follow,y:y+(aim?2.15:4.1)+pitch+s.lift,z:s.z-Math.cos(yaw)*follow};
  if(aim){wanted.x-=Math.cos(yaw)*.45;wanted.z+=Math.sin(yaw)*.45;}const p=safety.update(anchor,wanted,{level:0,dt,snap});camera.position.set(p.x,p.y,p.z);camera.lookAt(s.x+Math.sin(yaw)*(aim?12:3),y+1.35+s.lift,s.z+Math.cos(yaw)*(aim?12:3));camera.fov=T.MathUtils.lerp(camera.fov,aim?49:59,Math.min(1,dt*5));camera.updateProjectionMatrix();
  player.root.position.set(s.x,y+s.lift,s.z);player.root.rotation.y=s.yaw;animatePerson(player,s.time,{motion:s.lift>.1?'jump':s.doors.dodge>0?'dodge':s.resonance.reload>0?'reload':s.guarding?'guard':s.attackT>0?'strike':aim?'aim':'walk',level:10,action:s.attackT/.25});fade.update(safety.inspect().distance);staff.visible=s.resonance.tool==='staff';sling.visible=s.resonance.tool==='sling';
  for(const e of s.frontier.enemies){const a=creatures.get(e.id);a.root.visible=e.hp>0;a.root.position.set(e.x,frontierHeight(e.x,e.z),e.z);a.root.rotation.y=e.yaw;if(a.core){a.core.position.y=1.1+Math.sin(s.time*2)*.15;a.core.rotation.y=s.time*.4;}else animatePerson(a,s.time,{motion:e.phase==='windup'?'guard':e.phase==='recover'?'strike':e.phase==='stagger'?'dodge':'walk',level:10,action:e.timer});const near=Math.hypot(s.x-e.x,s.z-e.z)<19;a.tag.visible=a.bar.visible=near;q.copy(a.root.quaternion).invert().multiply(camera.quaternion);a.tag.quaternion.copy(q);a.bar.quaternion.copy(q);a.bar.scale.x=Math.max(.01,e.hp/e.maxHP);a.bar.material.color.set(e.phase==='windup'?'#ffbd8e':'#bad18b');}
  for(const {p,g,tag}of markers){tag.visible=Math.hypot(s.x-p.x,s.z-p.z)<12;tag.quaternion.copy(camera.quaternion);g.visible=!(p.kind==='relic'&&s.frontier.relic||s.frontier.harvested.includes(p.id));}const t=frontierTarget(s);ring.visible=!!t;if(t)ring.position.set(t.x,frontierHeight(t.x,t.z)+.12,t.z);
  pellets.forEach((m,i)=>{const b=s.resonance.projectiles[i];m.visible=!!b;if(b)m.position.set(b.x,frontierHeight(b.x,b.z)+1.3,b.z);});flames.forEach((f,i)=>f.scale.y=1+Math.sin(s.time*2+i)*.1);warm.visible=quality!=='low';renderer.render(scene,camera);
  last={active,name:'Cinder Hollow',monsterModels:creatures.size,liveMonsters:s.frontier.enemies.filter(e=>e.hp>0).length,trailSegments:TRAIL_EDGES.length,pointLights:warm.visible?1:0,cameraSafety:safety.inspect(),character:inspectMotion(player),triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls};
 }
 return {update,deactivate,inspect:()=>({...last,active})};
}
