/* Controller-first region notebook. Every button calls a validated reducer;
 * choosing a map destination cannot move the character or award progression. */
import {CONTRACTS,FRONTIER_SITES,BADLANDS,TRAIL_NODES,TRAIL_EDGES,CAMP,inBadlands,safeTown,frontierAction,frontierTarget,nearbyFrontier,contractComplete,frontierSight} from './frontier-core.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
export function createFrontierUI({getState,world,setPause,save,active,onTransition,legacyNearby}){
 const dialog=document.createElement('dialog');dialog.id='frontier-dialog';dialog.setAttribute('aria-label','Regions and expeditions');document.body.append(dialog);
 const badge=document.createElement('div');badge.id='region-badge';badge.hidden=true;document.body.append(badge);
 let tab='journey',message='',next=null;const rideButton=document.querySelector('[data-action="vehicle"]'),rideLabel=rideButton?.innerHTML;
 dialog.addEventListener('close',()=>{setPause(false);const action=next;next=null;action?.();});
 function render(){
  const s=getState(),f=s.frontier,bad=inBadlands(s),near=nearbyFrontier(s,world),gate=near.some(p=>p.id==='gate')&&s.mode==='foot';
  dialog.innerHTML=`<header class="frontier-heading"><div><p class="eyebrow">LEO'S GUILD / BORDERLANDS</p><h2>${bad?'Cinder Hollow':'Vinci and the world beyond'}</h2></div><button data-pad-default id="frontier-close">B / Close</button></header><p class="region-rule">${bad?'BADLANDS: hostile creatures outside the gate. Gate Camp is a sanctuary.':'SAFE TOWN: no hostile attacks or combat damage. Original investigations and house work remain available.'}</p><nav class="frontier-tabs" role="tablist">${[['journey','Journey'],['contracts','Contracts'],['pack','Field pack']].map(([id,name])=>`<button data-frontier-tab="${id}" role="tab" aria-selected="${id===tab}">${name}</button>`).join('')}</nav><section class="frontier-scroll" data-pad-scroll></section><p id="frontier-message" role="status">${esc(message)}</p><footer><button id="frontier-nearby">Other nearby town work</button></footer>`;
  const body=dialog.querySelector('.frontier-scroll');
  if(tab==='journey'){
   if(near.length)body.innerHTML='<h3>Here, within reach</h3>'+near.map(p=>`<article class="frontier-card"><h3>${esc(p.name)}</h3><p>${esc(p.detail||'This action must be performed here, not remotely from the map.')}</p>${p.kind==='gate'?`<button data-frontier-action="enter" ${s.mode!=='foot'?'disabled':''}>Enter Cinder Hollow / monsters ahead</button><button data-frontier-action="rest" ${!gate?'disabled':''}>Rest and refill the sling</button><p>${s.mode==='foot'?'Your bicycle stays parked in town. Return through Gate Camp whenever you choose.':'Dismount with Y before leaving town.'}</p>`:p.kind==='exit'?'<button data-frontier-action="return">Return to safe Vinci</button><button data-frontier-action="rest">Rest and refill the sling</button>':p.kind==='parley'?`<button data-frontier-action="${p.id}">Resolve this encounter peacefully</button>`:`<button data-frontier-action="site:${p.id}">${p.kind==='beacon'?'Record this route':p.kind==='relic'?'Recover the field case':'Gather this source'}</button>`}</article>`).join('');
   if(bad)body.innerHTML+='<h3>Three routes, one connected region</h3><p>The west ridge, central causeway and orchard path reconnect around the court. You can avoid patrols while surveying. Select a marker here, then walk there and press X.</p>'+FRONTIER_SITES.filter(p=>['beacon','exit','relic'].includes(p.kind)).map(p=>`<article class="frontier-card"><h3>${esc(p.name)}</h3><p>${esc(p.detail)}</p><button data-frontier-action="track:${p.id}">Mark ${esc(p.name)}</button></article>`).join('');
   else body.innerHTML+=`<article class="frontier-card"><h3>Vinci / safe town</h3><p>House commissions, crafting, trading and the two Living Stories stay in town. The folio watchman and attic/route rivals now accept a truce through X, without losing their original progression. Rocco's investigation resolves through its existing warrant and evidence interaction.</p></article><article class="frontier-card"><h3>Cinder Hollow / playable badlands</h3><p>Seven persistent creatures, three survey sites, salvage, a guarded field case and three return-to-town contracts. No enemies follow you through a region gate. Reloading returns you to town with your earned progress and cargo intact.</p><button data-frontier-action="track:gate">Mark the expedition gate</button><button data-frontier-action="untrack">Clear the expedition gate marker</button><button data-frontier-tab="contracts">Choose an expedition contract</button></article><article class="frontier-card frontier-planned"><h3>Farmlands / planned, not yet playable</h3><p>The next calmer region is reserved for growing, gathering, deliveries and stewardship. It is not a hidden combat mode and no farm purchase is being sold here.</p></article>`;
   body.innerHTML+='<p class="frontier-help">Xbox: left stick moves; right stick looks; LT aims or braces with the staff; RT uses the tool; LB opens equipment; X interacts or reloads while aiming; B dodges; Y uses a field dressing in the badlands. D-pad Up opens Dispatch. Keyboard: G opens this notebook in the badlands; J strikes, O dodges, F uses a dressing.</p>';
  }else if(tab==='contracts'){
   body.innerHTML=CONTRACTS.map(c=>{const accepted=f.accepted.includes(c.id),paid=f.reported.includes(c.id),complete=contractComplete(s,c.id);const progress=c.id==='survey'?f.visited.length+' / 3 routes':c.id==='wardens'?Math.min(3,f.defeated.length)+' / 3 creatures':f.relic?'Case recovered':'Case not recovered';return `<article class="frontier-card"><p class="eyebrow">${paid?'COMPLETED':accepted?'RECORDED':'AVAILABLE'}</p><h3>${esc(c.name)}</h3><p>${esc(c.text)}</p><p>${progress}. Reward: ${c.reward} florins and ${c.xp} XP, once.</p>${!accepted?`<button data-frontier-action="accept:${c.id}">Record this contract</button>`:!paid?`<button data-frontier-action="report:${c.id}" ${!(gate&&complete)?'disabled':''}>Report at the town gate</button><p>${complete?'Ready to report in Vinci.':'Keep exploring; progress is saved without a timer.'}</p>`:''}</article>`;}).join('');
  }else{
   body.innerHTML=`<article class="frontier-card"><h3>Field dressings: ${f.dressings} / 3</h3><p>Each restores up to 35 vitality. It is not consumed at full health. Y uses one directly while in the badlands.</p><button data-frontier-action="heal" ${f.dressings===0?'disabled':''}>Use a field dressing</button><button data-frontier-action="craft" ${!(gate&&f.dressings<3&&f.store.ore>=1&&f.store.resin>=2)?'disabled':''}>Prepare one at the gate / 1 iron + 2 resin</button></article><article class="frontier-card"><h3>Field cargo</h3><p>Iron: ${f.cargo.ore}. Resin: ${f.cargo.resin}.</p><h3>Banked in town</h3><p>Iron: ${f.store.ore}. Resin: ${f.store.resin}.</p><button data-frontier-action="bank" ${!gate?'disabled':''}>Bank cargo at the town gate</button><p>Nothing is charged for retreat or rescue. Cargo, creatures already defeated and surveyed sites survive a reload. Supplies are bounded, not an online economy.</p></article>`;
  }
  dialog.querySelector('#frontier-close').onclick=()=>dialog.close();
  dialog.querySelectorAll('[data-frontier-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.frontierTab;message='';render();dialog.querySelector(`[role="tab"][data-frontier-tab="${tab}"]`)?.focus();});
  dialog.querySelectorAll('[data-frontier-action]').forEach(b=>b.onclick=()=>{const before=s.frontier.zone,result=frontierAction(s,world,b.dataset.frontierAction);message=result.text;save();if(before!==s.frontier.zone){dialog.close();onTransition();}else render();});
  dialog.querySelector('#frontier-nearby').disabled=bad;dialog.querySelector('#frontier-nearby').onclick=()=>{next=legacyNearby;dialog.close();};
 }
 function open(which='journey'){if(!active())return;tab=which;message='';setPause(true);render();dialog.showModal();}
 function interact(){if(inBadlands(getState())||nearbyFrontier(getState(),world).length){open();return true;}return false;}
 function update(){const s=getState();if(!s.frontier)return;badge.hidden=!document.getElementById('menu').hidden;const bad=inBadlands(s);if(rideButton)rideButton.innerHTML=bad?'<b>Y</b>Dressing':rideLabel;const camp=bad&&Math.hypot(s.x-CAMP.x,s.z-CAMP.z)<18,target=frontierTarget(s);badge.className=bad&&!camp?'hostile':'safe';badge.textContent=(bad?(camp?'GATE CAMP / SANCTUARY':'CINDER HOLLOW / BADLANDS'):'VINCI / SAFE TOWN')+(target?' | '+target.name+' / '+Math.round(Math.hypot(s.x-target.x,s.z-target.z))+' m':'');if(safeTown(s)){document.getElementById('duel').hidden=true;document.getElementById('doors-enemy').hidden=true;}}
 function drawMap(canvas,full=false){
  const s=getState();if(!inBadlands(s))return false;const g=canvas.getContext('2d'),width=canvas.width,height=canvas.height;
  const X=x=>14+(x-BADLANDS.minX)/(BADLANDS.maxX-BADLANDS.minX)*(width-28),Z=z=>height-14-(z-BADLANDS.minZ)/(BADLANDS.maxZ-BADLANDS.minZ)*(height-28);
  g.clearRect(0,0,width,height);g.fillStyle='#172633';g.fillRect(0,0,width,height);g.strokeStyle='#938568';g.lineWidth=full?5:2;
  for(const [a,b]of TRAIL_EDGES){g.beginPath();g.moveTo(X(TRAIL_NODES[a][0]),Z(TRAIL_NODES[a][1]));g.lineTo(X(TRAIL_NODES[b][0]),Z(TRAIL_NODES[b][1]));g.stroke();}
  for(const p of FRONTIER_SITES.filter(p=>['beacon','exit','relic'].includes(p.kind))){g.fillStyle=p.id==='return'?'#8ed9ad':s.frontier.visited.includes(p.id)?'#81adae':'#edca7e';g.fillRect(X(p.x)-3,Z(p.z)-3,6,6);if(full){g.font='12px Arial';g.fillText(p.name,X(p.x)+8,Z(p.z)-5);}}
  for(const m of s.frontier.enemies){if(m.hp<=0||Math.hypot(s.x-m.x,s.z-m.z)>30||!frontierSight(s,m))continue;g.fillStyle='#ee9378';g.beginPath();g.arc(X(m.x),Z(m.z),full?4:2.5,0,Math.PI*2);g.fill();}
  const p=frontierTarget(s);if(p){g.strokeStyle='#e4eea6';g.lineWidth=2;g.beginPath();g.arc(X(p.x),Z(p.z),full?10:6,0,Math.PI*2);g.stroke();}
  g.fillStyle='#faf4d6';g.beginPath();g.arc(X(s.x),Z(s.z),full?5:4,0,Math.PI*2);g.fill();g.strokeStyle='#fff6c5';g.beginPath();g.moveTo(X(s.x),Z(s.z));g.lineTo(X(s.x)+Math.sin(s.yaw)*10,Z(s.z)-Math.cos(s.yaw)*10);g.stroke();return true;
 }
 return {open,interact,update,drawMap,close(){if(!dialog.open)return false;dialog.close();return true;}};
}
