/* Original, bounded badlands presentation. Same renderer and camera, with a
 * reversible region layer. No copied reference art, extra soundtrack or network.
 * Seven enemies, static batched ruins and three connected physical trails. */
import * as T from './vendor/three.module.js';
import {Batch,unit,label} from './art.mjs';
import {createPersonRig,createActorFade} from './character-rig.mjs';
import {animatePerson,inspectMotion} from './character-motion.mjs';
import {createCameraSafety} from './camera-safety.mjs';
import {inBadlands,FRONTIER_SITES,FRONTIER_SOLIDS,MONSTERS,CAMP,TOWN_GATE,frontierTarget,frontierHeight,TRAIL_NODES,TRAIL_EDGES} from './frontier-core.mjs';
export function createFrontierArt({scene,camera,renderer,m,heightAt}){
 const root=new T.Group();root.name='Cinder Hollow region';root.visible=false;scene.add(root);
 const townGate=new T.Group();townGate.name='Vinci expedition gate';townGate.position.set(TOWN_GATE.x,heightAt(TOWN_GATE.x,TOWN_GATE.z),TOWN_GATE.z);scene.add(townGate);
 const gateBatch=new Batch();for(const side of[-1,1]){gateBatch.box(side*3.2,1.65,0,.9,3.3,1.1,'#89826b');gateBatch.box(side*3.2,3.4,0,1.2,.3,1.3,'#c5b58a');}gateBatch.box(0,3.9,0,7.4,.3,.75,'#8d7250');gateBatch.finish(townGate,m.trim,'Open expedition arch');const townLabel=label(townGate,'CINDER HOLLOW\nX / EXPEDITIONS',0,3,0,3.7,.9,0,'#345450');townLabel.userData.frontierGateLabel=true;
 const terrainGeo=new T.PlaneGeometry(200,204,40,40);terrainGeo.rotateX(-Math.PI/2);terrainGeo.translate(300,0,100);const a=terrainGeo.attributes.position;for(let i=0;i<a.count;i++)a.setY(i,frontierHeight(a.getX(i),a.getZ(i))-.09);terrainGeo.computeVertexNormals();const terrain=new T.Mesh(terrainGeo,new T.MeshStandardMaterial({color:'#425555',roughness:1}));terrain.receiveShadow=true;root.add(terrain);
 const path=new Batch(),ruin=new Batch(),plants=new Batch(),details=new Batch();
 for(const [ai,bi] of TRAIL_EDGES){const [x,z]=TRAIL_NODES[ai],[xx,zz]=TRAIL_NODES[bi],dx=xx-x,dz=zz-z,len=Math.hypot(dx,dz),nx=-dz/len*2.3,nz=dx/len*2.3,n=Math.ceil(len/5);for(let i=0;i<n;i++){const at=t=>[x+dx*t,frontierHeight(x+dx*t,z+dz*t)+.025,z+dz*t];const p=at(i/n),q=at((i+1)/n);path.tri([p[0]+nx,p[1],p[2]+nz],[q[0]+nx,q[1],q[2]+nz],[q[0]-nx,q[1],q[2]-nz],'#7e8277');path.tri([p[0]+nx,p[1],p[2]+nz],[q[0]-nx,q[1],q[2]-nz],[p[0]-nx,p[1],p[2]-nz],'#7e8277');}}
 for(const b of FRONTIER_SOLIDS){const y=frontierHeight(b.x,b.z);ruin.box(b.x,y+b.h/2,b.z,b.hx*2,b.h,b.hz*2,'#72747b');for(let k=0;k<3;k++)ruin.box(b.x,y+b.h-.1+k*.11,b.z,b.hx*2+.3-k*.1,.12,b.hz*2+.3-k*.1,'#a5a195');}
 for(let z=6;z<=192;z+=9)for(const x of[205,395])ruin.ball(x,frontierHeight(x,z)+3.6,z,4.1,4.5+(z%3),6,'#424e62');
 for(let x=208;x<392;x+=10)for(const z of[3,195])ruin.ball(x,frontierHeight(x,z)+3,z,6,4,4,'#424e62');
 for(const x of[285,315])for(const z of[146,158,180]){const y=frontierHeight(x,z);ruin.add(unit.cyl,x,y+1.4,z,.7,2.8,.7,'#939098');ruin.box(x,y+2.9,z,1.7,.25,1.7,'#b8ab9a');}ruin.box(300,5.35,168,24,.65,1.4,'#8c8290');
 for(const [x,z]of[[224,66],[224,106],[229,136],[368,73],[378,137],[275,180]]){const y=frontierHeight(x,z);details.box(x,y+.3,z,2,.6,3.6,'#969086');details.box(x,y+1.0,z+1.5,1.5,1.4,.35,'#b7a897');}
 for(let i=0;i<15;i++){const x=371+(i%3)*4,z=69+Math.floor(i/3)*10,y=frontierHeight(x,z);plants.rod([x,y,z],[x+.4,y+3,z],.15,'#635b59');plants.rod([x+.2,y+2,z],[x+1.2,y+3.6,z+.4],.10,'#635b59');plants.rod([x+.2,y+1.8,z],[x-.9,y+3.2,z-.5],.10,'#635b59');plants.ball(x+.2,y+3,z,1.2,.6,.8,'#4d6261');}
 for(let i=0;i<200;i++){const x=212+(i*31.79)%176,z=10+(i*19.43)%176;const clear=TRAIL_NODES.every(p=>Math.hypot(x-p[0],z-p[1])>4);if(!clear)continue;const y=frontierHeight(x,z);plants.tri([x-.22,y,z],[x+.2,y,z],[x-.1,y+.65,z],'#687467');plants.tri([x,y,z-.2],[x,y,z+.2],[x+.1,y+.85,z],'#536d64');}
 path.finish(root,m.trim,'Three connected field trails');ruin.finish(root,m.wall,'Original stone ruins and perimeter cliffs');plants.finish(root,m.trim,'Orchard trees and low field plants');details.finish(root,m.trim,'Gravestones and broken survey landmarks');
 const arch=townGate.clone(true);arch.position.set(CAMP.x,frontierHeight(CAMP.x,CAMP.z),CAMP.z-3);root.add(arch);arch.traverse(c=>{if(c.userData.frontierGateLabel)c.visible=false;});label(root,'GATE CAMP\nX / RETURN TO VINCI',300,3.1,20,4,1,Math.PI,'#36666b');
 const halo=new T.Mesh(new T.RingGeometry(16,16.25,64),new T.MeshBasicMaterial({color:'#9aba9b',transparent:true,opacity:.35,side:T.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.set(300,.23,20);root.add(halo);
 const markers=[];for(const p of FRONTIER_SITES.filter(p=>p.kind!=='exit')){const g=new T.Group(),b=new Batch();g.position.set(p.x,frontierHeight(p.x,p.z),p.z);if(p.kind==='beacon'){b.box(0,.75,0,.8,1.5,.65,'#a9aa96');b.box(0,1.5,0,1.05,.16,.8,'#dac38d');}else if(p.kind==='relic'){b.box(0,.5,0,1.25,.8,.8,'#7d6246');b.box(0,.95,0,1.35,.15,.88,'#d7bc72');}else{b.ball(0,.35,0,.75,.5,.7,p.kind==='ore'?'#879498':'#608269');}b.finish(g,m.trim,p.name);const tag=label(g,p.name+'\nX / INSPECT',0,2.2,0,3.3,.6,0,'#324b53');root.add(g);markers.push({p,g,tag});}
 const hemisphere=new T.HemisphereLight('#99b9dd','#464557',1.9);root.add(hemisphere);const sun=new T.DirectionalLight('#bbc5e3',1.6);sun.position.set(250,70,100);root.add(sun);
 const flames=[];for(const [x,z]of[[295,23],[305,23],[292,158],[308,158]]){const y=frontierHeight(x,z),b=new Batch();b.rod([x,y,z],[x,y+1.5,z],.13,'#4d4950');b.add(unit.ring,x,y+1.45,z,.36,.36,.36,'#b5976a',Math.PI/2);b.finish(root,m.trim,'Caged signal brazier');const flame=new T.Mesh(new T.OctahedronGeometry(.35),new T.MeshBasicMaterial({color:'#edc596'}));flame.position.set(x,y+1.8,z);root.add(flame);flames.push(flame);}
 const warm=new T.PointLight('#edbd85',5,24,1.5);warm.position.set(300,3,23);root.add(warm);
 const apprentice=createPersonRig(m),fade=createActorFade(apprentice);root.add(apprentice.root);
 const stick=new Batch();stick.rod([0,-.65,0],[0,1.05,0],.045,'#c6a670');const staff=stick.finish(apprentice.handSockets[1],m.trim,'Field staff');
 const sling=new T.Mesh(new T.TorusGeometry(.14,.018,5,14),new T.MeshStandardMaterial({color:'#d2b47c'}));sling.position.set(0,0,.08);apprentice.handSockets[0].add(sling);
 const creatures=new Map();for(const def of MONSTERS){let actor;if(def.kind==='wisp'){const g=new T.Group(),core=new T.Mesh(new T.OctahedronGeometry(.55),new T.MeshStandardMaterial({color:'#85aaa8',emissive:'#487979',emissiveIntensity:.6,roughness:.6}));core.position.y=1.1;g.add(core);actor={root:g,wisp:core};}else{actor=createPersonRig(m,'bandit');const armor=new Batch();armor.box(0,.25,.21,.48,.44,.07,def.kind==='warden'?'#706474':'#738183');armor.ball(0,.82,.04,.20,.19,.18,'#80878a');armor.box(0,.79,.21,.25,.07,.035,'#bdd8b3');armor.finish(actor.root.guildRig.torso,m.trim,'Hollow armor and visor');const sword=new Batch();sword.rod([0,-.1,.03],[0,.9,.03],.04,'#c4ccc2');sword.rod([-.16,0,.03],[.16,0,.03],.03,'#c9ab73');sword.finish(actor.handSockets[1],m.trim,'Stone sentinel blade');if(def.kind==='warden')actor.root.scale.setScalar(1.25);}
  const tag=label(actor.root,def.name,0,2.65,0,3,.48,0,'#544f59');const bar=new T.Mesh(new T.PlaneGeometry(1.25,.07),new T.MeshBasicMaterial({color:'#acc889',side:T.DoubleSide}));bar.position.y=2.25;actor.root.add(bar);root.add(actor.root);creatures.set(def.id,{...actor,tag,bar});}
 const targetRing=new T.Mesh(new T.RingGeometry(1.1,1.2,32),new T.MeshBasicMaterial({color:'#f1dbaa',side:T.DoubleSide,transparent:true,opacity:.8}));targetRing.rotation.x=-Math.PI/2;root.add(targetRing);
 const pelletGeo=new T.SphereGeometry(.075,6,4),pelletMat=new T.MeshBasicMaterial({color:'#f3dfb2'});const pellets=Array.from({length:12},()=>{const p=new T.Mesh(pelletGeo,pelletMat);p.visible=false;root.add(p);return p;});
 const cameraWorld={colliders:FRONTIER_SOLIDS.map(b=>({...b,low:false})),rooms:[],gates:[],doorPaths:[]},safety=createCameraSafety(cameraWorld,frontierHeight);
 let active=false,oldBackground=null,oldFog=null,last={},visibility=new Map();
 function activate(){if(active)return;active=true;visibility.clear();for(const child of scene.children){if(child===root)continue;visibility.set(child,child.visible);child.visible=false;}oldBackground=scene.background;oldFog=scene.fog;scene.background=new T.Color('#303f59');scene.fog=new T.Fog('#53627c',45,170);root.visible=true;safety.reset();}
 function deactivate(s){if(active){for(const [child,v]of visibility)child.visible=v;scene.background=oldBackground;scene.fog=oldFog;root.visible=false;active=false;safety.reset();}townGate.visible=!s.doors?.level&&!s.life?.inside;}
 function update(s,dt,{yaw=s.yaw,pitch=0,distance=1,snap=false,quality='high'}={}){
  activate();const y=frontierHeight(s.x,s.z),aim=s.resonance.aim,follow=(aim?2.8:7)*distance;
  const anchor={x:s.x,y:y+1.45+s.lift,z:s.z},desired={x:s.x-Math.sin(yaw)*follow,y:y+(aim?2.15:4.3)+pitch+s.lift,z:s.z-Math.cos(yaw)*follow};
  if(aim){desired.x-=Math.cos(yaw)*.5;desired.z+=Math.sin(yaw)*.5;}
  const pos=safety.update(anchor,desired,{level:0,ground:y,dt,snap});camera.position.set(pos.x,pos.y,pos.z);camera.lookAt(s.x+Math.sin(yaw)*(aim?12:3),y+1.35+s.lift,s.z+Math.cos(yaw)*(aim?12:3));camera.fov=T.MathUtils.lerp(camera.fov,aim?49:59,Math.min(1,dt*5));camera.updateProjectionMatrix();
  apprentice.root.position.set(s.x,y+s.lift,s.z);apprentice.root.rotation.y=s.yaw;animatePerson(apprentice,s.time,{motion:s.lift>.1?'jump':s.doors.dodge>0?'dodge':s.resonance.reload>0?'reload':s.guarding?'guard':s.attackT>0?'strike':aim?'aim':'walk',level:10,action:s.attackT/.25});fade.update(safety.inspect().distance);staff.visible=s.resonance.tool==='staff';sling.visible=s.resonance.tool==='sling';
  for(const enemy of s.frontier.enemies){const a=creatures.get(enemy.id);a.root.visible=enemy.hp>0;a.root.position.set(enemy.x,frontierHeight(enemy.x,enemy.z),enemy.z);a.root.rotation.y=enemy.yaw;if(a.wisp){a.wisp.position.y=1.05+Math.sin(s.time*2)*.14;a.wisp.rotation.y=s.time*.4;a.wisp.material.emissiveIntensity=enemy.phase==='windup'?1.1:.6;}else animatePerson(a,s.time,{motion:enemy.phase==='windup'?'guard':enemy.phase==='recover'?'strike':enemy.phase==='stagger'?'dodge':'walk',level:10,action:enemy.timer});const near=Math.hypot(s.x-enemy.x,s.z-enemy.z)<18;a.tag.visible=near;a.bar.visible=near;a.tag.quaternion.copy(a.root.quaternion.clone().invert().multiply(camera.quaternion));a.bar.quaternion.copy(a.tag.quaternion);a.bar.scale.x=Math.max(.01,enemy.hp/enemy.maxHP);a.bar.material.color.set(enemy.phase==='windup'?'#edb18b':'#a7cd91');}
  for(const {p,g,tag} of markers){tag.visible=Math.hypot(s.x-p.x,s.z-p.z)<12;tag.quaternion.copy(camera.quaternion);g.visible=!(p.kind==='relic'&&s.frontier.relic||s.frontier.harvested.includes(p.id));}
  const target=frontierTarget(s);targetRing.visible=!!target;if(target)targetRing.position.set(target.x,frontierHeight(target.x,target.z)+.11,target.z);for(let i=0;i<pellets.length;i++){const p=s.resonance.projectiles[i],obj=pellets[i];obj.visible=!!p;if(p)obj.position.set(p.x,frontierHeight(p.x,p.z)+1.3,p.z);}
  flames.forEach((f,i)=>{f.scale.set(1,1+Math.sin(s.time*2+i)*.11,1)});warm.visible=quality!=='low';
  renderer.render(scene,camera);last={active:true,name:'Cinder Hollow',monsterModels:creatures.size,liveMonsters:s.frontier.enemies.filter(m=>m.hp>0).length,trailSegments:TRAIL_EDGES.length,areas:6,pointLights:warm.visible?1:0,cameraSafety:safety.inspect(),character:inspectMotion(apprentice),triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls};
 }
 return {update,deactivate,inspect:()=>({...last,active})};
}
