import {inQuarter,quarterEnter,quarterAct,quarterChoices,nearbyQuarter,quarterText} from './quarter-core.mjs';
import {QUARTER_GATE,QUARTER_FLOORS,QUARTER_SITES} from './quarter-data.mjs';
export function createQuarterUI({getState,setPause,save,onTransition}){
 const d=document.createElement('dialog');d.id='quarter-dialog';d.setAttribute('aria-label','Waterwheel Quarter');document.body.append(d);d.addEventListener('close',()=>setPause(false));
 function show(site){const s=getState();d.replaceChildren();const title=document.createElement('h2'),text=document.createElement('p'),feedback=document.createElement('p');title.textContent=site?.name||'Waterwheel Quarter';text.textContent=inQuarter(s)?quarterText(s).text:'The new Waterwheel Quarter begins beside Leonardo\'s workshop. Your earlier commissions, vehicles and saved rewards remain in this town.';feedback.id='quarter-feedback';feedback.setAttribute('role','status');d.append(title,text,feedback);
  const choices=inQuarter(s)?site?quarterChoices(s,site.id):[['overview','Three approaches: cooperation, roofs, or sluices']]:[['enter','Enter the Waterwheel Quarter']];
  for(const [id,label]of choices){const b=document.createElement('button');b.dataset.quarterAction=id;b.textContent=label;b.onclick=()=>{if(id==='enter'){if(quarterEnter(s)){save();d.close();onTransition();}else feedback.textContent='Approach the Quarter sign beside Leonardo\'s workshop on foot and stop first.';return;}if(id==='overview'){feedback.textContent='Marta\'s workshop is to the right. Ilaria\'s dye stairs climb on the left. The sluice platform overlooks the lower service channel. The bell-bracket arch opens from its far side.';return;}const result=quarterAct(s,site.id,id);feedback.textContent=result.text;save();if(result.transition){d.close();onTransition();}};d.append(b);}
  const back=document.createElement('button');back.textContent='Return to play / B';back.dataset.padDefault='';back.onclick=()=>d.close();d.append(back);setPause(true);if(!d.open)d.showModal();
 }
 function interact(){const s=getState();if(inQuarter(s)){show(nearbyQuarter(s)[0]);return true;}if(s.frontier?.zone==='town'&&s.mode==='foot'&&Math.hypot(s.x-QUARTER_GATE.x,s.z-QUARTER_GATE.z)<4&&!s.life.inside&&!s.doors.level){show();return true;}return false;}
 function drawMap(canvas,full){const s=getState();if(!inQuarter(s))return false;const g=canvas.getContext('2d'),W=canvas.width,H=canvas.height,scale=Math.min((W-24)/54,(H-45)/52),X=x=>(x+28)*scale+12,Z=z=>(z+18)*scale+25;g.fillStyle='#213e42';g.fillRect(0,0,W,H);for(const f of QUARTER_FLOORS){g.fillStyle=f.y>1?'#ae8857':f.y<0?'#497d80':'#c8b68d';g.fillRect(X(f.x1),Z(f.z1),(f.x2-f.x1)*scale,(f.z2-f.z1)*scale);g.strokeStyle='#203c3c';g.strokeRect(X(f.x1),Z(f.z1),(f.x2-f.x1)*scale,(f.z2-f.z1)*scale);}g.fillStyle='#fff3b8';g.beginPath();g.arc(X(s.x),Z(s.z),4,0,7);g.fill();if(full){g.font='12px sans-serif';g.fillText('WATERWHEEL QUARTER / ROOFS, COURT AND CHANNEL',12,16);for(const p of QUARTER_SITES){g.fillText(p.id,X(p.x)+4,Z(p.z)-4);}g.fillText('Gold: above. Teal: below. Footprints overlap on different floors.',12,H-12);}return true;}
 function update(){const s=getState();if(inQuarter(s)){const p=nearbyQuarter(s)[0];document.getElementById('context').textContent=p?'X / '+p.name:'Follow the workshop, drying roofs or service-channel connections. X inspects nearby.';document.getElementById('duel').hidden=true;}else if(Math.hypot(s.x-QUARTER_GATE.x,s.z-QUARTER_GATE.z)<7&&s.frontier?.zone==='town')document.getElementById('context').textContent='New Waterwheel Quarter / stop on foot near the workshop and press X.';}
 return {interact,open:()=>show(nearbyQuarter(getState())[0]),close(){if(!d.open)return false;d.close();return true;},drawMap,update,inspect:()=>({open:d.open,nearby:nearbyQuarter(getState()).map(p=>p.id)})};
