/* Bounded authored district in the existing fixed-step game, not a second sim. */
import {QUARTER_REVISION,QUARTER_ARRIVAL,QUARTER_GATE,QUARTER_FLOORS,QUARTER_SITES,QUARTER_ACTORS,activeQuarterWalls,surfaceY} from './quarter-data.mjs';
import {normalizePorterOrder,porterState,porterCanRequest,requestPorter,cancelPorter,takeFromPorter,takeFromBench,porterStatus,porterActor,porterSite,stepPorter} from './quarter-porter.mjs';
import {normalizeObservations,QUARTER_OBSERVATIONS} from './quarter-notes.mjs';
const finite=n=>Number.isFinite(n),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export const inQuarter=s=>s?.quarter?.active===true;
export function quarterState(raw={}){raw=raw&&typeof raw==='object'?raw:{};const q={version:1,layout:QUARTER_REVISION,active:raw.active===true,goodsAccess:raw.goodsAccess===true,archOpen:raw.archOpen===true,parcel:raw.parcel===true,reported:raw.reported===true&&raw.parcel===true,low:raw.low===true,delivery:0,briefed:raw.briefed===true,observations:normalizeObservations(raw.observations),visited:[],waterY:-.15,groundY:0,surface:'workshop-porch',actors:[]};q.delivery=q.reported&&Number.isInteger(raw.delivery)?clamp(raw.delivery,0,3):0;q.visited=Array.isArray(raw.visited)?[...new Set(raw.visited.filter(id=>QUARTER_FLOORS.some(f=>f.id===id)))].slice(0,QUARTER_FLOORS.length):[];q.waterY=q.low?-2.38:-.15;q.porterOrder=normalizePorterOrder(raw.porterOrder,q);q.porter=porterState(q.porterOrder);return q;}
export function saveQuarter(s){if(!s.quarter)return undefined;const q=quarterState(s.quarter);return Object.fromEntries(['version','layout','active','goodsAccess','archOpen','parcel','reported','low','delivery','briefed','observations','visited','porterOrder'].map(k=>[k,q[k]]));}
function clearTravel(s){s.speed=0;s.lift=0;s.vy=0;s.mode='foot';s.shots=[];s.attackT=0;s.guarding=false;if(s.life)s.life.inside=null;if(s.doors){s.doors.level=0;s.doors.room=null;s.doors.dodge=0;}if(s.resonance){s.resonance.projectiles=[];s.resonance.aim=false;s.resonance.lock=null;s.resonance.cover=null;s.resonance.duck=false;}if(s.frontier)s.frontier.zone='town';}
export function quarterRecover(s){clearTravel(s);Object.assign(s,QUARTER_ARRIVAL);s.quarter.groundY=0;s.quarter.surface='workshop-porch';s.toast='Returned to the workshop. All completed work is retained.';s.toastT=4;}
export function attachQuarter(s,raw,options={}){s.quarter=quarterState(raw);if(options.fresh&&!options.legacy)s.quarter.active=true;if(s.quarter.active)quarterRecover(s);return s;}
export function quarterEnter(s){if(inQuarter(s)||s.mode!=='foot'||s.life?.inside||s.doors?.level||s.frontier?.zone==='badlands'||s.cycle?.active||Math.abs(s.speed)>1||s.lift>.05||dist(s,QUARTER_GATE)>4)return false;s.quarter||=quarterState();s.quarter.active=true;quarterRecover(s);return true;}
export function quarterLeave(s){if(!inQuarter(s))return false;s.quarter.active=false;clearTravel(s);s.x=QUARTER_GATE.x;s.z=QUARTER_GATE.z;s.yaw=0;return true;}
export function quarterSurface(x,z,near=0){const candidates=QUARTER_FLOORS.filter(f=>x>=f.x1-1e-6&&x<=f.x2+1e-6&&z>=f.z1-1e-6&&z<=f.z2+1e-6).map(f=>({floor:f,y:surfaceY(f,z)}));candidates.sort((a,b)=>Math.abs(a.y-near)-Math.abs(b.y-near));return candidates[0]||null;}
export function quarterGround(s,x=s.x,z=s.z){return quarterSurface(x,z,s.quarter?.groundY||0)?.y??s.quarter?.groundY??0;}
export function quarterBlocked(s,x,z,r=.33){if(!finite(x)||!finite(z)||!finite(r))return true;const q=s.quarter||quarterState(),h=quarterSurface(x,z,q.groundY);if(!h||Math.abs(h.y-q.groundY)>.5)return true;
 if(h.floor.kind==='wet'&&q.waterY-h.y>.46)return true;
 for(let i=0;i<8;i++){const a=i*Math.PI/4,v=quarterSurface(x+Math.cos(a)*r,z+Math.sin(a)*r,h.y);if(!v||Math.abs(v.y-h.y)>.5)return true;}
 for(const b of activeQuarterWalls(q)){if(h.y+1.5<=b.y||h.y>=b.y+b.h)continue;const dx=x-clamp(x,b.x-b.hx,b.x+b.hx),dz=z-clamp(z,b.z-b.hz,b.z+b.hz);if(Math.hypot(dx,dz)<r)return true;}return false;
}
function lineClear(s,site){const length=dist(s,site),q=s.quarter;for(let t=.15;t<length-.1;t+=.15){const a=t/(length||1),x=s.x+(site.x-s.x)*a,z=s.z+(site.z-s.z)*a;for(const w of activeQuarterWalls(q))if(site.y+.9>w.y&&site.y+.9<w.y+w.h&&x>w.x-w.hx&&x<w.x+w.hx&&z>w.z-w.hz&&z<w.z+w.hz)return false;}return true;}
export function nearbyQuarter(s){if(!inQuarter(s)||s.mode!=='foot'||s.lift>.05)return [];const porter=porterSite(s.quarter);return [...QUARTER_SITES,...(porter?[porter]:[])].filter(a=>dist(a,s)<2.15&&Math.abs(a.y-s.quarter.groundY)<.42&&lineClear(s,a)).sort((a,b)=>dist(a,s)-dist(b,s));}
export function quarterTarget(s){if(!inQuarter(s))return null;const q=s.quarter;if(q.delivery===1&&q.porterOrder){return porterSite(q)||QUARTER_SITES.find(a=>a.id==='arch-front');}return QUARTER_SITES.find(a=>a.id===(!q.parcel?'parcel':!q.reported?'workshop':q.delivery===1?'precision':q.delivery===2?'loft':'workshop'));}
export function quarterText(s){const q=s.quarter;return {tag:'WATERWHEEL QUARTER / THE MISSING COMMISSION',title:!q.parcel?'Three households. One shared invention.':!q.reported?'The way home was beside you.':q.delivery===1?(q.porterOrder?'Meet Neri along the restored goods route.':'Collect a spindle from Marta.'):q.delivery===2?'Bring the spindle to the finishing loft.':'A neighborhood you now understand.',text:!q.parcel?'Reach the stalled goods carriage by cooperation, the dye roofs, or the drained service channel. X interacts. These are three independent approaches.':!q.reported?'Recovering the commission is enough. Return to Leonardo; look for the familiar bell bracket on the gallery descent.':q.delivery===1&&q.porterOrder?porterStatus(q):'The service arch stays open once unlatched. Completed work survives reload. Speak to Leonardo for a short follow-up delivery or continue into the older town.'};}
export function quarterChoices(s,id){const q=s.quarter;switch(id){case'workshop':return [['brief','Ask about the shared goods system'],...(!q.reported?[['report','Return the recovered commission']]:q.delivery===0?[['delivery-start','Take a follow-up spindle delivery']]:[]),['supplies','Replenish supplies without charge']];case'precision':return [...(!q.goodsAccess?[['ratio-1','Set the drive ratio to 1:1'],['ratio-2','Set the drive ratio to 2:1'],['ratio-3','Set the drive ratio to 3:1']]:[]),['collect-spindle','Collect the commissioned spindle'],['read','Read the drive instructions']];case'arch-front':return [...(nearbyQuarter(s).some(p=>p.id==='porter')?[['take-spindle','Take the spindle from Neri']]:[]),['read','Inspect the bell and household route'],...(q.porterOrder?[['cancel-porter','Ask Neri to return the spindle to Marta']]:[['call-porter','Ring for a commissioned spindle / optional']])];case'porter':return [['take-spindle','Take the spindle from Neri'],['porter-status','Ask about the household route']];case'carrier':return [['ask','Ask Neri to make the loading stairs available now']];case'sluice':return [['drain','Close inlet and drain the service channel'],['refill','Restore inlet and refill the channel']];case'parcel':return [['recover','Recover the missing commission']];case'arch-back':return [['unlatch','Unlatch the bell-bracket service arch']];case'loft':return [['deliver-spindle','Deliver the spindle to Ilaria'],['read','Inspect the roof route']];case'town':return [['leave','Continue to the older Vinci districts']];default:return [['read','Inspect this place']];}}
export function quarterAct(s,id,action){const q=s.quarter;const site=nearbyQuarter(s).find(v=>v.id===id);if(!site||Math.abs(s.speed)>.45)return {ok:false,text:'Reach this station on its actual floor and stop before interacting.'};if(!quarterChoices(s,id).some(v=>v[0]===action))return {ok:false,text:'That action does not belong to this station.'};let ok=true,text='';
 if(action==='call-porter'){ok=requestPorter(q);text=ok?'Neri is fetching Marta\'s spindle through the loading stairs, gallery and reopened arch. Meet him en route or wait here; there is no deadline. Return to play to let him work.':porterStatus(q);}
 else if(action==='cancel-porter'){ok=cancelPorter(q);text=q.porterOrder==='returning'?'Neri will carry it back to Marta. You can still intercept him for an in-person handoff. Return to play to let him walk.':'Request cancelled. Marta\'s bench remains available.';}
 else if(action==='take-spindle'){ok=nearbyQuarter(s).some(p=>p.id==='porter')&&takeFromPorter(q);text=ok?'Spindle received directly from Neri. Take it to Ilaria\'s finishing table; the delivery still needs your personal return.':'Neri is not carrying a commissioned spindle.';}
 else if(action==='porter-status'){text=porterStatus(q);}
 else if(action==='read'){text=id==='arch-front'?'The bell bracket is distinctive. The latch is on the far side: look for it again when descending the gallery.':id==='dye'||id==='loft'?'Fabric travels up the dye stairs, across the drying roof and over the timber bridge into the goods gallery. No permission or repair is needed to walk that route.':id==='cellar'?'The ledger explains the fault: the carriage stopped above this cellar. The two service stairs go around its rear and emerge beside it.':'The large drive turns once while the small pinion turns twice. The correct setting is 2:1. This shared repair opens the goods stairs.';}
 else if(action==='brief'){q.briefed=true;text='Marta produces, Ilaria finishes, and Neri carries. A commission is stranded on the goods gallery. Help Marta, follow the drying roofs, or drain the service channel. Every approach is valid.';}
 else if(action==='ratio-2'){q.goodsAccess=true;text='The 2:1 drive engages. Marta opens the loading stair gate. The commission can now be reached from the court.';}
 else if(action.startsWith('ratio-')){ok=false;text='The drive does not engage. Nothing was spent: the large gear turns once while the small pinion turns twice. Try another setting.';}
 else if(action==='ask'){if(!q.goodsAccess){ok=false;text='Neri is available now: Marta needs the 2:1 drive repaired at her workbench before these stairs can carry goods. The roof and sluice routes remain independent.';}else text='The loading stairs are open now. Reopen the bell-bracket arch to restore household deliveries. A later spindle can be fetched by Neri or collected manually.';}
 else if(action==='drain'){q.low=true;text='The outlet opens. Watch the waterline fall before descending the physical ramp; there is no drowning timer.';}
 else if(action==='refill'){if(q.groundY<-.1){ok=false;text='Return to the dry controls first.';}else {q.low=false;text='The inlet reopens. Stay on the dry route as the channel fills.';}}
 else if(action==='recover'){if(q.parcel){ok=false;text='You already recovered this commission.';}else{q.parcel=true;text='The missing commission is recovered. No preferred-route trigger is required. Return to Leonardo; the gallery descent leads toward the familiar bell bracket.';}}
 else if(action==='unlatch'){q.archOpen=true;text='The service arch opens beside Leonardo\'s workshop. This shortcut remains open in your saved adventure.';}
 else if(action==='report'){if(!q.parcel||q.reported){ok=false;text=q.reported?'That commission has already been paid.':'The commission is still on the goods gallery.';}else{q.reported=true;s.credits+=60;s.life.xp+=120;text='Commission returned: 60 florins and 120 experience, paid once. The neighborhood and its shortcut remain available.';}}
 else if(action==='delivery-start'){q.delivery=1;text='Collect Marta\'s spindle and take it to Ilaria\'s finishing loft. Use the routes you now know, or ring the bell-bracket arch for Neri after restoring the drive and arch. There is no deadline.';}
 else if(action==='collect-spindle'){if(!takeFromBench(q)){ok=false;text=q.porter?.carrying||q.porterOrder==='ready'?'Neri has the spindle. Meet him in person, or request its return at the bell.':'Leonardo commissions this spindle after the missing parcel has been returned.';}else{text='Spindle collected. Any uncollected porter request is cancelled. Ilaria\'s finishing table is in the dye loft.';}}
 else if(action==='deliver-spindle'){if(q.delivery!==2){ok=false;text='Bring the commissioned spindle from Marta first.';}else{q.delivery=3;s.credits+=15;s.life.xp+=40;text='Spindle delivered: 15 florins and 40 experience, paid once. The households can work together again.';}}
 else if(action==='supplies'){s.health=100+12*(s.life.attrs.vitality||0);s.papers=s.life.bike==='cargo'?30:20;s.resonance.ready=6;s.resonance.reserve=36;text='Health, letters and sling supplies restored. Progress and equipment are unchanged.';}
 else if(action==='leave'){quarterLeave(s);text='Your Quarter progress is kept. Older Vinci missions, houses, vehicles and expeditions remain available.';}
 if(ok&&action==='read'&&QUARTER_OBSERVATIONS[id]){q.observations=normalizeObservations([...(q.observations||[]),id]);text=QUARTER_OBSERVATIONS[id].text;}
 s.toast=text;s.toastT=5;return {ok,text,transition:action==='leave'&&ok};
}
export function stepQuarter(s,dt){const q=s.quarter;const f=quarterSurface(s.x,s.z,q.groundY);if(f){q.groundY=f.y;q.surface=f.floor.id;if(!q.visited.includes(q.surface))q.visited.push(q.surface);}if(q.groundY<-.4)q.low=true;const target=q.low?-2.38:-.15;q.waterY+=Math.sign(target-q.waterY)*Math.min(Math.abs(target-q.waterY),dt*.45);
 stepPorter(q,dt,{blocked:(x,z,y,r)=>quarterBlocked({quarter:{...q,groundY:y}},x,z,r),surface:quarterSurface});
 q.actors=QUARTER_ACTORS.map((a,i)=>{if(a.id==='neri')return porterActor(q);const t=(s.time+i*4)%a.period/a.period*2,phase=t<=1?t:2-t,progress=phase*(a.paths.length-1),k=Math.min(a.paths.length-2,Math.floor(progress)),u=progress-k,A=a.paths[k],B=a.paths[k+1];return {id:a.id,name:a.name,x:A[0]+(B[0]-A[0])*u,z:A[1]+(B[1]-A[1])*u,y:quarterSurface(A[0]+(B[0]-A[0])*u,A[1]+(B[1]-A[1])*u,A[2]+(B[2]-A[2])*u)?.y??A[2],yaw:Math.atan2((B[0]-A[0])*(t<=1?1:-1),(B[1]-A[1])*(t<=1?1:-1)),motion:'work'};});
 for(const k of['dodge','dodgeCD'])if(s.doors)s.doors[k]=Math.max(0,(s.doors[k]||0)-dt);if(s.life){s.life.aura=Math.max(0,s.life.aura-dt);s.life.spellCD=Math.max(0,s.life.spellCD-dt);s.life.focus=Math.min(60+15*(s.life.attrs.ingenuity||0),s.life.focus+dt*2);}
}
