import {inBadlands} from './frontier-core.mjs';
/* Calm, bounded Web Audio mixer. Music is strictly single-stream: different
 * compositions never overlap. Repetitive effects are density/rate limited. */
import {AUDIO_KEY,audioPreferences,MUSIC,scoreFor,spatialMix,surfaceFor} from './resonance-data.mjs';
import {doorLocation} from './doors-core.mjs';
import {validTargets,clearShot} from './resonance-core.mjs';
const files=new URL('./assets/resonance/',import.meta.url),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const cueMap={swing:['swing'],hit:['impact','Staff connects'],'doors-rival-hit':['impact','Staff connects'],'doors-rival-strike':['hurt','Rival strike'],'blocked-hit':['block','Strike braced'],'duel-hit':['hurt','Guard strike'],'doors-rival-yields':['success','Rival yields'],'duel-won':['success','The guard yields'],'town-duel':['success','Opponent yields'],'town-windup':['windup','Brace or dodge'],'town-hit':['hurt','Staff strike'],throw:['paper'],delivery:['success','Letter delivered'],chapter:['discovery','New commission stage'],relay:['lever','Waterwheel restored'],signals:['bell','Market bell'],folio:['discovery','Folio recovered'],complete:['success','Commission complete'],trade:['coin','Purchase complete'],refill:['loaded','Supplies restored'],recover:['enter','Returned to the workshop'],enter:['enter','Mounted vehicle'],exit:['exit','Dismounted'],scan:['magic','Mechanisms revealed'],collision:['collision','Collision'],jump:['jump'],'resonance-sling':['sling'],'resonance-reload':['reload','Reloading'],'resonance-loaded':['loaded','Sling ready'],'resonance-impact':['impact','Pellet connects'],'resonance-wall':['impact','Pellet strikes a surface'],'resonance-cover':['cover','In cover'],'resonance-special':['special','Special ability active'],'resonance-denied':['empty'],'resonance-empty':['empty','Pouch empty'],'resonance-discipline':['switch']};
const essential=new Set(['hurt','block','windup','success','discovery','empty','loaded','special']);
export function createResonanceAudio({getState,world,onStatus=()=>{}}){
 let config;try{config=audioPreferences(JSON.parse(localStorage.getItem(AUDIO_KEY)));}catch{config=audioPreferences();}
 let ctx=null,master=null,musicBus=null,effectsBus=null,ambienceBus=null,worldGain=null,compressor=null,analyser=null,wet=null;
 let available=true,initialized=false,unlocked=false,blocked=false,hidden=false,paused=false,session=false,listener={x:0,z:0,yaw:0},lastState=null,snapshot=null,stepDistance=0,stepIndex=0,ambientClock=0,birdAt=15,bellHour=-1;
 let requests=0,played=0,loadFailures=0,dropped=0,desired='vinci',desiredAge=0,chosen=null,nowPlaying='',slot=null,worldRoom=0,captionUntil=0,nowUntil=0,haptic=()=>{},lastCue='',motion=0,loopStart=null;
 const buffers=new Map(),voices=new Set(),loops=new Map(),eventCounts={},lastPlayed=new Map();
 let seenEvents=new WeakSet(),windups=new Set();
 const status=document.createElement('div');status.id='audio-status';status.setAttribute('role','status');status.hidden=true;document.body.append(status);
 const captions=document.createElement('div');captions.id='sound-caption';captions.setAttribute('role','status');captions.setAttribute('aria-live','polite');captions.hidden=true;document.body.append(captions);
 const now=document.createElement('div');now.id='now-playing';now.hidden=true;document.body.append(now);
 const save=()=>{try{localStorage.setItem(AUDIO_KEY,JSON.stringify(config));}catch{}};
 function report(){onStatus(inspect());const b=document.getElementById('sound');if(b){b.textContent=config.enabled?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(config.enabled));}}
 function gain(node,value,time=.08){if(ctx&&node)node.gain.setTargetAtTime(Math.max(0,value),ctx.currentTime,time);}
 function applyMix(){if(!ctx)return;gain(master,config.enabled?config.master:0);gain(musicBus,config.music*(paused?.28:1),.12);gain(effectsBus,config.effects);gain(ambienceBus,config.ambience);gain(worldGain,paused?.08:1,.12);const v=config.range==='night'?[-32,10,.02,.24]:config.range==='full'?[-10,3,.01,.18]:[-22,6,.012,.22];compressor.threshold.value=v[0];compressor.ratio.value=v[1];compressor.attack.value=v[2];compressor.release.value=v[3];}
 function graph(){if(ctx||!available)return !!ctx;const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C){available=false;return false;}try{ctx=new C({latencyHint:'interactive'});master=ctx.createGain();musicBus=ctx.createGain();effectsBus=ctx.createGain();ambienceBus=ctx.createGain();worldGain=ctx.createGain();compressor=ctx.createDynamicsCompressor();analyser=ctx.createAnalyser();analyser.fftSize=512;musicBus.connect(master);effectsBus.connect(master);ambienceBus.connect(worldGain);worldGain.connect(master);master.connect(compressor);compressor.connect(analyser);analyser.connect(ctx.destination);const rev=ctx.createConvolver(),imp=ctx.createBuffer(2,Math.floor(ctx.sampleRate*.4),ctx.sampleRate);for(let c=0;c<2;c++){const d=imp.getChannelData(c);let seed=711+c;for(let i=0;i<d.length;i++){seed=seed*16807%2147483647;d[i]=(seed/1073741823.5-1)*Math.exp(-i/(ctx.sampleRate*.08))*.08;}}rev.buffer=imp;wet=ctx.createGain();wet.gain.value=.012;effectsBus.connect(rev);rev.connect(wet);wet.connect(master);applyMix();initialized=true;ctx.onstatechange=()=>{unlocked=ctx.state==='running';if(unlocked){blocked=false;status.hidden=true;}report();};return true;}catch{available=false;loadFailures++;return false;}}
 async function unlock(){if(!config.enabled||hidden||!graph())return false;try{const r=ctx.resume();r?.catch(()=>{});await Promise.race([r,new Promise(q=>setTimeout(q,180))]);}catch{}unlocked=ctx.state==='running';blocked=!unlocked;if(blocked){status.textContent='Press Enter once if your browser requires audio permission. Gameplay does not wait for sound.';status.hidden=false;}else{status.hidden=true;startLoops();if(session&&!slot&&config.station!=='off')startMusic(config.station==='auto'?(chosen||'vinci'):config.station);slot?.element.play().catch(()=>{});}report();return unlocked;}
 const gesture=e=>{if(e.isTrusted&&config.enabled&&!hidden)unlock();};window.addEventListener('pointerdown',gesture,{passive:true});window.addEventListener('keydown',gesture);document.addEventListener('visibilitychange',()=>{hidden=document.hidden;if(hidden){slot?.element.pause();ctx?.suspend().catch(()=>{});}else if(config.enabled)unlock();});
 async function buffer(name,loop=false){const file=loop?'ambient-'+name+'.ogg':name+'.wav';if(!buffers.has(file))buffers.set(file,fetch(new URL(file,files)).then(r=>{if(!r.ok)throw Error(file);return r.arrayBuffer();}).then(a=>ctx.decodeAudioData(a)).catch(()=>{loadFailures++;return null;}));return buffers.get(file);}
 function cooldown(name,ui){if(ui)return 0;const density=config.density;if(density==='full')return name.startsWith('step-')?.16:.04;if(density==='balanced'){if(name.startsWith('step-'))return .34;if(['bird','coin','paper','swing','impact','door'].includes(name))return .45;return essential.has(name)?0:.18;}if(name==='windup')return .8;if(name.startsWith('step-'))return .62;if(name==='bird')return 24;if(['coin','paper','door','swing','impact','collision','lever'].includes(name))return .9;return essential.has(name)?.12:.55;}
 function play(name,{source=null,volume=.55,rate=1,caption:words=null,ui=false}={}){requests++;lastCue=name;eventCounts[name]=(eventCounts[name]||0)+1;const t=performance.now()/1000,wait=cooldown(name,ui),last=lastPlayed.get(name)||-1e9;if(t-last<wait){dropped++;return false;}lastPlayed.set(name,t);if(words&&config.captions&&!hidden){const m=spatialMix(listener,source);captions.textContent=(m.pan<-.4?'Left: ':m.pan>.4?'Right: ':'')+words;captions.hidden=false;captionUntil=performance.now()+1800;}if(!config.enabled||!unlocked||!ctx||hidden)return false;if(voices.size>=12){dropped++;return false;}const reservation={};voices.add(reservation);buffer(name).then(b=>{if(!b||!config.enabled||!unlocked||hidden||(!ui&&paused)){voices.delete(reservation);return;}const m=spatialMix(listener,source,18,config.mono),s=ctx.createBufferSource(),g=ctx.createGain(),pan=ctx.createStereoPanner();s.buffer=b;s.playbackRate.value=clamp(rate,.7,1.4);g.gain.value=clamp(volume*m.gain,0,.58);pan.pan.value=m.pan;s.connect(g);g.connect(pan);pan.connect(effectsBus);reservation.source=s;s.onended=()=>{s.disconnect();g.disconnect();pan.disconnect();voices.delete(reservation);};s.start();played++;}).catch(()=>{voices.delete(reservation);loadFailures++;});return true;}
 function startLoops(){if(loopStart)return loopStart;loopStart=Promise.all(['wind','water','room','wheel','chain'].map(async name=>{const b=await buffer(name,true);if(!b||!ctx)return;const src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=b;src.loop=true;g.gain.value=0;src.connect(g);g.connect(ambienceBus);src.start();loops.set(name,{src,g});}));return loopStart;}
 function disposeMusic(){if(!slot)return;slot.element.pause();slot.element.removeAttribute('src');slot.element.load();slot.source.disconnect();slot.gain.disconnect();slot=null;}
 function startMusic(id){if(!ctx||!unlocked||hidden||!config.enabled||config.station==='off')return;const entry=MUSIC.find(t=>t.id===id);if(!entry||slot?.id===id)return;disposeMusic();const element=new Audio(new URL(entry.file,files).href);element.loop=true;element.preload='auto';const source=ctx.createMediaElementSource(element),g=ctx.createGain();g.gain.value=0;source.connect(g);g.connect(musicBus);slot={id,element,source,gain:g};const current=slot;chosen=id;element.play().then(()=>{if(slot!==current)return;gain(g,1,.28);nowPlaying=entry.name;now.textContent='Now playing: '+entry.name;now.hidden=false;nowUntil=performance.now()+3000;report();}).catch(()=>{if(slot!==current)return;blocked=true;loadFailures++;});}
 function setStation(id){set({station:id});}
 function set(values){const before=config;config=audioPreferences({...config,...values});save();applyMix();if(before.enabled&&!config.enabled){slot?.element.pause();for(const v of voices)try{v.source?.stop();}catch{}ctx?.suspend().catch(()=>{});unlocked=false;}if(config.enabled&&!before.enabled)unlock();if(config.station!==before.station){desiredAge=99;chosen=null;if(config.station==='off'){disposeMusic();nowPlaying='';}else if(config.station!=='auto')startMusic(config.station);}report();}
 function update(s,dt,{playing=false,paused:isPaused=false,hidden:isHidden=false,cameraYaw=s.yaw}={}){session=playing;paused=isPaused;listener={x:s.x,z:s.z,yaw:cameraYaw};if(isHidden!==hidden){hidden=isHidden;if(hidden){slot?.element.pause();ctx?.suspend().catch(()=>{});}else if(config.enabled)unlock();}if(s!==lastState){lastState=s;snapshot={distance:s.distance,lift:s.lift,location:JSON.stringify(doorLocation(s,world)),credits:s.credits,health:s.health,focus:s.life.focus};seenEvents=new WeakSet(s.events);stepDistance=0;windups=new Set();}const nowTime=performance.now();if(nowTime>captionUntil)captions.hidden=true;if(nowTime>nowUntil)now.hidden=true;if(!session||hidden){applyMix();return;}const loc=doorLocation(s,world),threats=validTargets(s,world).filter(e=>Math.hypot(e.x-s.x,e.z-s.z)<12&&clearShot(s,world,s,e)),target=config.station==='auto'?(inBadlands(s)?'underways':scoreFor({level:loc.level,room:loc.room,minute:s.city.minute,z:s.z,danger:s.mode==='foot'&&threats.length>0})):config.station;if(target!==desired){desired=target;desiredAge=0;}else desiredAge+=dt;if(target!=='off'&&unlocked&&(slot===null||target!==chosen&&desiredAge>(target==='pursuit'?.8:7)))startMusic(target);applyMix();worldRoom=loc.level<0?.22:loc.room?.08:.01;gain(wet,worldRoom,.3);if(paused)return;motion=Math.min(1,Math.abs(s.speed)/14);const bed=(name,value,rate=1)=>{const b=loops.get(name);if(b){gain(b.g,value,.25);b.src.playbackRate.setTargetAtTime(rate,ctx.currentTime,.2);}},outside=!loc.room&&loc.level>=0,densityScale=config.density==='quiet'?.45:config.density==='balanced'?.72:1;bed('wind',(outside?(loc.level===3?.16:.035):.006)*densityScale);bed('water',(loc.level<0?.09:outside&&s.z>275?.055:Math.max(0,1-Math.hypot(s.x-11,s.z-190)/35)*.05)*densityScale);bed('room',(loc.room?.07:0)*densityScale);bed('wheel',(s.mode!=='foot'?motion*(s.mode==='car'?.11:.06):0)*densityScale,.72+motion*.5);bed('chain',(s.mode!=='foot'?motion*.045:0)*densityScale,.65+motion*.5);
  const traveled=s.distance-snapshot.distance;if(s.mode==='foot'&&s.lift<.02&&traveled>0&&traveled<4){stepDistance+=traveled;const stride=config.density==='quiet'?2.4:config.density==='balanced'?1.75:1.2;if(stepDistance>=stride){stepDistance%=stride;play('step-'+surfaceFor(s,world)+'-'+(stepIndex++%3),{volume:.16,rate:.95+(stepIndex%4)*.02});}}if(snapshot.lift>.08&&s.lift===0)play('land',{volume:.24});const location=JSON.stringify(loc);if(snapshot.location!==location){play('door',{volume:.25,caption:loc.level<0?'Cellar echoes':loc.room?'Inside '+loc.room.replaceAll('-',' '):null});stepDistance=0;}if(s.credits!==snapshot.credits)play('coin',{volume:.17});if(s.health<snapshot.health)haptic('hurt');if(s.life.focus<snapshot.focus-8&&s.life.aura>0)play('magic',{volume:.28});const nextWindups=new Set();for(const e of threats){const winding=['rival','monster'].includes(e.kind)?e.actor.phase==='windup':e.kind==='guard'?s.banditPhase==='windup':s.life.attackPending;if(winding){nextWindups.add(e.id);if(!windups.has(e.id)){play('windup',{source:e,volume:.42,caption:e.name+' raises a weapon'});haptic('warning');}}}windups=nextWindups;for(const e of s.events){if(seenEvents.has(e))continue;seenEvents.add(e);let cue=cueMap[e.type];if(!cue&&/complete|reward|finish/.test(e.type))cue=['success','Work complete'];if(cue){play(cue[0],{source:Number.isFinite(e.x)?e:null,volume:essential.has(cue[0])?.34:.24,caption:cue[1]});if(['duel-hit','doors-rival-strike','resonance-impact','doors-rival-yields'].includes(e.type))haptic(e.type==='doors-rival-yields'?'success':'impact');}}ambientClock+=dt;if(outside&&ambientClock>=birdAt&&config.density!=='quiet'){birdAt=ambientClock+(config.density==='balanced'?22:12);play('bird',{source:{x:s.x+16,z:s.z+12},volume:.08});}const hour=Math.floor(s.city.minute/60);if(bellHour<0)bellHour=hour;else if(hour!==bellHour){bellHour=hour;if(outside)play('bell',{source:{x:-10,z:139},volume:.22,caption:'Town clock: '+String(hour).padStart(2,'0')+':00'});}snapshot={distance:s.distance,lift:s.lift,location,credits:s.credits,health:s.health,focus:s.life.focus};}
 function inspect(){let rms=0;if(analyser&&ctx?.state==='running'){const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);rms=Math.sqrt(data.reduce((a,v)=>a+v*v,0)/data.length);}return {preferences:{...config},available,initialized,context:ctx?.state||'not-created',unlocked,blocked,nowPlaying,station:config.station,chosen,desired,voices:voices.size,musicVoices:Number(!!slot),loops:loops.size,requests,played,loadFailures,dropped,rms,lastCue,eventCounts:{...eventCounts},paused,hidden,worldRoom};}
 report();return {unlock,update,play,set,setStation,inspect,caption:(text,source)=>{if(config.captions&&text){const m=spatialMix(listener,source);captions.textContent=(m.pan<-.4?'Left: ':m.pan>.4?'Right: ':'')+text;captions.hidden=false;captionUntil=performance.now()+1800;}},get preferences(){return {...config};},setHaptics(fn){haptic=fn||(()=>{});},toggle(){set({enabled:!config.enabled});},setPaused(v){paused=v;applyMix();},start(){session=true;unlock();},preview(name='success'){unlock().then(()=>play(name,{volume:.34,ui:true,caption:'Sound preview'}));}};
}
