/* Controller-first dispatch, mixer and radial choices. Every displayed action
 * calls a real game operation. This is a guild notebook, not an online store. */
import {AUDIO_DEFAULTS,CONSOLE_KEY,consolePreferences,TOOLS,STATIONS,DISCIPLINES,radialIndex} from './resonance-data.mjs';
import {chooseTool,chooseDiscipline,validTargets,clearShot} from './resonance-core.mjs';
import {stats,notify} from './life-core.mjs';
export function createResonanceUI({getState,world,audio,setPause,save,active,playing,actions}){
 let preferences;try{preferences=consolePreferences(JSON.parse(localStorage.getItem(CONSOLE_KEY)));}catch{preferences=consolePreferences();}
 const persist=()=>{try{localStorage.setItem(CONSOLE_KEY,JSON.stringify(preferences));}catch{}};
 let wheel=null,index=0,variant=0,initial=null,changed=false,cash=-1,cashUntil=0;
 const byId=id=>document.getElementById(id);
 const dialog=document.createElement('dialog');dialog.id='dispatch-dialog';dialog.setAttribute('aria-label','Guild dispatch');document.body.append(dialog);
 const mixer=document.createElement('dialog');mixer.id='audio-dialog';mixer.setAttribute('aria-label','Audio and console settings');document.body.append(mixer);
 const radial=document.createElement('section');radial.id='guild-wheel';radial.hidden=true;radial.setAttribute('role','dialog');radial.setAttribute('aria-label','Radial selection');radial.innerHTML='<div class="wheel-shell"><p id="wheel-kicker"></p><h2 id="wheel-title"></h2><div class="wheel-ring" id="wheel-ring"></div><p id="wheel-detail" aria-live="polite"></p><p id="wheel-variant"></p><div class="wheel-controls"><button id="wheel-cancel">B / Cancel</button><button id="wheel-confirm">A / Select</button></div><p class="wheel-help">Right stick points. D-pad left/right changes variants; up/down changes category. Release the held button to select.</p></div>';document.body.append(radial);
 byId('wheel-cancel').onclick=()=>closeWheel(false);byId('wheel-confirm').onclick=()=>closeWheel(true);
 const vitals=document.createElement('div');vitals.id='console-vitals';
 vitals.innerHTML=['health','guard','focus'].map((id,i)=>`<div class="vital-row"><span>${['Vitality','Guard','Focus'][i]}</span><div id="vital-${id}" class="vital-track" role="progressbar" aria-label="${['Vitality','Guard reserve','Special ability focus'][i]}" aria-valuemin="0" aria-valuemax="100"><i></i></div></div>`).join('');byId('minimap-button').after(vitals);
 const reticle=document.createElement('div');reticle.id='aim-reticle';reticle.hidden=true;reticle.innerHTML='<i></i><span id="aim-label"></span>';document.body.append(reticle);
 const readout=document.createElement('div');readout.id='equipment-readout';readout.hidden=true;document.body.append(readout);
 const cue=document.createElement('div');cue.id='console-stance';cue.hidden=true;document.body.append(cue);
 const lists=()=>wheel==='tools'?TOOLS:wheel==='music'?STATIONS:DISCIPLINES;
 function renderWheel(){
  if(!wheel)return;const list=lists(),entry=list[index];byId('wheel-kicker').textContent='GUILD / '+(wheel==='tools'?'EQUIPMENT':wheel==='music'?'MUSIC':'DISCIPLINES');byId('wheel-title').textContent=entry.name;
  const ring=byId('wheel-ring');ring.replaceChildren();
  list.forEach((t,i)=>{const b=document.createElement('button');b.textContent=t.name;b.setAttribute('aria-pressed',String(i===index));b.dataset.wheelIndex=String(i);const a=i/list.length*Math.PI*2;b.style.left=50+Math.sin(a)*35+'%';b.style.top=50-Math.cos(a)*35+'%';b.onclick=()=>{index=i;variant=wheel==='tools'?(getState().resonance.variants[t.id]||0):0;renderWheel();};ring.append(b);});
  const middle=document.createElement('span');middle.className='wheel-center';middle.textContent=wheel==='tools'?'READY':wheel==='music'?'LISTEN':'TRAIN';ring.append(middle);
  byId('wheel-detail').textContent=entry.detail+(wheel==='disciplines'?' Disciplines change this apprentice\'s ability; they are not separate protagonists.':'');
  byId('wheel-variant').textContent=wheel==='tools'?entry.variants[variant]+(entry.id==='lantern'&&!getState().life.flags.lantern?' / Earn the Lantern in the existing story.':''):wheel==='music'?'All five pieces are original, locally hosted game music.':'Your deliveries, missions and saved progress are shared.';
 }
 function openWheel(kind){if(!active()||!['tools','music','disciplines'].includes(kind))return;wheel=kind;const s=getState(),list=lists(),id=kind==='tools'?s.resonance.tool:kind==='music'?audio.preferences.station:s.resonance.discipline;index=Math.max(0,list.findIndex(t=>t.id===id));variant=kind==='tools'?s.resonance.variants[id]:0;initial={index,variant};radial.hidden=false;document.body.classList.add('wheel-open');renderWheel();audio.play('ui-select',{ui:true,volume:.14});}
 function updateWheel(x,y,across=0,along=0){if(!wheel)return;const list=lists(),before=index,bv=variant;index=radialIndex(x,y,list.length,index);if(along)index=(index+along+list.length)%list.length;if(index!==before)variant=wheel==='tools'?(getState().resonance.variants[list[index].id]||0):0;if(across){if(wheel==='tools'){const n=list[index].variants.length;variant=(variant+across+n)%n;}else index=(index+across+list.length)%list.length;}if(index!==before||variant!==bv){renderWheel();audio.play('ui-move',{ui:true,volume:.12});}}
 function closeWheel(commit){if(!wheel)return;const list=lists(),id=list[index].id,s=getState();if(commit){if(wheel==='tools')chooseTool(s,id,variant);else if(wheel==='music')audio.setStation(id);else chooseDiscipline(s,world,id);save();}wheel=null;radial.hidden=true;document.body.classList.remove('wheel-open');audio.play(commit?'ui-select':'ui-back',{ui:true,volume:.14});}
 function handoff(fn){dialog.close();setPause(false);fn();}
 function dispatch(){if(!active())return;const s=getState();setPause(true);
  dialog.innerHTML='<div class="dispatch-heading"><div><p>LEONARDO\'S GUILD</p><h2>Guild dispatch</h2></div><button id="dispatch-close">B / Close</button></div><p id="dispatch-message"></p><div class="dispatch-grid"></div><p class="dispatch-foot">D-pad or left stick moves between applications. A opens. B closes. Commissions are still completed at their actual desks and work sites.</p>';
  byId('dispatch-message').textContent=s.toast||'Letters, commissions, supplies and discoveries in one place. Your game remains saved on this device.';
  const choices=[['nearby','Nearby','People, mechanisms and shops',actions.nearby],['adventures','Adventures','Track the six investigations',actions.guide],['journal','Notebook','Original missions and character',actions.journal],['map','City map','Locate your next objective',actions.map],['equipment','Equipment','Staff, sling, letters and Lantern',()=>openWheel('tools')],['music','Music','Adaptive score and station wheel',()=>openWheel('music')],['audio','Audio / controls','Mixer, lock-on and controller profile',openAudio],['save','Quick save','Keep current progress',()=>{save();notify(getState(),'Progress saved on this device.','resonance-saved');audio.play('loaded',{ui:true,volume:.2});}]];
  for(const [id,title,sub,fn]of choices){const b=document.createElement('button');b.dataset.dispatch=id;const name=document.createElement('strong'),small=document.createElement('span');name.textContent=title;small.textContent=sub;b.append(name,small);b.onclick=()=>handoff(fn);dialog.querySelector('.dispatch-grid').append(b);}
  byId('dispatch-close').onclick=()=>dialog.close();dialog.showModal();
 }
 function openAudio(){
  closeWheel(false);setPause(true);const p=audio.preferences;
  mixer.innerHTML='<div class="dispatch-heading"><div><p>RESONANCE / SOUND AND CONTROL</p><h2>Make the city sound right.</h2></div><button id="audio-close">B / Close</button></div><div class="audio-settings" data-pad-scroll></div><p id="audio-diagnostic" role="status"></p><div class="audio-bottom"><button id="audio-preview">Play a sound preview</button><button id="audio-defaults">Restore audio defaults only</button></div>';
  const body=mixer.querySelector('.audio-settings');
  function checkbox(id,title,value,fn){const l=document.createElement('label');l.className='audio-checkbox';const b=document.createElement('input');b.type='checkbox';b.id=id;b.checked=value;b.onchange=()=>fn(b.checked);l.append(b,document.createTextNode(title));body.append(l);}
  function select(id,title,items,value,fn){const l=document.createElement('label');l.textContent=title;const b=document.createElement('select');b.id=id;for(const [v,text]of items){const o=document.createElement('option');o.value=v;o.textContent=text;b.append(o);}b.value=value;b.onchange=()=>fn(b.value);l.append(b);body.append(l);}
  checkbox('audio-enabled','Enable sound',p.enabled,v=>audio.set({enabled:v}));
  for(const [id,title]of [['master','Master volume'],['music','Music'],['effects','Sound effects'],['ambience','Environment and vehicles']]){const l=document.createElement('label');const name=document.createElement('span');name.textContent=title;const output=document.createElement('output');output.id='audio-'+id+'-value';output.textContent=Math.round(p[id]*100)+'%';const input=document.createElement('input');input.type='range';input.id='audio-'+id;input.min='0';input.max='100';input.step='5';input.value=String(Math.round(p[id]*100));input.setAttribute('aria-label',title);input.oninput=()=>{output.textContent=input.value+'%';audio.set({[id]:Number(input.value)/100});};l.append(name,output,input);body.append(l);}
  select('audio-station','Music selection',STATIONS.map(t=>[t.id,t.name]),p.station,v=>audio.setStation(v));
  select('audio-range','Dynamic range',[['full','Full dynamics'],['balanced','Balanced'],['night','Night / gentler peaks']],p.range,v=>audio.set({range:v}));
  checkbox('audio-mono','Center sound effects for mono listening',p.mono,v=>audio.set({mono:v}));checkbox('audio-captions','Caption important sounds',p.captions,v=>audio.set({captions:v}));
  select('controller-profile','Controller profile',[['console','Contextual console (recommended)'],['classic','Classic Open Doors v0.7']],preferences.profile,v=>{preferences.profile=v;persist();});
  checkbox('controller-lock','Aim assistance: lock onto visible rivals',preferences.lockOn,v=>{preferences.lockOn=v;persist();});checkbox('controller-rumble','Controller vibration when supported',preferences.haptics,v=>{preferences.haptics=v;persist();});checkbox('controller-sprint','Repeated A taps extend sprint (LS click also toggles it)',preferences.repeatSprint,v=>{preferences.repeatSprint=v;persist();});
  const help=document.createElement('p');help.className='audio-help';help.textContent='Console: left stick moves relative to the camera on foot; right stick looks. A jumps or climbs, repeated A taps sprint. LT aims; RT uses your equipped tool. Hold LB for equipment. X reloads while aiming the sling; hold X to interact instead. RB uses nearby cover. Y mounts. In vehicles, RT accelerates, LT brakes/reverses, RB handbrakes, A ducks and LS sounds the bell. Up opens dispatch; hold left for music; tap left for the vehicle lamp. Both stick clicks activate your discipline. Classic retains the previous mapping. The music and effects are original, not recordings from a reference game.';body.append(help);
  byId('audio-close').onclick=()=>mixer.close();byId('audio-preview').onclick=()=>audio.preview();byId('audio-defaults').onclick=()=>{audio.set({...AUDIO_DEFAULTS});mixer.close();openAudio();};mixer.showModal();update();
 }
 dialog.addEventListener('close',()=>setPause(false));mixer.addEventListener('close',()=>setPause(false));
 function update(){
  const s=getState(),c=s.resonance;if(!c)return;
  const values={health:s.health/stats(s).maxHealth*100,guard:c.guard,focus:s.life.focus/stats(s).maxFocus*100};
  for(const [id,v]of Object.entries(values)){const el=byId('vital-'+id);el.setAttribute('aria-valuenow',String(Math.round(v)));el.querySelector('i').style.transform='scaleX('+Math.max(0,Math.min(1,v/100))+')';}
  reticle.hidden=!playing()||!c.aim||!active();reticle.classList.toggle('locked',!!c.lock);byId('aim-label').textContent=c.lock?(validTargets(s,world).find(t=>t.id===c.lock)?.name||''):'Free aim';
  if(s.credits!==cash){cash=s.credits;cashUntil=performance.now()+4500;}readout.hidden=!playing()||!active()||!(c.aim||c.reload>0||performance.now()<cashUntil);
  readout.textContent=(c.tool==='sling'?'SLING '+c.ready+' / '+c.reserve+(c.reload>0?' / RELOADING':''):TOOLS.find(t=>t.id===c.tool).name.toUpperCase())+' | '+s.credits+' florins';
  cue.hidden=!playing()||!active()||!c.cover&&c.special<=0;cue.textContent=c.special>0?DISCIPLINES.find(d=>d.id===c.discipline).name+' ability / '+Math.ceil(c.special)+'s':'IN COVER / RB or move away to leave';
  if(mixer.open){const info=audio.inspect();byId('audio-diagnostic').textContent=info.blocked?'The browser needs one Enter key press before it permits audio. All controller menus remain usable.':!info.available?'This browser cannot create an audio context. Visual cues remain available.':(info.nowPlaying?'Now playing: '+info.nowPlaying+'. ':'')+'Audio '+info.context+'. All audio is hosted with the game.';}
 }
 function drawMap(g,X,Z,full){const s=getState();for(const e of validTargets(s,world)){if(Math.hypot(e.x-s.x,e.z-s.z)>40||!clearShot(s,world,s,e))continue;const x=X(e.x),z=Z(e.z);g.fillStyle='#e6a28f';g.beginPath();g.arc(x,z,full?4:3,0,Math.PI*2);g.fill();if(e.actor?.yaw!==undefined){const angle=e.actor.yaw,scale=full?6:11;g.fillStyle='#df856a38';g.beginPath();g.moveTo(x,z);g.lineTo(x+Math.sin(angle-.55)*scale,z+Math.cos(angle-.55)*scale);g.lineTo(x+Math.sin(angle+.55)*scale,z+Math.cos(angle+.55)*scale);g.closePath();g.fill();}}}
 window.addEventListener('keydown',e=>{if(!wheel)return;e.stopImmediatePropagation();if(['Escape','KeyP'].includes(e.code)){closeWheel(false);e.preventDefault();}else if(e.code==='Enter'||e.code==='Space'){closeWheel(true);e.preventDefault();}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)){updateWheel(0,0,e.code==='ArrowLeft'?-1:e.code==='ArrowRight'?1:0,e.code==='ArrowUp'?-1:e.code==='ArrowDown'?1:0);e.preventDefault();}},{capture:true});
 return {dispatch,openAudio,openWheel,updateWheel,closeWheel,cancelWheel:()=>closeWheel(false),wheelActive:()=>wheel,timeScale:()=>wheel?.18:1,update,drawMap,get preferences(){return {...preferences};},inspect:()=>({preferences:{...preferences},wheel,index,variant}),close(){if(wheel){closeWheel(false);return true;}if(mixer.open){mixer.close();return true;}if(dialog.open){dialog.close();return true;}return false;}};
}
