import {test} from 'node:test';
import assert from 'node:assert/strict';
import {unit,at,tangent,projected,move,geo,angle,dot,cross,sub,mul,length} from '../planet/math.mjs';
import {makeWorld,RADIUS,position,surfaceRadius,VERSION,SAVE_KEY} from '../planet/world.mjs';
import {newState,step,enterExit,throwPaper,interact,saveData,readSave,inspect,phase} from '../planet/model.mjs';
const w=makeWorld();
function approx(a,b,e=1e-7){assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);}
function play(s,ticks,input={},world=w){for(let i=0;i<ticks;i++)step(s,world,input,1/60);}
function drive(s,to,r=1.5,maxTicks=4000){for(let i=0;i<maxTicks;i++){const d=geo(s.n,to,RADIUS);if(d<r){s.speed=0;return i;}
 const f=projected(sub(to,s.n),s.n),a=Math.atan2(dot(cross(s.f,f),s.n),dot(s.f,f)),want=Math.min(5,Math.sqrt(Math.max(.1,d-r)*3));step(s,w,{throttle:Math.abs(a)>1.4?0:s.speed>want+.3?-1:s.speed<want-.15?1:0,steer:Math.abs(a)<.015?0:a>0?-1:1},1/60);
 }throw Error('Cannot reach route point '+JSON.stringify({n:s.n,to,speed:s.speed}));}
test('The world is a deterministic sphere with the same radius in math and rendering data',()=>{assert.deepEqual(makeWorld(),w);assert.equal(w.radius,RADIUS);assert.equal(VERSION,'0.2.0');assert.equal(w.ring.length,257);assert.ok(w.homes.length>10&&w.trees.length>80);approx(geo(w.ring[0],w.ring.at(-1),RADIUS),0,1e-5);for(const h of w.homes)approx(length(h.n),1);});
test('One full great-circle trip returns to its start and transported heading without a map seam',()=>{let n=at(0),f=tangent(n);const origin=[...n],heading=[...f];for(let i=0;i<4000;i++)({n,f}=move(n,f,2*Math.PI*RADIUS/4000,RADIUS));approx(geo(n,origin,RADIUS),0,1e-4);approx(dot(f,heading),1);approx(dot(f,n),0);});
test('Movement crosses both poles and the opposite side with stable tangent heading',()=>{let n=[0,1,0],f=[0,0,1],negative=false;for(let i=0;i<1000;i++){({n,f}=move(n,f,.25,RADIUS));if(n[1]<-.9)negative=true;approx(length(n),1);approx(length(f),1);approx(dot(n,f),0);}assert.ok(negative);});
test('Reverse follows the surface backward rather than switching the player to another map',()=>{const n=at(.8,.2),f=tangent(n),go=move(n,f,15,RADIUS),back=move(go.n,go.f,-15,RADIUS);approx(geo(back.n,n,RADIUS),0,1e-5);approx(dot(back.f,f),1);});
test('Inspection proves altitude, 3D world position and up are radial; returned arrays cannot mutate state',()=>{const s=newState(),d=inspect(s,w);approx(length(d.position),surfaceRadius(s.n));approx(dot(unit(d.position),d.radialUp),1);d.n[0]=100;d.heading[0]=100;assert.notEqual(s.n[0],100);assert.notEqual(s.f[0],100);});
test('The simulated rider crosses the back of an unblocked globe with normal acceleration',()=>{const s=newState();play(s,1900,{throttle:1},{...w,obstacles:[]});assert.ok(s.distance>190);approx(length(s.n),1);assert.ok(s.steps===1900);assert.ok(s.n.every(Number.isFinite));});
test('A jump leaves the curved surface and gravity returns it to that surface',()=>{const s=newState();step(s,w,{jump:true});assert.ok(s.alt>0);play(s,100);assert.equal(s.alt,0);assert.equal(s.vy,0);});
test('High-speed collision is checked in small great-circle steps and cannot cut through a house',()=>{const s=newState(),wall={id:'wall',n:move(s.n,s.f,1.6,RADIUS).n,r:.6};s.mode='car';s.speed=13;play(s,30,{throttle:1},{...w,obstacles:[wall]});assert.ok(geo(s.n,wall.n,RADIUS)>=wall.r+.88-1e-7);assert.ok(s.collisions>0);});
test('Changing rides requires a stopped actor and a nearby vehicle',()=>{const s=newState();s.speed=4;assert.equal(enterExit(s,w),false);s.speed=0;assert.ok(enterExit(s,w));assert.equal(s.mode,'foot');assert.ok(enterExit(s,w));assert.equal(s.mode,'bike');const a=newState();a.mode='foot';a.n=at(-2,-.7);assert.equal(enterExit(a,w),false);});
test('A paper delivery requires a real projectile swept contact, not merely pressing an action',()=>{const s=newState();drive(s,at(.13),1.2);const before=s.delivered.size;assert.ok(throwPaper(s,w));assert.equal(s.delivered.size,before);play(s,100);assert.ok(s.delivered.size>before);assert.equal(s.papers,19);const credit=s.credits;play(s,100);assert.equal(s.credits,credit);});
test('The first edition remains a connected delivery/relay/return scenario',()=>{const s=newState();for(const u of [.13,.40,.74]){drive(s,at(u,.02),1.5);assert.ok(throwPaper(s,w));play(s,90);}assert.equal(s.delivered.size,3);assert.equal(phase(s),1);drive(s,at(1.13,.06),1.3);drive(s,at(1.18,.13),1.2);assert.ok(interact(s,w));assert.ok(s.relay);assert.equal(phase(s),2);assert.equal(s.completed,false);});
test('The local relay has real proximity/speed gates and awards once',()=>{const s=newState();assert.equal(s.relay,false);interact(s,w);assert.equal(s.relay,false);s.n=[...w.relay.n];s.speed=3;assert.equal(interact(s,w),false);s.speed=0;interact(s,w);const credits=s.credits;interact(s,w);assert.equal(credits,s.credits);assert.equal(s.relay,true);});
test('Saved planet progress is bounded and separate from the old flat-city key',()=>{assert.equal(SAVE_KEY,'svgn.city.planet.v1');const s=newState();s.delivered.add('maple');s.relay=true;const d=readSave(JSON.stringify(saveData(s)),w);assert.deepEqual(d.delivered,['maple']);assert.equal(d.relay,true);assert.equal(d.completed,false);assert.equal(readSave('{oops',w),null);assert.equal(readSave('x'.repeat(5000),w),null);const bad=readSave(JSON.stringify({version:1,delivered:['maple','fake','maple'],credits:1e99,completed:true}),w);assert.deepEqual(bad.delivered,['maple']);assert.equal(bad.completed,false);assert.equal(bad.credits,10000);});
test('No time input can create NaN state or a huge uncontrolled movement step',()=>{const s=newState(),p=JSON.stringify(s.n);step(s,w,{throttle:1},NaN);assert.equal(JSON.stringify(s.n),p);step(s,w,{throttle:1},Infinity);assert.equal(JSON.stringify(s.n),p);step(s,w,{throttle:1},10000);assert.ok(s.distance<.1);});
