'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=__dirname;
const data=JSON.parse(fs.readFileSync(path.join(ROOT,'groups.json'),'utf8'));
const parentSources=[...JSON.parse(fs.readFileSync(path.join(ROOT,'../sources.json'),'utf8')).sources,...JSON.parse(fs.readFileSync(path.join(ROOT,'../sources-more.json'),'utf8')).sources];
const sourceMap=new Map(parentSources.map(s=>[s.id,s]));
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(label,url)=>{const u=new URL(url,'https://v5ma.github.io/theology-wiki/comparative-religion/abrahamic-inheritance/');if(u.protocol!=='https:')throw Error('Unsafe URL');return '<a href="'+esc(url)+'">'+esc(label)+'</a>';};
const slug=x=>x.id+'.html';
const groupsDir=path.join(ROOT,'groups');fs.mkdirSync(groupsDir,{recursive:true});
const nav='<nav aria-label="Atlas navigation">'+link('Atlas index','../index.html')+link('Comparative religion directory','../../directory.html')+link('Comparative studies','../../index.html')+link('Apocalyptic Repair Theology','../../../san-reader.html?page=apocalyptic-repair-theology')+'</nav>';
const style='<link rel="stylesheet" href="../../series.css"><link rel="stylesheet" href="../atlas.css">';
function pageShell(g,body){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+esc(g.continuity_claim)+'"><title>'+esc(g.name)+' | Abrahamic inheritance atlas | Theology Wiki</title>'+style+'</head><body><a class="skip" href="#main">Skip to content</a><header><p class="eyebrow">THEOLOGY WIKI / ABRAHAMIC INHERITANCE ATLAS / SEPTEMBER 21, 2026</p><h1>'+esc(g.name)+'</h1><p class="lede">'+esc(g.continuity_claim)+'</p>'+nav+'</header><main id="main">'+body+'</main><footer><p>This page classifies a continuity claim; it does not decide which religion is true, chosen or historically superior. Living communities and ancient textual traditions are not interchangeable.</p><p>'+link('Return to all 60 entries','../index.html')+'</p></footer></body></html>\n';}
function sourceList(g){if(!g.source_ids.length)return '<p class="notice">Dedicated source expansion is still pending for this page. The linked parent study is the current Wiki context and should not be mistaken for a complete denominational history.</p>';return '<div class="source-list">'+g.source_ids.map(id=>{const s=sourceMap.get(id);if(!s)throw Error('Missing parent source '+id+' for '+g.id);return '<p>'+link(s.title,'../../sources.html#'+id)+'</p>';}).join('')+'</div>';}
const byFamily=new Map();for(const g of data.groups){if(!byFamily.has(g.family))byFamily.set(g.family,[]);byFamily.get(g.family).push(g);}
const files=[];
function write(file,text){fs.writeFileSync(path.join(ROOT,file),text);files.push({path:file,sha256:crypto.createHash('sha256').update(text).digest('hex')});}
for(const g of data.groups){
 const related=(byFamily.get(g.family)||[]).filter(x=>x.id!==g.id).slice(0,6);
 const body='<section><h2>Relationship to Abraham, Israel or covenant</h2><p>'+esc(g.continuity_claim)+'</p><p><strong>Claim type:</strong> '+esc(g.claim_type)+'</p><p>'+esc(g.scope_note)+'</p></section>'+
 '<section><h2>What this page represents</h2><p>'+esc(g.summary)+'</p><p><strong>Wiki research status:</strong> '+esc(g.research_status)+'.</p></section>'+
 '<section><h2>Existing Theology Wiki context</h2><p>'+link('Open the existing developed study or directory context',g.existing_wiki)+'</p>'+sourceList(g)+'</section>'+
 '<section><h2>Related traditions in this atlas</h2>'+(related.length?related.map(r=>'<p>'+link(r.name,slug(r))+' — '+esc(r.claim_type)+'.</p>').join(''):'<p>No same-family page is currently indexed.</p>')+'</section>';
 write('groups/'+slug(g),pageShell(g,body));
}
const claimTypes=[...new Set(data.groups.map(g=>g.claim_type))].sort();
const families=[...new Set(data.groups.map(g=>g.family))].sort();
const cards=data.groups.map(g=>'<article class="filter-record atlas-card" data-kind="'+esc(g.claim_type)+'" data-family="'+esc(g.family)+'" data-search="'+esc([g.name,g.family,g.claim_type,g.continuity_claim,g.summary].join(' '))+'"><p class="meta">'+esc(g.family)+' / '+esc(g.claim_type)+'</p><h2>'+link(g.name,'groups/'+slug(g))+'</h2><p>'+esc(g.continuity_claim)+'</p></article>').join('\n');
const index='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+esc(data.scope)+'"><title>'+esc(data.title)+' | Theology Wiki</title><link rel="stylesheet" href="../series.css"><link rel="stylesheet" href="atlas.css"></head><body><a class="skip" href="#main">Skip to content</a><header><p class="eyebrow">THEOLOGY WIKI / ABRAHAMIC INHERITANCE ATLAS / SEPTEMBER 21, 2026</p><h1>'+esc(data.title)+'</h1><p class="lede">'+esc(data.scope)+'</p><nav><a href="../directory.html">Tradition directory</a><a href="../index.html">Comparative studies</a><a href="../sources.html">Source scopes</a><a href="../egypt-emanation/index.html">Egypt and religious genealogy</a></nav></header><main id="main"><p class="notice">'+data.count+' dedicated group pages are indexed here. Inclusion does not mean the group claims to be the chosen people. The classification says what kind of relationship, if any, the Wiki is tracking.</p><div class="controls"><label>Search all entries<input id="query" type="search"></label><label>Continuity claim<select id="kind"><option value="">All claim types</option>'+claimTypes.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('')+'</select></label><label>Family<select id="family"><option value="">All families</option>'+families.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('')+'</select></label><button id="reset" type="button">Reset</button></div><p id="count" role="status" aria-live="polite">'+data.count+' of '+data.count+' entries shown.</p><p id="empty" hidden>No entries match these filters.</p><div id="cards">'+cards+'</div><noscript><p>All 60 entries and links remain visible without JavaScript.</p></noscript></main><footer><p>The atlas distinguishes direct Israelite continuity, Jewish covenant continuity, Christian inheritance, restoration/remnant claims, Islamic Abrahamic restoration, progressive revelation, genealogical relationship and non-Abrahamic comparison.</p></footer><script src="reader.js"></script></body></html>\n';
write('index.html',index);
write('index.json',JSON.stringify({schema_version:1,edition_date:data.edition_date,title:data.title,scope:data.scope,count:data.count,groups:data.groups.map(g=>({...g,url:'groups/'+slug(g)}))},null,2)+'\n');
write('READING.md','This is the plain-text index of the '+data.count+' dedicated group pages in the Abrahamic inheritance atlas. Inclusion is not an endorsement of any chosenness claim.\n\n'+data.groups.map(g=>g.name+'\nClaim type: '+g.claim_type+'\nFamily: '+g.family+'\n\n'+g.continuity_claim+'\n\n'+g.scope_note+'\n\nExisting Wiki context: '+g.existing_wiki).join('\n\n---\n\n')+'\n');
fs.writeFileSync(path.join(ROOT,'build-report.json'),JSON.stringify({schema_version:1,edition_date:data.edition_date,counts:{groups:data.groups.length,group_pages:data.groups.length,claim_types:claimTypes.length,families:families.length,html_pages:data.groups.length+1},files},null,2)+'\n');
console.log(JSON.stringify({groups:data.groups.length,claim_types:claimTypes.length,families:families.length,generated_html:data.groups.length+1}));
