"""Real-origin atlas, challenge, chronology and content-manifest verification."""
from pathlib import Path
import hashlib
import json

def run_atlas_checks(page, ctx, open_page, navigate, check, screenshot, OUT, BASE):
    def open_(slug, extra=''):
        open_page(page, slug, extra)
        page.wait_for_function('(slug)=>document.querySelector("#article-body").dataset.atlasReady===slug', arg=slug)
    page.set_viewport_size({'width': 1440, 'height': 1000})
    open_('source-atlas')
    check('Atlas distinguishes 29 typed records from a count of ancient works', '29 records' in page.locator('#article-body').inner_text() and page.locator('#atlas-list a').count() == 29)
    page.locator('#atlas-kind').select_option('translation')
    check('Translation filter isolates six access records', page.locator('#atlas-list a').count() == 6)
    page.locator('#atlas-search').fill('zzzz-unmatched')
    check('Atlas empty state permits recovery', 'No records match' in page.locator('#atlas-list').inner_text())
    page.locator('#atlas-search').fill('')
    page.locator('#atlas-kind').select_option('')
    page.locator('#atlas-selected').select_option('translation-kings-web')
    page.locator('#atlas-compare').select_option('translation-kings-brenton')
    check('Comparison preserves two distinct translated witnesses', page.locator('#atlas-cards .atlas-record').count() == 2 and '480th' in page.locator('#atlas-cards').inner_text() and '440th' in page.locator('#atlas-cards').inner_text())
    check('Selected atlas record has a shareable URL', 'record=translation-kings-web' in page.url)
    page.locator('#atlas-related a').first.click()
    check('Source relationship links select a record without dropping the view', page.locator('#atlas-selected').count() == 1)
    with page.expect_download() as ev:
        page.locator('#atlas-export').click()
    data = json.loads(Path(ev.value.path()).read_text())
    check('Atlas export retains typed edges and explicit open leads', len(data['edges']) == 21 and len([r for r in data['records'] if r['kind'] == 'research-lead']) == 3)
    screenshot(page, 'atlas-desktop.png')
    open_('source-atlas', '&record=fragment-manetho')
    check('Deep atlas URL opens the exact mediated source', page.locator('#atlas-selected').input_value() == 'fragment-manetho' and 'Josephus' in page.locator('#atlas-cards').inner_text())
    open_('argument-challenges', '&challenge=firstborn-narration')
    check('Four bounded challenges retain outcomes and remaining work', page.locator('.atlas-challenge').count() == 4 and 'Still to examine' in page.locator('#article-body').inner_text())
    check('Recovered famine qualification is visible in an attributed original excerpt', 'would not selectively target the first born' in page.locator('#challenge-firstborn-narration').inner_text())
    page.locator('#challenge-firstborn-narration .atlas-passage a').click()
    page.locator('#turn-23').wait_for()
    check('Challenge source opens exact original author turn', 'Micah Blumberg' in page.locator('#turn-23 header').inner_text())
    open_('argument-challenges', '&challenge=institution-not-motif')
    check('Institutional challenge exposes the author proposal and AI restatement separately', page.locator('#challenge-institution-not-motif .atlas-passage').count() == 2 and 'Self Aware Networks GPT' in page.locator('#challenge-institution-not-motif').inner_text())
    screenshot(page, 'challenge-institution.png')
    open_('exodus-to-temple-competing-chronologies')
    check('Foundation experiment renders four distinct interval records', page.locator('.atlas-interval').count() == 4)
    check('Ordinal default exposes 479 elapsed years and 1446 BCE', '967 + 479 = 1446' in page.locator('[data-interval="kings-480"]').inner_text())
    page.locator('#interval-full').check()
    check('Counting switch changes only the ordinal convention', '1447 BCE' in page.locator('[data-interval="kings-480"]').inner_text() and '1559 BCE' in page.locator('[data-interval="josephus-592"]').inner_text())
    page.locator('#interval-year').fill('0')
    check('Year zero produces a visible error instead of a false date', page.locator('#interval-results').inner_text() == '' and 'from 1 to 5000' in page.locator('#interval-error').inner_text())
    page.locator('#interval-anchor').select_option('destruction')
    check('Destruction comparison excludes foundation intervals', page.locator('.atlas-interval').count() == 2 and page.locator('[data-interval="kings-480"]').count() == 0)
    check('Josephus whole-year system remains internally inspectable', '1648 BCE' in page.locator('[data-interval="josephus-1062"]').inner_text() and '1056 BCE' in page.locator('[data-interval="josephus-470"]').inner_text())
    page.locator('#atlas-chronology').scroll_into_view_if_needed()
    page.screenshot(path=str(OUT/'interval-experiment.png'))
    open_('museum-trails')
    check('Museum content trails expose eleven stops with full arguments', page.locator('.atlas-trail').count() == 3 and page.locator('.atlas-stop').count() == 11 and page.locator('.atlas-stop a').count() >= 11)
    with page.expect_download() as ev:
        page.locator('#museum-manifest').click()
    museum = json.loads(Path(ev.value.path()).read_text())
    atlas_response = page.request.get(BASE.rsplit('/', 1)[0] + '/data/source-atlas.json')
    check('Museum manifest pins the actual served atlas bytes', atlas_response.ok and hashlib.sha256(atlas_response.body()).hexdigest() == museum['atlas']['sha256'])
    check('Museum manifest claims no XR runtime or unlicensed assets', museum['contentOnly'] is True and all(not s['assetIds'] for t in museum['trails'] for s in t['stops']))
    screenshot(page, 'museum-trails-desktop.png')
    for slug in ['source-atlas', 'argument-challenges', 'museum-trails', 'exodus-to-temple-competing-chronologies', 'manuscripts-movements-and-survival']:
        page.set_viewport_size({'width': 390, 'height': 844})
        open_(slug)
        check('Atlas edition fits a 390px viewport: ' + slug, page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        screenshot(page, slug+'-mobile.png')
    page.set_viewport_size({'width':1440, 'height':1000})
    open_('source-atlas')
