"""Native reader checks for the supplemental connected-arguments edition."""
from pathlib import Path

def run_connected_checks(page, ctx, open_page, check, OUT, BASE):
    page.set_viewport_size({'width':1440,'height':1000})
    open_page(page,'connected-arguments','&chapter=teacher-identity')
    page.wait_for_selector('#connected-workspace[data-ready="true"]')
    check('Book map has exactly seventeen existing chapter choices',page.locator('#connected-chapter option').count()==17)
    check('Chapter deep link opens the actual earlier-founder handoff',page.locator('#connected-chapter').input_value()=='teacher-identity' and 'What would identify an earlier founder' in page.locator('#connected-chapter-detail').inner_text())
    page.locator('#connected-chapter-detail button').last.click()
    check('Next chapter advances the chapter and its address',page.locator('#connected-chapter').input_value()=='thomas' and 'chapter=thomas' in page.url)
    page.reload(wait_until='domcontentloaded');page.wait_for_selector('#connected-workspace[data-ready="true"]')
    check('A genuine reload retains the chosen chapter',page.locator('#connected-chapter').input_value()=='thomas')
    check('Chapter share link preserves the same selection','chapter=thomas' in page.locator('#connected-share').get_attribute('href'))
    page.locator('#connected-chapter').select_option('shared-archive')
    check('Opening chapter has no invented predecessor',page.locator('#connected-chapter-detail button').first.is_disabled())
    page.locator('#connected-chapter').select_option('continuing')
    check('Final chapter has no invented successor',page.locator('#connected-chapter-detail button').last.is_disabled())
    for id,count in [('carriers',5),('dates',4),('formation',5)]:
        page.locator('button[data-diagram="'+id+'"]').click()
        check('Diagram renders its linked nodes: '+id,page.locator('#connected-diagram').get_attribute('data-diagram')==id and page.locator('.connected-node').count()==count and page.locator('.connected-node a[data-page]').count()==count)
        check('Diagram labels its interpretive scope: '+id,len(page.locator('.connected-edges').inner_text())>100)
    page.locator('#connected-workspace').evaluate('(el)=>el.scrollIntoView({block:"start"})')
    page.screenshot(path=str(OUT/'connected-book-map-desktop.png'))
    page.locator('#connected-diagram').evaluate('(el)=>el.scrollIntoView({block:"start"})')
    page.screenshot(path=str(OUT/'connected-formation-desktop.png'))
    page.set_viewport_size({'width':390,'height':844})
    for id in ['carriers','dates','formation']:
        page.locator('button[data-diagram="'+id+'"]').click()
        check('Argument diagram fits 390px without shrinking labels: '+id,page.evaluate('document.documentElement.scrollWidth<=innerWidth+1') and page.locator('.connected-node p').evaluate_all('(els)=>els.every(e=>parseFloat(getComputedStyle(e).fontSize)>=14)'))
    page.locator('#connected-diagram').evaluate('(el)=>el.scrollIntoView({block:"start"})');page.screenshot(path=str(OUT/'connected-formation-mobile.png'))
    open_page(page,'connected-arguments','&chapter=%3Cimg%3E');page.wait_for_selector('#connected-workspace[data-ready="true"]')
    check('Invalid chapter has a safe explicit fallback',page.locator('#connected-chapter').input_value()=='shared-archive' and 'Unknown chapter' in page.locator('#connected-message').inner_text() and page.locator('#connected-workspace img').count()==0)
    for slug in ['contested-memories-of-catastrophe','sanctuary-community-and-body','apocalypse-and-repair','inward-formation-and-accountable-intelligence']:
        open_page(page,slug)
        check('Full bridge is online with real resolved links: '+slug,len(page.locator('#article-body').inner_text().split())>800 and page.locator('#article-body .wiki-unavailable').count()==0 and page.locator('#article-body a[data-page="connected-arguments"]').count()>0)
        check('Bridge exposes consulted textual sources: '+slug,'External sources and access notes' in page.locator('#article-body').inner_text())
    open_page(page,'book-contents');page.wait_for_selector('.connected-entry')
    check('Existing table of contents links to the cumulative argument map',page.locator('.connected-entry a[data-page="connected-arguments"]').count()==1)
    open_page(page,'onias-egypt-and-priestly-continuity');page.wait_for_selector('.connected-entry')
    check('An existing investigation links back to its sanctuary bridge',page.locator('.connected-entry a[data-page="sanctuary-community-and-body"]').count()==1)
    open_page(page);page.wait_for_selector('.connected-entry')
    check('Live library and More menu expose the book map',page.locator('.connected-entry a[data-page="connected-arguments"]').count()==1 and page.locator('.depth-site-menu a[data-page="connected-arguments"]').count()==1)
    isolated=ctx.browser.new_context();p=isolated.new_page()
    try:
        p.route('**/data/connected-arguments.json',lambda route:route.abort())
        p.goto(BASE+'?page=connected-arguments',wait_until='domcontentloaded')
        p.wait_for_selector('.connected-notice[role="alert"]')
        check('Failed interactive request leaves all chapter and research text readable','What should a new kind of conscious participant inherit' in p.locator('#article-body').inner_text() and 'Collate Zi-ud-sura' in p.locator('#article-body').inner_text())
    finally:isolated.close()
