"""Foundation acceptance checks, called inside the existing native-HTTP browser suite."""
import json
from pathlib import Path

def run_foundation_checks(page, ctx, open_page, navigate, check, screenshot, out, base):
    page.set_viewport_size({'width':1440,'height':1000})
    open_page(page)
    check('Book contents is directly available in the main navigation', page.locator('.wiki-family-strip > a[data-page="book-contents"]').count()==1)
    page.locator('.wiki-family-strip > a[data-page="book-contents"]').click()
    page.locator('.foundation-chapter').first.wait_for()
    check('Book contents renders seventeen real chapter routes', page.locator('.foundation-chapter').count()==17)
    screenshot(page,'foundation-book-desktop.png')
    page.locator('#book-part').select_option('teacher')
    check('Contents can isolate one movement of the book',page.locator('.foundation-chapter').count()==3)
    page.locator('#book-search').fill('Thomas')
    check('Chapter search composes with part selection',page.locator('.foundation-chapter').count()==1)
    page.locator('#book-search').fill('qzunknown')
    check('Chapter search has an empty state','No chapter routes match' in page.locator('#book-chapters').inner_text())
    open_page(page,'book-contents','#chapter-thomas')
    check('Chapter-route deep links resolve to a real element',page.locator('#chapter-thomas').count()==1)
    open_page(page,'parallel-timelines')
    check('Timeline shows seventeen records on four explicit layers',page.locator('.foundation-time-record').count()==17 and page.locator('.foundation-layer-controls input').count()==4)
    check('The chart has an accessible title and description',page.locator('#foundation-chart-title').count()==1 and page.locator('#foundation-chart-description').count()==1)
    screenshot(page,'foundation-timelines-desktop.png')
    page.locator('#timeline-scope').select_option('undated')
    check('Undated constraints are preserved rather than assigned coordinates',page.locator('.foundation-time-record').count()==8)
    page.locator('#timeline-scope').select_option('all')
    for layer in ['june','witness','textual']:
        page.locator(f'.foundation-layer-controls input[value="{layer}"]').uncheck()
    check('An author reconstruction can be inspected without merging material evidence',page.locator('.foundation-time-record').count()==5)
    page.locator('#timeline-search').fill('88 BCE')
    check('Timeline layer and record search compose',page.locator('.foundation-time-record').count()==1)
    page.locator('#timeline-zoom').fill('180')
    page.locator('#timeline-zoom').dispatch_event('input')
    check('Chronology zoom changes the chart size',page.locator('#foundation-timeline').evaluate('(e)=>e.style.width')=='180%')
    page.locator('#timeline-records a[data-page]').first.click()
    page.locator('#turn-24').wait_for()
    check('Timeline evidence opens the original numbered source turn','Micah Blumberg' in page.locator('#turn-24').inner_text())
    open_page(page,'tor-thomas-and-gnostic-transmission')
    check('Teacher article exposes its full argument rather than only a synopsis',len(page.locator('#article-body').inner_text().split())>1500)
    page.locator('.foundation-dossier > summary').click()
    check('Selected source map explicitly preserves the different reconstructions',page.locator('.foundation-preserve').count()==4 and 'June' in page.locator('.foundation-dossier').inner_text() and 'October' in page.locator('.foundation-dossier').inner_text())
    check('Teacher source map links seven manually reviewed source turns',page.locator('.foundation-dossier .foundation-passage').count()==7)
    screenshot(page,'foundation-teacher-sources.png')
    open_page(page,'intellectual-debts')
    check('Debt register distinguishes four attribution categories',page.locator('.foundation-debt').count()==4)
    check('An AI-introduced author name is not presented as an author acknowledgment','AI-introduced research lead' in page.locator('.foundation-debt').last.inner_text() and 'Self Aware Networks GPT' in page.locator('.foundation-debt').last.inner_text())
    check('Tabor acknowledgment links actual author turns',page.locator('.foundation-debt').first.locator('.foundation-passage').count()==3)
    open_page(page,'divine-will-and-self-authorizing-power')
    check('The will article preserves the date and inference distinction','August 19, 2025' in page.locator('#article-body').inner_text() and 'inference' in page.locator('#article-body').inner_text().lower())
    screenshot(page,'foundation-will-desktop.png')
    open_page(page,'research-board')
    check('Research board has sixteen actionable tasks and five named stages',page.locator('.foundation-task').count()==16 and page.locator('.foundation-board-column').count()==5)
    check('Board explains that changes are personal, not publication decisions','personal planning copy only' in page.locator('.foundation-intro').inner_text())
    page.evaluate('localStorage.setItem("foundation-unrelated-fixture","keep")')
    page.locator('[data-board-move="melchizedek"]').select_option('Develop argument')
    check('Native stage selector moves a card without drag-only interaction',page.locator('[data-board-move="melchizedek"]').input_value()=='Develop argument')
    page.reload(wait_until='domcontentloaded')
    page.locator('[data-board-move="melchizedek"]').wait_for()
    check('Personal stage change survives a real-origin reload',page.locator('[data-board-move="melchizedek"]').input_value()=='Develop argument')
    check('Personal board does not clear unrelated browser storage',page.evaluate('localStorage.getItem("foundation-unrelated-fixture")')=='keep')
    with page.expect_download() as event:
        page.locator('#board-export').click()
    backup=json.loads(Path(event.value.path()).read_text())
    check('Personal board export contains the actual override',backup['tasks']['melchizedek']['stage']=='Develop argument')
    page.locator('#board-file').set_input_files({'name':'restore.json','mimeType':'application/json','buffer':json.dumps({'version':1,'tasks':{'tor-version':{'stage':'Develop argument','note':'Review the October source'},'unknown':{'stage':'Author review','note':'skip'}}}).encode()})
    page.wait_for_function('document.querySelector("#board-message")?.textContent.includes("restored")')
    check('Restore merges known task IDs and preserves existing changes',page.locator('[data-board-move="tor-version"]').input_value()=='Develop argument' and page.locator('[data-board-move="melchizedek"]').input_value()=='Develop argument')
    page.locator('#board-file').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':b'not json'})
    page.wait_for_function('document.querySelector("#board-message")?.textContent.includes("Restore failed")')
    check('Invalid board backup produces a visible error',True)
    page.locator('#board-search').fill('Tabor')
    check('Board search narrows to a specific research task',page.locator('.foundation-task').count()==1)
    page.locator('#board-search').fill('')
    screenshot(page,'foundation-board-desktop.png')
    page.once('dialog',lambda d:d.accept())
    page.locator('#board-reset').click()
    check('Reset touches only personal board changes',page.locator('[data-board-move="melchizedek"]').input_value()=='Verify citations' and page.evaluate('localStorage.getItem("foundation-unrelated-fixture")')=='keep')
    denied=ctx.new_page()
    denied.add_init_script('Object.defineProperty(window,"localStorage",{get(){throw Error("blocked")}})')
    open_page(denied,'research-board')
    denied.locator('[data-board-move="melchizedek"]').select_option('Author review')
    check('Storage-denied board works in session with a clear explanation','session-only' in denied.locator('#board-storage').inner_text() and denied.locator('[data-board-move="melchizedek"]').input_value()=='Author review')
    denied.close()
    page.set_viewport_size({'width':390,'height':844})
    for route in ['book-contents','parallel-timelines','research-board','intellectual-debts','tor-thomas-and-gnostic-transmission','divine-will-and-self-authorizing-power']:
        open_page(page,route)
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),route
        assert page.locator('[data-foundation-error]').count()==0,route
    check('All new research views and flagship additions fit a 390-pixel viewport',True)
    for route,name in [('book-contents','foundation-book-mobile.png'),('parallel-timelines','foundation-timelines-mobile.png'),('research-board','foundation-board-mobile.png')]:
        open_page(page,route);screenshot(page,name)
    open_page(page)
    page.screenshot(path=str(out/'foundation-home-mobile-top.png'),full_page=False)
