'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const C=require('../assets/js/pauline-core.js'),H=require('../editorial/authorial.cjs'),ROOT=path.resolve(__dirname,'..');
const scenario=x=>C.calculate({...C.defaults,...x});
test('Earlier-founder illustration excludes a historical year zero',()=>{const x=scenario({});assert.equal(x.gap,124);assert.equal(x.first,'40 CE');assert.equal(x.later,'51 CE');assert.equal(scenario({transition:'50'}).gap,137);assert.equal(scenario({founder:'1',transition:'1'}).gap,1);});
test('Fourteen-year origin remains an explicit independent choice',()=>{assert.equal(scenario({origin:'visit'}).later,'54 CE');assert.equal(scenario({origin:'transition'}).later,'51 CE');});
test('Inclusive labels are a different named illustration, not silently elapsed years',()=>{const a=scenario({count:'inclusive'}),b=scenario({count:'inclusive',origin:'visit'});assert.equal(a.first,'39 CE');assert.equal(a.later,'50 CE');assert.equal(b.later,'52 CE');assert.equal(a.three,2);assert.equal(a.fourteen,13);});
test('BCE transitions cross the era boundary without printing year zero',()=>{const x=scenario({founder:'10',transition:'2',transitionEra:'bce'});assert.equal(x.first,'2 CE');assert.equal(C.label(0),'1 BCE');assert.equal(C.label(1),'1 CE');assert.equal(C.label(-1),'2 BCE');});
test('Invalid inputs fail before any chronology is returned',()=>{for(const v of ['0','-1','','1.5','1e2','5001','<img>',' 37'])assert.throws(()=>scenario({transition:v}));assert.throws(()=>scenario({transitionEra:'AD'}));assert.throws(()=>scenario({count:'guess'}));assert.throws(()=>scenario({origin:'death'}));assert.throws(()=>scenario({founder:'50',founderEra:'ce'}));});
test('Malformed shared state reverts as a whole, without mixing assumptions',()=>{const p=C.fromParams(new URLSearchParams({pc_founder:'30',pc_founderEra:'ce',pc_transition:'0'}));assert(p.invalid);assert.deepEqual(p.state,C.defaults);const q=C.fromParams(new URLSearchParams());assert(!q.invalid);assert(!q.supplied);});
test('Sharing keeps the reader route, unrelated query and fragment intact',()=>{const u=C.toParams('https://v5ma.github.io/theology-wiki/san-reader.html?page=james-and-contested-succession&reading=all#example',C.defaults);assert.equal(u.searchParams.get('page'),'james-and-contested-succession');assert.equal(u.searchParams.get('reading'),'all');assert.equal(u.hash,'#example');assert.deepEqual(C.fromParams(u.searchParams).state,C.defaults);});
test('New reading companion cannot silently claim a persecution duration or a proof',()=>{const ui=fs.readFileSync(path.join(ROOT,'assets/js/pauline-tools.js'),'utf8');for(const phrase of ['Persecution duration: not specified','not dates established by Galatians','history.state','textContent','host.dataset.ready'])assert(ui.includes(phrase),phrase);for(const phrase of ['localStorage','sessionStorage','innerHTML=e','fetch('])assert(!ui.includes(phrase),phrase);});
test('Both entry points load the companion and full article text remains canonical',()=>{for(const f of ['index.html','san-reader.html']){const html=fs.readFileSync(path.join(ROOT,f),'utf8');for(const name of ['pauline-core.js','pauline-tools.js','pauline.css'])assert(html.includes(name+'?v='+H.version));}const james=H.articles.find(x=>x.slug==='james-and-contested-succession');for(const x of ['137 years','124 years','most of the five hundred','Ananias','pre-Pauline inheritance','First Corinthians 15:3-11'])assert(james.body.includes(x),x);const thomas=H.articles.find(x=>x.slug==='thomas-sayings-and-transmission');assert(thomas.body.includes('First Corinthians 11:17-34'));assert(thomas.body.includes('sacred name does not establish fidelity'));});

test('Companion recognizes shifted reader headings and declines safely without its optional core',()=>{const ui=fs.readFileSync(path.join(ROOT,'assets/js/pauline-tools.js'),'utf8');assert(ui.includes("querySelectorAll('h2,h3,h4,h5,h6')"));assert(ui.includes("textContent.trim()"));assert(ui.includes("||!C)return"));const context={window:{},document:{querySelector(){throw Error('A missing core must not touch the document.');}}};require('node:vm').runInNewContext(ui,context);assert.doesNotThrow(()=>context.window.TheologyPauline.enhance({slug:'james-and-contested-succession'}));});

test('Timeline positions preserve all four events on a shared numerical scale',()=>{const t=C.timeline(C.defaults);assert.equal(t.start,'88 BCE');assert.equal(t.end,'51 CE');assert.equal(t.span,138);assert.deepEqual(t.events.map(x=>x.date),['88 BCE','37 CE','40 CE','51 CE']);assert.deepEqual(t.events.map(x=>x.position),[0,124/138,127/138,1]);assert.equal(C.timeline({...C.defaults,origin:'visit'}).end,'54 CE');});
test('Timeline keeps simultaneous labels separate and rejects invalid scenarios',()=>{const t=C.timeline({...C.defaults,founder:'37',founderEra:'ce'});assert.equal(t.events.length,4);assert.equal(t.events[0].position,0);assert.equal(t.events[1].position,0);assert.equal(t.span,14);assert.throws(()=>C.timeline({...C.defaults,transition:'0'}));assert.throws(()=>C.timeline({...C.defaults,origin:'invalid'}));});
test('Timeline remains finite and ordered across eras, bounds and counting choices',()=>{for(const founder of ['1','88','5000'])for(const transition of ['1','37','5000'])for(const origin of ['transition','visit'])for(const count of ['elapsed','inclusive']){const t=C.timeline({...C.defaults,founder,transition,origin,count});assert(t.span>0);assert(t.events.every(x=>Number.isFinite(x.position)&&x.position>=0&&x.position<=1&&!x.date.startsWith('0 ')));assert(t.events.every((x,i)=>!i||x.position>=t.events[i-1].position));}const b=C.timeline({...C.defaults,founder:'10',transition:'2',transitionEra:'bce'});assert.equal(b.events[2].date,'2 CE');});
test('Companion asset URLs pin the actual reviewed bytes without changing the editorial edition',()=>{const hash=require('node:crypto').createHash;for(const name of ['pauline-core.js','pauline-tools.js','pauline.css']){const type=name.endsWith('.css')?'css':'js',digest=hash('sha256').update(fs.readFileSync(path.join(ROOT,'assets',type,name))).digest('hex').slice(0,16);for(const file of ['index.html','san-reader.html'])assert(fs.readFileSync(path.join(ROOT,file),'utf8').includes(name+'?v='+H.version+'&amp;asset='+digest),name+' in '+file);}});
