"""Real reader verification for the two historical studies and shared evidence."""
def run_priestly_checks(page, open_page, check, OUT):
    page.set_viewport_size({'width':1440,'height':1000})
    for slug, phrase in [('daniel-jubilee-and-the-teachers-time','reconstructed 40-year career'),('onias-egypt-and-priestly-continuity','Chelcias and Ananias')]:
        open_page(page,slug)
        body=page.locator('#article-body').inner_text()
        check('New full historical argument renders: '+slug,phrase in body and len(body.split())>1800 and "Micah's proposal" not in body)
        check('New study exposes sourced reading and full-listening entry: '+slug,'External sources' in body and page.locator('a[href*="listen='+slug+'"]').count()>0)
        link=page.locator('#article-body a[href$="data/priestly-evidence.json"]')
        result=page.request.get(link.evaluate('(a)=>a.href'))
        evidence=result.json()
        check('Study delivers twelve evidence claims and conditional calculations: '+slug,result.ok and len(evidence['claims'])==12 and evidence['calculations']['conditional'])
        page.locator('#article-title').scroll_into_view_if_needed()
        page.screenshot(path=str(OUT/(slug+'-desktop.png')))
        page.set_viewport_size({'width':390,'height':844})
        check('Historical article fits a 390px viewport: '+slug,page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        page.screenshot(path=str(OUT/(slug+'-mobile.png')))
        page.set_viewport_size({'width':1440,'height':1000})
    open_page(page,'source-atlas','&record=fragment-strabo-onias')
    page.wait_for_function('document.querySelector("#atlas-selected")?.value==="fragment-strabo-onias"')
    check('Strabo opens as a mediated quotation rather than an independent artifact','through Josephus' in page.locator('#atlas-cards').inner_text())
    open_page(page,'museum-trails')
    page.wait_for_function('document.querySelectorAll(".atlas-trail").length===8')
    for title in ['The Teacher and prophetic time','Onias and the priestly branches']:
        trail=page.locator('.atlas-trail').filter(has_text=title)
        check('New museum trail has five linked exhibit stops: '+title,trail.count()==1 and trail.locator('.atlas-stop').count()==5)
    open_page(page,'book-contents')
    check('Book routes include both historical studies',all(page.locator('#article-body a[data-page="'+s+'"]').count()>0 for s in ['daniel-jubilee-and-the-teachers-time','onias-egypt-and-priestly-continuity']))
