'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),C=require('../assets/js/listening-core.js');
const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8')),digest=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,p))).digest('hex');
const library=read('data/listening-library.json'),products=read('data/products.json'),pages=read('data/page-index.json');
test('Listening catalogue contains every complete developed article exactly once',()=>{const expected=pages.filter(p=>p.kind==='Developed article').map(p=>p.slug).sort();assert.deepEqual(library.articles.map(a=>a.slug).sort(),expected);assert.equal(expected.length,29);for(const a of library.articles){assert.equal(a.sourceSha256,digest(a.source));assert.equal(a.narrationSha256,digest(a.narration));const x=read(a.narration);assert.equal(x.sourceSha256,a.sourceSha256);assert.deepEqual(x.segments,C.segment(fs.readFileSync(path.join(ROOT,a.source),'utf8')));assert(x.segments.length>15);}});
test('Narration normalization retains words in order and labels notes without summarizing',()=>{const input='---\ntitle: X\n---\n\n# A title\n\nHere is [[a|the link]] and **some words**.\n\n## Source conversations\n\nA source note.';const chunks=C.segment(input,20);assert.equal(chunks.map(c=>c.text).join(' '),'A title Here is the link and some words. Source conversations A source note.');assert(chunks.at(-1).notes);assert(!chunks[1].notes);assert(chunks.every(c=>c.text.length<=20));});
test('Resume rejects stale text, invalid indexes, unknown format and untrusted JSON',()=>{const h='a'.repeat(64),raw=JSON.stringify({version:1,positions:{study:{hash:h,index:7}}});assert.equal(C.readResume(raw,'study',h,20),7);assert.equal(C.readResume(raw,'study','b'.repeat(64),20),null);assert.equal(C.readResume(raw,'study',h,5),null);assert.equal(C.readResume('{','study',h,20),null);assert.equal(C.readResume(raw,'other',h,20),null);});
function fixture(){const states=[],synth={queue:[],cancel(){this.cancelled=(this.cancelled||0)+1;},speak(u){this.queue.push(u);u.onstart();},pause(){this.paused=true;},resume(){this.paused=false;}};class U{constructor(text){this.text=text;}}const speaker=new C.Speaker(synth,U,s=>states.push(s));speaker.voice={name:'Explicit isolated unit-test voice',lang:'en-US'};speaker.load([{text:'First'},{text:'Second'}]);return {states,synth,speaker};}
test('Playback moves through actual segment boundaries and ignores cancelled callbacks',()=>{const {speaker,synth}=fixture();speaker.play();assert.equal(speaker.state,'playing');const first=synth.queue[0];first.onend();assert.equal(speaker.index,1);assert.equal(synth.queue.at(-1).text,'Second');first.onend();assert.equal(speaker.index,1);const old=synth.queue.at(-1);speaker.stop();old.onend();assert.equal(speaker.state,'stopped');assert.equal(speaker.index,1);});
test('Pause, resume, speed, seek and end are independently represented',()=>{const {speaker,synth}=fixture();speaker.play();speaker.pause();assert.equal(speaker.state,'paused');speaker.play();assert.equal(synth.paused,false);speaker.setRate(1.2);assert.equal(synth.queue.at(-1).rate,1.2);speaker.seek(99);assert.equal(speaker.index,1);synth.queue.at(-1).onend();assert.equal(speaker.state,'ended');speaker.play();assert.equal(speaker.index,0);assert.throws(()=>speaker.setRate(NaN));speaker.stop();});
test('A missing voice is unavailable, never reported as a completed recording',()=>{const {speaker}=fixture();speaker.voice=null;speaker.play();assert.equal(speaker.state,'unavailable');speaker.stop();});
test('Episodes preserve historical mechanisms and have exact source dependencies',()=>{assert.equal(products.episodes.length,3);for(const e of products.episodes){assert(e.scenes.length>=7);assert(e.voice.includes('not an imitation'));assert(fs.existsSync(path.join(ROOT,e.script)));for(const s of e.sources)assert.equal(s.sha256,digest(s.path));}const teacher=products.episodes.find(e=>e.id==='teacher-copy-community');assert(teacher.scenes.some(s=>s.narration.includes('successor')));assert(teacher.scenes.some(s=>s.narration.includes('institutional')));const challenge=products.episodes.find(e=>e.id==='objections-in-the-museum');assert(challenge.scenes.some(s=>s.narration.includes('I do not propose')));});
test('Product register retains unapproved manuscript, narration and XR milestones',()=>{assert.equal(products.tasks.length,10);assert(products.tasks.find(t=>t.id==='book-audio').status==='Planned');assert(products.tasks.find(t=>t.id==='author-voice').status==='Needs author decision');assert(products.channels.find(p=>p.id==='museum').state.includes('separate'));assert(!products.reference.scope.includes('verified audiobook controls'));});
test('All recorded files are local hash-checked outputs tied to current text',()=>{assert.equal(products.media.assets.length,2);assert.deepEqual(products.media.assets.map(a=>a.kind).sort(),['article','episode']);assert.equal(products.media.production.engine,'Kokoro 0.9.4');for(const a of products.media.assets){assert(a.status.includes('draft'));assert(a.durationSeconds>10);for(const f of a.files){assert(f.path.startsWith('products/media/'));assert(!f.path.includes('..'));assert.equal(f.sha256,digest(f.path));}const cues=read(a.files.find(f=>f.role==='cues').path).cues;assert.equal(cues.length,a.segments);assert(cues.every((c,i)=>c.end>c.start&&(!i||Math.abs(c.start-cues[i-1].end)<.001)));assert(Math.abs(cues.at(-1).end-a.durationSeconds)<.001);if(a.kind==='article'){const doc=read(library.articles.find(x=>x.slug===a.id).narration);assert.deepEqual(cues.map(c=>c.sourceSegment),doc.segments.filter(s=>!s.notes).map(s=>s.id));}}});
test('Product assets load locally and data stays out of other application storage',()=>{for(const f of ['san-reader.html','index.html']){const html=fs.readFileSync(path.join(ROOT,f),'utf8');for(const asset of ['listening-core.js','products-tools.js','products.css'])assert(html.includes(asset+'?v='+products.version));}const source=fs.readFileSync(path.join(ROOT,'assets/js/products-tools.js'),'utf8');assert(!source.includes('localStorage.clear'));assert(!source.includes('getUserMedia'));assert(source.includes('localService||remote'));assert(source.includes('theology:loading'));});

test('Speech failure cannot advance on a late completion callback',()=>{const {speaker,synth}=fixture();speaker.play();const u=synth.queue[0];u.onerror({error:'network'});u.onend();assert.equal(speaker.state,'error');assert.equal(speaker.index,0);assert.equal(synth.queue.length,1);speaker.stop();});
test('Voice disappearance at a boundary retains position instead of throwing',()=>{const {speaker,synth}=fixture();speaker.play();speaker.voice=null;synth.queue[0].onend();assert.equal(speaker.state,'unavailable');assert.equal(speaker.index,1);speaker.stop();});
