'use strict';
const R=require('../editorial/roadmap.cjs');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),C=require('../assets/js/research-core.js'),E=require('../editorial/edition.cjs'),X=require('../editorial/expansion.cjs'),D=require('../editorial/depth.cjs'),F=require('../editorial/foundations.cjs');
const references=[...X.references,...D.references,...F.references,...R.references];
const load=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const pages=load('data/page-index.json'),bySlug=new Map(pages.map(p=>[p.slug,p])),graph=load('data/graph.json').related,info=load('data/research.json'),full=load('data/search.json');
test('All 354 original chats remain byte-identical to their manifest',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'../theology-sources/manifest.json'),'utf8').replace(/^\uFEFF/,''));assert.equal(manifest.length,354);for(const m of manifest){const b=fs.readFileSync(path.join(ROOT,'../theology-sources/chats',m.name));assert.equal(b.length,m.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),m.sha256.toLowerCase());}});
test('416 unique routes include 354 conversation records and twenty-two developed articles',()=>{assert.equal(pages.length,416);assert.equal(bySlug.size,416);assert.equal(pages.filter(p=>p.sourceFile).length,354);assert.equal(pages.filter(p=>p.kind==='Developed article').length,22);});
test('Every indexed Markdown path exists inside the content directory',()=>{for(const p of pages){assert(!p.path.includes('..'));assert(fs.existsSync(path.join(ROOT,'content',p.path)));}});
test('Every chat file has exactly one reader route and source hash',()=>{assert.equal(new Set(pages.filter(p=>p.sourceFile).map(p=>p.sourceFile)).size,354);for(const p of pages.filter(p=>p.sourceFile)){assert(C.safeSourceFile(p.sourceFile));assert.match(p.sourceSha256,/^[0-9a-f]{64}$/);assert(p.turnCount>0);}});
test('Eight topic collections classify every source record',()=>{assert.equal(E.categories.length,8);for(const p of pages.filter(p=>p.sourceFile))assert(E.categories.some(c=>c.id===p.category));});
test('Developed articles include specific archived conversations and attribution',()=>{for(const p of pages.filter(p=>p.kind==='Developed article')){assert(p.references.length);assert(p.attribution.includes('editorial synthesis'));for(const s of p.references){assert(bySlug.get(s.slug)?.sourceFile===s.file);assert.match(s.sha256,/^[a-f0-9]{64}$/);}}});
test('All new article and navigation wikilinks resolve',()=>{for(const p of pages.filter(p=>p.editionGenerated||p.slug==='home')){const text=fs.readFileSync(path.join(ROOT,'content',p.path),'utf8');for(const m of text.matchAll(/\[\[([^\]|#]+)[^\]]*\]\]/g))assert(bySlug.has(m[1]),`${p.slug}: ${m[1]}`);}});
test('All graph destinations are local and backlinks exactly match directed edges',()=>{for(const p of pages){for(const target of graph[p.slug]){assert(bySlug.has(target));assert(info.backlinks[target].includes(p.slug));}assert.deepEqual((info.backlinks[p.slug]||[]).slice().sort(),pages.filter(x=>graph[x.slug].includes(p.slug)).map(x=>x.slug).sort());}});
test('No source record is routed to unrelated generated Riemann hubs',()=>{for(const p of pages.filter(p=>p.sourceFile))assert.deepEqual(graph[p.slug],['topic-'+p.category]);});
test('Top-level speaker parsing does not mistake quoted ChatGPT labels for new speakers',()=>{const text='Title: x\r\nDate: 1\r\n\r\nMicah Blumberg:\r\nA quoted reply:\r\nChatGPT said:\r\nquoted words\r\n\r\nSelf Aware Networks GPT:\r\nactual answer';const turns=C.splitTranscript(text);assert.equal(turns.length,2);assert(turns[0].text.includes('ChatGPT said:'));assert.equal(turns[1].speaker,'Self Aware Networks GPT');});
test('Transcript parser preserves source order and character offsets',()=>{const text='Micah Blumberg:\nfirst\n\nSelf Aware Networks GPT:\nsecond';for(const t of C.splitTranscript(text))assert.equal(text.slice(t.start,t.end).trim(),t.text);});
test('Unstructured input remains readable without fabricated speakers',()=>{assert.deepEqual(C.splitTranscript('unlabelled')[0],{number:1,speaker:'Unstructured source',text:'unlabelled',start:0,end:10});});
test('Export timestamps convert to UTC and invalid dates remain unknown',()=>{assert.equal(C.dateFromExport('Date: 0'),'1970-01-01');assert.equal(C.dateFromExport('Date: nope'),'');assert.equal(C.dateFromExport('Date: 99999999999999'),'');});
test('HTML-sensitive text is escaped',()=>{assert.equal(C.esc('<script>"&'), '&lt;script&gt;&quot;&amp;');});
test('Source filenames reject traversal and foreign paths',()=>{for(const bad of ['../secret.txt','https://example.com/x.txt','gpt2026dragon1_../secret.txt','gpt2026dragon1_X.js'])assert.equal(C.safeSourceFile(bad),false);});
test('Full-text search finds the original cognitive discussion beyond its summary',()=>{const hits=C.select(pages,'gradient descent',{kind:'chat'},full);assert(hits.some(p=>p.slug==='cognitive-gnosticism-jesus-vs-gnostic-jesus'));});
test('Multi-keyword search is an AND query',()=>{assert.equal(C.select(pages,'coherence zzzzunknownword',{},full).length,0);});
test('Category, article and saved filters compose',()=>{const result=C.select(pages,'',{topic:'apocalypse',kind:'saved',saved:['apocalyptic-repair-theology','religion-for-conscious-robots']},full);assert.deepEqual(result.map(p=>p.slug),['apocalyptic-repair-theology']);});
test('Title and conversation-date sorts are deterministic',()=>{for(const sort of ['title','date'])assert.deepEqual(C.select(pages,'',{sort}),C.select(pages,'',{sort}));const a=C.select(pages,'',{kind:'chat',sort:'date'});assert(a.every((p,i)=>!i||a[i-1].date>=p.date));});
test('Reading-list restore ignores unknown IDs and invalid formats',()=>{assert.deepEqual(C.validateState({version:1,saved:['home','home','unknown']},new Set(['home'])),{version:1,saved:['home']});assert.throws(()=>C.validateState({saved:[]},new Set()));});
test('Speaker and text filters compose inside a conversation',()=>{const turns=[{speaker:'Micah Blumberg',text:'coherence and humanity'},{speaker:'Self Aware Networks GPT',text:'coherence index'}];assert.equal(C.filterTurns(turns,'coherence','Micah Blumberg').length,1);assert.equal(C.filterTurns(turns,'humanity','Self Aware Networks GPT').length,0);});
test('Legacy routing boilerplate is removed without deleting preceding content',()=>{const text='Keep this.\n\n## Related Graph Routes\n\nNoise\n\n## Meaning\n\nKeep that.\n\n<!-- NINE-WIKI-X:START -->\nnoise\n<!-- NINE-WIKI-X:END -->';const clean=C.cleanRouting(text);assert(clean.includes('Keep this'));assert(clean.includes('Keep that'));assert(!clean.includes('Noise'));assert(!clean.includes('NINE-WIKI'));});
test('Runtime adapter protects against stale renders and unsafe schemes',()=>{const runtime=fs.readFileSync(path.join(ROOT,'assets/js/theology-reader.js'),'utf8');assert(runtime.includes('generation !== renderGeneration'));assert(runtime.includes('javascript|vbscript|file|data|blob'));assert(runtime.includes('event.ctrlKey || event.metaKey'));});
test('Preferred reader keeps SAN markup and loads only Theology-local enhancements',()=>{const html=fs.readFileSync(path.join(ROOT,'san-reader.html'),'utf8');assert(html.includes('wiki-theme-san'));assert(html.includes('article-outline-list'));assert(html.includes('./assets/js/theology-reader.js'));assert(html.includes('theology-source-edition-assets'));});
test('Legacy integration script cannot overwrite the improved reader',()=>{const file=path.join(ROOT,'../scripts/prepare-interactive-site.py');if(fs.existsSync(file)){assert(fs.readFileSync(file,'utf8').includes('Preserve the Theology source edition'));}});

test('Every requested investigation has archived references, claim type and external source records',()=>{for(const p of X.articles){const row=bySlug.get(p.slug);assert(row);assert(row.claimType);assert(row.references.length);assert(row.externalSources.length);for(const id of row.externalSources)assert(references.some(r=>r.id===id));}});
test('Alias search finds TOR and the hidden Ahmose chronology discussion',()=>{assert(C.select(pages,'Jesus TOR',{kind:'article'},full).some(p=>p.slug==='jesus-teacher-of-righteousness-hypothesis'));assert(C.select(pages,'Ahmose brick dating objection',{kind:'chat'},full).some(p=>p.slug==='parthians-and-medes-meaning'));});
test('Seven reading paths resolve every step and include both new investigations',()=>{assert.equal(info.paths.length,7);for(const p of info.paths)for(const id of p.pages)assert(bySlug.has(id));});
test('External sources are uniquely identified HTTPS records with honest access scope',()=>{assert.equal(new Set(references.map(r=>r.id)).size,44);for(const r of references){const u=new URL(r.url);assert.equal(u.protocol,'https:');assert(!u.username&&!u.password);assert(r.scope.length>40);}});
test('Ledger distinguishes available primary records from unscored recovery leads',()=>{const ledger=load('data/forecast-ledger.json');assert.equal(ledger.entries.length,6);assert.equal(new Set(ledger.entries.map(e=>e.id)).size,6);for(const e of ledger.entries){assert(e.dateBasis&&e.horizon&&e.criterion&&e.conditions);if(e.recordType==='Recovery lead'){assert(!e.sourceSlug&&!e.sourceURL);assert.equal(e.evaluation,'Not assessable from the available record');}else assert(e.sourceSlug||e.sourceURL);}assert.equal(ledger.entries.filter(e=>e.recordType==='Recovery lead').length,2);});
test('Archived ledger turns have matching source hashes and an author speaker',()=>{for(const e of load('data/forecast-ledger.json').entries.filter(e=>e.sourceSlug)){const row=bySlug.get(e.sourceSlug);assert.equal(e.sourceHash,row.sourceSha256);const text=fs.readFileSync(path.join(ROOT,'../theology-sources/chats',e.sourceFile),'utf8');assert.equal(C.splitTranscript(text)[e.turn-1].speaker,'Micah Blumberg');}const updated=load('data/forecast-ledger.json').entries.find(e=>e.id==='second-role-update-2025');assert.equal(updated.date,'2025-10-12');});
test('Entry points use the current cache version for every enhanced runtime asset',()=>{for(const file of ['index.html','san-reader.html']){const text=fs.readFileSync(path.join(ROOT,file),'utf8');assert(text.includes(R.version));assert(!text.includes('source-edition-1'));}});


test('Three flagship investigations contain worked cases instead of a research placeholder',()=>{for(const slug of D.featured){const p=bySlug.get(slug),text=fs.readFileSync(path.join(ROOT,'content',p.path),'utf8');assert(text.split(/\s+/).length>1000,slug);assert(!text.includes('The next useful comparison would'),slug);}const trump=bySlug.get('trump-first-beast-of-revelation');assert(trump.externalSources.includes('clemency-2025'));});
test('Explained relationships are distinct, directed and present in the navigation graph',()=>{const r=load('data/relationships.json');assert(r.edges.length>=40);const seen=new Set();for(const e of r.edges){assert(bySlug.has(e.from)&&bySlug.has(e.to));assert(e.why.length>40);assert(e.type);assert(graph[e.from].includes(e.to));const key=e.from+'|'+e.to+'|'+e.type;assert(!seen.has(key));seen.add(key);}});
test('Exact source-turn anchors preserve author labels and immutable source hashes',()=>{const r=load('data/relationships.json');assert.equal(r.anchors.length,38);for(const a of r.anchors){const p=bySlug.get(a.to);assert.equal(a.sourceHash,p.sourceSha256);const text=fs.readFileSync(path.join(ROOT,'../theology-sources/chats',p.sourceFile),'utf8');assert.equal(C.splitTranscript(text)[a.turn-1].speaker,'Micah Blumberg');assert(a.why);}});
test('Chronology separates proposed dates from the independently reproducible arithmetic',()=>{const depth=load('data/depth.json');assert.equal(depth.chronology.length,6);assert.equal(88+37-1,124);assert.equal(88+50-1,137);assert.equal(88+46-1,133);assert(depth.chronology.some(c=>c.layer.startsWith('Arithmetic')));for(const c of depth.chronology){assert(c.layer&&c.account);assert(bySlug.has(c.sourceSlug));}});
test('Speaker-specific searches require all words in one turn from the selected speaker',()=>{const fixture={turns:[{slug:'one',turn:1,speaker:'Micah Blumberg'},{slug:'one',turn:2,speaker:'Self Aware Networks GPT'},{slug:'two',turn:1,speaker:'Micah Blumberg'}],turnPostings:{alpha:[0,2],beta:[1,2]}};assert.deepEqual(C.findTurns(fixture,'alpha beta','author').map(t=>t.slug),['two']);assert.equal(C.findTurns(fixture,'alpha beta','ai').length,0);assert.equal(C.findTurns(fixture,'beta','ai')[0].turn,2);});
test('Turn index contains real speakers and corresponding numbered source turns',()=>{assert.equal(full.turns.length,4980);for(const p of pages.filter(p=>p.sourceFile)){const indexed=full.turns.filter(t=>t.slug===p.slug);assert.equal(indexed.length,p.turnCount);for(const t of indexed){assert(['Micah Blumberg','Self Aware Networks GPT','Unstructured source'].includes(t.speaker));assert(t.turn>=1&&t.turn<=p.turnCount);}}});
test('Global author search recovers a correction without counting an AI reply as an author turn',()=>{const result=C.findTurns(full,'not two things','author');assert(result.some(t=>t.slug==='agi-religious-framework'&&t.turn===3));assert(result.every(t=>t.speaker==='Micah Blumberg'));const hits=C.select(pages,'not two things',{kind:'chat',speaker:'author'},full);assert(hits.some(p=>p.slug==='agi-religious-framework'));});
test('Source snippets retain search context and are escaped at the rendering boundary',()=>{const input='x '.repeat(180)+'needle <script>bad</script> '+ 'z '.repeat(180);const excerpt=C.snippet(input,'needle');assert(excerpt.includes('needle'));assert(excerpt.length<=238);assert(!C.esc(excerpt).includes('<script>'));});
test('Glossary and introductory navigation preserve their connected article destinations',()=>{assert(bySlug.has('guide-to-the-inquiry'));assert(bySlug.has('glossary'));assert.equal(D.glossary.length,10);for(const t of D.glossary){assert(t.term&&t.text.length>40);assert(bySlug.has(t.page));}});
test('Depth assets are loaded from the same origin in both supported entry points',()=>{for(const file of ['index.html','san-reader.html']){const html=fs.readFileSync(path.join(ROOT,file),'utf8');assert(html.includes('./assets/js/depth-tools.js?v='+R.version));assert(html.includes('./assets/css/depth.css?v='+R.version));}const ui=fs.readFileSync(path.join(ROOT,'assets/js/depth-tools.js'),'utf8');assert(ui.includes("digest('SHA-256',bytes)"));assert(ui.includes("controller.signal.aborted||!target.isConnected"));assert(ui.includes("target.textContent=C.snippet"));});

require('./foundations.test.cjs');

require('./roadmap.test.cjs');

require('./atlas.test.cjs');
