"""Real HTTP checks for the passage comparison and full supplementary listening."""
def run_restoration_checks(page, ctx, open_page, check, OUT, BASE):
    slug='rival-continuations-and-restoration'
    def ready(extra=''):
        open_page(page,slug,extra)
        page.wait_for_selector('#restoration-workspace[data-ready="true"]')
    page.set_viewport_size({'width':1440,'height':1000})
    ready('&lens=boundary')
    check('Restoration deep link opens six distinct beneficiary readings',page.locator('.restoration-card').count()==6 and page.locator('#restoration-workspace').get_attribute('data-lens')=='boundary')
    check('The comparison preserves restorative and exclusionary readings together','exclusions' in page.locator('[data-record="revelation"] .restoration-reading').inner_text() and 'not established' in page.locator('[data-record="sibyl2"] .restoration-reading').inner_text())
    page.locator('button[data-lens="timing"]').click()
    check('Changing a lens updates the real narrative timing and shareable address','after punishment' in page.locator('[data-record="sibyl2"] .restoration-reading').inner_text() and 'lens=timing' in page.url and 'lens=timing' in page.locator('#restoration-share').get_attribute('href'))
    page.reload(wait_until='domcontentloaded');page.wait_for_selector('#restoration-workspace[data-ready="true"]')
    check('A genuine reload retains the selected comparison lens',page.locator('#restoration-workspace').get_attribute('data-lens')=='timing')
    page.locator('button[data-lens="agency"]').focus();page.keyboard.press('Enter')
    check('Comparison lenses work from the keyboard with pressed-state labels',page.locator('button[data-lens="agency"]').get_attribute('aria-pressed')=='true' and page.locator('button[data-lens][aria-pressed="true"]').count()==1)
    page.locator('[data-record="sibyl2"] summary').click()
    check('Expanded source distinguishes the translated passage from reported manuscript objection','not two independent ancient witnesses' in page.locator('[data-record="sibyl2"]').inner_text() and page.locator('[data-record="sibyl2"] a').count()==1)
    check('Source links use the actual historical translation and safe new-tab attributes','Terry' in page.locator('[data-record="sibyl2"] a').get_attribute('href') and page.locator('[data-record="sibyl2"] a').get_attribute('rel')=='noopener noreferrer')
    page.locator('[data-record="sibyl2"] summary').click()
    page.locator('#restoration-workspace h2').evaluate('(e)=>e.scrollIntoView({block:"start"})');page.screenshot(path=str(OUT/'restoration-desktop.png'))
    for width in [390,320]:
        page.set_viewport_size({'width':width,'height':844})
        check('Six-source comparison fits '+str(width)+'px with normal reading text',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1') and page.locator('.restoration-reading').evaluate_all('(els)=>els.length===6&&els.every(e=>parseFloat(getComputedStyle(e).fontSize)>=14)'))
        check('Every comparison card preserves its complete label at '+str(width)+'px',page.locator('.restoration-card').evaluate_all('(els)=>els.every(e=>e.scrollWidth<=e.clientWidth+1&&e.querySelector("summary").getBoundingClientRect().bottom<=e.getBoundingClientRect().bottom)'))
    page.set_viewport_size({'width':390,'height':844});page.locator('#restoration-workspace h2').evaluate('(e)=>e.scrollIntoView({block:"start"})');page.screenshot(path=str(OUT/'restoration-mobile.png'))
    page.locator('#restoration-read').click()
    check('Full argument shortcut moves actual keyboard focus without replacing the article heading',page.evaluate('document.activeElement.tagName==="H2"') and 'inheritance' in page.evaluate('document.activeElement.textContent').lower())
    ready('&lens=%3Cimg%20src=x%3E')
    check('Unknown lens fails safely without HTML injection','Unknown comparison lens' in page.locator('#restoration-status').inner_text() and page.locator('#restoration-workspace img').count()==0 and page.locator('#restoration-workspace').get_attribute('data-lens')=='agency')
    # Exercise a real resolved article link, not a route stub.
    page.locator('[data-listen-link]').click()
    page.wait_for_function('(s)=>document.querySelector("#product-workspace")?.dataset.articleReady===s',arg=slug)
    check('Bridge Listen action opens its own full, source-verified text','hashes match' in page.locator('#listen-version').inner_text() and 'Supplementary bridge essay' in page.locator('#listen-kind-note').inner_text() and page.locator('.listen-paragraph').count()>30)
    check('Bridge device text is not mislabeled as a prerecorded audiobook','No prerecorded' in page.locator('#listen-recorded').inner_text() and page.locator('#listen-recording').count()==0)
    page.locator('#listen-kind').select_option('Bridge study')
    check('Listening type filter exposes exactly five full bridge essays',page.locator('#listen-article option').count()==5)
    page.locator('#listen-chapter').select_option('shared-archive')
    check('Chapter and type filters compose through supplementary membership',page.locator('#listen-article option[value="'+slug+'"]').count()==1 and 0<page.locator('#listen-article option').count()<5)
    page.locator('#listen-search').fill('zzzz-not-found')
    check('Combined listening filter has a recoverable empty state',page.locator('#listen-article option').count()==0 and page.locator('#listen-load').is_disabled())
    page.locator('#listen-search').fill('');page.locator('#listen-chapter').select_option('');page.locator('#listen-kind').select_option('Developed article')
    check('Principal-only listening preserves the original twenty-nine choices',page.locator('#listen-article option').count()==29)
    page.locator('#listen-kind').select_option('Bridge study')
    slugs=page.locator('#listen-article option').evaluate_all('(els)=>els.map(e=>e.value)')
    for item in slugs:
        page.locator('#listen-article').select_option(item);page.locator('#listen-load').click()
        page.wait_for_function('(s)=>document.querySelector("#product-workspace")?.dataset.articleReady===s',arg=item)
        check('Full bridge listening verifies its exact source: '+item,'hashes match' in page.locator('#listen-version').inner_text() and page.locator('.listen-paragraph').count()>15)
    page.locator('#listen-kind').select_option('');page.locator('#listen-search').fill('');page.locator('#listen-chapter').select_option('')
    check('Clearing filters restores all thirty-four complete studies',page.locator('#listen-article option').count()==34)
    page.locator('#product-workspace').evaluate('(el)=>el.scrollIntoView({block:"start"})');page.screenshot(path=str(OUT/'restoration-listening-mobile.png'))
    page.set_viewport_size({'width':1440,'height':1000})
    open_page(page,'connected-arguments');page.wait_for_selector('#connected-workspace[data-ready="true"]')
    for chapter in ['shared-archive','trauma','scriptural-axis','repair-practice']:
        page.locator('#connected-chapter').select_option(chapter)
        check('Book handoff includes the new full passage comparison: '+chapter,page.locator('#connected-chapter-detail a[data-page="'+slug+'"]').count()==1)
    check('Online book map retains the actual review findings and unfinished research','Review and improvement cycle' in page.locator('#article-body').inner_text() and "Terry's reported anti-restoration addition" in page.locator('#article-body').inner_text())
    isolated=ctx.browser.new_context();p=isolated.new_page()
    try:
        p.route('**/data/connected-arguments.json',lambda route:route.abort())
        p.goto(BASE+'?page='+slug,wait_until='domcontentloaded');p.wait_for_selector('.connected-notice[role="alert"]')
        check('Failed comparison request leaves all six static source readings and the full essay',all(t in p.locator('#article-body').inner_text() for t in ['The six-passage comparison record','Apocalypse of Adam','Sibylline Oracles II','Revelation','Intercession can reopen']))
    finally:isolated.close()
