
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),B=require('../tools/connected.cjs'),C=require('../assets/js/listening-core.js');
const json=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8')),d=json('data/connected-arguments.json'),library=json('data/listening-library.json');
const refs=new Set(d.references.map(r=>r.id));
test('Restoration compares six explicit passage units with no invented copy or composition dates',()=>{B.validateComparison(d.comparison,refs);assert.equal(d.comparison.records.length,6);assert.equal(d.comparison.records[0].locator,'4QSd / 4Q258, Library of Congress displayed extract');for(const row of d.comparison.records){assert.equal(row.copyDate,null);assert.equal(row.compositionDate,null);assert(row.scope.length>35);assert(row.question.length>35);}});
test('Comparison rejects unknown sources, duplicate IDs and invented absolute dates',()=>{for(const alter of [x=>x.records[0].sourceIds.push('not-a-source'),x=>x.records[1].id=x.records[0].id,x=>x.records[0].compositionDate=50,x=>x.records[0].copyDate=100,x=>x.records[0].timing='',x=>x.records[0].id='<img>']){const x=structuredClone(d.comparison);alter(x);assert.throws(()=>B.validateComparison(x,refs));}});
test('Library contains exactly 29 principal studies and five full bridge studies',()=>{assert.equal(library.articles.length,34);assert.equal(library.articles.filter(a=>a.kind==='Developed article').length,29);assert.equal(library.articles.filter(a=>a.kind==='Bridge study').length,5);for(const s of d.studies){const a=library.articles.find(a=>a.slug===s.slug);assert(a);assert(a.chapters.length>0);const n=json(a.narration),source=fs.readFileSync(path.join(root,a.source));assert.equal(n.sourceSha256,crypto.createHash('sha256').update(source).digest('hex'));assert.deepEqual(n.segments,C.segment(source.toString('utf8')));assert.equal(fs.readFileSync(path.join(root,a.transcript),'utf8'),n.segments.map(s=>s.text).join('\n\n')+'\n');}});
test('Supplementary chapter memberships remain outside all principal reading lists',()=>{const book=json('data/foundations.json').parts.flatMap(p=>p.chapters);for(const c of library.chapters){assert.deepEqual(c.pages,book.find(x=>x.id===c.id).pages.filter(slug=>library.articles.some(a=>a.slug===slug)));assert(c.supplementaryPages.length>0);assert(c.supplementaryPages.every(slug=>!c.pages.includes(slug)&&library.articles.find(a=>a.slug===slug).kind==='Bridge study'));}assert.equal(d.chapters.filter(c=>c.additionalBridges?.includes(d.comparison.slug)).length,4);});
test('All prior complete studies, narration, transcript and planning files retain pinned bytes',()=>{const fixture=json('tests/fixtures/restoration-baseline-hashes.json');assert.equal(fixture.baseline,'eebe9c097f1ac6795a63ccb258a87067f91460c9');assert(Object.keys(fixture.files).length>90);for(const [p,hash] of Object.entries(fixture.files))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),hash,p);});
test('Six unit readings and open research scope exist in the complete static article',()=>{const text=fs.readFileSync(path.join(root,'content/bridges/'+d.comparison.slug+'.md'),'utf8');assert(text.split(/\s+/).length>2000);for(const row of d.comparison.records)for(const k of ['agency','timing','boundary','scope','question'])assert(text.includes(row[k]),row.id+' '+k);assert(text.includes('no new manuscript collation'));});
test('The review cycle identifies actual gaps, implemented work and unfinished research',()=>{assert.equal(d.improvementCycle.reviewFindings.length,2);assert(d.improvementCycle.implemented.length>=3);assert(d.improvementCycle.remaining.length>=4);const text=fs.readFileSync(path.join(root,'content/developed/connected-arguments.md'),'utf8');for(const item of [...d.improvementCycle.reviewFindings,...d.improvementCycle.implemented,...d.improvementCycle.remaining])assert(text.includes(item));});
test('Listening filter is cache-pinned and no new recorded assets are invented',()=>{const assets=json('products/media/manifest.json').assets;assert.equal(assets.length,2);assert(!assets.some(a=>d.studies.some(s=>s.slug===a.id)));const hash=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'assets/js/products-tools.js'))).digest('hex').slice(0,16);for(const f of ['index.html','san-reader.html'])assert(fs.readFileSync(path.join(root,f),'utf8').includes('products-tools.js?v='+require('../editorial/authorial.cjs').version+'&amp;asset='+hash));});
