"""Native browser checks for the shared roadmap; never mutate repository state."""
from pathlib import Path
import json
import zipfile
import hashlib

def run_roadmap_checks(page, ctx, open_page, navigate, check, screenshot, OUT, BASE):
    def open_(slug):
        open_page(page,slug)
        page.wait_for_function('(slug)=>document.querySelector("#article-body").dataset.roadmapReady===slug',arg=slug)
    page.set_viewport_size({'width':1440,'height':1000})
    open_('research-roadmap')
    check('Shared roadmap renders all thirty-six task acceptance criteria',page.locator('#roadmap-tasks .roadmap-task').count()==36)
    check('Long-term phase sequence has seven explicit exit criteria',page.locator('.roadmap-phases section').count()==7)
    check('Dependency graph has keyboard-addressable nodes and a text equivalent',page.locator('#roadmap-graph a[tabindex="0"]').count()>1 and 'Prerequisites' in page.locator('#roadmap-graph-text').inner_text())
    page.locator('#roadmap-task-focus').select_option('pilot-chapter')
    check('Graph selection exposes the opening chapter prerequisites','sacred-center' in page.locator('#roadmap-graph-text').inner_text())
    page.locator('#roadmap-search').fill('tabor')
    check('Roadmap search finds the precise citation task',page.locator('#roadmap-tasks .roadmap-task').count()>=1 and page.locator('#task-tabor-citations').count()==1)
    page.locator('#roadmap-search').fill('zzzzz-no-task')
    check('Empty roadmap search gives a readable recovery state','No tasks match' in page.locator('#roadmap-tasks').inner_text())
    page.locator('#roadmap-search').fill('')
    page.locator('#roadmap-ready').check()
    check('Ready filter excludes blocked and already delivered work',page.locator('#roadmap-tasks .roadmap-task').count()>0 and page.locator('#task-pilot-chapter').count()==0 and page.locator('#task-archive-integrity').count()==0)
    page.locator('#roadmap-ready').uncheck()
    with page.expect_download() as ev: page.locator('#roadmap-export').click()
    data=json.loads(Path(ev.value.path()).read_text())
    check('Roadmap export includes real acceptance criteria and dependencies',len(data['tasks'])==36 and all(t['acceptance'] for t in data['tasks']))
    with page.expect_download() as ev: page.locator('#roadmap-xlsx').click()
    workbook_path=Path(ev.value.path())
    with zipfile.ZipFile(workbook_path) as z:
        check('Excel download contains exactly nine worksheets','xl/workbook.xml' in z.namelist() and len([n for n in z.namelist() if n.startswith('xl/worksheets/sheet') and n.endswith('.xml')])==9)
    manifest_url=page.locator('#roadmap-xlsx').evaluate('(e)=>new URL("workbook-manifest.json",e.href).href')
    response=page.request.get(manifest_url)
    check('Downloaded workbook matches the published SHA-256 manifest',response.ok and hashlib.sha256(workbook_path.read_bytes()).hexdigest()==response.json()['sha256'])
    screenshot(page,'roadmap-desktop.png')
    open_('source-coverage')
    check('Coverage view paginates the complete source archive',page.locator('#coverage-rows .roadmap-task').count()==25 and '354' in page.locator('#coverage-count').inner_text())
    page.locator('#coverage-filter').select_option('unlinked')
    check('Unlinked source rows are not mislabeled unread','does not mean unread' in page.locator('#coverage-rows').inner_text())
    page.locator('#coverage-search').fill('zzzz-unfindable')
    check('Coverage empty state remains usable','No source record matches' in page.locator('#coverage-rows').inner_text())
    page.locator('#coverage-search').fill('')
    page.locator('#coverage-filter').select_option('')
    page.locator('#coverage-more').click()
    check('Coverage pagination reveals additional original records',page.locator('#coverage-rows .roadmap-task').count()==50)
    with page.expect_download() as ev: page.locator('#coverage-export').click()
    check('Coverage export preserves every source hash',len(json.loads(Path(ev.value.path()).read_text())['rows'])==354)
    open_('melchizedek-priesthood-and-transmission')
    page.locator('#melchizedek-passages summary').click()
    check('New article exposes five passage-role comparisons',page.locator('#melchizedek-passages section').count()==5)
    check('Nag Hammadi access scope and translation credit are visible','direct-page retrieval failed' in page.locator('#melchizedek-passages').inner_text())
    screenshot(page,'melchizedek-desktop.png')
    for slug in ['research-roadmap','source-coverage','melchizedek-priesthood-and-transmission']:
        page.set_viewport_size({'width':390,'height':844})
        open_(slug)
        check('Mobile view fits the screen: '+slug,page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        screenshot(page,slug+'-mobile.png')
    page.set_viewport_size({'width':1440,'height':1000})
    open_('research-roadmap')
