'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),P=require('../tools/roadmap.cjs'),R=require('../editorial/roadmap.cjs');
const read=f=>JSON.parse(fs.readFileSync(path.join(ROOT,f),'utf8'));
const roadmap=read('data/roadmap.json'),coverage=read('data/source-coverage.json'),pages=read('data/page-index.json'),slugs=new Set(pages.map(p=>p.slug));
test('Canonical roadmap has 36 deliverables, valid routes and acyclic dependencies',()=>{assert.equal(roadmap.tasks.length,36);assert.deepEqual(P.validate(R.plan,slugs),[]);assert.equal(roadmap.summary.dependencyEdges,44);for(const t of roadmap.tasks)assert(t.targetDate===null);});
test('Cycles, unknown dependencies and unsupported completion claims fail closed',()=>{const p=structuredClone(R.plan);p.tasks[0].dependsOn=['planning-workbook'];assert(P.validate(p).some(e=>e.includes('cycle')));p.tasks[0].dependsOn=['not-a-task'];assert(P.validate(p).some(e=>e.includes('Unknown')));p.tasks[0].dependsOn=[];p.tasks[0].evidence=[];assert(P.validate(p).some(e=>e.includes('completion evidence')));});
test('Blocked manuscript tasks expose unmet prerequisites and do not appear ready to start',()=>{const r=roadmap.tasks.find(t=>t.id==='pilot-chapter');assert(r.unmetDependencies.length>0);assert.equal(r.readyToStart,false);for(const t of roadmap.tasks.filter(t=>t.readyToStart)){assert.equal(t.status,'Not started');assert.equal(t.unmetDependencies.length,0);}});
test('Every original source appears once with real article and chapter links',()=>{assert.equal(coverage.rows.length,354);assert.equal(new Set(coverage.rows.map(r=>r.sourceFile)).size,354);for(const r of coverage.rows){assert.equal(r.readingStatus,'Not inferred');for(const slug of r.articles){const a=pages.find(p=>p.slug===slug);assert(a.references.some(s=>s.slug===r.slug));}for(const id of r.chapters)assert(roadmap.chapters.some(c=>c.id===id));}});
test('Coverage is not presented as unread or as manuscript approval',()=>{assert(coverage.policy.includes('does not measure'));for(const c of roadmap.chapters){assert.equal(c.authorApproved,false);assert.equal(c.manuscriptStatus,'Not assessed as a manuscript chapter');}assert.equal(roadmap.chapters.length,17);});
test('First Melchizedek comparison preserves author questions and exact external access scopes',()=>{const p=pages.find(p=>p.slug===R.articles[0].slug);assert(p.references.some(r=>r.file.startsWith('gpt2026dragon2656_')));assert(R.articles[0].body.includes('Turn 84'));const ev=read('data/melchizedek-evidence.json');assert.equal(ev.rows.length,5);for(const row of ev.rows)assert(row.passage&&row.limit&&row.source.scope);assert(ev.rows.find(r=>r.id==='nag-hammadi').source.scope.includes('direct-page retrieval failed'));});
test('Existing board task advances only to citation verification, not completed research',()=>{const f=read('data/foundations.json');const t=f.tasks.find(t=>t.id==='melchizedek');assert.equal(t.stage,'Verify citations');assert(t.detail.includes('first passage'));assert.equal(roadmap.tasks.find(t=>t.id==='melchizedek').status,'Not started');});
test('Planning assets are versioned and use no browser-local writes to shared status',()=>{for(const file of ['san-reader.html','index.html']){const text=fs.readFileSync(path.join(ROOT,file),'utf8');assert(text.includes('./assets/js/roadmap-tools.js?v='+require('../editorial/products.json').version));assert(text.includes('./assets/css/roadmap.css?v='+require('../editorial/products.json').version));}const js=fs.readFileSync(path.join(ROOT,'assets/js/roadmap-tools.js'),'utf8');assert(!js.includes('localStorage.setItem'));assert(js.includes('data-task-focus'));});
test('Published workbook matches its version and all canonical input hashes',()=>{const crypto=require('node:crypto'),m=read('planning/workbook-manifest.json');assert.equal(m.version,R.version);const digest=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex');assert.equal(digest('planning/'+m.file),m.sha256);assert.equal(m.sheets.length,9);assert.equal(m.formulaErrorCount,0);assert(m.formulaCells>500);for(const [f,hash] of Object.entries(m.inputHashes))assert.equal(digest(f),hash,f);});

test('Messianic-number clarification preserves the author question and identifies the AI compression',()=>{const a=R.articles[0];assert(a.body.includes('author turn 84'));assert(a.body.includes('AI reply in turn 85'));assert(a.body.includes('neither an automatic refutation'));assert(a.body.includes('two different axes'));const ref=R.references.find(r=>r.id==='melch-kim2018');assert(ref.scope.includes('abstract'));assert(ref.scope.includes('not a recovered author acknowledgment'));assert(a.externalSources.includes(ref.id));});
test('Release tree contains developed roadmap sources, not transfer placeholders',()=>{for(const f of ['editorial/roadmap.cjs','data/roadmap.json','planning/Theology-Research-Plan.xlsx'])assert(fs.existsSync(path.join(ROOT,f)));for(const f of fs.readdirSync(ROOT))assert(!/^(roadmap-transfer-|resume-foundation-|foundation-transfer-)/.test(f));assert(!fs.existsSync(path.join(ROOT,'tools/roadmap-review-fix.py')));});
