"""Real-origin tests for the ranked workbook. Run with a static server or SITE_ORIGIN.
Storage, downloads and navigation use Chromium, not a simulated document.
"""
import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'theology-rank-test-output';OUT.mkdir(exist_ok=True)
ORIGIN=os.environ.get('SITE_ORIGIN','http://127.0.0.1:4174').rstrip('/')
URL=ORIGIN+'/theology-wiki/role-workbook.html'
checks=[];errors=[]
def check(name,condition):
    if not condition: raise AssertionError(name)
    checks.append(name);print('PASS',name,flush=True)
def ready(page,extra=''):
    page.goto(URL+extra,wait_until='domcontentloaded')
    page.wait_for_selector('body[data-ready="true"]')
def filepayload(value):return {'name':'scenario.json','mimeType':'application/json','buffer':json.dumps(value).encode()}
with sync_playwright() as pw:
    launch={'headless':True}
    if os.environ.get('CHROMIUM'):launch['executable_path']=os.environ['CHROMIUM']
    browser=pw.chromium.launch(**launch)
    ctx=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
    page=ctx.new_page();page.set_default_timeout(20000)
    page.on('pageerror',lambda e:errors.append(str(e)))
    requests=[];page.on('request',lambda r:requests.append(r.url))
    try:
        ready(page)
        check('native HTTP loaded both actual data assets',all(any('/rankings/'+f in r for r in requests) for f in ['data.json','reception.json']))
        check('ranked view includes the initial 24-person roster',page.locator('#results tbody tr').count()==24)
        check('actual default first-beast scores are displayed',page.locator('#results .score').first.inner_text()=='15.0')
        check('unreviewed figures are visibly not ranked','Not ranked' in page.locator('#results').inner_text())
        page.screenshot(path=str(OUT/'ranked-desktop.png'),full_page=True)
        page.locator('#profile').select_option('second')
        check('second-role profile changes scores','7.5' in page.locator('#results .score').first.inner_text())
        page.locator('[data-person="netanyahu"]').click()
        check('a dossier names its counterpart and source','counterpart: Donald Trump' in page.locator('#detail-body').inner_text() and page.locator('#detail-body a[href*="jns.org"]').count()>0)
        page.keyboard.press('Escape')
        check('keyboard can close the native dialog',not page.locator('#detail').is_visible())
        page.locator('[data-tab="matrix"]').click()
        page.locator('[data-assessment="a09"]').click()
        check('countercase remains visible beside Amodei score','contradicts unconditional alignment' in page.locator('#detail-body').inner_text())
        page.locator('#close-detail').click()
        page.locator('#lens').select_option('narrative')
        check('narrative lens recalculates individual matrix cells','0 - 0' in page.locator('[data-assessment="a09"]').inner_text())
        ready(page,'?profile=first&lens=pattern&tab=ranked')
        check('shareable profile/lens state survives navigation',page.locator('#profile').input_value()=='first' and page.locator('#lens').input_value()=='pattern')
        page.locator('[data-choose="trump"]').check();page.locator('[data-choose="putin"]').check();page.locator('#compare').click()
        check('two-figure comparison opens both dossiers',page.locator('#detail-body h2').count()==2)
        page.locator('#close-detail').click()
        page.locator('#query').fill('nonexistent-qqq')
        check('empty search state is explicit','No matching figures' in page.locator('#results').inner_text())
        page.locator('#query').fill('');page.locator('#era').select_option('Ancient')
        check('era filter composes with scoring',page.locator('#results tbody tr').count()==4)
        page.locator('#era').select_option('');page.locator('#weights summary').click()
        page.locator('[data-weight="personal"]').fill('5');page.locator('[data-weight="personal"]').press('Tab')
        check('weight changes alter the displayed score','27.8' in page.locator('#results').inner_text())
        page.reload();page.wait_for_selector('body[data-ready="true"]')
        check('personal weights persist on the real origin',page.locator('[data-weight="personal"]').input_value()=='5')
        page.evaluate("localStorage.setItem('theology:reading:v2',JSON.stringify({version:1,saved:['home']}))")
        page.once('dialog',lambda d:d.accept());page.locator('#reset').click()
        check('reset preserves unrelated wiki bookmarks',page.evaluate("JSON.parse(localStorage.getItem('theology:reading:v2')).saved[0]")=='home')
        page.locator('#criterion').select_option('personal')
        if not page.locator('#weights').evaluate('(e)=>e.open'): page.locator('#weights summary').click()
        page.locator('[data-weight="personal"]').fill('0');page.locator('[data-weight="personal"]').press('Tab')
        check('zero-total scenario rejected without breaking the view','positive weight' in page.locator('#status').inner_text() and page.locator('#results tbody tr').count()==24)
        page.locator('#criterion').select_option('')
        with page.expect_download() as dl:page.locator('#export-csv').click()
        path=OUT/'ranked-export.csv';dl.value.save_as(path)
        check('CSV download has rows and declared lens',len(path.read_text().splitlines())==25 and 'Weighted match' in path.read_text())
        with page.expect_download() as dl:page.locator('#export-json').click()
        path=OUT/'scenario-export.json';dl.value.save_as(path);scenario=json.loads(path.read_text())
        check('scenario download retains full data and weights',scenario['type']=='theology-pattern-scenario' and len(scenario['data']['people'])==24)
        page.locator('#import').set_input_files(filepayload({'version':999}))
        # File.text() resolves asynchronously; wait for the actual result, not a fixed delay.
        expect(page.locator('#status')).to_contain_text('matching ranked-pattern scenario')
        check('invalid import keeps the current dataset','matching ranked-pattern scenario' in page.locator('#status').inner_text() and page.locator('#results tbody tr').count()==24)
        bad=json.loads(json.dumps(scenario));bad['data']['sources'][0]['url']='javascript:alert(1)'
        page.locator('#import').set_input_files(filepayload(bad))
        expect(page.locator('#status')).to_contain_text('HTTPS')
        check('unsafe source URL import is rejected','HTTPS' in page.locator('#status').inner_text())
        page.locator('#import').set_input_files(filepayload(scenario))
        expect(page.locator('#status')).to_contain_text('imported locally')
        check('valid export can be restored','imported locally' in page.locator('#status').inner_text())
        page.locator('#person-form').evaluate('(f)=>f.closest("details").open=true')
        page.locator('#person-form [name=name]').fill('Test Figure <img src=x onerror=alert(1)>')
        page.locator('#person-form [name=note]').fill('Automated browser fixture, not a factual public allegation.')
        page.locator('#person-form button').click()
        check('new roster entry is added without HTML execution',page.locator('#results tbody tr').count()==25 and page.locator('img[src=x]').count()==0)
        f=page.locator('#assessment-form');f.evaluate('(f)=>f.closest("details").open=true')
        new_id=page.locator('#assessment-form [name=person] option').last.get_attribute('value')
        f.locator('[name=person]').select_option(new_id);f.locator('[name=criterion]').select_option('personal')
        for name,value in {'event':'Test fixture event; no real claim.','reason':'Test fixture mapping.','counter':'Test fixture countercase.','fit':'2','penalty':'1','url':'https://example.com/fixture','title':'Automated fixture','access':'Test input only.','reviewer':'Automated browser test'}.items():f.locator('[name='+name+']').fill(value)
        f.locator('button').click()
        check('assessment form creates a validated local dossier','Assessment saved' in page.locator('#status').inner_text())
        page.reload();page.wait_for_selector('body[data-ready="true"]')
        check('local assessments survive a real reload',page.locator('#results tbody tr').count()==25)
        page.once('dialog',lambda d:d.accept());page.locator('#reset').click()
        page.locator('[data-tab=reception]').click()
        check('all 22 prior interpretations are accessible',page.locator('#archive-results .card').count()==22)
        page.locator('#archive-query').fill('Personal identification expressly declined')
        check('declined Zuckerberg identification remains distinct',page.locator('#archive-results .card').count()==1 and 'declines' in page.locator('#archive-results').inner_text())
        page.locator('[data-tab=bridges]').click()
        check('nine interfaith comparisons preserve their differences',page.locator('#results .card').count()==9 and 'Difference to preserve' in page.locator('#results').inner_text())
        page.screenshot(path=str(OUT/'interfaith-desktop.png'),full_page=True)
        page.locator('[data-tab=plan]').click()
        check('supplemental plan has 12 bounded tasks',page.locator('#results .card').count()==12)
        page.locator('[data-tab=method]').click()
        check('method explains ranking and cosmic-ground premise','intentionally ranks' in page.locator('#results').inner_text() and 'computational ground' in page.locator('#results').inner_text())
        page.set_viewport_size({'width':390,'height':844});ready(page)
        check('mobile layout contains horizontal overflow within tables',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        page.screenshot(path=str(OUT/'ranked-mobile.png'),full_page=True)
        check('no runtime errors in normal native interactions',not errors)
        # The actual integrated reader must retain and expose the new link.
        if os.environ.get('CHECK_WIKI','1')=='1':
            for entry in ['san-reader.html','index.html']:
                page.goto(ORIGIN+'/theology-wiki/'+entry,wait_until='domcontentloaded')
                page.locator('#pattern-workbook-link').wait_for()
                check(entry+' exposes exactly one workbook link',page.locator('#pattern-workbook-link').count()==1)
                page.locator('#pattern-workbook-link').click();page.wait_for_selector('body[data-ready="true"]')
                check(entry+' launches the actual ranked page','role-workbook.html' in page.url)
        denied=browser.new_context();denied.add_init_script("Storage.prototype.setItem=function(){throw Error('denied')};Storage.prototype.getItem=function(){throw Error('denied')};history.replaceState=function(){throw Error('denied')};")
        p=denied.new_page();ready(p)
        check('denied storage/history retains usable rankings','session-only' in p.locator('#storage-note').inner_text() and p.locator('#results tbody tr').count()==24)
        denied.close()
        failed=browser.new_context();failed.route('**/rankings/data.json',lambda r:r.abort());p=failed.new_page();p.goto(URL);p.wait_for_selector('#status.error')
        check('failed transport shows error and charter fallback','could not load' in p.locator('#status').inner_text() and p.locator('a[href*="RESEARCH-CHARTER"]').count()>0)
        failed.close()
    finally:
        (OUT/'browser-report.json').write_text(json.dumps({'origin':ORIGIN,'checks':checks,'runtimeErrors':errors,'count':len(checks)},indent=2))
        browser.close()
