/* A-Frame lifecycle, shared song transport and explicit input modes. Stats stay
 * on this device. No camera frames, controller traces, emails or remote scores. */
(function(){'use strict';const $=id=>document.getElementById(id),STORE='prism-current.v1.records';
 AFRAME.registerComponent('prism-game',{
  init(){this.T=AFRAME.THREE;this.art=PrismArt.create(this.T,this.el);this.audio=new PrismAudio();this.phase='menu';this.track='first-light';this.difficulty='flow';this.input='slice';this.immersive=false;this.state=null;this.previous=[null,null];this.message='';this.lastTime=0;this.activeHand=0;this.recorded=false;this.busy=false;this.pointer=null;this.offset=0;this.loadSerial=0;this.records={};try{const v=JSON.parse(localStorage.getItem(STORE)||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))for(const [k,r] of Object.entries(v).slice(0,100))if(r&&Number.isFinite(r.score)&&r.score>=0&&Number.isFinite(r.accuracy)&&r.accuracy>=0&&r.accuracy<=100)this.records[k]=r;}catch{}
   this.xr=PrismXR.install(this);this.ui();this.keyboard();this.pointerInput();this.xrTime=0;this.control=globalThis.PrismControl?.install(this);this.phrases=globalThis.PrismPhrases?.install(this);this.practice=globalThis.PrismPractice?.install(this);this.syncControls();
   document.addEventListener('visibilitychange',()=>{if(document.hidden){if(this.phase==='loading')this.abort();else this.pauseRun('Browser hidden. Resume when ready.');}});window.addEventListener('blur',()=>{if(!this.immersive)this.pauseRun('Window lost focus');this.resetBlades();});window.addEventListener('pagehide',()=>this.audio.pause());
   this.el.addEventListener('renderstart',()=>{this.rendererReady=true;});this.rendererReady=!!this.el.renderer;
   window.Prism={component:this,snapshot:()=>({version:'0.5.0',phase:this.phase,track:this.track,difficulty:this.difficulty,input:this.input,time:this.state?.time||0,state:this.state?PrismCore.result(this.state):null,notes:this.state?.song.notes||[],judged:this.state?{...this.state.judged}:{},immersive:this.immersive,calibrated:this.xr.calibrated,blend:this.xr.session?.environmentBlendMode,studio:this.art.studio.visible,ready:this.rendererReady,scoreRecords:{...this.records},practice:this.practice?.snapshot||null,audio:this.audio.a?.state,controller:!!this.control?.connected,mixer:{music:this.audio.volume,effects:this.audio.effectsVolume,rate:this.audio.feedbackRate,muted:this.audio.muted},message:this.message})};
  },
  pause(){this.pauseRun('Scene suspended. Resume when ready.');},
  remove(){this.practice?.dispose();this.control?.dispose();this.audio?.stop();this.art?.dispose?.();},
  notice(text){this.message=text;$('status').textContent=text;},
  ui(){const cards=$('tracks');for(const s of PrismCore.TRACKS){const b=document.createElement('button');b.className='track';b.dataset.track=s.id;b.innerHTML=`<span class="track-orb"></span><span><strong>${s.name}</strong><small>${s.subtitle}</small></span><span class="bpm">${s.bpm}<small>BPM</small></span>`;b.onclick=()=>{this.abort();this.track=s.id;this.syncControls();};cards.append(b);}
   $('start').onclick=()=>this.phase==='paused'?this.resume():this.start();$('pause').onclick=()=>this.phase==='playing'?this.pauseRun('Paused'):this.resume();$('menu-button').onclick=()=>{this.pauseRun('Choose another track');this.abort();};$('resume').onclick=()=>this.resume();$('retry').onclick=()=>this.start();$('back').onclick=()=>this.abort();
   $('difficulty').onchange=e=>{const value=e.target.value;this.abort();this.difficulty=value;this.syncControls();};$('input').onchange=e=>{const value=e.target.value;this.abort();this.input=value;this.syncControls();};$('volume').oninput=e=>{this.audio.level(Number(e.target.value)/100);this.control?.syncAudio();};$('mute').onchange=e=>{this.audio.level(this.audio.volume,e.target.checked);this.control?.syncAudio();};
   $('hand').onclick=()=>{this.activeHand=1-this.activeHand;$('hand').textContent=this.activeHand?'R / CORAL':'L / MINT';};$('reach').onchange=()=>{if(this.phase==='playing')this.pauseRun('Reach changed. Restart to apply.');};$('latency').onchange=e=>{this.offset=Math.max(-.15,Math.min(.15,Number(e.target.value)/1000));this.pauseRun('Timing offset changed. Restart to apply.');};
   this.syncControls();
  },
  syncControls(){$('menu').inert=!['menu','loading'].includes(this.phase);$('pause-panel').inert=this.phase!=='paused';$('results').inert=this.phase!=='complete';document.body.dataset.phase=this.phase;document.body.dataset.input=this.input;for(const b of document.querySelectorAll('[data-track]'))b.setAttribute('aria-pressed',String(b.dataset.track===this.track));$('difficulty').value=this.difficulty;$('input').value=this.input;$('track-copy').textContent=PrismCore.TRACKS.find(s=>s.id===this.track).description;$('now-playing').textContent=PrismCore.TRACKS.find(s=>s.id===this.track).name;$('input-label').textContent=this.immersive?'TRACKED SABERS':this.input==='gamepad'?'LT / LB / RB / RT':this.input==='keys'?'D / F / J / K':'MOUSE / TOUCH SLICES';$('start').textContent=this.busy?'Preparing music...':this.phase==='paused'?'Resume session':'Play in browser';$('start').disabled=this.busy;const mode=this.immersive?(this.el.is('ar-mode')?'ar':'vr'):this.input;const k=[this.track,this.difficulty,mode].join('/'),record=this.records[k];$('personal-best').textContent=record?`Local best / ${record.score.toLocaleString()} / ${record.accuracy}%`:'No local best for this track and mode yet.';this.control?.sync();this.phrases?.sync();this.practice?.sync();},
  async start(){if(this.busy)return;const serial=++this.loadSerial,track=this.track;this.busy=true;this.audio.context().resume().catch(()=>{});this.audio.stop();this.phase='loading';this.notice('Preparing the original soundtrack on your device...');this.syncControls();try{await this.audio.prepare(track);if(serial!==this.loadSerial||document.hidden){if(serial===this.loadSerial)this.abort();return;}const sourceChart=PrismCore.chart(this.track,this.difficulty),chart=this.practice?.selection(sourceChart)||sourceChart;this.state=PrismCore.create(chart,{mode:this.immersive?'slice':this.input==='gamepad'?'keys':this.input,reach:Number($('reach').value)});this.runMode=this.immersive?(this.el.is('ar-mode')?'ar':'vr'):this.input;this.runAudio=this.practice?.prepare(chart)||this.track;this.runOffset=this.offset;this.recorded=false;this.resetBlades();await this.art.prepare?.(this.state);if(serial!==this.loadSerial)return;const played=await this.audio.play(this.runAudio||this.track,0);if(serial!==this.loadSerial||played===false)return;if(document.hidden){this.abort();return;}this.phase='playing';this.state.state='playing';this.lastTime=0;this.notice('Listen first. Notes begin after the count-in.');$('scene-wrap').focus();}catch(e){if(serial===this.loadSerial){this.phase='menu';this.state=null;this.notice(e.message);}}finally{if(serial===this.loadSerial){this.busy=false;this.syncControls();}}},
  // Keep user pause separate from A-Frame's wrapped component.pause lifecycle.
  pauseRun(reason='Paused'){if(this.phase!=='playing')return;this.audio.pause();this.phase='paused';if(this.state)this.state.state='paused';this.resetBlades();this.notice(reason);this.syncControls();},
  async resume(){if(this.phase!=='paused'||!this.state||this.busy)return;if(this.immersive&&!this.xr.calibrated){this.notice('Recenter the stage first.');return;}const serial=this.loadSerial;this.busy=true;try{const played=await this.audio.play(this.runAudio||this.track,this.audio.offset);if(serial!==this.loadSerial||this.phase!=='paused'||played===false)return;if(document.hidden){this.audio.pause();return;}this.state.state='playing';this.phase='playing';this.lastTime=this.audio.offset;this.resetBlades();this.syncControls();if(!this.immersive)$('scene-wrap').focus();}catch(e){if(serial===this.loadSerial)this.notice(e.message);}finally{if(serial===this.loadSerial){this.busy=false;this.syncControls();}}},
  abort(){this.practice?.cancelRun();this.runAudio=null;this.loadSerial++;this.busy=false;this.audio.stop();this.phase='menu';this.state=null;this.resetBlades();this.syncControls();},
  clearBlade(hand){this.previous[hand]=null;},resetBlades(){this.previous=[null,null];this.pointer=null;for(const h of[0,1])this.art.blade(h,new this.T.Matrix4(),false);},
  blade(hand,pose,time){if(this.phase!=='playing')return;const prev=this.previous[hand];if(prev){const events=PrismCore.slice(this.state,hand,prev.pose,pose,prev.time,time);this.feedback(events);}this.previous[hand]={pose,time};},
  feedback(events){for(const e of events){const say=!this.control||this.control.textAllowed();if(e.type==='hit'){const n=this.state.song.notes[e.id];this.audio.hit(n.hand,e.quality);this.art.burst(n,PrismCore.position(n,this.state.time,this.state.reach));this.xr.haptic(n.hand);if(say)this.notice(e.quality>.86?'CLEAN CUT':e.quality>.65?'IN THE FLOW':'CONNECTED');}else if(say)this.notice('Wrong hand or cut direction. Keep going.');}},
  keyboard(){window.addEventListener('keydown',e=>{if(this.audio.a?.state==='suspended')this.audio.a.resume().catch(()=>{});if(e.repeat)return;if(e.code==='Escape'||e.code==='KeyP'){if(e.target.tagName==='INPUT'&&e.code==='KeyP')return;e.preventDefault();this.phase==='playing'?this.pauseRun('Paused'):this.resume();return;}if(/^(INPUT|SELECT|TEXTAREA|BUTTON|A)$/.test(e.target.tagName))return;const lanes={KeyD:0,KeyF:1,KeyJ:2,KeyK:3};if(e.code==='KeyZ'){this.activeHand=0;$('hand').textContent='L / MINT';}if(e.code==='KeyX'){this.activeHand=1;$('hand').textContent='R / CORAL';}if(this.phase==='playing'&&this.input==='keys'&&!this.immersive&&e.code in lanes){e.preventDefault();const event=PrismCore.tap(this.state,lanes[e.code],this.audio.time()+this.runOffset);if(event)this.feedback([event]);}});},
  pointerInput(){const wrap=$('scene-wrap'),pos=e=>{const box=wrap.getBoundingClientRect(),mouse=new this.T.Vector2((e.clientX-box.left)/box.width*2-1,-(e.clientY-box.top)/box.height*2+1),ray=new this.T.Raycaster();ray.setFromCamera(mouse,this.el.camera);const point=new this.T.Vector3();if(!ray.ray.intersectPlane(new this.T.Plane(new this.T.Vector3(0,0,1),-PrismCore.PLANE),point))return null;return point;};
   wrap.addEventListener('contextmenu',e=>e.preventDefault());wrap.addEventListener('pointerdown',e=>{if(this.immersive||this.phase!=='playing'||this.input!=='slice')return;e.preventDefault();wrap.focus();wrap.setPointerCapture(e.pointerId);if(e.pointerType==='mouse')this.activeHand=e.button===2?1:0;const p=pos(e);if(p)this.pointer={id:e.pointerId,p,time:this.audio.time()+this.runOffset};});
   wrap.addEventListener('pointermove',e=>{if(!this.pointer||this.pointer.id!==e.pointerId||this.immersive||this.phase!=='playing')return;const p=pos(e);if(!p)return;const now=this.audio.time()+this.runOffset,a=this.pointer.p,old={a:[a.x,a.y,PrismCore.PLANE+.15],b:[a.x,a.y,PrismCore.PLANE-.18]},next={a:[p.x,p.y,PrismCore.PLANE+.15],b:[p.x,p.y,PrismCore.PLANE-.18]};const ev=PrismCore.slice(this.state,this.activeHand,old,next,this.pointer.time,now);this.feedback(ev);this.pointer={id:e.pointerId,p,time:now};const matrix=new this.T.Matrix4().makeTranslation(p.x,p.y,PrismCore.PLANE+.54);this.art.blade(this.activeHand,matrix,true);});
   const clear=()=>{this.pointer=null;this.resetBlades();};wrap.addEventListener('pointerup',clear);wrap.addEventListener('pointercancel',clear);wrap.addEventListener('lostpointercapture',clear);
  },
  complete(){if(this.recorded||!this.state)return;this.audio.stop();this.recorded=true;this.phase='complete';const r=PrismCore.result(this.state),key=[r.track,r.difficulty,this.runMode].join('/'),old=this.records[key];if(this.state.song.practice){this.practice?.result(r);}else if(!old||r.score>old.score){this.records[key]={score:r.score,accuracy:r.accuracy,best:r.best};try{localStorage.setItem(STORE,JSON.stringify(this.records));}catch{this.notice('Storage unavailable. This score is not saved.');}}$('result-score').textContent=r.score.toLocaleString();$('result-detail').textContent=`${r.hits} clean connections / ${r.misses} misses / ${r.bad} wrong cuts / ${r.best} best combo / ${r.accuracy}% quality`;$('result-title').textContent=r.accuracy>90?'Beautifully in sync.':r.accuracy>60?'You found your flow.':'One more current?';this.syncControls();},
  tick(time,delta){const dt=Math.min(.06,(delta||0)/1000);if(this.phase==='playing'){const t=this.audio.time()+this.runOffset;if(this.audio.a.state!=='running'){this.pauseRun('Audio was interrupted. Resume when ready.');}else if(t-this.lastTime>.3){this.lastStall={gap:t-this.lastTime,audio:t,previous:this.lastTime};this.pauseRun('Rendering stalled. Resume when the view is steady.');}else{PrismCore.advance(this.state,Math.max(0,t));this.lastTime=t;}}this.control?.tick(time);this.phrases?.tick(time);const t=this.state?.time||0;this.xr.tick(t);this.art.update(this.state,this.phase==='menu'||this.phase==='loading'?time/1000:t,dt,this.phase==='menu'||this.phase==='loading');if(this.state){$('score').textContent=this.state.score.toLocaleString();$('combo').textContent=this.state.combo;const left=Math.max(0,this.state.song.duration-t);$('time').textContent=Math.floor(Math.ceil(left)/60)+':'+String(Math.ceil(left)%60).padStart(2,'0');$('progress').value=t/this.state.song.duration;$('countdown').textContent=t<this.state.song.notes[0].time?Math.max(1,Math.ceil((this.state.song.notes[0].time-t)*this.state.song.bpm/60)):' ';if(this.state.state==='complete')this.complete();}this.practice?.tick();},
 });})();
