/* One AudioContext and one whole-song buffer: graphics frames cannot schedule
 * late notes. Pause preserves the sample offset; only a gesture resumes audio. */
(function(root){'use strict';class AudioTransport{
 constructor(){this.a=null;this.source=null;this.startAt=0;this.offset=0;this.playing=false;this.cache=new Map();this.pending=null;this.volume=.55;this.muted=false;}
 context(){if(!this.a){this.a=new (window.AudioContext||window.webkitAudioContext)();this.gain=this.a.createGain();this.gain.gain.value=this.volume;this.gain.connect(this.a.destination);this.effects=this.a.createGain();this.effects.gain.value=.22;this.effects.connect(this.a.destination);}return this.a;}
 async prepare(id){this.context();if(this.cache.has(id))return;if(this.pending?.id===id)return this.pending.promise;
 const promise=new Promise((resolve,reject)=>{const w=new Worker('./music-worker.js'),timer=setTimeout(()=>{w.terminate();reject(Error('Music preparation timed out.'));},20000);w.onmessage=e=>{clearTimeout(timer);w.terminate();if(e.data.error){reject(Error(e.data.error));return;}const d=e.data,b=this.a.createBuffer(2,d.left.length,d.rate);b.copyToChannel(d.left,0);b.copyToChannel(d.right,1);this.cache.set(id,b);if(this.cache.size>3)this.cache.delete(this.cache.keys().next().value);resolve();};w.onerror=()=>{clearTimeout(timer);w.terminate();reject(Error('Could not prepare original soundtrack.'));};w.postMessage({id});});this.pending={id,promise};try{await promise;}finally{this.pending=null;}}
 async play(id,offset=0){const a=this.context();await a.resume();if(a.state!=='running')throw Error('Audio is suspended. Tap Play again.');this.stop();const b=this.cache.get(id);if(!b)throw Error('Music is not ready');this.offset=offset;this.source=a.createBufferSource();this.source.buffer=b;this.source.connect(this.gain);this.startAt=a.currentTime+.10;this.source.start(this.startAt,Math.min(offset,b.duration-.001));this.playing=true;}
 time(){return this.playing?Math.max(this.offset,this.offset+this.a.currentTime-this.startAt):this.offset;}
 pause(){if(this.playing)this.offset=this.time();this.stop();return this.offset;}
 stop(){if(this.source){try{this.source.stop();this.source.disconnect();}catch{}this.source=null;}this.playing=false;}
 level(value,muted=this.muted){this.volume=Math.max(0,Math.min(1,value));this.muted=muted;if(this.a){this.gain.gain.setTargetAtTime(muted?0:this.volume,this.a.currentTime,.02);this.effects.gain.setTargetAtTime(muted?0:.22,this.a.currentTime,.02);}}
 hit(hand,quality){if(!this.a||this.muted)return;const a=this.a,o=a.createOscillator(),g=a.createGain(),t=a.currentTime;o.type='sine';o.frequency.setValueAtTime(hand?640:470,t);o.frequency.exponentialRampToValueAtTime(hand?1000:720,t+.045);g.gain.setValueAtTime(.08*quality,t);g.gain.exponentialRampToValueAtTime(.0001,t+.065);o.connect(g);g.connect(this.effects);o.start(t);o.stop(t+.07);o.onended=()=>{o.disconnect();g.disconnect();};}
 }root.PrismAudio=AudioTransport;})(globalThis);
