/* Passthrough first: no camera-image access, room scan, upload, anchors or
 * hidden locomotion. Tracked controller samples alone drive saber collision. */
(function(root){'use strict';
 function install(g){const T=g.T,scene=g.el,art=g.art,$=id=>document.getElementById(id),hands={},priorButtons=new Map();let session=null,calibrated=false,missingSince=null,latestViewer=null,wasCentered=false,lastUI='',lastPaint=0;
  const panel=art.textPanel(1.48,.83);panel.mesh.position.set(0,1.45,-1.8);panel.mesh.name='In-headset rhythm menu';
  const hud=art.textPanel(1.32,.20);hud.mesh.position.set(0,1.93,-1.6);hud.mesh.name='In-headset score';
  const buttons=[],ray=new T.Raycaster(),controllerRay=new T.Vector3(),origin=new T.Vector3(),head=new T.Vector3();
  for(let i=0;i<4;i++){const m=new T.Mesh(new T.PlaneGeometry(.62,.15),new T.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,side:T.DoubleSide}));m.position.set(i%2? .36:-.36,i<2?-.065:-.26,.003);panel.mesh.add(m);m.userData.action=i;buttons.push(m);}
  function label(){return g.state?.state==='complete'?'Session complete':g.phase==='playing'?'Playing':g.phase==='paused'?'Paused':'Ready when you are';}
  function drawPanel(){const key=[g.phase,g.track,g.difficulty,g.state?.score,g.message,calibrated].join('|');if(key===lastUI)return;lastUI=key;const c=panel.context,w=panel.canvas.width,h=panel.canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#102336ee';c.fillRect(0,0,w,h);c.strokeStyle='#5c96a4';c.lineWidth=4;c.strokeRect(2,2,w-4,h-4);c.fillStyle='#8ae8d7';c.font='600 23px system-ui';c.fillText('PRISM CURRENT / '+(scene.is('ar-mode')?'PASSTHROUGH AR':'VR STUDIO'),40,49);c.fillStyle='#f1efe0';c.font='500 46px system-ui';c.fillText(label(),40,118);c.font='24px system-ui';c.fillStyle='#b8c9d5';c.fillText(PrismCore.TRACKS.find(s=>s.id===g.track).name+' · '+g.difficulty.toUpperCase(),40,161);c.font='19px system-ui';c.fillText('Clear your reach. Keep your feet planted. Trigger selects.',40,203);
   const labels=[g.phase==='paused'?'Resume':g.phase==='playing'?'Pause':'Start track','Next track','Recenter stage','Exit immersive'];for(let i=0;i<4;i++){const x=i%2?550:57,y=i<2?282:417;c.fillStyle=i===0?'#95e2cd':'#28455b';c.fillRect(x,y,418,84);c.fillStyle=i===0?'#123449':'#e7ecdf';c.font='600 25px system-ui';c.fillText(labels[i],x+22,y+51);}panel.texture.needsUpdate=true;
  }
  function centerStage(){if(!session)return;g.pauseRun('Stage recentered. Confirm your space before resuming.');const camera=scene.renderer.xr.getCamera();if(latestViewer){head.set(latestViewer.transform.position.x,latestViewer.transform.position.y,latestViewer.transform.position.z);controllerRay.set(0,0,-1).applyQuaternion(new T.Quaternion(latestViewer.transform.orientation.x,latestViewer.transform.orientation.y,latestViewer.transform.orientation.z,latestViewer.transform.orientation.w));}else{camera.getWorldPosition(head);camera.getWorldDirection(controllerRay);}controllerRay.y=0;if(controllerRay.lengthSq()<.01)controllerRay.set(0,0,-1);controllerRay.normalize();art.group.position.set(head.x,head.y-1.65,head.z);art.group.rotation.y=Math.atan2(-controllerRay.x,-controllerRay.z);art.group.updateMatrixWorld(true);g.resetBlades();calibrated=true;missingSince=null;lastUI='';}
  function action(i){if(i===0){if(!calibrated){centerStage();return;}g.phase==='playing'?g.pauseRun('Paused'):g.phase==='paused'?g.resume():g.start();}if(i===1){if(g.phase==='playing')g.pauseRun('Choose another track');g.abort();g.track=PrismCore.TRACKS[(PrismCore.TRACKS.findIndex(s=>s.id===g.track)+1)%3].id;g.syncControls();}if(i===2)centerStage();if(i===3)scene.exitVR();lastUI='';}
  async function enter(ar){g.pauseRun('Opening immersive mode');try{await g.audio.context().resume();if(ar)await scene.enterAR();else await scene.enterVR();}catch(e){g.notice('Could not enter '+(ar?'AR':'VR')+': '+e.message);}}
  $('enter-ar').onclick=()=>enter(true);$('enter-vr').onclick=()=>enter(false);
  if(navigator.xr){for(const [mode,id]of[['immersive-ar','enter-ar'],['immersive-vr','enter-vr']])navigator.xr.isSessionSupported(mode).then(ok=>{$(id).disabled=!ok;$(id).textContent=ok?(id==='enter-ar'?'Enter passthrough AR':'Enter VR studio'):(id==='enter-ar'?'AR unavailable here':'VR unavailable here');}).catch(()=>{});}
  const visibility=()=>{if(session?.visibilityState!=='visible'){g.pauseRun('Headset visibility changed');g.resetBlades();priorButtons.clear();}};
  const reset=()=>{calibrated=false;g.pauseRun('Reference space reset. Recenter the stage.');g.resetBlades();lastUI='';};
  scene.addEventListener('enter-vr',()=>{session=scene.renderer.xr.getSession();g.abort();g.immersive=true;calibrated=false;wasCentered=false;priorButtons.clear();g.pauseRun('Choose a track in the spatial menu');art.studio.visible=!scene.is('ar-mode');scene.renderer.setClearColor(0x000000,scene.is('ar-mode')?0:1);document.body.classList.add('immersive');if(scene.is('ar-mode')&&(!session||!['alpha-blend','additive'].includes(session.environmentBlendMode))){g.notice('The session is opaque, not passthrough AR.');scene.exitVR();return;}session?.addEventListener('visibilitychange',visibility);scene.renderer.xr.getReferenceSpace()?.addEventListener('reset',reset);});
  scene.addEventListener('exit-vr',()=>{session?.removeEventListener('visibilitychange',visibility);scene.renderer.xr.getReferenceSpace()?.removeEventListener('reset',reset);session=null;g.immersive=false;calibrated=false;g.pauseRun('Headset session ended');g.resetBlades();art.group.position.set(0,0,0);art.group.rotation.set(0,0,0);art.studio.visible=true;scene.renderer.setClearColor(0x0b1123,1);document.body.classList.remove('immersive');panel.mesh.visible=hud.mesh.visible=false;g.syncControls();});
  function tick(now){panel.mesh.visible=hud.mesh.visible=!!session;if(!session)return;const frame=scene.frame,space=scene.renderer.xr.getReferenceSpace();if(!frame||!space)return;const viewer=frame.getViewerPose(space);if(!viewer){g.pauseRun('Head tracking unavailable');g.resetBlades();return;}
   latestViewer=viewer;
   if(!wasCentered){wasCentered=true;centerStage();}
   if(session.visibilityState!=='visible'){visibility();return;}
   const seen=new Set();for(const src of session.inputSources){if(!['left','right'].includes(src.handedness)||!src.gripSpace)continue;const hand=src.handedness==='left'?0:1,pose=frame.getPose(src.gripSpace,space),aim=frame.getPose(src.targetRaySpace,space);if(!pose||pose.emulatedPosition){g.clearBlade(hand);continue;}seen.add(hand);const matrix=new T.Matrix4().fromArray(pose.transform.matrix);art.blade(hand,matrix,true);hands[hand]=src;
    const a=new T.Vector3(0,0,-.08).applyMatrix4(matrix),b=new T.Vector3(0,0,-.74).applyMatrix4(matrix);art.group.worldToLocal(a);art.group.worldToLocal(b);
    const buttonsState=(src.gamepad?.buttons||[]).map(b=>b.pressed),previous=priorButtons.get(src)||buttonsState;priorButtons.set(src,buttonsState);
    if((buttonsState[5]&&!previous[5])||(buttonsState[1]&&!previous[1])){g.phase==='playing'?g.pauseRun('Paused by controller'):g.phase==='paused'?g.resume():action(0);lastUI='';g.resetBlades();}
    if(g.phase==='playing'&&calibrated)g.blade(hand,{a:a.toArray(),b:b.toArray()},now);
    if(buttonsState[0]&&!previous[0]&&g.phase!=='playing'&&aim){origin.setFromMatrixPosition(new T.Matrix4().fromArray(aim.transform.matrix));controllerRay.set(0,0,-1).applyQuaternion(new T.Quaternion().setFromRotationMatrix(new T.Matrix4().fromArray(aim.transform.matrix)));ray.set(origin,controllerRay);panel.mesh.updateMatrixWorld(true);const hits=ray.intersectObjects(buttons,false);if(hits.length)action(hits[0].object.userData.action);}
   }
   for(const hand of[0,1])if(!seen.has(hand)){art.blade(hand,new T.Matrix4(),false);g.clearBlade(hand);}
   if(seen.size<2&&g.phase==='playing'){missingSince??=performance.now();if(performance.now()-missingSince>250){g.pauseRun('Both tracked controllers are required.');g.resetBlades();lastUI='';}}else missingSince=null;
   const local=art.group.worldToLocal(new T.Vector3(viewer.transform.position.x,viewer.transform.position.y,viewer.transform.position.z));if(g.phase==='playing'&&Math.hypot(local.x,local.z)>.55){g.pauseRun('You moved away from the play position. Recenter when clear.');lastUI='';}
   panel.mesh.visible=g.phase!=='playing';drawPanel();if(performance.now()-lastPaint>100){lastPaint=performance.now();const c=hud.context,w=hud.canvas.width,h=hud.canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#102c3dcc';c.fillRect(0,0,w,h);c.fillStyle='#cdeee0';c.font='600 30px system-ui';c.fillText(g.phase==='playing'?`${g.state.score.toLocaleString()}  /  ${g.state.combo} COMBO  /  ${Math.round(g.state.time)}s`:(g.message||'Choose a clear play space').slice(0,67),24,h/2+10);hud.texture.needsUpdate=true;}
  }
  function haptic(hand){try{hands[hand]?.gamepad?.hapticActuators?.[0]?.pulse(.2,35)?.catch?.(()=>{});}catch{}}
  return {tick,centerStage,haptic,get session(){return session},get calibrated(){return calibrated}};
 }
 root.PrismXR=Object.freeze({install});
})(globalThis);
