import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import * as T from '../vendor/three.module.js';import {GLTFLoader} from '../vendor/loaders/GLTFLoader.js';
import {cloneRig,makeActor} from '../aurora-rig.mjs';import {castBudget,makeRiftVeil,fabricMaterial,installAuroraAtmosphere} from '../aurora-shaders.mjs';import {installAuroraCast,castCandidates} from '../aurora-cast.mjs';
import {createState,saveState} from '../model.mjs';
const base=new URL('../art/characters/',import.meta.url),manifest=JSON.parse(fs.readFileSync(new URL('manifest.json',base))),assets=new Map();
for(const f of manifest.files){const bytes=fs.readFileSync(new URL(f.file,base));assert.equal(createHash('sha256').update(bytes).digest('hex'),f.sha256);assets.set(f.role,await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length),''));}
test('Every imported human is attributed, digest-checked, locally self-contained and under the asset budget',()=>{assert.equal(manifest.files.length,3);let total=0;for(const f of manifest.files){assert.equal(f.license,'CC0-1.0');assert.equal(f.creator,'Quaternius');assert.ok(f.triangles<9000);assert.equal(f.animations.length,10);total+=f.bytes;const b=fs.readFileSync(new URL(f.file,base)),j=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));assert.ok(j.skins.length>0);assert.equal(j.images,undefined);for(const x of j.buffers)assert.equal(x.uri,undefined);}assert.ok(total<3_600_000);});
test('Independent skinned clones share geometry but never skeletons or bone transforms',()=>{const g=assets.get('guard'),a=cloneRig(g.scene),b=cloneRig(g.scene);const mesh=root=>{let out;root.traverse(o=>{if(o.isSkinnedMesh&&!out)out=o;});return out;};assert.equal(mesh(a).geometry,mesh(b).geometry);assert.notEqual(mesh(a).skeleton,mesh(b).skeleton);assert.notEqual(mesh(a).skeleton.bones[0],mesh(b).skeleton.bones[0]);const skeletons=new Set();a.traverse(o=>{if(o.isSkinnedMesh)skeletons.add(o.skeleton);});assert.equal(skeletons.size,1);const before=b.getObjectByName('Head').quaternion.clone();a.getObjectByName('Head').rotation.x=.8;assert.ok(b.getObjectByName('Head').quaternion.equals(before));});
test('All three humans animate bones, have sane feet/head placement and keep actor state unchanged',()=>{for(const [role,g]of assets){const a=makeActor(g,role),actor={x:1,y:role==='guard'?1.05:0,z:2,heading:0,hp:100,walking:true},before=JSON.stringify(actor),joint=a.body.getObjectByName('Head');a.update(actor,.1,{time:1});a.root.updateMatrixWorld(true);const p=joint.getWorldPosition(new T.Vector3());a.update(actor,.12,{time:1.12});a.root.updateMatrixWorld(true);assert.ok(p.distanceTo(joint.getWorldPosition(new T.Vector3()))>.001,role);assert.ok(p.y>1.2&&p.y<2.2);assert.equal(JSON.stringify(actor),before);const geom=new T.Box3().setFromObject(a.root);assert.ok(geom.max.y<2.4);a.dispose();}});
test('Guard animation events select firing, hit and death without touching combat damage',()=>{const a=makeActor(assets.get('guard')),e={x:0,y:1.05,z:0,heading:0,hp:100};a.effect('shot');a.update(e,.05,{time:0});assert.equal(a.stats().clip,'Idle_Gun_Shoot');a.effect('hit');a.update(e,.05,{time:.1});assert.equal(a.stats().clip,'HitRecieve');e.hp=0;a.update(e,.05,{time:1});assert.equal(a.stats().clip,'Death');a.update(e,.05,{time:3});assert.equal(a.root.visible,false);assert.equal(e.hp,0);a.dispose();});
test('Light and XR retain human readability with hard smaller slot and effect limits',()=>{assert.equal(castBudget('prismatic',true).actors,3);assert.equal(castBudget('low').actors,5);assert.equal(castBudget('balanced').actors,10);for(const b of [castBudget('low'),castBudget('prismatic',true)])assert.equal(b.rifts||b.clothRim||b.clouds,false);});
test('Humanoid selection prioritizes companion, excludes dead/remote/nonhuman targets and stays bounded',()=>{const s=createState();s.drones=Array.from({length:100},(_,i)=>({id:String(i),humanoid:true,hp:i===1?0:80,x:i,y:1.05,z:0}));const chosen=castCandidates(s,castBudget('low'));assert.equal(chosen[0].id,'tavi');assert.ok(chosen.length<=5);assert.ok(!chosen.some(v=>v.id==='1'));});
test('Cast reuses slots and leaves game saves and progress unchanged over ordinary updates',async()=>{const s=createState(),scene=new T.Scene(),cast=installAuroraCast({scene,load:async role=>assets.get(role)});await cast.ready;s.drones=[{id:'qa',humanoid:true,x:2,y:1.05,z:0,hp:80,kind:'warden',walking:true}];const before=saveState(s);for(let i=0;i<120;i++)cast.update(s,1/60,{mode:'balanced'});const initial=cast.stats();assert.equal(initial.visible,2);assert.equal(initial.errors.length,0);assert.equal(saveState(s),before);for(let i=0;i<120;i++)cast.update(s,1/60,{mode:'low'});assert.equal(cast.stats().created,initial.created);cast.setOptions({characters:false});cast.update(s,0,{});assert.equal(scene.userData.auroraCovered.size,0);cast.setOptions({characters:true});cast.update(s,.1,{});assert.ok(scene.userData.auroraCovered.has('qa'));cast.dispose();assert.equal(scene.children.length,0);});
test('Failed assets leave all original bodies available rather than invisible enemies',async()=>{const scene=new T.Scene(),cast=installAuroraCast({scene,load:async()=>{throw Error('fixture unavailable');}});await cast.ready;cast.update(createState(),.1,{});assert.equal(cast.stats().errors.length,3);assert.equal(cast.stats().visible,0);assert.equal(scene.userData.auroraCovered.size,0);cast.dispose();});
test('Shader controls preserve uniforms, depth occlusion and reduced-motion clocks',()=>{const veil=makeRiftVeil();assert.equal(veil.depthWrite,false);assert.equal(veil.depthTest,true);assert.ok(veil.fragmentShader.includes('tonemapping_fragment'));const source=new T.MeshStandardMaterial({color:0x446677}),m=fabricMaterial(source),shader={uniforms:{},fragmentShader:'#include <opaque_fragment>'};m.onBeforeCompile(shader);assert.ok(shader.fragmentShader.includes('auroraRim'));assert.equal(source.onBeforeCompile.toString().includes('auroraRim'),false);const scene=new T.Scene(),sky=installAuroraAtmosphere({scene});sky.update(.1,{mode:'balanced'});assert.equal(sky.stats().cloudLayer,true);sky.update(.1,{reduced:true});assert.equal(sky.stats().clock,0);sky.update(.1,{xr:true});assert.equal(sky.stats().cloudLayer,false);sky.dispose();veil.dispose();m.dispose();source.dispose();});
