import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';
import {createState,readSave,saveState,step,interact,nearby,fire,groundAt,occupied,rescue,weaponStats,clearLine} from '../model.mjs';
import {BELL_TASK,BELL_POINTS,BELL_TARGETS,BELL_WAVES,bellGoal} from '../bellwether-world.mjs';
import {cleanBellwether,createBellwether} from '../bellwether-core.mjs';
import {installBellwetherScene} from '../bellwether-scene.mjs';
const dt=1/120;
// Unit fixtures isolate new encounters. Only browser journeys claim full-world play.
function fresh(){const s=createState();s.drones=[];s.p.invuln=9999;return s;}
function place(s,x,y,z){Object.assign(s.p,{x,y,z,vx:0,vy:0,vz:0,rail:null,climb:null,ride:null,grounded:true});}
function at(s,id){const q=BELL_POINTS.find(p=>p.id===id);place(s,q.x,q.y,q.z);assert.equal(nearby(s)?.id,id);return interact(s);}
function run(s,seconds){for(let t=0;t<seconds;t+=dt)step(s,{},dt);}
function killWave(s){let guard=0;const wave=s.bellwether.wave;
 while(s.drones.some(b=>b.bellwetherEnemy&&b.hp>0)&&guard++<1800){const b=s.drones.find(b=>b.bellwetherEnemy&&b.hp>0);const y=groundAt(b.x,b.z,b.y).y;place(s,b.x,y,b.z+2);s.p.yaw=0;s.p.pitch=Math.atan2(b.y+.32-(y+1.62),2);if(s.p.ammo===0)step(s,{reload:true},dt);else fire(s);step(s,{},dt);}
 assert.ok(guard<1800,'Actual weapon fire must defeat the wave');
}
function circuits(s){for(let i=0;i<3;i++)for(let n=0;n<BELL_TARGETS[i];n++)assert.ok(at(s,'bell-dial-'+i));assert.ok(at(s,'bell-test'));}
test('Old expedition saves keep checkpoint, kit and quests with neutral mission defaults',()=>{const s=createState({version:1,relays:['garden'],records:['quay-letter'],checkpoint:'academy',kit:{credits:720}});assert.equal(s.checkpoint,'academy');assert.equal(s.kit.credits,720);assert.deepEqual(s.bellwether,{stage:0,dials:[0,0,0],encounter:null,hold:0,gap:0,wave:0});assert.ok(s.relays.has('garden'));assert.equal(readSave(saveState(s)).bellwether.stage,0);});
test('Mission save values are bounded and cannot inject actors, health, coins or a pose',()=>{assert.deepEqual(cleanBellwether({stage:Infinity,dials:[-99,NaN,99],x:200,credits:10000,encounter:'roof'}),{stage:0,dials:[0,0,3]});const s=fresh();s.bellwether.stage=4;s.bellwether.encounter='roof';const r=createState(saveState(s));assert.equal(r.bellwether.encounter,null);assert.equal(r.bellwether.hold,0);assert.ok(!r.drones.some(e=>e.bellwetherEnemy));});
test('All mission interactions and wave spawns have clear supported floors',()=>{const s=fresh();for(const q of [...BELL_POINTS,...Object.values(BELL_WAVES).flat()]){assert.equal(groundAt(q.x,q.z,q.y+.2).y,q.y);assert.equal(occupied(q.x,q.y,q.z,s),false,JSON.stringify(q));}});
test('Remote mission activation is rejected, and existing trial activity blocks concurrent fights',()=>{const s=fresh(),core=createBellwether({emit(){},clearLine,groundAt,occupied,drop(){}});assert.equal(core.handle(s,'bell-dispatch'),false);place(s,-84,7,-4);s.skirmish.battle.phase='active';assert.equal(core.handle(s,'bell-dispatch'),false);assert.equal(s.bellwether.stage,0);});
test('An early roof visit and incorrect Arcade circuit cannot skip mission prerequisites',()=>{const s=fresh();place(s,-111,27.5,-6);assert.notEqual(nearby(s)?.id,'bell-signal');s.bellwether.stage=2;assert.equal(at(s,'bell-test'),false);assert.equal(s.bellwether.stage,2);for(const id of ['bell-dial-0','bell-dial-1'])assert.ok(at(s,id));assert.equal(at(s,'bell-test'),false);assert.equal(s.kit.credits,400);});
test('Whole mission uses weapon damage, three separate circuits, guard waves, a real hold and one report reward',()=>{const s=fresh();assert.ok(at(s,'bell-dispatch'));assert.equal(s.bellwether.stage,1);assert.equal(s.drones.filter(b=>b.bellwetherEnemy).length,2);killWave(s);run(s,.03);assert.equal(s.bellwether.stage,2);circuits(s);assert.equal(s.bellwether.stage,3);assert.deepEqual(createState(saveState(s)).bellwether.dials,[2,1,3]);assert.ok(at(s,'bell-signal'));killWave(s);run(s,2.1);assert.equal(s.bellwether.wave,1);assert.ok(s.drones.some(b=>b.bellwetherEnemy&&b.kind==='breacher'&&b.hp>0));killWave(s);place(s,-104,27.5,-6);run(s,7);assert.equal(s.bellwether.stage,4,'Waiting away from the receiver is not completion');place(s,-111,27.5,-6);run(s,6.1);assert.equal(s.bellwether.stage,5);assert.equal(s.kit.credits,400);assert.ok(at(s,'bell-dispatch'));assert.equal(s.bellwether.stage,6);assert.equal(s.kit.credits,700);at(s,'bell-dispatch');assert.equal(s.kit.credits,700);assert.ok(s.expedition.flags.includes(BELL_TASK.flag));assert.ok(!s.kit.dead.some(id=>id.startsWith('bell-blackout')));const r=createState(saveState(s));assert.equal(r.bellwether.stage,6);at(r,'bell-dispatch');assert.equal(r.kit.credits,700);});
test('Death and leaving the district interrupt combat without erasing the completed interior work',()=>{const s=fresh();at(s,'bell-dispatch');rescue(s,true);assert.equal(s.bellwether.stage,1);assert.equal(s.bellwether.encounter,null);assert.ok(!s.drones.some(b=>b.bellwetherEnemy));at(s,'bell-dispatch');killWave(s);run(s,.03);circuits(s);at(s,'bell-signal');place(s,-90,7,-6);run(s,.04);assert.equal(s.bellwether.stage,4);assert.equal(s.bellwether.encounter,null);assert.deepEqual(s.bellwether.dials,[2,1,3]);at(s,'bell-signal');assert.equal(s.drones.filter(b=>b.bellwetherEnemy).length,2);});
test('Journal destinations step through the actual workshop entrance, puzzle and service ladder',()=>{const s=fresh();s.bellwether.stage=2;place(s,-93,7,-18);assert.match(bellGoal(s).name,/entrance/);place(s,-103,7,-26);assert.equal(bellGoal(s).id,'bell-dial-0');s.bellwether.dials=[2,1,3];assert.equal(bellGoal(s).id,'bell-test');s.bellwether.stage=3;assert.equal(bellGoal(s).id,'roof-bell-ladder');s.p.y=27.5;assert.equal(bellGoal(s).id,'bell-signal');});
function drive(s,x,z){for(let i=0;i<7000;i++){const dx=x-s.p.x,dz=z-s.p.z,l=Math.hypot(dx,dz);if(l<.12)return;s.p.yaw=Math.atan2(dx,-dz);step(s,{moveZ:Math.min(1,l*2)},dt);}assert.fail('Blocked walking route '+JSON.stringify(s.p)+' to '+[x,z]);}
test('Continuous foot route joins the dispatch desk, Arcade rooms and the Theatre ladder',()=>{const s=fresh();place(s,-84,7,-4);for(const [x,z]of [[-92,-8],[-95,-18],[-103,-21],[-103,-25],[-106.5,-26],[-106.5,-30],[-103,-30],[-99.5,-30],[-99,-26],[-103,-25],[-103,-21],[-95,-18],[-95,0],[-107,.1]])drive(s,x,z);assert.equal(nearby(s)?.type,'ladder');interact(s);for(let i=0;i<4000&&s.p.climb;i++)step(s,{moveZ:1},dt);run(s,.5);assert.equal(s.p.y,27.5);drive(s,-111,-3);drive(s,-111,-6);assert.equal(s.stats.rescues,0);});
test('Mission art keeps fixed pools and saved state unchanged; completed market lights persist',()=>{const s=fresh(),scene=new T.Scene(),art=installBellwetherScene({scene,groundAt,clearLine});const count=()=>{let n=0;scene.traverse(()=>n++);return n;};const initial=count();const before=saveState(s);for(let i=0;i<50;i++)art.update(s);assert.equal(saveState(s),before);assert.equal(count(),initial);assert.equal(art.stats().restored,false);s.bellwether.stage=5;art.update(s);assert.equal(art.stats().restored,true);art.dispose();assert.equal(scene.children.length,0);});

import {CACHES} from '../arsenal.mjs';
test('New mission enemies do not emerge inside existing exploration supply caches',()=>{for(const enemy of Object.values(BELL_WAVES).flat())for(const cache of CACHES){if(Math.abs(enemy.y-cache.y)<1)assert.ok(Math.hypot(enemy.x-cache.x,enemy.z-cache.z)>1.4,JSON.stringify({enemy,cache}));}});

import {reloadWeapon} from '../model.mjs';
test('Reload completion clamps its timer to zero and allows another normal shot',()=>{const s=fresh();fire(s);assert.ok(reloadWeapon(s));run(s,2);assert.equal(s.p.reload,0);assert.ok(fire(s));});
