import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,step,occupied,saveState,groundAt,interact} from '../model.mjs';
import {BELL_ROUTES,BELL_SHORTCUT,BELL_DEMO,bellShortcutOpen,bellCircuitFeedback} from '../bellwether-layout.mjs';
const place=(s,[x,y,z])=>Object.assign(s.p,{x,y,z,vx:0,vy:0,vz:0,grounded:true});
function walk(s,points){for(const[x,y,z]of points){let i=0;for(;i<3600;i++){const dx=x-s.p.x,dz=z-s.p.z,d=Math.hypot(dx,dz);if(d<.15)break;s.p.yaw=Math.atan2(dx,-dz);step(s,{moveZ:Math.min(1,d*2),explorer:true},1/120);}assert(i<3600,`Blocked to ${x},${z}: ${JSON.stringify(s.p)}`);assert(Math.abs(s.p.y-y)<.4,`Wrong floor: ${s.p.y} != ${y}`);assert.equal(s.stats.rescues,0);}}
for(const route of BELL_ROUTES)test('Connected authored route uses ordinary movement: '+route.id,()=>{const s=createState();s.drones=[];s.bellwether.stage=3;place(s,route.points[0]);walk(s,route.points.slice(1));});
test('Upper gallery can be descended without a forced jump or purchased power',()=>{const s=createState();s.drones=[];s.bellwether.stage=3;const points=[...BELL_ROUTES.find(r=>r.id==='upper').points].reverse();place(s,points[0]);walk(s,points.slice(1));assert.deepEqual(s.kit.owns,['arc']);});
test('The circuit changes collision at the service shutter and old saved progress reopens it',()=>{const s=createState();const x=(BELL_SHORTCUT.x1+BELL_SHORTCUT.x2)/2;assert(occupied(x,7,-28,s));s.bellwether.stage=3;assert(bellShortcutOpen(s));assert(!occupied(x,7,-28,s));const resumed=createState(saveState(s));assert.equal(resumed.bellwether.stage,3);assert(!occupied(x,7,-28,resumed));});
test('The first broken circuit link is observable without discarding the maintenance aid',()=>{const s=createState();assert.equal(bellCircuitFeedback(s).firstFault,0);s.bellwether.dials=[2,0,0];assert.equal(bellCircuitFeedback(s).firstFault,1);s.bellwether.dials=[2,1,0];assert.equal(bellCircuitFeedback(s).firstFault,2);s.bellwether.dials=[2,1,3];assert(bellCircuitFeedback(s).stable);assert(!bellShortcutOpen(s));});
test('Repeatable induction bench needs no purchase and cannot award mission progress or credits',()=>{const s=createState();place(s,[BELL_DEMO.x,7,BELL_DEMO.z+1]);s.drones=[];const credits=s.kit.credits;assert(interact(s));assert(s.bellwether.demoUntil>s.time);assert(interact(s));assert.equal(s.kit.credits,credits);assert.equal(s.bellwether.stage,0);assert.equal(createState(saveState(s)).bellwether.demoUntil,undefined);assert(Number.isFinite(groundAt(BELL_DEMO.x,BELL_DEMO.z).y));});
