import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import * as T from '../vendor/three.module.js';import {GLTFLoader} from '../vendor/loaders/GLTFLoader.js';
import {cloneRig,prepareRig,disposeInstance,disposeRig} from '../cast-rig.mjs';import {installCast,actorRole,actorPose} from '../cast-scene.mjs';
import {createState,saveState} from '../model.mjs';
const root=new URL('../art/characters/',import.meta.url),manifest=JSON.parse(fs.readFileSync(new URL('manifest.json',root)));
async function load(role){const bytes=fs.readFileSync(new URL(role+'.glb',root));return new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');}
function enemy(id,x=2){return {id,x,y:1.05,z:-3,hp:80,humanoid:true,kind:'warden',heading:0,walking:true,stun:0,attack:2,awareness:1};}
function state(){const s=createState();s.drones=[enemy('one'),enemy('two',-2)];return s;}
test('All character files have creator provenance, pinned CC0 licenses and exact public hashes',()=>{assert.equal(manifest.license,'CC0-1.0');assert.ok(manifest.totalBytes<4_000_000);for(const f of manifest.files){assert.ok(!f.file.includes('/'));const data=fs.readFileSync(new URL(f.file,root));assert.equal(data.length,f.bytes);assert.equal(createHash('sha256').update(data).digest('hex'),f.sha256);}for(const s of manifest.sources)assert.ok(s.creator==='Quaternius'&&s.license==='CC0-1.0'&&s.url.startsWith('https://quaternius.com/'));for(const name of ['men','women'])assert.match(fs.readFileSync(new URL(name+'-license.txt',root),'utf8'),/CC0 1.0 Universal/);});
test('Shipped humans are self-contained skinned GLBs with ten actual source clips',()=>{for(const f of manifest.files.filter(f=>f.file.endsWith('.glb'))){const data=fs.readFileSync(new URL(f.file,root));assert.equal(data.readUInt32LE(0),0x46546c67);assert.equal(data.readUInt32LE(8),data.length);const j=JSON.parse(data.subarray(20,20+data.readUInt32LE(12)));assert.equal(j.animations.length,10);assert.ok(j.skins[0].joints.length>=50);assert.ok(j.buffers.every(b=>!b.uri));assert.ok(!j.images?.some(i=>i.uri));assert.ok(j.meshes.length>=4);assert.ok(f.triangles<9000);}});
test('Each cloned human has independent bones but shares read-only mesh resources',async()=>{const rig=prepareRig(await load('guard')),a=cloneRig(rig.source),b=cloneRig(rig.source);const ma=a.getObjectByProperty('isSkinnedMesh',true),mb=b.getObjectByProperty('isSkinnedMesh',true);assert.notEqual(ma.skeleton,mb.skeleton);assert.notEqual(ma.skeleton.bones[0],mb.skeleton.bones[0]);assert.equal(ma.geometry,mb.geometry);assert.equal(ma.material,mb.material);const old=b.getObjectByName('WristR').quaternion.clone(),mix=new T.AnimationMixer(a);mix.clipAction(rig.clips.find(c=>c.name==='Walk')).play();mix.update(.45);assert.ok(old.equals(b.getObjectByName('WristR').quaternion));assert.ok(!a.getObjectByName('WristR').quaternion.equals(old));disposeInstance(a);disposeInstance(b);disposeRig(rig);});
test('Model actors follow game foot positions, forward aim and animation without editing the save',async()=>{const scene=new T.Scene(),cast=installCast({scene,load}),s=state();await cast.ready;const before=saveState(s);cast.update(s,.02);const info=cast.stats();assert.equal(info.status.guard,'ready');assert.ok(info.actors.some(a=>a.id==='one'&&a.pose==='Run_Shoot'));assert.ok(scene.userData.castHas('one'));const wrapper=scene.getObjectByName('Cast / one');assert.equal(wrapper.position.y,0);const forward=new T.Vector3(0,0,1).applyEuler(wrapper.rotation);assert.ok(forward.dot(new T.Vector3(0,0,-1))>.999);const wrist=wrapper.getObjectByName('WristR'),q=wrist.quaternion.clone();cast.update(s,.07);assert.ok(!wrist.quaternion.equals(q));assert.equal(saveState(s),before);cast.dispose();assert.equal(scene.children.length,0);});
test('Animated cast budgets are bounded and lower-cost or failed loads preserve fallback ownership',async()=>{const scene=new T.Scene(),cast=installCast({scene,load}),s=state();await cast.ready;s.drones=Array.from({length:28},(_,i)=>enemy('test-'+i,(i%7)-3));for(let i=0;i<50;i++)cast.update(s,.016);assert.ok(cast.stats().allocated<=12);assert.equal(cast.stats().active,12);cast.update(s,.016,{mode:'low'});assert.equal(cast.stats().active,6);cast.update(s,.016,{xr:true});assert.equal(cast.stats().active,4);cast.setEnabled(false);assert.equal(cast.stats().active,0);assert.ok(!scene.userData.castHas('test-0'));cast.dispose();const failed=installCast({scene,load:async()=>{throw Error('missing fixture')}});await failed.ready;failed.update(s,.01);assert.equal(failed.stats().active,0);assert.equal(failed.stats().errors.length,3);assert.equal(scene.userData.castHas('test-0'),false);failed.dispose();});
test('Hit, shooting and short death animations follow events and expired corpses return pool slots',async()=>{const scene=new T.Scene(),cast=installCast({scene,load}),s=state();await cast.ready;s.drones[0].walking=false;cast.update(s,.02);s.drones[0].hp-=5;s.time+=.02;cast.update(s,.02);assert.equal(cast.stats().actors.find(a=>a.id==='one').pose,'HitRecieve');s.time+=.5;s.drones[0].attack=4;cast.update(s,.02);assert.equal(cast.stats().actors.find(a=>a.id==='one').pose,'Gun_Shoot');s.drones[0].hp=0;cast.update(s,.02);assert.equal(cast.stats().actors.find(a=>a.id==='one').pose,'Death');s.time+=2;cast.update(s,.02);assert.ok(!scene.userData.castHas('one'));assert.ok(cast.stats().allocated<=12);cast.dispose();});
test('Role and pose selection preserve friendly versus armed behavior',()=>{assert.equal(actorRole({id:'tavi'}),'courier');assert.equal(actorRole({id:'surveyor'}),'officer');assert.equal(actorPose({id:'tavi',offer:true}),'Wave');assert.equal(actorPose({id:'surveyor',walking:true}),'Walk');assert.equal(actorPose({id:'hostile',walking:false}),'Idle_Gun_Pointing');});
