import {test} from 'node:test';import assert from 'node:assert/strict';
import {createState,saveState,readSave,step,buy,equip,depotNear,loot,collect,fire,pulse,rescue,WEAPONS,CACHES,DEPOTS,RAILS,pointOnRail,interact,jump,railTarget,weaponStats} from '../model.mjs';
import {cleanKit} from '../arsenal.mjs';
const dt=1/120,run=(s,t,input={})=>{for(let i=0;i<t/dt;i++)step(s,{explorer:true,...input},dt);};
function buyer(){const s=createState();Object.assign(s.p,{x:3,y:0,z:7});return s;}
function scopedTarget(){const s=buyer();assert.ok(buy(s,'sniper'));const b=s.drones.find(b=>b.id==='range');Object.assign(s.p,{x:b.x,y:b.y-1.6,z:b.z+8,yaw:0,pitch:0,scoped:true});return s;}
test('Four mechanically distinct weapons: rate, spread, magazine, range and zoom',()=>{assert.equal(Object.keys(WEAPONS).length,4);assert.equal(WEAPONS.sniper.zoom,4);assert.ok(WEAPONS.sniper.range>WEAPONS.carbine.range);assert.ok(WEAPONS.sniper.delay>WEAPONS.carbine.delay*8);assert.equal(WEAPONS.scatter.pellets,6);});
test('Buying is proximity checked, atomic, earned-credit-only and persists the selected weapon',()=>{const s=createState();s.p.x=80;const before=saveState(s);assert.equal(buy(s,'sniper'),false);assert.equal(saveState(s),before);Object.assign(s.p,DEPOTS[0]);assert.ok(buy(s,'sniper'));assert.equal(s.kit.credits,100);assert.equal(s.p.weapon,'sniper');assert.equal(s.p.ammo,4);assert.equal(buy(s,'sniper'),false);assert.equal(buy(s,'carbine'),false);assert.equal(s.kit.credits,100);});
test('Damage/reload and shield purchases have real effects and capped levels',()=>{const s=buyer();assert.ok(buy(s,'arc','damage'));assert.ok(weaponStats(s).damage>34);assert.ok(buy(s,'arc','reload'));assert.ok(weaponStats(s).reload<1.05);s.kit.credits=2000;assert.ok(buy(s,'shield','shield'));assert.equal(s.p.shield,80);assert.ok(buy(s,'shield','shield'));assert.equal(buy(s,'shield','shield'),false);assert.equal(s.kit.shield,2);});
test('Scoped sniper ray deals its defined damage; a moving target is not auto-hit',()=>{const s=scopedTarget(),b=s.drones.find(b=>b.id==='range');assert.ok(fire(s));assert.ok(b.hp<=0);assert.equal(s.p.ammo,3);assert.equal(s.stats.defeated,1);assert.ok(s.kit.dead.includes('range'));assert.equal(fire(s),false);});
test('Defeat produces a collectible drop, and a repeated collection never mints credits',()=>{const s=scopedTarget();fire(s);const d=loot(s).find(d=>d.id==='drop-range');assert.ok(d);const money=s.kit.credits;assert.equal(collect(s,d.id),false);Object.assign(s.p,{x:d.x,y:d.y,z:d.z});assert.ok(collect(s,d.id));assert.equal(s.kit.credits,money+d.credits);assert.equal(collect(s,d.id),false);const restored=createState(saveState(s));assert.ok(!loot(restored).some(d=>d.id==='drop-range'));assert.equal(restored.drones.find(b=>b.id==='range').hp,0);});
test('Rare world crates unlock a specific weapon and do not reroll on reload',()=>{const s=createState(),box=CACHES.find(c=>c.weapon==='scatter');Object.assign(s.p,box);assert.ok(collect(s,box.id));assert.ok(s.kit.owns.includes('scatter'));const before=s.kit.credits,r=createState(saveState(s));Object.assign(r.p,box);assert.equal(collect(r,box.id),false);assert.equal(r.kit.credits,before);});
test('Finite magazines do not gain ammunition by switching or canceling reload',()=>{const s=buyer();buy(s,'sniper');s.p.ammo=1;step(s,{reload:true},dt);assert.ok(s.p.reload>0);equip(s,'arc');run(s,3);equip(s,'sniper');assert.equal(s.p.ammo,1);const supply=s.kit.reserve.sniper;run(s,2.5,{reload:true});assert.equal(s.p.ammo,4);assert.equal(s.kit.reserve.sniper,supply-3);s.p.ammo=0;s.kit.reserve.sniper=0;run(s,3,{reload:true});assert.equal(s.p.ammo,0);rescue(s);assert.equal(s.p.ammo,0);});
test('Malformed economic saves are bounded, unknown equipment is rejected and old saves migrate',()=>{const c=cleanKit({credits:-4,owns:['sniper','__proto__','arc'],reserve:{sniper:Infinity},tune:{sniper:{damage:999,reload:-2}},dead:['not-real'],taken:['drop-not-real']});assert.equal(c.credits,0);assert.equal(c.tune.sniper.damage,2);assert.equal(c.tune.sniper.reload,0);assert.deepEqual(c.owns,['arc','sniper']);assert.deepEqual(c.dead,[]);assert.equal(createState({version:1,relays:['garden'],checkpoint:'garden'}).kit.credits,400);});
test('Two new detours preserve the five original rail IDs and valid geometric endpoints',()=>{assert.equal(RAILS.length,7);for(const id of['glassline','copperline','sunline','crossline','homeline','gale-loop','spire-fork'])assert.ok(RAILS.some(r=>r.id===id));});
test('Free-look is the simulation default, and sight alignment is independent of travel direction',()=>{const s=createState();Object.assign(s.p,{x:9,y:0,z:-5,yaw:1.25,pitch:.3});interact(s);run(s,1);const yaw=s.p.yaw;s.p.yaw+=1;run(s,.5);assert.equal(s.p.yaw,yaw+1);assert.equal(s.p.pitch,.3);assert.ok(s.p.rail);});
for(const [from,to,times] of [['glassline','gale-loop',[.8,1.1,1.4,1.7,2]],['gale-loop','glassline',[.8,1.1,1.4,1.7,2]],['sunline','spire-fork',[2,2.3,2.6,2.9,3.2]],['spire-fork','sunline',[2.3,2.6,2.9,3.2,3.35]]])test(from+' has five road-origin carried-state jump/catch opportunities to '+to,()=>{
 for(const time of times){const a=RAILS.find(r=>r.id===from),b=RAILS.find(r=>r.id===to),s=createState(),start=pointOnRail(a,0);Object.assign(s.p,{x:start.x,y:start.y-3.1,z:start.z});for(let i=0;i<3&&!s.p.rail;i++)interact(s);assert.equal(s.p.rail?.id,from);run(s,time,{forward:true});const head={x:s.p.x,y:s.p.y+1.6,z:s.p.z};const p=[...b.pts].sort((a,b)=>Math.hypot(a.x-head.x,a.y-head.y,a.z-head.z)-Math.hypot(b.x-head.x,b.y-head.y,b.z-head.z))[0];s.p.yaw=Math.atan2(p.x-head.x,-(p.z-head.z));s.p.pitch=Math.atan2(p.y-head.y,Math.hypot(p.x-head.x,p.z-head.z));const old=[s.p.x,s.p.y,s.p.z];jump(s);assert.deepEqual([s.p.x,s.p.y,s.p.z],old);let success=false;for(let i=0;i<60;i++){step(s,{explorer:true},dt);const target=railTarget(s);if(target?.rail.id===to&&s.p.hookCooldown===0){const at=[s.p.x,s.p.y,s.p.z];assert.ok(interact(s));assert.deepEqual([s.p.x,s.p.y,s.p.z],at);success=true;break;}}assert.ok(success);run(s,1,{forward:true});assert.equal(s.p.rail?.id,to);assert.equal(s.stats.transfers,1);assert.equal(s.stats.rescues,0);}
});
test('Enemies differ in health, silhouette type and attack cadence; target does not fire',()=>{const s=createState();assert.equal(new Set(s.drones.map(b=>b.kind)).size,4);const heavy=s.drones.find(b=>b.kind==='heavy'),scout=s.drones.find(b=>b.kind==='scout');assert.ok(heavy.hp>scout.hp*2);Object.assign(s.p,{x:14,y:0,z:0});run(s,3);assert.equal(s.bullets.length,0);});

test('An early deliberate catch survives the release cooldown; there is no unsolicited magnetic catch',()=>{
 function launch(){const s=createState();Object.assign(s.p,{x:9,y:0,z:-5});interact(s);run(s,1.2,{forward:true});const r=RAILS.find(r=>r.id==='gale-loop'),p=[...r.pts].sort((a,b)=>Math.hypot(a.x-s.p.x,a.y-s.p.y-1.6,a.z-s.p.z)-Math.hypot(b.x-s.p.x,b.y-s.p.y-1.6,b.z-s.p.z))[0];s.p.yaw=Math.atan2(p.x-s.p.x,-(p.z-s.p.z));s.p.pitch=Math.atan2(p.y-s.p.y-1.6,Math.hypot(p.x-s.p.x,p.z-s.p.z));jump(s);return s;}
 const s=launch(),before=[s.p.x,s.p.y,s.p.z];assert.ok(s.p.hookCooldown>0);assert.ok(interact(s));assert.deepEqual([s.p.x,s.p.y,s.p.z],before);assert.equal(s.p.rail,null);run(s,.22,{forward:true});assert.equal(s.p.rail?.id,'gale-loop');assert.equal(s.stats.transfers,1);
 const untouched=launch();run(untouched,.3,{forward:true});assert.equal(untouched.p.rail,null);assert.equal(untouched.stats.transfers,0);
});
test('An expired catch request cannot attach later or survive rescue',()=>{const s=createState();Object.assign(s.p,{x:110,y:30,z:110,grounded:false,lastRail:'glassline',airSince:s.time,hookCooldown:.14});interact(s);assert.equal(s.p.hookRequest,.3);run(s,.4);assert.equal(s.p.hookRequest,0);assert.equal(s.p.rail,null);rescue(s);assert.equal(s.p.hookRequest,0);assert.equal(s.p.lastRail,null);});
test('Incoming rail momentum above cruise speed decays instead of being clipped at the next frame',()=>{const s=createState();Object.assign(s.p,{x:9,y:0,z:-5});interact(s);s.p.speed=25;step(s,{},dt);assert.ok(s.p.speed>24.9&&s.p.speed<25);run(s,.5);assert.ok(s.p.speed>23);});

test('The broadened Gale transfer shelf accepts 21 recorded-direction release/delay combinations',()=>{
 for(const at of[38,41,43.90416666666655,46,49,52,55])for(const delay of[.16,.23,.30]){const s=createState();Object.assign(s.p,{x:9,y:0,z:-5});interact(s);while(s.p.rail.s<at)step(s,{explorer:true},dt);s.p.yaw=2.1729166666666697;s.p.pitch=0;jump(s);run(s,delay);interact(s);run(s,1);assert.equal(s.p.rail?.id,'gale-loop',`arc length ${at}, delay ${delay}`);assert.equal(s.stats.transfers,1);assert.equal(s.stats.rescues,0);}
});
