/* Real r177 object/model fixtures, not a gameplay journey or physical-device QA. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import * as T from '../vendor/three.module.js';
import {createCurrentworks} from '../currentworks-view.mjs';
import {CURRENTWORKS_TREES,CURRENTWORKS_CLOUDS,CURRENTWORKS_CLOUD_SCALE,currentworksQuality} from '../currentworks-layout.mjs';
import {createState,saveState,DISTRICTS,BRIDGES,RAILS} from '../model.mjs';import {PATCHES} from '../tactics-core.mjs';import {PortalMaterials} from '../portal-aperture.mjs';
function fixture(){const scene=new T.Scene(),foliageFallback=new T.Group();scene.add(foliageFallback);const patches=new Map(PATCHES.map(p=>{const mesh=new T.Mesh(new T.CircleGeometry(p.r,12),new T.MeshBasicMaterial());scene.add(mesh);return [p.id,{p,mesh}];}));return {scene,foliageFallback,patches,...createCurrentworks({scene,patches,foliageFallback})};}
const compiler={compileAsync:async()=>{}};
function freeze(o){if(o&&typeof o==='object'&&!Object.isFrozen(o)){Object.freeze(o);for(const v of Object.values(o))freeze(v);}return o;}
test('Currentworks snapshots have exact upstream hashes without a second engine',()=>{const m=JSON.parse(fs.readFileSync(new URL('../vendor/currentworks/UPSTREAM.json',import.meta.url)));for(const [name,v]of Object.entries(m.files)){const raw=fs.readFileSync(new URL('../vendor/currentworks/'+name,import.meta.url));assert.equal(createHash('sha256').update(raw).digest('hex'),v.sha256,name);}assert.equal(T.REVISION,'177');});
test('New foliage occupies the original twelve Bellwether/Garden planter centers',()=>{assert.equal(CURRENTWORKS_TREES.length,12);for(const d of DISTRICTS.filter(d=>['bellmarket','garden'].includes(d.id)))for(let i=0;i<6;i++){const p=CURRENTWORKS_TREES.find(t=>t.id===d.id+'-planter-'+i).position;assert.deepEqual(p,[d.x+(i%2?1:-1)*d.w*.4,d.y+.55,d.z+(i/6-.5)*d.d*.65]);}});
test('Six mesh-cloud formations are authored, bounded and below nearby streets',()=>{assert.equal(CURRENTWORKS_CLOUDS.length,6);for(const cloud of CURRENTWORKS_CLOUDS){const [x,y,z]=cloud.position.map(v=>v*CURRENTWORKS_CLOUD_SCALE);assert(y<=16);assert(cloud.radius<=2.5);for(const d of DISTRICTS){if(Math.abs(x-d.x)<=d.w/2&&Math.abs(z-d.z)<=d.d/2)assert(y+cloud.radius*6<d.y,cloud.id+' street');}}});
test('Original water discs, oil patches and foliage remain until preparation succeeds',async()=>{const f=fixture();f.update(createState());assert(f.foliageFallback.visible);assert([...f.patches.values()].every(v=>v.mesh.visible));await f.prepare(compiler,new T.PerspectiveCamera());f.update(createState());assert(f.stats().ready);assert.equal(f.stats().water.length,PATCHES.filter(p=>p.type==='water').length);assert(!f.foliageFallback.visible);for(const {p,mesh}of f.patches.values())if(p.type==='oil')assert(mesh.visible);f.dispose();});
test('Renderer preparation failure restores old decoration and never rejects startup',async()=>{const f=fixture();await f.prepare({compileAsync:async()=>{throw Error('fixture compiler failure');}},new T.PerspectiveCamera());f.update(createState());assert(!f.stats().ready);assert.equal(f.stats().error,'fixture compiler failure');assert(f.foliageFallback.visible);assert([...f.patches.values()].every(v=>v.mesh.visible));f.dispose();});
test('Graphics updates read frozen gameplay and never change version-1 saves',async()=>{const f=fixture(),s=createState(),before=saveState(s),raw=JSON.stringify(s);freeze(s);await f.prepare(compiler,new T.PerspectiveCamera());for(let i=0;i<30;i++)f.update(s,{xr:i%2===0,reduced:i%3===0,mode:'prismatic'});assert.equal(JSON.stringify(s),raw);assert.equal(f.stats().time,s.time);assert.equal(before,saveState(createState(before)));f.dispose();});
test('Pause freezes module clocks, quiet mode freezes wind and XR caps geometry',async()=>{const f=fixture(),s=createState();await f.prepare(compiler,new T.PerspectiveCamera());s.time=12.5;f.update(s,{mode:'prismatic'});const root=f.scene.getObjectByName('Aether Currentworks environment'),pos=()=>{const a=[];root.traverse(o=>a.push(o.position.toArray()));return JSON.stringify(a);};const before=pos();f.update(s,{mode:'prismatic'});assert.equal(pos(),before);f.update(s,{xr:true,reduced:true,mode:'prismatic'});assert.equal(f.stats().trees.time,12.5);assert(f.stats().trees.quiet);assert(f.stats().clouds.quiet);assert.equal(f.stats().trees.lod[0],0);assert(f.stats().clouds.levels.every(l=>l===2));assert(f.stats().water.every(w=>w.quality==='light'));assert.equal(currentworksQuality('prismatic',true).water,'light');f.dispose();});
test('Charging retains the model hazard cue and water has a circular shader mask',async()=>{const f=fixture(),s=createState();await f.prepare(compiler,new T.PerspectiveCamera());const p=PATCHES.find(p=>p.type==='water');s.p={...s.p,x:p.x,y:p.y,z:p.z};s.tactics.hazards[p.id]=2;f.update(s);const mesh=f.scene.getObjectByName('Currentworks / '+p.id);assert.equal(mesh.material.uniforms.aetherWaterCharge.value,1);assert.equal(mesh.material.uniforms.aetherWaterRadius.value,p.r);assert(mesh.material.fragmentShader.includes('if(length(vLocal.xz)>aetherWaterRadius)discard;'));assert.equal(mesh.scale.y,.2);assert(!f.patches.get(p.id).mesh.visible);s.tactics.hazards[p.id]=0;f.update(s);assert.equal(mesh.material.uniforms.aetherWaterCharge.value,0);f.dispose();});
test('Only real eligible impact events add splashes, not decorative update calls',async()=>{const f=fixture(),s=createState();await f.prepare(compiler,new T.PerspectiveCamera());const p=PATCHES.find(p=>p.type==='water');s.p={...s.p,x:p.x,y:p.y,z:p.z};f.update(s);const before=f.stats().water[0].emitted;f.effect({type:'ui'});f.update(s);assert.equal(f.stats().water[0].emitted,before);f.effect({type:'tactical-cast',end:{x:p.x,y:p.y+.06,z:p.z}});assert(f.stats().water.find(w=>w.id===p.id).emitted>before);f.dispose();});
test('Toggling only decoration restores old surfaces and does not alter lights or camera',async()=>{const f=fixture(),s=createState(),camera=new T.PerspectiveCamera();f.scene.add(camera);await f.prepare(compiler,camera);f.update(s);f.setEnabled(false);assert(!f.stats().active);assert(f.foliageFallback.visible);assert.equal(camera.parent,f.scene);assert([...f.patches.values()].every(v=>v.mesh.visible));f.setEnabled(true);f.update(s);assert(f.stats().active);assert(!f.foliageFallback.visible);f.dispose();});
test('Portal collects all custom water, standard tree and toon cloud materials',async()=>{const f=fixture();await f.prepare(compiler,new T.PerspectiveCamera());f.update(createState());const portal=new PortalMaterials();portal.active=true;portal.collect(f.scene);const root=f.scene.getObjectByName('Aether Currentworks environment');let count=0;root.traverse(o=>{if(o.isMesh){assert(portal.entries.has(o.material));count++;}});assert(count>50);f.dispose();});
test('Repeated disposal frees owned geometry, leaves original game decorations intact',async()=>{const f=fixture();await f.prepare(compiler,new T.PerspectiveCamera());f.update(createState());f.dispose();f.dispose();assert(!f.scene.getObjectByName('Aether Currentworks environment'));assert(f.foliageFallback.visible);assert(f.stats().disposed);assert.equal(f.stats().trees.geometries,0);assert.equal(f.stats().clouds.geometryCount,0);assert(f.stats().water.every(w=>w.geometries===0&&w.textures===0));assert([...f.patches.values()].every(v=>v.mesh.parent===f.scene));});
