import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createState,step,interact,nearby,fire,saveState,readSave,groundAt,occupied,RAILS,pointOnRail,jump,clearLine,rescue} from '../model.mjs';
import {EXP_DISTRICTS,EXP_BRIDGES,EXP_RAILS,EXP_ENEMIES,TASKS,THINGS,POSTS,TRANSIT,TERRACES,BALCONY_RAILS,transitPosition,bridgeBarrier} from '../expedition-world.mjs';
import {cleanExpedition,expeditionSnapshot} from '../expedition-core.mjs';
const dt=1/120;
const tick=(s,seconds,input={})=>{for(let i=0;i<seconds/dt;i++)step(s,{explorer:true,...input},dt);};
const fresh=()=>{const s=createState();for(const b of s.drones)b.hp=0;return s;};
const pose=(s,t)=>Object.assign(s.p,{x:t.x,y:t.y+.005,z:t.z,vx:0,vy:0,vz:0,rail:null,ride:null,grounded:true,invuln:1000});
const at=(s,id)=>{const t=THINGS.find(t=>t.id===id);assert.ok(t,id);pose(s,t);const n=nearby(s);assert.equal(n?.id,id,JSON.stringify(n));assert.ok(interact(s));};
const walk=(s,x,z,max=15000)=>{let i=0;for(;i<max&&Math.hypot(s.p.x-x,s.p.z-z)>.12;i++){s.p.yaw=Math.atan2(x-s.p.x,-(z-s.p.z));step(s,{forward:true,explorer:true},dt);}assert.ok(i<max,`Blocked at ${s.p.x},${s.p.y},${s.p.z} toward ${x},${z}`);};
// These are deterministic model fixtures. Native-input HTTP/WebGL evidence is
// produced separately by expedition-browser.py without actor or mission writes.
test('Expansion uses unique original IDs and preserves the original five districts',()=>{assert.equal(EXP_DISTRICTS.length,7);assert.equal(TASKS.length,13);for(const a of[EXP_DISTRICTS,EXP_BRIDGES,EXP_RAILS,EXP_ENEMIES,TASKS,THINGS,TRANSIT])assert.equal(new Set(a.map(x=>x.id)).size,a.length);assert.equal(RAILS.length,15);});
for(const b of EXP_BRIDGES)test(b.id+' is physically walkable in both directions',()=>{for(const [a,end]of[[b.a,b.b],[b.b,b.a]]){const s=fresh();pose(s,{x:a[0],y:a[1],z:a[2]});walk(s,end[0],end[2]);assert.equal(s.stats.rescues,0);assert.ok(Math.abs(s.p.y-end[1])<.15,`${b.id}: ${s.p.y} != ${end[1]}`);}});
test('Handrails collide along diagonal stairs without closing the walking lane',()=>{for(const b of EXP_BRIDGES){const x=(b.a[0]+b.b[0])/2,y=(b.a[1]+b.b[1])/2,z=(b.a[2]+b.b[2])/2,dx=b.b[0]-b.a[0],dz=b.b[2]-b.a[2],l=Math.hypot(dx,dz);assert.equal(bridgeBarrier([b],x,y,z),false);for(const sign of[-1,1])assert.equal(bridgeBarrier([b],x-dz/l*(b.width/2+.1)*sign,y,z+dx/l*(b.width/2+.1)*sign),true);assert.equal(bridgeBarrier([b],x-dz/l*(b.width/2+.1),y+1.3,z+dx/l*(b.width/2+.1)),false);}});
test('Upper-gallery railings have physical stair openings and upper floors',()=>{assert.equal(TERRACES.length,11);assert.ok(BALCONY_RAILS.length>=12);for(const t of TERRACES)assert.equal(groundAt(t.x,t.z,t.y+.1).y,t.y);for(const q of BALCONY_RAILS)assert.ok(occupied((q.a[0]+q.b[0])/2,q.a[1],(q.a[2]+q.b[2])/2));});
test('Original saves migrate and expedition values are bounded and deduplicated',()=>{const old=createState({version:1,relays:['garden'],checkpoint:'garden',records:['quay-letter']});assert.deepEqual([...old.relays],['garden']);assert.deepEqual(old.expedition.flags,[]);const e=cleanExpedition({flags:['regulator','regulator','godmode'],valves:[99,-9,'x'],visited:['bellmarket','outside'],routes:['ferry','ferry','instant'],tracked:'bad'});assert.deepEqual(e.flags,['regulator']);assert.deepEqual(e.valves,[3,0,0]);assert.deepEqual(e.routes,['ferry']);assert.equal(e.tracked,'dispatch');assert.equal(createState(saveState(old)).checkpoint,'garden');});
test('Dispatch rewards are actual nearby interactions and cannot be farmed',()=>{const s=fresh(),credits=s.kit.credits;assert.equal(interact(s),false);at(s,'dispatch-board');assert.ok(s.expedition.flags.includes('dispatch-started'));assert.equal(s.kit.credits,credits);at(s,'market-board');assert.equal(s.kit.credits,credits+60);for(let i=0;i<5;i++)at(s,'market-board');assert.equal(s.kit.credits,credits+60);});
test('Ferry repair needs a regulator and survives save reload',()=>{const s=fresh();at(s,'ferry-engine');assert.ok(!s.expedition.flags.includes('ferry-online'));at(s,'regulator');at(s,'ferry-engine');assert.ok(s.expedition.flags.includes('ferry-online'));assert.equal(s.kit.credits,500);at(s,'ferry-engine');assert.equal(s.kit.credits,500);assert.ok(createState(saveState(s)).expedition.flags.includes('ferry-online'));});
test('Archive doors block bodies and bullets until all three charter leaves are delivered',()=>{const s=fresh(),a={x:-95,y:31.4,z:-162},b={x:-95,y:31.4,z:-171};assert.ok(occupied(-95,30,-165,s));assert.equal(clearLine(a,b,s),false);at(s,'archive-lock');assert.equal(s.expedition.flags.includes('archive-open'),false);for(const id of['charter-market','charter-academy','charter-dawn'])at(s,id);at(s,'archive-lock');assert.equal(occupied(-95,30,-165,s),false);assert.equal(clearLine(a,b,s),true);pose(s,{x:-95,y:30,z:-162});walk(s,-95,-172);assert.equal(s.stats.rescues,0);at(s,'charter-original');assert.ok(s.expedition.flags.includes('charter'));const credits=s.kit.credits;pose(s,{x:-95,y:30,z:-162});walk(s,-95,-169);assert.equal(s.kit.credits,credits);});
test('The weather lock is a three-dial puzzle, not a click-to-complete reward',()=>{const s=fresh();at(s,'weather-console');assert.equal(s.expedition.flags.includes('weather-open'),false);for(const [i,n]of[1,3,2].entries())for(let j=0;j<n;j++)at(s,'valve-'+i);assert.deepEqual(s.expedition.valves,[1,3,2]);at(s,'weather-console');assert.ok(s.expedition.flags.includes('weather-open'));assert.equal(occupied(116,26,-159,s),false);pose(s,{x:116,y:26,z:-155});walk(s,116,-165);assert.equal(s.stats.rescues,0);});
for(const r of TRANSIT)test(r.id+' transports the actual player continuously, with call and return service',()=>{const s=fresh();if(r.requires)s.expedition.flags.push(r.requires);pose(s,r.b);assert.equal(nearby(s)?.type,'exp-transit');interact(s);assert.equal(s.p.ride,null);tick(s,r.seconds+.5);assert.equal(s.expedition.transits.find(c=>c.id===r.id).t,1);pose(s,r.b);assert.ok(interact(s));assert.ok(s.p.ride);const before={...s.p};step(s,{},dt);assert.ok(Math.hypot(s.p.x-before.x,s.p.y-before.y,s.p.z-before.z)<.3);tick(s,r.seconds+1);assert.equal(s.p.ride,null);assert.ok(Math.hypot(s.p.x-r.a.x,s.p.y-r.a.y,s.p.z-r.a.z)<.05);assert.ok(s.expedition.routes.includes(r.kind));assert.equal(s.stats.rescues,0);for(const t of[0,.25,.5,.75,1])assert.ok(Object.values(transitPosition(r,t)).every(Number.isFinite));});
test('Jumping from transit never awards a completed ferry journey',()=>{const s=fresh(),r=TRANSIT.find(r=>!r.requires&&r.kind==='ferry');pose(s,r.a);interact(s);tick(s,4);const before={...s.p};assert.ok(jump(s));assert.equal(s.p.ride,null);assert.ok(Math.hypot(s.p.x-before.x,s.p.z-before.z)<.001);assert.ok(!s.expedition.routes.includes('ferry'));});
test('New rail passport stamps require reaching an actual rail end',()=>{const s=fresh(),r=RAILS.find(r=>r.id==='bellline'),q=pointOnRail(r,0);pose(s,{x:q.x,y:q.y-3.1,z:q.z});interact(s);tick(s,3);jump(s);step(s,{},dt);assert.ok(!s.expedition.routes.includes('rail'));pose(s,{x:q.x,y:q.y-3.1,z:q.z});s.p.hookCooldown=0;interact(s);for(let i=0;i<15000&&s.p.rail;i++)step(s,{boost:true,explorer:true},dt);assert.ok(s.expedition.routes.includes('rail'));});
test('Rest pavilions heal and checkpoint without credit farming or arbitrary-position saves',()=>{const s=fresh(),p=POSTS[2];pose(s,p);s.p.health=7;s.p.shield=0;const c=s.kit.credits;assert.equal(nearby(s)?.type,'exp-rest');interact(s);assert.equal(s.p.health,100);assert.equal(s.checkpoint,p.id);assert.equal(s.kit.credits,c);const saved=createState(saveState(s));assert.equal(saved.p.x,p.x);assert.equal(saved.p.z,p.z);assert.equal(saved.checkpoint,p.id);});
test('Humanoid projectiles respect cover; patrol feet remain on physical floors',()=>{const s=createState();s.p.invuln=1000;for(let i=0;i<1800;i++)step(s,{explorer:true},dt);for(const b of s.drones.filter(b=>b.humanoid&&b.hp>0)){assert.ok(!occupied(b.x,b.y-1.05,b.z,s),b.id);assert.ok(Math.abs(groundAt(b.x,b.z,b.y+1).y-(b.y-1.05))<.1,b.id);}assert.ok(s.drones.some(b=>b.humanoid&&Math.hypot(b.x-b.origin.x,b.z-b.origin.z)>.3));});
test('Humanoids have hittable heads, weapon damage, death and single-payment salvage',()=>{const s=fresh(),b=s.drones.find(b=>b.id==='bell-warden-a');b.hp=b.maxHp;pose(s,{x:b.x,y:b.y+.67-1.6,z:b.z+6});s.p.yaw=0;s.p.pitch=0;const hp=b.hp;fire(s);assert.ok(b.hp<hp-34,'Headshot receives the existing critical multiplier');assert.equal(s.stats.critical,1);tick(s,.26);fire(s);assert.ok(b.hp<=0);assert.equal(s.kit.dead.filter(id=>id===b.id).length,1);});
test('A real escort waits for the player and for nearby patrols, then walks to safety',()=>{const s=fresh();at(s,'surveyor');pose(s,{x:130,y:12,z:-54});tick(s,2);assert.equal(s.expedition.escort.z,-85);pose(s,{x:149,y:12,z:-81});const enemy=s.drones.find(b=>b.id==='dawn-warden');enemy.hp=enemy.maxHp;tick(s,2);assert.equal(s.expedition.escort.z,-85);enemy.hp=0;
 for(let i=0;i<10000&&!s.expedition.flags.includes('surveyor-safe');i++){const e=s.expedition.escort;pose(s,{x:e.x,y:e.y,z:e.z+3});step(s,{explorer:true},dt);}assert.ok(s.expedition.flags.includes('surveyor-safe'));assert.ok(Math.hypot(s.expedition.escort.x-130,s.expedition.escort.z+58)<.3);assert.equal(s.kit.credits,540);});
test('Solstice has three bounded combat waves, a minimum defense duration and a once-only reward',()=>{const s=fresh();at(s,'beacon-control');const base=s.kit.credits;let seen=new Set();for(let i=0;i<5000&&s.expedition.defense.active;i++){step(s,{explorer:true},dt);for(const b of s.drones.filter(b=>Number.isInteger(b.wave)&&b.hp>0)){seen.add(b.id);b.hp=0;}}
 assert.equal(seen.size,9);assert.ok(s.expedition.defense.time>=24);assert.equal(s.expedition.flags.includes('beacon-secure'),true);assert.equal(s.kit.credits,base+180);assert.ok(!s.kit.dead.some(id=>id.startsWith('solstice-wave')));at(s,'beacon-control');assert.equal(s.expedition.defense.active,false);assert.equal(s.kit.credits,base+180);});
test('Leaving a defense or rescue aborts transient motion safely and permits a fresh attempt',()=>{const s=fresh();at(s,'beacon-control');tick(s,2);s.p.x=100;step(s,{},dt);assert.equal(s.expedition.defense.active,false);assert.ok(!s.drones.some(b=>Number.isInteger(b.wave)&&b.hp>0));at(s,'beacon-control');assert.equal(s.expedition.defense.active,true);rescue(s,true);assert.equal(s.expedition.defense.active,false);assert.equal(s.p.ride,null);assert.ok(!s.expedition.flags.includes('beacon-secure'));});
test('Street discovery does not count remote flyovers; gallery surveys and final dispatch are guarded',()=>{const s=fresh();for(const d of EXP_DISTRICTS){pose(s,{...d,y:d.y+50});s.p.grounded=false;step(s,{},dt);}assert.equal(s.expedition.visited.length,0);for(const p of POSTS){pose(s,p);step(s,{},dt);}assert.equal(s.expedition.visited.length,7);assert.ok(s.expedition.flags.includes('all-districts'));for(const id of['survey-archive','survey-dawn','survey-solstice'])at(s,id);assert.ok(s.expedition.flags.includes('summits-surveyed'));at(s,'dispatch-board');assert.ok(!s.expedition.flags.includes('open-sky'));for(const id of['charter','weather-open','surveyor-safe','beacon-secure'])s.expedition.flags.push(id);at(s,'dispatch-board');assert.ok(s.expedition.flags.includes('open-sky'));const c=s.kit.credits;at(s,'dispatch-board');assert.equal(s.kit.credits,c);const snap=expeditionSnapshot(s);snap.flags.push('external-mutation');assert.ok(!s.expedition.flags.includes('external-mutation'));});
