import {test} from 'node:test';import assert from 'node:assert/strict';
import {createState,step,jump,toggleGlide,foldGlide,pointOnRail,RAILS,detach,interact,saveState,readSave,rescue,GLIDE} from '../model.mjs';
function launch(s0=44,speed=19){const s=createState(),r=RAILS.find(r=>r.id==='glassline'),q=pointOnRail(r,s0);Object.assign(s.p,{x:q.x,y:q.y-2.65,z:q.z,grounded:false,rail:{id:r.id,s:s0,dir:1},speed,yaw:Math.atan2(q.tangent.x,-q.tangent.z)});detach(s,true);return s;}
function update(s,controls,n=1){for(let i=0;i<n;i++)step(s,{...controls,explorer:true},1/120);}
test('Opening a foldwing preserves position and launch velocity',()=>{const s=launch(),before={...s.p};assert.ok(toggleGlide(s));for(const k of['x','y','z','vx','vy','vz'])assert.equal(s.p[k],before[k]);assert.equal(s.stats.glides,1);});
test('It cannot open from the ground, on a rail, with no charge or after completion',()=>{const s=createState();assert.equal(toggleGlide(s),false);s.p.grounded=false;s.p.y=10;s.p.rail={id:'glassline',s:10,dir:1};assert.equal(toggleGlide(s),false);s.p.rail=null;s.p.glideCharge=0;assert.equal(toggleGlide(s),false);s.p.glideCharge=100;s.won=true;assert.equal(toggleGlide(s),false);});
test('The canopy slows an actual fall over time, not a teleport or upwards boost',()=>{const s=launch();s.p.vy=-15;toggleGlide(s);const y=s.p.y;update(s,{},1);assert.ok(s.p.vy< -14&&s.p.vy> -15);assert.ok(s.p.y<y);});
test('Coasting preserves horizontal travel independent of where the player looks',()=>{const a=launch(),b=launch();toggleGlide(a);toggleGlide(b);b.p.yaw+=2;update(a,{},30);update(b,{},30);assert.equal(a.p.x,b.p.x);assert.equal(a.p.z,b.p.z);});
test('Steering and braking are explicit, bounded and do not rotate the camera',()=>{const a=launch(),b=launch();toggleGlide(a);toggleGlide(b);const yaw=b.p.yaw;update(a,{forward:true},50);update(b,{back:true},50);assert.ok(Math.hypot(b.p.vx,b.p.vz)<Math.hypot(a.p.vx,a.p.vz));assert.equal(b.p.yaw,yaw);});
test('Charge drains only while gliding and recharges on a rail or ground',()=>{const s=launch();toggleGlide(s);update(s,{},60);assert.ok(Math.abs(s.p.glideCharge-93.75)<.01);foldGlide(s);const n=s.p.glideCharge;update(s,{},10);assert.equal(s.p.glideCharge,n);s.p.y=0;s.p.grounded=true;s.p.x=s.p.z=0;s.p.vy=0;update(s,{},20);assert.ok(s.p.glideCharge>n);});
test('Depletion folds the canopy rather than allowing infinite altitude-free travel',()=>{const s=launch();s.p.glideCharge=8;toggleGlide(s);update(s,{},100);assert.equal(s.p.gliding,false);assert.equal(s.p.glideCharge,0);assert.ok(s.events.some(e=>e.type==='glide-fold'&&e.reason==='empty'));});
test('Folding retains velocity and resumed gravity accelerates downward',()=>{const s=launch();toggleGlide(s);update(s,{},30);const vy=s.p.vy;assert.ok(toggleGlide(s));assert.equal(s.p.vy,vy);update(s,{},1);assert.ok(s.p.vy<vy);});
test('Rescue cannot leave a stale airborne canopy active',()=>{const s=launch();toggleGlide(s);rescue(s);assert.equal(s.p.gliding,false);assert.equal(s.p.glideCharge,100);assert.equal(s.p.grounded,true);});
test('Glider state is not a new arbitrary-position save or equipment duplication source',()=>{const s=launch();toggleGlide(s);const saved=JSON.parse(saveState(s));assert.equal(saved.version,1);assert.equal(saved.gliding,undefined);const restored=createState(saved);assert.equal(restored.p.gliding,false);assert.equal(restored.kit.credits,s.kit.credits);});
test('Multiple full rail releases can steer to the garden and land without rescue',()=>{for(const start of[38,42,46,50])for(const speed of[16,19,22]){const s=launch(start,speed);toggleGlide(s);for(let i=0;i<1200&&!s.p.grounded;i++){s.p.yaw=Math.atan2(65-s.p.x,-(-24-s.p.z));const brake=Math.hypot(65-s.p.x,-24-s.p.z)<18;update(s,{forward:!brake,back:brake});}assert.equal(s.stats.rescues,0);assert.ok(s.p.grounded,'start '+start+' speed '+speed);assert.equal(s.p.gliding,false);assert.ok(s.stats.glideDistance>15);}});
