import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as T from '../vendor/three.module.js';import {GLTFLoader} from '../vendor/loaders/GLTFLoader.js';
import {createLegSolver,createGrounding,strideRate,CAST_HEIGHTS} from '../grounded-motion.mjs';
import {prepareRig,cloneRig,disposeInstance,disposeRig} from '../cast-rig.mjs';
import {HandPinchSampler} from '../hand-input.mjs';import {InputSampler,xrControls} from '../input-core.mjs';import {spatialPage,spatialHit} from '../spatial-menu.mjs';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
async function load(){const b=fs.readFileSync(new URL('../art/characters/guard.glb',import.meta.url));return prepareRig(await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),''));}
function actor(rig){const wrapper=new T.Group(),model=cloneRig(rig.source);wrapper.add(model);const k=1.84/rig.height;model.scale.setScalar(k);model.position.y=-rig.feet*k;const mixer=new T.AnimationMixer(model);mixer.clipAction(rig.clips.find(c=>c.name==='Idle_Neutral')).play();mixer.update(0);wrapper.updateMatrixWorld(true);return {wrapper,model,mixer};}
test('Analytic solver preserves both limb lengths through 2000 reachable and unreachable targets',()=>{const solve=createLegSolver(),h=V(0,1,0),k=V(0,.55,.14),a=V(0,.03,0),n=V(),f=V();for(let i=0;i<2000;i++){const t=V(Math.sin(i)*1.6,Math.cos(i*.73)+.4,Math.sin(i*.33)),ok=solve(h,k,a,t,k,n,f);assert.ok(ok);assert.ok(Math.abs(h.distanceTo(n)-h.distanceTo(k))<1e-8);assert.ok(Math.abs(n.distanceTo(f)-k.distanceTo(a))<1e-8);assert.ok(h.distanceTo(f)<h.distanceTo(k)+k.distanceTo(a));}});
test('Degenerate poles and zero target distance stay finite; NaN and zero-length limbs are rejected',()=>{const solve=createLegSolver(),n=V(),f=V();assert.ok(solve(V(0,1),V(0,.5),V(),V(0,1),V(0,2),n,f));assert.ok(n.toArray().every(Number.isFinite));assert.equal(solve(V(),V(),V(),V(),V(),n,f),false);assert.equal(solve(V(0,1),V(0,.5),V(),V(NaN),V(),n,f),false);});
test('Stride follows travelled speed with bounded walking/running cadence and unchanged action clips',()=>{assert.equal(strideRate(1.55,'Walk'),1);assert.equal(strideRate(3.5,'Run_Shoot'),1);assert.equal(strideRate(99,'Walk'),1.65);assert.equal(strideRate(0,'Walk'),.55);assert.equal(strideRate(99,'Death'),1);assert.ok(CAST_HEIGHTS.courier<1.8&&CAST_HEIGHTS.guard<1.9&&CAST_HEIGHTS.breacher<2.1);});
test('Real sibling foot controls lock without stretching either leg and release on missing floor',async()=>{const rig=await load(),{wrapper,model,mixer}=actor(rig);let floor=true;const grounding=createGrounding(model,()=>({y:floor?0:-Infinity,id:'deck'})),foot=model.getObjectByName('FootL');assert.notEqual(foot.parent,model.getObjectByName('LowerLegL'));let initial;
 for(let i=0;i<12;i++){grounding.restore();mixer.update(1/60);wrapper.position.x=i*.008;wrapper.updateMatrixWorld(true);const h=model.getObjectByName('UpperLegL').getWorldPosition(V()),k=model.getObjectByName('LowerLegL').getWorldPosition(V()),a=foot.getWorldPosition(V()),len=h.distanceTo(k)+k.distanceTo(a);grounding.update(1/60,{x:wrapper.position.x,y:0,z:0});const newK=model.getObjectByName('LowerLegL').getWorldPosition(V()),newA=foot.getWorldPosition(V());assert.ok(Math.abs(h.distanceTo(newK)+newK.distanceTo(newA)-len)<1e-6);if(i===0)initial=newA.clone();if(i>3)assert.ok(Math.abs(newA.x-initial.x)<.018);}
 assert.ok(grounding.stats().locked>0);floor=false;grounding.restore();mixer.update(.016);wrapper.updateMatrixWorld(true);grounding.update(.016,{x:.1,y:0,z:0});assert.equal(grounding.stats().locked,0);disposeInstance(wrapper);disposeRig(rig);});
test('Grounding never accumulates into the source animation over 180 mixer frames',async()=>{const rig=await load(),a=actor(rig),b=actor(rig),g=createGrounding(a.model,()=>({y:0,id:'deck'}));for(let i=0;i<180;i++){g.restore();a.mixer.update(1/60);b.mixer.update(1/60);a.wrapper.updateMatrixWorld(true);g.update(1/60,{x:0,y:0,z:0});g.restore();for(const name of ['UpperLegL','LowerLegL','FootL','FootR']){const x=a.model.getObjectByName(name),y=b.model.getObjectByName(name);assert.ok(x.quaternion.toArray().every((v,i)=>Math.abs(v-y.quaternion.toArray()[i])<1e-9),name);assert.ok(x.position.distanceTo(y.position)<1e-8);}}disposeInstance(a.wrapper);disposeInstance(b.wrapper);disposeRig(rig);});
test('Teleport, airborne, invalid dt and steep missing support cannot retain stale foot anchors',async()=>{const rig=await load(),a=actor(rig),g=createGrounding(a.model,()=>({y:0,id:'deck'}));const step=(x,dt=.016,grounded=true)=>{g.restore();a.mixer.update(.016);a.wrapper.position.x=x;a.wrapper.updateMatrixWorld(true);g.update(dt,{x,y:0,z:0,grounded});};step(0);assert.ok(g.stats().locked>0);step(4);assert.ok(g.stats().feet.every(f=>f.target[0]>3.5));step(4,.016,false);assert.equal(g.stats().locked,0);step(4,NaN);assert.equal(g.stats().locked,0);step(4,0);assert.equal(g.stats().locked,0);assert.ok(g.stats().resets>=3);disposeInstance(a.wrapper);disposeRig(rig);});
test('Gentle per-foot ramp samples stay reachable at 30, 60 and 90 Hz',async()=>{const rig=await load();for(const hz of [30,60,90]){const a=actor(rig),g=createGrounding(a.model,(x,z)=>({y:.08*x,id:'ramp'}));for(let i=0;i<30;i++){g.restore();a.mixer.update(1/hz);a.wrapper.updateMatrixWorld(true);g.update(1/hz,{x:0,y:0,z:0});assert.ok(g.stats().maxError<.025);}disposeInstance(a.wrapper);}disposeRig(rig);});
function handFixture(){const source={handedness:'right',hand:new Map([['thumb-tip','thumb'],['index-finger-tip','index']]),targetRaySpace:'ray'},q={x:0,y:0,z:0,w:1},f={distance:.05,missing:false,noRay:false};f.getJointPose=j=>f.missing?null:{transform:{position:{x:j==='index'?f.distance:0,y:1,z:0},orientation:q}};f.getPose=()=>f.noRay?null:{transform:{position:{x:0,y:1,z:0},orientation:q}};return {source,f};}
test('Pinches require neutral opening, select once and ignore threshold jitter',()=>{const {source,f}=handFixture(),s=new HandPinchSampler();f.distance=.02;assert.equal(s.sample(source,f,{}).pressed,false);f.distance=.05;s.sample(source,f,{});f.distance=.02;assert.equal(s.sample(source,f,{}).pressed,true);for(const d of [.02,.026,.035,.028,.024]){f.distance=d;assert.equal(s.sample(source,f,{}).pressed,false);}f.distance=.05;s.sample(source,f,{});f.distance=.02;assert.equal(s.sample(source,f,{}).pressed,true);});
test('Tracking loss, changed source and menu reset require a fresh open hand',()=>{const {source,f}=handFixture(),s=new HandPinchSampler();s.sample(source,f,{});f.missing=true;assert.equal(s.sample(source,f,{}).tracked,false);f.missing=false;f.distance=.02;assert.equal(s.sample(source,f,{}).pressed,false);f.distance=.05;s.sample(source,f,{});s.reset();f.distance=.02;assert.equal(s.sample(source,f,{}).pressed,false);f.distance=.05;s.sample(source,f,{});f.distance=.02;assert.equal(s.sample({...source},f,{}).pressed,false);});
test('Missing hand ray suppresses selection even with valid pinching joints',()=>{const {source,f}=handFixture(),s=new HandPinchSampler();s.sample(source,f,{});f.noRay=true;f.distance=.02;assert.equal(s.sample(source,f,{}).tracked,false);f.noRay=false;assert.equal(s.sample(source,f,{}).pressed,false);});
test('A hand source exposing xr-standard gamepad cannot fire, cast, jump or move',()=>{const s=new InputSampler(),source={hand:{},handedness:'right',gamepad:{mapping:'xr-standard',connected:true,buttons:Array.from({length:8},()=>({pressed:true,value:1})),axes:[1,1,1,1]}};for(let i=0;i<3;i++){const c=xrControls(s,[source]);assert.ok(!c.held.fire&&!c.edges.confirm&&!c.edges.jump);assert.deepEqual(c.move,[0,0]);}});
test('Spatial menus expose every page, adjustable value buttons, Back and real Exit VR',()=>{const menu={index:7,items:Array.from({length:18},(_,i)=>({label:'item '+i,element:{type:i===7?'range':'button'}}))},p=spatialPage(menu);assert.equal(p.length,11);assert.equal(p[0].label,'item 5');for(const k of ['previous-page','next-page','decrease','increase','back','exit'])assert.equal(p.find(v=>v.kind===k).disabled,false);for(const item of p){assert.equal(spatialHit(p,(item.x+5)/1024,1-(item.y+5)/768),item);}assert.equal(spatialHit(p,NaN,0),null);menu.index=17;assert.equal(spatialPage(menu).find(v=>v.kind==='next-page').disabled,true);});
