import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import * as T from '../vendor/three.module.js';
import {QUAY_BUILDINGS,QUAY_LAMPS,QUAY_PLANTERS,facadePlan} from '../quay-layout.mjs';
import {BUILDINGS} from '../model.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=n=>fs.readFileSync(path.join(root,n)),manifest=JSON.parse(read('art/manifest.json'));
function glb(name){const b=read('art/'+name);assert.equal(b.readUInt32LE(0),0x46546c67);assert.equal(b.readUInt32LE(4),2);assert.equal(b.readUInt32LE(8),b.length);return JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));}
function bounds(j,index){const box=new T.Box3();function visit(i,parent){const n=j.nodes[i],m=new T.Matrix4();if(n.matrix)m.fromArray(n.matrix);else m.compose(new T.Vector3(...n.translation||[0,0,0]),new T.Quaternion(...n.rotation||[0,0,0,1]),new T.Vector3(...n.scale||[1,1,1]));m.premultiply(parent);if(n.mesh!==undefined)for(const p of j.meshes[n.mesh].primitives){const a=j.accessors[p.attributes.POSITION];box.union(new T.Box3(new T.Vector3(...a.min),new T.Vector3(...a.max)).applyMatrix4(m));}for(const c of n.children||[])visit(c,m);}visit(index,new T.Matrix4());return box;}
test('Every stored runtime art file has a matching source register and SHA-256',()=>{assert.equal(manifest.files.length,19);assert.equal(new Set(manifest.sources.map(s=>s.id)).size,6);assert.ok(manifest.sources.every(s=>s.creator&&s.license==='CC0-1.0'&&s.url.startsWith('https://')));for(const f of manifest.files){assert.equal(path.basename(f.file),f.file);const b=read('art/'+f.file);assert.equal(b.length,f.bytes);assert.equal(createHash('sha256').update(b).digest('hex'),f.sha256);}assert.ok(manifest.totalBytes<9_000_000);});
test('Models are portable GLBs with embedded buffers/images, no hidden remote dependencies',()=>{for(const f of manifest.files.filter(f=>f.file.endsWith('.glb'))){const j=glb(f.file);assert.equal(j.buffers.length,1);assert.ok(j.buffers.every(b=>!b.uri));assert.ok(j.images.every(i=>i.bufferView!==undefined&&!i.uri));assert.deepEqual(j.extensionsRequired,['EXT_texture_webp']);assert.ok(!j.animations?.length);}});
test('The modular library retains named reusable components in both texture profiles',()=>{for(const p of ['desktop','mobile']){const j=glb('architecture-'+p+'.glb'),names=j.scenes[0].nodes.map(i=>j.nodes[i].name);assert.equal(names.length,13);for(const b of QUAY_BUILDINGS)for(const part of facadePlan(b))assert.ok(names.includes(part.module));}});
test('Authored new facades match the old solid building footprints and do not expand walls into routes',()=>{const j=glb('architecture-desktop.glb');for(const b of QUAY_BUILDINGS){const old=BUILDINGS.find(o=>o.id===b.id);for(const key of ['x','z','w','d'])assert.equal(b[key],old[key]);for(const slot of facadePlan(b)){const node=j.scenes[0].nodes.find(i=>j.nodes[i].name===slot.module),bb=bounds(j,node);const m=new T.Matrix4().compose(new T.Vector3(slot.x,slot.y,slot.z),new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),slot.yaw),new T.Vector3(slot.sx,1,1));bb.applyMatrix4(m);assert.ok(bb.min.x>=b.x-b.w/2-.01&&bb.max.x<=b.x+b.w/2+.01,slot.face+' X');assert.ok(bb.min.z>=b.z-b.d/2-.01&&bb.max.z<=b.z+b.d/2+.01,slot.face+' Z');}}});
test('Props avoid central navigation, the archive, the shop, engineering and rail boarding',()=>{const keep=[[0,5],[0,-15],[3,7],[7,4],[-5,4],[9,-5],[-10,-8],[14,-4]];for(const [x,y,z]of[...QUAY_LAMPS,...QUAY_PLANTERS]){assert.equal(y,0);assert.ok(Math.abs(x)<16.5&&Math.abs(z)<16.5);for(const [a,b]of keep)assert.ok(Math.hypot(a-x,b-z)>1.7);}});
test('The mobile profile reduces each imported prop and texture download without removing its identity',()=>{const get=n=>manifest.files.find(f=>f.file===n).bytes;for(const id of ['lamp','planter','architecture'])assert.ok(get(id+'-mobile.glb')<get(id+'-desktop.glb'));for(const id of ['lamp','planter']){const models=manifest.models;assert.ok(models.find(m=>m.file===id+'-mobile.glb').triangles<models.find(m=>m.file===id+'-desktop.glb').triangles*.5);}});
test('Art code neither imports the simulation nor writes persistence or progress',()=>{const text=read('quay-art.mjs').toString();assert.doesNotMatch(text,/from ['"].*model\.mjs|localStorage|sessionStorage|\.kit\b|\.relays\b|\.health\b|\.setAnimationLoop\(/);assert.match(text,/InstancedMesh/);assert.match(text,/fallbacks\.buildings\.visible=false/);assert.match(text,/state\.errors\.push/);});
