import {test} from 'node:test';import assert from 'node:assert/strict';
import {LADDERS,ROOFS,ROOF_TASKS,ROOF_THINGS,BEACON_TARGETS,ROOF_ENEMIES} from '../rooftop-world.mjs';
import {createState,step,nearby,interact,jump,toggleGlide,rescue,groundAt,occupied,saveState,fieldScan} from '../model.mjs';
import {cleanExpedition} from '../expedition-core.mjs';
const dt=1/120;const fresh=()=>{const s=createState();for(const b of s.drones)b.hp=0;s.p.invuln=9999;return s;};
const pose=(s,p)=>Object.assign(s.p,{x:p[0],y:p[1],z:p[2],rail:null,ride:null,climb:null,grounded:true,vx:0,vy:0,vz:0});
function at(s,id){const t=ROOF_THINGS.find(t=>t.id===id);pose(s,[t.x,t.y,t.z]);assert.equal(nearby(s)?.id,id);assert.ok(interact(s));}
for(const r of LADDERS)test(r.name+' climbs continuously to its roof and descends to its original street',()=>{const s=fresh();pose(s,r.points[0]);assert.ok(Number.isFinite(groundAt(s.p.x,s.p.z,s.p.y+.1).y));assert.equal(occupied(s.p.x,s.p.y,s.p.z,s),false);assert.equal(nearby(s)?.id,r.id);assert.ok(interact(s));assert.ok(s.p.climb);let last={...s.p};for(let i=0;i<3000&&s.p.climb;i++){step(s,{moveZ:1},dt);assert.ok(Math.hypot(s.p.x-last.x,s.p.y-last.y,s.p.z-last.z)<=.04);last={...s.p};}for(let i=0;i<100;i++)step(s,{},dt);assert.equal(s.p.climb,null);assert.ok(s.p.grounded);assert.equal(s.p.y,ROOFS.find(t=>t.id===r.roof).y);assert.equal(s.stats.rescues,0);assert.ok(interact(s));assert.ok(s.p.climb);for(let i=0;i<3000&&s.p.climb;i++)step(s,{moveZ:-1},dt);for(let i=0;i<80;i++)step(s,{},dt);assert.equal(s.p.y,r.points[0][1]);assert.equal(s.stats.rescues,0);});
test('Ladder holds require input; jump, drop, rescue and save/reload never leave stale climbing',()=>{const s=fresh(),r=LADDERS[0];pose(s,r.points[0]);interact(s);for(let i=0;i<220;i++)step(s,{moveZ:1},dt);const y=s.p.y;for(let i=0;i<120;i++)step(s,{},dt);assert.equal(s.p.y,y);const restored=createState(saveState(s));assert.ok(!restored.p.climb);assert.ok(jump(s));assert.ok(!s.p.climb);assert.ok(s.p.vy>0);pose(s,r.points[0]);interact(s);assert.ok(toggleGlide(s));assert.ok(!s.p.climb);pose(s,r.points[0]);interact(s);rescue(s);assert.ok(!s.p.climb);});
test('Rooftop courier needs all three separately located parcels and pays once',()=>{const s=fresh();at(s,'roof-desk');assert.equal(s.kit.credits,400);for(const id of ['roof-parcel-gannet','roof-parcel-academy','roof-parcel-dawn'])at(s,id);assert.equal(s.kit.credits,400);at(s,'roof-desk');assert.equal(s.kit.credits,580);at(s,'roof-desk');assert.equal(s.kit.credits,580);assert.ok(createState(saveState(s)).expedition.flags.includes('roof-courier-done'));});
test('Three actual rooftop rings must align; repeated energizing cannot duplicate the reward',()=>{const s=fresh();at(s,'roof-desk');for(let i=0;i<3;i++)for(let n=0;n<BEACON_TARGETS[i];n++)at(s,'roof-beacon-'+i);assert.equal(s.kit.credits,400);const restored=createState(saveState(s));assert.deepEqual(restored.expedition.beaconDials,[2,1,3]);at(s,'roof-desk');assert.equal(s.kit.credits,640);at(s,'roof-desk');assert.equal(s.kit.credits,640);});
test('Six surveys are proximity interactions, not remote flyover awards or the old summit task',()=>{const s=fresh();for(const r of ROOFS)at(s,'survey-'+r.id);assert.equal(s.kit.credits,620);assert.ok(s.expedition.flags.includes('roof-surveys-done'));assert.ok(!s.expedition.flags.includes('summits-surveyed'));});
test('New dial storage is sanitized and old campaign flags remain valid',()=>{assert.deepEqual(cleanExpedition({beaconDials:[Infinity,99,-99]}).beaconDials,[0,3,0]);assert.deepEqual(cleanExpedition(null).beaconDials,[0,0,0]);for(const t of ROOF_TASKS)assert.ok(cleanExpedition({flags:[t.flag]}).flags.includes(t.flag));});
test('Longshot and skirmisher are different combat profiles on supported rooftops',()=>{const [a,b]=ROOF_ENEMIES;assert.ok(a.range>b.range&&a.projectileSpeed>b.projectileSpeed&&a.attackDelay>b.attackDelay&&a.hp<b.hp);for(const enemy of ROOF_ENEMIES){assert.equal(groundAt(enemy.x,enemy.z,enemy.y).y,enemy.y-1.05);assert.equal(occupied(enemy.x,enemy.y-1.05,enemy.z),false);}});
