import {test} from 'node:test';import assert from 'node:assert/strict';
import {createState,readSave,saveState,step,interact,fieldCast,fieldChoose,fieldModule,fieldScan,fieldRotate,fieldHack,fieldStart,fieldUnlocked,fire,weaponStats,rescue,equip} from '../model.mjs';
import {FIELD_BENCH,SECURITY,RECOVERY,connectedCircuit,rotateCircuit,cleanTactics} from '../tactics-core.mjs';
const move=(s,p)=>Object.assign(s.p,p,{grounded:true,rail:null,invuln:0});
const toward=(s,p)=>{s.p.yaw=Math.atan2(p.x-s.p.x,-(p.z-s.p.z));s.p.pitch=Math.atan2(p.y-s.p.y-1.6,Math.hypot(p.x-s.p.x,p.z-s.p.z));};
const seconds=(s,n)=>{for(let i=0;i<Math.ceil(n*120);i++)step(s,{explorer:true},1/120);};
function rig(){const s=createState();move(s,FIELD_BENCH);assert.ok(interact(s));return s;}
function hacked(){const s=rig();move(s,SECURITY);for(const [cell,n]of [[0,1],[1,1],[2,2],[3,3],[5,3]])for(let j=0;j<n;j++)assert.ok(fieldRotate(s,cell));assert.ok(fieldHack(s));return s;}
function range(power='current'){const s=rig();move(s,{x:14,y:0,z:2});fieldChoose(s,power);toward(s,s.drones.find(b=>b.id==='range'));return s;}
test('Version-1 saves retain equipment and isolate new persistent state from transient battles',()=>{const s=rig();s.kit.credits=777;s.tactics.hacked=true;s.tactics.research=['scout'];s.tactics.hazards['quay-water']=4;s.tactics.encounter.phase='active';const r=createState(saveState(s));assert.equal(r.kit.credits,777);assert.ok(r.tactics.learned&&r.tactics.hacked);assert.deepEqual(r.tactics.research,['scout']);assert.equal(r.tactics.encounter.phase,'idle');assert.equal(r.tactics.hazards['quay-water'],0);assert.equal(r.drones.filter(b=>b.tactical).length,0);});
test('Loan rig must be collected by a real nearby bench interaction; unknown actions are denied',()=>{const s=createState();assert.equal(fieldChoose(s,'current'),false);assert.equal(fieldChoose(s,'__proto__'),false);move(s,FIELD_BENCH);assert.ok(interact(s));assert.ok(s.tactics.learned);assert.ok(fieldChoose(s,'current'));assert.equal(fieldModule(s,'engineer'),false);});
test('Gun and power have independent ammunition/cooldowns and can fire in the same simulation tick',()=>{const s=range(),ammo=s.p.ammo;assert.ok(fieldCast(s));assert.equal(s.p.ammo,ammo);assert.equal(s.p.shoot,0);assert.ok(fire(s));assert.equal(s.p.ammo,ammo-1);assert.equal(fieldCast(s),false);assert.equal(s.tactics.metrics.combos,1);});
test('Aimed electricity in water does more immediate damage than the same dry target',()=>{const wet=range(),dry=range();const b=dry.drones.find(b=>b.id==='range');b.y=7;toward(dry,b);fieldCast(wet);fieldCast(dry);assert.equal(wet.drones.find(b=>b.id==='range').hp,57);assert.equal(b.hp,84);assert.equal(wet.tactics.hazards['quay-water'],4.5);assert.equal(dry.tactics.hazards['quay-water'],0);});
test('Conductive water reaches a second visible nearby machine and then expires',()=>{const s=range();s.drones.find(b=>b.id==='g1').x=12.8;Object.assign(s.drones.find(b=>b.id==='g1'),{y:1.8,z:-4,origin:{x:12.8,y:1.8,z:-4}});assert.ok(fieldCast(s));const b=s.drones.find(b=>b.id==='g1');assert.ok(b.hp<85&&b.stun>0);seconds(s,5);assert.equal(s.tactics.hazards['quay-water'],0);});
test('Heat primes the actual oil patch, burning enemies over time rather than spending weapon ammunition',()=>{const s=rig();move(s,{x:-24,y:12,z:-96});const b=s.drones.find(b=>b.id==='f1');fieldChoose(s,'cinder');toward(s,b);const ammo=s.p.ammo;assert.ok(fieldCast(s));assert.equal(s.tactics.hazards['works-oil'],7);assert.ok(b.burning>0);const initial=b.hp;seconds(s,2);assert.ok(b.hp<initial-20);assert.equal(s.p.ammo,ammo);});
test('Shared wall occlusion and controller pose bounds prevent power or survey hits through buildings',()=>{const s=rig();move(s,{x:-35,y:12,z:-100});const b=s.drones.find(b=>b.id==='f1');Object.assign(b,{x:-35,y:14,z:-80});toward(s,b);fieldChoose(s,'current');assert.ok(fieldCast(s));assert.equal(b.hp,180);assert.equal(fieldScan(s),false);s.tactics.cooldown=0;const energy=s.p.energy;assert.equal(fieldCast(s,{origin:{x:100,y:20,z:0},direction:{x:0,y:0,z:-1}}),false);assert.equal(s.p.energy,energy);});
test('Survey requires a living, visible unrecorded class and cannot be farmed repeatedly',()=>{const s=range();assert.ok(fieldScan(s));assert.deepEqual(s.tactics.research,['target']);assert.equal(fieldScan(s),false);assert.ok(fieldUnlocked(s,'capacitor'));assert.ok(fieldModule(s,'capacitor'));s.tactics.scanCooldown=0;assert.equal(fieldScan(s),false);const restored=createState(saveState(s));assert.deepEqual(restored.tactics.research,['target']);});
test('Capacitor cost and researched damage are actual numeric changes, not UI labels',()=>{const s=range();fieldScan(s);fieldModule(s,'capacitor');assert.ok(fieldCast(s));assert.equal(s.p.energy,79);const b=s.drones.find(b=>b.id==='range');b.shocked=0;b.burning=0;b.hp=200;const before=b.hp;fire(s);assert.ok(Math.abs(before-b.hp-weaponStats(s).damage*1.1)<1e-8);});
test('Catalyst bonus applies only to afflicted targets, and only one passive is active',()=>{const s=range();s.tactics.research=['scout','heavy'];assert.ok(fieldModule(s,'catalyst'));const b=s.drones.find(b=>b.id==='range');b.hp=300;b.shocked=2;fire(s);assert.ok(Math.abs(b.hp-(300-34*1.2))<1e-8);s.p.shoot=0;b.shocked=0;fire(s);assert.ok(Math.abs(b.hp-(300-34*2.2))<1e-8);});
test('The security puzzle uses real adjacent port connectivity, not a predetermined click count',()=>{assert.equal(connectedCircuit([15]).connected,false);assert.equal(connectedCircuit([3,5,3,3,5,6,3,5,3]).connected,false);const c=[6,10,12,9,5,3,3,5,3];assert.deepEqual(connectedCircuit(c),{connected:true,path:[3,0,1,2,5]});for(let i=0;i<4;i++)c[1]=rotateCircuit(c[1]);assert.ok(connectedCircuit(c).connected);c[2]=3;assert.equal(connectedCircuit(c).connected,false);});
test('Hacking and conductor rotation require proximity, and rewards cannot be paid twice',()=>{const s=rig();assert.equal(fieldRotate(s,0),false);const h=hacked();assert.ok(h.tactics.hacked);const credits=h.kit.credits;assert.equal(fieldHack(h),false);assert.equal(h.kit.credits,credits);assert.ok(fieldUnlocked(h,'engineer'));assert.ok(createState(saveState(h)).tactics.hacked);});
test('An idle trial does not spawn extra enemies or replace the existing relay expedition',()=>{const s=createState();seconds(s,90);assert.equal(s.tactics.encounter.phase,'idle');assert.equal(s.drones.filter(b=>b.tactical).length,0);assert.equal(s.relays.size,0);assert.ok(s.drones.some(b=>b.id==='g1'));});
test('Unprepared unattended recovery can fail and genuinely needs defending',()=>{const s=rig();move(s,RECOVERY);assert.ok(fieldStart(s));seconds(s,100);assert.equal(s.tactics.encounter.phase,'failed');assert.equal(s.tactics.completed,false);assert.equal(s.kit.credits,400);});
test('Hacked security, active weapon use and preparation complete all waves without assigning mission progress',()=>{const s=hacked();fieldModule(s,'engineer');move(s,RECOVERY);const before=s.kit.credits;assert.ok(fieldStart(s));for(let i=0;i<100*120&&s.tactics.encounter.phase==='active';i++){const b=s.drones.find(b=>b.tactical&&b.hp>0);if(b){toward(s,b);if(s.p.ammo)fire(s);else if(s.p.reload<=0)step(s,{reload:true,explorer:true},1/120);}step(s,{explorer:true},1/120);}assert.equal(s.tactics.encounter.phase,'complete');assert.ok(s.tactics.encounter.kills===6&&s.tactics.metrics.turretHits>0);assert.equal(s.kit.credits,before+180);const restored=createState(saveState(s));assert.ok(restored.tactics.completed);move(restored,RECOVERY);assert.ok(fieldStart(restored));seconds(restored,1);assert.equal(restored.kit.credits,before+180);});
test('A mid-battle rescue or retreat stops the trial and clears its actors without inventing a reward',()=>{const s=hacked();move(s,RECOVERY);fieldStart(s);seconds(s,3);assert.equal(s.drones.filter(b=>b.tactical).length,2);rescue(s);assert.equal(s.tactics.encounter.phase,'retreated');assert.equal(s.drones.filter(b=>b.tactical).length,0);assert.equal(s.tactics.completed,false);});
test('Sanitization caps research to known unique classes and strips runtime enemy/currency injections',()=>{const t=cleanTactics({learned:1,power:'__proto__',module:'constructor',research:['heavy','heavy','fake'],enemies:['bad'],reward:9999});assert.equal(t.learned,false);assert.equal(t.power,'pulse');assert.deepEqual(t.research,['heavy']);assert.ok(!('reward' in t));});
