import {test} from 'node:test';import assert from 'node:assert/strict';
import {createState,saveState,readSave,step,nearby,interact,groundAt,occupied,clearLine,fire,fieldCast,jump,tideAction,combatUse,combatTraverse,rescue} from '../model.mjs';
import {TIDE_POINTS,TIDE_POOLS,TIDE_FLOORS,TIDE_TASKS,TIDEGLASS,TIDE_LADDERS,tidePoolAt,tideGoal} from '../tideglass-world.mjs';
import {createTideglass,cleanTideglass} from '../tideglass-core.mjs';
import {waterBudget,makePoolWater,patchPoolTiles} from '../tideglass-shaders.mjs';
import {installTideglassScene} from '../tideglass-scene.mjs';
import * as T from '../vendor/three.module.js';
const dt=1/120;
function fresh(){const s=createState();s.drones=[];return s;}
function run(s,n,input={}){for(let i=0;i<n/dt;i++){step(s,input,dt);s.events=[];}}
function pose(s,x,y,z){Object.assign(s.p,{x,y,z,vx:0,vy:0,vz:0,grounded:true,rail:null,ride:null,climb:null});}
function at(s,id){const p=TIDE_POINTS.find(q=>q.id===id);pose(s,p.x,p.y,p.z);assert.equal(nearby(s)?.id,id);return interact(s);}
function walk(s,x,z){for(let i=0;i<7000;i++){const dx=x-s.p.x,dz=z-s.p.z,l=Math.hypot(dx,dz);if(l<.12)return;s.p.yaw=Math.atan2(dx,-dz);step(s,{moveZ:Math.min(1,l*2)},dt);s.events=[];}assert.fail('Blocked '+JSON.stringify(s.p)+' -> '+[x,z]);}
function start(s){at(s,'tide-desk');at(s,'tide-valve-0');at(s,'tide-valve-1');}
test('Tideglass opens real basin holes rather than painting water onto the walkable island',()=>{assert.equal(groundAt(132,-2,8).y,1.8);assert.equal(groundAt(146,12,8).y,5.55);assert.equal(groundAt(116,12,8).y,6);assert.ok(!TIDE_FLOORS.some(f=>f.y===6&&Math.abs(f.x-132)<f.w/2&&Math.abs(f.z+2)<f.d/2));});
test('Every physical quest point has support, a clear body and a visible interaction',()=>{const s=fresh();s.tideglass.stage=1;for(const p of TIDE_POINTS){pose(s,p.x,p.y,p.z);assert.equal(groundAt(p.x,p.z,p.y+.1).y,p.y,p.id);assert.equal(occupied(p.x,p.y,p.z,s),false,p.id);assert.equal(nearby(s)?.id,p.id);}});
test('Old saves retain equipment and progression; new saves never restore swimming poses or ripple simulation',()=>{const s=createState({version:1,kit:{credits:840},checkpoint:'garden',relays:['garden']});assert.equal(s.kit.credits,840);assert.equal(s.tideglass.stage,0);assert.equal(s.p.water.swimming,false);assert.ok(s.relays.has('garden'));s.p.water.swimming=true;s.p.water.diving=true;s.tideglass.ripples=[{x:1,z:2}];const r=createState(saveState(s));assert.equal(r.p.water.swimming,false);assert.equal(r.tideglass.ripples.length,0);assert.equal(r.checkpoint,'garden');});
test('Remote or early regulator/pump interactions cannot skip isolation prerequisites',()=>{const s=fresh(),core=createTideglass({occupied,groundAt,clearLine,emit(){}});assert.equal(core.use(s,'tide-desk'),false);at(s,'tide-desk');assert.equal(at(s,'tide-pump'),false);assert.equal(at(s,'tide-regulator'),false);assert.equal(s.tideglass.stage,1);assert.equal(s.kit.credits,400);});
test('Drain and refill are gradual bounded motion, with mid-cycle resume restoring the requested stable water state',()=>{const s=fresh();start(s);at(s,'tide-pump');const high=s.tideglass.level;step(s,{},dt);assert.ok(s.tideglass.level<high&&high-s.tideglass.level<.01);const r=createState(saveState(s));assert.equal(r.tideglass.level,TIDE_POOLS[0].low);run(s,10);assert.equal(s.tideglass.level,TIDE_POOLS[0].low);at(s,'tide-pump');run(s,10);assert.equal(s.tideglass.level,high);});
test('Surface swimming, B diving and A surfacing move continuously without firing submerged or losing credits',()=>{const s=fresh();pose(s,132,4,-2);run(s,.5);assert.ok(s.p.water.swimming);assert.ok(!s.p.water.submerged);assert.ok(tideAction(s,'stance'));const old=s.p.y;step(s,{},dt);assert.ok(s.p.y<old&&old-s.p.y<.025);run(s,1.5);assert.ok(s.p.water.submerged);const ammo=s.p.ammo,energy=s.p.energy;assert.equal(fire(s),false);assert.equal(fieldCast(s),false);assert.equal(s.p.ammo,ammo);assert.equal(s.p.energy,energy);assert.ok(jump(s));run(s,1.6);assert.ok(!s.p.water.submerged);assert.equal(s.kit.credits,400);});
test('Swimmer can climb the actual pool ladder continuously from surface depth, then descend back into the basin',()=>{const s=fresh();pose(s,138.4,4.15,7);run(s,.4);assert.equal(nearby(s)?.id,'tide-pool-ladder');assert.ok(combatUse(s));assert.ok(s.p.climb);for(let i=0;i<2000&&s.p.climb;i++)step(s,{moveZ:1},dt);run(s,.4);assert.equal(s.p.y,6);assert.equal(s.p.water.swimming,false);assert.equal(s.stats.rescues,0);assert.equal(nearby(s)?.id,'tide-pool-ladder');interact(s);for(let i=0;i<2000&&s.p.climb;i++)step(s,{moveZ:-1},dt);run(s,.3);assert.ok(s.p.water.swimming);assert.equal(s.stats.rescues,0);});
test('All mission stages, three separate plates, refill gate and once-only rewards survive save/continue',()=>{const s=fresh();start(s);assert.equal(s.checkpoint,'tideglass');assert.ok(at(s,'tide-pump'));run(s,10);assert.ok(at(s,'tide-regulator'));assert.equal(s.tideglass.stage,2);for(const p of TIDE_POINTS.filter(p=>p.kind==='plate'))assert.ok(at(s,p.id));assert.equal(s.kit.credits,500);const middle=createState(saveState(s));assert.equal(middle.tideglass.stage,2);assert.equal(middle.tideglass.plates.length,3);assert.ok(at(s,'tide-install'));at(s,'tide-desk');assert.equal(s.tideglass.stage,3);assert.equal(s.kit.credits,500);run(s,10);at(s,'tide-desk');assert.equal(s.tideglass.stage,4);assert.equal(s.kit.credits,740);at(s,'tide-desk');assert.equal(s.kit.credits,740);const r=createState(saveState(s));assert.equal(r.kit.credits,740);assert.equal(r.tideglass.level,TIDE_POOLS[0].high);assert.ok(TIDE_TASKS.every(t=>r.expedition.flags.includes(t.flag)));});
test('Continuous walking joins both existing garden routes, valve circuit, pumphouse and drained basin steps',()=>{const s=fresh();pose(s,80,6,-12);walk(s,113,12);walk(s,116,12);interact(s);for(const [x,z] of [[118,8],[118,-14]])walk(s,x,z);interact(s);walk(s,118,-18);walk(s,148,-18);interact(s);walk(s,153,-18);walk(s,153,3);walk(s,147,3);walk(s,147,-3);walk(s,148,-7);assert.equal(nearby(s)?.id,'tide-pump');interact(s);run(s,7);walk(s,147,3);walk(s,147,18);walk(s,126,18);walk(s,126,12);walk(s,126,8.6);walk(s,126,-5);assert.ok(Math.abs(s.p.y-1.8)<.05);walk(s,130,-5);walk(s,134,-7);assert.equal(nearby(s)?.id,'tide-regulator');assert.ok(interact(s));walk(s,130,-5);walk(s,126,-5);walk(s,126,8.6);walk(s,126,12);walk(s,116,12);walk(s,116,-17);walk(s,105,-28);assert.equal(s.p.y,6);assert.equal(s.stats.rescues,0);});
test('Rescue clears transient swimming while retaining recovered parts and valve state',()=>{const s=fresh();start(s);at(s,'tide-regulator');pose(s,132,2,-2);run(s,.3);rescue(s);assert.equal(s.p.water.swimming,false);assert.equal(s.p.water.submerged,false);assert.equal(s.tideglass.stage,2);assert.ok(s.tideglass.valves.every(Boolean));assert.deepEqual([s.p.x,s.p.z],[116,12]);});
test('Water controls do not alter distant ground/rail movement or invalid input states',()=>{const s=fresh();assert.equal(tideAction(s,'stance'),false);assert.equal(tidePoolAt(0,0),null);assert.deepEqual(cleanTideglass({stage:Infinity,plates:['tide-plate-0','tide-plate-0','oops'],valves:[1,true],drained:'yes'}),{stage:0,plates:['tide-plate-0'],valves:[false,true],drained:false});});
test('Shader quality, reduced motion and ripple capacity are explicit and no extra framebuffer is allocated',()=>{assert.equal(waterBudget('low').detail,0);assert.equal(waterBudget('balanced',true).caustics,0);assert.equal(waterBudget('balanced',false,true).ripples,0);const water=makePoolWater(TIDE_POOLS[0]);assert.equal(water.depthWrite,false);assert.equal(water.depthTest,true);assert.equal(water.uniforms.ripples.value.length,8);assert.match(water.fragmentShader,/fresnel/);assert.doesNotMatch(water.fragmentShader,/sampler2D/);water.dispose();const shader={uniforms:{},vertexShader:T.ShaderLib.standard.vertexShader,fragmentShader:T.ShaderLib.standard.fragmentShader};patchPoolTiles(shader,{});assert.match(shader.fragmentShader,/#include <lights_physical_fragment>/);});
test('Reservoir scene has bounded geometry and follows water/repaired state without changing save data',()=>{const scene=new T.Scene();scene.fog=new T.Fog('#aacccc',140,500);const original=scene.fog,s=fresh(),art=installTideglassScene({scene});const before=saveState(s),count=()=>{let n=0;scene.traverse(()=>n++);return n;},n=count();for(let i=0;i<60;i++)art.update(s);assert.equal(saveState(s),before);assert.equal(count(),n);s.p.water.submerged=true;art.update(s);assert.notEqual(scene.fog,original);s.p.water.submerged=false;s.tideglass.stage=3;art.update(s);assert.equal(scene.fog,original);assert.equal(art.stats().fountains,true);art.update(s,{reduced:true});assert.equal(art.stats().clock,0);art.dispose();assert.equal(scene.children.length,0);});
test('Ripple activity stays capped even during repeated shots into the pool',()=>{const s=fresh(),core=createTideglass({occupied,groundAt,clearLine,emit(){}});for(let i=0;i<90;i++)core.impact(s,{x:132,y:10,z:0},{x:132,y:0,z:0});assert.equal(s.tideglass.ripples.length,8);run(s,4);assert.equal(s.tideglass.ripples.length,0);});
