import {VERSION,Run,BowState,vec,sub,unit,mul,add,clamp,distance,standingClear,slide,gateBoxes,prediction,seedText,random,hash} from './core.mjs';
const A=window.AFRAME,T=A.THREE,$=id=>document.getElementById(id),scene=$('scene'),rig=$('rig').object3D,head=$('head').object3D;
const hands={left:$('left-hand').object3D,right:$('right-hand').object3D};
const colors={stone:0x627b80,wall:0x85959a,cover:0x5e7376,column:0xb1aaa0,wood:0x725c42,gold:0xdcb979,mint:0x8ce9d4,ink:0x193642,ember:0xf8b887};
const settings={hand:'left',smooth:false,sound:false};try{const v=JSON.parse(localStorage.getItem('gloamward.settings.v1')||'null');if(v){settings.hand=v.hand==='right'?'right':'left';settings.smooth=!!v.smooth;settings.sound=!!v.sound;}}catch{}
let record={best:0,runs:0};try{const v=JSON.parse(localStorage.getItem('gloamward.record.v1')||'null');if(v){record.best=clamp(Number(v.best)||0,0,999999);record.runs=clamp(Number(v.runs)||0,0,99999);}}catch{}
const saveSettings=()=>{try{localStorage.setItem('gloamward.settings.v1',JSON.stringify(settings));}catch{}};
const materials=new Map();function material(color,emissive=false){const k=color+':'+emissive;if(!materials.has(k))materials.set(k,new T.MeshStandardMaterial({color,roughness:.75,metalness:color===colors.gold?.55:.08,emissive:emissive?color:0,emissiveIntensity:emissive?.55:0}));return materials.get(k);}
const geometries={box:new T.BoxGeometry(1,1,1),cylinder:new T.CylinderGeometry(1,1,1,10),cone:new T.ConeGeometry(1,1,8),sphere:new T.SphereGeometry(1,10,7)};
function mesh(kind,color,parent,position,scale,rotation=0,glow=false){const m=new T.Mesh(geometries[kind],material(color,glow));m.position.set(...position);m.scale.set(...scale);m.rotation.y=rotation;parent.add(m);return m;}
function line(points,color,parent){const g=new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p)));const l=new T.Line(g,new T.LineBasicMaterial({color}));parent.add(l);return l;}
function label(text,width,height,color='#e6dfbd',background='#173440'){const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=background;ctx.fillRect(0,0,512,256);ctx.strokeStyle='#bca46e';ctx.lineWidth=8;ctx.strokeRect(8,8,496,240);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';const rows=String(text).split('\n');ctx.font='600 '+Math.min(46,185/rows.length)+'px Georgia';rows.forEach((s,i)=>ctx.fillText(s,256,128+(i-(rows.length-1)/2)*52,460));const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(width,height),new T.MeshBasicMaterial({map:tex,transparent:false,side:T.DoubleSide}));m.userData={canvas:c,context:ctx,texture:tex};return m;}
function disposeGroup(group){group.traverse(o=>{if(o.isMesh&&o.geometry&&!Object.values(geometries).includes(o.geometry))o.geometry.dispose();if(o.material?.map){o.material.map.dispose();o.material.dispose();}if(o.isLine)o.geometry?.dispose();});group.removeFromParent();}
class StaticBatch{
 constructor(parent){this.parent=parent;this.items=new Map();}
 add(kind,color,p,s,yaw=0){const k=kind+':'+color;if(!this.items.has(k))this.items.set(k,{kind,color,a:[]});this.items.get(k).a.push({p,s,yaw});}
 finish(){const mat=new T.Matrix4(),pos=new T.Vector3(),q=new T.Quaternion(),scale=new T.Vector3();for(const {kind,color,a}of this.items.values()){const m=new T.InstancedMesh(geometries[kind],material(color),a.length);for(let i=0;i<a.length;i++){const v=a[i];pos.set(...v.p);q.setFromAxisAngle(new T.Vector3(0,1,0),v.yaw);scale.set(...v.s);mat.compose(pos,q,scale);m.setMatrixAt(i,mat);}m.computeBoundingSphere();this.parent.add(m);}}
}
function bowModel(){const g=new T.Group();mesh('cylinder',colors.wood,g,[0,0,0],[.035,.18,.035]);for(const side of[-1,1]){const curve=new T.CatmullRomCurve3([new T.Vector3(0,side*.06,0),new T.Vector3(.015,side*.27,-.12),new T.Vector3(0,side*.5,-.04),new T.Vector3(0,side*.58,.035)]);g.add(new T.Mesh(new T.TubeGeometry(curve,14,.015,5,false),material(colors.gold)));}const string=line([[0,.58,.035],[0,0,0],[0,-.58,.035]],0xd4eee2,g);g.userData.string=string;return g;}
function arrowModel(type){const g=new T.Group(),color=type==='hostile'?0xee927e:type==='teleport'?0x85eae6:type==='shatter'?0xffc16b:type==='snare'?0xbcabf0:0xe2d9b2;mesh('cylinder',color,g,[0,0,0],[.012,.63,.012]);mesh('cone',color,g,[0,.36,0],[.038,.10,.038],0,type!=='normal');mesh('box',0xc6d2c5,g,[0,-.27,0],[.06,.075,.008]);mesh('box',0xc6d2c5,g,[0,-.27,0],[.008,.075,.06]);return g;}
function enemyModel(e){const g=new T.Group(),s=e.type==='keeper'?1.3:1;g.scale.setScalar(s);mesh('cone',0x314d60,g,[0,.65,0],[.4,1.18,.28]);mesh('box',0x6e8a89,g,[0,1.17,0],[.54,.5,.3]);mesh('sphere',0xb6c6bc,g,[0,1.58,0],[.21,.24,.20]);mesh('box',colors.ink,g,[0,1.60,.19],[.28,.10,.055]);mesh('box',colors.mint,g,[0,1.61,.23],[.18,.035,.017],0,true);mesh('cone',colors.gold,g,[0,1.98,0],[.27,.53,.24]);for(const side of[-1,1]){mesh('cylinder',0x526d75,g,[side*.33,1.05,0],[.07,.58,.07]);mesh('sphere',colors.gold,g,[side*.36,.79,0],[.09,.08,.09]);}const weapon=mesh('cone',colors.mint,g,[.39,1.16,.32],[.06,.52,.06],0,true);weapon.rotation.x=Math.PI/2;g.userData.weapon=weapon;return g;}
class Gloamward{
 constructor(){
  this.run=new Run(seedText(new URLSearchParams(location.search).get('seed')||'GREYBELL-01'));this.paused=false;this.vr=false;this.bowState=new BowState();this.keys=new Set();this.yaw=0;this.pitch=-.035;this.holding=false;this.pull=0;this.teleportHeld=false;this.arrow=0;this.types=['normal','shatter','snare'];this.elapsed=0;this.acc=0;this.noticeTime=0;this.xrPrevious={trigger:true,button4:true,button5:true};this.turnArmed=false;this.world=null;this.enemyMeshes=new Map();this.arrowMeshes=new Map();this.effects=[];this.menuMeshes=[];this.menuGroup=new T.Group();scene.object3D.add(this.menuGroup);this.menuGroup.visible=false;this.headPosition=new T.Vector3();this.headRotation=new T.Quaternion();this.raycaster=new T.Raycaster();this.temp=new T.Vector3();this.bow=bowModel();this.desktopBow=bowModel();head.add(this.desktopBow);this.desktopBow.position.set(-.28,-.27,-.54);this.desktopBow.scale.setScalar(.64);this.preview=line(Array.from({length:61},()=>[0,0,0]),colors.mint,scene.object3D);this.preview.visible=false;this.preview.frustumCulled=false;this.pad=new T.Mesh(new T.RingGeometry(.32,.43,24),new T.MeshBasicMaterial({color:colors.mint,side:T.DoubleSide}));this.pad.rotation.x=-Math.PI/2;scene.object3D.add(this.pad);this.pad.visible=false;
  for(const side of['left','right']){mesh('cylinder',colors.ink,hands[side],[0,0,0],[.022,.1,.022]);mesh('sphere',colors.gold,hands[side],[0,.04,0],[.024,.015,.024]);hands[side].visible=false;}
  this.menuLine=line([[0,0,0],[0,0,-3]],0xa7dfd0,scene.object3D);this.menuLine.visible=false;this.hudPanel=label('VITALITY 100\nSTANDARD / 6',.40,.20);this.hudPanel.position.set(0,.8,.05);this.bow.add(this.hudPanel);this.build();this.bind();this.menu('ready');this.updateSupport();$('loading').hidden=true;
  window.GloamwardDemo=Object.freeze({version:VERSION,snapshot:()=>({state:this.run.state,paused:this.paused,seed:this.run.world.seed,hp:this.run.hp,room:this.run.wave,cleared:[...this.run.cleared],shots:this.run.shots,hits:this.run.hits,score:this.run.score,projectiles:this.run.projectiles.length,activeEnemies:this.run.enemies.filter(e=>e.alive&&e.room===this.run.wave).length,vr:this.vr,model:'A-Frame '+A.version}),observe:()=>JSON.parse(JSON.stringify({position:{x:this.headPosition.x,y:this.headPosition.y,z:this.headPosition.z},yaw:this.yaw,pitch:this.pitch,pull:this.pull,paused:this.paused,room:this.run.wave,rooms:this.run.world.rooms,exit:this.run.world.exit,obstacles:this.run.world.obstacles,enemies:this.run.enemies,arrows:this.run.projectiles,bow:{nocked:this.bowState.nocked,armed:this.bowState.armed,pull:this.bowState.pull},rigYaw:rig.rotation.y,menu:this.menuGroup.visible,settings})),controls:'Two-handed tracked bow; desktop fallback; no external accounts.'});
 }
 build(){
  if(this.world)disposeGroup(this.world);for(const a of this.arrowMeshes.values())disposeGroup(a);this.arrowMeshes.clear();this.enemyMeshes.clear();this.world=new T.Group();this.world.name='Gloamward seeded courtyard';scene.object3D.add(this.world);const batch=new StaticBatch(this.world),w=this.run.world,rng=random(hash(w.seed)+31);
  for(const f of w.floors){batch.add('box',f.bridge?0x7f8580:0x82948f,[f.x,-.34,f.z],[f.w,.68,f.d]);for(let x=-f.w/2+1;x<f.w/2;x+=2)for(let z=-f.d/2+1;z<f.d/2;z+=2)batch.add('box',((x+z)%4)?0x879996:0x7a8d8b,[f.x+x,.008,f.z+z],[1.93,.014,1.93]);if(!f.bridge){for(let j=0;j<8;j++)batch.add('cone',0x556e75,[f.x+(rng()-.5)*f.w,-2,f.z+(rng()-.5)*f.d],[2,5,1.5],rng()*6);}}
  for(const o of w.obstacles){const size=[o.max.x-o.min.x,o.max.y-o.min.y,o.max.z-o.min.z],pos=[(o.min.x+o.max.x)/2,(o.min.y+o.max.y)/2,(o.min.z+o.max.z)/2];batch.add('box',colors[o.kind]||colors.stone,pos,size);if(o.kind==='cover')batch.add('box',0x91a781,[pos[0],o.max.y+.04,pos[2]],[size[0]+.12,.08,size[2]+.12]);}
  for(const r of w.rooms){
   for(const side of[-1,1])for(const dz of[-8,8]){const x=r.x+side*9,z=r.z+dz;batch.add('cylinder',0x8c9891,[x,3.5,z],[.62,7,.62]);batch.add('cone',0x355e68,[x,8,z],[1.25,3,1.25],Math.PI/4);batch.add('cylinder',colors.gold,[x,6.7,z],[.72,.13,.72]);}
   for(const dz of[-9.7,9.7]){for(const side of[-1,1])batch.add('box',colors.column,[r.x+side*3.2,2.4,r.z+dz],[.6,4.8,.8]);const curve=new T.CatmullRomCurve3([new T.Vector3(r.x-3.2,4.7,r.z+dz),new T.Vector3(r.x-2,6.1,r.z+dz),new T.Vector3(r.x,7.3,r.z+dz),new T.Vector3(r.x+2,6.1,r.z+dz),new T.Vector3(r.x+3.2,4.7,r.z+dz)]);this.world.add(new T.Mesh(new T.TubeGeometry(curve,20,.28,5,false),material(colors.column)));}
   for(let j=0;j<16;j++){const side=j%2?1:-1,x=r.x+side*(7.4+rng()*1.3),z=r.z+(rng()-.5)*15;batch.add('cone',0x426e69,[x,.2,z],[.35,.55,.28],rng()*6);}
   const sign=label(r.name.toUpperCase()+'\n'+String(r.id+1).padStart(2,'0')+' / THE ASCENT',3.3,1.05);sign.position.set(r.x,4.1,r.z-9.3);this.world.add(sign);
  }
  // Distant silhouettes create depth but do not masquerade as reachable floors.
  for(let i=0;i<30;i++){const side=i%2?1:-1,x=side*(22+rng()*40),z=15-rng()*100,h=7+rng()*16;batch.add('box',0x6f8b97,[x,h/2-2,z],[4,h,4]);batch.add('cone',0x4f7587,[x,h-1,z],[3,6,3],Math.PI/4);}
  batch.finish();this.gates=[];for(let i=0;i<2;i++){const r=w.rooms[i],g=new T.Group();g.position.set(r.x,0,r.z-9.8);for(let j=-4;j<=4;j++)mesh('cylinder',colors.gold,g,[j*.56,1.5,0],[.04,3,.04]);const sign=label('CLEAR THE COURTYARD',2.7,.55);sign.position.set(0,3.15,.13);g.add(sign);this.world.add(g);this.gates.push(g);}
  const portal=new T.Group();portal.position.set(w.exit.x,0,w.exit.z);this.world.add(portal);for(const side of[-1,1])mesh('box',colors.gold,portal,[side*1.1,1.4,0],[.22,2.8,.30]);mesh('box',colors.gold,portal,[0,2.8,0],[2.4,.2,.3]);this.exitGlow=mesh('box',colors.mint,portal,[0,1.4,0],[2,2.6,.055],0,true);this.exitGlow.visible=false;
  for(const e of this.run.enemies){const m=enemyModel(e);m.position.set(e.pos.x,0,e.pos.z);this.world.add(m);this.enemyMeshes.set(e.id,m);}
  rig.position.set(w.rooms[0].x,0,6);rig.rotation.set(0,0,0);head.rotation.set(this.pitch,0,0,'YXZ');this.yaw=0;this.refreshBowHand();
 }
 refreshBowHand(){hands[settings.hand].add(this.bow);this.bow.position.set(0,.045,-.02);this.bow.rotation.set(0,0,0);this.bowState.cancel();}
 async updateSupport(){const btn=$('vr-btn');try{const okay=!!navigator.xr&&window.isSecureContext&&await navigator.xr.isSessionSupported('immersive-vr');btn.disabled=!okay;btn.textContent=okay?'Enter VR preview':'VR unavailable';btn.title=okay?'Experimental Quest/WebXR mode; physical hardware testing remains open.':'Use a WebXR headset browser over HTTPS or localhost.';}catch{btn.textContent='VR unavailable';}}
 notice(text){$('notice').textContent=text;this.noticeTime=3.3;}
 sound(freq=420){if(!settings.sound)return;try{this.audio??=new(window.AudioContext||window.webkitAudioContext)();if(this.audio.state==='suspended')this.audio.resume();const a=this.audio,t=a.currentTime,o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*.55,t+.14);g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(.065,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+.17);o.connect(g).connect(a.destination);o.start();o.stop(t+.2);o.onended=()=>{o.disconnect();g.disconnect();};}catch{}}
 cancelInput(){this.holding=false;this.pull=0;this.keys.clear();this.teleportHeld=false;this.bowState.cancel();this.xrPrevious={trigger:true,button4:true,button5:true};this.turnArmed=false;this.preview.visible=this.pad.visible=false;}
 start(fresh=false){if(fresh){this.run.reset(seedText($('seed').value));this.build();}this.run.start();this.paused=false;this.cancelInput();$('menu').hidden=true;this.menuGroup.visible=false;this.menuLine.visible=false;this.lastMenu='';}
 pause(){if(this.run.state!=='playing')return;this.paused=!this.paused;this.cancelInput();if(this.paused)this.menu('paused');else{$('menu').hidden=true;this.menuGroup.visible=false;this.lastMenu='';}}
 menu(kind){
  this.cancelInput();this.lastMenu=kind;let title='Gloamward',copy='Master the bow. Cross three seeded courtyards. Clear each encounter, choose a run upgrade, and find the final gate.',actions=[];
  if(kind==='ready')actions=[['Enter the courtyard',()=>this.start(true)],['New seed',()=>{$('seed').value='RUN-'+Math.floor(Math.random()*0xffffff).toString(36).toUpperCase();this.run.reset($('seed').value);this.build();this.menu('ready');}]];
  if(kind==='paused'){title='Take a breath';copy='The simulation is paused. Release both triggers before continuing.';actions=[['Resume',()=>{this.paused=false;this.start(false);}],['Restart this seed',()=>this.start(true)]];}
  if(kind==='upgrade'){title='A moment of renewal';copy='The courtyard is clear. Choose one upgrade for this run; the next gate is open.';actions=[['Heartwood · +15 maximum vitality',()=>{this.run.pick('vitality');this.start(false);}],['Keen string · +16% arrow damage',()=>{this.run.pick('power');this.start(false);}],['Deep quiver · +3 special charges',()=>{this.run.pick('quiver');this.start(false);}]];}
  if(kind==='dead'||kind==='won'){title=kind==='won'?'The last gate opens':'The courtyard keeps its secrets';copy=`${this.run.score} points · ${this.run.hits}/${this.run.shots} arrows connected · ${Math.round(this.run.time)} seconds. ${kind==='won'?'Three courts crossed. A new seed changes the next expedition.':'Try another route through cover, or use teleport arrows to reposition.'}`;actions=[['Retry this seed',()=>this.start(true)],['New expedition',()=>{$('seed').value='RUN-'+Math.floor(Math.random()*0xffffff).toString(36).toUpperCase();this.start(true);}]];}
  $('menu-title').textContent=title;$('menu-copy').textContent=copy;$('seed-label').hidden=kind!=='ready';$('menu-actions').replaceChildren();actions.forEach(([text,fn])=>{const b=document.createElement('button');b.textContent=text;b.onclick=fn;$('menu-actions').append(b);});$('menu').hidden=false;
  this.makeXRMenu(title,actions);if(!this.vr)setTimeout(()=>$('menu-actions').querySelector('button')?.focus(),0);
 }
 makeXRMenu(title,actions){for(const child of [...this.menuGroup.children])disposeGroup(child);this.menuMeshes=[];const board=label(title.toUpperCase()+'\n'+(this.lastMenu==='upgrade'?'CHOOSE YOUR UPGRADE':'GLOAMWARD / ARCHERY'),1.25,.42);board.position.set(0,.40,0);this.menuGroup.add(board);
  const all=actions.concat([[`Bow hand: ${settings.hand} · swap`,()=>{settings.hand=settings.hand==='left'?'right':'left';$('handedness').value=settings.hand;saveSettings();this.refreshBowHand();this.menu(this.lastMenu);}],[this.vr?'Exit VR':'VR preview',()=>{if(this.vr)scene.exitVR();}]]);
  all.forEach(([name,fn],i)=>{const m=label(name,1.15,.17,'#e5ead4','#254b59');m.position.set(0,.08-i*.20,.015);m.userData.action=fn;this.menuGroup.add(m);this.menuMeshes.push(m);});this.menuGroup.visible=this.vr;this.menuPositionPending=true;
 }
 bind(){
  $('pause-btn').onclick=()=>this.pause();$('vr-btn').onclick=()=>{this.cancelInput();scene.enterVR().catch(e=>this.notice('VR session was not started: '+e.message));};
  $('handedness').value=settings.hand;$('smooth').checked=settings.smooth;$('sound').checked=settings.sound;
  $('handedness').onchange=e=>{settings.hand=e.target.value;this.refreshBowHand();saveSettings();};$('smooth').onchange=e=>{settings.smooth=e.target.checked;saveSettings();};$('sound').onchange=e=>{settings.sound=e.target.checked;saveSettings();if(settings.sound)this.sound();};
  window.addEventListener('keydown',e=>{if(this.vr||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='KeyP'||e.code==='Escape'){if(!e.repeat)this.pause();return;}if(this.paused||this.run.state!=='playing')return;this.keys.add(e.code);if(e.code==='KeyF'&&!e.repeat)this.holding=true;if(e.code==='KeyQ'&&!e.repeat)this.cycle();});
  window.addEventListener('keyup',e=>{this.keys.delete(e.code);if(e.code==='KeyF'&&this.holding)this.releaseDesktop();});
  let drag=null;scene.canvas.addEventListener('contextmenu',e=>e.preventDefault());scene.canvas.addEventListener('pointerdown',e=>{if(this.vr||this.paused||this.run.state!=='playing')return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};scene.canvas.setPointerCapture(e.pointerId);if(e.button===0&&e.pointerType!=='touch')this.holding=true;});scene.canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId||this.vr)return;this.yaw-=(e.clientX-drag.x)*.003;this.pitch=clamp(this.pitch-(e.clientY-drag.y)*.003,-1.20,1.20);drag.x=e.clientX;drag.y=e.clientY;});
  scene.canvas.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId)drag=null;if(e.button===0&&this.holding)this.releaseDesktop();});scene.canvas.addEventListener('pointercancel',()=>{drag=null;this.cancelInput();});
  for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();this.keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>this.keys.delete(b.dataset.key));}
  const hold=(button,down,up)=>{button.onpointerdown=e=>{e.preventDefault();down();button.setPointerCapture(e.pointerId);};button.onpointerup=up;button.onpointercancel=()=>this.cancelInput();};hold($('touch-draw'),()=>this.holding=true,()=>this.releaseDesktop());hold($('touch-teleport'),()=>{this.teleportHeld=true;this.holding=true;},()=>{this.releaseDesktop();this.teleportHeld=false;});$('touch-arrow').onclick=()=>this.cycle();
  window.addEventListener('blur',()=>{this.cancelInput();if(!this.vr&&this.run.state==='playing'&&!this.paused)this.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.cancelInput();if(this.run.state==='playing'){this.paused=true;this.menu('paused');}}});
  scene.addEventListener('enter-vr',()=>{this.vr=true;document.body.classList.add('xr');this.cancelInput();this.desktopBow.visible=false;this.bow.visible=true;this.menuGroup.visible=this.run.state!=='playing'||this.paused;this.menuPositionPending=true;const session=scene.renderer.xr.getSession();session?.addEventListener('visibilitychange',()=>{if(session.visibilityState!=='visible'&&this.run.state==='playing'){this.paused=true;this.menu('paused');}});});
  scene.addEventListener('exit-vr',()=>{this.vr=false;document.body.classList.remove('xr');this.cancelInput();hands.left.visible=hands.right.visible=false;this.menuLine.visible=this.menuGroup.visible=false;head.rotation.set(this.pitch,this.yaw,0,'YXZ');if(this.run.state==='playing'){this.paused=true;this.menu('paused');}else this.menu(this.run.state);});
 }
 cycle(){this.arrow=(this.arrow+1)%this.types.length;this.notice(['Standard arrows','Shatter arrows · area impact','Snare arrows · slow a target'][this.arrow]);}
 releaseDesktop(){if(this.vr||!this.holding)return;const power=this.pull;this.holding=false;this.pull=0;if(this.paused||this.run.state!=='playing'||power<.12)return;head.getWorldPosition(this.headPosition);const direction=new T.Vector3(0,0,-1).applyQuaternion(head.getWorldQuaternion(new T.Quaternion()));const origin=this.headPosition.clone().addScaledVector(direction,.45);this.shoot(origin,direction,power,this.teleportHeld||this.keys.has('KeyT')?'teleport':this.types[this.arrow]);}
 shoot(origin,direction,power,type){if(this.run.fire(vec(origin.x,origin.y,origin.z),vec(direction.x,direction.y,direction.z),power,type))this.sound(type==='teleport'?600:300+power*130);}
 xrInput(dt){
  const xr=scene.renderer.xr,frame=xr.getFrame?.()||scene.frame,session=xr.getSession(),ref=xr.getReferenceSpace();if(!frame||!session||!ref){this.cancelInput();hands.left.visible=hands.right.visible=false;return;}
  const viewer=frame.getViewerPose(ref);if(!viewer){this.cancelInput();hands.left.visible=hands.right.visible=false;return;}rig.updateWorldMatrix(true,false);this.headPosition.set(viewer.transform.position.x,viewer.transform.position.y,viewer.transform.position.z).applyMatrix4(rig.matrixWorld);this.headRotation.copy(rig.getWorldQuaternion(new T.Quaternion())).multiply(new T.Quaternion(viewer.transform.orientation.x,viewer.transform.orientation.y,viewer.transform.orientation.z,viewer.transform.orientation.w));
  const sources={};for(const src of session.inputSources){if(!['left','right'].includes(src.handedness)||!src.gamepad)continue;const pose=frame.getPose(src.gripSpace||src.targetRaySpace,ref);if(!pose||pose.emulatedPosition)continue;const o=hands[src.handedness];o.position.set(pose.transform.position.x,pose.transform.position.y,pose.transform.position.z);o.quaternion.set(pose.transform.orientation.x,pose.transform.orientation.y,pose.transform.orientation.z,pose.transform.orientation.w);o.visible=true;o.updateWorldMatrix(true,false);sources[src.handedness]=src;}
  for(const side of['left','right'])if(!sources[side])hands[side].visible=false;
  const drawSide=settings.hand==='left'?'right':'left',draw=sources[drawSide],bow=sources[settings.hand];const buttons=draw?.gamepad.buttons||[];const trigger=!!buttons[0]?.pressed,squeeze=!!buttons[1]?.pressed,b4=!!buttons[4]?.pressed,b5=!!buttons[5]?.pressed;
  if(!draw||!bow){this.bowState.cancel();this.xrPrevious={trigger:true,button4:true,button5:true};this.preview.visible=this.pad.visible=false;this.menuLine.visible=false;return;}
  const changed=trigger&&!this.xrPrevious.trigger;
  if(this.menuGroup.visible){
   if(this.menuPositionPending){const dir=new T.Vector3(0,0,-1).applyQuaternion(this.headRotation);dir.y=0;dir.normalize();this.menuGroup.position.copy(this.headPosition).addScaledVector(dir,1.65);this.menuGroup.position.y=this.headPosition.y-.03;this.menuGroup.lookAt(this.headPosition.x,this.menuGroup.position.y,this.headPosition.z);this.menuGroup.updateMatrixWorld(true);this.menuPositionPending=false;}
   const origin=hands[drawSide].getWorldPosition(new T.Vector3()),direction=new T.Vector3(0,0,-1).applyQuaternion(hands[drawSide].getWorldQuaternion(new T.Quaternion()));this.raycaster.set(origin,direction);const hits=this.raycaster.intersectObjects(this.menuMeshes,false);for(const m of this.menuMeshes)m.material.color.setHex(hits[0]?.object===m?0xffdd91:0xffffff);const target=hits[0]?.point||origin.clone().addScaledVector(direction,2.5);this.updateLine(this.menuLine,[origin,target]);this.menuLine.visible=true;if(changed&&hits[0])hits[0].object.userData.action();this.bowState.cancel();
  }else if(this.run.state==='playing'&&!this.paused){
   this.menuLine.visible=false;const pos=hands[settings.hand].getWorldPosition(new T.Vector3()),hand=hands[drawSide].getWorldPosition(new T.Vector3());const shot=this.bowState.update({valid:true,pressed:trigger,bow:vec(pos.x,pos.y+.04,pos.z),hand:vec(hand.x,hand.y,hand.z)});this.pull=this.bowState.pull;
   if(shot)this.shoot(new T.Vector3(shot.origin.x,shot.origin.y,shot.origin.z),new T.Vector3(shot.direction.x,shot.direction.y,shot.direction.z),shot.power,squeeze?'teleport':this.types[this.arrow]);
   const local=this.bow.worldToLocal(hand.clone());this.updateLine(this.bow.userData.string,[new T.Vector3(0,.58,.035),this.bowState.nocked?local:new T.Vector3(0,0,0),new T.Vector3(0,-.58,.035)]);
   if(squeeze&&this.bowState.nocked){const dir=unit(sub(vec(pos.x,pos.y+.04,pos.z),vec(hand.x,hand.y,hand.z)));this.previewTeleport(vec(pos.x,pos.y+.04,pos.z),dir,12+this.pull*8);}else{this.preview.visible=false;this.pad.visible=false;}
   if(b4&&!this.xrPrevious.button4)this.cycle();if(b5&&!this.xrPrevious.button5){this.paused=true;this.menu('paused');}
   const right=sources.right?.gamepad,left=sources.left?.gamepad,rx=right?.axes.at(-2)||0;if(Math.abs(rx)<.3)this.turnArmed=true;if(Math.abs(rx)>.72&&this.turnArmed){this.turnArmed=false;this.snapTurn(rx>0?-Math.PI/6:Math.PI/6);}
   if(settings.smooth&&left){const ax=left.axes.at(-2)||0,az=left.axes.at(-1)||0;if(Math.hypot(ax,az)>.19)this.move(ax,az,dt,1.75);}
  }
  this.xrPrevious={trigger,button4:b4,button5:b5};
 }
 snapTurn(angle){const headBefore=this.headPosition.clone();rig.rotation.y+=angle;rig.updateMatrixWorld(true);const local=headBefore.clone();rig.rotation.y-=angle;rig.updateMatrixWorld(true);rig.worldToLocal(local);rig.rotation.y+=angle;rig.updateMatrixWorld(true);const after=local.applyMatrix4(rig.matrixWorld);rig.position.x+=headBefore.x-after.x;rig.position.z+=headBefore.z-after.z;this.bowState.cancel();this.preview.visible=this.pad.visible=false;}
 move(x,z,dt,speed){const forward=new T.Vector3(0,0,-1).applyQuaternion(this.vr?this.headRotation:head.getWorldQuaternion(new T.Quaternion()));forward.y=0;forward.normalize();const right=new T.Vector3(-forward.z,0,forward.x),v=right.multiplyScalar(x).addScaledVector(forward,-z);if(v.length()>1)v.normalize();const feet=vec(this.headPosition.x,0,this.headPosition.z),target=slide(this.run.world,feet,vec(v.x*speed*dt,0,v.z*speed*dt),this.run.wave);const gates=gateBoxes(this.run.world,this.run.cleared);const blocked=gates.some(b=>target.x>b.min.x-.3&&target.x<b.max.x+.3&&target.z>b.min.z-.3&&target.z<b.max.z+.3);if(!blocked){rig.position.x+=target.x-feet.x;rig.position.z+=target.z-feet.z;}}
 updateLine(l,points){const a=l.geometry.getAttribute('position');if(a.count!==points.length){l.geometry.dispose();l.geometry=new T.BufferGeometry().setFromPoints(points);}else{points.forEach((p,i)=>a.setXYZ(i,p.x,p.y,p.z));a.needsUpdate=true;l.geometry.computeBoundingSphere();}}
 previewTeleport(origin,direction,speed){const p=prediction(this.run.world,origin,direction,speed,gateBoxes(this.run.world,this.run.cleared),90),points=p.points.map(q=>new T.Vector3(q.x,q.y,q.z));this.updateLine(this.preview,points);this.preview.visible=true;const valid=p.hit?.kind==='floor'&&distance(vec(this.headPosition.x,this.headPosition.y,this.headPosition.z),p.hit.position)<=23&&standingClear(this.run.world,p.hit.position,this.run.wave);this.preview.material.color.setHex(valid?colors.mint:0xe79882);this.pad.visible=valid;if(valid)this.pad.position.set(p.hit.position.x,.025,p.hit.position.z);}
 teleport(p){if(!standingClear(this.run.world,p,this.run.wave))return;rig.position.x+=p.x-this.headPosition.x;rig.position.z+=p.z-this.headPosition.z;this.bowState.cancel();this.preview.visible=this.pad.visible=false;this.notice('Teleport landed');this.sound(670);}
 tick(dt){
  dt=clamp(dt/1000,0,.10);this.elapsed+=dt;const oldState=this.run.state;
  if(this.vr)this.xrInput(dt);else{head.rotation.set(this.pitch,this.yaw,0,'YXZ');head.getWorldPosition(this.headPosition);head.getWorldQuaternion(this.headRotation);hands.left.visible=hands.right.visible=false;this.bow.visible=false;this.desktopBow.visible=this.run.state==='playing'&&!this.paused;
   if(this.run.state==='playing'&&!this.paused){this.yaw+=((this.keys.has('ArrowLeft')?1:0)-(this.keys.has('ArrowRight')?1:0))*dt*1.25;this.pitch=clamp(this.pitch+((this.keys.has('ArrowUp')?1:0)-(this.keys.has('ArrowDown')?1:0))*dt*.9,-1.2,1.2);this.move((this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0),dt,this.keys.has('ShiftLeft')?3.8:2.9);if(this.holding)this.pull=clamp(this.pull+dt/1.15,0,1);const n=new T.Vector3(0,0,this.pull*.57);this.updateLine(this.desktopBow.userData.string,[new T.Vector3(0,.58,.035),n,new T.Vector3(0,-.58,.035)]);if(this.holding&&(this.keys.has('KeyT')||this.teleportHeld)){const dir=new T.Vector3(0,0,-1).applyQuaternion(this.headRotation);this.previewTeleport(vec(this.headPosition.x+dir.x*.45,this.headPosition.y+dir.y*.45,this.headPosition.z+dir.z*.45),vec(dir.x,dir.y,dir.z),12+this.pull*8);}else this.preview.visible=this.pad.visible=false;}
  }
  if(!this.paused&&this.run.state==='playing'){this.acc+=dt;let loops=0;while(this.acc>=1/60&&loops++<6){this.run.step(1/60,vec(this.headPosition.x,this.headPosition.y,this.headPosition.z));this.acc-=1/60;}}else this.acc=0;
  for(const e of this.run.events.splice(0)){
   if(e.type==='teleport')this.teleport(e.position);if(e.type==='hit')this.sound(700);if(e.type==='hurt'){this.notice('Hit — use cover or teleport to reposition');this.sound(130);}if(e.type==='empty')this.notice('No special charges. Standard arrows are unlimited.');if(e.type==='teleport-miss')this.notice('No safe floor at that impact. The teleport arrow must land on a clear courtyard.');
   if(e.type==='won'||e.type==='dead'){record.runs++;record.best=Math.max(record.best,this.run.score);try{localStorage.setItem('gloamward.record.v1',JSON.stringify(record));}catch{}}
  }
  if(this.run.state!==oldState&&['upgrade','won','dead'].includes(this.run.state))this.menu(this.run.state);
  for(const e of this.run.enemies){const m=this.enemyMeshes.get(e.id);m.visible=e.alive&&e.room<=this.run.wave;if(m.visible){m.position.set(e.pos.x,Math.sin(this.elapsed*1.9+e.phase)*.035,e.pos.z);m.lookAt(this.headPosition.x,m.position.y,this.headPosition.z);m.userData.weapon.scale.z=e.cooldown<.7?1.45:1;}}
  this.gates.forEach((g,i)=>g.visible=!this.run.cleared.has(i));this.exitGlow.visible=this.run.cleared.size===3;
  const alive=new Set(this.run.projectiles.map(p=>p.id));for(const [id,m]of this.arrowMeshes)if(!alive.has(id)){disposeGroup(m);this.arrowMeshes.delete(id);}for(const arrow of this.run.projectiles){let m=this.arrowMeshes.get(arrow.id);if(!m){m=arrowModel(arrow.type);scene.object3D.add(m);this.arrowMeshes.set(arrow.id,m);}m.position.set(arrow.pos.x,arrow.pos.y,arrow.pos.z);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),new T.Vector3(arrow.velocity.x,arrow.velocity.y,arrow.velocity.z).normalize());}
  $('health').textContent=Math.round(this.run.hp);$('health-bar').style.transform=`scaleX(${this.run.hp/this.run.maxHP})`;$('arrow-label').textContent=['Standard','Shatter','Snare'][this.arrow];$('charge').textContent=this.run.charge+' special charges';$('room-label').textContent=this.run.world.rooms[this.run.wave]?.name||'The last gate';$('draw-bar').style.transform=`scaleX(${this.pull})`;const enemies=this.run.enemies.filter(e=>e.alive&&e.room===this.run.wave).length;$('objective').textContent=this.run.cleared.size===3?'Enter the glowing final gate.':`${enemies} sentinels remain · ${this.run.score} points`;
  if(this.noticeTime>0){this.noticeTime-=dt;if(this.noticeTime<=0)$('notice').textContent='';}
  const hudText=`VITALITY ${Math.round(this.run.hp)}\n${this.types[this.arrow].toUpperCase()} / ${this.run.charge}`;
  if(this.vr&&this.lastHUDText!==hudText){this.lastHUDText=hudText;const {context:ctx,texture}=this.hudPanel.userData;ctx.fillStyle='#173440';ctx.fillRect(0,0,512,256);ctx.strokeStyle='#bca46e';ctx.lineWidth=8;ctx.strokeRect(8,8,496,240);ctx.fillStyle='#e6dfbd';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 43px Georgia';hudText.split('\n').forEach((line,i)=>ctx.fillText(line,256,99+i*58,460));texture.needsUpdate=true;}

 }
}
A.registerComponent('gloamward-game',{init(){this.app=new Gloamward();},tick(t,dt){if(dt)this.app.tick(dt);},remove(){this.app?.cancelInput();}});
if(scene.hasLoaded)scene.setAttribute('gloamward-game','');else scene.addEventListener('loaded',()=>scene.setAttribute('gloamward-game',''),{once:true});
