import {VERSION,RADIUS,WORLD,at,add,mul,norm,dot,cross,point,initial,step,nearest,interact,switchRide,readSave,saveData,SAVE_KEY,target,distance} from './model.mjs';
import {createScene} from './scene.mjs';
const $=id=>document.getElementById(id);let saved=null,storage=true;try{saved=readSave(localStorage.getItem(SAVE_KEY));}catch{storage=false;}
let s=initial(saved),started=false,paused=false,view,keys=new Set(),jump=false,stick=[0,0],boost=false,orbitDrag=null,last=0,acc=0,titleTime=0,viewMode=0,waypoint=null,saveStamp='';
document.body.classList.add('title');
function clear(){keys.clear();stick=[0,0];boost=false;jump=false;acc=0;$('stick').querySelector('i').style.transform='';}
function persist(){const raw=JSON.stringify(saveData(s));if(raw===saveStamp)return;try{localStorage.setItem(SAVE_KEY,raw);saveStamp=raw;$('save-status').textContent='Saved on this device';}catch{storage=false;$('save-status').textContent='Storage blocked · export is not available';}}
function pause(which='pause-dialog'){if(!started||paused)return;paused=true;clear();if(which==='map-dialog')drawMap();$(which).showModal();}
for(const id of ['pause-dialog','map-dialog']){$(id).addEventListener('close',()=>{paused=false;clear();$('world').focus({preventScroll:true});});}
$('pause').onclick=()=>pause();$('atlas').onclick=()=>pause('map-dialog');$('resume').onclick=()=>$('pause-dialog').close();$('map-close').onclick=()=>$('map-dialog').close();
$('start').onclick=()=>{started=true;paused=false;clear();$('welcome').hidden=true;document.body.classList.remove('title');$('world').focus({preventScroll:true});};
$('reset').onclick=()=>{if(!confirm('Start a new Little Planet expedition? This resets only this game’s local parcels and postmarks.'))return;s=initial();waypoint=null;saveStamp='';persist();$('pause-dialog').close();view.update(0,s,{snap:true});};
function changeView(){viewMode=(viewMode+1)%3;const mode=['planet','close','wide'][viewMode];view.setCamera(mode);$('view').innerHTML=['Planet view','Close view','Whole world'][viewMode]+' <kbd>V</kbd>';}
$('view').onclick=()=>{changeView();$('world').focus();};
function action(code){if(!started||paused)return;if(code==='KeyE'){interact(s);persist();}if(code==='KeyF'){switchRide(s);persist();}if(code==='Space')jump=true;if(code==='KeyV')changeView();if(code==='KeyM')pause('map-dialog');}
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if((e.code==='Escape'||e.code==='KeyP')&&!e.repeat&&started){e.preventDefault();if($('map-dialog').open)$('map-dialog').close();else if($('pause-dialog').open)$('pause-dialog').close();else pause();return;}if(!started||paused)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','KeyE','KeyF','KeyV','KeyM','KeyQ','KeyR'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat)action(e.code);});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clear();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clear();pause();}});
$('world').addEventListener('pointerdown',e=>{orbitDrag={id:e.pointerId,x:e.clientX};$('world').setPointerCapture(e.pointerId);});$('world').addEventListener('pointermove',e=>{if(orbitDrag?.id===e.pointerId){view?.orbitBy((e.clientX-orbitDrag.x)*.007);orbitDrag.x=e.clientX;}});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('world').addEventListener(name,()=>orbitDrag=null);
$('world').addEventListener('wheel',e=>{e.preventDefault();if(e.deltaY>0){view.setCamera('wide');viewMode=2;$('view').innerHTML='Whole world <kbd>V</kbd>';}else{view.setCamera('close');viewMode=1;$('view').innerHTML='Close view <kbd>V</kbd>';}},{passive:false});
$('touch-interact').onclick=()=>action('KeyE');$('touch-ride').onclick=()=>action('KeyF');$('touch-jump').onclick=()=>action('Space');$('touch-boost').onpointerdown=e=>{boost=true;e.currentTarget.setPointerCapture(e.pointerId);};for(const name of ['pointerup','pointercancel','lostpointercapture'])$('touch-boost').addEventListener(name,()=>boost=false);
let pointer=null;const pad=$('stick');pad.onpointerdown=e=>{pointer=e.pointerId;pad.setPointerCapture(e.pointerId);moveStick(e);};pad.onpointermove=e=>{if(pointer===e.pointerId)moveStick(e);};function moveStick(e){const r=pad.getBoundingClientRect(),x=(e.clientX-r.x-r.width/2)/35,y=(e.clientY-r.y-r.height/2)/35,l=Math.max(1,Math.hypot(x,y));stick=[x/l,-y/l];pad.querySelector('i').style.transform=`translate(${stick[0]*28}px,${-stick[1]*28}px)`;}for(const name of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(name,()=>{pointer=null;stick=[0,0];pad.querySelector('i').style.transform='';});
if(matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0)document.body.classList.add('touch');
function input(){const x=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'))+stick[0],z=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown'))+stick[1],basis=view.movementBasis(s);return {direction:Math.hypot(x,z)>.1?norm(add(mul(basis.right,x),mul(basis.forward,z))):null,boost:boost||keys.has('ShiftLeft')||keys.has('ShiftRight'),jump};}
function drawMap(){const c=$('map'),g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#183e48';g.fillRect(0,0,w,h);const xy=n=>[(Math.atan2(n[0],n[1])/(2*Math.PI)+.5)*w,(.5-Math.asin(n[2])/Math.PI)*h];
 for(let i=0;i<12;i++)for(let j=0;j<6;j++){g.strokeStyle='#315b60';g.strokeRect(i*w/12,j*h/6,w/12,h/6);}g.lineWidth=4;g.strokeStyle='#b1c28b';g.beginPath();g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke();
 for(const t of WORLD.trees){const [x,y]=xy(t.n);g.fillStyle='#478363';g.fillRect(x-2,y-2,4,4);}
 for(const p of WORLD.stars)if(!s.stamps.has(p.id)){const [x,y]=xy(p.n);g.fillStyle='#e4ca7b';g.fillRect(x-2,y-2,4,4);}
 for(const site of WORLD.sites){const [x,y]=xy(site.mail);g.fillStyle=s.delivered.has(site.id)?'#8ee1b7':'#efd090';g.beginPath();g.arc(x,y,7,0,7);g.fill();g.font='13px system-ui';g.textAlign='center';g.fillText(site.name,x,y-15);}
 const [x,y]=xy(s.n);g.fillStyle='#f3a04c';g.strokeStyle='#fff1c9';g.lineWidth=2;g.beginPath();g.arc(x,y,8,0,7);g.fill();g.stroke();if(waypoint){const [a,b]=xy(waypoint);g.strokeStyle='#9edee1';g.strokeRect(a-7,b-7,14,14);}}
$('map').onclick=e=>{const r=e.currentTarget.getBoundingClientRect(),u=(e.clientX-r.x)/r.width,v=(e.clientY-r.y)/r.height;waypoint=at((u-.5)*2*Math.PI*RADIUS,(.5-v)*Math.PI*RADIUS);$('map-description').textContent='Waypoint set. It marks a direction, never teleports you. Close the atlas to explore.';drawMap();};
function ui(){const t=target(s),near=nearest(s);$('mail-count').textContent=s.delivered.size+' / 3';$('stamp-count').textContent=s.stamps.size+' / 16';$('energy').style.width=(s.energy*100)+'%';$('ride-name').textContent=s.ride?'ELECTRIC UNICYCLE':'ON FOOT';$('objective-title').textContent=s.complete?'A world connected.':s.delivered.size===3?'Back to the little post office.':t.name;$('objective-text').textContent=s.complete?'Your first dispatch is complete. Keep exploring the far side and find all sixteen postmarks.':Math.round(distance(s.n,t.mail))+' m around the planet · '+(s.delivered.size===3?'Return and press E to complete your dispatch.':'Follow the path, then press E beside the striped mailbox.');$('toast').textContent=s.toast;$('toast').classList.toggle('visible',s.toastT>0);$('context').textContent=!started?'':near?'E · '+near.name:waypoint?'Waypoint · '+Math.round(distance(s.n,waypoint))+' m around the globe':'Explore either way around the planet';}
try{view=createScene($('world'));window.addEventListener('resize',view.resize);$('start').disabled=false;$('start').textContent=saved?'Continue exploring →':'Explore the planet →';
 if(!storage)$('save-status').textContent='Local storage unavailable';
 Object.defineProperty(window,'SVGNPlanet',{value:Object.freeze({inspect:()=>({version:VERSION,started,paused,n:[...s.n],north:[...s.north],facing:[...s.facing],basis:view.movementBasis(s),radius:RADIUS,lift:s.lift,ride:s.ride,speed:s.speed,steps:s.steps,distance:s.distance,deliveries:[...s.delivered],stamps:[...s.stamps],complete:s.complete,nearest:nearest(s)?.id||null,sites:WORLD.sites.map(p=>({id:p.id,n:[...p.mail]})),events:s.events.map(e=>({...e})),render:view.inspect()})})});
 let lastUI=0;function frame(now){requestAnimationFrame(frame);const dt=last?Math.min(.08,(now-last)/1000):0;last=now;if(started&&!paused&&!document.hidden){if(keys.has('KeyQ'))view.orbitBy(-dt*1.4);if(keys.has('KeyR'))view.orbitBy(dt*1.4);acc=Math.min(.15,acc+dt);while(acc>=1/60){step(s,input(),1/60);jump=false;acc-=1/60;}persist();}else acc=0;
  if(!started)titleTime+=dt;view.update(paused?0:dt,!started?{...s,time:titleTime}:s,{menu:!started});if(now-lastUI>80){ui();lastUI=now;}}
 requestAnimationFrame(frame);
 $('world').addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('failure').hidden=false;$('failure-message').textContent='Graphics were interrupted. Reload to restore the planet; completed deliveries stay saved.';});
}catch(e){console.error(e);$('failure').hidden=false;$('failure-message').textContent=String(e.message||e);}
