import {initialCity,readCitySave,citySave,CITY_SAVE_KEY,stepCity,cityInspect,startAssignment,mount,droneAction,scan,cycleDevice,interactCity,garageAction,pulse,focus} from './city-model.mjs';
import {createCityUI} from './city-ui.mjs';
import {VERSION,RADIUS,WORLD,at,add,mul,norm,distance,initial,step,nearest,interact,throwPaper,switchRide,readSave,saveData,SAVE_KEY,LEGACY_SAVE_KEY,target} from './model.mjs';
import {createScene} from './scene.mjs';
const $=id=>document.getElementById(id),canvas=$('world');let saved=null,storage=true;
try{saved=readSave(localStorage.getItem(SAVE_KEY));if(!saved)saved=readSave(localStorage.getItem(LEGACY_SAVE_KEY));}catch{storage=false;}
let s=initial(saved),started=false,paused=false,graphicsLost=false,failed=false,view,keys=new Set(),stick=[0,0],jump=false,boost=false,orbitDrag=null,last=0,lastRender=0,lastUI=0,lastSave=0,acc=0,mode=0,vehicle='unicycle',saveStamp='',wasPlaying=false,renderDirty=true;
let citySaved=null;try{citySaved=readCitySave(localStorage.getItem(CITY_SAVE_KEY));}catch{}
let city=initialCity(citySaved),cityStamp='',cityUI;
const diagnostics=[];
function record(type,message=''){diagnostics.push({type,message,time:Date.now()});if(diagnostics.length>20)diagnostics.shift();}
function clear(){keys.clear();stick=[0,0];jump=boost=false;acc=0;$('stick').querySelector('i').style.transform='';}
function persist(){const c=JSON.stringify(citySave(city));if(c!==cityStamp){try{localStorage.setItem(CITY_SAVE_KEY,c);cityStamp=c;}catch{storage=false;}}const raw=JSON.stringify(saveData(s));if(raw===saveStamp)return;try{localStorage.setItem(SAVE_KEY,raw);saveStamp=raw;}catch{storage=false;}}
function showFailure(message){failed=true;for(const id of ['pause-dialog','map-dialog','job-board'])if($(id).open)$(id).close();clear();persist();$('failure').hidden=false;$('failure-message').textContent=message;record('error',message);}
function pause(){if(!started||paused||graphicsLost||failed)return;paused=true;clear();persist();$('pause-dialog').showModal();}
function resume(){if(graphicsLost||failed)return;paused=false;clear();last=0;for(const id of ['pause-dialog','map-dialog','job-board'])if($(id).open)$(id).close();canvas.focus({preventScroll:true});}
function cityAction(kind){
 if(!started||failed||graphicsLost)return;
 if(kind==='begin')startAssignment(s,city);
 if(kind==='delivery')city.active=false;
 if(['service','nitro'].includes(kind))garageAction(s,city,kind);
 if(!paused){if(kind==='scan')scan(s,city);if(kind==='cycle')cycleDevice(s,city);if(kind==='drone')droneAction(s,city);if(kind==='pulse')pulse(s,city);if(kind==='crouch'){if(!city.drone.active&&!city.car){city.crouch=!city.crouch;s.ride=false;}}if(kind==='hold-hack')keys.add('KeyH');}
 if(kind==='release-hack')keys.delete('KeyH');if(kind==='descend')keys.add('KeyC');if(kind==='release-descend')keys.delete('KeyC');persist();renderDirty=true;
}
cityUI=createCityUI({get:()=>({s,c:city,started}),act:cityAction,pause:()=>{paused=true;clear();persist();},resume});
for(const id of ['pause-dialog','map-dialog','job-board']){$(id).addEventListener('close',()=>{if(graphicsLost||failed||!paused||document.querySelector('dialog[open]'))return;paused=false;clear();last=0;canvas.focus({preventScroll:true});});}
$('start').onclick=()=>{started=true;paused=false;vehicle=$('vehicle').value;s.ride=true;clear();$('welcome').hidden=true;document.body.classList.remove('title');view.setCamera('street');mode=0;canvas.focus({preventScroll:true});record('started');};
$('pause').onclick=pause;$('resume').onclick=resume;
$('reset').onclick=()=>{$('confirm-reset').hidden=false;};$('cancel-reset').onclick=()=>$('confirm-reset').hidden=true;
$('accept-reset').onclick=()=>{city=initialCity(citySave(city));s=initial();s.ride=true;saveStamp='';persist();$('confirm-reset').hidden=true;resume();};
$('vehicle-pause').onchange=e=>{vehicle=e.target.value;};$('vehicle').onchange=e=>{vehicle=e.target.value;$('vehicle-pause').value=vehicle;};
function changeView(){renderDirty=true;mode=(mode+1)%3;view.setCamera(['street','adventure','overview'][mode]);$('view').textContent=['Street view','Adventure view','World overview'][mode];}
$('view').onclick=()=>{changeView();canvas.focus({preventScroll:true});};
function action(code){if(!started||paused||failed||graphicsLost)return;if(code==='KeyE'){if(interactCity(s,city)){persist();return;}if(nearest(s))interact(s);else throwPaper(s);persist();}if(code==='KeyQ')throwPaper(s);if(code==='KeyF'){if(!mount(s,city))switchRide(s);city.crouch=false;persist();}if(code==='Space')jump=true;if(code==='KeyV')changeView();if(code==='KeyM')openMap();if(code==='KeyJ')cityUI.open();if(code==='KeyX')cityAction('scan');if(code==='KeyZ')cityAction('cycle');if(code==='KeyR')cityAction('drone');if(code==='KeyT')cityAction('pulse');if(code==='KeyC'&&!city.drone.active)cityAction('crouch');}
const codes=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight','KeyE','KeyQ','KeyF','KeyV','KeyM','KeyJ','KeyX','KeyZ','KeyR','KeyT','KeyC','KeyH'];
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if((e.code==='Escape'||e.code==='KeyP')&&!e.repeat&&started){e.preventDefault();paused?resume():pause();return;}if(!started||paused)return;if(codes.includes(e.code)){e.preventDefault();keys.add(e.code);if(!e.repeat)action(e.code);}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',clear);
document.addEventListener('visibilitychange',()=>{if(document.hidden){clear();persist();pause();}last=0;});window.addEventListener('pagehide',persist);
canvas.addEventListener('pointerdown',e=>{orbitDrag={id:e.pointerId,x:e.clientX};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(orbitDrag?.id===e.pointerId){view?.orbitBy((e.clientX-orbitDrag.x)*.005);renderDirty=true;orbitDrag.x=e.clientX;}});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>orbitDrag=null);
canvas.addEventListener('wheel',e=>{e.preventDefault();mode=e.deltaY>0?1:0;view.setCamera(mode?'adventure':'street');$('view').textContent=mode?'Adventure view':'Street view';renderDirty=true;},{passive:false});
$('touch-interact').onclick=()=>action('KeyE');$('touch-ride').onclick=()=>action('KeyF');$('touch-jump').onclick=()=>action('Space');$('touch-boost').onpointerdown=e=>{boost=true;e.currentTarget.setPointerCapture(e.pointerId);};for(const type of ['pointerup','pointercancel','lostpointercapture'])$('touch-boost').addEventListener(type,()=>boost=false);
$('touch-jump').addEventListener('pointerdown',e=>{if(city.drone.active&&!paused){e.preventDefault();keys.add('Space');e.currentTarget.setPointerCapture(e.pointerId);}});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('touch-jump').addEventListener(type,()=>keys.delete('Space'));
let pointer=null;const pad=$('stick');function moveStick(e){const r=pad.getBoundingClientRect(),x=(e.clientX-r.x-r.width/2)/38,y=(e.clientY-r.y-r.height/2)/38,l=Math.max(1,Math.hypot(x,y));stick=[x/l,-y/l];pad.querySelector('i').style.transform=`translate(${stick[0]*30}px,${-stick[1]*30}px)`;}
pad.onpointerdown=e=>{pointer=e.pointerId;pad.setPointerCapture(e.pointerId);moveStick(e);};pad.onpointermove=e=>{if(pointer===e.pointerId)moveStick(e);};for(const type of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(type,()=>{pointer=null;stick=[0,0];pad.querySelector('i').style.transform='';});
if(matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0)document.body.classList.add('touch');
function input(){const x=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'))+stick[0],z=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown'))+stick[1],b=view.movementBasis(focus(s,city));return {direction:Math.hypot(x,z)>.1?norm(add(mul(b.right,x),mul(b.forward,z))):null,throttle:Math.max(-1,Math.min(1,z)),steer:Math.max(-1,Math.min(1,x)),hack:keys.has('KeyH'),brake:keys.has('Space')||jump,rise:keys.has('Space')||jump,descend:keys.has('KeyC'),boost:boost||keys.has('ShiftLeft')||keys.has('ShiftRight'),jump};}
function drawMap(){const dialog=$('map-dialog');dialog.querySelector('h2').textContent=city.active?'Signal City / connected routes':'Your delivery route';dialog.querySelector('p').textContent=city.active?'Follow the roads, use the alley or scout above the checkpoint. Gold marks your objective; the map never teleports.':'Follow the raised flags in either direction. Deliver eight papers and return to the depot. Finishing does not close the game.';if(city.active)cityUI.map($('map'),true);else legacyRouteMap();}
function legacyRouteMap(){const c=$('map'),g=c.getContext('2d');g.fillStyle='#e9e2c9';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#7d9285';g.lineWidth=8;g.beginPath();g.moveTo(c.width/2,20);g.lineTo(c.width/2,c.height-20);g.stroke();g.font='16px system-ui';for(const h of WORLD.sites){const y=30+(h.t+10)/130*(c.height-60),x=c.width/2+h.side*125;g.fillStyle=s.delivered.has(h.id)?'#438e78':'#ae6a42';g.fillRect(x-6,y-6,12,12);g.textAlign=h.side<0?'right':'left';g.fillText(h.name,x+h.side*14,y+5);}g.textAlign='center';g.fillStyle='#244a60';g.fillText('The street continues around the curved world.',c.width/2,c.height-12);}
function openMap(){if(!started||paused)return;paused=true;clear();drawMap();$('map-dialog').showModal();}
$('atlas').onclick=openMap;$('map-close').onclick=resume;
function ui(){const t=target(s),near=nearest(s);$('mail-count').textContent=s.delivered.size+' / '+WORLD.homes.length;$('stamp-count').textContent=String(s.stamps.size);$('score').textContent=String(s.delivered.size*100+s.stamps.size*25).padStart(5,'0');$('speed').textContent=Math.round(s.speed*3.6)+' km/h';$('energy').style.width=s.energy*100+'%';$('ride-name').textContent=s.ride?(vehicle==='bicycle'?'BICYCLE':'ELECTRIC UNICYCLE'):'ON FOOT';$('objective-title').textContent=s.complete?'Route complete — free ride':t.name;$('objective-text').textContent=s.complete?'Keep exploring. The game does not stop at the last delivery.':Math.round(distance(s.n,t.mail))+' m · '+(s.delivered.size===WORLD.homes.length?'Return to the depot.':'Q throws a paper. E delivers nearby.');$('save-status').textContent=storage?'Saved on this device':'Storage unavailable — play continues';$('toast').textContent=s.toast;$('toast').classList.toggle('visible',s.toastT>0);$('context').textContent=started&&near?'E · '+near.name:'';}
$('quality').onchange=e=>{view?.setQuality(e.target.value);renderDirty=true;record('quality',e.target.value);};
$('retry').onclick=()=>{if(graphicsLost){view?.restoreGraphics();record('recovery-requested');return;}try{if(!view)view=createScene(canvas);$('start').disabled=false;view.setQuality('low');renderDirty=true;failed=false;$('failure').hidden=true;last=0;resume();}catch(e){showFailure(String(e.message||e));}};
$('copy-diagnostics').onclick=async()=>{const text=JSON.stringify({version:VERSION,started,paused,graphicsLost,events:diagnostics,render:view?.inspect(),viewport:[innerWidth,innerHeight,devicePixelRatio]},null,2);$('diagnostics').hidden=false;$('diagnostics').value=text;try{await navigator.clipboard.writeText(text);}catch{};};
function boot(){try{view=createScene(canvas);$('start').disabled=false;$('start').textContent=saved?'Continue route':'Start riding';record('renderer-ready');}catch(e){showFailure(String(e.message||e));}}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();wasPlaying=started&&!paused;graphicsLost=true;for(const id of ['pause-dialog','map-dialog','job-board'])if($(id).open)$(id).close();clear();persist();$('failure').hidden=false;$('failure-message').textContent='Graphics paused. Your route is still here. Waiting for the browser to restore graphics; Retry requests recovery.';record('context-lost');});
canvas.addEventListener('webglcontextrestored',()=>{queueMicrotask(()=>{graphicsLost=false;failed=false;view.setQuality('low');$('quality').value='low';$('failure').hidden=true;clear();last=0;lastRender=performance.now();renderDirty=true;if(wasPlaying)paused=false;else if(started){paused=false;pause();}record('context-restored');});});
boot();window.addEventListener('resize',()=>{view?.resize();renderDirty=true;});
Object.defineProperty(window,'SVGNPlanet',{value:Object.freeze({inspect:()=>({version:VERSION,started,paused,graphicsLost,failed,time:s.time,n:[...s.n],north:[...s.north],facing:[...s.facing],basis:view?.movementBasis(focus(s,city)),radius:RADIUS,lift:s.lift,ride:s.ride,speed:s.speed,steps:s.steps,distance:s.distance,deliveries:[...s.delivered],stamps:[...s.stamps],complete:s.complete,nearest:nearest(s)?.id||null,sites:WORLD.sites.map(p=>({id:p.id,n:[...p.mail]})),events:s.events.map(e=>({...e})),diagnostics:diagnostics.map(e=>({...e})),render:view?.inspect(),city:cityInspect(s,city)})})});
function frame(now){requestAnimationFrame(frame);if(!view||failed||graphicsLost||document.hidden){last=0;return;}const dt=last?Math.min(.075,(now-last)/1000):0;last=now;try{if(started&&!paused){acc=Math.min(.1,acc+dt);while(acc>=1/60){stepCity(s,city,input(),1/60);jump=false;acc-=1/60;}}else acc=0;if((renderDirty||(started&&!paused))&&now-lastRender>=1000/view.fps-1){view.update(paused?0:Math.min(.1,(now-lastRender)/1000),s,{vehicle,city});lastRender=now;renderDirty=false;}if(now-lastUI>120){ui();cityUI.update();lastUI=now;}if(now-lastSave>1000){persist();lastSave=now;}}catch(e){showFailure(String(e.message||e));}}
requestAnimationFrame(frame);
