import {JOBS,POOL,POOL_ENTRANCE,canEnterPool,enterPool,leavePool,returnToDeck,startPoolJob,abandonPoolJob,interactPool,solvePoolValve,poolJob,poolTarget,poolInspect,poolDistance} from './aquatics-core.mjs';
const $=id=>document.getElementById(id);
export const poolPreferences={simple:false};try{poolPreferences.simple=JSON.parse(localStorage.getItem('svgn.neighborhood.aquatic-effects.v1')||'{}').simple===true;}catch{}
export function mountAquaticDOM(){
 const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./aquatics.css?v=0.10.0',import.meta.url).href;document.head.append(css);
 document.body.insertAdjacentHTML('beforeend',`<dialog id="pool-board" aria-labelledby="pool-board-title"><p class="eyebrow">TIDEGLASS / NEIGHBORHOOD AQUATICS</p><h2 id="pool-board-title">There is a whole world beneath the surface.</h2><p>A calm pool, a deeper basin, and three reasons to explore. No oxygen countdown. Your city contract waits while you are here.</p><label for="pool-mission">Water mission</label><select id="pool-mission"></select><article class="pool-brief"><h3 id="pool-mission-title"></h3><p id="pool-mission-description"></p><p id="pool-record"></p></article><button id="pool-start" data-pad-default class="primary">Start water mission</button><section id="pool-conflict" hidden><p>Put aside the current water mission? Its unfinished steps will be replaced. Completed records and credits stay safe.</p><button id="pool-keep">Keep current mission</button><button id="pool-replace">Replace water mission</button></section><button id="pool-free">Free swim / put current water mission aside</button><button id="pool-board-deck">Return to pool deck</button><button id="pool-board-exit">Leave the aquatic center</button><button id="pool-board-close" data-pad-back>Back to the water / B</button><p class="pool-help">Left stick swims. Right stick looks. A rises, B dives, RT swims faster, LT slows, X interacts, Y returns to the deck, RB changes camera. View or D-pad down opens this board. Menu pauses.</p></dialog>
 <dialog id="pool-valve" aria-labelledby="pool-valve-title"><p class="eyebrow">TIDEGLASS / CIRCULATION SYSTEM</p><h2 id="pool-valve-title">Find the clear current.</h2><p id="pool-valve-target"></p><label for="pool-dial">Valve dial</label><select id="pool-dial"><option value="0">Closed</option><option value="1">Quarter turn</option><option value="2">Half turn</option><option value="3">Three-quarter turn</option></select><p id="pool-valve-feedback" role="status">Match the marked setting, then apply it.</p><button id="pool-valve-apply" class="primary" data-pad-default>Apply setting / A</button><button id="pool-valve-close" data-pad-back>Back to swimming / B</button></dialog>
 <dialog id="pool-result" aria-labelledby="pool-headline"><p class="eyebrow">THE TIDEGLASS DISPATCH / LOCAL EDITION</p><h2 id="pool-headline">Good work makes ripples.</h2><p id="pool-result-story"></p><div class="pool-result-grid"><p><small>YOUR TIME</small><strong id="pool-result-time"></strong></p><p><small>CREDITS EARNED</small><strong id="pool-result-credits"></strong></p><p><small>PERSONAL BEST</small><strong id="pool-result-best"></strong></p></div><button id="pool-result-close" data-pad-default data-pad-back class="primary">Keep exploring / B</button><button id="pool-result-board">Choose another water mission</button><button id="pool-result-exit">Back to the neighborhood</button></dialog>
 <div id="pool-hud" hidden><p class="eyebrow">TIDEGLASS</p><h2 id="pool-hud-title">Take your time.</h2><p id="pool-hud-objective"></p><p id="pool-hud-depth"></p><p id="pool-hud-help">A up / B down / X interact / Y deck</p><span id="pool-location" aria-live="polite"></span></div>
 <div id="pool-touch" hidden><button id="pool-rise">Rise</button><button id="pool-dive">Dive</button><button id="pool-touch-board">Missions</button><button id="pool-touch-deck">Deck</button></div>`);
 const section=document.createElement('section');section.className='pulse-settings';section.innerHTML='<p class="eyebrow">NEW / TIDEGLASS AQUATIC CENTER</p><h3>Make a splash.</h3><p>Take an optional transit trip to the pool. Your original route, cycle and city job stay saved. The pool has its own swim controls and mission board.</p><button id="visit-pool">Visit Tideglass Aquatic Center</button><button id="pause-pool-board" hidden>Water missions</button><button id="pause-pool-deck" hidden>Return to pool deck</button><button id="pause-pool-exit" hidden>Return to the city</button><label><input type="checkbox" id="simple-pool-water"> Lightweight pool water</label><p>Lightweight water and Low graphics use transparency without extra scene captures. Reduce motion freezes caustics, waves and ripples. These options do not affect the city weather or speed.</p>';$('resume').after(section);
 const intro=document.createElement('p');intro.className='hint';intro.textContent='New: Tideglass Aquatic Center. Visit from Menu, or find its entrance a short ride behind the original depot.';$('start').after(intro);
}
export function createAquaticUI({state,view,open,resume,persist,audio,changed}){
 const touch={ascend:false,dive:false};let pendingValve=null,lastResult=state().aquatics.last;
 for(const j of JOBS){const o=document.createElement('option');o.value=j.id;o.textContent=j.name;$('pool-mission').append(o);}
 function card(){const s=state(),q=s.aquatics,j=JOBS.find(j=>j.id===$('pool-mission').value)||JOBS[0],r=q.records[j.id];$('pool-mission-title').textContent=j.name;$('pool-mission-description').textContent=j.description;$('pool-record').textContent=(r?'Completed '+r.count+' times / Best '+r.best.toFixed(1)+' s / Replay '+Math.round(j.reward*.55):'First completion '+j.reward)+' credits';$('pool-start').textContent=q.active?.id===j.id?'Resume this water mission':'Start this water mission';}
 function board(){if(!state().aquatics.inside)return;if(state().aquatics.active)$('pool-mission').value=state().aquatics.active.id;card();$('pool-conflict').hidden=true;open('pool-board');}
 function exit(){if(!leavePool(state()))return;view()?.aquatic.release();changed();persist();resume();}
 function deck(){returnToDeck(state());changed();persist();resume();}
 function launch(replace=false){const r=startPoolJob(state(),$('pool-mission').value,{replace});if(r.kind==='conflict'){$('pool-conflict').hidden=false;$('pool-keep').focus();return;}changed();persist();resume();}
 $('pool-mission').onchange=card;$('pool-start').onclick=()=>launch();$('pool-replace').onclick=()=>launch(true);$('pool-keep').onclick=()=>{$('pool-conflict').hidden=true;$('pool-start').focus();};$('pool-board-close').onclick=()=>{if(!$('pool-conflict').hidden){$('pool-keep').click();return;}resume();};
 $('pool-free').onclick=()=>{abandonPoolJob(state());persist();resume();};for(const id of['pool-board-deck','pause-pool-deck','pool-touch-deck'])$(id).onclick=deck;for(const id of['pool-board-exit','pause-pool-exit','pool-result-exit'])$(id).onclick=exit;
 for(const id of['pause-pool-board','pool-result-board','pool-touch-board'])$(id).onclick=board;
 $('visit-pool').onclick=()=>{enterPool(state(),{travel:true});changed();persist();resume();};
 $('simple-pool-water').checked=poolPreferences.simple;$('simple-pool-water').onchange=e=>{poolPreferences.simple=e.target.checked;try{localStorage.setItem('svgn.neighborhood.aquatic-effects.v1',JSON.stringify(poolPreferences));}catch{}changed();};
 const dialNames=['Closed','Quarter turn','Half turn','Three-quarter turn'];
 $('pool-valve-apply').onclick=()=>{if(!pendingValve)return;const applied=solvePoolValve(state(),pendingValve.index,Number($('pool-dial').value));if(applied){pendingValve=null;persist();resume();}else{$('pool-valve-feedback').textContent='Not aligned. Set the dial to the marked target; your completed work is safe.';audio.cue('signal-miss');}};$('pool-valve-close').onclick=()=>{pendingValve=null;resume();};$('pool-result-close').onclick=resume;
 for(const [id,key]of[['pool-rise','ascend'],['pool-dive','dive']]){const el=$(id);el.onpointerdown=e=>{touch[key]=true;el.setPointerCapture(e.pointerId);};for(const type of['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,()=>touch[key]=false);}
 window.addEventListener('blur',()=>touch.ascend=touch.dive=false);
 function interact(){const s=state();if(!s.aquatics.inside){if(canEnterPool(s)){enterPool(s);changed();persist();return true;}return false;}const result=interactPool(s);if(result?.kind==='exit'){exit();return true;}if(result?.kind==='board')board();if(result?.kind==='valve'){pendingValve=result;$('pool-dial').value='0';$('pool-valve-target').textContent='Valve '+(result.index+1)+' / Marked setting: '+dialNames[result.setting]+'.';$('pool-valve-feedback').textContent='Use left/right on the dial. A applies; B returns without changing it.';open('pool-valve');}persist();return true;}
 function update(){const s=state(),q=s.aquatics;document.body.classList.toggle('in-pool',q.inside);$('pool-hud').hidden=!q.inside;$('pool-touch').hidden=!q.inside;for(const id of['pause-pool-board','pause-pool-deck','pause-pool-exit'])$(id).hidden=!q.inside;$('visit-pool').hidden=q.inside;
  if(!q.inside){if(canEnterPool(s))$('context').textContent='X / E | Enter Tideglass Aquatic Center';return;}
  const t=poolTarget(s),j=poolJob(s);$('pool-hud-title').textContent=j?.name||'Free swim';$('pool-hud-objective').textContent=t?t.label+' / '+poolDistance(q.p,t.p).toFixed(0)+' m':'Explore the tiled basin, or open the mission board.';$('pool-hud-depth').textContent=(q.swimming?'Depth '+Math.max(0,-q.p[1]).toFixed(1)+' m':'On the pool deck')+(q.active?' / '+q.active.elapsed.toFixed(0)+' s':'');$('pool-location').textContent=q.swimming?'Swimming':'Deck';$('pool-hud-help').textContent='A / Space rise | B / Ctrl dive | X / E interact | Y / F deck | RB / V camera';
  $('speed').textContent=(q.speed*3.6).toFixed(0)+' km/h';$('ride-name').textContent=q.swimming?'SWIMMING':'POOL DECK';$('district-name').textContent='Tideglass';$('context').textContent=t&&poolDistance(q.p,t.p)<1.9&&t.kind!=='circuit'?'X / E | '+t.label:!q.swimming&&poolDistance(q.p,POOL.exit)<2.5?'X / E | Return to the city':q.swimming&&poolDistance(q.p,POOL.ladder)<2.7?'X / E | Climb ladder':'';
  if(q.last&&q.last!==lastResult){lastResult=q.last;const r=q.last;const story={'glass-circuit':'Every ring cleared, from the shallow end to the deep blue. Your next lap can be as fast or as unhurried as you like.','lost-and-found':'Four keepsakes are back where their owners can find them. Small things matter to someone.','clear-current':'Three valves are aligned. The neighborhood pool is ready for another day.'};$('pool-headline').textContent=r.id==='clear-current'?'A clearer current.':r.id==='lost-and-found'?'Lost things, found again.':'A lap worth remembering.';$('pool-result-story').textContent=story[r.id];$('pool-result-time').textContent=r.time.toFixed(1)+' s';$('pool-result-credits').textContent='+'+r.reward;$('pool-result-best').textContent=q.records[r.id].best.toFixed(1)+' s';persist();open('pool-result');}
 }
 return {interact,board,exit,deck,update,touch,inspect:()=>poolInspect(state()),resetTouch(){touch.ascend=touch.dive=false;}};
}
