/* A bounded, instanced street population. Residents and cars are scenic: they
 * never apply invisible brakes to the player. Recycling happens beyond view. */
import * as T from './vendor/three.module.js';
import {RADIUS,CITY,WORLD,point,street,norm,add,mul,cross,dot,tangent,distance} from './world.mjs';
import {cubePoint,cubePosition} from './city-data.mjs';
import {roundedLoop,makePath,samplePath} from './coastal-motion.mjs';
import {roundedBox,coastalMaterial} from './coastal-materials.mjs';
import {preferences} from './coastal-prefs.mjs';
import {currentJob,jobTarget,PAINTS} from './activities.mjs';
const MAX_PEOPLE=48,MAX_CARS=24;
const CLOTHES=['#517b83','#cb8f6e','#d5be81','#809a85','#707ba0','#b27376','#dfd9c4','#58616b'];
const SKIN=['#b98260','#dfa67e','#8c5c43','#edc6a5','#644b3d'];
const TALK=['The bakery is busy today. There are breakfast baskets on the jobs board.','Try a lap through the next district. The streets go right around the world.','Thanks for helping clean up. These blocks are our home.','The photo club left new viewpoints on the board. Brake before taking the shot.','The signal cabinets need a steady hand. Lock the pulse when it reaches green.','Ring your bell on the way past. We will make room.','Ride as fast as you like. LT or B is your brake.','There is always another contract. Replays pay credits, too.'];
export function createCoastalLife(parent){
 const root=new T.Group();root.name='Coastal Pulse / city life';parent.add(root);
 const box=roundedBox(),sphere=new T.SphereGeometry(.5,10,8),limb=new T.CylinderGeometry(.5,.45,1,7),wheel=new T.CylinderGeometry(.5,.5,1,14);wheel.rotateZ(Math.PI/2);
 const paint=new T.MeshPhysicalMaterial({roughness:.31,metalness:.18,clearcoat:1,clearcoatRoughness:.22}),glass=new T.MeshStandardMaterial({color:'#7295a2',metalness:.42,roughness:.20}),rubber=new T.MeshStandardMaterial({color:'#263139',roughness:.84}),fabric=new T.MeshStandardMaterial({roughness:1}),skin=new T.MeshStandardMaterial({roughness:.74}),metal=new T.MeshStandardMaterial({color:'#b4c1bd',metalness:.7,roughness:.32}),light=new T.MeshStandardMaterial({color:'#fff0c1',emissive:'#ffd896',emissiveIntensity:.35}),red=new T.MeshStandardMaterial({color:'#b34437',emissive:'#b52f20',emissiveIntensity:.17}),hairMat=new T.MeshStandardMaterial({color:'#42362e',roughness:1});
 const dummy=new T.Object3D(),base=new T.Matrix4(),combined=new T.Matrix4(),up=new T.Vector3(),forward=new T.Vector3(),right=new T.Vector3(),pos=new T.Vector3(),color=new T.Color();
 const all=[];
 function inst(geo,mat,count){const mesh=new T.InstancedMesh(geo,mat,count);mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);mesh.frustumCulled=false;mesh.receiveShadow=true;mesh.castShadow=true;root.add(mesh);all.push(mesh);return mesh;}
 function pose(n,f,lift=0){up.set(...n);forward.set(...f).projectOnPlane(up).normalize();right.crossVectors(up,forward).normalize();base.makeBasis(right,up,forward);base.setPosition(pos.set(...point(n,lift)));}
 function set(mesh,i,p,size,rx=0,ry=0,rz=0){dummy.position.set(...p);dummy.rotation.set(rx,ry,rz);dummy.scale.set(...size);dummy.updateMatrix();combined.multiplyMatrices(base,dummy.matrix);mesh.setMatrixAt(i,combined);}
 function hide(mesh,i){dummy.position.set(0,0,0);dummy.rotation.set(0,0,0);dummy.scale.setScalar(0);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);}
 const car={body:inst(box,paint,MAX_CARS),cabin:inst(box,glass,MAX_CARS),roof:inst(box,paint,MAX_CARS),wheels:inst(wheel,rubber,MAX_CARS*4),hubs:inst(wheel,metal,MAX_CARS*4),head:inst(box,light,MAX_CARS*2),tail:inst(box,red,MAX_CARS*2),trim:inst(box,metal,MAX_CARS*2)};
 const people={body:inst(limb,fabric,MAX_PEOPLE),head:inst(sphere,skin,MAX_PEOPLE),hair:inst(sphere,hairMat,MAX_PEOPLE),hips:inst(box,rubber,MAX_PEOPLE),arms:inst(limb,fabric,MAX_PEOPLE*2),hands:inst(sphere,skin,MAX_PEOPLE*2),thighs:inst(limb,rubber,MAX_PEOPLE*2),calves:inst(limb,rubber,MAX_PEOPLE*2),shoes:inst(box,rubber,MAX_PEOPLE*2),bags:inst(box,fabric,MAX_PEOPLE),bikeWheels:inst(wheel,rubber,MAX_PEOPLE*2),bikeFrame:inst(box,paint,MAX_PEOPLE*3)};
 for(let i=0;i<MAX_CARS;i++){const shade=CLOTHES[(i*3)%CLOTHES.length];for(const m of[car.body,car.roof])m.setColorAt(i,color.set(shade));}
 for(let i=0;i<MAX_PEOPLE;i++){const shade=CLOTHES[i%CLOTHES.length];people.body.setColorAt(i,color.set(shade));people.bags.setColorAt(i,color.set(CLOTHES[(i+3)%8]));people.head.setColorAt(i,color.set(SKIN[i%5]));for(let side=0;side<2;side++){people.arms.setColorAt(i*2+side,color.set(shade));people.hands.setColorAt(i*2+side,color.set(SKIN[i%5]));}}
 const routes=new Map();
 function blockRoute(face,i,j){const key=face+'/'+i+'/'+j;if(routes.has(key))return routes.get(key);const u=-1+i*2/CITY.N,v=-1+j*2/CITY.N,h=2/CITY.N,corners=[[u,v],[u+h,v],[u+h,v+h],[u,v+h]].map(([x,y])=>cubePoint(face,x,y)),round=Math.min(.065,3.2/distance(corners[0],corners[1])),route=roundedLoop(corners,round),center=cubePoint(face,u+h/2,v+h/2);const item={key,path:route,center};routes.set(key,item);return item;}
 const oldRoutes=[{key:'sunrise-loop',path:roundedLoop([[18,0],[18,20],[114,20],[114,0]].map(([t,x])=>street(t,x)),.035),center:street(66,10)},{key:'oak-loop',path:roundedLoop([[18,-20],[18,0],[90,0],[90,-20]].map(([t,x])=>street(t,x)),.04),center:street(54,-10)},{key:'market-loop',path:roundedLoop([[42,20],[42,36],[114,36],[114,20]].map(([t,x])=>street(t,x)),.035),center:street(78,28)}];
 function candidates(n){if(distance(n,street(60,0))<145)return oldRoutes;const p=cubePosition(n),i=Math.max(0,Math.min(11,Math.floor((p.u+1)*6))),j=Math.max(0,Math.min(11,Math.floor((p.v+1)*6))),list=[];for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)if(i+x>=0&&i+x<12&&j+y>=0&&j+y<12)list.push(blockRoute(p.face,i+x,j+y));return list.sort((a,b)=>distance(a.center,n)-distance(b.center,n)).slice(0,4);}
 const drivers=Array.from({length:MAX_CARS},(_,i)=>({id:i,route:null,speed:5.3+(i%5)*.85,phase:i*47.73}));
 const residents=Array.from({length:MAX_PEOPLE},(_,i)=>({id:i,route:null,speed:i%8===0?3.8:i%7===0?2.1:1.1+(i%4)*.13,phase:i*19.173,rider:i%8===0}));
 let refresh=-100,bellUntil=0,nearestPerson=null,nearestTraffic=null,activePeople=0,activeCars=0,lastPaint='';
 function assign(n,time){if(time-refresh<.65)return;refresh=time;const nearby=candidates(n);for(const a of[...drivers,...residents])if(!a.route||distance(a.route.center,n)>260)a.route=nearby[a.id%nearby.length];if(routes.size>48){const keep=new Set([...drivers,...residents].map(a=>a.route.key));for(const [key,v]of routes)if(!keep.has(key)&&distance(n,v.center)>600)routes.delete(key);}}
 function person(a,s,visible){const i=a.id;if(!visible){for(const [key,m]of Object.entries(people)){const count=['arms','hands','thighs','calves','shoes','bikeWheels'].includes(key)?2:key==='bikeFrame'?3:1;for(let k=0;k<count;k++)hide(m,i*count+k);}return;}
  const moving=a.rider?true:(Math.floor((s.time+a.id*2)/17)%5!==4),clock=a.rider?s.time:s.time-Math.floor((s.time+a.id*2)/85)*17-Math.max(0,((s.time+a.id*2)%85)-68),loc=samplePath(a.route.path,clock*a.speed+a.phase,a.rider?2.6:5.05),d=distance(s.n,loc.n),wave=!a.rider&&d<12&&(s.time<bellUntil||(!moving&&s.speed<2)),gait=moving?Math.sin(s.time*a.speed*6+a.id):0;
  if(d>185){person(a,s,false);return;}
  if(!nearestPerson||d<nearestPerson.distance)nearestPerson={id:i,distance:d,n:loc.n,message:TALK[i%TALK.length]};
  const facing=wave?tangent(add(s.n,mul(loc.n,-1)),loc.n):loc.forward;pose(loc.n,facing,a.rider?.13:Math.abs(gait)*.023);activePeople++;
  set(people.body,i,[0,1.19,0],[.47,.62,.29],a.rider?.3:0);set(people.hips,i,[0,.83,0],[.34,.20,.27]);set(people.head,i,[0,1.72,a.rider?.13:0],[.34,.41,.34]);set(people.hair,i,[0,1.86,a.rider?.11:-.025],[.35,.20,.34]);set(people.bags,i,[.21,1.09,-.2],[.24,.33,.14]);
  for(let side=0;side<2;side++){const sign=side?1:-1,k=i*2+side,angle=a.rider?Math.sin(s.time*7+side*Math.PI)*.8:gait*sign*.46;
   set(people.thighs,k,[sign*.105,.64,-Math.sin(angle)*.18],[.155,.39,.17],angle);set(people.calves,k,[sign*.105,.28,-Math.sin(angle)*.36],[.13,.37,.14],angle*.3);set(people.shoes,k,[sign*.105,.075,-Math.sin(angle)*.4+.05],[.17,.13,.28]);
   const arm=wave&&side===1?-2.5+Math.sin(s.time*6)*.13:a.rider?-1.0:-angle*.65;
   set(people.arms,k,[sign*.29,1.22-Math.cos(arm)*.18,Math.sin(arm)*.18],[.13,.45,.14],arm);set(people.hands,k,[sign*.29,1.22-Math.cos(arm)*.42,Math.sin(arm)*.42],[.13,.17,.13]);
   if(a.rider)set(people.bikeWheels,k,[0,.24,sign*.59],[.66,.20,.66],s.distance/.33);else hide(people.bikeWheels,k);
  }
  if(a.rider){set(people.bikeFrame,i*3,[0,.49,0],[.065,.12,1.13]);set(people.bikeFrame,i*3+1,[0,.62,.37],[.065,.66,.08],-.22);set(people.bikeFrame,i*3+2,[0,.88,.51],[.63,.055,.06]);}else for(let k=0;k<3;k++)hide(people.bikeFrame,i*3+k);
 }
 function vehicle(a,s,visible){const i=a.id;if(!visible){for(const [key,m]of Object.entries(car)){const count=key==='wheels'||key==='hubs'?4:['head','tail','trim'].includes(key)?2:1;for(let k=0;k<count;k++)hide(m,i*count+k);}return;}
  const loc=samplePath(a.route.path,s.time*a.speed+a.phase,1.35),d=distance(s.n,loc.n);if(d>220){vehicle(a,s,false);return;}activeCars++;if(!nearestTraffic||d<nearestTraffic.distance){const delta=tangent(add(loc.n,mul(s.n,-1)),s.n);nearestTraffic={distance:d,pan:dot(delta,cross(s.facing,s.n)),speed:a.speed};}
  pose(loc.n,loc.forward,.06);const van=i%6===0;set(car.body,i,[0,.65,0],[1.86,.60,van?4.65:4.18]);set(car.cabin,i,[0,1.20,van?-.12:-.22],[1.62,van?1.15:.76,van?3.12:2.28]);set(car.roof,i,[0,van?1.79:1.58,van?-.13:-.26],[1.68,.14,van?3.2:2.15]);
  for(let side=0;side<2;side++){const sign=side?1:-1;set(car.head,i*2+side,[sign*.59,.81,van?2.33:2.1],[.47,.16,.10]);set(car.tail,i*2+side,[sign*.65,.83,van?-2.33:-2.1],[.30,.17,.10]);set(car.trim,i*2+side,[0,.47,sign*(van?2.34:2.11)],[1.62,.1,.12]);for(let axle=0;axle<2;axle++){const k=i*4+side*2+axle;set(car.wheels,k,[sign*.91,.36,axle?1.35:-1.35],[.70,.24,.70],s.time*a.speed/.35);set(car.hubs,k,[sign*1.04,.36,axle?1.35:-1.35],[.39,.035,.39],s.time*a.speed/.35);}}
 }
 // Contract objects are pooled. They are not collision volumes.
 const props=new T.Group();root.add(props);const gold=new T.MeshStandardMaterial({color:'#e6bb6d',emissive:'#8e5720',emissiveIntensity:.24,roughness:.35,metalness:.35}),green=coastalMaterial('wood','#567b64'),crateMat=coastalMaterial('wood','#a88352'),cabinetMat=new T.MeshStandardMaterial({color:'#677b7d',metalness:.3,roughness:.58});
 const markers=Array.from({length:10},()=>{const g=new T.Group();props.add(g);const ring=new T.Mesh(new T.TorusGeometry(1.85,.065,6,40),gold);g.add(ring);const indicator=new T.Mesh(new T.OctahedronGeometry(.23),gold);indicator.position.y=2.5;g.add(indicator);const bag=new T.Mesh(sphere,green);bag.scale.set(.7,.9,.7);bag.position.y=.47;g.add(bag);const crate=new T.Mesh(box,crateMat);crate.scale.set(.7,.55,.5);crate.position.y=.34;g.add(crate);const cabinet=new T.Mesh(box,cabinetMat);cabinet.scale.set(.72,1.25,.40);cabinet.position.y=.69;g.add(cabinet);const panel=new T.Mesh(box,glass);panel.scale.set(.53,.32,.06);panel.position.set(0,.92,.225);cabinet.add(panel);const cameraProp=new T.Mesh(box,rubber);cameraProp.scale.set(.4,.25,.20);cameraProp.position.y=1.1;g.add(cameraProp);return {g,ring,indicator,bag,crate,cabinet,cameraProp};});
 const board=new T.Group();root.add(board);const boardN=street(3.5,-4.8);pose(boardN,tangent([1,0,0],boardN));board.matrixAutoUpdate=false;board.matrix.copy(base);const signCanvas=document.createElement('canvas');signCanvas.width=512;signCanvas.height=320;const cg=signCanvas.getContext('2d');cg.fillStyle='#25474e';cg.fillRect(0,0,512,320);cg.fillStyle='#ecd3a4';cg.textAlign='center';cg.font='bold 44px system-ui';cg.fillText('CITY JOBS',256,87);cg.font='25px system-ui';cg.fillText('GOOD PEOPLE. GOOD RIDES.',256,141);cg.fillText('X / E near the board',256,210);cg.fillText('D-pad down / J anywhere',256,261);const tx=new T.CanvasTexture(signCanvas);tx.colorSpace=T.SRGBColorSpace;const sign=new T.Mesh(new T.BoxGeometry(2.2,1.38,.10),new T.MeshStandardMaterial({map:tx,roughness:.85}));sign.position.y=1.75;board.add(sign);for(const x of[-.9,.9]){const leg=new T.Mesh(box,cabinetMat);leg.scale.set(.1,1.2,.12);leg.position.set(x,.6,0);board.add(leg);}
 function missionArt(s){const j=currentJob(s),run=s.jobs?.active;for(let i=0;i<markers.length;i++){const m=markers[i],n=j?.nodes[i];m.g.visible=!!n&&i>=run.index&&distance(s.n,n.n)<240;if(!m.g.visible)continue;const next=j.nodes[Math.min(i+1,j.nodes.length-1)],f=distance(n.n,next.n)>.1?tangent(add(next.n,mul(n.n,-1)),n.n):s.facing;pose(n.n,f,.19);m.g.matrixAutoUpdate=false;m.g.matrix.copy(base);m.ring.visible=n.mode==='pass';m.ring.position.y=j.type==='stunt'?1.35:1.95;m.indicator.visible=n.mode!=='pass';m.indicator.rotation.y=s.time;m.indicator.position.y=2.5+Math.sin(s.time*2)*.09;m.bag.visible=j.type==='cleanup';m.crate.visible=j.type==='courier';m.cabinet.visible=j.type==='repair';m.cameraProp.visible=j.type==='photo';m.g.scale.setScalar(i===run.index?1:.85);}board.visible=distance(s.n,boardN)<140;}
 function update(dt,s,overview,low,courier){root.visible=!overview;if(overview)return;assign(s.n,s.time);nearestPerson=null;nearestTraffic=null;activePeople=activeCars=0;const density=low||preferences.density==='low'?0:preferences.density==='busy'?2:1,np=[16,32,48][density],nc=[8,16,24][density];for(const a of drivers)vehicle(a,s,a.id<nc);for(const a of residents)person(a,s,a.id<np);for(const m of all){m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;m.castShadow=!low;}missionArt(s);
  const id=s.jobs?.paint||'ocean';if(courier&&lastPaint!==id){lastPaint=id;const p=PAINTS.find(p=>p.id===id)||PAINTS[0];for(const group of[courier.bicycle,courier.unicycle])group.traverse(o=>{if(o.isMesh&&o.material?.isMeshPhysicalMaterial&&o.material.color&&o.material.metalness<.9){o.material=o.material.clone();o.material.color.set(p.color);}});}
 }
 return {update,bell(time){bellUntil=time+3;},nearBoard:n=>distance(n,boardN)<3.6,conversation(){return nearestPerson?.distance<5?nearestPerson.message:null;},traffic:()=>nearestTraffic,inspect:()=>({activeResidents:activePeople,activeCars,cyclists:residents.filter(a=>a.id<32&&a.rider).length,pooledResidents:MAX_PEOPLE,pooledCars:MAX_CARS,drawBatches:all.length,routeCache:routes.size,nearestResident:nearestPerson?.distance||null,continuousTraffic:true})};
}
