import {test} from 'node:test';
import assert from 'node:assert/strict';
import {wrapConsoleText,drawConsoleHUD,HUD_MAP} from './console-hud.mjs';
const measure=s=>s.length*12;
test('Long current controls wrap without losing the brake instruction',()=>{const input='Primary trigger: speed / off grip: brake';const lines=wrapConsoleText(input,measure,468,2);assert.equal(lines.join(' '),input);assert.ok(lines.every(s=>measure(s)<=468));});
test('Objective lines are bounded without silently painting over later fields',()=>{const s=Array(50).fill('workshop').join(' '),lines=wrapConsoleText(s,measure,724,3);assert.equal(lines.length,3);assert.ok(lines[2].endsWith('...'));assert.ok(lines.every(s=>measure(s)<=724));});
test('Unbroken words cannot exceed the text column',()=>{const lines=wrapConsoleText('x'.repeat(160),measure,468,3);assert.equal(lines.length,3);assert.ok(lines.every(s=>measure(s)<=468));});
test('Empty text stays empty and invalid layout arguments fail explicitly',()=>{assert.deepEqual(wrapConsoleText('',measure,468),[]);assert.throws(()=>wrapConsoleText('a',measure,0));assert.throws(()=>wrapConsoleText('a',null,10));assert.throws(()=>wrapConsoleText('a',measure,10,0));});
function fixture(){const text=[],maps=[],ctx={font:'',fillStyle:'',fillRect(){},measureText:s=>({width:measure(s)}),fillText:(...a)=>text.push(a),drawImage:(...a)=>maps.push(a)};return {ctx,text,maps};}
test('No equipment, menu or driving text overlaps the compact map',()=>{const f=fixture(),data={title:'LANTERN WARD',goal:'Meet Mara at the neighborhood watch desk',detail:'3 m / street level',equipment:'bicycle / service grapple',controls:'Primary trigger: speed / off grip: brake',menu:'B',health:100,map:{}};const rows=drawConsoleHUD(f.ctx,data);assert.equal(f.maps.length,1);for(const row of rows){assert.ok(row.y<=512);if(row.y>=HUD_MAP.y)assert.ok(row.x+row.width<HUD_MAP.x);}assert.equal(f.maps[0][1],HUD_MAP.x);assert.ok(rows.some(r=>r.text.includes('brake')));assert.ok(rows.some(r=>r.text.includes('Menu: B')));});
test('Floor and wrist cards explain their actual dismissal gesture',()=>{const a=fixture(),b=fixture();drawConsoleHUD(a.ctx,{goal:'Find depot'},{floor:true});drawConsoleHUD(b.ctx,{goal:'Find depot'});assert.ok(a.text.some(r=>r[0].startsWith('Look ahead')));assert.ok(b.text.some(r=>r[0].startsWith('Lower free hand')));});
test('Rendering updated mission data does not mutate its objective or credits',()=>{const f=fixture(),data=Object.freeze({goal:'Return to Mara',equipment:'foot',controls:'Primary grip: interact / trigger: action',credits:180});drawConsoleHUD(f.ctx,data);assert.equal(data.credits,180);assert.ok(f.text.some(r=>r[0]==='Return to Mara'));});
