import {HOST,CHAPTER,PROJECTS,storyStatus,nearHost,chooseProject,followChapter,claimHomecoming,storyTarget} from './homecoming.mjs';
const $=id=>document.getElementById(id);
export function mountHomecomingDOM(){
 document.body.insertAdjacentHTML('beforeend',`<dialog id="homecoming-dialog" aria-labelledby="hc-title"><p class="eyebrow">HOMECOMING / CHAPTER ONE</p><h2 id="hc-title">A block worth coming home to.</h2><p id="hc-speaker"></p><p id="hc-line"></p><p id="hc-progress" role="status"></p><label for="hc-project">Help shape Common Ground</label><select id="hc-project"><option value="garden">A community garden</option><option value="workshop">A neighborhood cycle workshop</option></select><p id="hc-project-detail"></p><button id="hc-follow" class="primary" data-pad-default>Follow the chapter</button><section id="hc-conflict" hidden><p>This will put aside your current contract, not erase completed work.</p><button id="hc-keep">Keep my current contract</button><button id="hc-replace">Put it aside and follow the chapter</button></section><div id="hc-scenes"></div><button id="hc-close" data-pad-back>Back to the neighborhood / B</button></dialog>
 <dialog id="health-dialog" aria-labelledby="health-title"><p class="eyebrow">LOCAL QUALITY REPORT</p><h2 id="health-title">Smoothness you can measure.</h2><button id="health-close" class="primary" data-pad-default data-pad-back>Back to riding / B</button><p id="health-summary"></p><p>This records your last 600 rendered frames. Pauses are excluded. CPU submission time is not GPU time, and a software-browser test is not a measurement of your gaming PC.</p><button id="health-reset">Clear measurements and start a new ride</button><button id="health-copy">Show and copy the report</button><textarea id="health-text" hidden readonly aria-label="Local frame timing and game quality report"></textarea><p>No measurements leave this device automatically. Desktop 60 fps is a target, not a certified result.</p></dialog>
 <dialog id="production-dialog" aria-labelledby="production-title"><p class="eyebrow">NEIGHBORHOOD MISSIONS / PRODUCTION CHECKLIST</p><h2 id="production-title">The path to a finished title.</h2><button id="production-close" class="primary" data-pad-default data-pad-back>Back to riding / B</button><p id="production-summary">Loading the versioned checklist...</p><label for="production-filter">Show work</label><select id="production-filter"><option value="all">All milestones</option><option value="remaining">Remaining work</option><option value="verified">Verified acceptance items</option><option value="P0">Highest priority / P0</option></select><div id="production-items"></div><p>Canonical records: production/roadmap.json and AAA_ROADMAP.md beside the game source. Checklist completion is not a claim of AAA status.</p></dialog>`);
 const menu=document.createElement('section');menu.className='hc-menu';menu.innerHTML='<h3>Your neighborhood</h3><button id="open-homecoming">Homecoming story journal</button><button id="open-health">Ride performance report</button><button id="open-production">AAA production checklist</button>';$('resume').after(menu);
 const welcome=document.createElement('p');welcome.className='hint';welcome.textContent='New: meet Maya at Common Ground, just across from the depot. Homecoming is an optional connected story; free roaming and every old contract remain available.';$('start').after(welcome);
 const css=document.createElement('style');css.textContent='#homecoming-dialog,#production-dialog{width:650px}#hc-line{font-size:16px;line-height:1.75}#hc-speaker{color:#785d37;font-weight:700}#hc-progress{border-left:3px solid #b78e55;padding:12px;background:#ffffff66}#hc-scenes article,#production-items article{padding:13px 16px;margin:12px 0;border:1px solid #b2bbb255;border-radius:7px;background:#ffffff44}#hc-scenes h3,#production-items h3{margin:4px 0 8px}#hc-conflict{padding:12px;border:2px solid #ac7141}#health-text{width:100%;height:230px}#production-items .status{font-size:11px;color:#38616a;font-weight:700}#production-items p{margin:7px 0}.hc-menu{padding-bottom:15px;border-bottom:1px solid #bfc4b4}';document.head.append(css);
}
export function createHomecomingUI({state,open,resume,persist,metrics,view}){
 let roadmap=null,loadError='';
 function refresh(){const s=state(),h=storyStatus(s),chapter=h.next;let line=chapter?.line||'You brought the neighborhood together. Come back to Maya at Common Ground to finish the chapter.';
  $('hc-speaker').textContent=h.complete?'Maya / Common Ground':(chapter?.speaker||'Maya')+' / '+(chapter?.name||'Welcome home');
  if(h.complete)line='Look around. This used to be a place people passed through. Now it is somewhere they stop. You helped make it happen. The next ride is yours.';
  $('hc-line').textContent=line;$('hc-progress').textContent=h.finished+' of '+h.total+' community projects complete.'+(h.ready?' Return to Maya near the depot to celebrate.':'')+(h.active?' Your current contract is part of this chapter.':'');
  $('hc-project').value=h.project;$('hc-project').disabled=h.claimed;$('hc-project-detail').textContent=PROJECTS[h.project].line;
  $('hc-follow').textContent=h.complete?'Keep exploring':h.ready?(nearHost(s)?'Celebrate with Maya / collect reward':'Follow the compass back to Maya'):h.active?'Continue my chapter contract':'Follow the chapter';
  $('hc-scenes').replaceChildren();for(const [i,c]of CHAPTER.entries()){const item=document.createElement('article'),title=document.createElement('h3'),body=document.createElement('p');title.textContent=(h.done.includes(c.id)?'Complete: ':'')+c.name;body.textContent=h.done.includes(c.id)?c.payoff:i===h.finished?c.line:'Meet '+c.speaker+' as the story continues.';item.append(title,body);$('hc-scenes').append(item);}
 }
 function journal(){refresh();$('hc-conflict').hidden=true;open('homecoming-dialog');}
 function follow(replace=false){const s=state(),h=storyStatus(s);if(h.ready){if(nearHost(s))claimHomecoming(s);persist();resume();return;}if(h.complete){resume();return;}const result=followChapter(s,{replace});if(result.kind==='conflict'){$('hc-conflict').hidden=false;$('hc-keep').focus();return;}persist();resume();}
 $('open-homecoming').onclick=journal;$('hc-follow').onclick=()=>follow();$('hc-replace').onclick=()=>follow(true);$('hc-keep').onclick=()=>{$('hc-conflict').hidden=true;$('hc-follow').focus();};$('hc-close').onclick=()=>{if(!$('hc-conflict').hidden){$('hc-keep').click();return;}resume();};
 $('hc-project').onchange=e=>{chooseProject(state(),e.target.value);persist();refresh();};
 function report(){return {version:'0.8.0',frames:metrics.inspect(),renderer:view()?.inspect(),chapter:storyStatus(state()),environment:{viewport:[innerWidth,innerHeight],dpr:devicePixelRatio},physicalHardwareApproval:false};}
 function health(){const r=metrics.inspect();$('health-summary').textContent=r.samples?`${r.samples} frames / ${r.windowSeconds.toFixed(1)} seconds. Average ${r.meanFPS.toFixed(1)} fps. Frame time p95 ${r.p95ms.toFixed(1)} ms; p99 ${r.p99ms.toFixed(1)} ms. CPU submission p95 ${r.cpuP95ms.toFixed(1)} ms. ${r.over50ms} intervals over 50 ms. Simulation/wall ratio ${r.simulationRatio.toFixed(2)}.`:'Start a ride to collect a frame-time sample.';open('health-dialog');}
 $('open-health').onclick=health;$('health-close').onclick=resume;$('health-reset').onclick=()=>{metrics.reset();resume();};$('health-copy').onclick=async()=>{const text=JSON.stringify(report(),null,2);$('health-text').value=text;$('health-text').hidden=false;try{await navigator.clipboard.writeText(text);}catch{}$('health-text').focus();};
 function drawRoadmap(){if(!roadmap){$('production-summary').textContent=loadError||'Loading the versioned checklist...';return;}const filter=$('production-filter').value,items=roadmap.items.filter(i=>filter==='all'||filter==='remaining'&&i.status!=='verified'||filter==='verified'&&i.status==='verified'||filter==='P0'&&i.priority==='P0');$('production-summary').textContent=roadmap.title+' / '+roadmap.version+'. '+items.length+' visible items. Targets require named-environment evidence; art and fun require playtest approval.';$('production-items').replaceChildren();for(const i of items){const el=document.createElement('article');for(const [tag,text,cls]of[['span',i.id+' / '+i.priority+' / '+i.status,'status'],['h3',i.title,''],['p',i.acceptance,''],['p','Next: '+i.next,'']]){const p=document.createElement(tag);p.textContent=text;p.className=cls;el.append(p);}$('production-items').append(el);}}
 $('open-production').onclick=()=>{open('production-dialog');drawRoadmap();};$('production-close').onclick=resume;$('production-filter').onchange=drawRoadmap;
 fetch(new URL('./production/roadmap.json?v=0.8.0',import.meta.url)).then(r=>{if(!r.ok)throw Error('Checklist file unavailable');return r.json();}).then(r=>{roadmap=r;drawRoadmap();}).catch(()=>{loadError='The checklist could not load. It remains in AAA_ROADMAP.md beside the game files. Game progress is unaffected.';drawRoadmap();});
 return {journal,interact(){if(!nearHost(state()))return false;journal();return true;},update(){const s=state(),h=storyStatus(s);if(h.ready){$('objective-title').textContent='Return to Maya';$('objective-text').textContent='Celebrate at Common Ground, across from the original depot.';}if(nearHost(s))$('context').textContent='X / E | Talk to Maya';},inspect:()=>({chapter:storyStatus(state()),performance:metrics.inspect()})};
}
