/* Original local effects: pooled collection sparks, view-dependent water and
 * selective luminance bloom. No physics, rewards, clocks or saves are mutated. */
import * as T from './vendor/three.module.js';
const fullVert='varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}';
export function createGlow(renderer){
 const rt=()=>new T.WebGLRenderTarget(2,2,{type:T.HalfFloatType,depthBuffer:false});const sceneTarget=new T.WebGLRenderTarget(2,2,{type:T.HalfFloatType}),a=rt(),b=rt(),scene=new T.Scene(),camera=new T.Camera();
 const extract=new T.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{tex:{value:sceneTarget.texture}},vertexShader:fullVert,fragmentShader:'varying vec2 vUv;uniform sampler2D tex;void main(){vec3 c=texture2D(tex,vUv).rgb;float l=max(max(c.r,c.g),c.b);gl_FragColor=vec4(c*smoothstep(1.4,3.,l),1.);}'});
 const blur=new T.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{tex:{value:a.texture},delta:{value:new T.Vector2()}},vertexShader:fullVert,fragmentShader:'varying vec2 vUv;uniform sampler2D tex;uniform vec2 delta;void main(){vec3 c=texture2D(tex,vUv).rgb*.227027;for(int i=1;i<=4;i++){float x=float(i);float w=exp(-x*x/8.)*.1946;c+=(texture2D(tex,vUv+delta*x).rgb+texture2D(tex,vUv-delta*x).rgb)*w;}gl_FragColor=vec4(c,1.);}'});
 const composite=new T.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{tex:{value:sceneTarget.texture},bloom:{value:a.texture},strength:{value:.18}},vertexShader:fullVert,fragmentShader:'varying vec2 vUv;uniform sampler2D tex,bloom;uniform float strength;void main(){vec3 c=texture2D(tex,vUv).rgb+texture2D(bloom,vUv).rgb*strength;gl_FragColor=vec4(c,1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'});
 const plane=new T.Mesh(new T.PlaneGeometry(2,2),extract);scene.add(plane);let w=0,h=0,frames=0;const size=new T.Vector2();
 function draw(world,view,enabled,strength=1){if(!enabled||renderer.xr.isPresenting){renderer.render(world,view);return;}renderer.getDrawingBufferSize(size);if(size.x!==w||size.y!==h){w=size.x;h=size.y;sceneTarget.setSize(w,h);a.setSize(Math.max(1,w>>2),Math.max(1,h>>2));b.setSize(Math.max(1,w>>2),Math.max(1,h>>2));}
  const previous=renderer.getRenderTarget(),tone=renderer.toneMapping;try{renderer.toneMapping=T.NoToneMapping;renderer.setRenderTarget(sceneTarget);renderer.render(world,view);plane.material=extract;renderer.setRenderTarget(a);renderer.render(scene,camera);plane.material=blur;blur.uniforms.tex.value=a.texture;blur.uniforms.delta.value.set(1/a.width,0);renderer.setRenderTarget(b);renderer.render(scene,camera);blur.uniforms.tex.value=b.texture;blur.uniforms.delta.value.set(0,1/b.height);renderer.setRenderTarget(a);renderer.render(scene,camera);renderer.toneMapping=tone;plane.material=composite;composite.uniforms.strength.value=.18*strength;renderer.setRenderTarget(previous);renderer.render(scene,camera);frames++;}finally{renderer.setRenderTarget(previous);renderer.toneMapping=tone;}}
 return {draw,inspect:()=>({frames,renderTargets:3,blurScale:.25}),dispose(){sceneTarget.dispose();a.dispose();b.dispose();extract.dispose();blur.dispose();composite.dispose();plane.geometry.dispose();}};
}
export function makeWater(){
 return new T.ShaderMaterial({name:'SVGN / rippled turquoise water',transparent:true,opacity:.86,depthWrite:false,uniforms:{clock:{value:0},eye:{value:new T.Vector3()}},vertexShader:'varying vec3 wp;varying vec3 wn;void main(){vec4 p=modelMatrix*vec4(position,1.);wp=p.xyz;wn=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*p;}',fragmentShader:`varying vec3 wp;varying vec3 wn;uniform vec3 eye;uniform float clock;
 void main(){vec3 v=normalize(eye-wp);float f=pow(1.-abs(dot(v,normalize(wn))),3.);float a=sin(wp.x*2.6+wp.z*1.9+clock*.8),b=sin(wp.z*4.-wp.y*2.1-clock*.7);float caustic=pow(max(0.,1.-abs(a+b)*.8),10.);vec3 c=mix(vec3(.035,.26,.3),vec3(.38,.7,.77),f)+caustic*vec3(.08,.19,.16);gl_FragColor=vec4(c,.84);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}`});
}
export function createSparks(parent){
 const capacity=96,pos=new Float32Array(capacity*3),ages=new Float32Array(capacity),vel=new Float32Array(capacity*3),alpha=new Float32Array(capacity);ages.fill(-1);const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(pos,3));geometry.setAttribute('fade',new T.BufferAttribute(alpha,1));
 const mat=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{pixel:{value:1}},vertexShader:'attribute float fade;varying float life;uniform float pixel;void main(){life=fade;vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=clamp(36.*pixel/max(1.,-p.z),1.,6.);}',fragmentShader:'varying float life;void main(){vec2 p=gl_PointCoord-.5;float r=length(p);float crossGlow=pow(max(0.,1.-min(abs(p.x),abs(p.y))*7.),4.)*max(0.,1.-r*2.);gl_FragColor=vec4(vec3(1.,.83,.4)*1.7,crossGlow*life);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'});
 const points=new T.Points(geometry,mat);points.frustumCulled=false;points.name='SVGN / fixed pool collection sparks';parent.add(points);let index=0,bursts=0;
 function burst(p,up){bursts++;for(let j=0;j<18;j++){const i=index++%capacity,a=j*2.4;ages[i]=0;pos.set(p,i*3);for(let k=0;k<3;k++)vel[i*3+k]=Math.sin(a+k*2.1)*1.3+up[k]*1.7;}}
 function update(dt,quiet){let alive=0;for(let i=0;i<capacity;i++){if(ages[i]<0)continue;ages[i]+=dt;if(ages[i]>1){ages[i]=-1;alpha[i]=0;continue;}alpha[i]=(1-ages[i])*(quiet?0:1);for(let k=0;k<3;k++)pos[i*3+k]+=vel[i*3+k]*dt;alive++;}points.visible=alive>0&&!quiet;geometry.attributes.position.needsUpdate=true;geometry.attributes.fade.needsUpdate=true;}
 return {burst,update,inspect:()=>({capacity,bursts}),dispose(){geometry.dispose();mat.dispose();}};
}
