import {RADIUS,WORLD,street,at,add,mul,norm,cross,dot,clamp,tangent,rotate,distance,height} from './world.mjs';
export * from './world.mjs';
export const VERSION='0.4.0',SAVE_KEY='svgn.paper-delivery-3d.v1',LEGACY_SAVE_KEY='svgn.little-planet.v1';
export function readSave(raw){try{if(!raw||raw.length>16000)return null;const s=JSON.parse(raw);if(s?.v!==1)return null;const known=(a,list)=>Array.isArray(a)?[...new Set(a.filter(id=>list.some(h=>h.id===id)))]:[];const delivered=known(s.delivered,WORLD.homes);return {delivered,bonusDelivered:known(s.bonusDelivered,WORLD.bonusStops),stamps:known(s.stamps,WORLD.stars),stunts:known(s.stunts,WORLD.stuntGates),complete:s.complete===true&&delivered.length===WORLD.homes.length,ride:s.ride===true};}catch{return null;}}
export function initial(saved=null){return {n:street(0,-1.5),north:[0,0,-1],facing:[0,0,-1],speed:0,lift:0,vy:0,energy:1,ride:saved?.ride??false,boosting:false,delivered:new Set(saved?.delivered||[]),bonusDelivered:new Set(saved?.bonusDelivered||[]),stamps:new Set(saved?.stamps||[]),stunts:new Set(saved?.stunts||[]),complete:!!saved?.complete,time:0,steps:0,distance:0,toast:'',toastT:0,lastSite:null,events:[],paper:null,paperCooldown:0};}
export const saveData=s=>({v:1,delivered:[...s.delivered],bonusDelivered:[...s.bonusDelivered],stamps:[...s.stamps],stunts:[...s.stunts],complete:s.complete,ride:s.ride});
export function event(s,type,data={}){s.events.push({type,step:s.steps,...data});if(s.events.length>180)s.events.shift();}
export function blocked(n){for(const h of WORLD.buildings)if(h.type!=='garden'&&distance(n,h.n)<2.75)return true;for(const r of WORLD.rocks)if(distance(n,r.n)<r.size*.37)return true;for(const t of WORLD.trees)if(distance(n,t.n)<.37)return true;return false;}
export function nearest(s){let best=null;for(const site of [...WORLD.sites,...WORLD.bonusStops]){const d=distance(s.n,site.mail);if(d<2.7&&(!best||d<best.distance))best={...site,distance:d};}return best;}
function deliver(s,p){if(!p)return false;if(WORLD.homes.some(h=>h.id===p.id)){if(s.delivered.has(p.id))return false;s.delivered.add(p.id);s.toast='DELIVERED · '+p.name+' · '+s.delivered.size+'/'+WORLD.homes.length;s.toastT=4;event(s,'delivery',{id:p.id});return true;}if(WORLD.bonusStops.some(h=>h.id===p.id)){if(s.bonusDelivered.has(p.id))return false;s.bonusDelivered.add(p.id);s.toast='BONUS STOP · '+p.name+' · '+s.bonusDelivered.size+'/'+WORLD.bonusStops.length;s.toastT=4;event(s,'bonus-delivery',{id:p.id});return true;}return false;}
export function interact(s){const p=nearest(s);if(!p){s.toast='Ride closer to a mailbox, or press Q to throw a paper.';s.toastT=3;return false;}s.lastSite=p.id;s.toastT=5;s.toast=p.message;if(deliver(s,p))return true;if(p.id==='post'&&s.delivered.size===WORLD.homes.length&&!s.complete){s.complete=true;s.toast='ROUTE COMPLETE · Branch roads, bonus addresses and stunt gates remain open.';event(s,'complete');return true;}event(s,'talk',{id:p.id});return false;}
export function throwPaper(s){if(s.paper||s.paperCooldown>0)return false;const candidates=[...WORLD.homes.filter(h=>!s.delivered.has(h.id)),...WORLD.bonusStops.filter(h=>!s.bonusDelivered.has(h.id))],p=candidates.filter(h=>distance(s.n,h.mail)<10).sort((a,b)=>distance(s.n,a.mail)-distance(s.n,b.mail))[0];if(!p){s.toast='No undelivered mailbox in throwing range. Get closer.';s.toastT=2;return false;}s.paper={from:[...s.n],to:[...p.mail],id:p.id,t:0};s.paperCooldown=.72;event(s,'throw',{id:p.id});return true;}
export function switchRide(s){s.ride=!s.ride;s.toast=s.ride?'Riding · hold Shift for high-speed boost':'On foot · explore sidewalks and side streets';s.toastT=3;event(s,'ride',{ride:s.ride});}
export function target(s){if(s.delivered.size<WORLD.homes.length)return WORLD.homes.filter(h=>!s.delivered.has(h.id)).reduce((a,b)=>!a||distance(s.n,b.mail)<distance(s.n,a.mail)?b:a,null);if(!s.complete)return WORLD.sites[0];const bonus=WORLD.bonusStops.filter(h=>!s.bonusDelivered.has(h.id));return bonus.length?bonus.reduce((a,b)=>!a||distance(s.n,b.mail)<distance(s.n,a.mail)?b:a,null):WORLD.sites[0];}
export function step(s,input={},dt=1/60){if(!Number.isFinite(dt)||dt<=0||dt>.05)throw Error('Use bounded fixed simulation steps.');s.steps++;s.time+=dt;s.toastT=Math.max(0,s.toastT-dt);s.paperCooldown=Math.max(0,s.paperCooldown-dt);if(s.paper){s.paper.t+=dt/.55;if(s.paper.t>=1){deliver(s,[...WORLD.homes,...WORLD.bonusStops].find(h=>h.id===s.paper.id));s.paper=null;}}
 let dir=input.direction;if(!dir||dir.length!==3||!dir.every(Number.isFinite)||Math.hypot(...dir)<.01)dir=null;
 const boosting=!!input.boost&&!!dir&&s.ride&&s.energy>.03;s.boosting=boosting;s.energy=clamp(s.energy+(boosting?-.16:.22)*dt,0,1);const desired=dir?(s.ride?(boosting?30:7.5):(input.boost?6.2:4.1)):0;s.speed+=(desired-s.speed)*Math.min(1,dt*(boosting?13:dir?8:13));
 if(input.jump&&s.lift<=.001){s.vy=s.ride?3.7:3.8;event(s,'jump');}s.vy-=10*dt;s.lift=Math.max(0,s.lift+s.vy*dt);if(s.lift===0)s.vy=0;
 if(dir){dir=tangent(dir,s.n);const axis=norm(cross(s.n,dir));let angle=s.speed*dt/RADIUS;if(height(s.n)<-.3&&s.lift===0)angle*=.63;const next=norm(rotate(s.n,axis,angle));if(!blocked(next)){s.n=next;s.north=tangent(rotate(s.north,axis,angle),s.n);s.facing=tangent(rotate(dir,axis,angle),s.n);s.distance+=angle*RADIUS;}else{s.speed*=.62;}}
 for(const p of WORLD.stars)if(!s.stamps.has(p.id)&&distance(s.n,p.n)<1.1){s.stamps.add(p.id);event(s,'stamp',{id:p.id});s.toast='POSTMARK FOUND · '+s.stamps.size+'/'+WORLD.stars.length;s.toastT=2;}for(const gate of WORLD.stuntGates)if(!s.stunts.has(gate.id)&&s.ride&&s.speed>=gate.minSpeed&&distance(s.n,gate.n)<1.45){s.stunts.add(gate.id);event(s,'stunt',{id:gate.id,speed:s.speed});s.toast='STUNT GATE · '+gate.name+' · '+Math.round(s.speed*3.6)+' km/h';s.toastT=3;}
}
