import {RADIUS,WORLD,street,at,add,mul,norm,cross,dot,clamp,tangent,rotate,distance,height} from './world.mjs';
export * from './world.mjs';
export const VERSION='0.2.0',SAVE_KEY='svgn.paper-delivery-3d.v1',LEGACY_SAVE_KEY='svgn.little-planet.v1';
export function readSave(raw){try{if(!raw||raw.length>12000)return null;const s=JSON.parse(raw);if(s?.v!==1)return null;const known=(a,list)=>Array.isArray(a)?[...new Set(a.filter(id=>list.some(h=>h.id===id)))]:[];const delivered=known(s.delivered,WORLD.homes);return {delivered,stamps:known(s.stamps,WORLD.stars),complete:s.complete===true&&delivered.length===WORLD.homes.length,ride:s.ride===true};}catch{return null;}}
export function initial(saved=null){return {n:street(0,-1.5),north:[0,0,-1],facing:[0,0,-1],speed:0,lift:0,vy:0,energy:1,ride:saved?.ride??false,delivered:new Set(saved?.delivered||[]),stamps:new Set(saved?.stamps||[]),complete:!!saved?.complete,time:0,steps:0,distance:0,toast:'',toastT:0,lastSite:null,events:[],paper:null,paperCooldown:0};}
export const saveData=s=>({v:1,delivered:[...s.delivered],stamps:[...s.stamps],complete:s.complete,ride:s.ride});
export function event(s,type,data={}){s.events.push({type,step:s.steps,...data});if(s.events.length>150)s.events.shift();}
export function blocked(n){for(const h of WORLD.buildings)if(h.type!=='garden'&&distance(n,h.n)<2.75)return true;for(const r of WORLD.rocks)if(distance(n,r.n)<r.size*.37)return true;for(const t of WORLD.trees)if(distance(n,t.n)<.37)return true;return false;}
export function nearest(s){let best=null;for(const site of WORLD.sites){const d=distance(s.n,site.mail);if(d<2.7&&(!best||d<best.distance))best={...site,distance:d};}return best;}
function deliver(s,p){if(!p||!WORLD.homes.some(h=>h.id===p.id)||s.delivered.has(p.id))return false;s.delivered.add(p.id);s.toast='DELIVERED · '+p.name+' · '+s.delivered.size+'/'+WORLD.homes.length;s.toastT=4;event(s,'delivery',{id:p.id});return true;}
export function interact(s){const p=nearest(s);if(!p){s.toast='Ride closer to a mailbox, or press Q to throw a paper.';s.toastT=3;return false;}s.lastSite=p.id;s.toastT=5;s.toast=p.message;if(deliver(s,p))return true;if(p.id==='post'&&s.delivered.size===WORLD.homes.length&&!s.complete){s.complete=true;s.toast='ROUTE COMPLETE · Keep riding, or choose a fresh round from the menu.';event(s,'complete');return true;}event(s,'talk',{id:p.id});return false;}
export function throwPaper(s){if(s.paper||s.paperCooldown>0)return false;const p=WORLD.homes.filter(h=>!s.delivered.has(h.id)&&distance(s.n,h.mail)<10).sort((a,b)=>distance(s.n,a.mail)-distance(s.n,b.mail))[0];if(!p){s.toast='No raised flag in throwing range. Get a little closer.';s.toastT=2;return false;}s.paper={from:[...s.n],to:[...p.mail],id:p.id,t:0};s.paperCooldown=.9;event(s,'throw',{id:p.id});return true;}
export function switchRide(s){s.ride=!s.ride;s.toast=s.ride?'Riding · hold Shift to boost':'On foot · explore the sidewalks and gardens';s.toastT=3;event(s,'ride',{ride:s.ride});}
export function target(s){if(s.delivered.size===WORLD.homes.length)return WORLD.sites[0];return WORLD.homes.filter(h=>!s.delivered.has(h.id)).reduce((a,b)=>!a||distance(s.n,b.mail)<distance(s.n,a.mail)?b:a,null);}
export function step(s,input,dt=1/60){if(!Number.isFinite(dt)||dt<=0||dt>.05)throw Error('Use bounded fixed simulation steps.');s.steps++;s.time+=dt;s.toastT=Math.max(0,s.toastT-dt);s.paperCooldown=Math.max(0,s.paperCooldown-dt);if(s.paper){s.paper.t+=dt/.65;if(s.paper.t>=1){deliver(s,WORLD.homes.find(h=>h.id===s.paper.id));s.paper=null;}}
 let dir=input.direction;if(!dir||dir.length!==3||!dir.every(Number.isFinite)||Math.hypot(...dir)<.01)dir=null;
 const boosting=!!input.boost&&!!dir&&s.energy>.03;s.energy=clamp(s.energy+(boosting?-.16:.14)*dt,0,1);const desired=dir?(s.ride?boosting?10:6.5:boosting?5.5:3.8):0;s.speed+=(desired-s.speed)*Math.min(1,dt*(dir?8:13));
 if(input.jump&&s.lift<=.001){s.vy=s.ride?3.4:3.8;event(s,'jump');}s.vy-=10*dt;s.lift=Math.max(0,s.lift+s.vy*dt);if(s.lift===0)s.vy=0;
 if(dir){dir=tangent(dir,s.n);const axis=norm(cross(s.n,dir));let angle=s.speed*dt/RADIUS;if(height(s.n)<-.3&&s.lift===0)angle*=.63;const next=norm(rotate(s.n,axis,angle));if(!blocked(next)){s.n=next;s.north=tangent(rotate(s.north,axis,angle),s.n);s.facing=tangent(rotate(dir,axis,angle),s.n);s.distance+=angle*RADIUS;}else{s.speed*=.65;}}
 for(const p of WORLD.stars)if(!s.stamps.has(p.id)&&distance(s.n,p.n)<1.1){s.stamps.add(p.id);event(s,'stamp',{id:p.id});s.toast='POSTMARK FOUND · '+s.stamps.size+'/16';s.toastT=2;}
}
