import * as T from './vendor/three.module.js';
import {WORLD,street,add,mul,norm,tangent,rand} from './world.mjs';
import {road,mesh,anchor,batchStatic} from './art.mjs';
import {faceSurface} from './neighborhood.mjs';
const roadVector=r=>({dt:r.b[0]-r.a[0],dx:r.b[1]-r.a[1]});
function frontAt(t,x,dt=1,dx=0){const n=street(t,x),next=street(t+dt,x+dx);return tangent(add(next,mul(n,-1)),n);}
function canvasSign(label,bg='#244b55',fg='#fff1ca'){const c=document.createElement('canvas');c.width=256;c.height=80;const q=c.getContext('2d');q.fillStyle=bg;q.fillRect(0,0,256,80);q.strokeStyle='#efd497';q.lineWidth=5;q.strokeRect(5,5,246,70);q.fillStyle=fg;q.font='bold 32px system-ui';q.textAlign='center';q.fillText(label,128,53,235);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;return tx;}
function doubleSign(parent,label,t,x,yaw=0){const g=new T.Group();parent.add(g);faceSurface(g,street(t,x),frontAt(t,x));g.rotateY(yaw);mesh(g,'cylinder','#35555d',[0,1.15,0],[.045,2.3,.045]);const tx=canvasSign(label),mat=new T.MeshStandardMaterial({map:tx,roughness:.82,side:T.FrontSide});for(const side of[-1,1]){const s=new T.Mesh(new T.PlaneGeometry(1.8,.58),mat);s.position.set(0,2.35,side*.018);if(side<0)s.rotation.y=Math.PI;g.add(s);}}
function crosswalk(parent,t,x,acrossT=false){const g=new T.Group();parent.add(g);faceSurface(g,street(t,x),frontAt(t,x));if(acrossT)g.rotateY(Math.PI/2);for(let i=-4;i<=4;i++)mesh(g,'box','#efe4c8',[i*.52,.23,0],[.28,.025,2.9]);}
function trafficLight(parent,t,x){const g=new T.Group();parent.add(g);faceSurface(g,street(t,x),frontAt(t,x));mesh(g,'cylinder','#3e5961',[0,2.3,0],[.055,4.6,.055]);mesh(g,'box','#273f47',[0,4.25,0],[.43,1.05,.35]);for(const [y,c]of[[4.57,'#e96c55'],[4.25,'#edc759'],[3.94,'#62b77f']])mesh(g,'round',c,[0,y,.19],[.12,.12,.07]);}
function bench(parent,t,x,front){const g=new T.Group();parent.add(g);faceSurface(g,street(t,x),front);for(const z of[-.22,.22])mesh(g,'box','#9b7049',[0,.52,z],[1.5,.12,.16]);for(const x0 of[-.62,.62])mesh(g,'box','#40585a',[x0,.25,0],[.08,.5,.55]);mesh(g,'box','#a8794f',[0,1.03,.3],[1.5,.65,.11]);}
function shopfront(parent,site,i){const g=new T.Group();parent.add(g);faceSurface(g,site.n,norm(add(site.mail,mul(site.n,-1))));const colors=['#cf704f','#4f8a84','#d49d45','#6c7fa5'],c=colors[i%colors.length],sign=new T.Mesh(new T.PlaneGeometry(2.65,.62),new T.MeshStandardMaterial({map:canvasSign(site.sign||'LOCAL',c),roughness:.72}));sign.position.set(0,2.55,2.08);g.add(sign);for(let k=-3;k<=3;k++)mesh(g,'box',k%2?c:'#f3e5c7',[k*.38,2.03,2.44],[.36,.12,.9],[.12,0,0]);for(const x of[-1.25,1.25]){mesh(g,'box','#b69262',[x,.38,2.8],[.78,.38,.65]);for(let j=0;j<4;j++)mesh(g,'ball',['#6ea35c','#f1c966','#d77c72'][j%3],[x+(rand(i*7+j)-.5)*.55,.75+rand(i+j)*.25,2.85+(rand(j+4)-.5)*.4],[.13,.13,.13]);}}
function stuntGate(parent,gate){const g=anchor(parent,gate.n,.25),mat=new T.MeshStandardMaterial({color:'#f0c55f',emissive:'#7b5011',emissiveIntensity:.6,metalness:.3,roughness:.38}),ring=new T.Mesh(new T.TorusGeometry(1.45,.11,10,42,Math.PI),mat);ring.rotation.z=Math.PI;ring.position.y=1.45;g.add(ring);for(const x of[-1.45,1.45])mesh(g,'cylinder','#826b4c',[x,.7,0],[.09,1.4,.09]);return {gate,g,ring,mat};}
export function createNeighborhoodNetwork(root){const roads=[],sidewalks=[],decor=new T.Group();root.add(decor);for(const r of WORLD.roads.slice(1)){const asphalt=road(root,r.points,r.width,'#5f6e70',.16);roads.push({mesh:asphalt,points:r.points,width:r.width});for(const p of r.sidewalks){const sw=road(root,p,1.55,'#d2c8b3',.2);sidewalks.push([sw,p]);}road(root,r.points,.09,'#dfc77d',.22);}
 for(const t of[18,42,66,90,114]){crosswalk(decor,t,0,false);crosswalk(decor,t,-20,true);crosswalk(decor,t,20,true);crosswalk(decor,t,36,true);trafficLight(decor,t,3.7);trafficLight(decor,t,16.3);}
 for(const s of WORLD.roadLabels)doubleSign(decor,s.name,s.t,s.x,s.x===36?Math.PI/2:0);
 for(const [i,r]of WORLD.roads.slice(1).entries())for(let k=0;k<5;k++){const p=r.coords[Math.floor((k+.5)/5*(r.coords.length-1))],v=roadVector(r),alongT=Math.abs(v.dt)>=Math.abs(v.dx),side=k%2?1:-1,offset=r.width/2+1.8,bt=alongT?p.t:p.t+side*(offset+.8),bx=alongT?p.x+side*(offset+.8):p.x,lt=alongT?p.t:p.t+side*offset,lx=alongT?p.x+side*offset:p.x,front=frontAt(p.t,p.x,v.dt||0,v.dx||0),lamp=new T.Group();decor.add(lamp);faceSurface(lamp,street(lt,lx),front);mesh(lamp,'cylinder','#45636c',[0,2.3,0],[.055,4.6,.055]);mesh(lamp,'box','#eedfad',[0,4.52,-.3],[.32,.16,.58]);if(k%2===0)bench(decor,bt,bx,front);}
 WORLD.bonusStops.forEach((s,i)=>shopfront(decor,s,i));batchStatic(decor);const stunts=WORLD.stuntGates.map(g=>stuntGate(root,g));return {roads,sidewalks,update(s){for(const x of stunts){x.ring.rotation.y+=.015;const done=s.stunts.has(x.gate.id);x.mat.color.set(done?'#65c79a':'#f0c55f');x.mat.emissive.set(done?'#214d3c':'#7b5011');x.mat.emissiveIntensity=done?.35:.6;}},inspect:()=>({roadSegments:WORLD.roads.length,branchRoads:WORLD.roads.length-1,bonusStops:WORLD.bonusStops.length,stuntGates:WORLD.stuntGates.length,shopfronts:WORLD.bonusStops.length,crosswalks:20})};}
