import {loadStreetArt} from './street-art.mjs';
import {createNeighborhoodNetwork} from './network-scene.mjs';
import * as T from './vendor/three.module.js';
import {RADIUS,WORLD,point,street,at,norm,add,mul,cross,rand,target,distance} from './model.mjs';
import {road,mailbox} from './art.mjs';
import {home,avenueTree,streetLamp,mesh,anchor,batchStatic,faceSurface,groundShadow} from './neighborhood.mjs';
import {createCourier,createCar} from './vehicles.mjs';
import {createSky} from './sky.mjs';
import {leafyTree} from './foliage.mjs';
import {CAMERA_PRESETS,chooseGraphics} from './presentation.mjs';
export function createScene(canvas){
 const touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;let requested=new URLSearchParams(location.search).get('quality')||'auto',quality=chooseGraphics({touch,width:innerWidth,height:innerHeight,dpr:devicePixelRatio,requested});
 const renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'default',stencil:false,preserveDrawingBuffer:false});const recoveryExtension=renderer.getContext().getExtension('WEBGL_lose_context');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=quality.shadows;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(62,1,.1,RADIUS*8);scene.background=new T.Color('#7cc8e6');scene.fog=new T.Fog('#c6e0e4',110,250);scene.add(new T.HemisphereLight('#e3f3ff','#a49b79',1.34));const sun=new T.DirectionalLight('#ffe3ad',3.15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30,near:1,far:110});sun.shadow.normalBias=.05;sun.shadow.bias=-.0002;scene.add(sun,sun.target);
 const streetFog=scene.fog,sky=createSky(scene,RADIUS),root=new T.Group();scene.add(root);const landGeo=new T.SphereGeometry(RADIUS,96,64),p=landGeo.attributes.position,colors=[],color=new T.Color();for(let i=0;i<p.count;i++){const n=norm([p.getX(i),p.getY(i),p.getZ(i)]);p.setXYZ(i,...point(n));color.set('#7fa160').multiplyScalar(.96+rand(i)*.1);colors.push(color.r,color.g,color.b);}landGeo.setAttribute('color',new T.Float32BufferAttribute(colors,3));landGeo.computeVertexNormals();const land=new T.Mesh(landGeo,new T.MeshStandardMaterial({vertexColors:true,roughness:1}));land.receiveShadow=true;root.add(land);const sea=new T.Mesh(new T.SphereGeometry(RADIUS-.38,64,40),new T.MeshStandardMaterial({color:'#4faeb8',roughness:.6}));root.add(sea);
 const main=WORLD.roads[0].points,asphalt=road(root,main,6.4,'#5d6b6d',.16),uv=[];for(let i=1;i<=main.length-1;i++)for(const j of[(i-1)*2,i*2,(i-1)*2+1,i*2,i*2+1,(i-1)*2+1])uv.push(j%2,Math.floor(j/2)*Math.PI*2*RADIUS/(main.length-1)/4);asphalt.geometry.setAttribute('uv',new T.Float32BufferAttribute(uv,2));const grain=document.createElement('canvas');grain.width=grain.height=128;const gc=grain.getContext('2d'),image=gc.createImageData(128,128);for(let i=0;i<128*128;i++){const v=172+Math.floor(rand(i)*24);image.data.set([v,v,v,255],i*4);}gc.putImageData(image,0,0);const tex=new T.CanvasTexture(grain);tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.colorSpace=T.SRGBColorSpace;asphalt.material.map=tex;
 const sidewalks=[];for(const p of WORLD.roads[0].sidewalks){const sw=road(root,p,1.55,'#d5ccba',.2);sidewalks.push([sw,p]);}for(const side of[-1,1])road(root,WORLD.roads[0].coords.map(p=>street(p.t,side*3.26)),.18,'#efe6d1',.23);
 const trail=Array.from({length:361},(_,i)=>at(i/360*Math.PI*2*RADIUS,0));road(root,trail.slice(6,176),2.4,'#c6b98d',.13);road(root,trail.slice(186,356),2.4,'#c6b98d',.13);
 const network=createNeighborhoodNetwork(root),stat=new T.Group(),fallback=new T.Group();root.add(stat,fallback);
 for(let t=0;t<Math.PI*2*RADIUS;t+=4){const g=new T.Group();stat.add(g);faceSurface(g,street(t),add(street(t+1),mul(street(t),-1)));mesh(g,'box','#e9d29b',[0,.22,0],[.085,.018,1.65]);}
 const link=(a,b,count=17)=>Array.from({length:count},(_,i)=>norm(add(mul(a,1-i/(count-1)),mul(b,i/(count-1)))));
 for(const [i,s] of WORLD.buildings.entries()){if(s.type!=='garden')home(fallback,s,i);groundShadow(stat,s.n,3.2,3);road(root,link(s.mail,s.n),1.25,'#c9c1ad',.24);}
 for(const t of WORLD.trees){if(t.id.startsWith('avenue-')||t.id.startsWith('street-tree-'))leafyTree(fallback,t);else avenueTree(fallback,t);groundShadow(stat,t.n,1.55*t.size,1.3*t.size);}for(let i=0;i<8;i++)streetLamp(stat,9+i*15,i%2?1:-1);
 for(const r of WORLD.rocks){const g=anchor(stat,r.n);mesh(g,'ball','#839182',[0,r.size*.35,0],[r.size*.43,r.size*.9,r.size*.42]);mesh(g,'cone','#c9ccb6',[0,r.size*1.05,0],[r.size*.29,r.size*.65,r.size*.28]);}
 const garden=anchor(stat,WORLD.sites.at(-1).n);for(let i=0;i<4;i++)for(let j=0;j<7;j++){mesh(garden,'box','#7c694c',[(j-3)*.45,.1,(i-1.5)*.65],[.43,.15,.5]);mesh(garden,'ball',i%2?'#dca14e':'#68a064',[(j-3)*.45,.3,(i-1.5)*.65],[.19,.25,.2]);}batchStatic(stat);batchStatic(fallback);
 const art=loadStreetArt({root,fallback,renderer,asphalt,sidewalks:[...sidewalks,...network.sidewalks],land,roadPoints:main,extraRoads:network.roads});
 const boxes=[...WORLD.sites.map(site=>({site,bonus:false,...mailbox(root,site)})),...WORLD.bonusStops.map(site=>({site,bonus:true,...mailbox(root,site)}))];
 const clouds=new T.Group();root.add(clouds);for(let i=0;i<24;i++){const g=anchor(clouds,street(40+i*8,(rand(i+1)-.5)*75),14+rand(i)*8);for(let j=0;j<4;j++){const m=mesh(g,'ball',j%2?'#f7f2df':'#e5efea',[(j-1.5)*1.8,Math.sin(j)*.5,rand(j+i)*1.1],[2.2,1.1+rand(j),1.65]);m.castShadow=m.receiveShadow=false;}}batchStatic(clouds);clouds.traverse(o=>{o.castShadow=false;o.receiveShadow=false;});
 const courier=createCourier(root),shadow=groundShadow(root,street(0),.48,.64),neighbors=[createCourier(root,'#bc7653'),createCourier(root,'#739a65'),createCourier(root,'#d1a55d')];neighbors.forEach(a=>{a.unicycle.visible=a.bicycle.visible=false;});
 const traffic=[{g:createCar(root,'#be7253'),r:WORLD.roads[0],speed:3.2,phase:55},{g:createCar(root,'#93a89c'),r:WORLD.roads[1],speed:2.7,phase:18},{g:createCar(root,'#d8ad56'),r:WORLD.roads[2],speed:3.0,phase:51},{g:createCar(root,'#6f91a0'),r:WORLD.roads[3],speed:2.4,phase:8},{g:createCar(root,'#b67971'),r:WORLD.roads[4],speed:2.2,phase:22},{g:createCar(root,'#84956e'),r:WORLD.roads[6],speed:2.5,phase:11}];
 const stamps=WORLD.stars.map(s=>{const g=anchor(root,s.n,.65),m=mesh(g,'box','#f1d987',[0,0,0],[.38,.28,.04]);return {s,g,m};}),paper=mesh(root,'box','#fff0d1',[0,0,0],[.34,.045,.21]);paper.visible=false;
 const boostFx=new T.Group();courier.g.add(boostFx);const streakMat=new T.MeshBasicMaterial({color:'#ffe3a1',transparent:true,opacity:.62,depthWrite:false});for(let i=0;i<14;i++){const s=new T.Mesh(new T.BoxGeometry(.025,.025,.8+rand(i)*1.4),streakMat);s.position.set((rand(i+3)-.5)*1.3,(rand(i+7)-.15)*1.7,.7+rand(i+11)*1.7);boostFx.add(s);}boostFx.visible=false;
 let mode='street',orbit=0,ready=false,screenHeight=0;const up=new T.Vector3(),forward=new T.Vector3(),right=new T.Vector3(),aim=new T.Vector3(),desired=new T.Vector3();
 function resize(){const r=canvas.getBoundingClientRect();quality=chooseGraphics({touch,width:r.width,height:r.height,dpr:devicePixelRatio,requested});renderer.setPixelRatio(quality.pixelRatio);renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=Math.max(.1,r.width/Math.max(1,r.height));camera.updateProjectionMatrix();}
 function setQuality(value){requested=value;renderer.shadowMap.enabled=value==='low'?false:!touch;resize();}
 function setCamera(kind){mode=({close:'street',planet:'adventure',wide:'overview'})[kind]||kind;if(!CAMERA_PRESETS[mode])mode='street';ready=false;}
 function orbitBy(v){orbit+=v;}
 function movementBasis(s){const east=cross(s.north,s.n),f=add(mul(s.north,Math.cos(orbit)),mul(east,-Math.sin(orbit)));return {forward:f,right:cross(f,s.n)};}
 function trafficPose(item,time){const pts=item.r.points,max=pts.length-1,q=(time*item.speed+item.phase)%(max*2),idx=Math.max(0,Math.min(max-1,Math.floor(q<=max?q:max*2-q))),reverse=q>max,n=pts[idx],next=pts[Math.max(0,Math.min(max,idx+(reverse?-1:1)))];faceSurface(item.g,n,norm(add(next,mul(n,-1))));}
 function update(dt,s,{snap=false,vehicle='unicycle'}={}){
  const n=new T.Vector3(...s.n),f=new T.Vector3(...s.facing),r=new T.Vector3().crossVectors(f,n).normalize();courier.g.position.set(...point(s.n,s.lift+.1));courier.g.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(r,n,f.clone().negate()));courier.unicycle.visible=s.ride&&vehicle==='unicycle';courier.bicycle.visible=s.ride&&vehicle==='bicycle';courier.body.position.y=s.ride?(vehicle==='bicycle'?.22:.26):0;courier.body.rotation.x=s.ride&&vehicle==='bicycle'?-.1:0;boostFx.visible=s.boosting&&s.speed>11;boostFx.children.forEach((m,i)=>m.position.z=1+((m.position.z+dt*s.speed*.8+i*.03)%2.6));
  courier.legs.forEach((l,i)=>l.rotation.x=s.ride?(vehicle==='bicycle'?Math.sin(s.time*9+i*Math.PI)*.45:.09):Math.sin(s.time*10+i*Math.PI)*Math.min(.62,s.speed*.16));courier.arms.forEach((a,i)=>a.rotation.x=s.ride?(vehicle==='bicycle'?.95:-.22):Math.sin(s.time*10+i*Math.PI)*Math.min(.35,s.speed*.12));courier.wheels.forEach(w=>w.rotation.x+=s.speed*dt/.34);shadow.position.set(...point(s.n,.25));shadow.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),n);
  boxes.forEach(({flag,site,bonus})=>{const done=bonus?s.bonusDelivered.has(site.id):s.delivered.has(site.id);flag.rotation.z=done?Math.PI/2:0;flag.material.color.set(done?'#77b694':bonus?'#5db5cb':'#da6044');});
  stamps.forEach(({g,m,s:star},i)=>{g.visible=!s.stamps.has(star.id);m.rotation.y=s.time+i;});network.update(s);
  neighbors.forEach((a,i)=>{const roadX=[-6.2,6.2,20][i],t=18+i*30+Math.sin(s.time*.25+i)*2,nn=street(t,roadX);faceSurface(a.g,nn,add(street(t+1,roadX),mul(nn,-1)));a.legs.forEach((l,j)=>l.rotation.x=Math.sin(s.time*3+j*Math.PI)*.2);});traffic.forEach(x=>trafficPose(x,s.time));
  paper.visible=!!s.paper;if(s.paper){const t=s.paper.t,nn=norm(add(mul(s.paper.from,1-t),mul(s.paper.to,t)));paper.position.set(...point(nn,1+Math.sin(t*Math.PI)*2.2));paper.rotation.set(s.time*8,0,s.time*6);}
  const basis=movementBasis(s);up.copy(n);forward.set(...basis.forward);right.set(...basis.right);aim.set(...point(s.n,1.02+s.lift*.4));const preset=CAMERA_PRESETS[mode],baseFov=preset.fov+(camera.aspect<1&&mode==='street'?10:0),wantedFov=baseFov+(s.boosting&&mode==='street'?12:0);if(Math.abs(camera.fov-wantedFov)>.05){camera.fov=T.MathUtils.lerp(camera.fov,wantedFov,1-Math.exp(-dt*8));camera.updateProjectionMatrix();}
  if(mode==='overview'){desired.copy(n).multiplyScalar(RADIUS*(camera.aspect<1?4.2:3.05)).addScaledVector(forward,-RADIUS*.9);aim.set(0,0,0);scene.fog=null;}else{scene.fog=streetFog;desired.copy(aim).addScaledVector(up,preset.height).addScaledVector(forward,-preset.distance-(s.boosting?1.2:0));const ray=new T.Ray(aim.clone(),desired.clone().sub(aim).normalize()),hit=new T.Vector3();let clearance=desired.distanceTo(aim);for(const h of WORLD.buildings){if(h.type==='garden')continue;const sphere=new T.Sphere(new T.Vector3(...point(h.n,1.5)),2.7);if(ray.intersectSphere(sphere,hit)){const d=aim.distanceTo(hit)-.4;if(d>2&&d<clearance)clearance=d;}}desired.copy(aim).addScaledVector(ray.direction,clearance);}
  if(!ready||snap){camera.position.copy(desired);ready=true;}else camera.position.lerp(desired,1-Math.exp(-dt*9));camera.up.copy(up);camera.lookAt(aim);camera.updateMatrixWorld();sun.position.set(...point(s.n,35)).addScaledVector(right,-22).addScaledVector(forward,-18);sun.target.position.set(...point(s.n));clouds.visible=mode==='overview';sky.update(camera,up,mode!=='overview');art.update(s.n,mode==='overview');renderer.render(scene,camera);const bottom=new T.Vector3(...point(s.n,.1+s.lift)).project(camera),top=new T.Vector3(...point(s.n,2.12+s.lift+(s.ride?.26:0))).project(camera);screenHeight=Math.abs(top.y-bottom.y)/2;
 }
 resize();return {artReady:art.ready,consumeArtRedraw:art.consumeRedraw,update,resize,setCamera,setQuality,restoreGraphics:()=>recoveryExtension?.restoreContext(),orbitBy,movementBasis,renderer,scene,camera,get fps(){return quality.fps;},inspect:()=>({triangles:renderer.info.render.triangles,calls:renderer.info.render.calls,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,low:quality.low,shadows:renderer.shadowMap.enabled,pixelRatio:renderer.getPixelRatio(),cameraMode:mode,playerScreenHeight:screenHeight,webgl:!renderer.getContext().isContextLost(),radius:RADIUS,sky:sky.inspect(),leafyAvenue:true,network:network.inspect(),boostFov:camera.fov,art:art.inspect()})};
}
