/* Real Three math/meshes, fake canvas. These tests are not rendered evidence. */
import {test} from 'node:test';import assert from 'node:assert/strict';import * as T from './vendor/three.module.js';
import {createSpatialConsole} from './spatial-console.mjs';import {CONSOLE_KEY} from './console-state.mjs';
const ctx={fillRect(){},fillText(){},drawImage(){},measureText:s=>({width:s.length*12})};
const canvas=()=>({width:0,height:0,getContext:()=>ctx});globalThis.document={createElement:canvas};
const pose=(x=0,y=1.65,z=0,pitch=0,roll=0)=>({transform:{position:new T.Vector3(x,y,z),orientation:new T.Quaternion().setFromEuler(new T.Euler(pitch,0,roll))}});
function fixture(raw){const ui=new T.Group(),panel=new T.Mesh(new T.PlaneGeometry(1.4,1.4),new T.MeshBasicMaterial()),tex=new T.CanvasTexture(canvas()),data=new Map(raw?[[CONSOLE_KEY,raw]]:[]);ui.add(panel);let clears=0;const consoleUI=createSpatialConsole(ui,panel,tex,{storage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},clear:()=>clears++,hud:()=>({goal:'Meet Mara',title:'LANTERN WARD',detail:'3 m / street',equipment:'bicycle',controls:'Trigger: speed'})});
 const source={handedness:'left',gripSpace:{pose:pose(-.25,1.25,-.4)},gamepad:{buttons:[{value:0,pressed:false}]}},viewer=pose(),frame={getPose:s=>s.pose,getJointPose:s=>s.pose};let now=0;const sources=[source,{handedness:'right'}];
 function step(open=true,n=12){panel.visible=open;for(let i=0;i<n;i++){now+=25;consoleUI.step({viewer,floorY:0,open,dt:.025,frame,ref:{},sources,dominant:'right',now});}}
 return {ui,panel,consoleUI,source,sources,viewer,step,data,get clears(){return clears;}};}
test('Console creates actual raised button surfaces at exactly the atlas hit coordinates',()=>{const h=fixture();h.step();const row={id:'go',label:'Go',x:36,y:212,w:952,h:85};h.consoleUI.sync([row]);h.ui.updateMatrixWorld(true);assert.equal(h.consoleUI.inspect().buttonMeshes,1);const target=new T.Vector3(((row.x+row.w/2)/1024-.5)*1.4,(.5-(row.y+row.h/2)/1024)*1.4,.03).applyMatrix4(h.panel.matrixWorld);const start=new T.Vector3(0,1.6,0),cast=new T.Raycaster(start,target.clone().sub(start).normalize());const hit=h.consoleUI.hit(cast,true);assert.equal(hit.row.id,'go');assert.ok(Math.abs(hit.u-.5)<.015);assert.ok(h.consoleUI.inspect().hoverVisible);});
test('Opening is animated but submenu redraws and head tilt do not move an open floor console',()=>{const h=fixture();h.step(true,1);assert.ok(!h.consoleUI.ready);h.step();const a=h.consoleUI.inspect();h.viewer.transform=pose(.2,1.4,.15,.3,.6).transform;h.consoleUI.sync([{label:'Next page',x:36,y:212,w:952,h:85}]);h.step();assert.deepEqual(h.consoleUI.inspect().panelMatrix,a.panelMatrix);assert.deepEqual(h.consoleUI.inspect().anchor,a.anchor);});
test('Default stow leaves no menu button or head-attached billboard',()=>{const h=fixture();h.step();h.consoleUI.sync([{label:'Go',x:36,y:212,w:952,h:85}]);h.step(false);const q=h.consoleUI.inspect();assert.equal(q.buttonMeshes,0);assert.equal(q.open,false);assert.equal(q.headAttached,false);});
test('Raising/lowering the off-hand controls only wrist HUD visibility; it does not move the world',()=>{const h=fixture();h.step(false);assert.equal(h.consoleUI.inspect().hudVisible,true);const before=h.consoleUI.inspect().panelMatrix;h.source.gripSpace.pose=pose(-.25,.6,-.4);h.step(false);assert.equal(h.consoleUI.inspect().hudVisible,false);assert.deepEqual(h.consoleUI.inspect().panelMatrix,before);});
test('HUD controller transform follows grip pose and not camera roll',()=>{const h=fixture();h.step(false);const before=h.consoleUI.inspect().hudMatrix;h.viewer.transform.orientation.copy(pose(0,1.65,0,0,.5).transform.orientation);h.step(false);assert.deepEqual(h.consoleUI.inspect().hudMatrix,before);h.source.gripSpace.pose=pose(-.2,1.3,-.4);h.step(false);assert.notDeepEqual(h.consoleUI.inspect().hudMatrix,before);});
test('Controller menu mounting falls back to its fixed floor pose when tracking disappears',()=>{const h=fixture();h.consoleUI.configure('mount','controller');h.step();const controller=h.consoleUI.inspect().panelMatrix;h.source.gripSpace.pose=null;h.step();assert.notDeepEqual(h.consoleUI.inspect().panelMatrix,controller);assert.ok(h.consoleUI.inspect().panelMatrix.every(Number.isFinite));});
test('Transform preferences rearm controls and persist without touching gameplay saves',()=>{const h=fixture();h.consoleUI.configure('height',1.1);h.consoleUI.configure('size',.6);assert.equal(h.clears,2);assert.equal(h.data.size,1);assert.equal(JSON.parse(h.data.get(CONSOLE_KEY)).size,.6);});
test('Corrupt future preferences remain intact while session adjustments still work',()=>{const raw='{"v":92}',h=fixture(raw);h.consoleUI.configure('height',1.05);assert.equal(h.data.get(CONSOLE_KEY),raw);assert.equal(h.consoleUI.inspect().storageBlocked,true);});
test('Closing, controller loss and end leave no stale interactive surfaces',()=>{const h=fixture();h.consoleUI.configure('mount','controller');h.step();h.consoleUI.end();const q=h.consoleUI.inspect();assert.equal(q.open,false);assert.equal(q.buttonMeshes,0);assert.equal(q.hudVisible,false);assert.equal(q.anchor,null);assert.equal(q.controllerDocked,false);});

test('A single tracked hand or controller can always use the floor fallback instead of pointing at its own wrist',()=>{const h=fixture();h.consoleUI.configure('mount','controller');h.step();assert.equal(h.consoleUI.inspect().controllerDocked,true);h.sources.pop();h.step();assert.equal(h.consoleUI.inspect().controllerDocked,false);assert.equal(h.consoleUI.inspect().mount,'controller');assert.ok(h.consoleUI.ready);assert.ok(h.consoleUI.inspect().panelMatrix.every(Number.isFinite));});
