import {WATER_JOBS,TIDEWATER,waterSummary,waterTarget,startWaterJob,abandonWater,visitWaterfront,returnWaterDock,interactWater,toggleWatercraft,setWaterValve,finishWaterPump,PUMP_SOLUTION} from './tidewater-core.mjs';
import {street,distance,localPosition} from './world.mjs';
const $=id=>document.getElementById(id);
export function mountWaterDOM(){
 const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./tidewater.css?v=0.10.0',import.meta.url).href;document.head.append(css);
 document.body.insertAdjacentHTML('beforeend',`<dialog id="water-dialog" aria-labelledby="water-title"><p class="eyebrow">TIDEWATER COMMONS / POOL & MARINA</p><h2 id="water-title">Take the waterside route.</h2><p>A tiled pool, a boatable canal, and a connected boardwalk. Your city job is kept; its timer pauses during a water excursion.</p><label for="water-job-select">Choose an excursion</label><select id="water-job-select"></select><section class="water-card"><h3 id="water-job-name"></h3><p id="water-job-description"></p><p id="water-job-reward"></p></section><button id="water-start-job" class="primary" data-pad-default>Start excursion & go to Tidewater</button><button id="water-continue">Continue my current water excursion</button><button id="water-visit">Visit the waterfront without a new job</button><button id="water-return-dock">Return safely to the boat dock</button><button id="water-abandon">Put water excursion aside / resume city job</button><p id="water-progress" role="status"></p><p class="hint">Riding: RT accelerates, LT / B brakes, A hops, X works, Y switches ride. Skiff: left stick steers, RT accelerates, LT / B brakes, X works, Y boards or docks. The dock is marked on the local map.</p><button id="water-close" data-pad-back>Back to the neighborhood / B</button></dialog>
 <dialog id="water-pump-dialog" aria-labelledby="water-pump-title"><p class="eyebrow">SEAGLASS POOL / FILTER FLOW</p><h2 id="water-pump-title">Give the water a clear path.</h2><p>Connect each valve to its labeled destination. Left/right turns a valve; A advances it. Nothing expires while this panel is open.</p><label for="water-valve-0">Inlet valve: connect to Pool intake</label><select id="water-valve-0" data-pad-default></select><label for="water-valve-1">Middle valve: connect to Filter bed</label><select id="water-valve-1"></select><label for="water-valve-2">Outlet valve: connect to Clean return</label><select id="water-valve-2"></select><p id="water-valve-status" role="status"></p><button id="water-pump-test" class="primary">Start the filter pump</button><button id="water-pump-close" data-pad-back>Keep settings and return / B</button></dialog>
 <dialog id="water-results-dialog" aria-labelledby="water-result-title"><p class="eyebrow">THE TIDEWATER DISPATCH</p><h2 id="water-result-title">Good work by the water.</h2><p id="water-result-name"></p><div class="water-result-score" id="water-result-score"></div><p id="water-result-detail"></p><button id="water-result-close" class="primary" data-pad-default data-pad-back>Keep exploring / B</button><button id="water-result-replay">Replay this excursion</button><button id="water-result-jobs">Choose another water excursion</button></dialog>
 <section id="water-minimap" hidden aria-label="Local waterfront map"><canvas id="water-map" width="280" height="170"></canvas><p id="water-map-label"></p></section>`);
 for(const [target,id,label]of[['resume','open-water','Water missions / pool & marina'],['job-start','jobs-water','Explore the water missions'],['start','start-water','Play the water missions now']]){const b=document.createElement('button');b.id=id;b.textContent=label;$(target).after(b);}
 const welcome=$('start-water');welcome.disabled=$('start').disabled;new MutationObserver(()=>welcome.disabled=$('start').disabled).observe($('start'),{attributes:true,attributeFilter:['disabled']});
}
export function createWaterUI({state,view,audio,open,resume,persist,resetView}){
 let lastResult=null;const seen=new WeakSet();
 for(const j of WATER_JOBS){const o=document.createElement('option');o.value=j.id;o.textContent=j.name;$('water-job-select').append(o);}
 for(let i=0;i<3;i++){for(const [v,name]of['Closed','Pool intake','Filter bed','Clean return'].entries()){const o=document.createElement('option');o.value=v;o.textContent=name;$('water-valve-'+i).append(o);} $('water-valve-'+i).onchange=e=>{setWaterValve(state(),i,Number(e.target.value));audio.cue('water-valve');persist();valveStatus();};}
 function valveStatus(){const v=state().tide.valves;const n=v.filter((v,i)=>v===PUMP_SOLUTION[i]).length;$('water-valve-status').textContent=n+' of 3 connections aligned.';}
 function refresh(){const s=state(),j=WATER_JOBS.find(j=>j.id===$('water-job-select').value)||WATER_JOBS[0],repeat=s.tide.completed.includes(j.id);$('water-job-name').textContent=j.name;$('water-job-description').textContent=j.description;$('water-job-reward').textContent=j.nodes.length+' stages / '+Math.round(j.reward*(repeat?.55:1))+' credits'+(s.tide.best[j.id]?' / Best: '+s.tide.best[j.id].toFixed(1)+' s':'');$('water-progress').textContent=s.tide.completed.length+' / 3 excursions completed. '+(s.tide.active?'Active water progress is saved. Starting a different water job replaces only its unfinished run.':'Your city progress is unchanged.');$('water-continue').hidden=$('water-abandon').hidden=!s.tide.active;$('water-return-dock').hidden=!s.tide.boat;}
 function menu(){refresh();open('water-dialog');}
 function moved(){resetView();persist();resume();}
 function startSelected(){const s=state();startWaterJob(s,$('water-job-select').value);visitWaterfront(s);moved();}
 $('water-start-job').onclick=startSelected;$('water-job-select').onchange=refresh;$('water-continue').onclick=resume;
 $('water-visit').onclick=()=>{visitWaterfront(state());moved();};$('water-return-dock').onclick=()=>{returnWaterDock(state());moved();};$('water-abandon').onclick=()=>{abandonWater(state());persist();resume();};
 $('open-water').onclick=$('jobs-water').onclick=menu;$('start-water').onclick=()=>{if($('start').disabled)return;$('start').click();visitWaterfront(state());moved();menu();};
 for(const id of['water-close','water-pump-close','water-result-close'])$(id).onclick=()=>{persist();resume();};
 $('water-pump-test').onclick=()=>{if(finishWaterPump(state())){persist();resume();}else{$('water-valve-status').textContent=state().toast;audio.cue('signal-miss');}};
 $('water-result-replay').onclick=()=>{if(!lastResult)return;$('water-job-select').value=lastResult.id;startSelected();};$('water-result-jobs').onclick=menu;
 function interaction(){const result=interactWater(state());if(!result)return false;if(result.kind==='pump'){for(let i=0;i<3;i++)$('water-valve-'+i).value=state().tide.valves[i];valveStatus();open('water-pump-dialog');}persist();return true;}
 function miniMap(s,t){const el=$('water-minimap'),p=localPosition(s.n);el.hidden=distance(s.n,street(-88,73))>190||!$('welcome').hidden;if(el.hidden)return;const c=$('water-map'),g=c.getContext('2d'),P=n=>{const p=localPosition(n);return {x:20+(p.x-12)*1.98,y:18+(-p.t-30)*1.1};};g.fillStyle='#193f4b';g.fillRect(0,0,280,170);g.fillStyle='#7cafa9';for(const b of[{t:-64,x:51,w:16,h:22},{t:-114,x:75,w:84,h:44}]){const a=P(street(b.t+b.h/2,b.x-b.w/2));g.fillRect(a.x,a.y,b.w*1.98,b.h*1.1);}g.strokeStyle='#d8c39a';g.lineWidth=2;g.beginPath();for(const [i,a]of[[-40,25],[-143,25],[-143,127],[-85,127],[-85,72],[-40,72],[-40,25]].entries()){const p=P(street(...a));i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y);}g.stroke();g.fillStyle='#f4d283';const dock=P(street(...TIDEWATER.dock));g.fillRect(dock.x-4,dock.y-4,8,8);if(t){const goal=P(t.n);g.strokeStyle='#fff1b1';g.lineWidth=2;g.beginPath();g.arc(goal.x,goal.y,6,0,Math.PI*2);g.stroke();}const me=P(s.n);g.fillStyle='#ffffff';g.beginPath();g.arc(me.x,me.y,4,0,Math.PI*2);g.fill();g.fillStyle='#f1ead7';g.font='11px system-ui';g.fillText('POOL',86,51);g.fillText('CANAL',128,113);g.fillText('White: you   Gold square: dock',14,162);$('water-map-label').textContent=s.tide.boat?'PEDAL SKIFF / Y docks near the pier':'TIDEWATER / Menu opens Water missions';}
 function update(){const s=state(),t=waterTarget(s);if(t){$('objective-title').textContent=WATER_JOBS.find(j=>j.id===s.tide.active.id).name.split(' / ')[0];$('objective-text').textContent=t.label+' | '+Math.round(distance(s.n,t.n))+' m | '+(s.tide.active.index+1)+' / '+WATER_JOBS.find(j=>j.id===s.tide.active.id).nodes.length;if(distance(s.n,t.n)<3.8&&!t.kind.endsWith('-pass'))$('context').textContent=(t.kind==='board'||t.kind==='dock'?'Y / X':'X / E')+' | '+t.label;}
  if(s.tide.boat)$('ride-name').textContent='PEDAL SKIFF';miniMap(s,t);
  for(const e of s.events){if(seen.has(e))continue;seen.add(e);if(e.type==='water-complete'){lastResult=e;$('water-result-name').textContent=WATER_JOBS.find(j=>j.id===e.id)?.name||'Water excursion';$('water-result-score').textContent='+'+e.reward+' credits';$('water-result-detail').textContent='Completed in '+(e.elapsed||s.tide.best[e.id]).toFixed(1)+' seconds. Your credits, best time and completed excursion are saved.';persist();open('water-results-dialog');}}
 }
 return {menu,interaction,update,visit(){visitWaterfront(state());moved();},craft(){const handled=toggleWatercraft(s=state());if(handled){resetView();persist();}return handled;},inspect:()=>waterSummary(state())};
}
