import {VERSION,DISTRICTS,BRIDGES,RAILS,RELAYS,RECORDS,EXTRACTION,createState,saveState,readSave,step,interact,nearby,fire,pulse,jump,reverseRail,rescue,forward,clamp,distance,pointOnRail} from './model.mjs';
import {makeView,T} from './scene.mjs';
import {installControllers} from './controllers.mjs';
const $=id=>document.getElementById(id),canvas=$('world'),SAVE='aether-reach.expedition.v1',SETTINGS='aether-reach.settings.v1';
const store={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);return true;}catch{return false;}},remove(k){try{localStorage.removeItem(k);}catch{}}};
const defaults={sensitivity:1,fov:75,sound:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,explorer:true,railCamera:true,controllerSpeed:1,invertY:false};
let savedSettings={};try{savedSettings=JSON.parse(store.get(SETTINGS)||'{}');}catch{}const settings={...defaults};for(const k of Object.keys(defaults)){const v=savedSettings?.[k];if(typeof defaults[k]==='boolean'&&typeof v==='boolean')settings[k]=v;else if(k==='sensitivity'&&Number.isFinite(v))settings[k]=clamp(v,.4,2);else if(k==='fov'&&Number.isFinite(v))settings[k]=clamp(v,60,95);else if(k==='controllerSpeed'&&Number.isFinite(v))settings[k]=clamp(v,.5,2.5);}
let devices=null,state=createState(),view=null,playing=false,paused=true,accumulator=0,last=performance.now(),visualTime=0,toastUntil=0,damageUntil=0,menuAngle=0,drag=null,touchLook=null,padPointer=null,pad={x:0,y:0},audio=null,pendingResume=false,reloadQueued=false,lookReadyAt=0;
const keys=new Set(),heldActions=new Set(),eventHistory=[];const input=()=>({forward:keys.has('KeyW')||pad.y<-.25,back:keys.has('KeyS')||pad.y>.25,left:keys.has('KeyA')||pad.x<-.25,right:keys.has('KeyD')||pad.x>.25,boost:keys.has('ShiftLeft')||keys.has('ShiftRight'),reload:reloadQueued||keys.has('KeyR'),explorer:settings.explorer,railCamera:settings.railCamera});
const dialogs=[...document.querySelectorAll('dialog')];
function clearInput(){devices?.reset();reloadQueued=false;keys.clear();heldActions.clear();pad={x:0,y:0};$('move-pad').firstElementChild.style.transform='';drag=null;touchLook=null;}
function unlock(){if(document.pointerLockElement===canvas)document.exitPointerLock();}
function lock(){if(!playing||paused||navigator.maxTouchPoints>0||devices?.xr.active)return;lookReadyAt=performance.now()+350;try{const promise=canvas.requestPointerLock?.();promise?.catch?.(()=>{toast('Mouse capture unavailable. Drag to look or use the arrow keys.');});}catch{toast('Drag to look, or use the arrow keys.');}}
function toast(text,seconds=5){$('toast').textContent=text;toastUntil=performance.now()+seconds*1000;}
function persist(){const ok=store.set(SAVE,saveState(state));$('storage-status').textContent=ok?'CHECKPOINT SAVED ON THIS DEVICE':'Storage unavailable. This expedition will not survive a reload.';return ok;}
function sound(type){if(!settings.sound||!playing)return;try{if(!audio){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio=new AC();}if(audio.state==='suspended')audio.resume().catch(()=>{});const t=audio.currentTime,types={shot:[180,.06,.035],hit:[420,.08,.05],hook:[530,.15,.06],release:[270,.16,.04],relay:[660,.5,.07],pulse:[120,.3,.08],damage:[82,.14,.04],arrive:[440,.2,.04],win:[880,.8,.06]},[freq,dur,vol]=types[type]||[320,.12,.03],o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(type==='hook'?freq*1.6:freq*.8,t+dur);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.009);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+dur+.02);o.onended=()=>{o.disconnect();g.disconnect();};}catch{}}
function showDialog(id){pendingResume=playing&&!paused;paused=true;clearInput();unlock();audio?.suspend().catch(()=>{});$(id).showModal();}
function closeDialogs(){for(const d of dialogs)if(d.open)d.close();}
for(const d of dialogs){d.addEventListener('close',()=>{if(!dialogs.some(x=>x.open)&&playing&&d.id!=='complete-dialog'){paused=false;accumulator=0;canvas.focus({preventScroll:true});}});}
function pause(){if(!playing||dialogs.some(d=>d.open)||state.won)return;showDialog('pause-dialog');}
function start(continueSave=false){closeDialogs();state=createState(continueSave?store.get(SAVE):null);playing=true;paused=false;clearInput();accumulator=0;$('menu').hidden=true;$('hud').hidden=false;$('pause-button').hidden=false;$('touch').hidden=!(navigator.maxTouchPoints>0||innerWidth<680);$('storage-status').textContent='';canvas.focus({preventScroll:true});toast(continueSave?'Resuming at your last restored district.':'IONA: Welcome to Meridian Ward. Restore the three relays. The bridges are open, and the freight rails are yours to ride.',8);}
function title(){playing=false;paused=true;clearInput();unlock();closeDialogs();$('menu').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('pause-button').hidden=true;updateContinue();}
function updateContinue(){const s=readSave(store.get(SAVE));$('continue').hidden=s.relays.length+s.records.length===0;}
function action(name){if(!playing||paused||state.won)return;if(name==='interact'){if(!interact(state))toast(nearby(state)?.label||'Look for a rail station, a relay console, or an archive tablet.',2);}if(name==='jump')jump(state);if(name==='pulse')pulse(state);if(name==='reverse')reverseRail(state);if(name==='reload')reloadQueued=true;if(name==='fire')fire(state,devices?.aim);if(view)events();}
function record(id){const r=RECORDS.find(r=>r.id===id);$('record-title').textContent=r.title;$('record-text').textContent=r.text;showDialog('record-dialog');}
function events(){for(const e of state.events.splice(0)){eventHistory.push({type:e.type,time:Number(state.time.toFixed(2)),...e});if(eventHistory.length>250)eventHistory.shift();view.effect(e);sound(e.type);
 if(e.type==='relay')toast(RELAYS.find(r=>r.id===e.id).message,8);
 if(e.type==='record')record(e.id);
 if(e.type==='save')persist();
 if(e.type==='damage')damageUntil=performance.now()+(settings.reduced?120:280);
 if(e.type==='rescue')toast(e.death?'Your field suit has returned you to the last restored district.':'Safety tether deployed. You are back at your last checkpoint.',5);
 if(e.type==='hook')toast('Sky clamp engaged. W accelerates, S brakes, C reverses. Space releases with your momentum.',5);
 if(e.type==='arrive')toast('Arrived at '+DISTRICTS.find(d=>d.id===e.district).name+'. You can walk, explore, or take the rail back.',4);
 if(e.type==='win'){paused=true;clearInput();unlock();$('run-stats').replaceChildren();for(const text of [`${state.records.size} / 4 archives`,`${state.stats.rails} rail rides`,`${Math.round(state.stats.railDistance)} m by rail`,`${state.stats.defeated} machines disabled`]){const span=document.createElement('span');span.textContent=text;$('run-stats').append(span);}$('complete-dialog').showModal();}
 }}
function hud(){const p=state.p;for(const [id,n]of [['health',p.health],['shield',p.shield],['energy',p.energy]]){$(id).value=n;$(id+'-number').textContent=Math.ceil(n);}
 $('ammo').innerHTML=String(p.ammo).padStart(2,'0')+' <i>/ ∞</i>';$('weapon-status').textContent=p.reload>0?'RECHARGING…':'F / CLICK: FIRE · R: RELOAD';
 $('objective').textContent=state.relays.size===3?'Return to Arrival Quay and broadcast':'Restore the three district relays';for(const el of document.querySelectorAll('[data-relay]'))el.classList.toggle('done',state.relays.has(el.dataset.relay));
 const d=[...DISTRICTS].sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];$('district').textContent=d.name.toUpperCase();const compass=['N','NE','E','SE','S','SW','W','NW'];$('bearing').textContent=compass[((Math.round(p.yaw/(Math.PI/4))%8)+8)%8];$('interaction').textContent=nearby(state)?.label||'';
 $('rail-status').hidden=!p.rail;if(p.rail){$('rail-name').textContent=RAILS.find(r=>r.id===p.rail.id).name;$('rail-speed').textContent=Math.round(p.speed*3.6)+' km/h · '+(p.rail.dir>0?'OUTBOUND':'RETURNING');}
 if(performance.now()>toastUntil)$('toast').textContent='';$('damage-flash').style.opacity=performance.now()<damageUntil?'.55':'0';
}
function map(){const c=$('map'),g=c.getContext('2d'),w=c.width,h=c.height,scale=3.55,ox=440,oz=480;const X=x=>ox+x*scale,Z=z=>oz+z*scale;g.fillStyle='#112e3c';g.fillRect(0,0,w,h);g.strokeStyle='#557e802b';g.lineWidth=1;for(let x=0;x<w;x+=35){g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke();}for(let y=0;y<h;y+=35){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke();}
 for(const b of BRIDGES){g.strokeStyle='#d8d8bd';g.lineWidth=7;g.beginPath();g.moveTo(X(b.a[0]),Z(b.a[2]));g.lineTo(X(b.b[0]),Z(b.b[2]));g.stroke();}
 for(const d of DISTRICTS){g.fillStyle=state.relays.has(d.id)?'#467a70':'#2d5862';g.strokeStyle='#91b3a0';g.lineWidth=2;g.fillRect(X(d.x-d.w/2),Z(d.z-d.d/2),d.w*scale,d.d*scale);g.strokeRect(X(d.x-d.w/2),Z(d.z-d.d/2),d.w*scale,d.d*scale);g.fillStyle='#f8e6b8';g.font='bold 14px Arial';g.textAlign='center';g.fillText(d.name,X(d.x),Z(d.z+d.d/2)+20);}
 const colors=['#e1bc75','#c8996c','#89c7ba','#96b7d3','#d8d2ad'];RAILS.forEach((r,i)=>{g.strokeStyle=colors[i];g.lineWidth=2.5;g.beginPath();r.pts.forEach((p,k)=>k?g.lineTo(X(p.x),Z(p.z)):g.moveTo(X(p.x),Z(p.z)));g.stroke();for(const p of [r.pts[0],r.pts.at(-1)]){g.fillStyle=colors[i];g.beginPath();g.arc(X(p.x),Z(p.z),4,0,7);g.fill();}});
 for(const r of RELAYS){g.fillStyle=state.relays.has(r.id)?'#a1efc4':'#ffdf95';g.beginPath();g.arc(X(r.x),Z(r.z),6,0,7);g.fill();}for(const r of RECORDS){g.fillStyle=state.records.has(r.id)?'#69837d':'#ddf1e1';g.fillRect(X(r.x)-3,Z(r.z)-3,6,6);}
 const p=state.p,f=forward(p.yaw);g.save();g.translate(X(p.x),Z(p.z));g.rotate(p.yaw);g.fillStyle='#ff9e82';g.strokeStyle='#fff3d9';g.lineWidth=1.5;g.beginPath();g.moveTo(0,-10);g.lineTo(6,7);g.lineTo(0,3);g.lineTo(-6,7);g.closePath();g.fill();g.stroke();g.restore();
 g.textAlign='left';g.fillStyle='#f5e3b8';g.font='18px Georgia';g.fillText('N ↑',28,35);g.font='11px Arial';g.fillStyle='#bad3ce';g.fillText('No route is a teleport. Walk the bridges or board at the marked rail ends.',28,h-20);
 $('journal').replaceChildren();for(const r of RECORDS){const button=document.createElement('button');button.textContent=state.records.has(r.id)?r.title:'Unrecovered archive';button.disabled=!state.records.has(r.id);button.onclick=()=>record(r.id);$('journal').append(button);}
}
$('start').onclick=()=>{if(readSave(store.get(SAVE)).relays.length&& !confirm('Start a new expedition? This replaces the local relay checkpoint.'))return;store.remove(SAVE);start(false);};$('continue').onclick=()=>start(true);$('settings-button').onclick=()=>showDialog('settings-dialog');$('pause-settings').onclick=()=>{$('pause-dialog').close();showDialog('settings-dialog');};$('pause-button').onclick=pause;$('resume').onclick=()=>{$('pause-dialog').close();paused=false;lock();};$('return-title').onclick=title;$('map-button').onclick=()=>{map();showDialog('map-dialog');};$('explore-more').onclick=()=>{$('complete-dialog').close();state.won=false;paused=false;};$('new-expedition').onclick=()=>{store.remove(SAVE);start(false);};
for(const [id,k]of [['sensitivity','sensitivity'],['fov','fov'],['sound','sound'],['reduced','reduced'],['explorer','explorer'],['rail-camera','railCamera']]){const e=$(id);if(e.type==='checkbox')e.checked=settings[k];else e.value=settings[k];e.addEventListener('input',()=>{settings[k]=e.type==='checkbox'?e.checked:Number(e.value);store.set(SETTINGS,JSON.stringify(settings));if(view){view.camera.fov=settings.fov;view.camera.updateProjectionMatrix();}if(k==='sound'&&settings.sound)sound('relay');});}
window.addEventListener('keydown',e=>{
 if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;
 if(dialogs.some(d=>d.open)){if(e.code==='Escape'){e.preventDefault();const d=[...dialogs].reverse().find(d=>d.open);if(d.id==='complete-dialog')return;d.close();}return;}
 if(!playing)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyM','KeyE','KeyQ','KeyP'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;
 if(e.code==='Escape'||e.code==='KeyP'){pause();return;}if(e.code==='KeyM'){map();showDialog('map-dialog');return;}
 if(e.code==='KeyR')reloadQueued=true;if(e.code==='KeyE')action('interact');if(e.code==='Space')action('jump');if(e.code==='KeyC')action('reverse');if(e.code==='KeyQ')action('pulse');if(e.code==='KeyF')action('fire');
});window.addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(!playing||paused)return;if(document.pointerLockElement===canvas){if(e.button===0)heldActions.add('fire');return;}if(e.pointerType==='mouse'){drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:0};canvas.setPointerCapture(e.pointerId);}});
canvas.addEventListener('pointermove',e=>{if(!playing||paused)return;if(document.pointerLockElement===canvas){if(performance.now()<lookReadyAt)return;state.p.yaw+=e.movementX*.002*settings.sensitivity;state.p.pitch=clamp(state.p.pitch-e.movementY*.002*settings.sensitivity,-1.35,1.35);}else if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved+=Math.abs(dx)+Math.abs(dy);state.p.yaw+=dx*.004*settings.sensitivity;state.p.pitch=clamp(state.p.pitch-dy*.004*settings.sensitivity,-1.35,1.35);drag.x=e.clientX;drag.y=e.clientY;}});
canvas.addEventListener('pointerup',()=>{heldActions.delete('fire');if(drag&&drag.moved<4){action('fire');lock();}drag=null;});canvas.addEventListener('pointercancel',()=>{heldActions.clear();drag=null;});window.addEventListener('pointerup',()=>heldActions.delete('fire'));
document.addEventListener('pointerlockchange',()=>{lookReadyAt=performance.now()+180;if(document.pointerLockElement!==canvas&&playing&&!paused&&!dialogs.some(d=>d.open))pause();});document.addEventListener('pointerlockerror',()=>{if(playing)toast('Drag to look or use the arrow keys. Mouse capture is unavailable.',4);});
window.addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}last=performance.now();accumulator=0;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
const padEl=$('move-pad');function padMove(e){const r=padEl.getBoundingClientRect(),dx=clamp((e.clientX-r.left-r.width/2)/45,-1,1),dy=clamp((e.clientY-r.top-r.height/2)/45,-1,1);pad={x:dx,y:dy};padEl.firstElementChild.style.transform=`translate(${dx*32}px,${dy*32}px)`;}
padEl.addEventListener('pointerdown',e=>{e.preventDefault();padPointer=e.pointerId;padEl.setPointerCapture(e.pointerId);padMove(e);});padEl.addEventListener('pointermove',e=>{if(e.pointerId===padPointer)padMove(e);});for(const type of ['pointerup','pointercancel','lostpointercapture'])padEl.addEventListener(type,()=>{padPointer=null;pad={x:0,y:0};padEl.firstElementChild.style.transform='';});
const look=$('look-pad');look.addEventListener('pointerdown',e=>{e.preventDefault();touchLook={id:e.pointerId,x:e.clientX,y:e.clientY};look.setPointerCapture(e.pointerId);});look.addEventListener('pointermove',e=>{if(!touchLook||paused)return;state.p.yaw+=(e.clientX-touchLook.x)*.006*settings.sensitivity;state.p.pitch=clamp(state.p.pitch-(e.clientY-touchLook.y)*.006*settings.sensitivity,-1.3,1.3);touchLook.x=e.clientX;touchLook.y=e.clientY;});for(const t of ['pointerup','pointercancel'])look.addEventListener(t,()=>touchLook=null);
const reloadTouch=document.createElement('button');reloadTouch.dataset.key='reload';reloadTouch.textContent='RELOAD';document.querySelector('.touch-actions').append(reloadTouch);
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const k=b.dataset.key;action(k);if(k==='fire')heldActions.add(k);});for(const t of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(t,()=>heldActions.delete(b.dataset.key));}
function resize(){if(!view)return;view.resize(innerWidth,innerHeight);$('touch').hidden=!playing||!(navigator.maxTouchPoints>0||innerWidth<680);}window.addEventListener('resize',resize);
function animate(now,xrFrame){const elapsed=Math.min(.12,(now-last)/1000);last=now;if(document.hidden)return;visualTime+=elapsed;devices?.frame(elapsed,xrFrame);
 if(playing&&!paused&&!state.won){accumulator+=elapsed;let guard=0;while(accumulator>=1/120&&guard++<16){const dt=1/120;state.p.yaw+=((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0))*dt*1.75;state.p.pitch=clamp(state.p.pitch+((keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0))*dt*1.3,-1.35,1.35);if(heldActions.has('fire')||keys.has('KeyF')||devices?.firing)fire(state,devices?.aim);const controls=devices?devices.merge(input()):input();reloadQueued=false;step(state,controls,dt);events();accumulator-=dt;if(paused)break;}}else accumulator=0;
 if(playing&&!devices?.xr.active){const p=state.p,d=forward(p.yaw,p.pitch);view.camera.position.set(p.x,p.y+1.65,p.z);view.camera.lookAt(p.x+d.x,p.y+1.65+d.y,p.z+d.z);hud();}else if(!devices?.xr.active){menuAngle=settings.reduced?0:Math.sin(visualTime*.027)*.15;view.camera.position.set(92+Math.sin(menuAngle)*22,45,48);view.camera.lookAt(4,13,-58);}
 if(devices?.xr.active)devices.xr.syncRig();
 view.update(playing?state:{...state,time:visualTime},paused&&playing?0:elapsed,!playing,settings.reduced);view.render();
}
try{view=makeView(canvas,matchMedia('(max-width:680px)').matches?'low':'balanced');view.camera.fov=settings.fov;resize();$('start').disabled=false;$('start').textContent='Enter the district  ↗';$('load-status').textContent='First expedition ready · WebGL2 · no installation';updateContinue();devices=installControllers({view,state:()=>state,settings,saveSettings:()=>store.set(SETTINGS,JSON.stringify(settings)),start:()=>{if(!playing)start(!!store.get(SAVE));else{closeDialogs();paused=false;}},clear:clearInput,pause,playing:()=>playing,paused:()=>paused,action,map:()=>{map();showDialog('map-dialog');},hint:()=>nearby(state)?.label||$('toast').textContent});view.renderer.setAnimationLoop(animate);
 window.AetherReach=Object.freeze({version:VERSION,snapshot:()=>({devices:devices?.snapshot(),playing,paused,won:state.won,time:state.time,position:{x:state.p.x,y:state.p.y,z:state.p.z,yaw:state.p.yaw,pitch:state.p.pitch},rail:state.p.rail?{...state.p.rail}:null,health:state.p.health,shield:state.p.shield,ammo:state.p.ammo,reload:state.p.reload,energy:state.p.energy,relays:[...state.relays],records:[...state.records],checkpoint:state.checkpoint,stats:{...state.stats},enemies:state.drones.map(b=>({id:b.id,x:b.x,y:b.y,z:b.z,hp:b.hp,stun:b.stun})),interaction:nearby(state)?.type||null,renderer:view.stats(),events:eventHistory.slice(-60)})});
}catch(error){console.error(error);$('load-status').textContent='The 3D renderer could not start. A WebGL2-capable browser is required. Your other projects are unchanged.';$('start').textContent='3D unavailable';$('settings-button').disabled=false;}
