/* Controller-first input. Menus use fixed A/B/D-pad bindings even after remapping.
 * A gamepad never needs pointer lock or an OS popup to play this game. */
import {CombatGestures} from './combat-gestures.mjs';
import {InputSampler,clamp} from './input-core.mjs';
import {PAD_NAMES,PAD_ACTIONS,cleanControllerProfile,swapBinding} from './controller-profile.mjs';
import {createMenuNavigator} from './ui-navigation.mjs';
import {createXR} from './xr-session.mjs';
export function installControllers(api){
 const $=id=>document.getElementById(id),sampler=new InputSampler(),gestures=new CombatGestures();let lastDevice=null,lastPad=null,frameInput=null,lastActivity=0,lastMenu=null,lastGestureAt=performance.now(),sprint=false,aim=false,lastHaptic=0,used=false;
 api.settings.controller=cleanControllerProfile(api.settings.controller);
 const badge=document.createElement('span');badge.id='controller-status';badge.textContent='Xbox controller: press a button to connect';$('masthead').append(badge);
 const guide=document.createElement('dialog');guide.id='controller-dialog';guide.setAttribute('aria-labelledby','controller-title');guide.innerHTML='<p class="eyebrow">CONTROLLER DECK</p><h2 id="controller-title">Every action, in your hands.</h2><p>Menu and View always open pause and the atlas. In menus A selects, B returns one level, and D-pad or left stick navigates. Left/right adjusts options without opening a system popup. Right stick and LT/RT scroll; LB/RB page through long menus.</p><div id="controller-binding-grid"></div><p id="controller-binding-note">Changing a binding swaps its previous action. No action is lost. Menu controls never change.</p><button id="controller-defaults">Restore controller defaults</button><form method="dialog"><button>Back</button></form>';
 document.body.append(guide);
 const label=action=>PAD_NAMES[api.settings.controller.bindings[action]]||action;
 function rumble(strength=.08,duration=28){if(!api.settings.controller.vibration||!lastPad||performance.now()-lastHaptic<70||document.hidden)return;const actuator=lastPad.vibrationActuator||lastPad.hapticActuators?.[0];if(!actuator)return;lastHaptic=performance.now();try{const result=actuator.playEffect?actuator.playEffect('dual-rumble',{duration,startDelay:0,weakMagnitude:strength,strongMagnitude:strength*.5}):actuator.pulse?.(strength,duration);result?.catch?.(()=>{});}catch{}}
 function reset(){sampler.reset();gestures.reset();lastGestureAt=performance.now();if(api.state().skirmish)api.state().skirmish.charging=false;frameInput=null;sprint=false;aim=false;nav?.reset();}
 function bindings(){const grid=$('controller-binding-grid');grid.replaceChildren();for(const [action,title]of Object.entries(PAD_ACTIONS)){const row=document.createElement('label'),select=document.createElement('select');row.textContent=title;select.id='bind-'+action;select.dataset.bind=action;select.setAttribute('aria-label',title);for(const index of Object.keys(PAD_ACTIONS).map(k=>api.settings.controller.bindings[k]).sort((a,b)=>a-b)){const option=document.createElement('option');option.value=index;option.textContent=PAD_NAMES[index];select.append(option);}select.value=api.settings.controller.bindings[action];select.onchange=()=>{api.settings.controller=swapBinding(api.settings.controller,action,Number(select.value));api.saveSettings();reset();for(const key of Object.keys(PAD_ACTIONS))$('bind-'+key).value=api.settings.controller.bindings[key];};row.append(select);grid.append(row);}}
 const nav=createMenuNavigator({root:()=>api.topDialog()||(!api.playing()?$('menu'):null),back:m=>{if(m.root.id==='complete-dialog')$('explore-more').click();else if(m.root.tagName==='DIALOG')m.root.close();},onFocus:()=>{if(used){rumble(.035,12);api.uiSound?.();}}});
 const xr=createXR(api.view,{state:api.state,start:api.start,clear:reset,pause:api.pause,menu:()=>{const m=nav.read();if(m){const at=Math.max(0,m.items.findIndex(i=>i.focused)),start=Math.floor(at/5)*5;m.items=m.items.slice(start,start+5);m.items.push({element:$('exit-vr'),label:'Exit VR',focused:document.activeElement?.id==='exit-vr'});}return m;},focus:e=>e.focus({preventScroll:true}),hint:api.hint});
 const grid=document.querySelector('.settings-grid');
 function slider(id,title,key,min,max,step,controller=true){const row=document.createElement('label'),e=document.createElement('input');row.textContent=title;e.id=id;e.type='range';Object.assign(e,{min,max,step,value:controller?api.settings.controller[key]:api.settings[key]});row.append(e);grid.append(row);e.oninput=()=>{if(controller)api.settings.controller[key]=Number(e.value);else api.settings[key]=Number(e.value);api.saveSettings();};return e;}
 function checkbox(id,title,key,controller=true){const row=document.createElement('label'),e=document.createElement('input');e.id=id;e.type='checkbox';e.checked=controller?api.settings.controller[key]:!!api.settings[key];row.append(e,document.createTextNode(' '+title));grid.append(row);e.onchange=()=>{if(controller)api.settings.controller[key]=e.checked;else api.settings[key]=e.checked;api.saveSettings();reset();};return e;}
 slider('controller-look-speed','Controller look speed','controllerSpeed',.5,2.5,.1,false);checkbox('controller-invert','Invert controller look','invertY',false);
 slider('controller-move-deadzone','Movement deadzone','moveDeadzone',.08,.4,.02);slider('controller-look-deadzone','Look deadzone','lookDeadzone',.08,.4,.02);slider('controller-look-curve','Fine aiming response curve','lookCurve',1,2.4,.1);
 checkbox('controller-toggle-sprint','Toggle sprint / rail boost','toggleSprint');checkbox('controller-toggle-aim','Toggle aiming','toggleAim');checkbox('controller-vibration','Controller vibration when supported','vibration');
 function openGuide(){bindings();api.show('controller-dialog');}
 for(const target of ['settings-dialog','pause-dialog']){const b=document.createElement('button');b.id=target==='pause-dialog'?'pause-controller':'settings-controller';b.textContent='Controller controls and remapping';b.onclick=openGuide;$(target).insertBefore(b,$(target).querySelector('form'));}
 $('controller-defaults').onclick=()=>api.confirm('Restore controller defaults?','This only resets controller bindings and comfort options. Your expedition is not changed.','Restore controls',()=>{api.settings.controller=cleanControllerProfile(null);api.saveSettings();reset();bindings();for(const [id,k]of [['controller-move-deadzone','moveDeadzone'],['controller-look-deadzone','lookDeadzone'],['controller-look-curve','lookCurve']])$(id).value=api.settings.controller[k];for(const [id,k]of [['controller-toggle-sprint','toggleSprint'],['controller-toggle-aim','toggleAim'],['controller-vibration','vibration']])$(id).checked=api.settings.controller[k];});
 function frame(dt,xrFrame){
  const menuRoot=api.topDialog()||(!api.playing()?$('menu'):null);if(menuRoot!==lastMenu){reset();xr.reset();lastMenu=menuRoot;}
  const now=performance.now(),gestureDt=Math.min(.75,(now-lastGestureAt)/1000);lastGestureAt=now;let data;
  if(xr.active){data=xr.frame(xrFrame,dt);badge.textContent='WebXR preview - headset QA pending';}
  else{const pads=(()=>{try{return [...navigator.getGamepads?.()||[]];}catch{return [];}})();const pad=pads.find(p=>p?.connected&&p.mapping==='standard'&&(p.index+':'+p.id===lastDevice))||pads.find(p=>p?.connected&&p.mapping==='standard');
   if(!pad){if(lastDevice!==null){lastDevice=null;lastPad=null;used=false;reset();if(api.playing())api.pause();}badge.textContent='Xbox controller: press a button to connect';frameInput=null;return;}
   const identity=pad.index+':'+pad.id;if(identity!==lastDevice){reset();lastDevice=identity;}lastPad=pad;
   data=sampler.read(pad,identity,false,menuRoot?{}:api.settings.controller);badge.textContent='Xbox / standard controller connected';
  }
  if(!data){frameInput=null;return;}
  if(data.move?.some(Boolean)||data.look?.some(Boolean)||Object.values(data.held).some(Boolean)||Object.values(data.edges).some(Boolean)){lastActivity=now;used=true;}
  if(menuRoot){if(!xr.active&&menuRoot.id==='power-wheel'&&Math.hypot(...data.move)>.65){const choices=[...menuRoot.querySelectorAll('[data-power]:not(:disabled)')],angle=(Math.atan2(data.move[0],-data.move[1])+Math.PI*2)%(Math.PI*2),i=Math.round(angle/(Math.PI*2)*choices.length)%choices.length;choices[i]?.focus({preventScroll:true});data={...data,move:[0,0]};}nav.tick(data,dt,now/1000,xr.active);frameInput=null;return;}
  if(!api.playing()||api.paused()||document.hidden){frameInput=null;return;}
  if(data.edges.pause){api.pause();frameInput=null;return;}if(data.edges.map){api.map();frameInput=null;return;}
  if(!xr.active){if(data.edges.back)api.action('stance');if(data.edges.boost&&api.state().p.scoped&&api.state().p.weapon==='sniper'){api.action('zoom');data.edges.boost=false;}const profile=api.settings.controller;if(profile.toggleSprint){if(data.edges.boost)sprint=!sprint;data.held.boost=sprint;}if(profile.toggleAim){if(data.edges.aim)aim=!aim;data.held.aim=aim;}
   api.state().p.yaw+=data.look[0]*dt*2.2*(api.settings.controllerSpeed||1)*(api.state().p.scoped?.35:1);api.state().p.pitch=clamp(api.state().p.pitch-data.look[1]*dt*1.6*(api.settings.controllerSpeed||1)*(api.settings.invertY?-1:1)*(api.state().p.scoped?.35:1),-1.35,1.35);
  }
  if(xr.active){for(const name of ['jump','interact','reload','pulse','reverse','next','previous','shop','field','survey'])if(data.edges[name]){api.action(name==='reverse'&&!api.state().p.rail?'power-next':name);if(api.paused()){frameInput=null;return;}}}
  else{for(const [edge,name]of Object.entries({jump:'traverse',interact:'next',survey:'melee',next:'navigate',previous:'survey',shop:'shop',field:'field'}))if(data.edges[edge]){api.action(name);if(api.paused()){frameInput=null;return;}}for(const name of gestures.step(data.held,gestureDt)){api.action(name);if(api.paused()){frameInput=null;return;}}}
  frameInput=data;
 }
 function merge(base){if(!frameInput)return xr.active?{...base,railCamera:false}:base;const[x,y]=frameInput.move;return{...base,moveX:clamp((base.right?1:0)-(base.left?1:0)+x,-1,1),moveZ:clamp((base.forward?1:0)-(base.back?1:0)-y,-1,1),back:base.back||y>.25,boost:base.boost||frameInput.held.boost,railCamera:xr.active?false:base.railCamera};}
 function updateHints(){const hints=$('controller-gameplay-hints');if(hints)hints.hidden=!used||xr.active||!api.playing()||api.paused();if(!used||xr.active||!api.playing())return;const s=api.state(),rewrite=id=>{const e=$(id);if(e)e.textContent=e.textContent.replace(/E \/ /g,label('reload')+' / ').replace(/^E[: ]/g,label('reload')+' ').replace(/\bSpace\b/g,label('jump'));};rewrite('interaction');rewrite('transfer-help');$('weapon-status').textContent=s.p.reload>0?'RELOADING':`${label('fire')}: fire / ${label('reload')}: reload / ${label('aim')}: aim`;
  const p=$('field-power');if(p)p.textContent=p.textContent.replace(/^Q /,label('pulse')+' ');for(const[id,action,text]of [['field-open','field','Field rig'],['field-cycle','reverse','Power'],['field-scan','previous','Survey'],['buy-button','shop','Outfitters / loadout'],['scope-button','aim','Aim / scope'],['swap-button','interact','Swap carried weapon']]){const e=$(id);if(e)e.textContent=label(action)+' / '+text;}
  $('skyward-hud').querySelector('.eyebrow').textContent='ADVENTURES / MENU > JOURNAL';$('expedition-button').textContent='Menu / Adventures';$('pause-button').textContent='Menu / Pause';$('map-button').textContent='View / Atlas';const h=$('controller-gameplay-hints');if(h){h.hidden=api.paused();h.textContent=s.p.climb?`Left stick up / down: climb  ${label('jump')}: jump clear  ${label('back')}: let go`:s.p.rail?`${label('jump')} release / aimed plunge  Stick: accelerate / brake / reverse  ${label('boost')} boost`:s.p.gliding?`${label('back')} foldwing  Left stick steers / down brakes  ${label('jump')} catch aimed rail`:`${label('jump')} jump / aimed hook  ${label('reload')} use / reload  ${label('interact')} swap  ${label('back')} crouch  ${label('survey')} melee`;}}
 const hints=document.createElement('div');hints.id='controller-gameplay-hints';hints.hidden=true;$('hud').append(hints);
 window.addEventListener('blur',reset);document.addEventListener('visibilitychange',reset);window.addEventListener('pointerdown',()=>used=false);window.addEventListener('keydown',()=>used=false);
 const link=document.createElement('a');link.href='./roadmap.html';link.textContent='Development roadmap';link.className='roadmap-link';document.querySelector('.start-actions').append(link);
 return{frame,merge,xr,reset,label,updateHints,openGuide,effect:e=>{if(['shot','hit','hook','damage','shield-break','plunge-hit','expedition-complete'].includes(e.type))rumble(['damage','shield-break','plunge-hit'].includes(e.type)?.4:e.type==='expedition-complete'?.22:.1,e.type==='shot'?35:110);},get aimHeld(){return !!frameInput?.held.aim},get firing(){return !!frameInput?.held.fire&&(!xr.active||!!xr.aim)},get powerAim(){return xr.active?xr.powerAim:null},get aim(){return xr.active?xr.aim:null},snapshot:()=>({gamepad:!!lastDevice,xr:xr.active,lastActivity,move:frameInput?.move||[0,0],xrPhysicalQA:false,controllerPhysicalQA:false,menu:api.topDialog()?.id||(!api.playing()?'menu':null),focus:document.activeElement?.id||document.activeElement?.dataset?.track||'',sprint,aim,profile:JSON.parse(JSON.stringify(api.settings.controller))})};
}
