/* Passive canopy art and explicit actions; all movement is owned by model.mjs. */
import {T} from './scene.mjs';
export function installFlightUI(api){
 const toggle=document.createElement('button');toggle.id='glide-button';toggle.textContent='G · Foldwing';toggle.title='In midair: G or Xbox B opens/folds. Steer with movement; S/left stick back brakes.';document.getElementById('combat-tools').append(toggle);toggle.onclick=()=>{api.action('glide');document.getElementById('world').focus({preventScroll:true});};
 const meter=document.createElement('div');meter.id='glide-status';meter.hidden=true;meter.setAttribute('role','status');meter.innerHTML='<b>FOLDWING</b><progress max="100" value="100" aria-label="Foldwing charge"></progress><span></span>';document.getElementById('hud').append(meter);
 const css=document.createElement('style');css.textContent='#glide-status{position:absolute;bottom:89px;left:50%;transform:translateX(-50%);display:flex;align-items:center;gap:9px;padding:8px 14px;background:#123843eb;border:1px solid #b9d8aa;border-radius:5px;font:10px system-ui;color:#d9efc8;max-width:95%;white-space:nowrap}#glide-status progress{width:90px;height:7px;accent-color:#8bd7b4}@media(max-width:680px){#glide-status{bottom:292px;font-size:9px;padding:6px;gap:5px}#glide-status progress{width:55px}}body:has(#scope-view:not([hidden])) #glide-status{visibility:hidden}.in-xr #glide-status{visibility:hidden}';document.head.append(css);
 const wing=new T.Group();wing.name='Foldwing visual only';api.view.scene.add(wing);const mat=new T.MeshStandardMaterial({color:0x507f82,metalness:.12,roughness:.65,side:T.DoubleSide});const sparMat=new T.MeshStandardMaterial({color:0xd6b46e,metalness:.65,roughness:.3});
 for(const sign of[-1,1]){const shape=new T.Shape();shape.moveTo(sign*.22,-.3);shape.lineTo(sign*2.5,-.05);shape.lineTo(sign*2.0,1.7);shape.lineTo(sign*.24,.65);shape.closePath();const mesh=new T.Mesh(new T.ShapeGeometry(shape),mat);mesh.rotation.x=Math.PI/2;wing.add(mesh);for(const z of[-.25,.5]){const rod=new T.Mesh(new T.CylinderGeometry(.025,.025,2.2,6),sparMat);rod.rotation.z=Math.PI/2;rod.position.set(sign*1.3,.025,z);wing.add(rod);}}
 let spread=0;
 return {update(){const s=api.state(),p=s.p,live=api.playing(),on=live&&p.gliding;spread+=(Number(on)-spread)*.18;wing.visible=live&&spread>.025;wing.position.set(p.x,p.y+1.05,p.z);wing.rotation.y=-Math.atan2(p.vx,-p.vz);wing.scale.set(spread,.6,1);meter.hidden=!live||api.paused()||(!on&&p.glideCharge>=99.9)||!!api.xr();meter.querySelector('progress').value=p.glideCharge;meter.querySelector('span').textContent=on?`${Math.ceil(p.glideCharge)}% · ${Math.round(Math.hypot(p.vx,p.vz)*3.6)} km/h · G/B fold`:`${Math.ceil(p.glideCharge)}% · land or hook to recharge`;toggle.textContent=on?'G · Fold canopy':'G · Foldwing';if(on&&!api.paused()){const help=document.getElementById('transfer-help');help.hidden=false;help.textContent='GLIDE · movement steers · S brakes · aim + E catches a nearby rail · G/B folds';}}};
}
