/* All controls participate in the game's existing Xbox/keyboard/hand focus model. */
import {DIORAMA_KEY,cleanDiorama} from './diorama-core.mjs';
export function createPresentationUI(api,{change,preview,recenter,active}){
 let config;try{config=cleanDiorama(JSON.parse(localStorage.getItem(DIORAMA_KEY)||'null'));}catch{config=cleanDiorama();}
 const dialog=document.createElement('dialog');dialog.id='presentation-dialog';dialog.setAttribute('aria-labelledby','presentation-title');
 dialog.innerHTML='<p class="eyebrow">VIEW THE SAME EXPEDITION</p><h2 id="presentation-title">A city in your hands.</h2><p>Play first-person VR, or first- or third-person gameplay inside a room-fixed AR window. The courier stays centered while the world moves around them. Looking around never moves or aims the courier. In AR windows, left stick moves, right stick aims, right trigger fires, left trigger gives fine aim, B reloads, right grip uses, A jumps, X swaps weapons, left grip uses the selected power, and Y pauses. Xbox keeps its saved mappings. Hands operate menus only. Choose a session type before entering XR.</p><div class="settings-grid"><label>XR presentation<select id="xr-presentation" aria-label="XR presentation"><option value="first-person-vr">First-person VR</option><option value="diorama-vr">Third-person diorama VR</option><option value="diorama-ar">Third-person diorama AR / passthrough</option><option value="first-person-ar">First-person diorama AR / passthrough window</option></select></label><label>Open sides<select id="diorama-opening" aria-label="Diorama open sides"><option value="both">Open top and front</option><option value="top">Open top, closed front</option><option value="front">Open front, closed top</option></select></label><label>Miniature scale<input id="diorama-scale" aria-label="Miniature scale" type="range" min="0.02" max="0.055" step="0.005"></label><label>Table height in meters<input id="diorama-height" aria-label="Table height" type="range" min="0.35" max="1.15" step="0.05"></label></div><p id="diorama-description" class="fine"></p><button id="diorama-left">Rotate table left</button><button id="diorama-right">Rotate table right</button><button id="diorama-center">Recenter table</button><button id="diorama-preview">Start desktop diorama preview</button><button id="diorama-flat">Return to first-person desktop</button><form method="dialog"><button id="presentation-back">Back</button></form>';
 document.body.append(dialog);const $=id=>document.getElementById(id);
 function fill(){ $('xr-presentation').value=config.mode;$('diorama-opening').value=config.opening;$('diorama-scale').value=config.scale;$('diorama-height').value=config.height;const xr=active();$('xr-presentation').disabled=xr;$('diorama-preview').disabled=xr;$('diorama-flat').disabled=xr;$('diorama-description').textContent=`Table footprint ${(60*config.scale).toFixed(2)} by ${(48*config.scale).toFixed(2)} meters. Side and rear faces reveal the distant world; the frame has no filled glass faces. At least one top/front opening stays open. Recenter places the table in front of your current view. Diorama AR uses local-floor placement; first-person AR now shows the normal player-eye camera inside the same window, not life-size scenery across your room. Neither AR mode senses real obstacles. Keep your physical play area clear. ${xr?'Exit XR before changing session type.':'The desktop preview needs no headset.'}`; }
 function save(){config=cleanDiorama(config);try{localStorage.setItem(DIORAMA_KEY,JSON.stringify(config));}catch{}fill();change(config);}
 for(const[id,key]of [['xr-presentation','mode'],['diorama-opening','opening'],['diorama-scale','scale'],['diorama-height','height']])$(id).addEventListener(key==='scale'||key==='height'?'input':'change',e=>{config[key]=e.target.type==='range'?Number(e.target.value):e.target.value;save();});
 $('diorama-left').onclick=()=>{config.yaw-=Math.PI/6;save();};$('diorama-right').onclick=()=>{config.yaw+=Math.PI/6;save();};$('diorama-center').onclick=recenter;
 $('diorama-preview').onclick=()=>preview(true);$('diorama-flat').onclick=()=>preview(false);
 function open(){fill();api.show('presentation-dialog');}
 for(const[target,id]of [['.start-actions','presentation-button'],['#pause-dialog','pause-presentation'],['#settings-dialog','settings-presentation']]){const parent=document.querySelector(target);if(!parent)continue;const b=document.createElement('button');b.id=id;b.textContent='XR / diorama views';b.onclick=open;parent.append(b);}
 fill();return {get config(){return {...config}},refresh:fill,open};
}
