const key='aether-reach.roadmap.v1',states=['Planned','Implemented','In review','Browser checked','Hardware QA','Released','Deferred'];
const $=id=>document.getElementById(id);let edits={};try{edits=JSON.parse(localStorage.getItem(key)||'{}');if(!edits||typeof edits!=='object'||Array.isArray(edits))edits={};}catch{}
let data;try{const r=await fetch('./roadmap.json');if(!r.ok)throw Error('HTTP '+r.status);data=await r.json();}catch(e){$('status').textContent='Roadmap could not load: '+e.message;throw e;}
for(const phase of new Set(data.tasks.map(t=>t.phase))){const o=document.createElement('option');o.value=o.textContent=phase;$('phase').append(o);}
function save(){try{localStorage.setItem(key,JSON.stringify(edits));$('status').textContent='Local board saved. GitHub and the game were not changed.';}catch{$('status').textContent='Storage is unavailable. Export the board to retain edits.';}}
function current(t){return states.includes(edits[t.id])?edits[t.id]:t.status;}
function draw(){const q=$('search').value.toLowerCase(),phase=$('phase').value;const tasks=data.tasks.filter(t=>(!phase||t.phase===phase)&&JSON.stringify(t).toLowerCase().includes(q));$('board').replaceChildren();$('stats').textContent=`${data.tasks.length} tracked upgrades · ${data.tasks.filter(t=>current(t)==='Hardware QA').length} hardware gates open · source updated ${data.updated}`;
 const lanes=[['Backlog',['Planned','Deferred']],['Implementation',['Implemented']],['Validation',['In review','Browser checked']],['Physical device gates',['Hardware QA']],['Released',['Released']]];
 for(const [title,statuses] of lanes){const col=document.createElement('section');col.className='column';const list=tasks.filter(t=>statuses.includes(current(t))),h=document.createElement('h2');h.textContent=title+' · '+list.length;col.append(h);
  for(const t of list){const card=document.createElement('article');card.className='card';const tag=document.createElement('span');tag.className='tag';tag.textContent=t.id+' / '+t.phase+' / '+t.priority;const title=document.createElement('h3');title.textContent=t.title;const p=document.createElement('p');p.textContent=t.acceptance;const deps=document.createElement('div');deps.className='dependencies';deps.textContent='Depends on: '+(t.depends.join(', ')||'—');const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Evidence and next action';details.append(summary);const evidence=document.createElement('p');evidence.textContent=t.evidence;const next=document.createElement('p');next.textContent='Next: '+t.next;details.append(evidence,next);const select=document.createElement('select');select.setAttribute('aria-label','Status for '+t.id);for(const state of states){const o=document.createElement('option');o.value=o.textContent=state;select.append(o);}select.value=current(t);select.onchange=()=>{edits[t.id]=select.value;save();draw();};card.append(tag,title,p,deps,details,select);col.append(card);}
  $('board').append(col);
 }
}
$('search').oninput=draw;$('phase').onchange=draw;$('reset').onclick=()=>{if(confirm('Reset local roadmap edits to the committed plan?')){edits={};save();draw();}};$('export').onclick=()=>{const text=JSON.stringify({...data,localOnly:true,tasks:data.tasks.map(t=>({...t,status:current(t)}))},null,2),a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=u;a.download='aether-reach-roadmap.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};draw();
for(const [href,title]of [['./planning/Aether-Reach-Development-Roadmap-v0.3.xlsx','Workbook archive · v0.3'],['https://github.com/v5ma/v5ma.github.io/releases','Versioned source backups']]){const a=document.createElement('a');a.href=href;a.textContent=title;document.querySelector('.controls').append(a);}
