import * as T from './vendor/three.module.js';
import {COMBAT_DECKS,RIFTS} from './skirmish-world.mjs';
import {COMBAT_COVER,equip,combatCrouch,combatMelee,combatUse,combatTrap,combatZoom,combatTraverse,combatRecentPower,fieldChoose} from './model.mjs';
export function installSkirmishUI(api){
 const $=id=>document.getElementById(id),scene=api.view?.scene;let wheel=null,scope=null,nav=null;
 const settingsGrid=document.querySelector('.settings-grid');if(settingsGrid&&!document.getElementById('audio-master')){for(const [key,label] of [['master','Master volume'],['effects','Effects volume'],['music','Music volume'],['ambience','Ambience volume']]){const row=document.createElement('label'),input=document.createElement('input');row.textContent=label;input.id='audio-'+key;input.type='range';input.min='0';input.max='1';input.step='.05';input.value=api.settings.audio[key];input.oninput=()=>{api.settings.audio[key]=Number(input.value);api.saveSettings();api.audio.unlock();};row.append(input);settingsGrid.append(row);}const row=document.createElement('label'),night=document.createElement('input');night.id='audio-night';night.type='checkbox';night.checked=api.settings.audio.night;night.onchange=()=>{api.settings.audio.night=night.checked;api.saveSettings();};row.append(night,document.createTextNode(' Night audio / reduced dynamic range'));settingsGrid.append(row);}
 if(scene){const coverMat=new T.MeshStandardMaterial({color:'#8a7257',roughness:.9}),wallMat=new T.MeshStandardMaterial({color:'#c2af91',roughness:.95}),deckMat=new T.MeshStandardMaterial({color:'#b9aa8f',roughness:.92});
  for(const d of COMBAT_DECKS){const m=new T.Mesh(new T.BoxGeometry(d.w,.55,d.d),deckMat);m.position.set(d.x,d.y-.28,d.z);m.receiveShadow=true;scene.add(m);}
  for(const c of COMBAT_COVER){const m=new T.Mesh(new T.BoxGeometry(c.w,c.h,c.d),c.kind==='wall'?wallMat:coverMat);m.position.set(c.x,c.y+c.h/2,c.z);m.castShadow=m.receiveShadow=true;scene.add(m);}
  for(const r of RIFTS){const g=new T.BoxGeometry(r.w,r.h,r.d),mat=new T.MeshBasicMaterial({color:r.type==='medical'?'#7ce4c7':r.type==='turret'?'#f2bd69':'#9ed5eb',wireframe:true,transparent:true,opacity:.35}),m=new T.Mesh(g,mat);m.position.set(r.x,r.y+r.h/2,r.z);scene.add(m);}
 }
 scope=document.createElement('div');scope.id='crosswind-scope';scope.hidden=true;scope.innerHTML='<div></div><span id="crosswind-zoom">4x</span>';document.body.append(scope);
 nav=document.createElement('div');nav.id='crosswind-nav';nav.hidden=true;document.body.append(nav);
 const style=document.createElement('style');style.textContent='#crosswind-scope{position:fixed;inset:0;z-index:45;pointer-events:none;background:radial-gradient(circle at center,transparent 0 31%,#020708ee 32% 100%)}#crosswind-scope>div{position:absolute;left:50%;top:50%;width:62vmin;height:62vmin;transform:translate(-50%,-50%);border:3px solid #d9d7c9;border-radius:50%;box-shadow:inset 0 0 55px #0009}#crosswind-scope>div:before,#crosswind-scope>div:after{content:"";position:absolute;background:#d9d7c9aa;left:50%;top:0;transform:translateX(-50%);width:1px;height:100%}#crosswind-scope>div:after{top:50%;left:0;width:100%;height:1px;transform:translateY(-50%)}#crosswind-zoom{position:absolute;left:50%;top:calc(50% + 24vmin);transform:translateX(-50%);color:#e9d9ad;font:700 13px system-ui}#crosswind-nav{position:fixed;left:50%;bottom:13%;transform:translateX(-50%);z-index:44;color:#f8e6a8;background:#102d3bd9;border:1px solid #d3b46d;padding:8px 14px;font:700 12px system-ui;pointer-events:none}';document.head.append(style);
 function openWheel(){if(wheel?.isConnected){api.show(wheel);return true;}wheel=document.createElement('dialog');wheel.id='power-wheel';wheel.innerHTML='<p class="eyebrow">POWER WHEEL</p><h2>Select a left-hand ability</h2><div data-nav-grid="3"></div><form method="dialog"><button>Back</button></form>';const grid=wheel.querySelector('div');for(const id of ['pulse','current','cinder','updraft','override']){const b=document.createElement('button');b.dataset.power=id;b.textContent=id.toUpperCase();b.onclick=()=>{if(fieldChoose(api.state(),id)){api.events();wheel.close();}else api.toast('That power is not unlocked yet.');};grid.append(b);}document.body.append(wheel);api.show(wheel);return true;}
 function action(name){const s=api.state();if(name==='stance')return combatCrouch(s);if(name==='melee')return combatMelee(s);if(name==='use')return combatUse(s,false);if(name==='use-hold')return combatUse(s,true);if(name==='power-tap'){s.skirmish.charging=false;api.action?.('pulse');return false;}if(name==='power-charge'){s.skirmish.charging=true;api.audio?.event({type:'charge'});return true;}if(name==='power-trap')return combatTrap(s);if(name==='power-recent')return combatRecentPower(s);if(name==='power-wheel')return openWheel();if(name==='zoom')return combatZoom(s);if(name==='traverse')return combatTraverse(s);if(name==='navigate'){s.skirmish.navigateUntil=s.time+5;api.toast('Objective route projected for five seconds.');return true;}if(name==='next'){const c=s.kit.carried||[];if(c.length<2)return false;const id=c[(c.indexOf(s.p.weapon)+1)%c.length];return equip(s,id);}return false;}
 function effect(e){if(e.type==='shield-break')api.toast('SHIELD DOWN',2);if(e.type==='companion-offer')api.toast('TAVI has '+e.resource+'. Tap X to catch it.',3);if(e.type==='arena-wave')api.toast('COMBAT WAVE '+e.number+' / 2',2);}
 function update(){const s=api.state(),zoom=s.skirmish?.scopeZoom||4;scope.hidden=!(api.playing()&&!api.paused()&&s.p.weapon==='sniper'&&s.p.scoped);$('crosswind-zoom').textContent=zoom+'x';if(!scope.hidden){api.view.camera.fov=Math.max(9,api.settings.fov/zoom);api.view.camera.updateProjectionMatrix();}nav.hidden=!(s.skirmish?.navigateUntil>s.time);if(!nav.hidden){const g=s.relays.size===3?'Return to Arrival Quay':'Follow the next relay / tracked adventure';nav.textContent='▲ '+g;}}
 return{action,effect,update};
}
