import {COMBAT_DECKS,ARENA_TASKS,ARENA_CONSOLES,ARENA_SPAWNS,RIFTS,ARENA_LOADOUTS,asBox} from './skirmish-world.mjs';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z),flat=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export const eyeHeight=p=>p.crouched?.90:1.65;
export function cleanSkirmish(v){v=v&&typeof v==='object'?v:{};return{version:1,aidUsed:Number.isFinite(v.aidUsed)?clamp(Math.floor(v.aidUsed),0,3):0,scopeZoom:v.scopeZoom===8?8:4};}
export const riftSolid=s=>{const r=s?.skirmish?.rift;return r?.type==='cover'&&r.life>0?[asBox(r)]:[];};
export function createSkirmish({groundAt,occupied,clearLine,forward,emit,defeated,equip,weaponStats,weapons,nearby,interact,reload,detach,cover}){
 const eye=s=>({...s.p,y:s.p.y+eyeHeight(s.p)});
 function init(s,save){s.skirmish={...cleanSkirmish(save),companion:{x:s.p.x-1.6,y:s.p.y,z:s.p.z+1.2,path:[],flying:false},offer:null,aidCooldown:2,trapSerial:0,traps:[],charging:false,rift:null,riftCooldown:0,meleeCooldown:0,meleeFlash:0,plunge:null,navigateUntil:0,navPath:[],gunDrops:[],gunSerial:0,battle:{phase:'idle',id:null,wave:0,time:0,hold:0},metrics:{melee:0,plunges:0,traps:0,riftUses:0,catches:0},recentPowers:['pulse'],recoil:{x:0,y:0,index:0},dryAt:-1};s.p.crouched=false;}
 function damage(s,b,amount,source){if(!b||b.hp<=0)return;b.hp-=amount;b.stun=Math.max(b.stun||0,.2);emit(s,'hit',{id:b.id,damage:amount,source,at:{x:b.x,y:b.y,z:b.z}});if(b.hp<=0)defeated(s,b);}
 function target(s,range=3,cone=.70){const o=eye(s),d=forward(s.p.yaw,s.p.pitch);let best=null,nearest=range;for(const b of s.drones){if(b.hp<=0||b.allyUntil>s.time)continue;const length=dist(o,b),dot=((b.x-o.x)*d.x+(b.y-o.y)*d.y+(b.z-o.z)*d.z)/(length||1);if(length<nearest&&dot>cone&&clearLine(o,b,s)){best=b;nearest=length;}}return best;}
 function crouch(s){if(s.p.rail||s.p.ride||s.p.climb||!s.p.grounded)return false;if(s.p.crouched){s.p.crouched=false;if(occupied(s.p.x,s.p.y,s.p.z,s)){s.p.crouched=true;return false;}}else s.p.crouched=true;emit(s,'stance',{crouched:s.p.crouched});return true;}
 function melee(s){const k=s.skirmish;if(s.won||k.meleeCooldown>0||s.p.climb)return false;k.meleeCooldown=.65;k.meleeFlash=.32;const b=target(s,3,.60);if(b){damage(s,b,b.kind==='breacher'?38:64,'melee');k.metrics.melee++;}emit(s,'melee',{hit:!!b});return true;}
 function plungeTarget(s){if(!s.p.rail||s.p.pitch>-.2)return null;const b=target(s,27,.83);return b&&s.p.y-b.y>2?b:null;}
 function plunge(s){const b=plungeTarget(s);if(!b)return false;detach(s,false);s.p.gliding=false;s.p.crouched=false;s.skirmish.plunge={id:b.id,time:0};emit(s,'plunge-start',{id:b.id});return true;}
 function riftTarget(s){if(s.won)return null;const o=eye(s),d=forward(s.p.yaw,s.p.pitch);return RIFTS.map(r=>({r,q:{...r,y:r.y+1.15}})).filter(({q})=>{const l=dist(o,q);return l<26&&l>1.3&&((q.x-o.x)*d.x+(q.y-o.y)*d.y+(q.z-o.z)*d.z)/l>.965&&clearLine(o,q,s);}).sort((a,b)=>dist(o,a.q)-dist(o,b.q))[0]?.r||null;}
 function manifest(s){const k=s.skirmish,r=riftTarget(s),c=k.companion;if(!r||k.riftCooldown>0||dist(s.p,c)>18)return false;const box=asBox(r);if(r.type==='cover'&&s.drones.concat(s.p).some(p=>p.hp!==0&&p.x>box.x1-.6&&p.x<box.x2+.6&&p.z>box.z1-.6&&p.z<box.z2+.6&&Math.abs(p.y-r.y)<r.h+2))return false;
  k.rift={...r,life:35,battery:18,fire:0};k.riftCooldown=2.5;k.metrics.riftUses++;emit(s,'rift',{id:r.id,at:{x:r.x,y:r.y+1,z:r.z}});return true;
 }
 function trap(s){const k=s.skirmish,p=s.p,power=s.tactics.power;k.charging=false;const spec={pulse:[38,4.5],current:[32,5],cinder:[36,4.5],updraft:[36,5],override:[48,4]};
  if(s.won||s.tactics.cooldown>0||(!s.tactics.learned&&power!=='pulse')||k.traps.length>=3||p.energy<spec[power][0])return false;
  const o=eye(s),d=forward(p.yaw,p.pitch),length=p.pitch<-.12?clamp((eyeHeight(p)+.2)/-d.y,2.5,11):4.2,q={x:p.x+d.x*length,y:0,z:p.z+d.z*length},floor=groundAt(q.x,q.z,p.y+2);q.y=floor.y+.05;
  if(!Number.isFinite(q.y)||Math.abs(q.y-p.y)>8||occupied(q.x,q.y,q.z,s)||!clearLine(o,{...q,y:q.y+.25},s))return false;
  p.energy-=spec[power][0];s.tactics.cooldown=.7;k.traps.push({...q,id:++k.trapSerial,power,life:75,armed:.7,r:spec[power][1]});k.metrics.traps++;emit(s,'trap-place',{power,at:q});return true;
 }
 function affect(s,b,power){if(power==='override'){b.allyUntil=s.time+8;b.allyFire=0;}else if(power==='updraft'){b.liftBase=b.liftBase??b.y;b.liftUntil=s.time+3;b.stun=3;damage(s,b,15,'updraft');}else{b.stun=power==='cinder'?.25:3;if(power==='cinder')b.burning=5;if(power==='current')b.shocked=4;damage(s,b,power==='pulse'?48:power==='cinder'?35:42,'trap');}}
 function specialPower(s,power){const cost=power==='updraft'?30:44;if(s.won||!s.tactics.learned||s.tactics.cooldown>0||s.p.energy<cost)return false;const b=target(s,36,.95);if(!b)return false;s.p.energy-=cost;s.tactics.cooldown=power==='override'?3:1.4;affect(s,b,power);emit(s,'tactical-cast',{power,o:eye(s),end:{x:b.x,y:b.y,z:b.z},hit:true});return true;}
 function rememberPower(s,id){const a=s.skirmish.recentPowers;if(a[0]!==id){s.skirmish.recentPowers=[id,...a.filter(x=>x!==id)].slice(0,2);}}
 function recoil(s){const k=s.skirmish.recoil,w=s.p.weapon;k.index++;const pattern=[0,.35,-.4,-.65,.3,.7,.55,-.3,-.65,-.2,.6,.4];k.x=clamp(k.x+(pattern[(k.index-1)%pattern.length])*(w==='carbine'?.007:.003),-.08,.08);k.y=clamp(k.y+(w==='sniper'?.044:w==='scatter'?.035:w==='carbine'?.010:.012)*(s.p.crouched?.75:1),0,.11);}
 function drop(s,b){if(!b.humanoid||s.skirmish.gunDrops.length>=24)return;const id=b.gun||({longshot:'sniper',breacher:'scatter'}[b.kind]||'carbine'),floor=groundAt(b.x,b.z,b.y);if(Number.isFinite(floor.y))s.skirmish.gunDrops.push({id:++s.skirmish.gunSerial,weapon:id,x:b.x,y:floor.y,z:b.z});}
 function gunNear(s){return s.skirmish.gunDrops.find(g=>dist(s.p,g)<2.8&&clearLine(eye(s),{...g,y:g.y+.5},s))||null;}
 function pickup(s){const g=gunNear(s);if(!g)return false;const id=g.weapon,w=weapons[id];if(!s.kit.owns.includes(id)){s.kit.owns.push(id);s.kit.mags[id]=w.mag;s.kit.reserve[id]=w.reserve;s.kit.tune[id]={damage:0,reload:0};}equip(s,id,true);s.skirmish.gunDrops=s.skirmish.gunDrops.filter(d=>d!==g);emit(s,'gun-pickup',{weapon:id});emit(s,'save');return true;}
 function catchOffer(s){const k=s.skirmish,o=k.offer;if(!o||k.aidUsed>=3||dist(s.p,k.companion)>14)return false;if(o.type==='health')s.p.health=Math.min(100,s.p.health+40);else if(o.type==='energy')s.p.energy=Math.min(100,s.p.energy+55);else{const id=s.p.weapon,w=weaponStats(s);if(id==='arc')s.p.ammo=w.mag;else s.kit.reserve[id]=Math.min(weapons[id].reserve*3,s.kit.reserve[id]+w.mag*2);s.kit.mags[id]=s.p.ammo;}
  k.aidUsed++;k.offer=null;k.aidCooldown=24;k.metrics.catches++;emit(s,'companion-catch',{resource:o.type,from:{...k.companion},end:eye(s)});emit(s,'save');return true;}
 function use(s,held=false){if(held){if(riftTarget(s))return manifest(s);if(gunNear(s))return pickup(s);return reload(s);}if(catchOffer(s))return true;const n=nearby(s);if(n&&n.type!=='rail'&&!(n.type==='exit'&&s.relays.size<3))return interact(s);return reload(s);}
 function nearConsole(s){return ARENA_CONSOLES.find(c=>s.p.grounded&&!s.p.rail&&dist(s.p,c)<3&&clearLine(eye(s),{...c,y:c.y+1},s))||null;}
 function start(s,id){const c=nearConsole(s),k=s.skirmish;if(!c||c.id!==id||k.battle.phase==='active'||s.won)return false;s.drones=s.drones.filter(b=>!b.arena);k.gunDrops=[];k.battle={id:id.slice(6),phase:'active',time:0,wave:0,hold:0,next:0};emit(s,'arena-start',{id:k.battle.id});return true;}
 function killed(s,b){if(!b.arena)return false;if(b.credited)return true;b.credited=true;s.stats.defeated++;drop(s,b);emit(s,'defeat',{id:b.id,at:{x:b.x,y:b.y,z:b.z}});return true;}
 function abort(s){const k=s.skirmish;if(!k)return;k.traps=[];k.rift=null;k.offer=null;k.charging=false;k.plunge=null;k.recoil.x=k.recoil.y=0;s.p.crouched=false;s.drones=s.drones.filter(b=>!b.arena);if(k.battle.phase==='active'){k.battle.phase='interrupted';emit(s,'arena-end',{reason:'interrupted'});}k.companion={x:s.p.x-1.5,y:s.p.y,z:s.p.z+1,path:[],flying:false};}
 function step(s,dt){const k=s.skirmish,p=s.p;if(!k)return;for(const n of ['aidCooldown','meleeCooldown','meleeFlash','riftCooldown'])k[n]=Math.max(0,k[n]-dt);k.recoil.x*=Math.exp(-dt*8);k.recoil.y*=Math.exp(-dt*6);if(p.shoot===0)k.recoil.index=0;
  const c=k.companion,trail=c.path,last=trail.at(-1)||c;if(dist(last,p)>.9)trail.push({x:p.x,y:p.y,z:p.z});if(trail.length>220)trail.shift();if(trail.length>3||dist(c,p)>4){const q=trail[0]||p,l=dist(c,q),f=Math.min(1,dt*(p.rail?90:9)/(l||1));c.x+=(q.x-c.x)*f;c.y+=(q.y-c.y)*f;c.z+=(q.z-c.z)*f;c.heading=Math.atan2(q.x-c.x,-(q.z-c.z));if(l<.3)trail.shift();}c.flying=!!p.rail||Math.abs(groundAt(c.x,c.z,c.y+.6).y-c.y)>1;
  if(!k.offer&&k.aidCooldown===0&&k.aidUsed<3&&s.time-s.damagedAt<12&&dist(p,c)<12){const w=weaponStats(s),type=p.health<42?'health':p.ammo===0&&(p.weapon==='arc'||s.kit.reserve[p.weapon]<w.mag)?'ammo':p.energy<25?'energy':null;if(type){k.offer={type,life:10};emit(s,'companion-offer',{resource:type,at:{x:c.x,y:c.y+1,z:c.z}});}}
  if(k.offer){k.offer.life-=dt;if(k.offer.life<=0){k.offer=null;k.aidCooldown=4;}}
  for(const b of s.drones){if(b.liftUntil){if(b.liftUntil>s.time&&b.hp>0){b.y=b.liftBase+Math.sin(Math.min(1,(b.liftUntil-s.time)/.4)*Math.PI/2)*2.5;b.stun=Math.max(b.stun,.1);}else{b.y=b.liftBase;delete b.liftUntil;delete b.liftBase;}}
   if(b.allyUntil>s.time&&b.hp>0){b.stun=Math.max(b.stun,.1);b.allyFire=(b.allyFire||0)-dt;const victim=s.drones.find(v=>v!==b&&v.hp>0&&!(v.allyUntil>s.time)&&dist(v,b)<30&&clearLine(b,v,s));if(victim&&b.allyFire<=0){damage(s,victim,18,'override');b.allyFire=.8;emit(s,'ally-shot',{o:{x:b.x,y:b.y,z:b.z},end:{x:victim.x,y:victim.y,z:victim.z}});}}
  }
  for(let i=k.traps.length-1;i>=0;i--){const t=k.traps[i];t.life-=dt;t.armed-=dt;const targets=s.drones.filter(b=>b.hp>0&&!(b.allyUntil>s.time)&&dist(t,b)<t.r&&clearLine({...t,y:t.y+.3},b,s));if(t.armed<=0&&targets.length){for(const b of targets)affect(s,b,t.power);emit(s,'trap-trigger',{power:t.power,at:{x:t.x,y:t.y,z:t.z}});t.life=0;}if(t.life<=0)k.traps.splice(i,1);}
  if(k.rift){const r=k.rift;r.life-=dt;if(r.type==='medical'&&flat(p,r)<3&&Math.abs(p.y-r.y)<2)p.health=Math.min(100,p.health+6*dt);if(r.type==='turret'){r.fire-=dt;const o={x:r.x,y:r.y+1.6,z:r.z},b=s.drones.find(b=>b.hp>0&&!(b.allyUntil>s.time)&&dist(o,b)<34&&clearLine(o,b,s));if(b&&r.battery>0&&r.fire<=0){r.battery--;r.fire=.6;damage(s,b,23,'rift');emit(s,'ally-shot',{o,end:{x:b.x,y:b.y,z:b.z}});}}if(r.life<=0)k.rift=null;}
  if(k.plunge){const a=k.plunge,b=s.drones.find(b=>b.id===a.id&&b.hp>0);a.time+=dt;if(!b||a.time>3||!clearLine(eye(s),b,s)){k.plunge=null;}else if(dist(p,b)<2.7){damage(s,b,190,'plunge');k.metrics.plunges++;k.meleeFlash=.5;for(const v of s.drones)if(v!==b&&v.hp>0&&dist(v,b)<4&&clearLine(b,v,s))damage(s,v,45,'plunge');emit(s,'plunge-hit',{at:{x:b.x,y:b.y,z:b.z}});k.plunge=null;}else{const l=flat(p,b)||1;p.vx+=(b.x-p.x)/l*dt*30;p.vz+=(b.z-p.z)/l*dt*30;p.vy=Math.min(p.vy,-13);}}
  const battle=k.battle;if(battle.phase==='active'){battle.time+=dt;const d=COMBAT_DECKS.find(d=>d.id===battle.id),c=ARENA_CONSOLES.find(c=>c.id==='arena-'+d.id),live=s.drones.filter(b=>b.arena&&b.hp>0);if(flat(p,d)>48||Math.abs(p.y-d.y)>24){abort(s);return;}
   if(live.length===0&&battle.wave<2){battle.next-=dt;if(battle.next<=0){const spots=ARENA_SPAWNS.find(a=>a.id===d.id).points;battle.wave++;for(let i=0;i<3;i++){const [x,y,z]=spots[i],kind=['warden','skirmisher',battle.wave===2?'breacher':'longshot'][i],hp=kind==='breacher'?155:kind==='longshot'?78:95;s.drones.push({id:'arena-'+d.id+'-'+battle.wave+'-'+i,arena:true,humanoid:true,home:d.home,arenaHome:d,x,y,z,hp,maxHp:hp,stun:0,attack:1.6+i*.65,telegraph:0,reward:0,gun:ARENA_LOADOUTS[i],patrol:[[x,z],[x+(i===1?2:-2),z+3]],range:38,projectileSpeed:kind==='longshot'?36:24,shotDamage:kind==='longshot'?24:12,attackDelay:kind==='skirmisher'?1.2:2.4,chaseSpeed:kind==='breacher'?2:3,origin:{x,y,z}});}battle.next=2;emit(s,'arena-wave',{number:battle.wave,at:{x:d.x,y:d.y,z:d.z}});}}
   else if(live.length===0&&battle.wave===2){if(flat(p,c)<4)battle.hold+=dt;if(battle.hold>=5){battle.phase='complete';const t=ARENA_TASKS.find(t=>t.id==='arena-'+d.id);if(!s.expedition.flags.includes(t.flag)){s.expedition.flags.push(t.flag);s.kit.credits=Math.min(99999,s.kit.credits+t.reward);emit(s,'expedition-complete',{id:t.id,name:t.name,credits:t.reward});emit(s,'save');}emit(s,'arena-end',{reason:'complete'});}}
  }
 }
 return{init,step,target,crouch,melee,plunge,plungeTarget,riftTarget,manifest,trap,specialPower,rememberPower,recoil,drop,gunNear,pickup,catchOffer,use,nearConsole,start,killed,abort};
}
