import {SHOTS,SCORE,cleanAudio,spatialMix,musicNotes} from './sound-design.mjs';
/* One context, four buses, bounded voices. Every source disconnects on end.
 * Browser autoplay restrictions are reported rather than silently bypassed. */
export function createSoundscape({settings,state,clearLine}){
 let ctx=null,master,fx,music,ambience,compressor,wind,rail,windFilter,railOsc,noiseBuffer,impulse,reverb,send,analyser;
 let nextBeat=0,beat=0,active=false,wasRunning=false,stepDistance=0,railDistance=0,lastPos=null,lastShot=-1,lastReload=null,heartbeatAt=0,lastResume=-1000,threat=0,mode='calm';
 const voices=new Set(),counts={},pending=new Set();let total=0;
 const options=()=>cleanAudio(settings.audio),freq=n=>440*2**((n-69)/12);
 const gainTo=(n,v,t=.04)=>n?.gain.setTargetAtTime(v,ctx.currentTime,t);
 function build(){if(ctx)return true;const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AC)return false;ctx=new AC();master=ctx.createGain();fx=ctx.createGain();music=ctx.createGain();ambience=ctx.createGain();compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-15;compressor.knee.value=22;compressor.ratio.value=5;compressor.attack.value=.004;compressor.release.value=.19;analyser=ctx.createAnalyser();analyser.fftSize=256;fx.connect(master);music.connect(master);ambience.connect(master);master.connect(compressor);compressor.connect(analyser);analyser.connect(ctx.destination);
  let seed=92371;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296*2-1;};noiseBuffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);const a=noiseBuffer.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=random();
  impulse=ctx.createBuffer(2,ctx.sampleRate*.65,ctx.sampleRate);for(let ch=0;ch<2;ch++){const a=impulse.getChannelData(ch);for(let i=0;i<a.length;i++)a[i]=random()*(1-i/a.length)**3*.12;}
  reverb=ctx.createConvolver();reverb.buffer=impulse;send=ctx.createGain();send.gain.value=.10;fx.connect(send);send.connect(reverb);reverb.connect(master);
  wind=ctx.createGain();windFilter=ctx.createBiquadFilter();windFilter.type='lowpass';windFilter.frequency.value=500;const air=ctx.createBufferSource();air.buffer=noiseBuffer;air.loop=true;air.connect(windFilter);windFilter.connect(wind);wind.connect(ambience);wind.gain.value=0;air.start();
  rail=ctx.createGain();railOsc=ctx.createOscillator();railOsc.type='triangle';railOsc.frequency.value=55;railOsc.connect(rail);rail.connect(ambience);rail.gain.value=0;railOsc.start();nextBeat=ctx.currentTime+.1;return true;
 }
 function unlock(){if(!settings.sound)return;try{if(!build())return;if(ctx.state==='suspended'&&performance.now()-lastResume>800){lastResume=performance.now();ctx.resume().catch(()=>{});}}catch{}}
 function dispose(source,nodes){voices.delete(source);for(const n of nodes){try{n.disconnect();}catch{}}}
 function voice({hz=120,endHz=hz,duration=.15,volume=.1,noise=false,cutoff=9000,pan=0,bus=fx,time=ctx?.currentTime||0,type='triangle',attack=.003}){
  if(!ctx||ctx.state!=='running'||voices.size>=64||volume<=0)return;const source=noise?ctx.createBufferSource():ctx.createOscillator(),filter=ctx.createBiquadFilter(),g=ctx.createGain(),p=ctx.createStereoPanner();
  if(noise){source.buffer=noiseBuffer;}else{source.type=type;source.frequency.setValueAtTime(Math.max(20,hz),time);source.frequency.exponentialRampToValueAtTime(Math.max(20,endHz),time+duration);}
  filter.type='lowpass';filter.frequency.value=cutoff;p.pan.value=Math.max(-1,Math.min(1,pan));g.gain.setValueAtTime(.00001,time);g.gain.exponentialRampToValueAtTime(Math.max(.00002,volume),time+Math.min(attack,duration/3));g.gain.exponentialRampToValueAtTime(.00001,time+duration);source.connect(filter);filter.connect(g);g.connect(p);p.connect(bus);source.onended=()=>dispose(source,[source,filter,g,p]);voices.add(source);source.start(time);source.stop(time+duration+.02);total++;
 }
 function ring(hz,duration,volume,pan=0,bus=fx,time=ctx.currentTime){voice({hz,endHz:hz*.998,duration,volume,pan,bus,time,type:'sine'});voice({hz:hz*2.76,endHz:hz*2.76,duration:duration*.4,volume:volume*.14,pan,bus,time});}
 function event(e){if(!active||!settings.sound)return;unlock();if(!ctx||ctx.state!=='running')return;const s=state(),origin=e.at||(e.type==='enemy-shot'?e.o:null),mix=spatialMix(origin,{...s.p,y:s.p.y+1.5},origin&&!clearLine({...s.p,y:s.p.y+1.5},origin,s));if(mix.gain<.008)return;counts[e.type]=(counts[e.type]||0)+1;const v=(p)=>voice({pan:mix.pan,...p,volume:(p.volume||.1)*mix.gain,cutoff:Math.min(p.cutoff||12000,mix.cutoff)}),t=ctx.currentTime;
  if(e.type==='shot'||e.type==='enemy-shot'||e.type==='ally-shot'){
   if(e.type==='shot'){if(lastShot===s.stats.shots)return;lastShot=s.stats.shots;}const q=SHOTS[e.weapon]||SHOTS.carbine,scale=e.type==='shot'?1:.42;v({hz:q.body*1.7,endHz:q.body*.65,duration:q.tail,volume:q.volume*scale});v({noise:true,duration:q.noise,cutoff:q.cutoff,volume:q.volume*scale*.6});if(e.type==='shot'){v({hz:1900,endHz:970,duration:.028,volume:.055,time:t+.045});v({noise:true,duration:.04,volume:.025,time:t+.12});}
  }else if(e.type==='reload-start'){v({noise:true,duration:.07,cutoff:2700,volume:.16});v({hz:260,endHz:90,duration:.09,volume:.12});if(e.weapon!=='arc'){v({noise:true,duration:.06,volume:.11,time:t+e.duration*.6});v({hz:950,endHz:180,duration:.04,volume:.1,time:t+e.duration*.85});}else ring(320,.3,.1);}
  else if(e.type==='reload-end'||e.type==='equip'||e.type==='gun-pickup'){v({hz:650,endHz:200,duration:.035,volume:.13});v({noise:true,duration:.022,volume:.10});}
  else if(e.type==='dry-fire'){v({hz:1550,endHz:230,duration:.025,volume:.1});}
  else if(e.type==='shield-break'){v({noise:true,duration:.48,cutoff:9500,volume:.32});for(let i=0;i<5;i++)v({hz:1600+i*790,endHz:600+i*400,duration:.14+i*.04,volume:.07,time:t+i*.023});v({hz:65,endHz:30,duration:.4,volume:.15});}
  else if(e.type==='damage'){v({hz:90,endHz:40,duration:.15,volume:.2});}
  else if(e.type==='hit'){ring(e.critical?1200:780,.05,.065,mix.pan);}
  else if(e.type==='ricochet'){v({hz:2500,endHz:370,duration:.14,volume:.12});v({noise:true,duration:.04,volume:.07});}
  else if(e.type==='step-stone'||e.type==='step-metal'||e.type==='step-wood'){const metal=e.type==='step-metal';v({noise:true,duration:.09,cutoff:metal?2100:800,volume:s.p.crouched?.026:.07});v({hz:metal?320:110,endHz:metal?280:70,duration:metal?.14:.07,volume:.03});}
  else if(['hook','release','reverse','arrive','climb-start','climb-leave'].includes(e.type)){v({hz:e.type==='hook'?450:240,endHz:75,duration:.12,volume:.13});v({noise:true,duration:.08,volume:.10});if(e.type==='arrive')ring(520,.35,.07);}
  else if(['melee','plunge-start','plunge-hit'].includes(e.type)){v({noise:true,duration:.18,cutoff:900,volume:.17});v({hz:e.hit||e.type==='plunge-hit'?85:250,endHz:45,duration:.2,volume:e.type==='plunge-hit'?.4:.18});}
  else if(['tactical-cast','pulse','trap-place','trap-trigger','rift'].includes(e.type)){const fire=e.power==='cinder',hz=fire?65:e.power==='override'?290:140;v({hz,endHz:fire?30:hz*2.8,duration:.38,volume:.18});v({noise:true,duration:fire?.5:.19,cutoff:fire?1200:6500,volume:.20});if(e.type==='rift')for(let i=0;i<3;i++)ring(330*2**(i/3),.8,.075,0,fx,t+i*.06);}
  else if(e.type==='bell-dial'){ring(330*2**((e.value||0)/6),.3,.06,mix.pan);}
  else if(e.type==='bell-stage'||e.type==='bell-wave'){[62,69,74].forEach((n,i)=>ring(freq(n),.45,.06,0,fx,t+i*.10));}
  else if(e.type==='charge'){ring(220,.7,.07);}
  else if(['companion-offer','companion-catch','optic','ui-focus'].includes(e.type)){ring(e.type==='companion-catch'?784:523,.17,e.type==='ui-focus'?.025:.07);}
  else if(['relay','expedition-complete','arena-end','win'].includes(e.type)){[62,66,69,74].forEach((n,i)=>ring(freq(n),.7,.08,0,fx,t+i*.13));}
 }
 function update(s,dt,{playing,paused}){active=playing&&!paused;const o=options();if(!ctx){if(settings.sound&&playing)unlock();return;}if(ctx.state!=='running'){wasRunning=false;return;}if(!wasRunning){nextBeat=ctx.currentTime+.05;wasRunning=true;}gainTo(master,settings.sound?o.master*(playing?(paused?.18:1):0):0);gainTo(fx,o.effects);gainTo(music,o.music);gainTo(ambience,o.ambience);compressor.threshold.setTargetAtTime(o.night?-24:-15,ctx.currentTime,.1);compressor.ratio.setTargetAtTime(o.night?12:5,ctx.currentTime,.1);
  const danger=!!s.bellwether?.encounter||s.skirmish?.battle.phase==='active'||s.tactics.encounter.phase==='active'||s.drones.some(b=>b.hp>0&&b.kind!=='target'&&b.telegraph>.1&&Math.hypot(b.x-s.p.x,b.z-s.p.z)<50);threat+=(Number(danger)-threat)*Math.min(1,dt*2);mode=danger?'combat':s.p.rail?'rail':'calm';const speed=s.p.rail?s.p.speed:Math.hypot(s.p.vx,s.p.vz);gainTo(wind,active?Math.min(.13,.018+speed*.0011):0,.2);windFilter.frequency.setTargetAtTime(300+speed*24,ctx.currentTime,.1);gainTo(rail,active&&s.p.rail?.016+speed*.00045:0,.06);railOsc.frequency.setTargetAtTime(45+speed*3,ctx.currentTime,.09);
  if(!active){nextBeat=ctx.currentTime+.1;lastPos=null;return;}const t=ctx.currentTime;if(nextBeat<t-.4)nextBeat=t+.05;let guard=0;while(nextBeat<t+.09&&guard++<3){for(const n of musicNotes(beat,mode)){if(n.instrument==='pad'){voice({hz:freq(n.note),duration:n.duration,volume:n.gain,attack:.12,type:'sine',bus:music,time:nextBeat});}else ring(freq(n.note),n.duration,n.gain,0,music,nextBeat);}if(threat>.2){if(beat%4===0)voice({hz:90,endHz:35,duration:.17,volume:.11*threat,bus:music,time:nextBeat});if(beat%4===2)voice({noise:true,duration:.08,cutoff:4500,volume:.065*threat,bus:music,time:nextBeat});if(beat%2===1)voice({noise:true,duration:.025,volume:.023*threat,bus:music,time:nextBeat});}beat++;nextBeat+=60/SCORE.bpm/4;}
  if(lastPos){const moved=Math.hypot(s.p.x-lastPos.x,s.p.z-lastPos.z);if(moved<4&&s.p.grounded&&!s.p.rail){stepDistance+=moved;if(stepDistance>1.9){stepDistance=0;event({type:s.p.y>10?'step-metal':s.p.x<-120?'step-wood':'step-stone'});}}if(s.p.rail){railDistance+=moved;if(railDistance>9){railDistance=0;voice({noise:true,duration:.045,cutoff:1800,volume:.045});}}}lastPos={x:s.p.x,z:s.p.z};if(s.p.health<30&&t>heartbeatAt){heartbeatAt=t+1;voice({hz:55,endHz:32,duration:.17,volume:.09});}
 }
 function mute(){active=false;if(ctx)gainTo(master,0,.03);}
 const wake=()=>unlock();globalThis.addEventListener?.('pointerdown',wake);globalThis.addEventListener?.('keydown',wake);globalThis.addEventListener?.('visibilitychange',()=>{if(document.hidden)mute();});
 return{unlock,event,update,mute,stats:()=>({state:ctx?.state||'not-started',voices:voices.size,total,events:{...counts},mode,settings:options(),autoplayBlocked:!!ctx&&ctx.state==='suspended'&&settings.sound}),sample:()=>{if(!analyser)return[];const a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);return [...a];}};
}
