/* Fixed pools and authored surfaces: tactical effects are real scene geometry,
 * not screenshot overlays. Material/state lifetimes are bounded per scene. */
import {FIELD_BENCH,RECOVERY,SECURITY,TURRET,PATCHES,POWERS} from './tactics-core.mjs';
export function tacticsScene(T,{scene,camera,part,box,label,material,movingPart}){
 const steel=material('#365565','metal'),brass=material('#c9a567','metal');
 for(const [p,text]of [[FIELD_BENCH,'FIELD ENGINEERING\nE / BORROW A POWER RIG'],[SECURITY,'SECURITY JUNCTION\nE / REWIRE THE TURRET'],[RECOVERY,'ATRIUM RECOVERY\nE / PREPARE AND DEFEND']]){box(p.x,p.y+.65,p.z,1.4,1.3,.85,'#365565');box(p.x,p.y+1.32,p.z,1.6,.13,1,'#d8b477');const sign=label(text,p.x,p.y+3.2,p.z+.05,2.9,.75,'#213e50','#ffe8b4');if(sign?.material)sign.material.side=T.FrontSide;}
 label('FIELD TRIAL\nWATER + CURRENT / OIL + CINDER',2,5.7,-37,7,1.2,'#244859','#e3f3d3');
 const patches=new Map(),glowGeo=new T.TorusGeometry(1,.025,5,48),fx=[];
 for(const p of PATCHES){const g=new T.Group();g.position.set(p.x,p.y+.025,p.z);scene.add(g);const water=p.type==='water',mat=new T.MeshStandardMaterial({color:water?'#438eab':'#483733',roughness:water?.18:.32,metalness:.4,transparent:true,opacity:water?.62:.88,emissive:'#000000',side:T.DoubleSide});const mesh=new T.Mesh(new T.CircleGeometry(p.r,36),mat);mesh.rotation.x=-Math.PI/2;g.add(mesh);const ring=new T.Mesh(glowGeo,new T.MeshBasicMaterial({color:water?'#a6e5f4':'#c9975e',transparent:true,opacity:.6}));ring.scale.setScalar(p.r);ring.rotation.x=-Math.PI/2;ring.position.y=.03;g.add(ring);const flames=[];if(!water)for(let i=0;i<7;i++){const flame=new T.Mesh(new T.ConeGeometry(.28,1.6,6),new T.MeshBasicMaterial({color:i%2?'#ffb75e':'#ff7653',transparent:true,opacity:.7}));const a=i/7*Math.PI*2;flame.position.set(Math.cos(a)*p.r*.55,.8,Math.sin(a)*p.r*.55);g.add(flame);flames.push(flame);}patches.set(p.id,{g,mesh,ring,flames,p});}
 const core=new T.Mesh(new T.IcosahedronGeometry(.48,2),new T.MeshStandardMaterial({color:'#9bebdf',emissive:'#26796d',emissiveIntensity:.8,metalness:.4,roughness:.25}));core.position.set(RECOVERY.x,RECOVERY.y+1.85,RECOVERY.z);scene.add(core);
 const turret=new T.Group();turret.position.set(TURRET.x,TURRET.y,TURRET.z);scene.add(turret);movingPart('cylinder',steel,[0,-.65,0],[.35,1.3,.35],turret);movingPart('sphere',brass,[0,0,0],[.5,.4,.5],turret);const barrel=movingPart('cylinder',steel,[0,0,-.4],[.1,.9,.1],turret);barrel.rotation.x=Math.PI/2;const eye=movingPart('sphere',new T.MeshStandardMaterial({color:'#c88356',emissive:'#693420'}),[0,.1,-.55],[.12,.12,.12],turret);
 const bots=new Map();for(let i=0;i<6;i++){const g=new T.Group();g.visible=false;scene.add(g);const heavy=i===5;movingPart('sphere',steel,[0,0,0],[heavy?1.3:.85,heavy?.8:.55,heavy?.9:.65],g);for(const x of[-1,1]){movingPart('box',brass,[x*(heavy?1:.75),0,0],[.65,.12,.45],g);movingPart('torus',brass,[x*(heavy?1:.75),.06,0],[.37,.37,.37],g).rotation.x=Math.PI/2;}movingPart('sphere',new T.MeshStandardMaterial({color:'#ffc780',emissive:'#b2331f',emissiveIntensity:.6}),[0,.1,-.55],[.2,.2,.2],g);bots.set('trial-'+i,g);}
 const auras=new Map();for(const id of['range','g1','f1','s1',...bots.keys()]){const m=new T.Mesh(new T.TorusGeometry(1.3,.035,5,28),new T.MeshBasicMaterial({color:'#8fdbff',transparent:true,opacity:.8}));scene.add(m);m.visible=false;auras.set(id,m);}
 const boltGeo=new T.SphereGeometry(.095,6,4),boltMat=new T.MeshBasicMaterial({color:'#ff966d'}),bolts=Array.from({length:36},()=>{const m=new T.Mesh(boltGeo,boltMat);m.visible=false;scene.add(m);return m;});
 const gauntlet=new T.Group();camera.add(gauntlet);gauntlet.position.set(-.32,-.32,-.62);movingPart('box',steel,[0,0,0],[.19,.2,.31],gauntlet);movingPart('box',brass,[0,.08,-.12],[.24,.1,.24],gauntlet);for(let i=0;i<4;i++)movingPart('cylinder',brass,[-.08+i*.052,.03,-.24],[.022,.19,.022],gauntlet).rotation.x=Math.PI/2;const palm=movingPart('sphere',new T.MeshBasicMaterial({color:'#88dfff'}),[0,.15,-.16],[.065,.065,.065],gauntlet);
 for(let i=0;i<20;i++){const geometry=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),m=new T.Line(geometry,new T.LineBasicMaterial({color:'#88dfff',transparent:true,opacity:1}));m.visible=false;scene.add(m);fx.push({m,ttl:0});}let cursor=0;
 function effect(e){if(!['tactical-cast','tactical-turret'].includes(e.type)||!e.o||!e.end)return;if(e.type==='tactical-turret')turret.rotation.y=Math.atan2(TURRET.x-e.end.x,TURRET.z-e.end.z);const f=fx[cursor++%fx.length];f.ttl=.25;f.m.visible=true;f.m.material.color.set(e.power==='cinder'?'#ffc37c':e.type==='tactical-turret'?'#bff6a3':'#95e4ff');const attr=f.m.geometry.attributes.position;attr.setXYZ(0,e.o.x,e.o.y,e.o.z);attr.setXYZ(1,e.end.x,e.end.y,e.end.z);attr.needsUpdate=true;f.m.geometry.computeBoundingSphere();}
 function update(s,dt,menu,xr){const t=s.tactics;if(!t)return;for(const [id,v]of patches){const active=t.hazards[id]>0;v.mesh.material.emissive.set(active?(v.p.type==='water'?'#238ec3':'#943e19'):'#000000');v.ring.material.opacity=active?.75:.35;v.ring.rotation.z=s.time*.35;v.flames.forEach((m,i)=>{m.visible=active;m.scale.y=.8+Math.sin(s.time*5+i)*.2;});}core.rotation.y=s.time*.4;core.material.emissive.set(t.encounter.phase==='active'?'#528676':t.completed?'#0fc463':'#26796d');eye.material.emissive.set(t.hacked?'#43ca97':'#8c321b');
  for(const [id,g]of bots){const b=s.drones.find(d=>d.id===id);g.visible=!!b&&b.hp>0;if(g.visible){g.position.set(b.x,b.y,b.z);g.rotation.y=Math.atan2(b.x-RECOVERY.x,b.z-RECOVERY.z);}}
  for(const [id,m]of auras){const b=s.drones.find(b=>b.id===id);m.visible=!!b&&b.hp>0&&(b.shocked>0||b.burning>0);if(m.visible){m.position.set(b.x,b.y,b.z);m.rotation.y=s.time*2;m.material.color.set(b.shocked>0?'#8edbff':'#ffad75');}}
  for(let i=0;i<bolts.length;i++){const b=t.projectiles[i];bolts[i].visible=!!b;if(b)bolts[i].position.set(b.x,b.y,b.z);}
  gauntlet.visible=!menu&&!xr&&t.learned&&t.power!=='pulse'&&!s.p.rail&&!s.p.scoped;palm.material.color.set(POWERS[t.power].color);palm.scale.setScalar(.065*(t.flash>0?1.9:1));gauntlet.rotation.x=t.flash*.6;
  for(const f of fx){if(f.ttl<=0)continue;f.ttl=Math.max(0,f.ttl-dt);f.m.visible=f.ttl>0;f.m.material.opacity=f.ttl/.25;}
 }
 return {effect,update};
}
