'use strict';
// Egyptian Seed follow-up integration, 2026-09-18
require('./egypt-emanation/build.cjs');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,read=n=>JSON.parse(fs.readFileSync(path.join(root,n),'utf8')),manifest=read('manifest.json');
const sources=[...read('sources.json').sources,...read('sources-more.json').sources],bySource=new Map(sources.map(s=>[s.id,s]));
const studies=[...read('studies-core.json').studies,...read('studies-bridges.json').studies],byStudy=new Map(studies.map(s=>[s.slug,s]));
const directory=read('directory.json'),audit=read('claim-audit.json'),extras=read('sources-more.json').section_source_additions;
if(sources.length!==bySource.size||studies.length!==byStudy.size)throw Error('Duplicate source or study');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function link(text,url){const u=new URL(url,'https://v5ma.github.io/theology-wiki/comparative-religion/');if(u.protocol!=='https:')throw Error('Unsafe link');return '<a href="'+esc(url)+'">'+esc(text)+'</a>';}
const para=s=>'<p>'+esc(s)+'</p>';
function refs(ids){return ids.length?'<p class="references">Sources: '+[...new Set(ids)].map(id=>{if(!bySource.has(id))throw Error('Missing source '+id);return link(bySource.get(id).title,'sources.html#'+id);}).join(' / ')+'.</p>':'';}
const nav='<nav aria-label="Series navigation">'+link('Studies','index.html')+link('Tradition directory','directory.html')+link('Claim and quotation audit','claim-audit.html')+link('Source scopes','sources.html')+link('Egypt, emanation and genealogy','egypt-emanation/index.html')+link('Apocalyptic Repair Theology','../san-reader.html?page=apocalyptic-repair-theology')+'</nav>';
function shell(title,desc,content,script=false){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+esc(desc)+'"><title>'+esc(title)+' | Theology Wiki</title><link rel="stylesheet" href="series.css"></head><body><a class="skip" href="#main">Skip to content</a><header><p class="eyebrow">THEOLOGY WIKI / COMPARATIVE RELIGION / SEPTEMBER 18, 2026</p><h1>'+esc(title)+'</h1><p class="lede">'+esc(desc)+'</p>'+nav+'</header><main id="main">'+content+'</main><footer><p>This source-linked edition distinguishes textual evidence, community self-description, scholarly reconstruction and constructive theology. It does not claim that every living tradition shares one origin or creed.</p><p>'+link('Editorial and preservation notes','README.md')+' / '+link('Machine-readable local index','index.json')+' / '+link('Earlier religious-development studies','../religious-development/index.html')+'</p></footer>'+(script?'<script src="reader.js"></script>':'')+'</body></html>\n';}
const output=[];function write(name,text){fs.writeFileSync(path.join(root,name),text);output.push({path:name,sha256:crypto.createHash('sha256').update(text).digest('hex')});}
function filters(values,label){return '<div class="controls"><label>Search this page<input id="query" type="search"></label><label>'+esc(label)+'<select id="kind"><option value="">All</option>'+[...new Set(values)].sort().map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('')+'</select></label><button id="reset" type="button">Reset</button></div><p id="count" role="status" aria-live="polite"></p><p id="empty" hidden>No entries match these filters.</p>';}
for(const study of studies){const sections=study.sections.map((s,i)=>'<section id="section-'+(i+1)+'"><h2>'+esc(s.title)+'</h2>'+s.paragraphs.map(para).join('')+refs(s.source_ids)+'</section>').join('\n');const extra=extras[study.slug]||[];const related='<section><h2>Related studies</h2>'+study.related.map(slug=>{if(!byStudy.has(slug))throw Error('Missing related study '+slug);return '<p>'+link(byStudy.get(slug).title,slug+'.html')+'</p>';}).join('')+'</section>';write(study.slug+'.html',shell(study.title,study.summary,sections+(['shared-repertoire','iranian-and-greek-contact'].includes(study.slug)?'<section><h2>Develop the Egyptian Seed and transmission comparison</h2><p>The expanded study tests the method against named Egyptian, Greek and later witnesses rather than requiring every resemblance to be a proven lineage.</p><p>'+link('Read the larger Egypt-emanation series','egypt-emanation/index.html')+'</p></section>':'')+(extra.length?'<section><h2>Additional source witnesses</h2>'+refs(extra)+'</section>':'')+related));}
const nextSeries='<section><h2>Egypt, emanation and a larger genealogy</h2><p>The next research series develops the Egyptian Seed hypothesis, the abstraction method, Plotinus and Arabic transmission, 27 source-scoped comparisons, and a testable account of moral time horizons. It separates documented reception from possible lost connections.</p><p>'+link('Open the eight new studies and relationship register','egypt-emanation/index.html')+'</p></section>';
const cards=studies.map(s=>'<article class="filter-record" data-kind="Study" id="study-'+s.slug+'"><h2>'+link(s.title,s.slug+'.html')+'</h2>'+para(s.summary)+'</article>').join('\n');
write('index.html',shell('Evil, revelation and the work of transformation','A comparative foundation across Jewish apocalyptic texts, Mandaeans, Nag Hammadi writings, later mystical traditions and living religious communities.','<p class="notice">Nine developed studies are accompanied by 36 introductory or prospect entries. The directory does not imply 36 complete monographs. Six supplied scholarly quotations remain explicitly unverified.</p>'+nextSeries+filters(['Study'],'Entry type')+cards+'<section><h2>Read the comparison without flattening it</h2><p>The proposed shared repertoire is an interpretive model. Source dates, distinct creators, community rules, ritual practices and different understandings of salvation remain part of the evidence rather than being subtracted to force a single lineage.</p><p>'+link('Open the complete directory','directory.html')+' / '+link('Review corrected claims and unauthenticated attributions','claim-audit.html')+'</p></section>',true));
const entries=directory.entries.map(e=>{for(const id of e.source_ids)if(!bySource.has(id))throw Error('Missing directory source');if(!byStudy.has(e.study))throw Error('Missing directory study');return '<article class="filter-record" data-kind="'+esc(e.family)+'" id="'+e.id+'"><p class="meta">'+esc(e.family)+' / '+esc(e.coverage)+'</p><h2>'+esc(e.name)+'</h2>'+para(e.description)+para('Next research task: '+e.next)+refs(e.source_ids)+'<p>'+link('Related developed study',e.study+'.html')+'</p></article>';}).join('\n');
write('directory.html',shell('Traditions and textual communities','An orientation directory with visible limits and specific next research tasks.','<p class="notice">'+esc(directory.scope)+'</p>'+filters(directory.entries.map(e=>e.family),'Family or research setting')+entries,true));
const claims=audit.claims.map(c=>'<article class="filter-record" data-kind="Claim review" id="'+c.id+'"><p class="meta">'+esc(c.assessment)+'</p><h2>Supplied claim: '+esc(c.supplied_claim)+'</h2>'+para(c.correction)+refs(c.source_ids)+'</article>').join('\n');
const quotes=audit.unverified_quotations.map(q=>'<article class="filter-record unverified" data-kind="Unverified attribution" id="'+q.id+'"><p class="meta">Unverified supplied attribution; not authenticated quotation</p><h2>'+esc(q.attributed_author)+'</h2>'+para('Work named in the supplied discussion: '+q.attributed_work)+para('Opening words supplied by the user: '+q.opening_supplied)+para(q.finding)+'</article>').join('\n');
write('claim-audit.html',shell('Claim audit and unverified quotations','Correcting consequential conflations without rewriting the original conversation.','<p class="notice">'+esc(audit.policy)+'</p>'+filters(['Claim review','Unverified attribution'],'Record type')+claims+'<h2 id="unverified">Six supplied quotations requiring authentication</h2>'+quotes,true));
write('sources.html',shell('Sources and reading scope','Primary witnesses, scholarly interpretations, community accounts and bibliographic leads are not interchangeable.','<p>Each link below identifies the actual scope of access. A cited abstract is not a claimed reading of a complete book. No fresh manuscript collation or whole-community survey is represented.</p>'+sources.map(s=>'<article id="'+s.id+'"><p class="meta">'+esc(s.kind)+'</p><h2>'+esc(s.title)+'</h2>'+para(s.scope)+'<p>'+link('Open source',s.url)+'</p></article>').join('\n')));
write('index.json',JSON.stringify({schema_version:1,edition_date:manifest.edition_date,scope:manifest.scope,studies:studies.map(s=>({slug:s.slug,title:s.title,summary:s.summary,url:s.slug+'.html',text:s.sections.flatMap(x=>[x.title,...x.paragraphs]).join('\n')})),directory:directory.entries.map(e=>({id:e.id,name:e.name,coverage:e.coverage,url:'directory.html#'+e.id})),counts:{studies:studies.length,directory:directory.entries.length,claim_reviews:audit.claims.length,unverified_quotations:audit.unverified_quotations.length,sources:sources.length}},null,2)+'\n');
write('READING.md','This is the plain-text counterpart of the nine developed comparative studies. Source IDs resolve through sources.json and sources-more.json. The claims retain their stated source scope.\n\n'+studies.map(s=>s.title+'\n\n'+s.summary+'\n\n'+s.sections.map(p=>p.title+'\n\n'+p.paragraphs.join('\n\n')+'\n\nSources: '+p.source_ids.map(id=>bySource.get(id).url).join(' ; ')).join('\n\n')).join('\n\n'));
const wordCount=studies.reduce((n,s)=>n+s.sections.flatMap(x=>x.paragraphs).join(' ').split(/\s+/).length,0);
fs.writeFileSync(path.join(root,'build-report.json'),JSON.stringify({schema_version:1,edition_date:manifest.edition_date,counts:{studies:studies.length,directory:directory.entries.length,claims:audit.claims.length,unverified_quotations:audit.unverified_quotations.length,sources:sources.length,study_words:wordCount},files:output},null,2)+'\n');
console.log(JSON.stringify({studies:studies.length,directory:directory.entries.length,claims:audit.claims.length,sources:sources.length,study_words:wordCount,generated_html:output.filter(x=>x.path.endsWith('.html')).length}));
