'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),m=require('./manifest.json'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),blob=b=>crypto.createHash('sha1').update('blob '+b.length+'\0').update(b).digest('hex');
const file=path.join(root,'editorial/authorial-articles',m.main_article+'.md'),current=fs.readFileSync(file),extra=fs.readFileSync(path.join(__dirname,m.supplement));let original=current;if(current.length>=extra.length&&current.subarray(current.length-extra.length).equals(extra))original=current.subarray(0,current.length-extra.length);assert.equal(blob(original),m.original_git_blob,'Original repair article changed');const combined=Buffer.concat([original,extra]);if(!combined.equals(current))fs.writeFileSync(file,combined);
const repairs=[];
function patch(name,expected,marker,changes){const p=path.join(root,'research-expansion-20260918',name);let t=fs.readFileSync(p,'utf8');if(!t.includes(marker)){assert.equal(sha(Buffer.from(t)),expected,name+' unexpected version');for(const [from,to]of changes){assert.equal(t.split(from).length-1,1,'Non-unique patch '+name);t=t.replace(from,to);}fs.writeFileSync(p,t);}assert.ok(t.includes(marker));repairs.push({path:'research-expansion-20260918/'+name,before_sha256:expected,after_sha256:sha(Buffer.from(t))});}
const active="const activeVersion=fs.existsSync(path.join(root,'comparative-religion/manifest.json'))?require('../comparative-religion/manifest.json').version:manifest.version;";
patch('integrate.cjs','641f9171f09fb4a650338af9847ba4d466872787fe6b19b6978fd0c3b6edc389',active,[['meta.version=manifest.version;meta.updated=manifest.edition_date;',active+'\nmeta.version=activeVersion;meta.updated=manifest.edition_date;'],['products.version=manifest.version;','products.version=activeVersion;']]);
const verify=" if(fs.existsSync(path.join(root,'comparative-religion/revision-receipt.json')))return require('../comparative-religion/verify-preservation.cjs').verify().legacy;";
patch('verify-preservation.cjs','6f9ed50283aa11303bbfb05720c23419fe38970e09ca9fad8b7b7e7ac07c7006',verify,[['function verify(){','function verify(){\n'+verify]]);
const redirect="if(require('node:fs').existsSync(require('node:path').join(__dirname,'../comparative-religion/revision-receipt.json'))){require('../comparative-religion/verify-preservation.cjs').verify();return;}";
patch('reconcile.cjs','ee14ee34cd550088274c182d54445a6229c8f8346dcaeb674780a62d95482a44',redirect,[["'use strict';","'use strict';\n"+redirect]]);
const expect="assert.equal(JSON.parse(read('../editorial/authorial.json')).version,fs.existsSync(path.join(root,'comparative-religion/manifest.json'))?require('../comparative-religion/manifest.json').version:manifest.version);";
patch('expansion.test.cjs','b721afb2b3ec0403558926667afcbff35d28a45c0ac2c6aa98fd91fe5bd5b8e1',expect,[["assert.equal(JSON.parse(read('../editorial/authorial.json')).version,manifest.version);",expect]]);
const metadata=path.join(root,'editorial/authorial.json'),meta=JSON.parse(fs.readFileSync(metadata));assert.ok(meta.updated<=m.edition_date);meta.version=m.version;meta.updated=m.edition_date;const page=meta.articles.find(a=>a.slug===m.main_article);assert.ok(page);page.updated=m.edition_date;page.summary='Repair as ethical action, with Jewish adversarial traditions, Maimonides, a shared revelatory-transformative repertoire and a source-critical comparative religion series.';fs.writeFileSync(metadata,JSON.stringify(meta,null,2)+'\n');const pp=path.join(root,'editorial/products.json'),products=JSON.parse(fs.readFileSync(pp));products.version=m.version;fs.writeFileSync(pp,JSON.stringify(products,null,2)+'\n');
const r=path.join(root,'README.md'),text=fs.readFileSync(r,'utf8'),addition='\nThe September 18 comparative-religion edition adds nine developed source-linked studies, a 36-entry scoped tradition directory, twenty claim reviews and six explicitly unverified quotation attributions. [The comparative series](comparative-religion/index.html) is linked from a substantive addition to Apocalyptic Repair Theology. Its new main-article text is indexed and narrated; standalone series pages have their own local index, not new principal-reader routes. Original article bytes and all earlier source and forecast records remain preserved. Canonical JSON, deterministic HTML generation and exact three-derivative preservation receipts are in comparative-religion/.\n';if(!text.includes('The September 18 comparative-religion edition'))fs.writeFileSync(r,text+addition);
fs.writeFileSync(path.join(__dirname,'integration-receipt.json'),JSON.stringify({schema_version:1,edition_date:m.edition_date,base_commit:m.base_commit,article:{slug:m.main_article,original_git_blob:m.original_git_blob,original_bytes:original.length,supplement:m.supplement,integrated_git_blob:blob(combined)},compatibility_patches:repairs,scope:'Original main article preserved as exact prefix. Earlier three-article tooling checks the new bounded receipt rather than downgrading metadata; previous receipt bytes remain unchanged.'},null,2)+'\n');console.log(JSON.stringify({integrated:m.main_article,version:m.version,compatibility_patches:repairs.length}));
