'use strict';
// Moses-Jesus-Mammon follow-up integration
require('./moses-jesus-mammon/build.cjs');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{load}=require('./data.cjs');
const d=load(),root=__dirname,esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const anchor=id=>id.replaceAll(':','-');
function link(t,u){if(new URL(u,'https://v5ma.github.io/theology-wiki/comparative-religion/egypt-emanation/').protocol!=='https:')throw Error('Unsafe URL');return '<a href="'+esc(u)+'">'+esc(t)+'</a>';}
const nav='<nav aria-label="Research navigation">'+link('Eight studies','index.html')+link('Tradition comparisons','profiles.html')+link('Genealogy register','relationships.html')+link('Sources and access','sources.html')+link('Moses, Jesus and Mammon','moses-jesus-mammon/index.html')+link('Earlier comparative series','../index.html')+link('Apocalyptic Repair Theology','../../san-reader.html?page=apocalyptic-repair-theology')+'</nav>';
function shell(title,summary,body,script=false){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="'+esc(summary)+'"><title>'+esc(title)+' | Theology Wiki</title><link rel="stylesheet" href="../series.css"><link rel="stylesheet" href="research.css"></head><body><a class="skip" href="#main">Skip to content</a><header><p class="eyebrow">THEOLOGY WIKI / EGYPT, EMANATION AND GENEALOGY / SEPTEMBER 18, 2026</p><h1>'+esc(title)+'</h1><p class="lede">'+esc(summary)+'</p>'+nav+'</header><main id="main">'+body+'</main><footer><p>The Egyptian Seed and Emanationist Esotericism proposals are developed as research hypotheses. A structural resemblance, explicit appeal, material contact and identified textual transmission are different relationships.</p><p>'+link('Scope and preservation','README.md')+' / '+link('Plain-text studies','READING.md')+' / '+link('Searchable source data','index.json')+'</p></footer>'+(script?'<script src="reader.js"></script>':'')+'</body></html>\n';}
const p=t=>'<p>'+esc(t)+'</p>';
function refs(ids){return [...new Set(ids)].map(id=>{const s=d.sourceMap.get(id);if(!s)throw Error('Unresolved source');return '<p>'+link(s.title,'sources.html#'+anchor(id))+'</p>';}).join('');}
const outputs=[];function write(n,t){fs.writeFileSync(path.join(root,n),t);outputs.push({path:n,sha256:crypto.createHash('sha256').update(t).digest('hex')});}
function controls(values,label){return '<div class="controls"><label>Search '+esc(label)+'<input id="query" type="search"></label><label>Record type<select id="kind"><option value="">All</option>'+[...new Set(values)].sort().map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('')+'</select></label><button id="reset" type="button">Reset</button></div><p id="count" role="status" aria-live="polite"></p><p id="empty" hidden>No records match these filters.</p>';}
const byStudy=new Map(d.studies.map(s=>[s.slug,s]));
for(const s of d.studies){const related=d.relations.relationships.filter(r=>r.study===s.slug);const body=s.sections.map((section,i)=>'<section id="section-'+(i+1)+'"><h2>'+esc(section.title)+'</h2>'+section.paragraphs.map(p).join('')+'</section>').join('\n');
 const sourceSection='<section id="sources"><h2>Sources for this study</h2><p>Source records retain the consulted passage and access limitation; hypotheses and proposed tests are identified in the study.</p>'+refs(s.sections.flatMap(x=>x.sources))+'</section>';
 const relationships=related.length?'<section><h2>Inspect the proposed connections</h2>'+related.map(r=>'<p>'+link(r.from+' / '+r.to,'relationships.html#'+r.id)+'. '+esc(r.type)+'.</p>').join('')+'</section>':'';
 write(s.slug+'.html',shell(s.title,s.summary,body+(['egyptian-seed','moral-horizons-beyond-life','egypt-iran-contact'].includes(s.slug)?'<section><h2>Egyptian care, Mosaic obligation and Jesus on wealth</h2><p>The next study uses Egyptian inscriptions, Torah rules and explicit Gospel references to Moses to distinguish shared ethical structures from an assumed complete genealogy.</p><p>'+link('Read Moses, Jesus and Mammon','moses-jesus-mammon/index.html')+'</p></section>':'')+sourceSection+relationships));}
const cards=d.studies.map(s=>{const text=s.sections.flatMap(x=>[x.title,...x.paragraphs]).join(' ');return '<article class="filter-record" id="study-'+s.slug+'" data-kind="Developed study" data-search="'+esc(s.title+' '+s.summary+' '+text)+'"><h2>'+link(s.title,s.slug+'.html')+'</h2>'+p(s.summary)+'</article>';}).join('\n');
write('index.html',shell('Egypt, emanation and the ancestry of spiritual ideas','Eight new studies develop the Egyptian Seed hypothesis, the abstraction method and a wider family of traditions without treating resemblance as a completed genealogy.','<p class="notice">This expansion adds '+d.studies.length+' developed studies, '+d.profiles.profiles.length+' source-scoped comparisons and '+d.relations.relationships.length+' typed relationships. The local search below searches the complete text of the eight new studies, not only their titles. Original main-reader articles and earlier forecast records remain unchanged.</p>'+controls(['Developed study'],'eight full studies')+cards+'<section><h2>Move from the pattern to the evidence</h2><p>'+link('Compare the five dimensions across traditions','profiles.html')+' or '+link('inspect each proposed transmission or resemblance','relationships.html')+'. An unverified connection remains a research question, not a missing fact silently supplied by the reader.</p></section>',true));
const labels={knowledge:'Knowledge',cosmology:'Cosmology',person:'Person and source',transmission:'Guidance and transmission',goal:'Transformation and goal'};
const profiles=d.profiles.profiles.map(r=>'<article class="filter-record" id="'+r.id+'" data-kind="'+esc(r.status)+'"><p class="meta">'+esc(r.status)+'</p><h2>'+esc(r.name)+'</h2>'+p('Witness scope: '+r.scope)+Object.entries(labels).map(([key,label])=>p(label+': '+r[key])).join('')+'<details><summary>Source witnesses</summary>'+refs(r.sources)+(r.sources.length?'':'<p>No primary witness has been recovered for this proposed profile in this edition.</p>')+'</details></article>').join('\n');
write('profiles.html',shell('Twenty-seven qualitative comparisons','The five proposed pillars are questions applied to specified witnesses, not a ranking of religions or a claim that every tradition has every feature.','<p class="notice">'+esc(d.profiles.policy)+'</p>'+controls(d.profiles.profiles.map(r=>r.status),'profiles')+profiles,true));
const relations=d.relations.relationships.map(r=>{if(!byStudy.has(r.study))throw Error('Unknown related study');return '<article class="filter-record" id="'+r.id+'" data-kind="'+esc(r.type)+'"><p class="meta">'+esc(r.type)+'</p><h2>'+esc(r.from)+' / '+esc(r.to)+'</h2>'+p('Historical scope: '+r.period)+p('Available evidence: '+r.evidence)+p('What remains missing: '+r.missing)+p('Alternative account: '+r.alternative)+'<p>'+link('Read the developed argument',r.study+'.html')+'</p><details><summary>Source witnesses</summary>'+refs(r.sources)+'</details></article>';}).join('\n');
write('relationships.html',shell('A register of twenty proposed connections','Inspect textual dependence, explicit appeals, material contact and unresolved genealogies separately.','<p class="notice">'+esc(d.relations.policy)+'</p>'+controls(d.relations.relationships.map(r=>r.type),'connections')+relations,true));
write('sources.html',shell('Sources, passages and retrieval limits','New witnesses and inherited source records are identified separately. A publisher description is not a full-book reading.','<p>Source amendments preserve the difference between a broad page title and the passages actually retrieved. In particular, the missing later Plotinus tractates were recovered through separate witnesses rather than assumed present in a truncated page.</p>'+d.sources.map(s=>'<article id="'+anchor(s.id)+'"><p class="meta">'+esc(s.kind)+'</p><h2>'+esc(s.title)+'</h2>'+p('Locator: '+(s.locator||s.scope))+p(s.scope)+p(s.edition_scope)+'<p>'+link('Open source',s.url)+'</p></article>').join('\n')));
const search=d.studies.map(s=>({slug:s.slug,title:s.title,summary:s.summary,url:s.slug+'.html',text:s.sections.flatMap(x=>[x.title,...x.paragraphs]).join('\n')}));
write('index.json',JSON.stringify({schema_version:1,edition_date:d.manifest.edition_date,scope:d.manifest.scope,studies:search,profiles:d.profiles.profiles,relationships:d.relations.relationships},null,2)+'\n');
write('READING.md','This is the complete plain-text counterpart of the eight new studies. Hypotheses, source testimony and proposed experiments remain distinct. Source IDs resolve through the local source files and, where prefixed legacy:, the previous comparative-religion source register.\n\n'+d.studies.map(s=>s.title+'\n\n'+s.summary+'\n\n'+s.sections.map(x=>x.title+'\n\n'+x.paragraphs.join('\n\n')).join('\n\n')+'\n\nSources for this study: '+[...new Set(s.sections.flatMap(x=>x.sources))].map(id=>d.sourceMap.get(id).url).join(' ; ')).join('\n\n')+'\n');
const count=xs=>xs.join(' ').trim().split(/\s+/).length;const report={schema_version:1,edition_date:d.manifest.edition_date,counts:{studies:d.studies.length,profiles:d.profiles.profiles.length,relationships:d.relations.relationships.length,sources:d.sources.length,new_source_records:d.sources.filter(s=>!s.id.startsWith('legacy:')).length,study_words:count(d.studies.flatMap(s=>s.sections.flatMap(x=>x.paragraphs))),profile_words:count(d.profiles.profiles.flatMap(r=>[r.scope,r.knowledge,r.cosmology,r.person,r.transmission,r.goal])),relationship_words:count(d.relations.relationships.flatMap(r=>[r.evidence,r.missing,r.alternative]))},files:outputs};
fs.writeFileSync(path.join(root,'build-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.counts));
