'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=__dirname,read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const data=JSON.parse(read('passages.json')),docs=JSON.parse(read('dossiers.json'));
const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function anchor(title,url){const u=new URL(url,'https://v5ma.github.io/theology-wiki/scripture-concordance/');if(u.protocol!=='https:')throw Error('Unsafe URL');return '<a href="'+escape(url)+'">'+escape(title)+'</a>';}
const byD=new Map(docs.dossiers.map(d=>[d.id,d])),byS=new Map(docs.sources.map(s=>[s.id,s]));
if(data.passages.length!==148||new Set(data.passages.map(p=>p.id)).size!==148)throw Error('Invalid selection');
const options=(field,caption)=>`<label>${caption}<select id="${field}"><option value="">All</option>${[...new Set(data.passages.map(p=>p[field]))].map(x=>`<option value="${escape(x)}">${escape(x)}</option>`).join('')}</select></label>`;
const cards=data.passages.map(p=>`<article class="passage" id="${p.id}" data-book="${escape(p.book)}" data-corpus="${escape(p.corpus)}" data-theme="${escape(p.theme)}"><p class="meta">${escape(p.corpus)} / ${escape(p.theme)}</p><h3>${escape(p.reference)}</h3><p>${escape(p.textual_summary)}</p><p>Textual actor: ${escape(p.textual_subject)}.</p><p>${anchor('Read the translated passage',p.source_url)}. ${escape(p.edition)}.</p><p>${escape(p.canon_note)}</p><p>${escape(p.assignment_status)}.</p>${p.comparison_links.length?'<p>Documentary comparisons: '+p.comparison_links.map(id=>{if(!byD.has(id))throw Error('Missing dossier');return anchor(byD.get(id).title,'#d-'+id);}).join(' / ')+'</p>':''}<details><summary>Comparison and source limits</summary><p>${escape(p.relation_note)}</p><p>${escape(p.source_access)}</p></details></article>`).join('\n');
const dossiers=docs.dossiers.map(d=>`<article class="dossier" id="d-${d.id}"><p class="meta">${escape(d.record_type)}</p><h3>${escape(d.title)}</h3><p>${escape(d.documented_record)}</p><p>Comparison question: ${escape(d.comparison_question)}</p><p>${escape(d.scope_limit)}</p>${d.source_ids.map(id=>{const s=byS.get(id);if(!s)throw Error('Missing source');return '<p>'+anchor(s.title,s.url)+'. '+escape(s.access_scope)+'</p>';}).join('')}${d.wiki_paths.map((p,i)=>'<p>'+anchor('Related wiki record '+(i+1),p)+'</p>').join('')}</article>`).join('\n');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Theology Wiki | 148-passage concordance</title><meta name="description" content="A source-linked concordance of end-times, authority and discernment passages with distinct historical and contemporary documentary comparisons."><style>
:root{color-scheme:dark;font:17px/1.65 system-ui,sans-serif;background:#101923;color:#eef2f5}*{box-sizing:border-box}body{max-width:1050px;margin:auto;padding:26px}a{color:#a3d2f0;text-underline-offset:3px}h1,h2,h3{line-height:1.25}h1{font-size:clamp(2rem,4vw,3.1rem)}header,footer{padding:18px 0;border-bottom:1px solid #697a8b}nav,.filters{display:flex;gap:16px;flex-wrap:wrap}.filters{margin:24px 0}label{display:flex;flex-direction:column;gap:5px}select,input,button{font:inherit;color:inherit;background:#213142;border:1px solid #879aac;padding:8px 10px;border-radius:4px}input{max-width:100%;width:280px}article{margin:18px 0;padding:20px;border:1px solid #697a8b;border-left:4px solid #91b6d0;border-radius:4px;overflow-wrap:anywhere}.meta{color:#bfd0df}summary{cursor:pointer}details{margin-top:14px}.notice{padding:16px;border:1px solid #697a8b}[hidden]{display:none!important}:focus-visible{outline:3px solid #ffd788;outline-offset:3px}@media(max-width:520px){body{padding:14px}.filters{display:block}label{margin:12px 0}input{width:100%}article{padding:15px}}@media print{:root{color:black;background:white}a,.meta{color:black}.filters{display:none}article{break-inside:avoid}}
</style></head><body><header><p class="meta">THEOLOGY WIKI / SCRIPTURE CONCORDANCE / SEPTEMBER 17, 2026</p><h1>End times, authority and recurring forms</h1><p>148 selected passages: 128 biblical verses and 20 numbered sections from a wider corpus. Textual actors, historical documents and the author's contemporary interpretation remain separate.</p><nav><a href="../san-reader.html?page=trump-first-beast-of-revelation">First Beast article</a><a href="../san-reader.html?page=antichrist-as-a-pattern-of-conduct">Conduct and typology</a><a href="#dossiers">Documentary dossiers</a><a href="README.md">Editorial scope</a><a href="passages.json">Passage data</a><a href="dossiers.json">Dossier data</a></nav></header><main><p class="notice">This is a concordance, not a completed fulfillment chart. A linked document supplies a comparison question, not a score for a leader. Unassigned passages remain visible, including passages about other agents, ethical contrasts and unresolved events.</p><section><h2>Passages in textual order</h2><div class="filters"><label>Search passage text<input id="query" type="search" placeholder="Reference, theme or textual subject"></label>${options('book','Work')}${options('corpus','Corpus')}${options('theme','Theme')}<button id="reset" type="button">Reset</button></div><p id="count" role="status" aria-live="polite">148 passage rows are visible.</p><p id="empty" hidden>No passage rows match these filters.</p><div id="passages">${cards}</div></section><section id="dossiers"><h2>Documentary comparisons and reception history</h2><p>These dossiers distinguish account publications, public reactions, official instruments, material culture and recorded accusations. They are not interchangeable kinds of evidence and are not ranked.</p>${dossiers}</section><noscript><p>All passages, documentary comparisons and source links remain readable without JavaScript.</p></noscript></main><footer><p>Edited on September 17, 2026. Earlier forecast dates and original source files remain unchanged. Canonical placement is tradition-dependent; “wider corpus” means outside this edition's 66-book baseline, not universal exclusion.</p></footer><script src="reader.js"></script></body></html>\n`;
fs.writeFileSync(path.join(ROOT,'index.html'),html);
const list=data.passages.map(p=>`${p.reference}. ${p.textual_summary} Textual actor: ${p.textual_subject}. ${p.edition}.\n\nSource: ${p.source_url}\n\n${p.assignment_status}. ${p.comparison_links.length?'See dossier IDs: '+p.comparison_links.join(', ')+'. ':''}${p.relation_note}\n`).join('\n');
fs.writeFileSync(path.join(ROOT,'PASSAGES.md'),'This is the complete plain-text counterpart of the 148-passage concordance. It is a source-linked selection, not a score or fulfillment count. Full context and canon notes are in passages.json.\n\n'+list);
console.log(JSON.stringify({passages:data.passages.length,biblical:data.passages.filter(p=>p.corpus==='Biblical base').length,wider:data.passages.filter(p=>p.corpus==='Wider corpus').length,dossiers:docs.dossiers.length,htmlSha256:crypto.createHash('sha256').update(html).digest('hex')}));
