import {createMenuNavigation} from './controller-ui.mjs';
import {createControllerFeedback} from './controller-feedback.mjs';
import {createFrameClock} from './frame-clock.mjs';
import {CURRENT,LEVELS,VERSION,OBSTACLES,GRASS,ITEMS,SHELTERS,EXIT,BOUNDS,HEIGHT,dist,coverAt} from './world.mjs';
import {createGame,update,stance,interactable,interact,craft,heal,smoke,reload,bottle,fire,dodgeOrVault,checkpoint,restore,forward,RECIPES} from './model.mjs';
import {createScene} from './scene.mjs';
import {GamepadInput} from './input.mjs';
import {createHUD} from './hud.mjs';
import {bindControls} from './controls.mjs';
import {createStealthUI} from './stealth-ui.mjs';
import {createAudio} from './audio.mjs';
const $=id=>document.getElementById(id),canvas=$('world'),SAVE='svgn.rainward.v1.checkpoint',SETTINGS='svgn.rainward.v1.settings';
const frameClock=createFrameClock();
const requestedChapter=new URLSearchParams(location.search).get('chapter'),initialChapter=Object.hasOwn(LEVELS,requestedChapter)?requestedChapter:'district';
$('chapter-select').value=initialChapter;
let state=createGame(initialChapter),scene=null,mode='title',keys=new Set(),controls=null,last=0,eventSeq=0,frame=0,gamepad=new GamepadInput(),pad={},menu=null,started=false,pauseOrigin='title',confirmation=null,confirmationOrigin='title',sprintLatched=false;
const view={yaw:0,pitch:-.09,aim:false,snap:true,shoulder:1},touch={x:0,z:0,aim:false,fire:false,listen:false};let settings={vibration:true,invertY:false,toggleSprint:true,deadzone:18,mute:false,low:false,sensitivity:85,scanned:true,cinematic:true,motion:!matchMedia('(prefers-reduced-motion: reduce)').matches};
const read=key=>{try{return localStorage.getItem(key);}catch{return null;}};const write=(key,value)=>{try{localStorage.setItem(key,value);return true;}catch{return false;}};
try{const d=JSON.parse(read(SETTINGS)||'null');if(d){settings.vibration=d.vibration!==false;settings.invertY=!!d.invertY;settings.toggleSprint=d.toggleSprint!==false;settings.deadzone=Math.max(10,Math.min(35,Number(d.deadzone)||18));settings.mute=!!d.mute;settings.low=!!d.low;settings.scanned=d.scanned!==false;settings.cinematic=d.cinematic!==false;settings.motion=d.motion!==false&&!matchMedia('(prefers-reduced-motion: reduce)').matches;settings.sensitivity=Math.max(30,Math.min(170,Number(d.sensitivity)||85));}}catch{}
const feedback=createControllerFeedback(()=>gamepad.raw,()=>settings.vibration&&['play','pack'].includes(mode));
const audio=createAudio(settings,()=>mode),audioStart=()=>audio.start(),sound=e=>audio.event(e);
function clearInput(){sprintLatched=false;pad={connected:gamepad.id!==null,actions:[],move:[0,0],look:[0,0]};keys.clear();Object.assign(touch,{x:0,z:0,aim:false,fire:false,listen:false});controls?.clear();gamepad.reset();}
function setMode(next){if(next==='pause'&&mode!=='confirm')pauseOrigin=mode==='title'?'title':started?'play':'title';frameClock.reset();mode=next;feedback.stop();clearInput();for(const id of['title','pause','map-panel','pack','result','fatal','confirm-panel'])$(id).hidden=true;
 const panel=next==='confirm'?'confirm-panel':next==='map'?'map-panel':next==='dead'||next==='won'?'result':next; if($(panel))$(panel).hidden=false;
 $('hud').hidden=!['play','pack'].includes(next);$('touch').hidden=next!=='play'||!(matchMedia('(pointer:coarse)').matches||innerWidth<760);
 if(next!=='play'&&document.pointerLockElement)document.exitPointerLock();if(next==='map'){ui.drawMap();ui.hud();}if(next==='pause'){$('resume').textContent=started?'RESUME':'BACK TO TITLE';$('retry').disabled=!started;}if(next==='play')canvas.focus({preventScroll:true});menu?.enter();audioStart();
}
function makeScene(){return createScene(canvas,{onXRStart:()=>setMode('xr'),onXREnd:error=>{setMode('pause');if(error)$('xr-status').textContent='VR could not start: '+error.message;}});}
function configureScene(){scene.setQuality(settings.low);scene.setScanned(settings.scanned);scene.setCinematic(settings.cinematic);scene.setMotion(settings.motion);scene.renderer.setAnimationLoop(tick);last=0;frameClock.reset();}
function ask(message,operation){if(confirmation)return;confirmationOrigin=mode;confirmation=operation;$('confirm-message').textContent=message;setMode('confirm');}
function answerConfirmation(yes){if(!confirmation)return;const operation=confirmation,origin=confirmationOrigin;confirmation=null;setMode(origin);if(yes)operation();}
function start(fresh=false,confirmed=false){const old=restore(read(SAVE),false);const chapter=$('chapter-select').value;if(fresh&&old&&!confirmed&&state.status!=='won'){ask('Start a new expedition? Your current shelter checkpoint will be replaced.',()=>start(true,true));return;}state=!fresh&&old?restore(read(SAVE)):createGame(chapter);scene?.dispose();scene=makeScene();configureScene();resize();eventSeq=0;view.yaw=0;view.pitch=-.09;view.snap=true;view.shoulder=1;started=true;if(fresh)write(SAVE,checkpoint(state));setMode('play');}
function save(){if(!write(SAVE,checkpoint(state))){state.hint='Storage is unavailable. Keep this tab open to retain progress.';state.hintTime=5;}syncTitle();}
function syncTitle(){$('continue').hidden=!restore(read(SAVE),false);}
function closePanel(){if(mode==='confirm'){answerConfirmation(false);return;}if(mode==='pause'){setMode(pauseOrigin);return;}if(['map','pack'].includes(mode)){setMode('play');return;}if(mode==='won'||mode==='dead'){setMode('title');syncTitle();}}
function cycleChapter(direction){const select=$('chapter-select');select.selectedIndex=(select.selectedIndex+direction+select.options.length)%select.options.length;select.dispatchEvent(new Event('change',{bubbles:true}));}
function menuTab(direction){if(mode==='title'){cycleChapter(direction);return;}if(!started||!['pause','map','pack'].includes(mode))return;const tabs=['map','pack','pause'];setMode(tabs[(tabs.indexOf(mode)+direction+3)%3]);}

function act(action){if(action==='pause'){if(mode==='play'||mode==='pack')setMode('pause');else closePanel();return;}if(action==='map'||action==='pack'){if(mode==='play')setMode(action);else if(mode===action)setMode('play');return;}
 if(mode!=='play')return;const p=state.player;
 if(action==='crouch'||action==='prone')sprintLatched=false;
 if(action==='crouch')stance(state,p.stance==='crouch'?'stand':'crouch');if(action==='prone')stance(state,p.stance==='prone'?'stand':'prone');
 if(action==='interact'){const target=interactable(state);if(interact(state)&&target?.kind==='shelter')save();}
 if(action==='shoulder'){view.shoulder*=-1;state.hint='Camera: '+(view.shoulder<0?'left':'right')+' shoulder';state.hintTime=2;}
 if(action==='reload')reload(state);if(action==='bottle')bottle(state,view.yaw);if(action==='heal')heal(state);if(action==='smoke')smoke(state);
 if(action==='dodge'){const v=motion();dodgeOrVault(state,v.x,v.z);}
}
function motion(){let x=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touch.x+(pad.move?.[0]||0),y=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-touch.z-(pad.move?.[1]||0),l=Math.max(1,Math.hypot(x,y));x/=l;y/=l;const f=forward(view.yaw);return {x:Math.cos(view.yaw)*x+f.x*y,z:-Math.sin(view.yaw)*x+f.z*y};}
const stealth=createStealthUI($('hud'));
const ui=createHUD({get state(){return state},get mode(){return mode},get pad(){return pad},get scene(){return scene},view,setMode,closePanel});
menu=createMenuNavigation({get mode(){return mode},closePanel,menuButton:()=>{if(mode==='title')setMode('pause');else if(mode==='pause')closePanel();else if(['map','pack'].includes(mode))setMode('pause');},viewButton:()=>{if(mode==='map')closePanel();else if(started&&['pack','pause'].includes(mode))setMode('map');},tab:menuTab});
controls=bindControls({get mode(){return mode},keys,view,touch,canvas,act,setMode,settings,clearInput});
$('chapter-cycle').onclick=()=>cycleChapter(1);$('chapter-select').onchange=()=>{$('chapter-cycle').textContent='CHAPTER '+($('chapter-select').selectedIndex+1)+' SELECTED / NEXT';};
$('start').onclick=()=>start(true);$('continue').onclick=()=>start(false);$('resume').onclick=closePanel;$('retry').onclick=()=>ask('Return to your last shelter? Progress since that checkpoint will be lost.',()=>start(false,true));$('to-title').onclick=()=>{const leave=()=>{setMode('title');syncTitle();};if(started&&state.status==='playing')ask('Return to the title? Your last shelter checkpoint remains available. Unsaved progress will not be resumed.',leave);else leave();};$('result-retry').onclick=()=>start(false);$('result-new').onclick=()=>{setMode('title');syncTitle();};$('result-next').onclick=()=>{const names=Object.keys(LEVELS),i=names.indexOf(state.level);if(i>=0&&i+1<names.length){$('chapter-select').value=names[i+1];start(true);}};$('map-button').onclick=()=>act('map');$('pack-button').onclick=()=>act('pack');$('map-close').onclick=closePanel;$('pack-close').onclick=closePanel;$('help-button').onclick=()=>{if(mode==='title')setMode('pause');else act('pause');};
$('title-controls').onclick=()=>setMode('pause');
$('confirm-yes').onclick=()=>answerConfirmation(true);$('confirm-no').onclick=()=>answerConfirmation(false);$('reload-button').onclick=()=>act('reload');$('fatal-retry').onclick=()=>location.reload();
for(const [id,action]of [['pack-heal','heal'],['pack-smoke','smoke'],['pack-reload','reload']])$(id).onclick=()=>{setMode('play');act(action);};
$('craft-med').onclick=()=>{craft(state,'medkit');ui.hud();};$('craft-smoke').onclick=()=>{craft(state,'smoke');ui.hud();};
$('xr-start').onclick=()=>void scene?.enterXR();
for(const id of ['muted','low','sensitivity','scanned','cinematic','motion','vibration','invertY','toggleSprint','deadzone']){const el=$(id);if(id==='sensitivity'||id==='deadzone')el.value=settings[id];else el.checked=settings[id==='muted'?'mute':id];el.oninput=()=>{settings[id==='muted'?'mute':id]=id==='sensitivity'||id==='deadzone'?Number(el.value):el.checked;write(SETTINGS,JSON.stringify(settings));scene?.setQuality(settings.low);scene?.setScanned(settings.scanned);scene?.setCinematic(settings.cinematic);scene?.setMotion(settings.motion);resize();audioStart();if(!settings.vibration)feedback.stop();$('sensitivity-value').textContent=settings.sensitivity;$('deadzone-value').textContent=settings.deadzone+'%';};}
$('sensitivity-value').textContent=settings.sensitivity;$('deadzone-value').textContent=settings.deadzone+'%';
function tick(now){if(!scene)return;const elapsed=Math.max(0,(now-(last||now))/1000),dt=Math.min(.25,elapsed);last=now;
 pad=gamepad.sample(navigator.getGamepads?.(),settings.deadzone/100);$('device').textContent=pad.connected?'STANDARD GAMEPAD / X RELOAD':'KEYBOARD + MOUSE';if(pad.disconnected){feedback.stop();if(mode==='play'||mode==='pack')setMode('pause');$('controller-status').textContent='Controller disconnected. Reconnect, release the controls, then press A to resume.';}else if(pad.connected)$('controller-status').textContent='A select / B back / D-pad or left stick navigate / left-right adjust / right stick scroll / LB-RB tabs';
 if(mode==='play'){if(settings.toggleSprint&&pad.sprintToggle)sprintLatched=!sprintLatched;for(const action of pad.actions){act(action);if(mode!=='play')break;}view.yaw-=(pad.look?.[0]||0)*dt*2.3*settings.sensitivity/85;view.pitch=Math.max(-.7,Math.min(.6,view.pitch-(pad.look?.[1]||0)*dt*1.7*settings.sensitivity/85*(settings.invertY?-1:1)));view.yaw+=((keys.has('ArrowLeft')?1:0)-(keys.has('ArrowRight')?1:0))*dt*1.6;view.pitch=Math.max(-.7,Math.min(.6,view.pitch+((keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0))*dt));}else if(mode!=='xr')menu.update(pad,dt);
 if(mode==='play')$('controller-menu-hint').hidden=true;
 view.aim=mode==='play'&&(keys.has('Aim')||touch.aim||pad.aim);const moving=motion();const input=mode==='play'?{...moving,aim:view.aim,yaw:view.yaw,listen:keys.has('KeyQ')||pad.listen||touch.listen,sprint:keys.has('ShiftLeft')||keys.has('ShiftRight')||(settings.toggleSprint?sprintLatched:pad.sprint)}:{x:0,z:0};
 if(mode==='play'||mode==='pack'){frameClock.advance(elapsed,step=>{update(state,input,step);if(mode==='play'&&(keys.has('Fire')||keys.has('KeyF')||pad.fire||touch.fire))fire(state,scene.aimDirection(state));return state.status==='playing';});if(state.status!=='playing')ui.endScreen();}else frameClock.reset();
 scene.render(state,view,dt);view.snap=false;for(const event of state.events)if(event.seq>eventSeq){eventSeq=event.seq;sound(event);feedback.event(event);}if(++frame%3===0){ui.hud();$('reload-state').textContent=state.player.reload>0?'RELOADING / '+state.player.reload.toFixed(1)+'s':state.player.mag===0?(state.player.reserve>0?(pad.connected?'EMPTY / PRESS X TO RELOAD':'EMPTY / PRESS R TO RELOAD'):'NO RESERVE AMMO / SCAVENGE SUPPLIES'):pad.connected?'X RELOAD / LT AIM / RT FIRE':'R RELOAD / RMB AIM / F FIRE';$('reload-button').textContent=pad.connected?'RELOAD [X]':'RELOAD [R]';$('pack-button').textContent=pad.connected?'SATCHEL [D-PAD DOWN]':'SATCHEL [TAB]';$('map-button').textContent=pad.connected?'MAP / JOURNAL [VIEW]':'MAP / HINTS [M]';stealth.update(state,view,mode);$('asset-status').textContent=scene.assetStatus().message;}
}
function resize(){scene?.resize(innerWidth,innerHeight);$('touch').hidden=mode!=='play'||!(matchMedia('(pointer:coarse)').matches||innerWidth<760);}
try{scene=makeScene();configureScene();resize();syncTitle();$('loading').textContent='';$('start').focus();window.Rainward={get state(){return state},get mode(){return mode},get view(){return {...view}},get renderer(){return scene.renderer},get chapter(){return CURRENT.id},project:(x,y,z)=>scene.project(x,y,z),snapshot:()=>({version:VERSION,level:state.level,completedTasks:[...state.completedTasks],trackedTask:state.trackedTask,puzzle:state.puzzle,drops:state.drops,mode,player:{...state.player},objectives:{...state.objectives},stats:{...state.stats},taken:[...state.taken],enemies:state.enemies.map(e=>({id:e.id,x:e.x,z:e.z,state:e.state,hp:e.hp,awareness:e.awareness,target:e.target})),events:state.events.map(e=>({...e})),camera:scene.cameraState(),assets:scene.assetStatus(),visuals:scene.visualStatus(),xr:scene.xrStatus(),clock:frameClock.stats(),renderer:scene.stats()})};scene.xrSupported().then(supported=>{$('xr-start').disabled=!supported;$('xr-status').textContent=supported?'Experimental stationary overlook. Mission pauses; trigger cycles views, grip exits.':'WebXR immersive VR is not available in this browser. Desktop play remains available.';});window.addEventListener('resize',resize);}catch(error){$('fatal-message').textContent=String(error.message||error);setMode('fatal');console.error(error);const fallback=()=>{if(mode!=='fatal')return;pad=gamepad.sample(navigator.getGamepads?.(),settings.deadzone/100);menu.update(pad,1/60);requestAnimationFrame(fallback);};requestAnimationFrame(fallback);}
