/* Original Rainward score; no recordings or provider keys. */
export const AUDIO_DEFAULTS=Object.freeze({masterVolume:75,musicVolume:40,effectsVolume:85,ambienceVolume:60,monoAudio:false,audioCaptions:true,nightAudio:false});
export const THEMES=Object.freeze({district:{name:'Rain on Wire',root:50,bpm:72,air:'rain',tone:'felt',motif:[0,7,10,5,3,7,2,0],chords:[0,8,5,10]},conservatory:{name:'A Memory Under Glass',root:57,bpm:66,air:'water',tone:'glass',motif:[0,3,7,14,10,7,5,2],chords:[0,5,8,3]},terminus:{name:'Last Train, No Passenger',root:45,bpm:80,air:'rail',tone:'pluck',motif:[0,0,7,3,10,5,2,7],chords:[0,3,8,5]},meridian:{name:'Windows Still Remember',root:52,bpm:74,air:'rain',tone:'pluck',motif:[0,7,3,2,10,7,5,3],chords:[0,8,3,10]},breakwater:{name:'Light Beyond the Seawall',root:48,bpm:68,air:'surf',tone:'felt',motif:[0,7,12,10,7,3,5,2],chords:[0,5,8,10]},whiteout:{name:'Footprints After Midnight',root:54,bpm:62,air:'wind',tone:'glass',motif:[0,2,7,10,5,3,2,0],chords:[0,8,5,3]}});
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function volume(value,fallback){return clamp(Number.isFinite(Number(value))?Number(value):fallback,0,100)/100;}
export function threatLevel(s){if(!s)return 0;return Math.max(s.player.hp<35?.22:0,...s.enemies.filter(e=>e.hp>0).map(e=>{const d=Math.hypot(e.x-s.player.x,e.z-s.player.z);return d>32?0:e.state==='chase'?1:['search','investigate'].includes(e.state)?.46:(e.awareness||0)*.65;}));}
export function smoothThreat(previous,target,dt){return previous+(target-previous)*(1-Math.exp(-Math.min(.25,dt)/(target>previous?.65:5.5)));}
export function spatialCue(listener,point,blocked=false,mono=false){const dx=point.x-listener.x,dz=point.z-listener.z,d=Math.hypot(dx,dz);const right=Math.cos(listener.yaw||0)*dx-Math.sin(listener.yaw||0)*dz;return {distance:d,pan:mono?0:clamp(right/Math.max(2,d),-.94,.94),gain:(d>40?0:1/(1+Math.max(0,d-1.5)*.16))*(blocked?.42:1),direction:Math.abs(right)>Math.abs(-Math.sin(listener.yaw||0)*dx-Math.cos(listener.yaw||0)*dz)?(right<0?'LEFT':'RIGHT'):(-Math.sin(listener.yaw||0)*dx-Math.cos(listener.yaw||0)*dz<0?'BEHIND':'AHEAD'),cutoff:blocked?850:14500};}
export function scoreStep(chapter,step){const theme=THEMES[chapter]||THEMES.district,bar=Math.floor(step/8),slot=step%8,chord=theme.chords[Math.floor(bar/2)%4],notes=[];
 if(slot===0){for(const [i,n]of [0,7,10].entries())notes.push({bus:'bed',kind:'bow',midi:theme.root-12+chord+n,duration:60/theme.bpm*4.2,gain:.12/(i+1),pan:(i-1)*.35});notes.push({bus:'pulse',kind:'bass',midi:theme.root-12+chord,duration:1.6,gain:.20,pan:0});}
 if(slot%2===0||bar%4===3){const tone=theme.motif[(slot+bar*2)%8];notes.push({bus:'melody',kind:theme.tone,midi:theme.root+12+tone,duration:slot%2?1.25:2.6,gain:slot%2?.17:.26,pan:Math.sin(step*.8)*.35});}
 if(slot%2===0)notes.push({bus:'tension',kind:'drum',midi:theme.root-12,duration:.65,gain:slot===0?.30:.17,pan:slot===4?-.2:.2});
 if(slot%2===1)notes.push({bus:'tension',kind:'tick',midi:theme.root+7+(slot%3)*2,duration:.25,gain:.12,pan:slot%4===1?-.4:.4});
 return {notes,seconds:30/theme.bpm,theme:theme.name};
}
export const CAPTIONS=Object.freeze({'enemy-shot':'Gunshot','enemy-melee':'A swing nearby','monster-attack':'Creature lunge','shriek':'A shriek carries through the district',reload:'Magazine released',reloaded:'Weapon ready',throw:'Bottle thrown',bottle:'Glass breaks','melee':'Melee swing','melee-hit':'Strike connects',damage:'Hit taken','heal-start':'Bandaging wounds',heal:'Bandage secured','craft-start':'Assembling supplies',crafted:'Item assembled','action-cancel':'Action interrupted',wheel:'Mechanism turns','puzzle-solved':'Gate mechanism opens',checkpoint:'Shelter recorded','task-complete':'Field task complete',pickup:'Supplies recovered',loot:'Dropped supplies recovered',death:'Expedition ended',complete:'A way through'});
