const $=id=>document.getElementById(id);
const actionMap={KeyC:'crouch',KeyZ:'prone',KeyE:'interact',Space:'dodge',KeyR:'reload',KeyB:'bottle',KeyX:'smoke',KeyH:'heal',KeyM:'map',Tab:'pack',KeyP:'pause',Escape:'pause'};
export function bindControls(E){const {keys,view,touch,canvas,act,setMode,settings,clearInput}=E;let lookDrag=null,wasLocked=false;
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||E.mode!=='play'&&e.code==='Tab'||e.target.tagName==='BUTTON'&&['Space','Enter'].includes(e.code))return;if(e.code==='Tab'||e.code==='Space'||e.code.startsWith('Arrow'))e.preventDefault();if(e.repeat)return;if(actionMap[e.code]){e.preventDefault();act(actionMap[e.code]);}else if(E.mode==='play')keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(E.mode!=='play'||e.pointerType==='touch')return;e.preventDefault();canvas.focus();if(e.button===2)keys.add('Aim');if(e.button===0){if(document.pointerLockElement===canvas)keys.add('Fire');else{lookDrag={x:e.clientX,y:e.clientY};try{const req=canvas.requestPointerLock();req?.catch(()=>{});}catch{}}}});
window.addEventListener('pointerup',()=>{keys.delete('Fire');keys.delete('Aim');lookDrag=null;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('mousemove',e=>{if(E.mode!=='play')return;const locked=document.pointerLockElement===canvas;if(locked||lookDrag){const dx=locked?e.movementX:e.clientX-lookDrag.x,dy=locked?e.movementY:e.clientY-lookDrag.y;view.yaw-=dx*.0022*settings.sensitivity/85;view.pitch=Math.max(-.7,Math.min(.6,view.pitch-dy*.0018*settings.sensitivity/85));if(lookDrag)lookDrag={x:e.clientX,y:e.clientY};}});
document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===canvas;if(wasLocked&&!locked&&E.mode==='play')setMode('pause');wasLocked=locked;keys.delete('Fire');});window.addEventListener('blur',()=>{if(E.mode==='play'||E.mode==='pack')setMode('pause');clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(E.mode==='play'||E.mode==='pack'))setMode('pause');});
function touchStick(id,callback){const el=$(id);let origin=null;el.addEventListener('pointerdown',e=>{e.preventDefault();origin={x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId);});el.addEventListener('pointermove',e=>{if(!origin)return;e.preventDefault();callback(e.clientX-origin.x,e.clientY-origin.y);});for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,()=>{origin=null;callback(0,0);});}
touchStick('touch-move',(x,z)=>{touch.x=Math.max(-1,Math.min(1,x/35));touch.z=Math.max(-1,Math.min(1,z/35));$('touch-move').firstElementChild.style.transform=`translate(${touch.x*22}px,${touch.z*22}px)`;});
let lastTouch=null;$('touch-look').onpointerdown=e=>{e.preventDefault();lastTouch={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);};$('touch-look').onpointermove=e=>{if(!lastTouch)return;view.yaw-=(e.clientX-lastTouch.x)*.005;view.pitch=Math.max(-.7,Math.min(.6,view.pitch-(e.clientY-lastTouch.y)*.004));lastTouch={x:e.clientX,y:e.clientY};};for(const event of ['pointerup','pointercancel','lostpointercapture'])$('touch-look').addEventListener(event,()=>lastTouch=null);
for(const b of document.querySelectorAll('[data-touch]'))b.onclick=()=>act(b.dataset.touch);for(const b of document.querySelectorAll('[data-hold]')){b.onpointerdown=e=>{e.preventDefault();touch[b.dataset.hold]=true;b.setPointerCapture(e.pointerId);};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>touch[b.dataset.hold]=false);}
return {clear(){lookDrag=null;lastTouch=null;}};}
