/* Original Rainward expedition layouts. Geometry is shared by rendering,
 * movement, visibility and navigation; every interior has authored entrances. */
const box=(id,x,z,w,d,h,kind='brick',bottom=0)=>({id,x,z,w,d,h,kind,bottom});
const cover=(id,x,z,w=4,d=1.4)=>box(id,x,z,w,d,1,'planter');
function room(id,x,z,w,d,h=8){return [
 box(id+'-back',x,z-d/2,w,1,h),
 box(id+'-front-l',x-w/4-1.5,z+d/2,w/2-3,1,h),box(id+'-front-r',x+w/4+1.5,z+d/2,w/2-3,1,h),
 box(id+'-west-a',x-w/2,z-d/4-1.5,1,d/2-3,h),box(id+'-west-b',x-w/2,z+d/4+1.5,1,d/2-3,h),
 box(id+'-east-a',x+w/2,z-d/4-1.5,1,d/2-3,h),box(id+'-east-b',x+w/2,z+d/4+1.5,1,d/2-3,h),
 ];}
const patrol=(id,name,type,points,yaw=0)=>({id,name,type,points,yaw});
const supplies=(id,x,z,label,ammo=6)=>({id,x,z,label,type:'supplies',ammo,cloth:2,canister:2,bottles:2});
const task=(id,x,z,title,description,kind='record',extra={})=>({id,x,z,title,description,kind,reward:{ammo:3,cloth:1},...extra});
export const LEGACY_TASKS={
 district:[task('ward-missing',-19,6,'The missing ward','Read the clinic register and leave a route marker for anyone following you.','record'),task('ward-radio',18,-11,'A voice in the rain','Repair the freight hall receiver after recovering the signal battery.','repair',{requires:['cell'],reward:{canister:2,ammo:4}})],
 conservatory:[task('archive-pages',-40,-3,'Pages above the water','Recover the rain-soaked catalogue from the western archive.','record'),task('garden-seeds',39,-19,'A garden for tomorrow','Seal the surviving seed collection before leaving the glasshouse.','supply',{reward:{cloth:2,canister:2}})],
 terminus:[task('last-dispatch',32,20,'The last dispatch','Record the abandoned dispatch desk message. It names a coastal evacuation route.','record'),task('station-radio',-31,-23,'The station answers','Restore the workshop radio once the railway power circuit is safe.','repair',{requires:['puzzle'],reward:{ammo:5,canister:2}})]
};
export const MERIDIAN={
 id:'meridian',title:'Meridian Ward',subtitle:'CHAPTER 04 / THE RECLAIMED CITY',number:4,
 bounds:{x0:-58,x1:58,z0:-88,z1:66},start:{x:0,z:58},
 intro:'Follow the yellow clinic signs. Find the water filter and service key, restore the clinic, and open the northern quarantine route. M opens the field journal.',
 objectiveNames:{cell:'Water filter',crank:'Service key'},objectivePrompt:'Recover the filter and service key.',
 exit:{x:0,z:-80,name:'North quarantine passage'},exitPrompt:'Leave Meridian Ward / continue to the coast',
 shelters:[{id:'meridian-arrival',x:0,z:58,name:'Arrival shelter'},{id:'meridian-clinic',x:-47,z:31,name:'Clinic back room'},{id:'meridian-library',x:45,z:-12,name:'Library reading room'},{id:'meridian-north',x:-17,z:-70,name:'North gate refuge'}],
 zones:[{name:'Arrival square',x:0,z:53},{name:'Field clinic',x:-39,z:28},{name:'Market arcade',x:38,z:30},{name:'Library and garage',x:39,z:-18},{name:'Service alleys',x:-38,z:-20},{name:'Quarantine gate',x:0,z:-63}],
 grass:[{x:-16,z:44,w:13,d:13},{x:17,z:43,w:12,d:17},{x:-18,z:11,w:9,d:16},{x:18,z:6,w:11,d:17},{x:-17,z:-34,w:12,d:16},{x:16,z:-37,w:11,d:13},{x:-39,z:-43,w:20,d:10},{x:38,z:-47,w:18,d:9},{x:-27,z:-76,w:18,d:12}],
 water:[{x:-8,z:35,w:10,d:6,depth:.16},{x:8,z:-6,w:8,d:10,depth:.23},{x:-39,z:-25,w:12,d:7,depth:.18}],
 buildings:[{x:-39,z:27,w:24,d:26,h:8,label:'MERIDIAN / FIELD CLINIC'},{x:39,z:29,w:24,d:26,h:10,label:'ORCHARD MARKET'},{x:-39,z:-18,w:24,d:28,h:9,label:'MUNICIPAL WORKS'},{x:39,z:-18,w:24,d:28,h:11,label:'LIBRARY / SERVICE GARAGE'},{x:-38,z:-51,w:24,d:17,h:7,label:'COMMUNITY KITCHEN'},{x:38,z:-51,w:24,d:17,h:8,label:'NORTH WATCH'}],
 obstacles:[
 box('meridian-edge-w',-59,-11,2,156,14),box('meridian-edge-e',59,-11,2,156,14),box('meridian-edge-s',0,67,120,2,6),box('meridian-edge-n',0,-89,120,2,13),
 ...room('clinic',-39,27,24,26),...room('market',39,29,24,26,10),...room('works',-39,-18,24,28,9),...room('library',39,-18,24,28,11),...room('kitchen',-38,-51,24,17,7),...room('watch',38,-51,24,17,8),
 box('clinic-bed',-35,23,2,4,.85,'counter'),box('market-counter',37,28,6,1.4,1,'counter'),box('works-shelf',-48,-22,1.2,7,2.6,'shelf'),box('library-shelf',48,-22,1.2,7,2.8,'shelf'),
 box('arrival-car',-9,43,4.9,2.15,1.4,'car'),box('market-bus',10,24,2.8,10,2.7,'bus'),box('alley-truck',-13,-18,2.6,6,2.3,'truck'),box('library-car',12,-25,2.1,4.8,1.5,'car'),box('north-car',-8,-47,4.8,2.1,1.3,'car'),
 cover('arrival-planter',3,43,5,2),cover('clinic-cover',-18,22),cover('market-cover',19,26),cover('fountain-west',-6,3,4,3),cover('fountain-east',6,3,4,3),cover('works-cover',-19,-25),cover('library-cover',22,-23),cover('north-cover',0,-37,7,2),
 box('crawl-roof',-16,34,7,3,.55,'slab',.64),box('crawl-foot-w',-19.6,34,.5,3,1.3,'pillar'),box('crawl-foot-e',-12.4,34,.5,3,1.3,'pillar'),
 box('checkpoint-west',-34,-63,48,1.8,8,'fence'),box('checkpoint-east',34,-63,48,1.8,8,'fence'),{...box('meridian-gate',0,-63,20,1.8,6,'gate'),openWhen:'meridian'},
 ],
 items:[supplies('meridian-kit',2,56,'Arrival emergency supplies',12),{id:'meridian-filter',x:-43,z:20,type:'objective',objective:'cell',label:'Sealed water filter'}, {id:'meridian-key',x:42,z:-27,type:'objective',objective:'crank',label:'Northern service key'},supplies('market-medicine',43,25,'Market medical case',8),supplies('works-tools',-43,-27,'Works toolbag',8),supplies('library-cache',33,-24,'Librarian supply satchel',8),supplies('underpass-cache',-16,34,'Drainage crawlspace cache',6),supplies('north-rations',-40,-53,'Kitchen stores',8)],
 patrols:[patrol('meridian-scout','Market patrol','watcher',[[5,30],[3,21],[-2,21],[-2,30]],Math.PI),patrol('meridian-raider-a','Arcade raider','raider',[[34,23],[43,23],[43,33],[34,33]]),patrol('meridian-rifle','Quarantine marksman','marksman',[[19,-50],[19,-56],[11,-56],[11,-50]],Math.PI),patrol('meridian-guard','Works sentry','sentinel',[[-34,-24],[-34,-13],[-44,-13],[-44,-24]]),patrol('meridian-raider-b','Library raider','raider',[[33,-27],[40,-27],[40,-18],[33,-18]]),patrol('meridian-hound','Drainage mire hound','prowler',[[-20,-8],[-16,-8],[-16,-2],[-20,-2]]),patrol('meridian-shrieker','Glasshouse shrieker','shrieker',[[14,-13],[19,-13],[19,-4],[14,-4]]),patrol('meridian-heavy','Kitchen rootback','brute',[[-34,-54],[-41,-54],[-41,-49],[-31,-49]]),patrol('meridian-north-watch','North gate patrol','watcher',[[12,-77],[22,-77],[22,-70],[12,-70]])],
 puzzle:{id:'meridian',symbols:['CLOSE','BYPASS','OPEN'],initial:[0,0,0],targets:[2,0,1],
 clue:{x:-42,z:35,label:'Read the clinic water diagram',text:'From west to east: OPEN the clinic supply; CLOSE the flooded central drain; BYPASS the library return. The northern gate releases when all three pressure lamps are safe.'},
 wheels:[{id:'clinic-valve',x:-42,z:28,label:'Clinic supply'},{id:'drain-valve',x:0,z:-29,label:'Central drain'},{id:'library-valve',x:42,z:-15,label:'Library return'}],clueLocation:'Inside the clinic south entrance, at the illuminated water diagram.',
 hints:['Enter the western clinic from the arrival square. The water diagram is inside its south doorway.','The diagram names three places, not three turns. Each valve advances CLOSE -> BYPASS -> OPEN independently.','Set Clinic supply to OPEN, Central drain to CLOSE, and Library return to BYPASS. The pressure gate then opens.'],gateText:'The quarantine pressure gate is open. Finish the clinic work and send the north relay signal.'},
 tasks:[task('clinic-power',-34,34,'Clean water, one room at a time','Install the recovered filter in the clinic purification unit.','repair',{required:true,requires:['cell'],reward:{health:20,canister:2}}),task('market-survivors',43,35,'Leave a way out','Mark the sheltered market passage and leave the evacuation instructions.','rescue',{reward:{cloth:2,canister:2}}),task('works-log',-34,-11,'Why the ward went dark','Read the maintenance ledger in Municipal Works.','record'),task('library-records',34,-10,'Save the neighborhood records','Seal the library records against the rain.','supply',{reward:{ammo:4,cloth:2}}),task('kitchen-radio',-34,-47,'The kitchen broadcast','Tune the community kitchen receiver after restoring clean water.','repair',{requires:['task:clinic-power'],reward:{health:20,ammo:5}}),task('meridian-signal',0,-72,'Send the all-clear','Use the service key to send the northern relay signal after opening the gate.','signal',{required:true,requires:['cell','crank','puzzle','task:clinic-power'],reward:{ammo:5,canister:2}})]
};
export const BREAKWATER={
 id:'breakwater',title:'Breakwater Signal',subtitle:'CHAPTER 05 / THE COAST AFTER THE STORM',number:5,
 bounds:{x0:-60,x1:60,z0:-106,z1:68},start:{x:0,z:59},
 intro:'The last ferry follows the foghorn. Recover the battery and lens, open the seawall, and relight the coast. The promenade and warehouse alleys both lead north.',
 objectiveNames:{cell:'Beacon battery',crank:'Signal lens'},objectivePrompt:'Find the battery and signal lens.',
 exit:{x:5,z:-99,name:'Rescue signal platform'},exitPrompt:'Transmit the coastal rescue signal / finish',
 shelters:[{id:'coast-arrival',x:0,z:59,name:'Coastal arrival shelter'},{id:'coast-boatshop',x:-43,z:28,name:'Boatshop refuge'},{id:'coast-museum',x:44,z:-17,name:'Museum refuge'},{id:'coast-beacon',x:13,z:-92,name:'Beacon shelter'}],
 zones:[{name:'Salt market',x:0,z:49},{name:'Boat repair yard',x:-38,z:25},{name:'Seafront promenade',x:11,z:14},{name:'Coastal museum',x:37,z:-24},{name:'Seawall control',x:-37,z:-41},{name:'Beacon approach',x:0,z:-82}],
 grass:[{x:-16,z:45,w:14,d:17},{x:18,z:44,w:14,d:15},{x:-20,z:7,w:12,d:15},{x:20,z:4,w:12,d:18},{x:-15,z:-23,w:11,d:15},{x:18,z:-47,w:14,d:16},{x:-38,z:-61,w:16,d:12},{x:37,z:-64,w:17,d:10}],
 water:[{x:0,z:30,w:15,d:8,depth:.25},{x:-7,z:2,w:12,d:12,depth:.30},{x:7,z:-30,w:10,d:15,depth:.25},{x:30,z:35,w:10,d:12,depth:.23}],
 buildings:[{x:-38,z:26,w:26,d:26,h:7,label:'SALT / BOAT REPAIR'},{x:38,z:25,w:26,d:24,h:8,label:'COASTAL MARKET'},{x:-38,z:-21,w:26,d:26,h:8,label:'SEAWALL WORKS'},{x:38,z:-24,w:26,d:30,h:11,label:'COASTAL MUSEUM'}],
 obstacles:[box('coast-edge-w',-61,-19,2,176,9,'rock'),box('coast-edge-e',61,-19,2,176,1.15,'rock'),box('coast-edge-s',0,69,124,2,8),box('coast-edge-n',0,-107,124,2,10,'rock'),
 ...room('boatshop',-38,26,26,26,7),...room('coast-market',38,25,26,24,8),...room('seawall-works',-38,-21,26,26,8),...room('museum',38,-24,26,30,11),
 box('boatshop-bench',-33,24,2,6,1,'counter'),box('museum-display',33,-27,3,7,1.05,'counter'),box('market-stall',37,24,6,2,1,'counter'),
 box('coast-bus',-9,42,2.8,10,2.6,'bus'),box('coast-car-1',11,22,4.8,2.1,1.4,'car'),box('coast-truck',-11,-17,2.6,6,2.3,'truck'),box('coast-car-2',14,-36,2.2,5,1.4,'car'),
 cover('promenade-west',-17,22,4,2),cover('promenade-east',17,14,4,2),cover('seaweed-bed',0,-8,5,2),cover('coast-cover-w',-19,-37,5,2),cover('coast-cover-e',20,-53,4,2),
 box('seawall-west',-35,-74,50,2,7,'fence',1.35),box('seawall-east',35,-74,50,2,7,'fence',1.35),{...box('coast-gate',0,-74,20,2,6,'gate',1.35),openWhen:'coast'},
 box('beacon-base',-7,-97,6,6,18,'lighthouse',4.8),
 ],
 items:[supplies('coast-kit',2,57,'Coastal emergency roll',12),{id:'coast-battery',x:-44,z:19,type:'objective',objective:'cell',label:'Weatherproof beacon battery'},{id:'coast-lens',x:43,z:-33,type:'objective',objective:'crank',label:'Preserved signal lens'},supplies('coast-market-kit',43,28,'Salt market case',8),supplies('coast-works-kit',-42,-29,'Seawall repair locker',10),supplies('coast-museum-kit',43,-14,'Museum emergency stores',8),supplies('coast-drift-kit',-35,-63,'Driftwood supply bag',6),supplies('coast-north-kit',18,-82,'Beacon maintenance cache',8)],
 patrols:[patrol('coast-raider-a','Market scavenger','raider',[[7,36],[16,36],[16,44],[7,44]]),patrol('coast-boatwatch','Boatshop sentinel','sentinel',[[-43,21],[-35,21],[-35,30],[-43,30]]),patrol('coast-rifle-a','Promenade marksman','marksman',[[22,4],[16,4],[16,-3],[22,-3]],Math.PI),patrol('coast-hound','Salt mire hound','prowler',[[-19,0],[-13,0],[-13,-7],[-19,-7]]),patrol('coast-raider-b','Works scavenger','raider',[[-32,-30],[-42,-30],[-42,-19],[-32,-19]]),patrol('coast-shrieker','Museum shrieker','shrieker',[[40,-30],[40,-22],[37,-22],[37,-30]]),patrol('coast-heavy','Seawall rootback','brute',[[4,-52],[-5,-52],[-5,-42],[4,-42]]),patrol('coast-rifle-b','Seawall marksman','marksman',[[-25,-65],[-19,-65],[-19,-57],[-25,-57]],Math.PI),patrol('coast-watch','Beacon sentinel','sentinel',[[19,-100],[27,-100],[27,-91],[19,-91]]),patrol('coast-drifter','Shore echo drifter','drifter',[[35,-61],[43,-61],[43,-54],[35,-54]])],
 puzzle:{id:'coast',symbols:['LAND','HARBOR','SEA'],initial:[0,0,0],targets:[1,2,0],clue:{x:-43,z:-12,label:'Read the seawall tide chart',text:'Send the western outlet to HARBOR, the central outlet to SEA, and keep the eastern refuge on LAND. Three safe channels release the seawall gate.'},wheels:[{id:'west-tide',x:-43,z:-22,label:'Western outlet'},{id:'central-tide',x:0,z:-42,label:'Central outlet'},{id:'east-tide',x:43,z:-20,label:'Eastern refuge'}],clueLocation:'Inside Seawall Works, beside its south doorway.',hints:['Enter Seawall Works on the west of the promenade. Read the lit tide chart beside the entrance.','Match each outlet to its destination. The eastern refuge must stay dry; it belongs on LAND.','Set Western outlet to HARBOR, Central outlet to SEA, and Eastern refuge to LAND.'],gateText:'The seawall passage is open. Follow the rising beacon road and install the signal lens.'},
 tasks:[task('coast-foghorn',-33,34,'A sound through the fog','Connect the recovered battery to the boatyard foghorn.','repair',{required:true,requires:['cell'],reward:{health:20,canister:2}}),task('coast-supplies',43,33,'Stores for the next boat','Secure the market emergency stores for the next ferry crew.','supply',{reward:{cloth:2,ammo:4}}),task('coast-radio',-33,-14,'The coast is listening','Read the coastguard frequency card inside Seawall Works.','record'),task('coast-archive',33,-15,'Remember the shoreline','Protect the museum survey archive from the next tide.','record',{reward:{canister:2,ammo:4}}),task('coast-marker',-34,-58,'Mark the safe channel','Raise the harbor channel marker after sounding the foghorn.','rescue',{requires:['task:coast-foghorn'],reward:{health:20,cloth:2}}),task('coast-beacon',2,-94,'A light beyond the rain','Install the signal lens and bring the beacon online.','signal',{required:true,requires:['crank','puzzle','task:coast-foghorn'],reward:{health:20,ammo:5}})]
};


export const WHITEOUT={
 id:'whiteout',title:'Whiteout Market',subtitle:'CHAPTER 06 / THE FROZEN QUARTER',number:6,
 bounds:{x0:-62,x1:62,z0:-112,z1:70},start:{x:0,z:61},
 intro:'The cold front buried the upper district overnight. Recover the generator fuse and tram crank, relight the warming stations, and reopen the north tunnel before the next whiteout closes in.',
 objectiveNames:{cell:'Generator fuse',crank:'Tram crank'},objectivePrompt:'Recover the generator fuse and tram crank.',
 exit:{x:0,z:-104,name:'North transit tunnel'},exitPrompt:'Open the north transit tunnel / finish',
 shelters:[{id:'snow-arrival',x:0,z:61,name:'Bus depot shelter'},{id:'snow-clinic',x:-45,z:27,name:'Pharmacy back room'},{id:'snow-hall',x:45,z:-23,name:'Community hall'},{id:'snow-tunnel',x:-16,z:-94,name:'Tunnel refuge'}],
 zones:[{name:'Snowbound avenue',x:0,z:52},{name:'Pharmacy row',x:-40,z:27},{name:'Winter market',x:39,z:28},{name:'Tram square',x:0,z:-12},{name:'Community hall',x:40,z:-28},{name:'North tunnel',x:0,z:-92}],
 grass:[{x:-18,z:45,w:14,d:14},{x:18,z:43,w:14,d:14},{x:-19,z:4,w:12,d:18},{x:20,z:2,w:13,d:17},{x:-18,z:-37,w:12,d:14},{x:18,z:-48,w:13,d:16},{x:-39,z:-73,w:17,d:11},{x:39,z:-75,w:17,d:11}],
 water:[],
 buildings:[{x:-40,z:27,w:27,d:25,h:8,label:'NORTHLINE PHARMACY'},{x:40,z:28,w:27,d:26,h:9,label:'WINTER MARKET'},{x:-40,z:-23,w:27,d:29,h:9,label:'TRAM MAINTENANCE'},{x:40,z:-27,w:27,d:31,h:10,label:'COMMUNITY HALL'},{x:-39,z:-67,w:25,d:18,h:8,label:'WARMING CENTER'},{x:39,z:-68,w:25,d:18,h:8,label:'FREIGHT ANNEX'}],
 obstacles:[
  box('snow-edge-w',-63,-21,2,184,13,'brick'),box('snow-edge-e',63,-21,2,184,13,'brick'),box('snow-edge-s',0,71,128,2,7),box('snow-edge-n',0,-113,128,2,12),
  ...room('snow-pharmacy',-40,27,27,25,8),...room('snow-market',40,28,27,26,9),...room('snow-tram',-40,-23,27,29,9),...room('snow-hall',40,-27,27,31,10),...room('snow-warm',-39,-67,25,18,8),...room('snow-freight',39,-68,25,18,8),
  box('snow-bus',-10,43,2.9,10,2.7,'bus'),box('snow-car-a',11,29,4.9,2.2,1.4,'car'),box('snow-truck',-13,-15,2.7,6.3,2.4,'truck'),box('snow-car-b',14,-42,4.9,2.2,1.4,'car'),
  box('snow-market-counter',39,29,6,1.5,1,'counter'),box('snow-tram-shelf',-49,-25,1.3,8,2.8,'shelf'),box('snow-hall-table',35,-27,6,1.4,1,'counter'),
  cover('snow-cover-a',-18,24,5,2),cover('snow-cover-b',18,18,5,2),cover('snow-cover-c',-19,-31,5,2),cover('snow-cover-d',20,-47,5,2),cover('snow-cover-e',0,-68,7,2),
  box('snow-gate-west',-36,-87,52,2,7,'fence'),box('snow-gate-east',36,-87,52,2,7,'fence'),{...box('snow-gate',0,-87,20,2,6,'gate'),openWhen:'whiteout'},
 ],
 items:[supplies('snow-kit',2,59,'Cold-weather emergency pack',12),{id:'snow-fuse',x:-45,z:20,type:'objective',objective:'cell',label:'Substation generator fuse'},{id:'snow-crank',x:45,z:-35,type:'objective',objective:'crank',label:'Manual tram crank'},supplies('snow-market-meds',45,31,'Winter market medical crate',9),supplies('snow-tram-tools',-45,-33,'Tram maintenance tools',9),supplies('snow-hall-supplies',45,-17,'Community hall stores',8),supplies('snow-warm-cache',-42,-72,'Warming-center cache',7),supplies('snow-tunnel-cache',18,-97,'Tunnel emergency cache',8)],
 patrols:[patrol('snow-raider-a','Market raider','raider',[[34,23],[45,23],[45,33],[34,33]]),patrol('snow-rifle-a','Pharmacy marksman','marksman',[[-22,14],[-16,14],[-16,7],[-22,7]],Math.PI),patrol('snow-sentinel','Tram sentinel','sentinel',[[-34,-29],[-44,-29],[-44,-18],[-34,-18]]),patrol('snow-hound','Whiteout mire hound','prowler',[[-15,-5],[-9,-5],[-9,-12],[-15,-12]]),patrol('snow-raider-b','Hall scavenger','raider',[[34,-34],[44,-34],[44,-24],[34,-24]]),patrol('snow-shrieker','Alley shrieker','shrieker',[[9,-50],[14,-50],[14,-46],[9,-46]]),patrol('snow-heavy','Warming-center rootback','brute',[[-31,-75],[-42,-75],[-42,-66],[-31,-66]]),patrol('snow-rifle-b','Tunnel marksman','marksman',[[20,-98],[28,-98],[28,-92],[20,-92]],Math.PI),patrol('snow-watch','Freight sentinel','sentinel',[[33,-74],[44,-74],[44,-66],[33,-66]]),patrol('snow-drifter','Snowblind drifter','drifter',[[5,-60],[-4,-60],[-4,-53],[5,-53]])],
 puzzle:{id:'whiteout',symbols:['LOW','HEAT','VENT'],initial:[0,0,0],targets:[1,2,1],clue:{x:-45,z:-14,label:'Read the tram heat-routing board',text:'Route the pharmacy line to HEAT, the square line to VENT, and keep the community line on HEAT. The north tunnel interlock releases when all three lamps agree.'},wheels:[{id:'snow-west-heat',x:-45,z:-23,label:'Pharmacy line'},{id:'snow-square-heat',x:0,z:-52,label:'Square line'},{id:'snow-east-heat',x:45,z:-28,label:'Community line'}],clueLocation:'Inside Tram Maintenance, beside the south service door.',hints:['Enter Tram Maintenance west of the square and read the lit heat-routing board.','Each control cycles LOW -> HEAT -> VENT. The center line must exhaust snowmelt vapor.','Set Pharmacy to HEAT, Square to VENT, and Community to HEAT.'],gateText:'The north tunnel interlock is open. Bring the warming stations online before leaving.'},
 tasks:[task('snow-pharmacy-heat',-35,34,'Warm the pharmacy','Install the generator fuse and restart the pharmacy heater.','repair',{required:true,requires:['cell'],reward:{health:25,canister:2}}),task('snow-market-route',45,36,'Mark the covered route','Raise the market route marker so evacuees can cross the avenue in low visibility.','rescue',{reward:{cloth:2,ammo:4}}),task('snow-tram-log',-34,-15,'Last tram out','Read the transit operator log inside maintenance.','record'),task('snow-hall-stores',35,-17,'Stock the community hall','Secure the emergency food and blankets before the next storm band.','supply',{reward:{cloth:3,canister:2}}),task('snow-warming',-34,-61,'Light the warming center','Bring the secondary heater online after restoring the pharmacy.','repair',{required:true,requires:['task:snow-pharmacy-heat'],reward:{health:25,ammo:5}}),task('snow-tunnel-signal',0,-96,'Open the winter road','Use the tram crank and heat-routing interlock to send the tunnel-open signal.','signal',{required:true,requires:['crank','puzzle','task:snow-pharmacy-heat','task:snow-warming'],reward:{ammo:6,canister:2}})]
};

// Console collision is deliberately offset from its usable standing position.
for(const chapter of [MERIDIAN,BREAKWATER,WHITEOUT]){
 for(const t of chapter.tasks)chapter.obstacles.push({...box('task-prop-'+t.id,t.x,t.z-.7,.72,.45,t.kind==='record'||t.kind==='supply'?.82:1.12,'task',chapter.id==='breakwater'&&t.z< -65?Math.min(5.4,(-t.z-65)*.15):0),renderAsTask:true});
 for(const w of chapter.puzzle.wheels)chapter.obstacles.push({...box('control-prop-'+w.id,w.x,w.z-.65,.72,.38,1.38,'task'),renderAsTask:true});
}
