import {CURRENT,BOUNDS,heightAt,OBSTACLES,GRASS,ITEMS,SHELTERS,EXIT,HEIGHT,dist,coverAt} from './world.mjs';
import {interactable,RECIPES} from './model.mjs';
const $=id=>document.getElementById(id);
export function createHUD(E){const {setMode,closePanel}=E;let navLast=0;
function drawMap(){const state=E.state;const c=$('map'),g=c.getContext('2d'),w=c.width,h=c.height,scale=Math.min((w-45)/(BOUNDS.x1-BOUNDS.x0),(h-45)/(BOUNDS.z1-BOUNDS.z0)),x=v=>w/2+(v-(BOUNDS.x0+BOUNDS.x1)/2)*scale,z=v=>22+(v-BOUNDS.z0)*scale;g.fillStyle='#223b31';g.fillRect(0,0,w,h);g.strokeStyle='#70867433';g.lineWidth=1;for(let i=-35;i<36;i+=5){g.beginPath();g.moveTo(x(i),20);g.lineTo(x(i),h-20);g.stroke();}for(const patch of GRASS){g.fillStyle='#567654';g.fillRect(x(patch.x-patch.w/2),z(patch.z-patch.d/2),patch.w*scale,patch.d*scale);}for(const o of OBSTACLES){if(o.disabled)continue;g.fillStyle=o.h>1.5?'#91a18a':'#657c67';g.fillRect(x(o.x-o.w/2),z(o.z-o.d/2),o.w*scale,o.d*scale);}g.textAlign='center';g.font='bold 18px monospace';for(const i of ITEMS){if(state.taken.has(i.id))continue;g.fillStyle=i.type==='objective'?'#e6d4a2':'#bacbae';g.fillText(i.objective==='cell'?'+':i.objective==='crank'?'◇':'·',x(i.x),z(i.z));}g.fillStyle='#dbc393';g.fillText('↗',x(EXIT.x),z(EXIT.z));for(const s of SHELTERS)g.fillText('△',x(s.x),z(s.z));if(CURRENT.puzzle){for(const p of CURRENT.puzzle.wheels){g.fillStyle=state.puzzle.solved?'#a8d69b':'#edb67e';g.fillText('◉',x(p.x),z(p.z));}}g.fillStyle='#d9e5ce';g.beginPath();g.arc(x(state.player.x),z(state.player.z),5,0,7);g.fill();g.font='11px Arial';g.fillText('YOU',x(state.player.x),z(state.player.z)+17);}
function hud(){const {state,view,pad,mode,scene}=E;const p=state.player;document.body.classList.toggle('aiming',view.aim);document.body.classList.toggle('hurt',p.invulnerable>.15);$('health-fill').style.transform=`scaleX(${p.hp/100})`;$('stamina-fill').style.transform=`scaleX(${p.stamina/100})`;$('stance').textContent=p.stance.toUpperCase()+' · '+(coverAt(p)&&p.stance!=='stand'?'CONCEALED':'EXPOSED');$('ammo').innerHTML=String(p.mag).padStart(2,'0')+' <small>/ '+p.reserve+'</small>';$('quick-items').textContent=`BOTTLES ${p.bottles}   MED ${p.medkit}   SMOKE ${p.smoke}`;
 $('objective-title').textContent=state.level==='conservatory'?(state.puzzle.solved?(state.objectives.cell&&state.objectives.crank?'Reach the north sanctuary.':'Recover the lens and core.'):'Read the archive. Open the sluice.'):(state.objectives.cell&&state.objectives.crank?'Reach the floodgate.':'Recover the components.');$('objective-progress').textContent=(state.level==='conservatory'?'LENS ':'BATTERY ')+(state.objectives.cell?'✓':'—')+(state.level==='conservatory'?' / CORE ':' / SPINDLE ')+(state.objectives.crank?'✓':'—');const target=mode==='play'?interactable(state):null;$('prompt').hidden=!target;$('prompt').textContent=target?(pad.connected?'[Y] ':'[E] ')+target.label:'';$('hint').textContent=state.hintTime>0?state.hint:'';
 const danger=Math.max(0,...state.enemies.filter(e=>e.hp>0).map(e=>e.awareness));const searching=state.enemies.some(e=>e.hp>0&&e.state!=='patrol');$('suspicion-text').textContent=danger>=.95?'SPOTTED':danger>.2?'SUSPICIOUS':searching?'SEARCHING':'UNSEEN';$('suspicion-meter').value=danger;
 $('materials').textContent=`FABRIC ${p.cloth} / SALVAGE ${p.canister}\nMEDKITS ${p.medkit} / SMOKE ${p.smoke}`;for(const kind of ['med','smoke']){const item=kind==='med'?'medkit':'smoke';$('craft-'+kind).disabled=!!p.craft||p.cloth<1||p.canister<1||p[item]>=3;}$('craft-progress').value=p.craft?1-p.craft.left/RECIPES[p.craft.item].time:0;$('craft-status').textContent=p.craft?'Crafting '+p.craft.item+'…':'Use H to heal. X deploys smoke cover.';
 $('puzzle-journal').hidden=state.level!=='conservatory';if(state.puzzle)$('puzzle-journal').textContent=(state.puzzle.clueRead?CURRENT.puzzle.clue.text:'Read the inscription in the western archive. The three wheels control the north gate.')+' Current: '+state.puzzle.wheels.map(v=>CURRENT.puzzle.symbols[v]).join(' / ')+(state.puzzle.solved?' — GATE OPEN':'');$('chapter-name').textContent=CURRENT.title;
 const labels=$('world-labels');labels.replaceChildren();if(mode!=='play')return;const markers=[];
 for(const i of ITEMS)if(!state.taken.has(i.id)&&(i.type==='objective'||dist(i,p)<6))markers.push({x:i.x,y:heightAt(i.x,i.z)+1.1,z:i.z,symbol:i.type==='objective'?'◇':'·',text:i.type==='objective'?Math.round(dist(i,p))+'m':i.label});
 if(state.objectives.cell&&state.objectives.crank)markers.push({...EXIT,y:heightAt(EXIT.x,EXIT.z)+2.5,symbol:'↗',text:'EXTRACT '+Math.round(dist(p,EXIT))+'m'});
 for(const e of state.enemies)if(e.hp>0&&((p.listen&&dist(e,p)<14)||(e.awareness>.2&&e.seen)))markers.push({x:e.x,z:e.z,y:heightAt(e.x,e.z)+2.25,symbol:e.state==='chase'?'!':'?',text:p.listen?e.type==='drifter'?'UNEVEN BREATHING':'FOOTSTEPS':e.state.toUpperCase(),enemy:true});
 for(const d of state.drops||[])if(Object.values(d.items).some(v=>v>0)&&dist(d,p)<12)markers.push({x:d.x,y:heightAt(d.x,d.z)+.8,z:d.z,symbol:'◇',text:'DROPPED SUPPLIES'});
 if(state.puzzle&&!state.puzzle.solved)for(const [i,w]of CURRENT.puzzle.wheels.entries())if(dist(w,p)<9)markers.push({...w,y:3.6,symbol:'◉',text:CURRENT.puzzle.symbols[state.puzzle.wheels[i]]});
 for(const mark of markers){const q=scene.project(mark.x,mark.y,mark.z);if(!q.visible)continue;const el=document.createElement('div');el.className='world-label'+(mark.enemy?' guard':'');el.style.left=q.x*100+'%';el.style.top=q.y*100+'%';const icon=document.createElement('span');icon.className='symbol';icon.textContent=mark.symbol;el.append(icon,document.createTextNode(mark.text));labels.append(el);}
}
function endScreen(){const state=E.state;setMode(state.status==='won'?'won':'dead');const won=state.status==='won';$('result-kind').textContent=won?(state.level==='conservatory'?'CHAPTER 02 / COMPLETE':'CHAPTER 01 / COMPLETE'):'CHECKPOINT AVAILABLE';$('result-title').textContent=won?'A way through.':'Try another approach.';$('result-text').textContent=won?(state.level==='conservatory'?'The archive is recovered and the north waterway is open. The conservatory expedition is complete.':'The floodgate is open. The Drowned Conservatory is ready to explore.'):'Break line of sight. Use grass, a bottle, or smoke. Your last shelter checkpoint is unchanged.';$('result-retry').hidden=won;$('result-next').hidden=!won||state.level==='conservatory';$('result-stats').innerHTML=`<div><strong>${Math.floor(state.t/60)}:${String(Math.floor(state.t%60)).padStart(2,'0')}</strong>TIME</div><div><strong>${state.stats.alerts}</strong>ALARMS</div><div><strong>${state.stats.shots}</strong>SHOTS</div><div><strong>${state.taken.size}/${ITEMS.length}</strong>SUPPLIES RECOVERED</div>`;}
function menuPad(dt){const pad=E.pad;if(!pad.connected)return;const visibleButtons=[...document.querySelectorAll('.sheet:not([hidden]) button')].filter(el=>!el.disabled&&!el.hidden&&el.offsetHeight);const axis=pad.nav||0;if(Math.abs(axis)>.55&&performance.now()-navLast>230){navLast=performance.now();let i=visibleButtons.indexOf(document.activeElement);i=(i+(axis>0?1:-1)+visibleButtons.length)%visibleButtons.length;visibleButtons[i]?.focus();}if(pad.confirm){const focused=visibleButtons.includes(document.activeElement)?document.activeElement:visibleButtons[0];focused?.click();}if(pad.back)closePanel();}
return {drawMap,hud,endScreen,menuPad};}
