import * as T from './vendor/three.module.js';
import {CURRENT,OBSTACLES,heightAt} from './world.mjs';
import {rnd} from './artkit.mjs';
function tileTexture(){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#bcc9c5';g.fillRect(0,0,256,256);g.strokeStyle='#617b78';g.lineWidth=3;for(let i=0;i<=256;i+=32){g.beginPath();g.moveTo(i,0);g.lineTo(i,256);g.stroke();g.beginPath();g.moveTo(0,i);g.lineTo(256,i);g.stroke();}for(let i=0;i<120;i++){g.fillStyle=`rgba(45,73,70,${.018+rnd(i)*.026})`;g.fillRect(rnd(i+11)*256,rnd(i+91)*256,2+rnd(i+23)*8,2+rnd(i+44)*8);}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(6,8);t.anisotropy=4;return t;}
function poolSurface(width,depth,waterDepth,id){const uniforms={time:{value:0},deep:{value:waterDepth},tint:{value:id==='divewell'?new T.Color(0x17484e):id==='filter-channel'?new T.Color(0x1e5557):new T.Color(0x2e6b6a)}};const material=new T.ShaderMaterial({uniforms,transparent:true,depthWrite:false,side:T.DoubleSide,vertexShader:`varying vec2 vUv;varying vec3 vWorld;varying float vWave;uniform float time;void main(){vUv=uv;vec3 p=position;float a=sin(p.x*.72+time*1.25)*.028;float b=sin(p.y*1.05-time*.87)*.020;float c=sin((p.x+p.y)*1.7+time*.51)*.009;vWave=a+b+c;p.z+=vWave;vec4 world=modelMatrix*vec4(p,1.);vWorld=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`,fragmentShader:`varying vec2 vUv;varying vec3 vWorld;varying float vWave;uniform float time;uniform float deep;uniform vec3 tint;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1)),f.x),f.y);}void main(){vec3 V=normalize(cameraPosition-vWorld);float fres=pow(1.-clamp(abs(V.y),0.,1.),2.2);vec2 q=vWorld.xz;float ca=pow(abs(sin(q.x*2.2+time*1.4)*sin(q.y*2.7-time*1.1)),5.);float drift=n(q*.38+vec2(time*.05,-time*.03));vec3 shallow=mix(vec3(.12,.40,.40),vec3(.22,.56,.52),drift);vec3 col=mix(tint,shallow,.32+ca*.18);col+=vec3(.34,.50,.48)*(fres*.34+ca*.12);float edge=smoothstep(0.,.06,min(min(vUv.x,1.-vUv.x),min(vUv.y,1.-vUv.y)));float foam=(1.-edge)*(.20+.18*sin(time*4.+q.x*2.));gl_FragColor=vec4(col+foam,.57+fres*.18);}`});const mesh=new T.Mesh(new T.PlaneGeometry(width,depth,16,24),material);mesh.rotation.x=-Math.PI/2;mesh.renderOrder=4;mesh.userData.poolWater=true;return {mesh,material,uniforms};}
function caustics(width,depth,color=0x8fd4c6){const material=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{time:{value:0},color:{value:new T.Color(color)}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;uniform float time;uniform vec3 color;float bands(vec2 p){float a=abs(sin((p.x+p.y)*32.+time*1.8));float b=abs(sin((p.x-p.y)*27.-time*1.35));return pow(1.-min(a,b),7.);}void main(){float c=bands(vUv+vec2(sin(time*.2)*.02,cos(time*.17)*.02));gl_FragColor=vec4(color,c*.20);}`});const mesh=new T.Mesh(new T.PlaneGeometry(width,depth),material);mesh.rotation.x=-Math.PI/2;mesh.renderOrder=2;return {mesh,material};}
export function buildNatatorium(scene,A){const {add,mesh,label,mat,buckets}=A,dynamic={water:[],caustics:[],lights:[]},tile=tileTexture(),tileMat=new T.MeshStandardMaterial({map:tile,color:0xd0d8d4,roughness:.74,metalness:.03}),trim=mat(0x5f7876,'metal');
 scene.background=new T.Color(0x71817f);scene.fog.color.setHex(0x71817f);scene.fog.density=.011;
 for(const o of OBSTACLES){if(o.openWhen){const g=new T.Group();g.position.set(o.x,o.bottom,o.z);for(let x=-o.w/2+.4;x<o.w/2;x+=.7){const b=mesh('box',[.16,o.h,.22],0x6a7775,'metal');b.position.set(x,o.h/2,0);g.add(b);}scene.add(g);dynamic.gate=g;continue;}if(o.kind==='column')add('cyl',o.x,o.bottom+o.h/2,o.z,.42,o.h,.42,0xbac7c2,'stone');else add('box',o.x,o.bottom+o.h/2,o.z,o.w,o.h,o.d,o.kind==='tile'?0xc6cfcb:0x677573,o.kind==='tile'?'stone':o.kind);}
 // Most fluorescent strips are emissive geometry. Three real area lights establish
 // the long indoor pools without making every software-rendered pixel evaluate ten lights.
 for(let z=47;z>-70;z-=12){for(const x of[-38,-19,0,19,38])add('box',x,8.8,z,15,.18,.28,0x6b7472,'metal',0,0,(x/38)*.035);add('box',0,8.1,z,8,.08,.32,0xd9efea,'glow');}
 for(const z of[35,-7,-49]){const light=new T.RectAreaLight(0xcbe3dd,7.5,20,.35);light.position.set(0,8.0,z);light.rotation.x=-Math.PI/2;scene.add(light);dynamic.lights.push(light);}
 add('box',0,9.3,-7,94,.35,124,0x6f7a78,'stone');
 for(const p of CURRENT.water){if(!p.pool)continue;const y=p.surface??.28,wall=.22;
  const bottom=new T.Mesh(new T.BoxGeometry(p.w,p.depth*.12,p.d),tileMat);bottom.position.set(p.x,-p.depth-.06,p.z);scene.add(bottom);
  for(const [x,z,w,d]of[[p.x-p.w/2-wall/2,p.z,wall,p.d+wall*2],[p.x+p.w/2+wall/2,p.z,wall,p.d+wall*2],[p.x,p.z-p.d/2-wall/2,p.w,wall],[p.x,p.z+p.d/2+wall/2,p.w,wall]]){const side=new T.Mesh(new T.BoxGeometry(w,p.depth,d),tileMat);side.position.set(x,-p.depth/2,z);scene.add(side);}
  const laneMat=new T.MeshBasicMaterial({color:0x214a59});if(p.id==='competition')for(let i=-2;i<=2;i++){const lane=new T.Mesh(new T.BoxGeometry(.075,.025,p.d*.92),laneMat);lane.position.set(p.x+i*3,-p.depth+.03,p.z);scene.add(lane);}
  const water=poolSurface(p.w,p.d,p.depth,p.id);water.mesh.position.set(p.x,y,p.z);scene.add(water.mesh);dynamic.water.push(water);
  const glow=caustics(p.w*.98,p.d*.98);glow.mesh.position.set(p.x,-p.depth+.09,p.z);scene.add(glow.mesh);dynamic.caustics.push(glow);
  for(const side of[-1,1]){const lx=p.x+side*(p.w/2-.9),lz=p.z+p.d/2+.45;for(const xx of[-.18,.18])add('cyl',lx+xx,.48,lz,.028,1.25,.028,0x889796,'metal');for(let r=0;r<4;r++)add('cyl',lx,.12-r*.22,lz,.025,.36,.025,0x889796,'metal',0,0,Math.PI/2);}
 }
 for(const [x,z]of[[-8,31],[8,31],[-7,-4],[29,-27]]){add('box',x,.42,z,4,.16,.72,0x747a70,'wood');add('box',x-1.6,.2,z,.10,.4,.6,0x66726e,'metal');add('box',x+1.6,.2,z,.10,.4,.6,0x66726e,'metal');}
 for(const [x,z]of[[-5,10],[30,10],[-29,-22]]){add('box',x,1.5,z,1.2,3,.8,0xe6e2ce,'tile');add('box',x,3.25,z,2.4,.25,1.2,0x687b79,'metal');}
 label('NORTHLIGHT\nNATATORIUM',-18,5.4,48.6,8,1.7,'#536966','#e8e6d7');label('COMPETITION POOL\nDEEP WATER',15,.95,22.2,5,1.0,'#31585b','#edf0e4');label('DIVING WELL\n3.1 M',-18,.95,-16.5,4.2,.9,'#31585b','#edf0e4');label('FILTER GALLERY',13,1.2,-40.5,4.2,.8,'#31585b','#edf0e4');label('PUMP ROOM / DRY',-36,2.8,-40.5,4.4,.8,'#5c6156','#ece1be');
 for(const z of[13,1,-11]){const lamp=new T.PointLight(0x5ec9c0,3.4,8,2);lamp.position.set(15,-1.1,z);scene.add(lamp);dynamic.lights.push(lamp);}
 for(const {geo,mat:m,items}of buckets.values()){const inst=new T.InstancedMesh(geo,m,items.length);items.forEach((v,i)=>inst.setMatrixAt(i,v));inst.instanceMatrix.needsUpdate=true;inst.castShadow=true;inst.receiveShadow=true;inst.computeBoundingSphere();scene.add(inst);}
 return {update(s,dt){const t=s.t;dynamic.water.forEach((w,i)=>w.uniforms.time.value=t+i*.37);dynamic.caustics.forEach((c,i)=>c.material.uniforms.time.value=t+i*.23);if(dynamic.gate)dynamic.gate.position.y+=((s.puzzle?.solved?8:0)-dynamic.gate.position.y)*Math.min(1,dt*3);},dispose(){tile.dispose();tileMat.dispose();for(const w of dynamic.water){w.mesh.geometry.dispose();w.material.dispose();}for(const c of dynamic.caustics){c.mesh.geometry.dispose();c.material.dispose();}dynamic.lights.forEach(l=>l.dispose?.());},stats:()=>({waterSurfaces:dynamic.water.length,causticProjectors:dynamic.caustics.length,activeLights:dynamic.lights.length,extraRenderTargets:0})};
}
