import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
// Bytes may be reused between chapter changes; decoded GPU resources never are.
const files={female:new URL('./assets/humans/survivor-female.glb',import.meta.url),male:new URL('./assets/humans/survivor-male.glb',import.meta.url)},byteCache=new Map();
const boneNames=['hips','spine','chest','neck','head','armL','elbowL','handL','armR','elbowR','handR','legL','kneeL','footL','legR','kneeR','footR'];
function bytes(gender){if(!byteCache.has(gender)){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),12000);const request=fetch(files[gender],{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('Human model HTTP '+r.status);return r.arrayBuffer();}).then(data=>{if(data.byteLength>3000000||new DataView(data).getUint32(0,true)!==0x46546c67)throw Error('Invalid human model');return data;}).finally(()=>clearTimeout(timer)).catch(error=>{byteCache.delete(gender);throw error;});byteCache.set(gender,request);}return byteCache.get(gender);}
export function validateHumanSource(gltf){const parts=[];gltf.scene.traverse(o=>{if(!o.isSkinnedMesh)return;if(o.skeleton.bones.length!==17||o.skeleton.bones.some((b,i)=>b.name!==boneNames[i]))throw Error('Human model rig does not match Rainward');for(const name of ['position','normal','uv','skinIndex','skinWeight'])if(!o.geometry.attributes[name])throw Error('Incomplete human surface');parts.push(o);});if(parts.length<5||parts.length>12)throw Error('Unexpected human material budget');return parts;}
function releaseTemplate(gltf){const geometry=new Set(),materials=new Set(),textures=new Set(),skeletons=new Set();gltf.scene.traverse(o=>{if(o.geometry)geometry.add(o.geometry);if(o.skeleton)skeletons.add(o.skeleton);for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[]){materials.add(m);for(const value of Object.values(m))if(value?.isTexture)textures.add(value);}});geometry.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>{t.dispose();t.image?.close?.();});skeletons.forEach(s=>s.dispose());}
function fabricTexture(){const side=64,data=new Uint8Array(side*side*4);for(let y=0;y<side;y++)for(let x=0;x<side;x++){const i=(y*side+x)*4,v=218+((x*13+y*7)%9)+(x%2===y%2?5:0);data.set([v,v,v,255],i);}const tex=new T.DataTexture(data,side,side);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(10,10);tex.needsUpdate=true;return tex;}
// Keep tailored garments, with collar and cuff geometry joining the imported skin.
export function accessories(original){const src=original.geometry,p=src.attributes.position,selected=[],groups=[];for(const group of src.groups){const start=selected.length;for(let i=group.start;i<group.start+group.count;i+=3){let x=0,y=0,z=0;for(let j=0;j<3;j++){x+=p.getX(i+j)/3;y+=p.getY(i+j)/3;z+=p.getZ(i+j)/3;}const seam=group.materialIndex===1&&(src.attributes.skinIndex.getX(i)===3||(Math.abs(x)>.22&&y>.85&&y<.94));if(group.materialIndex!==1&&y<1.49||seam)selected.push(i,i+1,i+2);}if(selected.length>start)groups.push({start,count:selected.length-start,materialIndex:group.materialIndex});}const geo=new T.BufferGeometry();for(const [name,attribute]of Object.entries(src.attributes)){const data=new attribute.array.constructor(selected.length*attribute.itemSize);selected.forEach((index,i)=>{for(let j=0;j<attribute.itemSize;j++)data[i*attribute.itemSize+j]=attribute.array[index*attribute.itemSize+j];});geo.setAttribute(name,new T.BufferAttribute(data,attribute.itemSize));}geo.groups=groups;geo.computeBoundingSphere();return geo;}
function coatColor(a){return !a.enemy?0x78816a:a.role==='raider'?0x80634f:a.role==='marksman'?0x4f6553:a.role==='sentinel'?0x657078:0x747765;}
export function createDetailedHumans(scene,hero,enemies){const sources=new Map(),actors=new Map(),requests=new Map(),errors={},fabric=fabricTexture();let dead=false,enabled=false,reduced=false;let switches=0;
 function start(gender){if(requests.has(gender)||sources.has(gender)||errors[gender])return;const request=bytes(gender).then(data=>{if(dead)return null;return new GLTFLoader().parseAsync(data,'');}).then(gltf=>{if(!gltf)return;if(dead){releaseTemplate(gltf);return;}try{const parts=validateHumanSource(gltf);sources.set(gender,{gltf,parts});}catch(error){releaseTemplate(gltf);throw error;}}).catch(error=>{if(!dead)errors[gender]=String(error.message||error);}).finally(()=>requests.delete(gender));requests.set(gender,request);}
 function register(a,key){if(actors.has(a))return actors.get(a);const gender=a===hero?'female':([...key].reduce((n,c)=>n+c.charCodeAt(0),0)%3===0?'female':'male');const source=sources.get(gender);if(!source)return null;const group=new T.Group();group.name='Rainward adapted '+gender+' / Quaternius CC0';const owned=new Set(),materials=new Map();
  function material(m){if(materials.has(m))return materials.get(m);const out=m.clone();if(m.name==='skin'){out.roughness=.73;out.normalScale.set(.52,.52);}if(m.name==='hair')out.color.setHex(a.enemy?0x90867a:0xb3a38e);out.name='Rainworn '+m.name;out.side=T.FrontSide;materials.set(m,out);owned.add(out);return out;}
  for(const part of source.parts){if(['jacket','trousers','boots'].includes(part.material.name))continue;const mesh=new T.SkinnedMesh(part.geometry,material(part.material));mesh.name=part.material.name;mesh.bind(a.skin.skeleton,new T.Matrix4());mesh.frustumCulled=false;mesh.boundingSphere=new T.Sphere(new T.Vector3(0,.9,0),2.4);mesh.raycast=function(ray,hits){if(group.visible)T.SkinnedMesh.prototype.raycast.call(this,ray,hits);};mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);}
  const gearGeometry=accessories(a.skin),garments=a.materials.map((m,i)=>{let n;if(i===0){n=new T.MeshPhysicalMaterial({color:coatColor(a),map:fabric,roughness:.94,sheen:.16,sheenColor:0x85927b,sheenRoughness:.9});}else if(i===1){n=new T.MeshStandardMaterial({color:coatColor(a),map:fabric,roughness:.96});n.name='Rain jacket collar and cuff lining';}else n=m.clone();owned.add(n);return n;}),gear=new T.SkinnedMesh(gearGeometry,garments);gear.name='Original tailored jacket, cargo trousers, boots and backpack';gear.bind(a.skin.skeleton,new T.Matrix4());gear.frustumCulled=false;gear.boundingSphere=new T.Sphere(new T.Vector3(0,.9,0),2.4);gear.raycast=function(ray,hits){if(group.visible)T.SkinnedMesh.prototype.raycast.call(this,ray,hits);};gear.castShadow=gear.receiveShadow=true;group.add(gear);a.rig.add(group);group.visible=false;const entry={group,gender,owned,gearGeometry,active:false,mask:a.skin.layers.mask};actors.set(a,entry);return entry;
 }
 function visible(a,entry,value){if(value===entry.active)return;entry.active=value;entry.group.visible=value;a.skin.layers.mask=value?0:entry.mask;a.skin.userData.replacedBody=value;a.visualRevision=(a.visualRevision||0)+1;switches++;}
 function update(state){if(dead)return;if(enabled){start('female');start('male');}const all=[[hero,'hero',state.player],...state.enemies.filter(e=>enemies.get(e.id)?.skin).map(e=>[enemies.get(e.id),e.id,e])];for(const [a,key,p]of all){const entry=actors.get(a)||(enabled?register(a,key):null);if(!entry)continue;const distance=Math.hypot(p.x-state.player.x,p.z-state.player.z),limit=reduced?20:30;const detailed=enabled&&(a===hero||distance<(entry.active?limit+3:limit));visible(a,entry,detailed);if(detailed){a.root.updateMatrixWorld(true);a.skin.skeleton.update();}}}
 return {update,set(value,low=false){enabled=!!value;reduced=!!low;},retry(){for(const key of Object.keys(errors))delete errors[key];if(enabled){start('female');start('male');}},stats:()=>({enabled,reduced,pending:requests.size,loaded:sources.size,active:[...actors.values()].filter(a=>a.active).length,instances:actors.size,switches,errors:{...errors},source:'Quaternius CC0 face, hands and hair / original Rainward outfit',bones:17,extraRenderTargets:0}),dispose(){dead=true;for(const [a,e]of actors){visible(a,e,false);a.rig.remove(e.group);e.owned.forEach(m=>m.dispose());e.gearGeometry.dispose();}actors.clear();for(const {gltf}of sources.values())releaseTemplate(gltf);sources.clear();fabric.dispose();}};
}
