import {GamepadInput} from './input.mjs';
import {createMenuNavigation} from './controller-ui.mjs';
const $=id=>document.getElementById(id),KEY='svgn.rainward.production.review.v1';let plan=null,review={},previous=performance.now();
try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))review=raw;}catch{}
function element(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function reviewSummary(){if(plan)$('filter-result').textContent=document.querySelectorAll('details.task').length+' of '+plan.items.length+' deliverables shown. '+plan.items.filter(t=>review[t.id]===true).length+' local review marks.';}
function store(){reviewSummary();try{localStorage.setItem(KEY,JSON.stringify(review));}catch{$('filter-result').textContent='Local review storage is unavailable. Export your notes before leaving.';}}
const safeLink=path=>typeof path==='string'&&!path.includes('..')&&!path.startsWith('/')&&!/^[a-z]+:/i.test(path);
function render(){if(!plan)return;const query=$('search-filter').value.trim().toLowerCase(),phase=$('phase-filter').value,status=$('status-filter').value,priority=$('priority-filter').value;const found=plan.items.filter(t=>(!phase||t.phase===phase)&&(!status||t.status===status)&&(!priority||t.priority===priority)&&(!query||[t.id,t.title,t.owner,t.acceptance,t.evidence].join(' ').toLowerCase().includes(query)));const host=$('tasks');host.replaceChildren();
 for(const phase of plan.phases){const tasks=found.filter(t=>t.phase===phase.id);if(!tasks.length)continue;const section=element('section',undefined,'gate'),head=element('div',undefined,'gate-head');head.append(element('span',phase.id),element('h2',phase.name));section.append(head,element('p',phase.goal+' Gate: '+phase.gate));
  for(const task of tasks){const detail=element('details',undefined,'task'),summary=element('summary');summary.id='task-'+task.id;const chip=element('span',task.status,'status');chip.dataset.state=task.status;summary.append(element('span',task.id+' / '+task.priority,'task-id'),element('span',task.title,'task-title'),chip);detail.append(summary);const body=element('div',undefined,'detail');body.append(element('p',task.acceptance),element('p','Owner role: '+task.owner+' / Reviewer: '+task.reviewer+' / Effort: '+task.estimate,'meta'),element('p','Dependencies: '+(task.depends.join(', ')||'None'),'meta'));
   if(task.evidence&&safeLink(task.evidence)){const link=element('a','Inspect evidence: '+task.evidence);link.href='./'+task.evidence;body.append(link);}else body.append(element('p','Evidence not recorded yet.','meta'));const label=element('label',undefined,'local-review'),check=element('input');check.type='checkbox';check.id='review-'+task.id;check.checked=review[task.id]===true;check.onchange=()=>{review[task.id]=check.checked;store();};label.append(check,document.createTextNode('Reviewed locally (not acceptance sign-off)'));body.append(label);detail.append(body);section.append(detail);
  }host.append(section);
 }reviewSummary();
}
for(const id of ['search-filter','phase-filter','status-filter','priority-filter'])$(id).addEventListener('input',render);
$('export-review').onclick=()=>{const blob=new Blob([JSON.stringify({release:plan?.release,kind:'local-review-notes',review},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download='Rainward-local-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
const pad=new GamepadInput();function nextGate(direction){const el=$('phase-filter');el.selectedIndex=(el.selectedIndex+direction+el.options.length)%el.options.length;render();el.focus();}
const menu=createMenuNavigation({mode:'title',closePanel:()=>location.assign('./index.html'),menuButton:()=>{$('phase-filter').focus();},viewButton:()=>{$('status-filter').focus();},tab:nextGate});
function tick(now){menu.update(pad.sample(navigator.getGamepads?.(),.18,'classic'),Math.min(.1,(now-previous)/1000));previous=now;requestAnimationFrame(tick);}
// Navigation must work while loading and after a failed plan request.
menu.enter();requestAnimationFrame(tick);
fetch('./production-plan.json').then(response=>{if(!response.ok)throw Error('Checklist data could not load.');return response.json();}).then(data=>{if(data.schema!==1||!Array.isArray(data.items)||!Array.isArray(data.phases))throw Error('Unsupported checklist data.');plan=data;for(const phase of data.phases){const option=element('option',phase.id+' / '+phase.name);option.value=phase.id;$('phase-filter').append(option);}for(const [name,description]of Object.entries(data.statusDefinitions)){const option=element('option',name);option.value=name;$('status-filter').append(option);$('status-definitions').append(element('p',name+': '+description));}$('release').textContent=(data.edition||'PRODUCTION').toUpperCase()+' / v'+data.release;$('plan-purpose').textContent=data.purpose;$('plan-policy').textContent=data.policy;$('total-count').textContent=data.items.length;$('foundation-count').textContent=data.items.filter(t=>['Implemented','Automated','Approved'].includes(t.status)).length;$('automated-count').textContent=data.items.filter(t=>t.status==='Automated').length;$('approved-count').textContent=data.items.filter(t=>t.status==='Approved').length;for(const id of data.nextRelease){const task=data.items.find(t=>t.id===id);if(task)$('next-focus').append(element('span',id+' / '+task.title));}for(const ref of data.references){if(!safeLink(ref.url)&&!/^https:/.test(ref.url))continue;const link=element('a',ref.title);link.href=ref.url;$('references').append(link);}render();menu.enter();}).catch(error=>{$('load-error').hidden=false;$('load-error').textContent=error.message+' The Markdown checklist remains available below.';});
