import {START,BOUNDS,OBSTACLES,ITEMS,SHELTERS,EXIT,PATROLS,HEIGHT,RAD,clamp,dist,inside,solidAt,rayBox,obstruction,coverAt,findPath} from './world.mjs';
export {HEIGHT,EXIT,ITEMS,SHELTERS};
export const forward=yaw=>({x:-Math.sin(yaw),z:-Math.cos(yaw)});
const numeric=(x,min,max)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max;
export const RECIPES={medkit:{cloth:1,canister:1,time:2.1},smoke:{cloth:1,canister:1,time:2.4}};
export function createGame(){return {t:0,status:'playing',player:{...START,hp:100,stamina:100,stance:'stand',yaw:0,speed:0,aim:false,listen:false,noise:0,invulnerable:0,dodge:0,vault:null,mag:6,reserve:12,reload:0,shotCD:0,cloth:0,canister:0,bottles:0,medkit:0,smoke:0,craft:null},enemies:PATROLS.map(e=>({...e,x:e.points[0][0],z:e.points[0][1],hp:e.type==='drifter'?3:2,index:1,state:'patrol',awareness:0,target:null,path:[],repath:0,timer:0,attack:0,seen:false,lastNoise:0})),taken:new Set(),objectives:{cell:false,crank:false},smokes:[],projectiles:[],sounds:[],events:[],serial:0,stats:{shots:0,alerts:0,takedowns:0,hits:0,bottles:0,seconds:0},checkpoint:'start',hint:'Find the signal battery and gate spindle. The wet grass is your cover.',hintTime:5};}
export function emit(s,type,data={}){s.events.push({type,t:s.t,seq:++s.serial,...data});if(s.events.length>180)s.events.shift();}
export function hint(s,text){s.hint=text;s.hintTime=3.5;}
export function noise(s,x,z,radius,type='sound'){s.sounds.push({id:++s.serial,x,z,radius,type,life:.25});emit(s,'sound',{x,z,radius,kind:type});}
export function checkpoint(s){return JSON.stringify({version:1,checkpoint:s.checkpoint,taken:[...s.taken],player:Object.fromEntries(['hp','mag','reserve','cloth','canister','bottles','medkit','smoke'].map(k=>[k,s.player[k]])),objectives:{...s.objectives},stats:{...s.stats}});}
export function restore(raw){try{if(typeof raw!=='string'||raw.length>12000)return null;const d=JSON.parse(raw),c=SHELTERS.find(c=>c.id===d.checkpoint);if(d.version!==1||!c||!Array.isArray(d.taken)||d.taken.length>ITEMS.length||d.taken.some(id=>!ITEMS.some(i=>i.id===id)))return null;const limits={hp:100,mag:6,reserve:36,cloth:12,canister:12,bottles:12,medkit:3,smoke:3};for(const [k,max]of Object.entries(limits))if(!numeric(d.player?.[k],k==='hp'?1:0,max))return null;
 const s=createGame();s.checkpoint=c.id;s.taken=new Set(d.taken);for(const k of Object.keys(limits))s.player[k]=d.player[k];Object.assign(s.player,{x:c.x,z:c.z});s.objectives={cell:s.taken.has('clinic-cell'),crank:s.taken.has('depot-crank')};for(const k of Object.keys(s.stats))if(numeric(d.stats?.[k],0,1e8))s.stats[k]=d.stats[k];s.t=s.stats.seconds;return s;}catch{return null;}}
