import {AUDIO_DEFAULTS} from './audio-design.mjs';import {weapon} from './armory.mjs';
const $=id=>document.getElementById(id);
const rows=[['Left stick','Move / click to sprint'],['Right stick','Look / click to switch shoulders'],['B tap / B hold','Crouch / prone'],['A','Jump / vault low cover'],['Y','Interact / scavenge / silent takedown'],['X / LT + X','Melee / reload'],['LB / RB hold','Dodge / listen'],['LT / RT','Aim / fire or throw'],['D-pad left / right','Rifle / sidearm'],['D-pad up','Cycle medkit / bottle / smoke'],['D-pad down / hold a direction','Satchel / quick crafting'],['Hold A in satchel','Assemble selected recipe; release cancels'],['Medkit + hold RT','Bandage; release or damage cancels'],['View / Menu','Journal / pause']];
const icons={pistol:'M4 10h28v8H18l-3 15H6l4-16H4Z',rifle:'M3 15h32v-4h21v4h10v5H38l-2 13h-6l-1-13H16l-6 6H3Z',medkit:'M9 8h34v28H9Z M22 12v7h-7v7h7v7h8v-7h7v-7h-7v-7Z',bottle:'M20 3h10v11l6 7v17H14V21l6-7Z',smoke:'M15 13h25v23H15Z M23 6h15v6H23Z'};
export function createSurvivalUI(E){const settings=E.settings,oldControls=document.querySelector('.controls').innerHTML,host=document.querySelector('#pause .settings');
 const controls=document.createElement('div');controls.className='audio-controls';controls.innerHTML='<label>CONTROLLER PRESET <select id="controlPreset"><option value="survival">Survival / melee, dodge, hold actions</option><option value="classic">Classic / v0.8.1 controls</option></select></label><p id="audio-status" role="status"></p><button id="audio-test">TEST SOUND / LEFT - RIGHT</button>';
 for(const [id,text]of [['masterVolume','Master volume'],['musicVolume','Original music'],['effectsVolume','Action and threat sounds'],['ambienceVolume','Environmental ambience']])controls.insertAdjacentHTML('beforeend','<label>'+text+' <input type="range" min="0" max="100" step="5" id="'+id+'"><output id="'+id+'-value"></output></label>');
 for(const [id,text]of [['monoAudio','Mono audio'],['audioCaptions','Directional sound captions'],['nightAudio','Compressed night mix'],['cinematicHUD','Fade HUD during quiet moments']])controls.insertAdjacentHTML('beforeend','<label><input type="checkbox" id="'+id+'">'+text+'</label>');host.before(controls);
 function refresh(){const survival=settings.controlPreset==='survival';if(survival)document.querySelector('.controls').innerHTML=rows.map(([a,b])=>'<div><b>'+a+'</b><span>'+b+'</span></div>').join('');else document.querySelector('.controls').innerHTML=oldControls;document.body.classList.toggle('survival-preset',survival);$('controller-status').textContent='A select / B back / left-right adjust / right stick scroll / LB-RB tabs';}
 for(const id of ['controlPreset',...Object.keys(AUDIO_DEFAULTS),'cinematicHUD']){const el=$(id);if(!el)continue;if(el.type==='checkbox')el.checked=!!settings[id];else el.value=settings[id];const out=$(id+'-value');if(out)out.textContent=settings[id]+'%';el.addEventListener('input',()=>{settings[id]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;if(out)out.textContent=settings[id]+'%';E.changed(id);refresh();});}
 $('audio-test').onclick=()=>E.audioTest();refresh();const vitals=document.querySelector('.vitals');vitals.insertAdjacentHTML('afterbegin','<div id="health-disc" role="meter" aria-label="Health" aria-valuemin="0" aria-valuemax="100"><span id="health-number"></span></div>');
 $('inventory-hud').insertAdjacentHTML('afterbegin','<div id="equipped-readout"><svg viewBox="0 0 70 44" aria-hidden="true"><path id="equipped-icon" fill="currentColor" fill-rule="evenodd"></path></svg><span id="equipped-name"></span></div>');$('hud').insertAdjacentHTML('beforeend','<div id="sound-caption" role="status"></div><div id="survival-action" hidden><span></span><progress max="1" value="0"></progress></div>');let last=null,lastHP=100,hotUntil=0;
 function update(s,pad,mode,audio){const p=s.player;if(last!==s){last=s;lastHP=p.hp;hotUntil=s.t+5;}if(p.hp!==lastHP){lastHP=p.hp;hotUntil=s.t+5;}const quiet=settings.cinematicHUD&&mode==='play'&&!p.aim&&!p.listen&&!p.healing&&!p.craft&&p.equipped!=='medkit'&&p.hp>=35&&s.t>hotUntil&&!s.enemies.some(e=>e.hp>0&&e.awareness>.2);document.body.classList.toggle('hud-quiet',!!quiet);document.body.classList.toggle('cinematic-hud',settings.cinematicHUD);document.body.classList.toggle('listening',!!p.listen&&mode==='play');$('health-disc').style.setProperty('--health',Math.max(0,p.hp)*3.6+'deg');$('health-disc').setAttribute('aria-valuenow',Math.round(p.hp));$('health-number').textContent=Math.ceil(p.hp);
 const item=p.equipped||'pistol';$('equipped-icon').setAttribute('d',icons[item]||icons.pistol);$('equipped-name').textContent=item==='pistol'||item==='rifle'?weapon(p).label:item.toUpperCase();const action=p.healing||p.craft;const overlay=$('survival-action');overlay.hidden=!action||!['play','pack'].includes(mode);if(action){const total=p.healing?2.6:action.item==='medkit'?2.1:2.4;overlay.querySelector('span').textContent=p.healing?'HOLD RT / BANDAGING':action.hold?'HOLD A / ASSEMBLING '+action.item.toUpperCase():'ASSEMBLING '+action.item.toUpperCase();overlay.querySelector('progress').value=1-action.left/total;}
 $('sound-caption').textContent=settings.audioCaptions&&['play','pack'].includes(mode)?audio.caption||'':'';$('audio-status').textContent=audio.status+' / '+audio.theme;$('reticle').style.setProperty('--spread',(p.aim?14:9)+(p.speed||0)*2.5+(p.bloom||0)*500+(p.shotCD||0)*8+'px');
 if(mode==='play'&&settings.controlPreset==='survival'){$('device').textContent=pad.connected?'SURVIVAL PAD / X MELEE / LT + X RELOAD':'KEYBOARD + MOUSE';$('reload-state').textContent=p.reload>0?'RELOADING / '+p.reload.toFixed(1)+'s':item==='medkit'?'HOLD RT TO BANDAGE / '+p.medkit+' KIT(S)':item==='smoke'||item==='bottle'?'LT AIM / RT THROW / '+(item==='bottle'?p.bottles:p.smoke)+' LEFT':(p.mag===0?'EMPTY / ':'')+'LT + X RELOAD / X MELEE';$('reload-button').textContent=pad.connected?'RELOAD [LT + X]':'RELOAD [R]';}
 }return {update,refresh};
}
