/* Original non-graphic game actions; range, sightline and finite resources. */
import {HEIGHT,RAD,OBSTACLES,dist,solidAt,heightAt,obstruction,clamp} from './world.mjs';
import {emit,hint,forward,noise,RECIPES} from './state.mjs';
import {vaultCandidate,dodgeOrVault} from './combat.mjs';
import {craft} from './supplies.mjs';import {equip} from './armory.mjs';
export function selectEquipment(s,id){if(s.status!=='playing'||!equip(s.player,id))return false;emit(s,'equip',{item:id});hint(s,id==='medkit'?'Hold RT to bandage. Release to cancel.':id==='smoke'||id==='bottle'?'Hold LT to aim, then RT to throw.':id==='rifle'?'Bolt rifle equipped. LT + X reloads.':'Sidearm equipped. LT + X reloads.');return true;}
export function cancelAction(s,reason='Action interrupted. Supplies recovered.'){const p=s.player;let stopped=false;if(p.craft){const r=RECIPES[p.craft.item];p.cloth=Math.min(12,p.cloth+r.cloth);p.canister=Math.min(12,p.canister+r.canister);p.craft=null;stopped=true;}if(p.healing){p.medkit=Math.min(3,p.medkit+1);p.healing=null;stopped=true;}if(stopped){emit(s,'action-cancel');hint(s,reason);}return stopped;}
export function beginHealing(s){const p=s.player;if(s.status!=='playing'||p.hp>=100||!p.medkit||p.healing||p.craft||p.reload||p.dodge||p.vault||p.melee)return false;p.medkit--;p.healing={left:2.6,total:2.6,hp:p.hp,next:.7};p.vx=p.vz=0;emit(s,'heal-start');return true;}
export function beginCrafting(s,item){if(s.player.healing||s.player.melee||s.player.reload)return false;if(!craft(s,item))return false;s.player.craft.hold=true;s.player.craft.hp=s.player.hp;s.player.craft.next=.6;return true;}
export function melee(s){const p=s.player;if(s.status!=='playing'||p.melee||p.reload||p.craft||p.healing||p.vault||p.dodge||p.stamina<16)return false;p.stamina-=16;p.melee={left:.54,total:.54,hit:false,counter:(p.counterUntil||0)>s.t,weapon:p.meleeDurability>0?p.meleeWeapon:'fists'};p.counterUntil=0;p.vx=p.vz=0;emit(s,'melee');noise(s,p.x,p.z,5,'scuffle');return true;}
export function dodge(s,dx,dz){cancelAction(s);const p=s.player;if(s.status!=='playing'||p.melee||p.reload||p.dodge>0||p.vault||p.stamina<28||solidAt(p.x,p.z,HEIGHT.crouch))return false;const l=Math.hypot(dx,dz),f=forward(p.yaw);p.dodgeDir=l>.1?{x:dx/l,z:dz/l}:f;p.stamina-=28;p.dodge=.38;p.invulnerable=.26;p.stance='crouch';p.vx=p.vz=0;const timed=s.enemies.some(e=>e.hp>0&&dist(e,p)<3.4&&(e.phase==='windup'||e.aimTime>.45));if(timed){p.counterUntil=s.t+1.25;hint(s,'Clean dodge. X counterattack.');}emit(s,'dodge',{timed});return true;}
export function traverse(s,dx,dz){const p=s.player;if(s.status!=='playing'||p.vault||p.dodge||p.craft||p.healing||p.melee||p.stamina<25)return false;const v=vaultCandidate(p,dx,dz);if(v){p.vault=v;p.stance='stand';p.stamina-=25;p.vx=p.vz=0;emit(s,'vault',{id:v.ignore});return true;}
 if(solidAt(p.x,p.z,HEIGHT.stand)){hint(s,'Not enough headroom to jump.');return false;}const l=Math.hypot(dx,dz),f=forward(p.yaw),dir=l>.1?{x:dx/l,z:dz/l}:f,range=l>.1?1.75:.12,end={x:p.x+dir.x*range,z:p.z+dir.z*range};for(let d=0;d<=range+.05;d+=.08)if(solidAt(p.x+dir.x*d,p.z+dir.z*d,HEIGHT.stand,RAD)){hint(s,'The jump landing is blocked.');return false;}
 p.stamina-=25;p.stance='stand';p.vault={start:{x:p.x,z:p.z},end,t:0,duration:.62,ignore:null,jump:true};p.vx=p.vz=0;emit(s,'jump');return true;}
export function updateSurvival(s,input,dt){const p=s.player;
 if(p.melee){const a=p.melee;a.left-=dt;if(!a.hit&&a.left<=a.total-.19){a.hit=true;const f=forward(p.yaw),victims=s.enemies.filter(e=>e.hp>0&&dist(e,p)<1.95&&((e.x-p.x)*f.x+(e.z-p.z)*f.z)/Math.max(.01,dist(e,p))>.30&&!obstruction({x:p.x,y:heightAt(p.x,p.z)+.85,z:p.z},{x:e.x,y:heightAt(e.x,e.z)+.85,z:e.z})).sort((x,y)=>dist(x,p)-dist(y,p));const e=victims[0];if(e){const amount=(a.weapon==='fists'?1:2)+(a.counter?1:0);e.hp=Math.max(0,e.hp-amount);e.stagger=e.type==='brute'?.15:.55;e.aimTime=0;e.target={x:p.x,z:p.z};e.awareness=1;e.state=e.hp>0?'chase':'down';s.stats.melee=(s.stats.melee||0)+1;emit(s,'melee-hit',{id:e.id,x:e.x,z:e.z,weapon:a.weapon,counter:a.counter});noise(s,e.x,e.z,9,'scuffle');if(a.weapon!=='fists'&&--p.meleeDurability<=0){p.meleeWeapon='fists';emit(s,'weapon-break');hint(s,'The scavenged weapon broke. Fists remain available.');}}}if(a.left<=0)p.melee=null;}
 if(p.healing){const a=p.healing;if(s.status!=='playing'||!input.healHeld||p.hp<a.hp){cancelAction(s);return;}a.left-=dt;if(a.total-a.left>=a.next){a.next+=.7;emit(s,'heal-progress');}if(a.left<=0){p.hp=clamp(p.hp+55,0,100);p.healing=null;emit(s,'heal');hint(s,'Bandage secured. Health restored.');}}
 if(p.craft?.hold){const a=p.craft;if(s.status!=='playing'||!input.craftHeld||p.hp<a.hp){cancelAction(s);return;}a.left-=dt;if(RECIPES[a.item].time-a.left>=a.next){a.next+=.6;emit(s,'craft-progress');}if(a.left<=0){const item=a.item;p[item]++;p.craft=null;emit(s,'crafted',{item});hint(s,'Item assembled. Release A before crafting another.');}}
}
export function throwSmoke(s,yaw){const p=s.player;if(s.status!=='playing'||!p.smoke||p.craft||p.healing||p.melee)return false;const f=forward(yaw),target={x:p.x+f.x*8,z:p.z+f.z*8};if(solidAt(target.x,target.z,.1,.1)){hint(s,'Throw landing is blocked.');return false;}const from={x:p.x,y:heightAt(p.x,p.z)+1,z:p.z},to={...target,y:heightAt(target.x,target.z)+.3},hit=obstruction(from,to);if(hit){target.x=p.x+f.x*Math.max(.5,hit.t-.5);target.z=p.z+f.z*Math.max(.5,hit.t-.5);}p.smoke--;s.projectiles.push({x:p.x,z:p.z,to:target,kind:'smoke',life:.65,total:.65});emit(s,'throw',{x:p.x,z:p.z,to:target});return true;}
