from pathlib import Path
import sys
D=Path(__file__).resolve().parents[1]/'dino-atlas'
if "import {RanchGame,calibrateResident,scaleNote}" in (D/'ranger.js').read_text():
 print('Ranch and Coast source is already integrated.');sys.exit(0)
def patch(name,old,new):
 p=D/name;s=p.read_text();assert old in s,(name,old[:120]);p.write_text(s.replace(old,new))
patch('frontier-data.js',"export const BUILD='ranger-operations-20260911.1';", "import {seaWater,WORLD_EDGE} from './ranch-data.js';\nexport const BUILD='ranch-coast-20260911.1';")
patch('frontier-data.js','export const WORLD_RADIUS=310;','export const WORLD_RADIUS=WORLD_EDGE;')
patch('frontier-data.js','export const isWater=(x,z,margin=0)=>WATER.some','export const isWater=(x,z,margin=0)=>seaWater(x,z,margin)||WATER.some')
patch('frontier-data.js','rate:20,range:26','rate:20,range:38')
patch('frontier-data.js','rate:1,range:19','rate:1,range:32')
patch('frontier-data.js',"a.deter=kind==='zapper'?5:3;a.stun=kind==='zapper'?.65:0;a.mood='being herded';", "a.deter=kind==='zapper'?7.5:kind==='horn'?4.5:6;a.stun=kind==='zapper'?1.1:0;a.effect=kind;a.herdSpeed=kind==='horn'?4.4:5.6;a.mood=kind==='zapper'?'stunned':'being herded';")
patch('frontier-data.js',"speed=a.kind==='sauropod'||a.kind==='brachio'?2.8:4.8;", "speed=(a.herdSpeed||5.6)*(a.kind==='sauropod'||a.kind==='brachio'?.68:1);")
patch('frontier-data.js',"const outside=!insidePen(a,pen,2);tx=outside&&a.z>pen.z+pen.hz-3?pen.x:pen.x+Math.sin(a.phase)*7;tz=outside?pen.z+pen.hz-7:pen.z-4+Math.cos(a.phase)*7;speed=1.75;a.mood='returning to feeder';", "const outside=!insidePen(a,pen,2),south=pen.z+pen.hz;tx=pen.x+Math.sin(a.phase)*7;tz=pen.z-4+Math.cos(a.phase)*7;\n  if(outside){if(a.z<south+3&&Math.abs(a.x-pen.x)>5){tx=pen.x+Math.sign(a.x-pen.x)*(pen.hx+4);tz=south+7;}else if(Math.abs(a.x-pen.x)>2.5){tx=pen.x;tz=south+7;}else{tx=pen.x;tz=ps.open?south-7:south+5;}}speed=2.5;a.mood='returning to feeder';")
patch('ranger-physics.js','cuboid(325,.5,325)','cuboid(545,.5,545)')
patch('ranger-physics.js','animal(radius,x,z){','animal(radius,x,z,height=1.8){')
patch('ranger-physics.js','setTranslation(x,1,z));this.world.createCollider(RAPIER.ColliderDesc.cylinder(.9,radius)','setTranslation(x,height/2,z));this.world.createCollider(RAPIER.ColliderDesc.cylinder(height/2,radius)')
patch('ranger-world.js','CylinderGeometry(310,314,3,128)','CylinderGeometry(420,424,3,128)')
patch('ranger-world.js','CircleGeometry(309.7,128)','CircleGeometry(419.7,128)')
patch('frontier-vehicles.js',"import R from './vendor/rapier.mjs';", "import R from './vendor/rapier.mjs';\nimport {HARBORS,surfaceAt} from './ranch-data.js';")
patch('frontier-vehicles.js','this.grounded=p.y<1.5?4:0;','this.grounded=p.y<surfaceAt(p)+1.5?4:0;')
patch('frontier-vehicles.js','dt*14,.88,80)','dt*14,surfaceAt(p)+.88,80)')
patch('frontier-vehicles.js',"nearest(){return [...this.vehicles].filter(v=>distance(v.drive.position,this.position)<6.7||(v.type==='boat'&&distance(this.position,DOCK)<10&&distance(v.drive.position,DOCK)<22)).sort", "nearest(){return [...this.vehicles].filter(v=>Math.abs(v.drive.position.y-this.position.y)<3&&(distance(v.drive.position,this.position)<6.7||(v.type==='boat'&&HARBORS.some(d=>distance(this.position,d.land)<12&&distance(v.drive.position,d)<35)))).sort")
patch('frontier-vehicles.js',"{x:p.x,y:1.05,z:p.z}","{x:p.x,y:p.y??1.05,z:p.z}")
patch('frontier-vehicles.js',"v.type==='helicopter'&&p.y>2.3", "v.type==='helicopter'&&p.y>surfaceAt(p)+2.3")
patch('frontier-vehicles.js',"if(v.type==='boat'){if(distance(p,DOCK)>22){this.onNotice('Return to the marked wetland dock to disembark.');return false;}exit={x:DOCK.x+5,y:1.6,z:DOCK.z};}","if(v.type==='boat'){const dock=HARBORS.find(d=>distance(p,d)<35);if(!dock){this.onNotice('Return to any marked harbor to disembark.');return false;}exit={...dock.land,y:1.6};}")
patch('frontier-vehicles.js',"y:1.1,z:p.z+Math.cos(h+a)*4.4", "y:surfaceAt(p)+1.1,z:p.z+Math.cos(h+a)*4.4")
patch('frontier-vehicles.js',"v.type==='helicopter'&&v.drive.position.y>2.6", "v.type==='helicopter'&&v.drive.position.y>surfaceAt(v.drive.position)+2.6")
patch('frontier-world-expanded.js',"rivals.push({...r,model,curve,lamp,halo,near:false,index:i});", "rivals.push({...r,model,curve,lamp,halo,near:false,index:i,deliveries:0,lastCycle:-1,status:'Beginning scheduled service run'});")
patch('frontier-world-expanded.js','return {...base,','return {...base,rivals,')
patch('frontier-world-expanded.js',"for(const r of rivals){const u=(time*r.speed+r.phase)%1,p=r.curve.getPointAt(u),n=r.curve.getPointAt((u+.006)%1);r.model.position.copy(p);r.model.lookAt(n);r.halo.rotation.z=time*.6+r.index;const near=Math.hypot(player.x-p.x,player.z-p.z)<13;if(near&&!r.near&&rivalNotice<=0){rivalNotice=10;event('rival',{name:r.name});}r.near=near;}", "for(const r of rivals){const period=1/r.speed+10,elapsed=time+r.phase*period,cycle=Math.floor(elapsed/period),local=elapsed%period,unloading=local>period-10,u=unloading?.995:local/(period-10),p=r.curve.getPointAt(u),n=r.curve.getPointAt((u+.006)%1);r.model.position.copy(p);r.model.lookAt(n);r.halo.rotation.z=time*.6+r.index;const jobs=['Armored Valley feeder supplies','Amber Mesa fossil casting supplies','Coastal freight replenishment'];r.status=(unloading?'Unloading: ':'Transporting: ')+jobs[r.index];if(cycle!==r.lastCycle){if(r.lastCycle>=0){r.deliveries++;event('crew-delivery',{index:r.index,name:r.name});}r.lastCycle=cycle;}const near=Math.hypot(player.x-p.x,player.z-p.z)<13;if(near&&!r.near&&rivalNotice<=0){rivalNotice=10;event('rival',{name:r.name});}r.near=near;}")
patch('frontier-economy-core.js',"capacity:32,cargo:{}", "capacity:32,rewardLedger:[],cargo:{}")
patch('frontier-economy-core.js',"const s=emptyEconomy();if(!v||v.version!==1)return s;", "const s=emptyEconomy();if(!v||v.version!==1)return s;\n if(Array.isArray(v.rewardLedger))s.rewardLedger=[...new Set(v.rewardLedger.filter(x=>typeof x==='string'&&x.startsWith('ranch:')))].slice(0,64);")
patch('frontier-economy-ui.js',"open:openMarket,render,advance:", "open:openMarket,render,grant:(amount,tag)=>{if(!Number.isFinite(amount)||amount<=0||tag&&economy.rewardLedger.includes(tag))return false;if(tag)economy.rewardLedger.push(tag);economy.credits=Math.min(9999999,economy.credits+Math.round(amount));save();return true;},crewDelivery:i=>{const id=['redwood','mesa','coast'][i];if(id){economy.rivalPressure[id]=Math.max(.04,(economy.rivalPressure[id]||0)-.12);save();}},advance:")
patch('frontier-economy-ui.js',"if(!['sonic','gravity','celebration'].includes(e.detail?.type))return;", "if(document.getElementById('motion-toggle')?.checked||!['sonic','gravity','celebration'].includes(e.detail?.type))return;")
patch('ranger.js',"const $=id=>document.getElementById(id),esc=escapeHTML;", "import {RanchGame,calibrateResident,scaleNote} from './ranch-game.js';\nimport {EXTRA_ROADS,LAND_RADIUS,RANCH_BUILD} from './ranch-data.js';\nconst $=id=>document.getElementById(id),esc=escapeHTML;")
patch('ranger.js','let started=false,time=0,','let ranch=null;\n let started=false,time=0,')
patch('ranger.js','a.model=makeResident(a);a.collider=physics.animal(a.radius,a.x,a.z);','a.model=makeResident(a);calibrateResident(a);a.collider=physics.animal(a.radius,a.x,a.z,a.collisionHeight);')
patch('ranger.js','function save(){fleet.capture();','function save(){ranch?.save();fleet.capture();')
patch('ranger.js',"state.tracked=b.dataset.track;campaignPinned=false;close();", "state.tracked=b.dataset.track;campaignPinned=false;ranch?.pauseTracking();close();")
patch('ranger.js',"function interact(){if(isPaused()||!candidate)return;", "function interact(){if(isPaused()||!candidate)return;if(candidate.kind==='ranch'){ranch.interact(candidate);return;}")
patch('ranger.js',"else if(key==='horn'){hornAt=time;audio.horn();", "else if(key==='horn'){hornAt=time;ranch?.horn();audio.horn();")
patch('ranger.js',"toast('Horn sounded. Give nearby animals room to move.');", "if(!ranch)toast('Horn sounded. Give nearby animals room to move.');")
patch('ranger.js',"if(!state.rides.includes(fleet.mode)&&fleet.mode!=='foot')state.rides.push(fleet.mode);};", "if(!state.rides.includes(fleet.mode)&&fleet.mode!=='foot')state.rides.push(fleet.mode);ranch?.start();};")
patch('ranger.js',"$('campaign-track').onclick=()=>{campaignPinned=campaign.stage<5;close();};", "$('campaign-track').onclick=()=>{ranch?.pauseTracking();campaignPinned=campaign.stage<5;close();};")
patch('ranger.js',"const labels={power:", "candidate=ranch?.candidate()||candidate;\n  const labels={power:")
patch('ranger.js',"candidate.kind==='animal'?'Observe '","candidate.kind==='ranch'?candidate.label:candidate.kind==='animal'?'Observe '")
patch('ranger.js','function activeTask(){if(campaignPinned', 'function activeTask(){const guided=ranch?.task();if(guided)return guided;if(campaignPinned')
patch('ranger.js','span=full?650:145','span=full?1110:145')
patch('ranger.js','WORLD_RADIUS*k,0,7);ctx.fill();','LAND_RADIUS*k,0,7);ctx.fill();')
patch('ranger.js','[...ROADS,...TRAILS]','[...ROADS,...TRAILS,...EXTRA_ROADS]')
patch('ranger.js',"ctx.strokeStyle='#c4af7e';", "ranch?.drawMap(ctx,to,k,full);ctx.strokeStyle='#c4af7e';")
patch('ranger.js',"if(a){deterAnimal(a,origin,t.id);state.toolHits[t.id]++;input.pulse(t.id==='zapper'?.35:.08,t.id==='zapper'?130:45);}", "if(a&&!ranch){deterAnimal(a,origin,t.id);state.toolHits[t.id]++;}")
patch('ranger.js','const positions=lineGeo.attributes.position;', "if(ranch){const a=hit?animals.find(a=>a.collider.collider(0).handle===hit.collider.handle):null;ranch.shot(t,origin,dir,length,a);}\n  const positions=lineGeo.attributes.position;")
patch('ranger.js','a.collider.setNextKinematicTranslation({x:a.x,y:1,z:a.z});','a.collider.setNextKinematicTranslation({x:a.x,y:a.collisionHeight/2,z:a.z});')
patch('ranger.js','syncModels(dt);park.update(dt,time,','syncModels(dt);ranch?.update(dt,time);park.update(dt,time,')
patch('ranger.js','function ui(){const task=activeTask(),p=fleet.position;', 'function ui(){ranch?.hud();const task=activeTask(),p=fleet.position;')
patch('ranger.js',"ui();syncModels(0);frontier.update(0,0,fleet.position,settings.reduced);", "ranch=new RanchGame({scene,physics,R,fleet,animals,state,storage,audio,input,frontier,started:()=>started,notify:toast,radio,save,close,show:id=>{backTarget=null;show(id);},info,ranchSnapshot:()=>ranch.snapshot()});\n ui();syncModels(0);frontier.update(0,0,fleet.position,settings.reduced);")
patch('ranger.js','ready:true,build:BUILD,','ready:true,build:RANCH_BUILD,')
patch('ranger.js','render:ui,physics,fleet,animals,','render:ui,ranch,physics,fleet,animals,')
patch('ranger.js','<p>${esc(d.role)}</p>','<p>${esc(d.role)}</p><p class="fact">${esc(scaleNote(d.id))}</p>')
patch('ranger.js','${state.observed.length} of 14 species recorded.','${state.observed.length} of ${SPECIES.length} species recorded.')
patch('ranger.js',"state.observed.length+' / 14 species recorded'", "state.observed.length+' / '+SPECIES.length+' species recorded'")
for p in D.glob('*.js'):
 s=p.read_text();t=s.replace('?v=ops1','?v=ranch1').replace('?v=spectacle1','?v=ranch1').replace('?base=ops1','?base=ranch1').replace('?base=spectacle1','?base=ranch1');
 if t!=s:p.write_text(t)
p=D/'index.html';s=p.read_text().replace('?v=ops1','?v=ranch1').replace('?v=spectacle1','?v=ranch1');s=s.replace('Dino Atlas | Spectacle & Trade','Dino Atlas | Ranch & Coast').replace('WILD FRONTIER / SPECTACLE &amp; TRADE','WILD FRONTIER / RANCH &amp; COAST').replace('ATLAS RESERVE / 620 M ACROSS','ATLAS RESERVE / 840 M LAND + COAST').replace('The boat is boarded and exited at the wetland dock.','The boat boards and disembarks at all four marked harbors. The wetland channel now opens to a complete ocean circuit.').replace('Wild<br>Frontier.','Ranch<br>&amp; Coast.');
s=s.replace('<p class="intro-description">','<p class="intro-description">Your first ranger shift starts with a guided task.<br>')
s=s.replace('</div><p class="intro-links">','</div><p class="intro-links">Menu / Dispatch: lessons, roundups, boat races, rooftop archives.<br>')
s=s.replace('Build: Spectacle &amp; Trade, September 11, 2026.','Build: Ranch &amp; Coast, September 11, 2026.')
s=s.replace('<div class="control-copy">','<div class="control-copy"><p><b>Ranch and Coast.</b> Menu / Dispatch introduces every new activity. The horn reaches 42 m and shows orange waves. Water reaches 38 m. The zapper reaches 32 m and can arc to nearby animals. Tool halos show a successful hit. All tools are nonlethal.</p><p><b>New destinations.</b> The wetland channel leads west to the coastal boat circuit. Follow 24 ordered buoys for a full lap. Three large buildings have landable roofs; land before exiting with Y. The maintenance lifts connect rooftops, mezzanine galleries and ground-floor archives. Narrow entrances require exploring on foot.</p>')
p.write_text(s)
print('Ranch and Coast source integration applied.')
