"""Guarded one-time integration into the exact reviewed v0.4 source.
The read-only acceptance workflow never runs this script.
"""
from pathlib import Path
import subprocess
r=Path(__file__).resolve().parents[1];g=r/'vesperfall'
expected={'app.js':'a8964c98359cd086079e535b8c92b3e8075f4803','architecture.js':'2c33ba04fe2c8456d0ad8a20513b65cc508529ea','core.js':'83cb3d242dbc9f6cdef273bab67c9a00a3251d15','index.html':'ac759c727f169445a3b2d99130b25a3ab438783e'}
for n,sha in expected.items():assert subprocess.check_output(['git','hash-object',str(g/n)],text=True).strip()==sha,n
p=g/'core.js';s=p.read_text().replace("VERSION='0.4.0'","VERSION='0.5.0'");a=s.index(' function generate(seed,depth=1){');b=s.index(' function drawState(',a)
s=s[:a]+" const districts=root.CathedralDistricts||(typeof require!=='undefined'?require('./districts.js'):null);\n function generate(seed,depth=1){return architecture.augment(districts.generate(seed,depth,{hash,rng,shuffle,rect,route}));}\n"+s[b:]
s=s.replace("else s.ammo[p.kind]+=3;emit(s,'pickup',{kind:p.kind});", "else if(p.kind==='relic'){s.score+=100;s.health=Math.min(s.maxHealth,s.health+12);}else s.ammo[p.kind]+=3;emit(s,'pickup',{kind:p.kind,label:p.label||'',reward:p.kind==='relic'?100:0});")
p.write_text(s)
p=g/'architecture.js';s=p.read_text().replace("if(b.type==='wall')b.max[1]=7.8;", "if(b.type==='wall'&&b.room===undefined)b.max[1]=Math.max(b.max[1],7.8);");s=s.replace('  return world;',"  return (root.CathedralDistricts||(typeof require!=='undefined'?require('./districts.js'):null)).elevate(world);");p.write_text(s)
p=g/'app.js';s=p.read_text();s=s.replace('this.arsenal=VesperArsenal.install(this);this.hunt=VesperHunt.install(this);','this.arsenal=VesperArsenal.install(this);this.hunt=VesperHunt.install(this);this.cathedral=CathedralUI.install(this);')
s=s.replace("if(e.type==='pickup')this.toast(e.kind==='health'?'Vitality restored.':e.kind+' arrows replenished.');", "if(e.type==='pickup')this.toast(e.kind==='relic'?(e.label||'Reliquary')+' recovered · +100 score · +12 vitality':e.kind==='health'?'Vitality restored.':e.kind+' arrows replenished.');")
a=s.index("   const map=$('map'),g=map.getContext('2d');if(!map.hidden)");b=s.index('\n   if(this.xr)',a);s=s[:a]+'   this.cathedral?.hud();'+s[b:]
s=s.replace("const g=new this.T.Group();this.entities.add(g);const color=", "const g=new this.T.Group();this.entities.add(g);if(p.kind==='relic'){this.art.mesh('box','#877149',g,0,.02,0,.36,.27,.25);this.art.mesh('box','#d7bb78',g,0,.19,0,.41,.06,.29);this.art.mesh('ball','#a9ded0',g,0,.24,0,.105,.145,.105);for(const side of[-1,1])this.art.mesh('box','#e4c886',g,side*.13,.035,0,.025,.32,.27);return g;}const color=")
p.write_text(s)
p=g/'index.html';s=p.read_text().replace('v0.4.0','v0.5.0').replace('<script src="./architecture.js"></script>','<script src="./districts.js"></script><script src="./architecture.js"></script>').replace('<script src="./arsenal.js"></script>','<script src="./cathedral-art.js"></script><script src="./cathedral-ui.js"></script><script src="./arsenal.js"></script>').replace('<link rel="stylesheet" href="./hunt.css">','<link rel="stylesheet" href="./hunt.css"><link rel="stylesheet" href="./cathedral.css">')
s=s.replace('<label>Lighting <select','<label><input type="checkbox" id="cathedral-shadows" checked> Desktop sun shadows (off in VR)</label><label>Lighting <select').replace('<div id="hunt-readout" hidden>','<div id="district-readout"></div><div id="hunt-readout" hidden>')
s=s.replace('Room connections, living wardens and exit beacon','Scaled room footprints, elevated routes, reliquaries and exit beacon').replace('<a class="roadmap" href="./roadmap.html">Roadmap, controls & testing boundaries ↗</a>','<a class="roadmap" href="./roadmap.html">Roadmap, controls & testing boundaries ↗</a><a class="roadmap" href="./assets/cathedral/ASSET-REGISTER.json">Art sources & CC0 asset register ↗</a>').replace('CONNECTED PROCEDURAL RUINS','VARIED ROOMS + UPPER ROUTES')
s=s.replace('Defeat the five stone wardens, find the open beacon, choose a blessing, and descend into a new arrangement.','Cross the skywalk. Search the belfry. Defeat five wardens, find the beacon, and descend into another arrangement.');p.write_text(s)
p=g/'release.json';p.write_text('{"version":"0.5.0","name":"living-cathedral","date":"2026-09-07","status":"candidate","scope":"Varied footprints, inter-room skywalk, 6.4m belfry and CC0 art-production pass. Physical Quest acceptance open."}\n')
p=r/'scripts/check-vesperfall.py';s=p.read_text().replace("'index.html','style.css'", "'districts.js','cathedral-art.js','cathedral-ui.js','cathedral.css','index.html','style.css'")
s=s.replace('for name in files:',"asset_root=app/'assets/cathedral'\nregistry=json.loads((asset_root/'ASSET-REGISTER.json').read_text())\nfor a in registry['assets']:\n assert hashlib.sha256((asset_root/a['file']).read_bytes()).hexdigest()==a['sha256'],a['file']\nfiles += [str(p.relative_to(root)) for p in asset_root.iterdir() if p.is_file()]\nfor name in files:")
s=s.replace("and '/vendor/' not in name:","and '/vendor/' not in name and p.suffix not in ['.jpg','.glb']:");p.write_text(s)
p=g/'tests/hunt-browser.py';s=p.read_text().replace("snap(page)['version']=='0.4.0'", "snap(page)['version']==json.loads((ROOT/'vesperfall/release.json').read_text())['version']").replace('loads Hollow Hunt v0.4.0','loads the current release with preserved Hollow Hunt mechanics');p.write_text(s)
