"""Make the physical catcher forgiving and preserve input/checkpoint behavior."""
from pathlib import Path
root=Path(__file__).resolve().parents[1];g=root/'mario-maker-clone/svgn-paper-route'
p=g/'open-course.js';s=p.read_text()
s=s.replace('[[1800,1830]];bez(c,c[0],[1880,1920],[1920,2060],[2070,2060]);c.push([2400,2060]);bez(c,c.at(-1),[2500,2060],[2530,2000],[2595,1935]);','[[1760,1840]];bez(c,c[0],[1860,2020],[1900,2190],[2100,2190]);c.push([3400,2190]);bez(c,c.at(-1),[3500,2190],[3530,2130],[3595,2065]);')
s=s.replace('[[3080,1830]];bez(d,d[0],[3200,1940],[3240,2088],[3380,2088]);d.push([3600,2088]);','[[4140,1990]];bez(d,d[0],[4260,2100],[4300,2304],[4460,2304]);d.push([4750,2304]);')
s=s.replace('width=113','width=148').replace('x=98;x<111;x++){put(x,58,T.STEEL);put(x,59,T.STEEL);}put(107,57,T.GOAL)','x=130;x<146;x++){put(x,64,T.STEEL);put(x,65,T.STEEL);}put(141,63,T.GOAL)')
s=s.replace('{x:79,y:48}','{x:106,y:52}').replace('ground:58','ground:64').replace('goal:{x:107,y:58}','goal:{x:141,y:64}').replace('mail:[18,45,79]','mail:[18,45,106]')
p.write_text(s)
p=g/'grapple-core.js';s=p.read_text().replace('?.0032:', '?.0052:');p.write_text(s)
p=g/'grapple-game.js';s=p.read_text()
s=s.replace('checkpoint:null,from:null,castTicks:', 'checkpoint:null,checkpoints:{},pendingRelease:false,from:null,castTicks:')
s=s.replace('const keep=routeKeep,checkpoint=state.checkpoint;', 'const keep=routeKeep,checkpoint=state.checkpoints[S.checkpoint]||state.checkpoint;')
s=s.replace('state.lastReleased=null;}', 'state.lastReleased=null;state.checkpoints={};}')
s=s.replace('state.target=null;state.wasZ=false;touchHeld=false;', 'state.target=null;state.wasZ=false;state.pendingRelease=false;touchHeld=false;jumpHeld=false;')
s=s.replace("function release(){if(!enabled()||!player.peg)return;", "function release(){if(!player?.peg)return;if(__sky.active()&&(__delivery.paused||__delivery.state.menu)){state.pendingRelease=true;return;}if(!enabled())return;state.pendingRelease=false;")
if 'if(state.pendingRelease&&enabled())release();' not in s:s=s.replace('  function tickWhip(){\n', '  function tickWhip(){\n   if(state.pendingRelease&&enabled())release();\n')
if 'state.checkpoints[hit.tr.sky.stage]=state.checkpoint;' not in s:s=s.replace('state.checkpoint={id:hit.tr.sky.id,s:hit.s};', 'state.checkpoint={id:hit.tr.sky.id,s:hit.s};state.checkpoints[hit.tr.sky.stage]=state.checkpoint;')
s=s.replace("if(player?.peg&&__sky.active()){K.release(player);state.from='whip';cooldown=10;}", 'if(player?.peg&&__sky.active())state.pendingRelease=true;')
s=s.replace("document.querySelector('#cloud-hud .cloud-loop .cloud-label')?.replaceChildren(document.createTextNode('SECTIONS'));", "const label=document.querySelector('#cloud-hud .cloud-loop .cloud-label');if(label&&label.textContent!=='SECTIONS')label.textContent='SECTIONS';\n    for(const o of document.querySelectorAll('#sky-checkpoint option'))if(o.textContent.includes('loop'))o.textContent=o.textContent.replace('loop','section');")
p.write_text(s)
p=g/'delivery-upgrade.js';s=p.read_text().replace('${r.district} / ${r.stages} LOOPS', "${r.district} / ${r.stages} ${r.kind==='open'?'OPEN SECTIONS':'LOOPS'}");p.write_text(s)
p=root/'tests/grapple_browser.py';s=p.read_text()
s=s.replace("if not snap:\n                    check", "if not snap:\n                    page.wait_for_function('__grapple.graphics.chain.count>0',timeout=10000)\n                    check")
p.write_text(s)
print('Widened the real receiver, strengthened swing pumping and corrected checkpoint/input edge cases.')
