import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';
import {normalizeDiorama,shellOpenings,setOpening,DIORAMA_SHELLS,XR_VIEWS,sessionType,readDioramaPreferences,writeDioramaPreferences,XR_PREFS_KEY,followCentre} from '../diorama-core.mjs';
import {createDioramaView} from '../diorama-view.mjs';
import {createGame,checkpoint} from '../model.mjs';
for(const shell of DIORAMA_SHELLS)test('Diorama '+shell+' always retains a viewing opening',()=>{
 const state=shellOpenings(shell);assert.ok(state.topOpen||state.frontOpen);
 for(const part of ['top','front'])for(const value of [false,true]){const next=setOpening(shell,part,value),s=shellOpenings(next);assert.equal(s[part+'Open'],value);assert.ok(s.topOpen||s.frontOpen);assert.ok(DIORAMA_SHELLS.includes(next));}
});
test('Closing the last open face opens the other face rather than sealing the display',()=>{assert.equal(setOpening('top-open','top',false),'front-open');assert.equal(setOpening('front-open','front',false),'top-open');});
test('Invalid saved preferences cannot create a sealed stage or invalid scale',()=>{for(const data of [null,[],{},'sealed',{shell:'sealed',scale:NaN},{shell:'sealed',scale:Infinity},{scale:-4},{scale:800}]){const p=normalizeDiorama(data);assert.ok(shellOpenings(p.shell).topOpen||shellOpenings(p.shell).frontOpen);assert.ok(p.scale>=.02&&p.scale<=.08);assert.ok(XR_VIEWS.includes(p.view));}});
test('AR specifically requests immersive-ar; VR views never impersonate passthrough',()=>{assert.equal(sessionType('diorama-ar'),'immersive-ar');assert.equal(sessionType('diorama-vr'),'immersive-vr');assert.equal(sessionType('first-person'),'immersive-vr');});
test('View preferences do not write shelter or settings-bank keys and tolerate storage denial',()=>{const disk=new Map(),store={getItem:k=>disk.get(k),setItem:(k,v)=>disk.set(k,v)};assert.equal(writeDioramaPreferences(store,{shell:'front-open',scale:.055,view:'diorama-ar'}),true);assert.deepEqual([...disk.keys()],[XR_PREFS_KEY]);assert.equal(readDioramaPreferences(store).view,'diorama-ar');assert.equal(readDioramaPreferences({getItem(){throw Error('blocked')}}).shell,'both-open');assert.equal(writeDioramaPreferences({setItem(){throw Error('full')}},{}),false);});
test('Table following has a deadband and never mutates player coordinates',()=>{const p={x:2,z:1},raw=JSON.stringify(p);assert.deepEqual(followCentre({x:0,z:0},p,0,40,30,.1),{x:0,z:0});assert.equal(JSON.stringify(p),raw);const far={x:30,z:20};assert.deepEqual(followCentre({x:0,z:0},far,0,40,30,.1,false),{x:0,z:0});const out=followCentre({x:0,z:0},far,0,40,30,.1);assert.ok(out.x>0&&out.x<30&&out.z>0&&out.z<20);});
test('Scaled stereo camera, hand rays and clipping planes share one stage transform',()=>{
 const stage=createDioramaView(),rig=new T.Group(),h={position:{x:.2,y:1.65,z:.1},orientation:new T.Quaternion()},p={x:12,z:-8,waterMode:'dry'};
 for(const scale of [.02,.04,.08])for(const yaw of [0,.5,Math.PI,-Math.PI/2]){
  stage.reset();stage.update(rig,h,p,yaw,0,.016,{view:'diorama-vr',scale});const s=stage.stats();assert.equal(rig.scale.x,1/scale);const anchor=new T.Vector3(s.anchor.x,s.anchor.y,s.anchor.z).applyMatrix4(rig.matrixWorld);assert.ok(anchor.distanceTo(new T.Vector3(s.centre.x,s.floor,s.centre.z))<1e-8);
  const inside=new T.Vector3(s.centre.x,1,s.centre.z);assert.ok(stage.planes.every(plane=>plane.distanceToPoint(inside)>=0));assert.ok(stage.contains(inside));assert.equal(stage.contains({x:999,y:1,z:999}),false);assert.ok(stage.planes.some(plane=>plane.distanceToPoint(new T.Vector3(999,1,999))<0));
 }stage.dispose();
});
test('Head movement around a fixed diorama changes the spectator view, not the saved game',()=>{const s=createGame(),raw=checkpoint(s),rig=new T.Group(),stage=createDioramaView(),h={position:{x:0,y:1.65,z:0},orientation:new T.Quaternion()};stage.update(rig,h,s.player,0,0,.016,{view:'diorama-ar'});const before=rig.matrixWorld.clone();h.position.x+=.4;h.position.y-=.25;stage.update(rig,h,s.player,0,0,.016,{view:'diorama-ar'});assert.deepEqual(rig.matrixWorld.toArray(),before.toArray());assert.equal(checkpoint(s),raw);stage.dispose();});
test('The world is clipped separately from the depth-preserving shell and input UI',()=>{const stage=createDioramaView(),scene=new T.Scene(),rig=new T.Group(),camera=new T.PerspectiveCamera(),state=createGame();scene.add(rig);rig.add(camera);scene.background=new T.Color(0x123456);const fog=scene.fog=new T.Fog(0x123456,1,100);stage.update(rig,{position:{x:0,y:1.65,z:0},orientation:new T.Quaternion()},state.player,0,0,.016,{view:'diorama-ar'});let color=new T.Color(0xffffff),alpha=1;const calls=[],renderer={autoClear:true,clippingPlanes:[],getClearAlpha:()=>alpha,getClearColor:o=>o.copy(color),setClearColor(c,a){color.set(c);alpha=a;},render(s,c){calls.push({s,planeCount:this.clippingPlanes.length,autoClear:this.autoClear,alpha});}};stage.render(renderer,scene,camera,rig);assert.equal(calls.length,2);assert.equal(calls[0].planeCount,6);assert.equal(calls[0].alpha,0);assert.equal(calls[1].planeCount,0);assert.equal(calls[1].autoClear,false);assert.equal(scene.fog,fog);assert.equal(scene.background.getHex(),0x123456);assert.equal(rig.parent,scene);assert.equal(alpha,1);assert.equal(renderer.clippingPlanes.length,0);stage.dispose();});

test('The stage includes existing deep pool space rather than clipping the diver below its base',()=>{const stage=createDioramaView(),rig=new T.Group();stage.update(rig,{position:{x:0,y:1.65,z:0},orientation:new T.Quaternion()},{x:0,z:0,waterMode:'swim'},0,0,.016,{view:'diorama-vr'});assert.ok(stage.contains({x:0,y:-6.5,z:0}));stage.dispose();});
