import {test} from 'node:test';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';
import {DESK_KEY,deskOptions,deskAnchor,deskTransform,createFieldDesk,readDesk,writeDesk} from '../field-desk.mjs';
import {createReadingLog,restoredReading} from '../xr-reading-log.mjs';import * as M from '../model.mjs';import {LEVELS} from '../world.mjs';
const head=(x=0,y=1.65,z=0,yaw=0,pitch=0)=>({position:new T.Vector3(x,y,z),orientation:new T.Quaternion().setFromEuler(new T.Euler(pitch,yaw,0,'YXZ'))});
const store=()=>{const map=new Map();return {getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v),map};};
function fixture(storage=store()){const rig=new T.Group(),panel=new T.Mesh(new T.PlaneGeometry(1.45,1.45),new T.MeshBasicMaterial());rig.add(panel);return {rig,panel,desk:createFieldDesk(panel,rig,storage),storage};}
test('Desk validates corrupt layouts, protects the camera, and stores no room coordinates or save keys',()=>{const s=store(),options=deskOptions({height:NaN,distance:-100,scale:999,yaw:Infinity,pedestal:false,motion:true});assert.equal(options.height,-.12);assert.equal(options.distance,1);assert.equal(options.scale,1.12);assert.equal(options.yaw,0);assert.ok(writeDesk(s,{...options,health:999,anchor:{x:99}}));assert.deepEqual([...s.map.keys()],[DESK_KEY]);assert.deepEqual(readDesk(s),options);assert.equal(s.getItem(DESK_KEY).includes('anchor'),false);s.setItem(DESK_KEY,'oops');assert.deepEqual(readDesk(s),deskOptions());assert.equal(writeDesk({setItem(){throw Error('denied');}},options),false);});
test('Spatial desk stays in its summon frame through look, page and menu transitions; recall is deliberate',()=>{const {desk,panel}=fixture();desk.place('pause',head());desk.update(.016);const initial=panel.matrix.toArray();for(const mode of ['pause','map','pack','pause']){desk.place(mode,head(.4,1.4,.2,1.1,-.4));desk.update(.016);assert.deepEqual(panel.matrix.toArray(),initial);}desk.recall();desk.place('pause',head(.4,1.4,.2,1.1,-.4));assert.notDeepEqual(panel.matrix.toArray(),initial);assert.equal(panel.rotation.x,0);assert.equal(panel.rotation.z,0);desk.dispose();});
test('Every adjusted panel is selected by its actual world transform, including a nonidentity game rig',()=>{const {desk,rig,panel}=fixture();rig.position.set(14,3,-6);rig.rotation.y=.7;desk.place('pause',head());desk.update(.016);for(const id of ['desk-raise','desk-lower','desk-closer','desk-farther','desk-larger','desk-smaller','desk-left','desk-right']){desk.actions().find(a=>a.id===id).run();rig.updateMatrixWorld(true);const point=new T.Vector3(.24,.12,0).applyMatrix4(panel.matrixWorld),normal=new T.Vector3(0,0,1).transformDirection(panel.matrixWorld),ray=new T.Raycaster(point.clone().addScaledVector(normal,1),normal.negate());const hit=ray.intersectObject(panel)[0];assert.ok(hit,id);assert.ok(Math.abs(hit.uv.x-(.24/1.45+.5))<1e-7);assert.ok(Math.abs(hit.uv.y-(.12/1.45+.5))<1e-7);}desk.dispose();});
test('Resume removes menu hit targets immediately, even during optional pedestal lowering',()=>{const {desk,panel}=fixture();desk.place('pause',head());desk.update(.2);desk.actions().find(a=>a.id==='desk-motion').run();desk.place('play',head());assert.equal(panel.visible,false);for(let i=0;i<20;i++)desk.update(.02);assert.equal(desk.stats().visible,false);assert.equal(desk.stats().lift,0);desk.place('pause',head(0,1.1));desk.update(.1);assert.ok(panel.visible);assert.equal(desk.stats().anchor.y,1.1);desk.reset();assert.equal(panel.visible,false);assert.equal(desk.stats().visible,false);desk.dispose();});
test('Missing tracking cannot place a desk and bad inputs never create nonfinite transforms',()=>{const {desk,panel}=fixture();desk.place('pause',null);assert.equal(panel.visible,false);assert.equal(deskAnchor(head(NaN)),null);const t=deskTransform(deskAnchor(head(2,1.1,-3)),{distance:Infinity,height:-99,scale:NaN});assert.ok(t.position.toArray().every(Number.isFinite));assert.ok(t.scale>=.65);desk.dispose();});
test('Acquired clues survive newer status messages without mutating the original record',()=>{const log=createReadingLog(),clue={title:'Inscription',text:'Read SUN / LEAF / WAVE.',persistent:true};log.add(clue);for(let i=0;i<40;i++)log.add({text:'Hint '+i});assert.equal(log.clue().text,clue.text);assert.equal(log.latest().text,'Hint 39');assert.equal(log.size(),12);const copy=log.clue();copy.text='altered';assert.equal(log.clue().text,clue.text);log.clear();assert.equal(log.clue(),null);});
test('Clue recall from an earned checkpoint reveals nothing unacquired and never changes saved state',()=>{for(const level of Object.keys(LEVELS)){const s=M.createGame(level),before=M.checkpoint(s);assert.equal(restoredReading(s),null);assert.equal(M.checkpoint(s),before);if(s.puzzle){s.puzzle.clueRead=true;const acquired=M.checkpoint(s);assert.equal(restoredReading(s).text,LEVELS[level].puzzle.clue.text);assert.equal(M.checkpoint(s),acquired);}}});
