import {test} from 'node:test';import assert from 'node:assert/strict';
import {createGame,checkpoint,restore} from '../model.mjs';import {CURRENT,LEVELS} from '../world.mjs';
import {createCheckpointStore,CHAPTER_SAVE,BACKUP_SAVE,LEGACY_SAVE} from '../checkpoint-store.mjs';import {impulse} from '../audio-synthesis.mjs';import {spatialCue} from '../audio-design.mjs';
function fixture(){const disk=new Map();const read=k=>disk.get(k)||null,write=(k,v)=>{disk.set(k,v);return true;};return {disk,read,write,store:createCheckpointStore(read,write,()=>12345)};}
test('A shelter checkpoint from every chapter survives switching and reconstructing the store',()=>{const f=fixture();for(const id of Object.keys(LEVELS))assert.ok(f.store.save(createGame(id)).ok);const second=createCheckpointStore(f.read,f.write);assert.equal(second.entries().filter(s=>s.occupied).length,6);for(const id of Object.keys(LEVELS))assert.equal(restore(second.get(id),false).level,id);assert.equal(restore(second.latest(),false).level,'whiteout');});
test('Restarting a chapter changes only its slot and preserves the other five byte-for-byte',()=>{const f=fixture();for(const id of Object.keys(LEVELS))f.store.save(createGame(id));const before=JSON.parse(f.read(CHAPTER_SAVE));const s=createGame('meridian');s.player.hp=51;f.store.save(s);const after=JSON.parse(f.read(CHAPTER_SAVE));for(const id of Object.keys(LEVELS))if(id!=='meridian')assert.deepEqual(before.slots[id],after.slots[id]);assert.equal(restore(f.store.get('meridian'),false).player.hp,51);});
test('Legacy migration is non-destructive and never activates the previewed world',()=>{const f=fixture(),raw=checkpoint(createGame('terminus'));f.disk.set(LEGACY_SAVE,raw);createGame('conservatory');const before=CURRENT;const store=createCheckpointStore(f.read,f.write);assert.equal(CURRENT,before);assert.equal(f.read(LEGACY_SAVE),raw);assert.equal(f.read(CHAPTER_SAVE),null);assert.equal(restore(store.latest(),false).level,'terminus');});
test('Read-only save summaries cannot replace a current chapter or mutate its gates',()=>{const f=fixture();f.store.save(createGame('meridian'));createGame('breakwater');const before=CURRENT;for(let i=0;i<5;i++)f.store.entries();assert.equal(CURRENT,before);});
test('Storage failure preserves both bank and legacy mirror and reports failure',()=>{const f=fixture();f.store.save(createGame('district'));const bank=f.read(CHAPTER_SAVE),legacy=f.read(LEGACY_SAVE);const store=createCheckpointStore(f.read,(k,v)=>k===CHAPTER_SAVE?false:f.write(k,v));assert.equal(store.save(createGame('meridian')).ok,false);assert.equal(f.read(CHAPTER_SAVE),bank);assert.equal(f.read(LEGACY_SAVE),legacy);assert.equal(store.get('meridian'),null);});
test('The previous bank recovers after corruption without trusting an invalid replacement',()=>{const f=fixture();f.store.save(createGame('district'));f.store.save(createGame('meridian'));f.disk.set(CHAPTER_SAVE,'broken');const store=createCheckpointStore(f.read,f.write);assert.ok(store.recovered);assert.ok(store.get('district'));assert.ok(store.get('meridian'));assert.ok(f.read(BACKUP_SAVE));});
test('The backup can be unavailable without preventing a valid primary save',()=>{const f=fixture();const store=createCheckpointStore(f.read,(k,v)=>k===BACKUP_SAVE?false:f.write(k,v));const result=store.save(createGame());assert.ok(result.ok);assert.match(result.message,/backup/);assert.ok(store.latest());});
test('A forged slot cannot impersonate a different chapter or pollute prototypes',()=>{const f=fixture();f.disk.set(CHAPTER_SAVE,JSON.stringify({version:1,active:'meridian',slots:{meridian:{checkpoint:checkpoint(createGame('district'))},__proto__:{polluted:true}}}));const store=createCheckpointStore(f.read,f.write);assert.equal(store.latest(),null);assert.equal({}.polluted,undefined);});
test('Saving refreshes other chapter slots written by another tab before replacement',()=>{const f=fixture(),other=createCheckpointStore(f.read,f.write);f.store.save(createGame('district'));other.save(createGame('meridian'));f.store.save(createGame('terminus'));assert.equal(f.store.entries().filter(x=>x.occupied).length,3);});
test('Legacy v1, v2 and v3 saves retain valid resource values on migration',()=>{for(const version of [1,2,3]){const f=fixture(),d=JSON.parse(checkpoint(createGame()));d.version=version;d.player.hp=56;f.disk.set(LEGACY_SAVE,JSON.stringify(d));const store=createCheckpointStore(f.read,f.write);assert.equal(restore(store.latest(),false).player.hp,56);}});
test('Dead or otherwise invalid checkpoints cannot overwrite a good bank',()=>{const f=fixture();f.store.save(createGame());const before=f.read(CHAPTER_SAVE),s=createGame();s.player.hp=0;assert.equal(f.store.save(s).ok,false);assert.equal(f.read(CHAPTER_SAVE),before);});
test('Reverb impulses match 24, 44.1, 48 and 96 kHz context rates',()=>{for(const rate of [24000,44100,48000,96000]){let actual;const context={sampleRate:rate,createBuffer(channels,length,sampleRate){actual={channels,length,sampleRate};const data=Array.from({length:channels},()=>new Float32Array(length));return {getChannelData:i=>data[i]};}};impulse(context,.1);assert.equal(actual.sampleRate,rate);assert.equal(actual.length,rate*.1);}});
test('Mono does not destroy sound-caption direction, including directly behind',()=>{const p={x:0,z:0,yaw:0};assert.equal(spatialCue(p,{x:-8,z:0},false,true).pan,0);assert.equal(spatialCue(p,{x:-8,z:0},false,true).direction,'LEFT');assert.equal(spatialCue(p,{x:0,z:8},false,true).direction,'BEHIND');assert.equal(spatialCue(p,{x:0,z:-8},false,true).direction,'AHEAD');});
