import {test} from 'node:test';import assert from 'node:assert/strict';
import {createGame,interact,interactable,checkpoint,restore,update} from '../model.mjs';
import {FLOODGATE_NOTES} from '../floodgate-content.mjs';
import {taskReady,taskBlockReason} from '../field-tasks.mjs';
import {OBSTACLES,LEVELS,findPath,solidAt,obstruction,heightAt,HEIGHT} from '../world.mjs';
import {move,visible} from '../motion.mjs';
import {FIREBREAK_TASK,FIREBREAK_LEVER,FIREBREAK_ROUTES,firebreakState} from '../freight-firebreak.mjs';
// Explicit model fixtures verify geometry and invariants, not end-to-end play.
function at(s,x,z){Object.assign(s.player,{x,z,y:heightAt(x,z)});}
function trigger(s){at(s,26.1,-10.3);assert.equal(interactable(s).id,FIREBREAK_TASK);return interact(s);}
function walk(s,to){const route=findPath(s.player,to);assert.ok(route.length);for(const target of [...route,to]){for(let i=0;i<100&&Math.hypot(target.x-s.player.x,target.z-s.player.z)>.08;i++){const dx=target.x-s.player.x,dz=target.z-s.player.z,d=Math.hypot(dx,dz);move(s.player,dx/d*Math.min(d,.07),dz/d*Math.min(d,.07),HEIGHT.stand);}assert.ok(Math.hypot(target.x-s.player.x,target.z-s.player.z)<.15,JSON.stringify({target,player:s.player}));}return route.length;}
test('Firebreak occupies the original Freight Hall and retains every stable objective and shelter',()=>{const s=createGame();assert.equal(Object.keys(LEVELS).length,7);assert.deepEqual(LEVELS.district.shelters.map(t=>t.id),['start','clinic']);assert.equal(LEVELS.district.items.find(i=>i.id==='depot-crank').x,22.3);assert.equal(s.enemies.length,5);assert.equal(OBSTACLES.find(o=>o.id==='freight-firebreak-screen').disabled,true);assert.equal(solidAt(28,-15),true);assert.equal(solidAt(20.5,-21.2),false);});
test('One nearby noisy operation changes sightline and exit together without granting supplies',()=>{const s=createGame();at(s,26.1,-10.3);const inventory={...s.player};assert.ok(interact(s));assert.equal(solidAt(28,-15),false);assert.equal(solidAt(20.5,-21.2),true);assert.deepEqual(s.player,inventory);assert.equal(s.sounds.filter(n=>n.type==='mechanism').length,1);assert.ok(s.sounds.find(n=>n.type==='mechanism').radius===18);assert.equal(interact(s),false);assert.equal(s.sounds.length,1);});
test('The partition breaks the actual central shot/sight ray but guards can flank both ends',()=>{const s=createGame(),a={x:20.5,y:1.5,z:-13},b={x:20.5,y:1.3,z:-22};assert.equal(obstruction(a,b),null);trigger(s);assert.equal(obstruction(a,b).o.id,'freight-firebreak-screen');for(const x of [16.5,24.4]){at(s,x,-14);walk(s,{x,z:-22});}assert.ok(findPath(a,b).length>9);});
test('A lowering partition never crushes an occupying player or live enemy; retry stays available',()=>{const s=createGame();at(s,20.5,-21.2);assert.equal(taskReady(s,FIREBREAK_LEVER),false);at(s,26.1,-10.3);Object.assign(s.enemies[0],{x:20.5,z:-21.2});assert.equal(interact(s),false);assert.match(taskBlockReason(s,FIREBREAK_LEVER),/clear the marked partition floor/);assert.equal(s.completedTasks.includes(FIREBREAK_TASK),false);s.enemies[0].x=17;assert.ok(interact(s));});
test('The lever cannot be activated remotely or through the closed yard wall',()=>{const s=createGame();assert.equal(interact(s)&&firebreakState(s).deployed,false);at(s,29.4,-10.3);assert.notEqual(interactable(s)?.id,FIREBREAK_TASK);assert.equal(firebreakState(s).deployed,false);});
test('The yard return is an ordinary traversable loop and gains a shorter first crossing',()=>{const s=createGame();at(s,26.1,-10.3);const closed=findPath(s.player,{x:30.2,z:-15}).length;trigger(s);const open=findPath(s.player,{x:30.2,z:-15}).length;assert.ok(open<closed/2,JSON.stringify({closed,open}));for(const [x,z]of FIREBREAK_ROUTES.yard.points.slice(1))walk(s,{x,z});});
test('Both geometry states preserve all required objects, notes, tasks and exit reachability',()=>{for(const deployed of [false,true]){const s=createGame();if(deployed)trigger(s);const d=LEVELS.district;for(const target of [...d.items,...d.shelters,...d.tasks,...FLOODGATE_NOTES,d.exit]){assert.equal(solidAt(target.x,target.z,target.id==='crawl-cache'?HEIGHT.prone:HEIGHT.stand),false,target.id||'exit');assert.ok(findPath(d.start,target).length||Math.hypot(d.start.x-target.x,d.start.z-target.z)<.5,target.id||'exit');}}});
test('Existing v4 saves and preview restores preserve the gate contract without adding save fields',()=>{const s=createGame(),old=checkpoint(s);trigger(s);s.checkpoint='clinic';const saved=checkpoint(s);assert.deepEqual(Object.keys(JSON.parse(saved)),Object.keys(JSON.parse(old)));assert.equal(JSON.parse(saved).version,4);createGame();assert.ok(solidAt(28,-15));restore(saved,false);assert.ok(solidAt(28,-15));const r=restore(saved);assert.ok(r.completedTasks.includes(FIREBREAK_TASK));assert.equal(solidAt(28,-15),false);assert.equal(solidAt(20.5,-21.2),true);assert.equal(r.player.x,-24);restore(old);assert.equal(solidAt(28,-15),true);assert.equal(solidAt(20.5,-21.2),false);});
test('Mechanism noise produces a normal investigation while visual occlusion remains authoritative',()=>{const s=createGame();trigger(s);const e=s.enemies.find(e=>e.id==='watch-3');Object.assign(e,{x:24,z:-22,state:'patrol',yaw:0,awareness:0,lastNoise:0});update(s,{},1/60);assert.equal(e.state,'investigate');assert.equal(e.target.x,FIREBREAK_LEVER.x);const d=s.enemies.find(e=>e.id==='drifter');assert.equal(visible(s,d),false);});
test('No firebreak progression is added to the other six authored chapters',()=>{for(const id of Object.keys(LEVELS).filter(id=>id!=='district')){const s=createGame(id);assert.equal(firebreakState(s).active,false);assert.ok(!OBSTACLES.some(o=>o.closeOnTask===FIREBREAK_TASK));assert.ok(!LEVELS[id].tasks.some(t=>t.id===FIREBREAK_TASK));}});

import {enemyProfile} from "../enemy-types.mjs";
test("The raised panel is outside watcher firing range from the entrance lever, avoiding a designed-in firing camp under the interlock",()=>{assert.ok(Math.hypot(FIREBREAK_LEVER.x-20.5,FIREBREAK_LEVER.z+21.2)>enemyProfile("watcher").range+.5);});
