import {test} from 'node:test';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';
import {createWorldPortal} from '../portal-view.mjs';import {seesFragment,boxInverse,faceOpacity} from '../world-aperture.mjs';import {normalizeDiorama,sessionType} from '../diorama-core.mjs';import {createDirectXRInput} from '../direct-xr-input.mjs';
const head=()=>({position:new T.Vector3(0,1.65,0),orientation:new T.Quaternion()}),player=()=>({x:12,z:-8,swimDepth:0});
test('Portal centers the actual character in XYZ without scaling the headset rig',()=>{const portal=createWorldPortal(),rig=new T.Group(),p=player(),h=head();for(const scale of [.02,.04,.08])for(const y of [0,6,-3]){portal.update(rig,h,p,.5,y,.016,{view:'diorama-ar',scale});const s=portal.stats(),point=portal.displayPoint({x:p.x,y:y+.9,z:p.z});assert.ok(point.distanceTo(new T.Vector3(s.anchor.x,s.anchor.y+.825,s.anchor.z))<1e-7);assert.equal(rig.scale.x,1);}portal.dispose();});
test('Aperture accepts distant rear scenery but rejects foreground and outside silhouette',()=>{const inv=boxInverse(new T.Vector3(0,0,-2),0),size={width:1.6,depth:1.2,height:1.65},eye=new T.Vector3(0,.825,0);assert.ok(seesFragment(eye,new T.Vector3(0,.825,-200),inv,size));assert.equal(seesFragment(eye,new T.Vector3(0,.825,-.5),inv,size),false);assert.equal(seesFragment(eye,new T.Vector3(10,.825,-3),inv,size),false);assert.equal(faceOpacity(new T.Vector3(0,.825,2),new T.Vector3(0,0,1),new T.Vector3(0,.825,.6)),0);});
test('Throwing during portal render restores source ownership and renderer state',()=>{const portal=createWorldPortal(),scene=new T.Scene(),rig=new T.Group(),mesh=new T.Mesh(new T.BoxGeometry(),new T.MeshBasicMaterial());scene.add(mesh,rig);scene.background=new T.Color(0x123456);const bg=scene.background;portal.update(rig,head(),player(),0,0,.016,{view:'diorama-vr'});let alpha=1;const renderer={autoClear:true,clippingPlanes:[],getClearColor:c=>c.set(0),getClearAlpha:()=>alpha,setClearColor(c,a){alpha=a;},render(){throw Error('fixture');}};assert.throws(()=>portal.render(renderer,scene,new T.PerspectiveCamera(),rig));assert.equal(mesh.parent,scene);assert.equal(rig.parent,scene);assert.equal(scene.background,bg);assert.equal(alpha,1);assert.equal(renderer.autoClear,true);portal.dispose();mesh.geometry.dispose();mesh.material.dispose();});
function fixture(){const input=createDirectXRInput(),make=side=>({id:side,side,buttons:Array.from({length:6},()=>({pressed:false,value:0})),axes:[0,0,0,0]}),L=make('left'),R=make('right'),list=[L,R],step=options=>input.sample(list,.1,options);step();step();return {input,L,R,list,step,press(s,i,on=true){s.buttons[i]={pressed:on,value:on?1:0};}};}
test('Direct Quest A and grip interact; B reloads; X crouches and Y traverses',()=>{for(const [side,index,action]of [['R',4,'interact'],['R',1,'interact'],['R',5,'reload'],['L',5,'traverse']]){const f=fixture();f.press(f[side],index);let v=f.step();if(index===5&&side==='R'){f.press(f.R,5,false);v=f.step();}assert.ok(v.actions.includes(action));}const f=fixture();f.press(f.L,4);f.step();f.press(f.L,4,false);assert.ok(f.step().actions.includes('crouch'));});
test('Y boosts swimming and the left grip previews then commits blink on release',()=>{const f=fixture();f.press(f.L,5);assert.ok(f.step({water:true}).swimBoost);f.press(f.L,5,false);f.step();f.press(f.L,1);assert.ok(f.step().blinkHeld);f.press(f.L,1,false);assert.ok(f.step().actions.includes('blink'));});
test('Remapping never removes reserved R3 pause or menu A/B',()=>{const f=fixture();f.press(f.R,3);assert.deepEqual(f.step().actions,['pause']);f.press(f.R,3,false);f.step({mode:'pause'});f.step({mode:'pause'});f.step({mode:'pause'});f.press(f.R,4);assert.ok(f.step({mode:'pause'}).confirm);});
test('Hand blink commits only on release and source changes cancel held actions',()=>{const f=fixture();f.R.hand=true;f.R.buttons=[];f.R.pinch=true;assert.ok(f.step({handBlink:true}).blinkHeld);f.R.pinch=false;assert.ok(f.step({handBlink:true}).actions.includes('blink'));f.R.id='new';f.R.pinch=true;assert.equal(f.step({handBlink:true}).blinkHeld,undefined);});
test('First-person AR is a distinct validated transparent session',()=>{assert.equal(normalizeDiorama({view:'first-person-ar'}).view,'first-person-ar');assert.equal(sessionType('first-person-ar'),'immersive-ar');});

import {blocksPortalFocus} from '../portal-occlusion.mjs';
test('Foreground cutaway reveals the survivor without erasing ground or the farther world',()=>{const eye=new T.Vector3(0,1.65,0),focus=new T.Vector3(0,1.15,-1.5);assert.equal(blocksPortalFocus(eye,new T.Vector3(0,1.3,-1),focus,1.12,.2),true);assert.equal(blocksPortalFocus(eye,new T.Vector3(0,1,-1),focus,1.12,.2),false);assert.equal(blocksPortalFocus(eye,new T.Vector3(0,1.3,-4),focus,1.12,.2),false);assert.equal(blocksPortalFocus(eye,new T.Vector3(1,1.3,-1),focus,1.12,.2),false);});

test('Diorama size preferences are bounded and the taller shell is the default',()=>{const d=normalizeDiorama({size:9});assert.equal(d.size,1.6);assert.equal(normalizeDiorama({size:.1}).size,.7);assert.equal(normalizeDiorama({}).size,1);});
