import {test} from 'node:test';import assert from 'node:assert/strict';
import * as M from '../model.mjs';import * as W from '../world.mjs';
import {meridianHeight,MERIDIAN_PLANS,accessibleMeridianDrops} from '../meridian-relief.mjs';import {nextGoal} from '../goal-guide.mjs';
test('Meridian has a sunken spine and two distinct raised neighborhoods, not a flat template',()=>{assert.equal(meridianHeight(0,58),0);assert.equal(meridianHeight(-43,20),2.4);assert.equal(meridianHeight(42,-27),6);assert.equal(meridianHeight(0,-29),-2.4);assert.equal(new Set(MERIDIAN_PLANS.map(p=>p.form)).size,6);assert.ok(MERIDIAN_PLANS.every(p=>p.polygon.length>=6));});
test('Physical terrain is continuous rather than floating inaccessible floors',()=>{let slope=0;for(let z=-86;z<64;z+=.5)for(let x=-57;x<57;x+=.5)slope=Math.max(slope,Math.abs(meridianHeight(x+.1,z)-meridianHeight(x,z))/.1,Math.abs(meridianHeight(x,z+.1)-meridianHeight(x,z))/.1);assert.ok(slope<.8);});
test('Original objective, task, valve and refuge positions remain valid in the new footprints',()=>{M.createGame('meridian');const d=W.CURRENT;for(const p of [...d.items,...d.shelters,...d.tasks,...d.puzzle.wheels,d.puzzle.clue]){if(p.id==='underpass-cache')assert.equal(W.solidAt(p.x,p.z,W.HEIGHT.prone),false);else assert.equal(W.solidAt(p.x,p.z),false,p.id||p.label);}assert.equal(d.items.length,9);assert.equal(d.tasks.length,6);assert.equal(d.shelters.length,4);assert.equal(Object.keys(W.LEVELS).length,7);});
function walk(s,x,z){const path=W.findPath(s.player,{x,z});assert.ok(path.length||W.dist(s.player,{x,z})<1,'No route '+x+','+z);for(const q of [...path,{x,z}]){let n=0;while(W.dist(s.player,q)>.15){const dx=q.x-s.player.x,dz=q.z-s.player.z,d=Math.hypot(dx,dz);M.update(s,{x:dx/d,z:dz/d,freeStride:true,sprint:true,runSpeed:9},1/60);assert.ok(++n<1500,'Physically stuck '+JSON.stringify(q));}}}
test('Isolated actual model movement connects the two buildings and sunken mechanism before gate opening',()=>{const s=M.createGame('meridian');s.enemies=[];for(const p of [{x:-42,z:35},{x:-43,z:20},{x:0,z:-29},{x:42,z:-27},{x:45,z:-12}])walk(s,p.x,p.z);assert.ok(s.player.y>5.9);assert.equal(s.status,'playing');assert.equal(s.puzzle.solved,false);assert.equal(W.findPath(s.player,{x:0,z:-80}).length,0);});
test('Goal guidance follows prerequisites without changing checkpoint state',()=>{const s=M.createGame('meridian'),before=M.checkpoint(s);assert.equal(nextGoal(s).id,'meridian-filter');assert.equal(M.checkpoint(s),before);s.objectives.cell=true;assert.equal(nextGoal(s).id,'clinic-power');s.completedTasks.push('clinic-power');assert.equal(nextGoal(s).label,'Read the clinic water diagram');s.puzzle.clueRead=true;assert.equal(nextGoal(s).id,'clinic-valve');});
test('An older drop inside a replaced wall retains its ID and quantities at adjacent clear ground',()=>{const s=M.createGame('meridian'),d=W.CURRENT,drop={id:'meridian-raider-a',x:29,z:20,items:{ammo:3,cloth:1}},original=JSON.stringify(drop),out=accessibleMeridianDrops(d,[drop],s.puzzle)[0];assert.ok(Math.hypot(out.x-drop.x,out.z-drop.z)>0);assert.deepEqual(out.items,drop.items);assert.equal(out.id,drop.id);assert.equal(JSON.stringify(drop),original);assert.deepEqual(accessibleMeridianDrops(d,[out],s.puzzle),[out]);});
