import {test} from 'node:test';import assert from 'node:assert/strict';
import {createXRInput,pinchDown,handStick,deadAxis} from '../xr-input.mjs';
function fixture(){const i=createXRInput(),L={id:'left',side:'left',axes:[0,0,0,0],buttons:Array.from({length:6},()=>({pressed:false,value:0}))},R={id:'right',side:'right',axes:[0,0,0,0],buttons:Array.from({length:6},()=>({pressed:false,value:0}))};const list=[L,R];const step=(mode='play')=>i.sample(list,.05,{mode});step();step();return {i,L,R,list,step,press(s,n){s.buttons[n]={pressed:true,value:1};},release(s,n){s.buttons[n]={pressed:false,value:0};}};}
for(const [side,button,expected]of [['R',1,'interact'],['L',4,'reload'],['R',4,'traverse'],['R',3,'melee']])test('Quest '+side+' button '+button+' maps to '+expected,()=>{const f=fixture();f.press(f[side],button);assert.deepEqual(f.step().actions,[expected]);assert.equal(f.step().actions.length,0);});
test('Triggers and left grip retain fire aim and listen rather than Xbox indices',()=>{const f=fixture();f.press(f.R,0);f.press(f.L,0);f.press(f.L,1);const p=f.step();assert.ok(p.fire&&p.aim&&p.listen);assert.deepEqual(p.actions,[]);});
test('Left grip plus A dodges, without also traversing',()=>{const f=fixture();f.press(f.L,1);f.press(f.R,4);assert.deepEqual(f.step().actions,['evade']);});
test('Right B tap crouches, hold prones exactly once and release does not crouch',()=>{const f=fixture();f.press(f.R,5);assert.equal(f.step().actions.length,0);f.release(f.R,5);assert.deepEqual(f.step().actions,['crouch']);f.press(f.R,5);let a=[];for(let j=0;j<18;j++)a.push(...f.step().actions);f.release(f.R,5);a.push(...f.step().actions);assert.deepEqual(a,['prone']);});
test('Left Y tap opens pack; hold pauses without opening pack on release',()=>{const f=fixture();f.press(f.L,5);f.step();f.release(f.L,5);assert.deepEqual(f.step().actions,['pack']);f.press(f.L,5);let a=[];for(let j=0;j<18;j++)a.push(...f.step().actions);f.release(f.L,5);a.push(...f.step().actions);assert.deepEqual(a,['pause']);});
test('Quest thumbstick axes are 2/3; touchpad placeholders never move the hero',()=>{const f=fixture();f.L.axes=[1,-1,0,0];assert.deepEqual(f.step().move,[0,0]);f.L.axes=[0,0,.7,-1];assert.ok(f.step().move[0]>.5);assert.equal(f.step().move[1],-1);});
test('Snap turns and weapon/tool flicks require release and never repeat while held',()=>{const f=fixture();f.R.axes[2]=1;assert.equal(f.step().turn,-Math.PI/6);assert.equal(f.step().turn,0);f.R.axes[2]=0;f.step();f.R.axes[3]=-1;assert.deepEqual(f.step().actions,['swapGun']);assert.deepEqual(f.step().actions,[]);f.R.axes[3]=0;f.step();f.R.axes[3]=1;assert.deepEqual(f.step().actions,['selectTool']);});
test('Mode/source changes suppress held fire, movement and menu confirmation until neutral',()=>{const f=fixture();f.press(f.R,0);assert.ok(f.step().fire);assert.equal(f.step('pause').confirmHeld,false);f.release(f.R,0);f.step('pause');f.step('pause');f.press(f.R,4);assert.ok(f.step('pause').confirm);f.R.id='replacement';assert.equal(f.step('pause').confirm,false);f.release(f.R,4);f.step('pause');f.step('pause');assert.equal(f.step().fire,false);});
test('Hands default to use, explicit fire mode enables hold firing and not an interact',()=>{const i=createXRInput(),r={id:'hand',side:'right',hand:true,pinch:false},a=[r];i.sample(a,.016);i.sample(a,.016);r.pinch=true;assert.deepEqual(i.sample(a,.016).actions,['interact']);assert.equal(i.sample(a,.016).fire,false);r.pinch=false;i.sample(a,.016);r.pinch=true;const s=i.sample(a,.016,{handFire:true});assert.ok(s.fire&&s.aim);assert.deepEqual(s.actions,[]);});
test('Pinch hysteresis rejects missing/non-finite data and avoids release jitter',()=>{assert.equal(pinchDown(.02),true);assert.equal(pinchDown(.03),false);assert.equal(pinchDown(.03,true),true);assert.equal(pinchDown(.04,true),false);for(const x of [NaN,Infinity,undefined,-1])assert.equal(pinchDown(x,true),false);});
test('Pinch joystick is bounded and uses horizontal displacement; raising the hand alone never moves',()=>{const o={x:0,y:1,z:0};assert.deepEqual(handStick(o,{x:0,y:2,z:0},0),[0,0]);assert.deepEqual(handStick(o,{x:1,y:1,z:-1},0),[1,-1]);assert.equal(deadAxis(Infinity),0);assert.equal(deadAxis(.1),0);assert.equal(deadAxis(20),1);});
