import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import * as T from '../vendor/three.module.js';import {actor,pose} from '../actors.mjs';import {applyRainFilm,rainClimate,createRainwornMaterials} from '../rainworn-materials.mjs';
const root=new URL('../assets/humans/',import.meta.url),manifest=JSON.parse(fs.readFileSync(new URL('manifest.json',root)));
function read(file){const bytes=fs.readFileSync(new URL(file,root)),length=bytes.readUInt32LE(12),g=JSON.parse(bytes.subarray(20,20+length)),bin=bytes.subarray(28+length),sizes={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};function attribute(index){const a=g.accessors[index],view=g.bufferViews[a.bufferView],type=a.componentType===5126?Float32Array:Uint16Array,n=sizes[a.type],offset=(view.byteOffset||0)+(a.byteOffset||0);const source=bin.subarray(offset,offset+a.count*n*type.BYTES_PER_ELEMENT);return new T.BufferAttribute(new type(source.buffer.slice(source.byteOffset,source.byteOffset+source.length)),n);}return {g,bytes,attribute};}
function rig(file){const {g,attribute}=read(file),scene=new T.Scene(),a=actor(scene,null,0),surface=new T.Group();for(const p of g.meshes[0].primitives){const geometry=new T.BufferGeometry();for(const [source,name]of Object.entries({POSITION:'position',NORMAL:'normal',TEXCOORD_0:'uv',JOINTS_0:'skinIndex',WEIGHTS_0:'skinWeight'}))geometry.setAttribute(name,attribute(p.attributes[source]));geometry.setIndex(attribute(p.indices));const mesh=new T.SkinnedMesh(geometry,new T.MeshBasicMaterial());mesh.bind(a.skin.skeleton,new T.Matrix4());surface.add(mesh);}a.rig.add(surface);return {a,scene,surface};}
test('Two actual CC0 human assets have locked hashes and a bounded transfer budget',()=>{assert.equal(manifest.license,'CC0-1.0');assert.equal(manifest.author,'Quaternius');assert.equal(manifest.models.length,2);let sum=0;for(const m of manifest.models){const data=fs.readFileSync(new URL(m.path,root));assert.equal(crypto.createHash('sha256').update(data).digest('hex'),m.sha256);assert.equal(data.length,m.bytes);assert.ok(m.triangles>12000&&m.triangles<24000);sum+=m.bytes;}assert.ok(sum<4500000);assert.match(fs.readFileSync(new URL('LICENSE-Quaternius.txt',root),'utf8'),/CC0 1.0 Universal/);});
test('Self-contained glTF retains actual source face, eye and normal textures, with no remote image URI',()=>{for(const m of manifest.models){const {g}=read(m.path);assert.ok(g.images.length>=5);assert.ok(g.images.every(i=>i.bufferView!==undefined&&!i.uri));assert.ok(g.buffers.every(b=>!b.uri));assert.ok(g.extensionsRequired.includes('EXT_texture_webp'));assert.ok(g.materials.some(m=>m.name==='skin'&&m.normalTexture&&m.pbrMetallicRoughness.baseColorTexture));assert.ok(g.materials.some(m=>m.name==='eyes'));assert.ok(g.materials.some(m=>m.name==='jacket'));assert.ok(g.materials.some(m=>m.name==='trousers'));}});
test('Adapted skin weights bind only to the original seventeen gameplay bones',()=>{for(const m of manifest.models){const {g,attribute}=read(m.path);assert.equal(g.skins[0].joints.length,17);for(const p of g.meshes[0].primitives){const joints=attribute(p.attributes.JOINTS_0),weights=attribute(p.attributes.WEIGHTS_0);for(let i=0;i<weights.count;i++){let sum=0;for(let j=0;j<4;j++){assert.ok(joints.array[i*4+j]<17);sum+=weights.array[i*4+j];}assert.ok(Math.abs(sum-1)<1e-5);}}}});
test('Both imported human silhouettes stay within the existing stand, crouch and crawl envelopes',()=>{for(const m of manifest.models){const {a,scene,surface}=rig(m.path);for(const [stance,height]of [['stand',1.84],['crouch',1.09],['prone',.46]]){pose(a,{x:0,z:0,yaw:0,hp:100,stance,speed:0},1);scene.updateMatrixWorld(true);const box=new T.Box3().setFromObject(surface,true);assert.ok(box.min.y>-.04,m.path+stance);assert.ok(box.max.y<height,m.path+stance);assert.ok(box.max.x-box.min.x<.72);}}});
test('Aiming, reloading, striking and healing move the imported mesh using the real wrist skeleton',()=>{const {a,scene,surface}=rig('survivor-female.glb');for(const extra of [{aim:true},{reload:1},{melee:{left:.3,total:.54,weapon:'club'}},{healing:{left:1}},{craft:{left:1}},{vault:{t:.25,duration:.6}},{hp:0}]){pose(a,{x:0,z:0,yaw:.2,hp:100,stance:'stand',speed:2,...extra},2);scene.updateMatrixWorld(true);for(const mesh of surface.children){assert.equal(mesh.skeleton,a.skin.skeleton);const sample=mesh.getVertexPosition(0,new T.Vector3());assert.ok(sample.toArray().every(Number.isFinite));}}});
test('Different actors share no mutable skeleton and adapting a surface does not alter gameplay state',()=>{const first=rig('survivor-female.glb'),second=rig('survivor-male.glb');const p={x:0,z:0,yaw:0,hp:100,stance:'stand',speed:2,aim:true},before=JSON.stringify(p);pose(first.a,p,1);pose(second.a,{...p,aim:false},1);assert.equal(JSON.stringify(p),before);assert.notEqual(first.a.skin.skeleton,second.a.skin.skeleton);assert.notEqual(first.a.bones[8].rotation.x,second.a.bones[8].rotation.x);});
test('Rain film composes with existing world texture work instead of replacing it',()=>{const m=new T.MeshPhysicalMaterial();m.userData.worldSurface=true;let called=0;m.onBeforeCompile=s=>{called++;s.fragmentShader='// existing surface\n'+s.fragmentShader;};const u={value:.8};assert.ok(applyRainFilm(m,u));assert.equal(applyRainFilm(m,u),false);const shader={uniforms:{},vertexShader:'unchanged geometry',fragmentShader:'#include <lights_physical_fragment>'};m.onBeforeCompile(shader);assert.equal(called,1);assert.equal(shader.vertexShader,'unchanged geometry');assert.equal(shader.uniforms.rwRainFilm,u);assert.match(shader.fragmentShader,/existing surface/);assert.match(shader.fragmentShader,/material\.roughness/);assert.match(shader.fragmentShader,/material\.clearcoat/);});
test('Reduced Graphics and the rain toggle restore the dry mix with no new render target',()=>{const m=new T.MeshPhysicalMaterial();m.userData.worldSurface=true;const effect=createRainwornMaterials({mats:new Map([['surface',m]])},{id:'district'});assert.equal(effect.stats().extraRenderTargets,0);effect.set(true,true);assert.equal(effect.stats().amount,0);assert.equal(effect.stats().active,false);effect.set(true,false);assert.equal(effect.stats().amount,rainClimate('district'));effect.set(false);assert.equal(effect.stats().amount,0);});
test('Rain effect leaves particle, foliage, character and unlit materials alone',()=>{for(const m of [new T.MeshBasicMaterial(),new T.MeshLambertMaterial(),new T.MeshStandardMaterial()])assert.equal(applyRainFilm(m,{value:1}),false);assert.ok(rainClimate('breakwater')>rainClimate('conservatory'));});
test('Model runtime has a recoverable failure path, scene lifetime guard and no gameplay mutation',()=>{const s=fs.readFileSync(new URL('../rainworn-humans.mjs',import.meta.url),'utf8');assert.match(s,/AbortController/);assert.match(s,/if\(dead\)/);assert.match(s,/releaseTemplate\(gltf\)/);assert.match(s,/retry\(\)/);assert.doesNotMatch(s,/state\.player\.(?:hp|mag|reserve|x|z)\s*=/);assert.doesNotMatch(s,/https?:\/\//);});
