import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as W from '../world.mjs';
import * as M from '../model.mjs';
import * as F from '../field-tasks.mjs';
import {enemyProfile} from '../enemy-types.mjs';
import {updateShrieker} from '../monsters.mjs';
import {visible} from '../motion.mjs';
const newChapters=['meridian','breakwater','whiteout'];
function at(s,t){s.player.x=t.x;s.player.z=t.z;s.player.y=W.heightAt(t.x,t.z);}
function collectObjectives(s,d){for(const t of d.items.filter(t=>t.objective)){at(s,t);assert.equal(M.interact(s),true,t.id);assert.equal(s.objectives[t.objective],true,t.id);}}
function solve(s,d){if(!d.puzzle)return;for(const [i,w]of d.puzzle.wheels.entries()){at(s,w);let count=0;while(s.puzzle.wheels[i]!==d.puzzle.targets[i]&&count++<4)assert.equal(M.interact(s),true,w.id);}assert.equal(s.puzzle.solved,true);}
test('Six authored chapters preserve the original three and add three larger maps',()=>{assert.deepEqual(Object.keys(W.LEVELS),['district','conservatory','terminus','meridian','breakwater','whiteout']);const area=d=>(d.bounds.x1-d.bounds.x0)*(d.bounds.z1-d.bounds.z0);for(const id of newChapters)assert.ok(area(W.LEVELS[id])>3*area(W.LEVELS.district));assert.equal(W.VERSION,'0.12.0');});
test('Twenty-nine additional enemies and twenty-four authored tasks have stable unique IDs',()=>{assert.equal(newChapters.reduce((n,id)=>n+W.LEVELS[id].patrols.length,0),29);assert.equal(Object.values(W.LEVELS).reduce((n,d)=>n+d.tasks.length,0),24);for(const d of Object.values(W.LEVELS)){assert.equal(new Set(d.tasks.map(t=>t.id)).size,d.tasks.length);assert.equal(new Set(d.obstacles.map(t=>t.id)).size,d.obstacles.length);}});
for(const id of newChapters){
 test(id+': every task, clue, objective and shelter has a clear standing position',()=>{M.createGame(id);const d=W.CURRENT;for(const t of [...d.tasks,...d.shelters,...d.items.filter(t=>t.objective),d.puzzle.clue,...d.puzzle.wheels])assert.equal(W.solidAt(t.x,t.z,1.72,.33),false,t.id||t.label);});
 test(id+': gate actually separates the exit until puzzle completion',()=>{const s=M.createGame(id),d=W.CURRENT;assert.equal(W.findPath(d.start,d.exit).length,0);s.puzzle.solved=true;W.syncGates(s.puzzle);assert.ok(W.findPath(d.start,d.exit).length>20);});
 test(id+': objective and control routes are reachable before opening the gate',()=>{M.createGame(id);const d=W.CURRENT;for(const t of [...d.items.filter(t=>t.objective),d.puzzle.clue,...d.puzzle.wheels])assert.ok(W.findPath(d.start,t).length>0,t.id||t.label);});
 test(id+': optional and required task locations are reachable after opening the gate',()=>{const s=M.createGame(id),d=W.CURRENT;s.puzzle.solved=true;W.syncGates(s.puzzle);for(const t of [...d.tasks,...d.shelters])assert.ok(W.findPath(d.start,t).length>0||W.dist(d.start,t)<1,t.id);});
 test(id+': extraction cannot skip required work, and a complete unit-model route can finish',()=>{const s=M.createGame(id),d=W.CURRENT;collectObjectives(s,d);solve(s,d);at(s,d.exit);assert.equal(M.interact(s),false);assert.equal(s.status,'playing');for(const t of d.tasks.filter(t=>t.required)){at(s,t);assert.equal(M.interact(s),true,t.id);}at(s,d.exit);assert.equal(M.interact(s),true);assert.equal(s.status,'won');});
 test(id+': tasks reject distance, missing dependencies and duplicate rewards',()=>{const s=M.createGame(id),d=W.CURRENT,t=d.tasks.find(t=>t.requires?.includes('cell'));at(s,t);assert.equal(F.completeTask(s,t.id),false);collectObjectives(s,d);at(s,d.start);assert.equal(F.completeTask(s,t.id),false);at(s,t);assert.equal(F.completeTask(s,t.id),true);const before=JSON.stringify(s.player);assert.equal(F.completeTask(s,t.id),false);assert.equal(JSON.stringify(s.player),before);});
 test(id+': every task can be completed and restored without duplicate inventory rewards',()=>{const s=M.createGame(id),d=W.CURRENT;collectObjectives(s,d);solve(s,d);for(const t of d.tasks){at(s,t);assert.equal(M.interact(s),true,t.id);}s.trackedTask=null;const raw=M.checkpoint(s),again=M.restore(raw);assert.ok(again);assert.equal(again.completedTasks.length,6);assert.deepEqual(JSON.parse(M.checkpoint(again)).player,JSON.parse(raw).player);assert.equal(F.requiredTasksDone(again),true);});
 test(id+': checkpoint validation rejects a forged late task and duplicate task IDs',()=>{const s=M.createGame(id),raw=JSON.parse(M.checkpoint(s));raw.completedTasks=[W.CURRENT.tasks.at(-1).id];assert.equal(M.restore(JSON.stringify(raw)),null);raw.completedTasks=[W.CURRENT.tasks[1].id,W.CURRENT.tasks[1].id];assert.equal(M.restore(JSON.stringify(raw)),null);});
 test(id+': an inactive checkpoint preview leaves the active world untouched',()=>{const s=M.createGame(id),raw=M.checkpoint(s);M.createGame('district');const bounds={...W.BOUNDS};assert.ok(M.restore(raw,false));assert.equal(W.CURRENT.id,'district');assert.deepEqual(W.BOUNDS,bounds);});
}
test('Legacy v1/v2 checkpoint compatibility survives the new optional journal',()=>{for(const version of[1,2]){const s=M.createGame('district'),raw=JSON.parse(M.checkpoint(s));raw.version=version;delete raw.completedTasks;delete raw.trackedTask;if(version===1)delete raw.level;assert.ok(M.restore(JSON.stringify(raw)));}});
test('Optional legacy tasks do not become required extraction objectives',()=>{for(const id of['district','conservatory','terminus']){const s=M.createGame(id);assert.equal(F.requiredTasksDone(s),true);assert.equal(W.CURRENT.tasks.length,2);}});
test('Task graph references only real objectives and earlier tasks, with no cycles',()=>{for(const d of Object.values(W.LEVELS)){const seen=new Set();for(const t of d.tasks){for(const r of t.requires||[])assert.ok(['cell','crank','puzzle'].includes(r)||r.startsWith('task:')&&seen.has(r.slice(5)),d.id+'/'+r);seen.add(t.id);}}});
test('Marksman, raider and sentinel rules are mechanically different',()=>{assert.ok(enemyProfile('marksman').range>enemyProfile('watcher').range);assert.ok(enemyProfile('marksman').windup>enemyProfile('watcher').windup);assert.equal(enemyProfile('raider').attackKind,'melee');assert.ok(enemyProfile('raider').range<2);assert.ok(enemyProfile('raider').chaseSpeed>enemyProfile('watcher').chaseSpeed);assert.ok(enemyProfile('sentinel').hp>enemyProfile('watcher').hp);});
test('Smoke can break a new marksman sightline during its longer approach',()=>{const s=M.createGame('district');at(s,{x:0,z:27});const e={x:0,z:18,yaw:Math.PI,type:'marksman'};assert.equal(visible(s,e),true);s.smokes.push({x:0,z:24,radius:3,life:5});assert.equal(visible(s,e),false);});
test('A shrieker has a visible call windup and reports the last observed point, not a hidden player',()=>{const s=M.createGame('district');at(s,{x:0,z:27});const e={id:'test-call',type:'shrieker',x:0,z:19,hp:4,points:[[0,19],[2,19]],index:0,repath:0,path:[],state:'patrol'},ally={...s.enemies[0],x:4,z:23,state:'patrol',hp:2};s.enemies=[e,ally];updateShrieker(s,e,.016);assert.equal(e.phase,'call');assert.equal(ally.state,'patrol');assert.ok(s.events.some(e=>e.type==='callout'));at(s,{x:20,z:28});for(let i=0;i<19;i++)updateShrieker(s,e,.1);assert.equal(ally.state,'investigate');assert.deepEqual(ally.target,{x:0,z:27});assert.equal(s.player.hp,100);assert.ok(s.events.some(e=>e.type==='shriek'));});
test('A dying shrieker cannot finish a call or damage the player',()=>{const s=M.createGame('district'),e={id:'call',type:'shrieker',x:0,z:27,hp:0,phase:'call',phaseTime:.01};const count=s.events.length;updateShrieker(s,e,.1);assert.equal(s.events.length,count);assert.equal(s.player.hp,100);assert.equal(e.state,'down');});
test('Coastal rise is a continuous ground surface, not teleportation or a fake staircase',()=>{M.createGame('breakwater');assert.equal(W.heightAt(0,-65),0);assert.ok(Math.abs(W.heightAt(0,-85)-3)<1e-9);assert.equal(W.heightAt(0,-105),5.4);for(let z=-104;z<-64;z+=.25)assert.ok(Math.abs(W.heightAt(0,z+.25)-W.heightAt(0,z))<=.038);});
