import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGame,checkpoint,restore,interact,interactable} from '../model.mjs';
import {completeTask} from '../field-tasks.mjs';
import {move} from '../motion.mjs';
import {LEVELS,OBSTACLES,HEIGHT,solidAt,findPath,heightAt,syncRouteGates} from '../world.mjs';
import {RECUT_ROUTES,RECUT_REVISION,RETURN_TASK,recutHeight} from '../floodgate-recut.mjs';
function walk(s,points){let peak=0,steps=0;for(const [x,z]of points){const path=findPath(s.player,{x,z});assert.ok(path.length||Math.hypot(s.player.x-x,s.player.z-z)<1.4,JSON.stringify({x,z}));for(const p of [...path,{x,z}]){for(let i=0;i<200&&Math.hypot(s.player.x-p.x,s.player.z-p.z)>.08;i++){const dx=p.x-s.player.x,dz=p.z-s.player.z,d=Math.hypot(dx,dz),oldY=heightAt(s.player.x,s.player.z);move(s.player,dx/d*Math.min(.07,d),dz/d*Math.min(.07,d),HEIGHT.stand);const y=heightAt(s.player.x,s.player.z);assert.ok(Math.abs(y-oldY)<.07,'No instantaneous floor-height jump: '+JSON.stringify({p,oldY,y}));peak=Math.max(peak,y);steps++;}assert.ok(Math.hypot(s.player.x-p.x,s.player.z-p.z)<.15,'Physical path blocked '+JSON.stringify({p,player:s.player}));}}return {peak,steps};}
test('The existing Floodgate slot contains the recut rather than an eighth demonstration level',()=>{createGame();assert.equal(Object.keys(LEVELS).length,7);assert.equal(LEVELS.district.layoutRevision,RECUT_REVISION);assert.equal(OBSTACLES.some(o=>o.id==='clinic-west'),false);assert.ok(OBSTACLES.some(o=>o.id==='clinic-west-north'));assert.deepEqual(LEVELS.district.shelters.map(c=>[c.id,c.x,c.z]),[['start',0,27],['clinic',-24,-1]]);});
test('Sheltered clinic approach physically reaches the original battery with no new extraction requirement',()=>{const s=createGame();walk(s,RECUT_ROUTES.garden.points);assert.equal(interactable(s).id,'clinic-cell');assert.ok(interact(s));assert.equal(s.objectives.cell,true);assert.ok(!s.completedTasks.includes(RETURN_TASK));});
for(const key of ['marketTerrace','westRamp'])test('The '+key+' route is actual continuous elevated navigation, not visual-only scenery',()=>{const s=createGame();Object.assign(s.player,{x:RECUT_ROUTES[key].points[0][0],z:RECUT_ROUTES[key].points[0][1]});const result=walk(s,RECUT_ROUTES[key].points);assert.ok(result.peak>=2.39);assert.ok(result.steps>50);});
test('The clinic descent joins the upper route to the original battery room',()=>{const s=createGame();Object.assign(s.player,{x:-22,z:-10});walk(s,[[-22,-7],[-22,-3.5]]);assert.equal(heightAt(s.player.x,s.player.z),0);assert.equal(interactable(s).id,'clinic-cell');});
test('The return shutter cannot be opened remotely or through its outside face',()=>{const s=createGame();assert.equal(completeTask(s,RETURN_TASK),false);Object.assign(s.player,{x:-29,z:5.8});assert.equal(completeTask(s,RETURN_TASK),false);assert.equal(solidAt(-28,5.8),true);});
test('Opening the shutter changes real collision and shortens the recovery loop without granting resources',()=>{const s=createGame();Object.assign(s.player,{x:-26.1,z:5.8});const before=JSON.stringify(s.player),closed=findPath({x:-26.1,z:5.8},{x:-30,z:5.8}).length;assert.equal(interactable(s).id,RETURN_TASK);assert.ok(interact(s));assert.equal(solidAt(-28,5.8),false);assert.equal(JSON.stringify(s.player),before);const opened=findPath({x:-26.1,z:5.8},{x:-30,z:5.8}).length;assert.ok(opened<closed/2,{closed,opened});walk(s,RECUT_ROUTES.clinicReturn.points);assert.equal(completeTask(s,RETURN_TASK),false);});
test('Return-gate state survives an unchanged version-4 shelter save; old saves remain closed and valid',()=>{const s=createGame();const old=checkpoint(s);Object.assign(s.player,{x:-26.1,z:5.8});interact(s);s.checkpoint='clinic';const raw=checkpoint(s);assert.equal(JSON.parse(raw).version,4);const newState=restore(raw);assert.ok(newState.completedTasks.includes(RETURN_TASK));assert.equal(solidAt(-28,5.8),false);assert.equal(newState.player.x,-24);const oldState=restore(old);assert.ok(oldState);assert.equal(solidAt(-28,5.8),true);assert.equal(oldState.player.z,27);});
test('A preview restore cannot open gates in the active map, and a fresh start closes them',()=>{const s=createGame();Object.assign(s.player,{x:-26.1,z:5.8});interact(s);const raw=checkpoint(s);createGame();assert.ok(solidAt(-28,5.8));assert.ok(restore(raw,false));assert.ok(solidAt(-28,5.8));restore(raw);assert.equal(solidAt(-28,5.8),false);createGame();assert.ok(solidAt(-28,5.8));});
test('Patrols use the same reachable terrace route and all legacy objects remain reachable',()=>{const s=createGame();for(const p of LEVELS.district.patrols)for(const [x,z]of p.points)assert.ok(findPath(s.player,{x,z}).length,p.id);for(const item of LEVELS.district.items)assert.ok(findPath(s.player,item).length,item.id);assert.equal(recutHeight(-30,-22),0);assert.equal(recutHeight(-8,-10),0);assert.equal(recutHeight(-22,-3.5),0);});
