import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import * as T from '../vendor/three.module.js';import {LEVELS} from '../world.mjs';import {fernPlacements,planterRockPlacements,scanStatus} from '../scan-plan.mjs';import {graphicsPreset} from '../graphics.mjs';import {worldTexturing} from '../surface-work.mjs';
const root=path.resolve(import.meta.dirname,'../assets/scanned'),manifest=()=>JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));
function glb(name){const b=fs.readFileSync(path.join(root,name));assert.equal(b.toString('ascii',0,4),'glTF');assert.equal(b.readUInt32LE(4),2);const j=JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));return j;}
test('Every imported binary has a source credit and exact locked runtime hash under the transfer budget',()=>{const m=manifest();assert.equal(m.license,'CC0-1.0');assert.equal(Object.keys(m.assets).length,8);let n=0;for(const [name,f]of Object.entries(m.files)){const b=fs.readFileSync(path.join(root,name));assert.equal(b.length,f.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),f.sha256,name);n+=b.length;}assert.equal(n,m.totalBytes);assert.ok(n<14000000);for(const a of Object.values(m.assets)){assert.ok(Object.keys(a.authors).length);assert.equal(a.license,'CC0-1.0');}});
test('The four real surface sets retain 2K color, 1K normal and packed material channels',()=>{const m=manifest();for(const s of Object.values(m.surfaces)){assert.equal(s.color.width,2048);assert.equal(s.normal.width,1024);assert.equal(s.orm.width,512);assert.ok(s.metres>0);}});
test('Imported models remain textured glTF with UVs, normal maps and no runtime external URIs',()=>{for(const id of ['boulder_01','rock_moss_set_01','fern_02']){const j=glb(id+'.glb');for(const mesh of j.meshes)for(const p of mesh.primitives){assert.ok(p.attributes.TEXCOORD_0!==undefined);assert.ok(j.materials[p.material].pbrMetallicRoughness.baseColorTexture);assert.ok(j.materials[p.material].normalTexture);}for(const b of [...j.buffers,...j.images])assert.equal(b.uri,undefined);assert.ok(j.images.every(i=>i.mimeType==='image/webp'));}});
test('Fern alpha silhouettes and four plant variants survive optimization',()=>{const j=glb('fern_02.glb');assert.equal(j.meshes.length,4);assert.ok(j.materials.some(m=>m.alphaMode==='MASK'));assert.ok(j.materials.some(m=>m.doubleSided));});
test('Six independently placeable mossy rocks keep a bounded mesh budget',()=>{const m=manifest();assert.equal(m.models.rock_moss_set_01.meshes.length,6);assert.ok(m.models.rock_moss_set_01.triangles<25000);assert.ok(m.models.fern_02.triangles<7000);});
test('Detailed plants never change authored paths or crowd an objective, clue, control or shelter',()=>{for(const c of Object.values(LEVELS)){const before=JSON.stringify(c),points=fernPlacements(c);assert.deepEqual(points,fernPlacements(c));assert.ok(points.length>0&&points.length<90);for(const p of points){assert.ok(c.grass.some(g=>Math.abs(p.x-g.x)<g.w/2&&Math.abs(p.z-g.z)<g.d/2));for(const q of [...c.items,...c.shelters,...(c.puzzle?[c.puzzle.clue,...c.puzzle.wheels]:[])])assert.ok(Math.hypot(q.x-p.x,q.z-p.z)>=2.2);}assert.equal(JSON.stringify(c),before);}});
test('New solid-looking near rocks are confined to existing blocked planter footprints',()=>{for(const c of Object.values(LEVELS))for(const p of planterRockPlacements(c)){const o=c.obstacles.find(o=>o.kind==='planter'&&o.x===p.x&&o.z===p.z);assert.ok(o);assert.ok(p.scale<=Math.min(o.w,o.d)/2);}});
test('Asynchronous source material changes invalidate the low-cost material, without touching geometry',()=>{const scene=new T.Scene(),m=new T.MeshStandardMaterial({map:new T.Texture()}),mesh=new T.Mesh(new T.BoxGeometry(),m);scene.add(mesh);const renderer={shadowMap:{},setPixelRatio(){}},g=graphicsPreset(scene,renderer);g.set(true);const first=mesh.material,newMap=new T.Texture();m.map=newMap;m.needsUpdate=true;g.update();assert.notEqual(mesh.material,first);assert.equal(mesh.material.map,newMap);g.dispose();assert.equal(mesh.material,m);});
test('Late HDR environment remains suppressed in low mode and restores on full quality',()=>{const scene=new T.Scene(),g=graphicsPreset(scene,{shadowMap:{},setPixelRatio(){}}),hdr=new T.Texture();g.set(true);g.setEnvironment(hdr);assert.equal(scene.environment,null);g.set(false);assert.equal(scene.environment,hdr);g.dispose();});
test('Scanned normals and occlusion are actually sampled by the surface shader',()=>{const m=worldTexturing(new T.MeshStandardMaterial()),s={vertexShader:'#include <project_vertex>',fragmentShader:'#include <normal_fragment_maps>\n#include <aomap_fragment>\n#include <metalnessmap_fragment>'};m.onBeforeCompile(s);assert.match(s.fragmentShader,/USE_NORMALMAP_TANGENTSPACE/);assert.match(s.fragmentShader,/texture2D\(normalMap/);assert.match(s.fragmentShader,/rwSample\(aoMap\)/);assert.match(s.fragmentShader,/rwFrame\(/);});
test('Asset status distinguishes readiness, progress, fallback and deliberate comparison mode',()=>{const s={enabled:true,pending:true,done:3,total:8,errors:[]};assert.match(scanStatus(s),/3\/8/);s.pending=false;assert.match(scanStatus(s),/ready/);s.errors.push('texture missing');assert.match(scanStatus(s),/partial/);s.enabled=false;assert.match(scanStatus(s),/off/);});
