import {makeWorld,newState,readSave,saveData,SAVE_KEY,VERSION,step,enterExit,scan,recover,activeTarget,missionText,nearestNode,district,distance} from './model.mjs';
import {createScene} from './scene.mjs';
const $=id=>document.getElementById(id),world=makeWorld();let storage=true,saved=null;
try{saved=readSave(localStorage.getItem(SAVE_KEY),world);}catch{storage=false;}
let state=newState(saved),view,playing=false,paused=false,keys=new Set(),touch=new Set(),accumulator=0,last=0,lastSave='',lastUI=0,jump=false,look=0,drag=null,audio=null,sound=false,flash='';
function save(){const value=JSON.stringify(saveData(state));if(value===lastSave)return;try{localStorage.setItem(SAVE_KEY,value);lastSave=value;$('save-status').textContent='Progress saved on this device';}catch{storage=false;$('save-status').textContent='Storage unavailable — this session is not saved';}}
function clearInput(){keys.clear();touch.clear();jump=false;look=0;document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));accumulator=0;}
function setPause(v){paused=v;clearInput();if(audio){if(v)audio.ctx.suspend().catch(()=>{});else if(sound)audio.ctx.resume().catch(()=>{});}if(!v)$('world').focus({preventScroll:true});}
function pause(){if(!playing)return;setPause(true);if(!$('pause-dialog').open)$('pause-dialog').showModal();}
function map(){if(!playing)return;setPause(true);drawMap($('city-map'),true);$('map-dialog').showModal();}
function soundGraph(){if(audio)return;const ctx=new AudioContext(),gain=ctx.createGain(),engine=ctx.createOscillator(),filter=ctx.createBiquadFilter();gain.gain.value=0;engine.type='triangle';engine.frequency.value=42;filter.type='lowpass';filter.frequency.value=150;engine.connect(filter);filter.connect(gain);gain.connect(ctx.destination);engine.start();audio={ctx,gain,engine};}
function toggleSound(){sound=!sound;if(sound){soundGraph();audio.ctx.resume().catch(()=>{});}else audio?.ctx.suspend().catch(()=>{});$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));}
function chime(){if(!sound||!audio||paused)return;const c=audio.ctx;[523.25,659.25,783.99].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=f;const t=c.currentTime+i*.07;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.025,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+.28);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.3);o.onended=()=>{o.disconnect();g.disconnect();};});}
function start(){playing=true;paused=false;clearInput();$('menu').hidden=true;$('menu').style.display='none';$('hud').hidden=false;$('world').focus();if(sound)audio?.ctx.resume();}
$('start').onclick=start;$('pause-button').onclick=pause;$('map-button').onclick=$('minimap-button').onclick=map;$('sound').onclick=toggleSound;
$('resume').onclick=()=>$('pause-dialog').close();$('map-close').onclick=()=>$('map-dialog').close();
$('pause-dialog').addEventListener('close',()=>{if(playing)setPause(false);});$('map-dialog').addEventListener('close',()=>{if(playing)setPause(false);});
$('recover').onclick=()=>{recover(state);$('pause-dialog').close();view?.update(0,state,{snap:true});};
$('reset').onclick=()=>{if(!confirm('Start a fresh SVGN City dispatch? This resets only this game’s saved deliveries, credits and story progress.'))return;state=newState();lastSave='';save();$('pause-dialog').close();view?.update(0,state,{snap:true});};
$('menu-return').onclick=()=>{playing=false;setPause(true);$('pause-dialog').close();$('hud').hidden=true;$('menu').hidden=false;$('menu').style.display='flex';$('start').textContent='Continue exploring →';};
const handled=new Set(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyQ','KeyC','KeyE','KeyF','KeyX','KeyH','KeyM','KeyP','Escape','ShiftLeft','ShiftRight']);
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||!playing)return;
 if((e.code==='KeyP'||e.code==='Escape')&&!e.repeat){if($('map-dialog').open)$('map-dialog').close();else if($('pause-dialog').open)$('pause-dialog').close();else pause();e.preventDefault();return;}
 if(paused)return;if(handled.has(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;
 if(e.code==='KeyM')map();if(e.code==='KeyF'||e.code==='KeyE')enterExit(state,world);if(e.code==='KeyX')scan(state);if(e.code==='Space')jump=true;
});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(playing&&!paused)pause();else clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause();});
for(const b of document.querySelectorAll('[data-hold]')){const code=b.dataset.hold;b.onpointerdown=e=>{if(!playing||paused)return;e.preventDefault();touch.add(code);b.classList.add('held');b.setPointerCapture(e.pointerId);};for(const type of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>{touch.delete(code);b.classList.remove('held');});}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>{if(paused||!playing)return;switch(b.dataset.action){case'vehicle':enterExit(state,world);break;case'scan':scan(state);break;case'jump':jump=true;}};
if(matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0)document.body.classList.add('touch');
$('world').addEventListener('pointerdown',e=>{if(!playing||paused)return;drag={id:e.pointerId,x:e.clientX};$('world').setPointerCapture(e.pointerId);});$('world').addEventListener('pointermove',e=>{if(drag?.id===e.pointerId){look-=(e.clientX-drag.x)*.003;drag.x=e.clientX;}});for(const e of['pointerup','pointercancel','lostpointercapture'])$('world').addEventListener(e,()=>drag=null);
function controls(){const has=(a,b)=>keys.has(a)||keys.has(b);return {throttle:Number(has('KeyW','ArrowUp')||touch.has('up'))-Number(has('KeyS','ArrowDown')||touch.has('down')),steer:Number(has('KeyD','ArrowRight')||touch.has('right'))-Number(has('KeyA','ArrowLeft')||touch.has('left')),boost:has('ShiftLeft','ShiftRight'),brake:keys.has('Space')&&state.mode==='car',jump,leftPaper:keys.has('KeyQ')||touch.has('q'),rightPaper:keys.has('KeyC')||touch.has('c'),hack:keys.has('KeyH')||touch.has('hack'),look};}
function drawMap(canvas,full=false){const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,scale=full?Math.min(w/330,h/480):1.55,ox=full?w/2:w/2-state.x*scale,oy=full?55:-state.z*scale+h*.52;
 const X=x=>ox+x*scale,Z=z=>oy+z*scale;g.fillStyle='#224650';g.fillRect(0,0,w,h);g.fillStyle='#54765e';g.fillRect(X(-148),Z(-26),296*scale,432*scale);
 for(const x of world.roads){g.fillStyle='#213e48';g.fillRect(X(x-7),Z(-26),14*scale,432*scale);g.fillStyle='#8f9b84';g.fillRect(X(x-10),Z(-26),2*scale,432*scale);}
 for(const z of world.crossings){g.fillStyle='#213e48';g.fillRect(X(-148),Z(z-7),296*scale,14*scale);}
 for(const b of world.houses){g.fillStyle='#b9b396';g.fillRect(X(b.x-b.w/2),Z(b.z-b.d/2),b.w*scale,b.d*scale);}
 for(const b of world.mailboxes){g.fillStyle=state.deliveries.has(b.id)?'#688c70':b.route?'#edbd7d':'#9bbdac';g.fillRect(X(b.x)-2,Z(b.z)-2,4,4);}
 for(const n of world.nodes){g.strokeStyle=state.relay&&n.type==='relay'?'#80bf9f':'#8bd6c1';g.lineWidth=2;g.beginPath();g.arc(X(n.x),Z(n.z),full?7:4,0,7);g.stroke();}
 const goal=activeTarget(state,world);g.strokeStyle='#f5daae';g.lineWidth=1.4;g.setLineDash([4,6]);g.beginPath();g.moveTo(X(state.x),Z(state.z));g.lineTo(X(goal.x),Z(goal.z));g.stroke();g.setLineDash([]);g.save();g.translate(X(goal.x),Z(goal.z));g.rotate(Math.PI/4);g.fillStyle='#f4cb85';g.fillRect(-4,-4,8,8);g.restore();
 for(const [type,v]of Object.entries(state.vehicle))if(state.mode!==type){g.fillStyle=type==='car'?'#eda065':'#83c2cf';g.fillRect(X(v.x)-3,Z(v.z)-5,6,10);}
 g.save();g.translate(X(state.x),Z(state.z));g.rotate(-state.yaw);g.fillStyle='#fff9d3';g.beginPath();g.moveTo(0,8);g.lineTo(5,-5);g.lineTo(-5,-5);g.closePath();g.fill();g.restore();
 if(full){g.fillStyle='#e1e7cc';g.font='600 15px Arial';g.textAlign='center';for(const [name,z]of[['SUNRISE TERRACE',-13],['CIVIC QUARTER',157],['HARBOR FRONT',310]])g.fillText(name,X(0),Z(z));g.font='11px Arial';g.textAlign='left';g.fillText('N ↑',15,22);g.fillText('Waterfront / distant skyline is scenery',20,h-20);}
}
function updateUI(){const p=missionText(state),set=(id,text)=>{if($(id).textContent!==text)$(id).textContent=text;};set('mission-tag',p.tag);set('mission-title',p.title);set('mission-description',p.text);set('target-distance',Math.round(distance(state,activeTarget(state,world)))+' m');set('district',district(state).toUpperCase());set('mode-name',state.mode==='bike'?'COURIER BICYCLE':state.mode==='car'?'SVGN PRESS HATCHBACK':'ON FOOT / CITY REPORTER');set('speed',String(Math.round(Math.abs(state.speed)*3.6)).padStart(2,'0'));set('papers',String(state.papers));set('score',String(state.score));set('credits',String(state.credits));$('health').style.width=state.health+'%';set('trace-status',state.trace>.1?'CITY SIGNAL / TRACE '+Math.round(state.trace*100)+'%':'CITY SIGNAL / CLEAR');$('toast').classList.toggle('visible',state.toastT>0);set('toast',state.toast);if(flash!==state.toast&&state.toast.startsWith('Delivered'))chime();flash=state.toast;
 const node=nearestNode(state,world);let hint=state.mode==='foot'?'WASD walk · F enter a nearby ride':state.mode==='car'?'WASD drive · Space handbrake · F get out':'WASD ride · Q / C throw · F dismount';
 if(node)hint=state.scan>0?((state.relay&&node.type==='relay')?'Relay restored. The garden shortcut is open.':'Stop and hold H: '+node.name):'X: scan '+node.name;
 if(distance(state,world.depot)<8)hint='Kiosk nearby · hold H to refill papers and repair';set('context',hint);$('hack').style.display=state.hackProgress>0?'block':'none';$('hack').querySelector('i').style.transform=`scaleX(${state.hackProgress})`;drawMap($('minimap'));if($('map-dialog').open)drawMap($('city-map'),true);
}
function frame(now){requestAnimationFrame(frame);const dt=last?Math.min(.1,(now-last)/1000):0;last=now;const input=controls();
 if(playing&&!paused&&!document.hidden){accumulator=Math.min(.18,accumulator+dt);while(accumulator>=1/60){step(state,world,input,1/60);input.jump=false;jump=false;accumulator-=1/60;}if(now-lastUI>80){updateUI();lastUI=now;}save();}
 else accumulator=0;
 view.update(dt,state,{steer:input.steer,look:playing&&!paused?look:0});look=0;
 if(sound&&audio&&!paused){audio.engine.frequency.setTargetAtTime(state.mode==='car'?36+Math.abs(state.speed)*3:47+Math.abs(state.speed),audio.ctx.currentTime,.12);audio.gain.gain.setTargetAtTime(playing?Math.min(.03,Math.abs(state.speed)*.001):0,audio.ctx.currentTime,.2);}
}
try{
 const quality=new URLSearchParams(location.search).get('quality')==='low'?'low':'high';view=createScene($('world'),world,state,quality);window.addEventListener('resize',()=>view.resize());$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('failure-detail').textContent='The graphics context was interrupted. Reload to restore the scene; completed mission progress is kept.';$('failure').hidden=false;});
 $('start').disabled=false;$('start').textContent=saved?'Continue your dispatch →':'Start your first dispatch →';if(saved)$('resume-info').textContent='Your saved deliveries and story progress are ready.';if(!storage)$('resume-info').textContent='Storage is blocked. Play is available, but progress will not be saved.';
 Object.defineProperty(window,'SVGNCity',{value:Object.freeze({version:VERSION,inspect:()=>({version:VERSION,running:playing&&!paused,paused,mode:state.mode,x:state.x,z:state.z,yaw:state.yaw,speed:state.speed,lift:state.lift,steps:state.steps,mission:state.mission,relay:state.relay,completed:state.completed,deliveries:[...state.deliveries],papers:state.papers,credits:state.credits,score:state.score,health:state.health,scan:state.scan,trace:state.trace,events:state.events.map(e=>({...e})),vehicles:JSON.parse(JSON.stringify(state.vehicle)),target:{...activeTarget(state,world)},render:view.inspect()})})});
 updateUI();requestAnimationFrame(frame);
}catch(e){console.error(e);$('failure-detail').textContent=String(e.message||e);$('failure').hidden=false;$('start').textContent='Graphics unavailable';}
