const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../core');
function fixture(){const nodes=new Map(),listeners=new Map(),saved=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{id,value:id==='reach'?'1':'',dataset:{},textContent:'',append(){},setAttribute(){},focus(){},addEventListener(){}});return nodes.get(id);};let definition;
const c={window:null,document:{hidden:false,body:{dataset:{}},getElementById:node,querySelectorAll:()=>[],createElement:()=>({dataset:{},setAttribute(){}})},AFRAME:{registerComponent:(name,d)=>definition=d},PrismCore:C,localStorage:{getItem:()=>null,setItem:(k,v)=>saved.set(k,v)},console};c.window=c;c.addEventListener=(name,fn)=>listeners.set(name,fn);vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),c);
let time=0;const audio={a:{state:'running'},offset:2,context(){return {resume:async()=>{}};},prepare:async()=>{},play:async()=>{},stop(){},pause(){this.offset=time;},time:()=>time,level(){}};
const g={...definition,audio,phase:'menu',track:'first-light',difficulty:'flow',input:'slice',busy:false,offset:0,loadSerial:0,records:{},immersive:false,el:{is:()=>false},art:{blade(){},update(){}},T:{Matrix4:class{}},xr:{calibrated:true,tick(){}},lastTime:0};g.ui();return {g,node,listeners,saved,context:c};}
test('Gamepad selection survives rebuilding and has a separate run mode',async()=>{const {g,node}=fixture();node('input').value='gamepad';node('input').onchange({target:node('input')});A.equal(g.input,'gamepad');await g.start();A.equal(g.state.mode,'keys');A.equal(g.runMode,'gamepad');A.equal(g.phase,'playing');});
test('Gamepad records preserve legacy keyboard and slice records',async()=>{const {g,saved}=fixture();g.records={'first-light/flow/keys':{score:900,accuracy:80,best:9},'first-light/flow/slice':{score:500,accuracy:70,best:5}};g.input='gamepad';await g.start();g.state.state='complete';g.state.score=1000;g.complete();const r=JSON.parse(saved.get('prism-current.v1.records'));A.equal(r['first-light/flow/keys'].score,900);A.equal(r['first-light/flow/slice'].score,500);A.equal(r['first-light/flow/gamepad'].score,1000);});
test('Pause avoids the reserved A-Frame lifecycle',async()=>{const {g}=fixture();g.pause=()=>{throw Error('Reserved lifecycle invoked')};g.phase='playing';g.state=C.create(C.chart());g.state.state='playing';g.pauseRun('Test');A.equal(g.phase,'paused');await g.resume();A.equal(g.phase,'playing');});
test('Abandoned preparation cannot revive a run',async()=>{const {g}=fixture();let resolve;g.audio.prepare=()=>new Promise(r=>resolve=r);const pending=g.start();g.abort();resolve();await pending;A.equal(g.phase,'menu');A.equal(g.state,null);});
test('Abandoned resume cannot revive a run',async()=>{const {g}=fixture();g.phase='paused';g.state=C.create(C.chart());let resolve;g.audio.play=()=>new Promise(r=>resolve=r);const pending=g.resume();g.abort();resolve(true);await pending;A.equal(g.phase,'menu');A.equal(g.state,null);});
test('Two resume requests call the transport only once',async()=>{const {g}=fixture();g.phase='paused';g.state=C.create(C.chart());let resolve,calls=0;g.audio.play=()=>{calls++;return new Promise(r=>resolve=r)};const pending=g.resume();await g.resume();A.equal(calls,1);resolve(true);await pending;A.equal(g.phase,'playing');});
test('Hidden-page resume leaves the track paused',async()=>{const {g,context}=fixture();g.phase='paused';g.state=C.create(C.chart());g.state.state='paused';let resolve;g.audio.play=()=>new Promise(r=>resolve=r);const pending=g.resume();context.document.hidden=true;resolve(true);await pending;A.equal(g.phase,'paused');A.equal(g.state.state,'paused');});
test('Shader preparation remains ahead of soundtrack playback',async()=>{const {g}=fixture();let resolve,calls=0;g.art.prepare=()=>new Promise(r=>resolve=r);g.audio.play=async()=>{calls++};const pending=g.start();await new Promise(setImmediate);A.equal(calls,0);resolve();await pending;A.equal(calls,1);A.equal(g.phase,'playing');});
test('Typing P in an input does not pause gameplay',()=>{const {g,listeners}=fixture();g.keyboard();g.phase='playing';let calls=0;g.pauseRun=()=>calls++;const key=listeners.get('keydown');key({target:{tagName:'INPUT'},code:'KeyP',preventDefault(){}});A.equal(calls,0);key({target:{tagName:'CANVAS'},code:'KeyP',preventDefault(){}});A.equal(calls,1);});
