/* Pure input and AudioContext fixtures; not physical-device acceptance. */
const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const P=require('../control-room.js'),C=require('../core.js');
function pad(buttons=[],axes=[0,0]){return {mapping:'standard',connected:true,buttons:Array.from({length:17},(_,i)=>({pressed:buttons.includes(i),value:buttons.includes(i)?1:0})),axes};}
function audio(saved=null){const store=new Map(saved?[['prism-current.v1.audio',saved]]:[]);let live=0,max=0;const param=()=>({value:0,setTargetAtTime(v){this.value=v},setValueAtTime(v){this.value=v},exponentialRampToValueAtTime(v){this.value=v}});class Context{constructor(){this.currentTime=0;this.state='running';this.destination={};this.defer=null;}resume(){return this.defer||Promise.resolve()}createGain(){return {gain:param(),connect(){},disconnect(){}}}createBufferSource(){let active=false;return {connect(){},disconnect(){},start(){active=true;live++;max=Math.max(max,live)},stop(){if(active){active=false;live--}}}}createOscillator(){return {frequency:param(),connect(){},disconnect(){},start(){},stop(){}}}}
 const context={AudioContext:Context,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},setTimeout,clearTimeout,console};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/../audio.js','utf8'),context);const a=new context.PrismAudio();a.context();a.cache.set('first-light',{duration:60});return {a,store,get live(){return live},get max(){return max}};}
test('Lane mapping is LT LB RB RT from left to right',()=>{A.deepEqual(P.sample(pad([6,4,5,7])).lanes,[0,1,2,3]);});
test('Held triggers produce no repeated hits',()=>{const first=P.sample(pad([6]));A.deepEqual(P.sample(pad([6]),first.down).lanes,[]);A.deepEqual(P.sample(pad([6]),P.sample(pad([])).down).lanes,[0]);});
test('Analog triggers cross threshold and tolerate missing entries',()=>{const p=pad();p.buttons[6]={value:.7};A.deepEqual(P.sample(p).lanes,[0]);A.deepEqual(P.sample({mapping:'standard',buttons:[],axes:[]}).lanes,[]);});
test('Disconnected, nonstandard and XR pads are rejected',()=>{A.equal(P.sample(null),null);A.equal(P.sample({...pad(),connected:false}),null);A.equal(P.sample({...pad(),mapping:'xr-standard'}),null);A.equal(P.sample({...pad(),mapping:''}),null);});
test('Stick deadzone and D-pad direction are stable',()=>{A.equal(P.sample(pad([],[.2,.2])).direction,0);A.equal(P.sample(pad([],[.9,0])).direction,2);A.equal(P.sample(pad([12])).direction,-1);A.equal(P.sample(pad([13]),[],1).directionChanged,false);});
test('Quality targets do not mutate records',()=>{const r={accuracy:80,score:1000};A.deepEqual(P.goals(r),{earned:2,next:90});A.deepEqual(P.goals({accuracy:95}),{earned:3,next:null});A.equal(r.score,1000);A.equal(P.goals(null).earned,0);});
test('Music and effects volumes are independent',()=>{const {a}=audio();a.level(0);A.equal(a.gain.gain.value,0);A.equal(a.effects.gain.value,.22);a.effectLevel(0);a.level(.8);A.equal(a.gain.gain.value,.8);A.equal(a.effects.gain.value,0);});
test('Mute initializes both buses and restores both levels',()=>{const {a}=audio('{"music":0.4,"effects":0.1,"muted":true,"rate":"minimal"}');A.equal(a.gain.gain.value,0);A.equal(a.effects.gain.value,0);a.level(a.volume,false);A.equal(a.gain.gain.value,.4);A.equal(a.effects.gain.value,.1);});
test('Persisted settings are bounded; bad JSON falls back safely',()=>{const {a}=audio('{"music":9,"effects":-1,"rate":"garbage"}');A.equal(a.volume,1);A.equal(a.effectsVolume,0);A.equal(a.feedbackRate,'balanced');A.equal(audio('{bad').a.volume,.55);a.level(NaN);A.equal(a.volume,1);});
test('Mixer preferences never overwrite score storage',()=>{const {a,store}=audio();store.set('prism-current.v1.records','{"legacy":true}');a.effectLevel(.35);a.rate('minimal');A.equal(store.get('prism-current.v1.records'),'{"legacy":true}');A.equal(JSON.parse(store.get('prism-current.v1.audio')).effects,.35);});
test('Minimal feedback has a cooldown and off is silent',()=>{const {a}=audio();a.rate('minimal');A.equal(a.hit(0,1),true);a.a.currentTime=.1;A.equal(a.hit(1,1),false);a.a.currentTime=.41;A.equal(a.hit(1,1),true);a.rate('off');a.a.currentTime=1;A.equal(a.hit(0,1),false);});
test('Effects never exceed four voices',()=>{const {a}=audio();a.rate('all');for(let i=0;i<20;i++){a.a.currentTime=i*.04;a.hit(i%2,1);}A.equal(a.voices.size,4);a.stop();A.equal(a.voices.size,0);});
test('Rapid playback keeps at most one soundtrack voice',async()=>{const f=audio();await f.a.play('first-light');await f.a.play('first-light',4);await f.a.play('first-light',5);A.equal(f.max,1);A.equal(f.live,1);f.a.stop();A.equal(f.live,0);});
test('Cancellation during pending resume cannot start a source',async()=>{const f=audio();let resolve;f.a.a.defer=new Promise(r=>resolve=r);const pending=f.a.play('first-light');f.a.stop();resolve();A.equal(await pending,false);A.equal(f.live,0);});
test('Concurrent resume leaves only the latest request active',async()=>{const f=audio();let resolve;f.a.a.defer=new Promise(r=>resolve=r);const first=f.a.play('first-light',3),second=f.a.play('first-light',7);resolve();A.equal(await first,false);A.equal(await second,true);A.equal(f.live,1);A.equal(f.a.offset,7);});
test('Pause preserves the audio-clock offset',async()=>{const f=audio();await f.a.play('first-light',2);f.a.a.currentTime=3.65;A.equal(f.a.pause(),5);A.equal(f.live,0);A.equal(f.a.time(),5);});
for(const track of C.TRACKS)for(const difficulty of ['flow','pulse'])test(`Unchanged chart completes through timing taps: ${track.id}/${difficulty}`,()=>{const s=C.create(C.chart(track.id,difficulty),{mode:'keys'});s.state='playing';for(const n of s.song.notes){C.advance(s,n.time);A.equal(C.tap(s,n.lane,n.time)?.type,'hit');A.equal(C.tap(s,n.lane,n.time),null);}C.advance(s,s.song.duration);A.equal(C.result(s).complete,true);A.equal(C.result(s).accuracy,100);});
