const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core'),M=require('../music');
function state(mode='slice',hand=0,dir=0){const s=C.create({...C.chart(),notes:[{id:0,time:1,lane:1,row:0,hand,dir}],duration:2},{mode});s.state='playing';C.advance(s,1);return s;}
function swipe(s,hand=0,reverse=false){const p=C.position(s.song.notes[0],1,s.reach),b=y=>({a:[p[0],p[1]+y,p[2]+.25],b:[p[0],p[1]+y,p[2]-.20]});return C.slice(s,hand,b(reverse?-.16:.16),b(reverse?.16:-.16),.98,1.02);}
test('All songs share the score tempo grid and have original finite varied arrangements',()=>{for(const t of C.TRACKS){const s=C.chart(t.id),p=C.chart(t.id,'pulse'),e=M.events(s);A.ok(s.notes.length>=44);A.ok(p.notes.length>s.notes.length);A.ok(new Set(p.notes.map(n=>n.dir)).size>=4);A.ok(e.length>500);A.ok(s.notes.every(n=>n.time>=8*60/t.bpm&&n.time<s.duration));A.equal(new Set(s.notes.map(n=>n.id)).size,s.notes.length);}});
test('Swept two-ended blade catches a moving note between frames, once',()=>{const s=state();A.equal(swipe(s)[0].type,'hit');A.equal(s.hits,1);A.equal(swipe(s).length,0);A.ok(s.score>60);});
test('Wrong hand and opposite direction break combo instead of granting points',()=>{for(const [hand,reverse]of[[1,false],[0,true]]){const s=state();s.combo=20;A.equal(swipe(s,hand,reverse)[0].type,'bad');A.equal(s.score,0);A.equal(s.combo,0);}});
test('A dot note accepts any deliberate direction with the correct blade',()=>{const s=state('slice',0,6);A.equal(swipe(s,0,true)[0].type,'hit');});
test('Tracking gaps and position jumps cannot cut through a row of targets',()=>{const s=state(),p={a:[0,0,0],b:[0,0,0]};A.equal(C.slice(s,0,p,{a:[8,8,8],b:[8,8,8]},.99,1.01).length,0);A.equal(C.slice(s,0,p,p,.5,1).length,0);A.equal(s.hits,0);});
test('A stationary blade is not an automatic hit as notes pass it',()=>{const s=state(),p=C.position(s.song.notes[0],1),pose={a:p,b:[p[0],p[1],p[2]-.5]};A.equal(C.slice(s,0,pose,pose,.98,1.02).length,0);});
test('Off-axis or distant swings cannot teleport an attachment to a note',()=>{const s=state(),p={a:[6,6,0],b:[6,6,-1]};A.equal(C.slice(s,0,p,{a:[6,5.9,0],b:[6,5.9,-1]},.98,1.02).length,0);});
test('Keyboard tapping is an explicit separate mode, not perfect saber direction',()=>{let s=state('keys');A.equal(C.tap(s,1,1).type,'hit');A.equal(C.tap(s,1,1),null);s=state();A.equal(C.tap(s,1,1),null);});
test('Pause and backward clock readings cannot create misses or points',()=>{const s=state();s.state='paused';C.advance(s,99);A.equal(s.time,1);A.equal(swipe(s).length,0);s.state='playing';C.advance(s,.5);A.equal(s.time,1);});
test('Finishing with no inputs still yields a complete no-fail song',()=>{const s=state();C.advance(s,2);A.equal(s.state,'complete');A.equal(s.misses,1);A.equal(C.result(s).accuracy,0);});
test('Timing and center quality are bounded, and best-combo persists after misses',()=>{const s=state('keys');s.combo=7;C.tap(s,1,1.16);A.ok(s.score>=45&&s.score<=200);s.song.notes.push({id:1,time:1.5,lane:2,row:0,hand:1,dir:0});C.advance(s,1.8);A.equal(s.combo,0);A.equal(s.best,8);A.ok(C.result(s).accuracy<=100);});
test('Malformed charts and requests are rejected or ignored safely',()=>{A.throws(()=>C.chart('unknown'));A.throws(()=>C.chart('first-light','impossible'));const s=state();A.equal(C.slice(s,0,{a:[NaN,0,0],b:[0,0,0]},{a:[0,0,0],b:[0,0,0]},.98,1.02).length,0);});
test('Scores synthesize stereo audio with headroom, not clipping or silence',()=>{for(const song of C.TRACKS){const s=C.chart(song.id),r=M.render(s,12000);A.equal(r.left.length,Math.ceil(s.duration*12000));A.ok(r.peak<=.781&&r.peak>.1);A.ok(r.rms>.025&&r.rms<.3);A.ok(r.left.every(Number.isFinite));A.ok(r.left.some((v,i)=>Math.abs(v-r.right[i])>.001));}});
