/* Deterministic geometry and contracts, not renderer or physical-device approval. */
'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs');
const T=require('../modules/environment/trees');
test('Trees exposes frozen limits and the same ES-module implementation',async()=>{const e=await import('../modules/environment/trees.mjs');A.equal(e.default,T);A.equal(T.VERSION,'0.2.0');A.ok(Object.isFrozen(T.DETAIL[0]));A.equal(T.MAX_TREES,24);});
test('Seed and schema reconstruct exactly the same skeleton',()=>{for(const preset of T.PRESETS){const a=T.skeleton({seed:19,preset,height:4}),b=T.skeleton(JSON.parse(JSON.stringify(a.descriptor)));A.deepEqual(a,b);A.notDeepEqual(a,T.skeleton({seed:20,preset,height:4}));A.equal(a.schema,1);}});
test('Descriptors copy input and reject invalid identity or positions',()=>{const p=Object.freeze([1,2,3]),d=Object.freeze({id:'oak',seed:17,height:4,position:p});const r=T.descriptor(d);A.notEqual(r.position,p);A.deepEqual(r.position,p);for(const bad of [null,[],{id:''},{position:[NaN,2,3]},{position:[1,2]}])A.throws(()=>T.descriptor(bad),TypeError);});
test('Untrusted numeric settings are bounded before generation',()=>{const d=T.descriptor({height:Infinity,yaw:NaN,seed:NaN,preset:'__proto__',position:[1e12,-1e12,0]});A.equal(d.height,4);A.equal(d.yaw,0);A.equal(d.preset,'palm');A.deepEqual(d.position,[10000,-10000,0]);A.equal(T.descriptor({height:99}).height,18);A.equal(T.descriptor({height:0}).height,.5);});
test('All presets create tapered wood paths and distinct actual leaf silhouettes',()=>{const p=T.skeleton({preset:'palm'}),a=T.skeleton({preset:'alder'}),w=T.skeleton({preset:'willow'});A.equal(p.paths.length,13);A.ok(w.paths.length>a.paths.length);for(const s of[p,a,w]){A.ok(s.leaves.length>300&&s.leaves.length<600);A.ok(s.paths.every(p=>p.radius>p.tip&&p.tip>0));A.ok(s.leaves.every(l=>l.width>0&&l.base.every(Number.isFinite)&&l.tip.every(Number.isFinite)));}});
test('Every detail uses the original skeleton and decreases actual triangle count',()=>{for(const preset of T.PRESETS){const s=T.skeleton({preset,seed:3}),copy=JSON.stringify(s),counts=[];for(let i=0;i<3;i++){const g=T.geometryData(s,i);counts.push((g.wood.index.length+g.foliage.index.length)/3);}A.ok(counts[2]<counts[1]&&counts[1]<counts[0]);A.equal(JSON.stringify(s),copy);A.ok(counts[0]<7000);}});
test('Every buffer/index/normal remains finite over presets and several seeds',()=>{for(const preset of T.PRESETS)for(const seed of[0,1,99999])for(let d=0;d<3;d++){const g=T.geometryData(T.skeleton({preset,seed,height:3}),d);for(const p of Object.values(g)){const n=p.position.length/3;A.equal(p.cwRoot.length,n*4);A.equal(p.uv.length,n*2);for(const a of Object.values(p))A.ok(a.every(Number.isFinite));A.ok(p.index.every(i=>i>=0&&i<n));for(let i=0;i<p.normal.length;i+=3)A.ok(Math.abs(Math.hypot(...p.normal.subarray(i,i+3))-1)<1e-5);}}});
test('Base trunk triangles face outwards rather than disappearing with backface culling',()=>{const g=T.geometryData(T.skeleton({seed:5,preset:'palm',height:4}),0).wood;for(let i=0;i<9;i++){const p=g.position.subarray(i*3,i*3+3),n=g.normal.subarray(i*3,i*3+3);A.ok(p[0]*n[0]+p[2]*n[2]>0);}});
test('Geometry transforms match the descriptor root and yaw without changing topology',()=>{const a=T.geometryData(T.skeleton({id:'a',seed:7,height:3}),1),b=T.geometryData(T.skeleton({id:'b',seed:7,height:3,position:[2,1,-8],yaw:Math.PI/2}),1);for(const k of ['wood','foliage']){A.deepEqual(a[k].index,b[k].index);for(let i=0;i<a[k].position.length;i+=3){A.ok(Math.abs(b[k].position[i]-(a[k].position[i+2]+2))<2e-6);A.ok(Math.abs(b[k].position[i+1]-(a[k].position[i+1]+1))<2e-6);A.ok(Math.abs(b[k].position[i+2]-(-a[k].position[i]-8))<2e-6);}}});
test('Wind fixes the roots, uses absolute time, and matches its analytic normal derivative',()=>{for(const t of[0,.6,3,90])for(const h of[.5,4,18])for(const y of[0,h*.5,h,h*1.3]){const a=T.wind(y,h,.6,t,.7);A.deepEqual(a,T.wind(y,h,.6,t,.7));if(y===0)A.ok(a.offset===0);else {const e=1e-5,der=(T.wind(y+e,h,.6,t,.7).offset-T.wind(y-e,h,.6,t,.7).offset)/(2*e);A.ok(Math.abs(a.gradient-der)<1e-7);}A.ok(Math.abs(a.offset)<=h*.3);}});
test('Zero wind removes displacement without replacing the skeleton',()=>{const a=T.wind(2,4,.3,5,0);A.ok(a.offset===0&&a.gradient===0);});
test('Distance detail hysteresis avoids left/right-eye threshold oscillation',()=>{A.equal(T.level(16.3,0),0);A.equal(T.level(18.1,0),1);A.equal(T.level(15,1),1);A.equal(T.level(13.8,1),0);A.equal(T.level(31,1),1);A.equal(T.level(34,1),2);A.equal(T.level(28,2),2);A.equal(T.level(25,2),1);A.equal(T.level(1,0,1),1);});
test('No engine, renderer, storage, network or input is owned by the Trees module',()=>{const s=fs.readFileSync(__dirname+'/../modules/environment/trees.js','utf8');A.doesNotMatch(s,/requestAnimationFrame|performance\.now|Date\.now|Math\.random|localStorage|document\.|new T\.WebGLRenderer|fetch\(/);A.match(s,/cwTime/);A.match(s,/customProgramCacheKey/);});
test('Creation fails clearly without the host Three namespace',()=>A.throws(()=>T.create({}),/THREE/));

test('Palm detail thinning keeps paired left and right leaflets together',()=>{const s=T.skeleton({preset:'palm'});for(const lod of T.DETAIL){const kept=s.leaves.filter(l=>l.sample%lod.leafStride===0);for(let i=0;i<12;i++){const segment=s.leaves.slice(i*35,i*35+34);for(let j=0;j<34;j+=2)A.equal(kept.includes(segment[j]),kept.includes(segment[j+1]));}}});
test('Prism bank foliage stays outside the 7m-wide action corridor even at peak authored wind',()=>{const layout=require('../river/bank-trees');for(const d of layout.TREES)for(let lod=0;lod<3;lod++){const g=T.geometryData(T.skeleton(d),lod),sign=Math.sign(d.position[0]);for(const mesh of Object.values(g))for(let i=0;i<mesh.position.length;i+=3){const y=mesh.position[i+1]-d.position[1],k=Math.min(1.4,Math.max(0,y/d.height)),maxWind=d.height*k*k*(.065+.027)*layout.WIND;A.ok(sign*mesh.position[i]-maxWind>3.5,d.id+' lod '+lod);}}});

test('Vertex wind reads shared amplitudes instead of recalculating trigonometry per vertex',()=>{const s=fs.readFileSync(__dirname+'/../modules/environment/trees.js','utf8'),shader=s.split('const windGLSL=`')[1].split('`;')[0];A.match(shader,/cwAmplitude\[int\(cwTree/);A.doesNotMatch(shader,/sin\(|cos\(/);});

test('Tree 0.2 foliage and bark enrich shading without adding runtime texture or persistent-target ownership',()=>{const s=fs.readFileSync(__dirname+'/../modules/environment/trees.js','utf8');A.match(s,/float edge=pow/);A.match(s,/float fine=/);A.doesNotMatch(s,/new T\.Texture|new T\.DataTexture|sampler2D|sampler3D/);A.match(s,/renderTargets:0/);A.match(s,/rt\.dispose\(\)/);});
