/* Actual production start method, controlled audio/renderer collaborators. */
const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../river/core');
function fixture(){let def,finish,plays=0;const order=[];const scope={RiverCore:C,document:{hidden:false,getElementById:()=>({focus(){}})},AFRAME:{registerComponent:(_,v)=>def=v}};vm.createContext(scope);vm.runInContext(fs.readFileSync(__dirname+'/../river/app.js','utf8'),scope);
 const g={...def,phase:'menu',serial:0,busy:false,immersive:false,padId:null,chapter:'duck-armada',cruise:false,quiet:false,xr:{},el:{is:()=>false,object3D:{},camera:{},renderer:{compileAsync:async()=>{order.push('scene');}}},art:{reset(){},update(){},prepare(){order.push('effects');return new Promise(r=>finish=r);}},audio:{context:()=>({resume:async()=>{}}),prepare:async()=>{},play:async()=>{plays++;order.push('play');return true;}},sync(){},clearInputs(){},notice(t){this.message=t;},cancel(){this.serial++;this.busy=false;this.phase='menu';this.state=null;}};
 return {g,scope,order,get plays(){return plays;},async started(){const p=g.start();for(let i=0;i<10&&!finish;i++)await Promise.resolve();A.ok(finish,'reached actual effect preparation');return {pending:p};},finish(){finish();}};
}
test('Actual start awaits density/program preparation before audio plays',async()=>{const f=fixture(),{pending}=await f.started();A.equal(f.plays,0);A.equal(f.g.phase,'loading');f.finish();await pending;A.deepEqual(f.order,['scene','effects','play']);A.equal(f.g.phase,'playing');});
test('Cancelling during effect preparation never starts the abandoned battle',async()=>{const f=fixture(),{pending}=await f.started();f.g.cancel();f.finish();await pending;A.equal(f.plays,0);A.equal(f.g.phase,'menu');A.equal(f.g.state,null);});
test('Visibility loss during preparation aborts instead of starting hidden audio',async()=>{const f=fixture(),{pending}=await f.started();f.scope.document.hidden=true;f.finish();await pending;A.equal(f.plays,0);A.equal(f.g.phase,'menu');});
test('Older preparation cannot unlock a newer operation',async()=>{const f=fixture(),{pending}=await f.started();f.g.serial++;f.g.busy=true;f.g.phase='loading';f.g.message='new request';f.finish();await pending;A.equal(f.plays,0);A.equal(f.g.busy,true);A.equal(f.g.message,'new request');});
