/* Test-only ordinary input producer. Reads the real audio clock; never writes
 * game state, note times, scores, judgments or the AudioContext clock.
 * The held pointer is presented during count-in, not first drawn at the hit. */
window.PrismTestInput={
 now(){const g=Prism.component;return g.audio.time()+(g.runOffset||0);},
 keys(){const done=new Set(),map=['KeyD','KeyF','KeyJ','KeyK'];const timer=setInterval(()=>{const s=Prism.snapshot();if(s.phase==='complete'){clearInterval(timer);return;}if(s.phase!=='playing')return;const time=this.now();for(const n of s.notes){if(done.has(n.id)||time<n.time-.035||time>n.time+.12)continue;done.add(n.id);const target=document.getElementById('scene-wrap');for(const type of ['keydown','keyup'])target.dispatchEvent(new KeyboardEvent(type,{code:map[n.lane],bubbles:true,cancelable:true}));}},3);},
 async pointer(){window.prismPointerTrace=[];const g=Prism.component,n=g.state.song.notes[0],id=g.pointer.id,T=AFRAME.THREE,el=document.getElementById('scene-wrap');await new Promise((resolve,reject)=>{const start=performance.now(),timer=setInterval(()=>{const time=this.now();if(g.state.judged[n.id]==='hit'){clearInterval(timer);resolve();return;}if(g.phase!=='playing'||performance.now()-start>15000){clearInterval(timer);reject(Error('Pointer timing interrupted before a valid hit'));return;}const f=Math.max(0,Math.min(1,(time-(n.time-.10))/.20)),v=PrismCore.position(n,n.time),p=new T.Vector3(v[0],v[1]+.28-f*.56,v[2]).project(AFRAME.scenes[0].camera),r=el.getBoundingClientRect();const prior=g.pointer;el.dispatchEvent(new PointerEvent('pointermove',{pointerId:id,pointerType:'mouse',isPrimary:true,buttons:1,clientX:r.x+(p.x*.5+.5)*r.width,clientY:r.y+(-p.y*.5+.5)*r.height,bubbles:true,cancelable:true}));prismPointerTrace.push({offset:time-n.time,gap:time-(prior?.time||0),frameLag:time-g.state.time,point:g.pointer?.p.toArray(),judged:g.state.judged[n.id]||null});if(prismPointerTrace.length>64)prismPointerTrace.shift();if(g.state.judged[n.id]==='hit'){clearInterval(timer);resolve();}else if(f===1){clearInterval(timer);reject(Error('Pointer missed; input trace: '+JSON.stringify(prismPointerTrace)));}},5);});},
 async xr(){const note=Prism.snapshot().notes[0],center=PrismCore.position(note,note.time);await new Promise((resolve,reject)=>{const began=performance.now(),timer=setInterval(()=>{const state=Prism.snapshot(),time=this.now();if(state.phase!=='playing'||performance.now()-began>20000){clearInterval(timer);reject(Error('Saber input could not reach its audio cue'));return;}if(time<note.time-.18)return;const f=Math.max(0,Math.min(1,(time-note.time+.15)/.30));TestXR.pose('left',[center[0],center[1]+.28-.56*f,-.41]);if(f>=1){clearInterval(timer);resolve();}},4);});}
};
