/* Pure lesson rules and PCM fixtures, not a human onboarding or hardware test. */
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core'),L=require('../lessons');
function played(step,mode='keys',skip=[]){const s=C.create(L.chart(step,mode),{mode:'keys'});s.state='playing';for(const n of s.song.notes){C.advance(s,n.time);if(!skip.includes(n.id))C.tap(s,n.lane,n.time);}C.advance(s,s.song.duration);return s;}
for(const mode of L.MODES)for(let step=0;step<4;step++)test(`${mode} exercise ${step+1} is reachable, bounded and uses real core timing`,()=>{const s=played(step,mode),p=s.song;A.ok(p.duration<12);A.equal(p.notes[0].row,0);A.ok(p.notes[0].time>=p.lesson.countIn);A.equal(C.result(s).accuracy,100);A.equal(L.assess(s,{paused:true,resumed:true}).passed,true);A.ok(p.notes.every(n=>n.hand===(n.lane<2?0:1)));});
test('A no-input complete song does not pass the lesson',()=>{const s=played(0,'keys',[0,1,2,3]);A.equal(C.result(s).complete,true);A.equal(L.assess(s).passed,false);});
test('Both hand groups are required, not just the hit threshold',()=>{const s=played(3,'keys',[1,3]);A.equal(s.hits,2);A.equal(L.assess(s,{paused:true,resumed:true}).passed,false);});
test('Pause exercise needs explicit pause AND resume evidence',()=>{const s=played(3);for(const proof of [{},{paused:true},{resumed:true},{paused:true,resumed:false}])A.equal(L.assess(s,proof).passed,false);A.equal(L.assess(s,{paused:true,resumed:true}).passed,true);});
test('Early completion or arbitrary charts cannot grant a lesson pass',()=>{const s=played(0);s.state='playing';A.equal(L.assess(s).passed,false);A.equal(L.assess(C.create(C.chart())).passed,false);});
test('Four key exercises do not alter any catalog charts',()=>{const before=JSON.stringify(C.TRACKS.map(t=>C.chart(t.id)));for(let i=0;i<4;i++)played(i);A.equal(JSON.stringify(C.TRACKS.map(t=>C.chart(t.id))),before);});
test('Wrong-way slicing still fails a directional tutorial note',()=>{const song=L.chart(2,'slice'),n=song.notes[0],s=C.create(song,{mode:'slice'});s.state='playing';C.advance(s,n.time);const p=C.position(n,n.time),pose=y=>({a:[p[0],p[1]+y,p[2]+.1],b:[p[0],p[1]+y,p[2]-.2]});C.slice(s,0,pose(-.04),pose(.04),n.time-.02,n.time+.02);A.equal(s.judged[0],'bad');});
test('Matching directional swipe still earns a real lesson hit',()=>{const song=L.chart(2,'slice'),n=song.notes[0],s=C.create(song,{mode:'slice'});s.state='playing';C.advance(s,n.time);const p=C.position(n,n.time),pose=y=>({a:[p[0],p[1]+y,p[2]+.1],b:[p[0],p[1]+y,p[2]-.2]});C.slice(s,0,pose(.04),pose(-.04),n.time-.02,n.time+.02);A.equal(s.judged[0],'hit');});
test('Keyboard lesson instructions do not claim arrow grading',()=>{A.match(L.instructions(2,'keys'),/not graded/);A.match(L.instructions(2,'slice'),/down, then up/);});
test('Bad lesson selections are rejected',()=>{for(const i of [-1,4,NaN,1.5,'1'])A.throws(()=>L.chart(i,'keys'));A.throws(()=>L.chart(0,'ar'));});
test('Only recognized input-specific completion flags survive malformed storage',()=>{A.deepEqual(L.load('{bad'),[]);A.deepEqual(L.load('{}'),[]);A.deepEqual(L.load('{"version":2,"completed":["keys"]}'),[]);A.deepEqual(L.load('{"version":1,"completed":["keys","keys","__proto__","ar","gamepad"]}'),['keys','gamepad']);A.notEqual(L.STORE,'prism-current.v1.records');A.notEqual(L.STORE,'prism-current.v1.practice');});
test('Every original lesson sound is finite, stereo, bounded and long enough',()=>{for(let step=0;step<4;step++){const s=L.chart(step,'slice');const b=L.buffer({createBuffer:(ch,n,rate)=>{const a=Array.from({length:ch},()=>new Float32Array(n));return {length:n,sampleRate:rate,getChannelData:i=>a[i]};}},s);let peak=0;for(const value of b.getChannelData(0)){A.ok(Number.isFinite(value));peak=Math.max(peak,Math.abs(value));}A.ok(peak>.02&&peak<.2);A.ok(Math.abs(b.length/b.sampleRate-s.duration)<1/b.sampleRate);A.deepEqual(b.getChannelData(0),b.getChannelData(1));}});
