const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../core');
function fixture(){const nodes=new Map(),listeners=new Map(),saved=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{id,value:id==='reach'?'1':'',dataset:{},textContent:'',append(){},setAttribute(){},focus(){},addEventListener(){}});return nodes.get(id);};let definition;
const c={window:null,document:{hidden:false,body:{dataset:{}},getElementById:node,querySelectorAll:()=>[],createElement:()=>({dataset:{},setAttribute(){}})},AFRAME:{registerComponent:(name,d)=>definition=d},PrismCore:C,localStorage:{getItem:()=>null,setItem:(k,v)=>saved.set(k,v)},console};c.window=c;c.addEventListener=(name,fn)=>listeners.set(name,fn);vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),c);
let time=0;const audio={a:{state:'running'},offset:2,context(){return {resume:async()=>{}};},prepare:async()=>{},play:async()=>{},stop(){},pause(){this.offset=time;},time:()=>time,level(){}};
const g={...definition,audio,phase:'menu',track:'first-light',difficulty:'flow',input:'slice',busy:false,offset:0,loadSerial:0,records:{},immersive:false,el:{is:()=>false},art:{blade(){},update(){}},T:{Matrix4:class{}},xr:{calibrated:true,tick(){}},lastTime:0};g.ui();return {g,node,listeners,saved,context:c};}

test('A lesson completion cannot enter either score writer',async()=>{const {g,saved}=fixture(),L=require('../lessons');let marked=0;g.lessons={beforeStart(){},selection:()=>L.chart(0,'keys'),prepare:()=>L.BUFFER,result(){marked++},sync(){},cancelRun(){}};g.practice={result(){throw Error('Practice writer reached')},sync(){},cancelRun(){}};g.input='keys';g.records={'first-light/flow/keys':{score:99,accuracy:50,best:2}};await g.start();A.equal(g.runAudio,L.BUFFER);g.state.state='complete';g.complete();A.equal(marked,1);A.equal(g.records['first-light/flow/keys'].score,99);A.equal(saved.size,0);});
test('Lesson resume uses its own audio buffer and emits a resume signal only after playback',async()=>{const {g}=fixture();let started=0,notified=0;g.phase='paused';g.state=C.create(C.chart());g.runAudio='__prism-lesson__';g.lessons={resumed(){notified++;A.equal(started,1)},sync(){}};g.audio.play=async id=>{A.equal(id,'__prism-lesson__');started++;return true};await g.resume();A.equal(notified,1);});
test('Abort during lesson loading cannot revive abandoned educational audio',async()=>{const {g}=fixture();let done,cancel=0;g.lessons={beforeStart(){},sync(){},cancelRun(){cancel++}};g.audio.prepare=()=>new Promise(r=>done=r);const job=g.start();g.abort();done();await job;A.equal(g.phase,'menu');A.equal(g.state,null);A.equal(cancel,1);});
test('Pause passes its actual reason to lesson evidence',()=>{const {g}=fixture();let reason;g.phase='playing';g.state=C.create(C.chart());g.lessons={paused:r=>reason=r,sync(){}};g.pauseRun('Controller disconnected');A.equal(reason,'Controller disconnected');A.equal(g.phase,'paused');});
