/* Component contract fixtures, not native renderer/AR acceptance. */
const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../core');
function fixture(){const nodes=new Map(),listeners=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{id,value:id==='reach'?'1':'',dataset:{},textContent:'',append(){},setAttribute(){},focus(){},addEventListener(){}});return nodes.get(id);};let definition;
const c={window:null,document:{hidden:false,body:{dataset:{}},getElementById:node,querySelectorAll:()=>[],createElement:()=>({dataset:{},setAttribute(){}})},AFRAME:{registerComponent:(name,d)=>definition=d},PrismCore:C,localStorage:{getItem:()=>null,setItem(){}},console};c.window=c;c.addEventListener=(name,fn)=>listeners.set(name,fn);vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),c);
let time=0;const audio={a:{state:'running'},offset:2,context(){return {resume:async()=>{}};},prepare:async()=>{},play:async()=>{},stop(){},pause(){this.offset=time;},time:()=>time,level(){}};
const g={...definition,audio,phase:'menu',track:'first-light',difficulty:'flow',input:'slice',busy:false,offset:0,loadSerial:0,records:{},immersive:false,el:{is:()=>false},art:{blade(){},update(){}},T:{Matrix4:class{}},xr:{calibrated:true,tick(){}},lastTime:0};g.ui();return {g,node,listeners,setTime:n=>time=n};}
test('Input and difficulty selection survive abort rebuilding the menu',()=>{const {g,node}=fixture();node('input').value='keys';node('input').onchange({target:node('input')});A.equal(g.input,'keys');A.equal(node('input').value,'keys');node('difficulty').value='pulse';node('difficulty').onchange({target:node('difficulty')});A.equal(g.difficulty,'pulse');});
test('User pause/resume never invokes A-Frame wrapped pause or deregisters tick',async()=>{const {g}=fixture();g.pause=()=>{throw Error('Reserved lifecycle should not be used for user pause');};g.phase='playing';g.state=C.create(C.chart());g.state.state='playing';g.pauseRun('Test user pause');A.equal(g.phase,'paused');A.equal(g.message,'Test user pause');await g.resume();A.equal(g.phase,'playing');A.equal(g.state.state,'playing');});
test('The actual scene lifecycle still stops audio and does not auto-resume',()=>{const {g}=fixture();g.phase='playing';g.state=C.create(C.chart());g.pause();A.equal(g.phase,'paused');A.equal(g.message,'Scene suspended. Resume when ready.');});
test('Stopping during an async start cannot revive an abandoned track',async()=>{const {g}=fixture();let resolve;g.audio.prepare=()=>new Promise(r=>resolve=r);const start=g.start();g.abort();resolve();await start;A.equal(g.phase,'menu');A.equal(g.state,null);});
test('Saber state is discarded on pause; no held swing is replayed after resume',()=>{const {g}=fixture();g.phase='playing';g.state=C.create(C.chart());g.previous=[{pose:{a:[1,2,3],b:[3,4,5]},time:1},null];g.pauseRun();A.deepEqual(Array.from(g.previous),[null,null]);});
test('Canvas keyboard input is accepted, but editing fields do not play notes',()=>{const {g,listeners}=fixture();g.keyboard();let pauses=0;g.phase='playing';g.pauseRun=()=>pauses++;const key=listeners.get('keydown');key({target:{tagName:'CANVAS'},code:'KeyP',preventDefault(){}});A.equal(pauses,1);key({target:{tagName:'INPUT'},code:'KeyP',preventDefault(){}});A.equal(pauses,1);});

test('Graphics preparation completes before the original audio transport starts',async()=>{const {g}=fixture();let release,started=0;g.art.prepare=()=>new Promise(r=>release=r);g.audio.play=async()=>{started++;};const run=g.start();await new Promise(setImmediate);A.equal(g.phase,'loading');A.equal(started,0);release();await run;A.equal(started,1);A.equal(g.phase,'playing');});
test('Aborting during shader preparation cannot start an abandoned audio buffer',async()=>{const {g}=fixture();let release,started=0;g.art.prepare=()=>new Promise(r=>release=r);g.audio.play=async()=>{started++;};const run=g.start();await new Promise(setImmediate);g.abort();release();await run;A.equal(started,0);A.equal(g.phase,'menu');A.equal(g.state,null);});
