/* Practice derivation, copy integrity and real-time scoring contracts. */
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core'),F=require('../phrases'),P=require('../practice');
for(const track of C.TRACKS)for(const difficulty of ['flow','pulse'])test(`All section/speed plans preserve source charts: ${track.id}/${difficulty}`,()=>{
 const song=C.chart(track.id,difficulty),before=JSON.stringify(song);for(const section of P.sections(song))for(const speed of P.SPEEDS){
  const plan=P.chart(song,section.id,speed),original=song.notes.filter(n=>n.time>=section.start&&n.time<section.end);A.equal(plan.notes.length,original.length);A.equal(plan.bpm,song.bpm*speed);A.ok(plan.duration<120);
  for(const [i,n]of plan.notes.entries()){A.equal(n.id,i);A.equal(n.sourceId,original[i].id);A.equal(n.lane,original[i].lane);A.equal(n.hand,original[i].hand);A.equal(n.dir,original[i].dir);A.ok(Math.abs((n.time-plan.practice.countIn)*speed+section.start-original[i].time)<1e-10);}
  const s=C.create(plan,{mode:'keys'});s.state='playing';for(const n of plan.notes){C.advance(s,n.time);C.tap(s,n.lane,n.time);}C.advance(s,plan.duration);A.equal(C.result(s).accuracy,100);A.equal(C.result(s).hits,plan.notes.length);A.equal(F.summary(s).samples,plan.notes.length);
 }A.equal(JSON.stringify(song),before);
});
test('Invalid section, empty section, speed and unbounded plans are rejected',()=>{const song=C.chart();for(const x of [0,1.1,NaN,Infinity,'0.75'])A.throws(()=>P.chart(song,'phrase-0',x));A.throws(()=>P.chart(song,'missing',.75));A.throws(()=>P.chart({...song,notes:[]},'phrase-0',.75));A.throws(()=>P.chart({...song,bpm:1},'phrase-0',.6));});
test('Real-time hit windows are not widened by slowing a section',()=>{const s=C.create(P.chart(C.chart(),'phrase-0',.6),{mode:'keys'});s.state='playing';const n=s.song.notes[0];C.advance(s,n.time);A.equal(C.tap(s,n.lane,n.time+.18),null);A.equal(C.tap(s,n.lane,n.time+.1).type,'hit');});
function audioBuffer(channels,length,rate){const data=Array.from({length:channels},()=>new Float32Array(length));return {sampleRate:rate,length,numberOfChannels:channels,duration:length/rate,getChannelData:n=>data[n]};}
for(const speed of P.SPEEDS)test(`Practice PCM preserves crop and matches note-clock timing at ${speed}`,()=>{
 const original=C.chart(),song=P.chart(original,'phrase-0',speed),source=audioBuffer(2,Math.ceil(original.duration*24000),24000);source.getChannelData(0).fill(.2);source.getChannelData(1).fill(-.3);const ctx={createBuffer:audioBuffer},out=P.buffer(ctx,source,song,false);
 A.equal(out.sampleRate,24000*speed);A.ok(Math.abs(out.duration-song.duration)<1/out.sampleRate*2);const onset=Math.round(song.practice.countIn*out.sampleRate);A.ok(out.getChannelData(0).subarray(0,onset).every(v=>v===0));A.ok(Math.abs(out.getChannelData(0)[onset+400]-.2)<1e-7);A.ok(Math.abs(out.getChannelData(1)[onset+400]+.3)<1e-7);A.equal(out.getChannelData(0)[onset],0);A.equal(out.getChannelData(0).at(-1),0);A.ok(source.getChannelData(0).every(v=>Math.abs(v-.2)<1e-7));
 const audible=P.buffer(ctx,source,song,true);A.ok(audible.getChannelData(0).subarray(0,onset).some(v=>Math.abs(v)>.02));A.ok(audible.getChannelData(0).subarray(0,onset).every(v=>Math.abs(v)<=.1));
});
test('Audio validates sample rate, range and source presence',()=>{const s=P.chart(C.chart(),'phrase-0',.6);A.throws(()=>P.buffer({},null,s));A.throws(()=>P.buffer({createBuffer:audioBuffer},audioBuffer(1,100,1000),s));A.throws(()=>P.buffer({createBuffer:audioBuffer},audioBuffer(1,100,24000),s));});
test('Practice records separate speed, section, chart and device; input is immutable',()=>{const s=P.chart(C.chart(),'phrase-0',.75),before={},r={complete:true,score:1200,accuracy:88};const records=P.record(before,s,'gamepad',r);A.equal(Object.keys(before).length,0);A.equal(records[P.key(s,'gamepad')].passes,1);A.notEqual(P.key(s,'gamepad'),P.key(P.chart(C.chart(),'phrase-0',1),'gamepad'));A.notEqual(P.key(s,'gamepad'),P.key(s,'keys'));const next=P.record(records,s,'gamepad',{...r,score:900,accuracy:93});A.equal(next[P.key(s,'gamepad')].score,1200);A.equal(next[P.key(s,'gamepad')].accuracy,93);A.equal(next[P.key(s,'gamepad')].passes,2);});
test('Aborted, invalid and immersive practice results cannot create records',()=>{const s=P.chart(C.chart(),'phrase-0',.75);A.throws(()=>P.record({},s,'keys',{complete:false,score:1,accuracy:1}));A.throws(()=>P.record({},s,'keys',{complete:true,score:NaN,accuracy:1}));A.throws(()=>P.key(s,'ar'));});
test('Malformed practice saves are ignored without touching the full-song namespace',()=>{A.deepEqual(P.load('{bad'),{});A.deepEqual(P.load('[]'),{});A.deepEqual(P.load('{"__proto__":{},"x":4}'),{});const s=P.chart(C.chart(),'phrase-0',1),r=P.record({},s,'keys',{complete:true,score:1000,accuracy:80});A.deepEqual(P.load(JSON.stringify(r)),r);A.notEqual(P.STORE,'prism-current.v1.records');});
test('Repeat is opt-in, once-only and cancelled when visibility or focus is unsafe',()=>{const gate=new P.RepeatGate();A.equal(gate.due(10000,true),false);gate.arm(10);A.equal(gate.due(5009,true),false);A.equal(gate.due(5010,true),true);A.equal(gate.due(6000,true),false);gate.arm(0);A.equal(gate.due(6000,false),false);A.equal(gate.due(7000,true),false);gate.arm(0);gate.cancel();A.equal(gate.due(9000,true),false);});
