/* Model fixtures, not native gameplay or physical-device acceptance. */
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../river/core');
function entity(type,position,extra={}){return {id:1,type,at:0,travel:10,start:position.slice(),end:position.slice(),r:.24,hp:4,maxHP:4,dead:false,hand:0,dir:0,...extra};}
function setup(type='fruit',p=[-.5,1.4,-1]){const s=C.create();s.mode='playing';s.time=1;s.entities=[entity(type,p)];s.cursor=s.timeline.length;return s;}
test('Each authored chapter has eight slice directions and different enemy families',()=>{for(const ch of ['duck-armada','mothership']){const a=C.plan(ch);A.equal(new Set(a.filter(n=>n.type==='fruit').map(n=>n.dir)).size,8);A.ok(a.every(n=>n.at>=0&&n.at<C.DURATION));A.equal(a.filter(n=>n.type==='boss').length,1);}A.ok(C.plan('duck-armada').some(n=>n.type==='catapult'));A.ok(C.plan('duck-armada').some(n=>n.type==='boat'));A.ok(C.plan('mothership').some(n=>n.type==='fighter'));});
test('Water smoothly changes tide height, without altering the player body',()=>{A.equal(C.water('duck-armada',0),-.18);A.ok(C.water('duck-armada',34)>.20);A.ok(C.water('duck-armada',55)>.6);for(let t=.01;t<88;t+=.01)A.ok(Math.abs(C.water('duck-armada',t)-C.water('duck-armada',t-.01))<.01);});
for(let d=0;d<8;d++)test('Actual swept blade cuts fruit direction '+d,()=>{const s=setup(),n=s.entities[0];n.dir=d;const v=C.DIRS[d],p=n.start,pose=a=>({a:[p[0]+v[0]*a,p[1]+v[1]*a,-.4],b:[p[0]+v[0]*a,p[1]+v[1]*a,-1.3]});A.equal(C.slice(s,0,pose(-.2),pose(.2),.96,1.04),1);A.equal(s.stats.slices,1);A.ok(n.dead);A.equal(C.slice(s,0,pose(-.2),pose(.2),.96,1.04),0);});
test('Wrong hand, wrong direction, still blades and stale poses do not grant slices',()=>{for(const kind of ['hand','reverse','still','stale']){const s=setup(),pose=y=>({a:[-.5,y,-.4],b:[-.5,y,-1.3]});const a=kind==='reverse'?1.2:1.6,b=kind==='reverse'?1.6:kind==='still'?1.6:1.2;C.slice(s,kind==='hand'?1:0,pose(a),pose(b),kind==='stale'?.5:.96,1.04);A.equal(s.stats.slices,0);}});
test('Laser must intersect a target and obey each hand cooldown',()=>{const s=setup('boat',[0,1.4,-8]);s.entities[0].life=10;s.entities[0].x=0;s.entities[0].y=1.4;const p=C.position(s,s.entities[0]),o=[0,1.4,0],dir=p.map((x,i)=>x-o[i]);A.equal(C.shoot(s,0,o,[1,0,0]),false);A.equal(s.stats.shotHits,0);A.equal(C.shoot(s,0,o,dir),false);s.time+=.2;A.equal(C.shoot(s,0,o,dir),true);A.equal(s.stats.shotHits,1);});
test('Shield intercepts a crossing projectile; wrong-facing shield does not',()=>{for(const correct of [true,false]){const s=setup('bolt',[0,1.4,-1]);s.time=.8;s.entities[0].start=[0,1.4,-2];s.entities[0].end=[0,1.4,1];s.entities[0].travel=2;s.entities[0].r=.12;C.advance(s,1,[0,1.4,0],[{active:true,center:[0,1.4,-.7],normal:[0,0,correct?-1:1],raised:.85,hand:0}]);A.equal(s.stats.blocks,correct?1:0);if(correct){A.equal(s.stats.reflects,1);A.equal(s.health,100);}}});
test('Moving out of a projectile lane awards dodge instead of damage',()=>{const s=setup('bolt',[0,1.4,-1]);s.entities[0].start=[0,1.4,-2];s.entities[0].end=[0,1.4,1];s.entities[0].travel=1;s.time=.2;C.advance(s,.7,[.8,1.4,0]);A.equal(s.stats.dodges,1);A.equal(s.health,100);});
test('Bombs punish slicing, while aimed distant fire disarms them',()=>{const s=setup('bomb');C.slice(s,0,{a:[-.5,1.6,-.4],b:[-.5,1.6,-1.3]},{a:[-.5,1.2,-.4],b:[-.5,1.2,-1.3]},.96,1.04);A.equal(s.health,92);A.equal(s.stats.slices,0);});
test('Boss core cannot be damaged before the visible vulnerability phase',()=>{const s=C.create('mothership');s.mode='playing';C.advance(s,0);const boss=s.entities.find(n=>n.type==='boss');const hit=()=>{const p=C.position(s,boss);C.shoot(s,0,[0,1.4,0],[p[0],p[1]-1.4,p[2]]);};hit();A.equal(boss.hp,60);s.time=152*C.BEAT;hit();A.equal(boss.hp,59);});
test('Destroying a catapult before its launch suppresses its fruit volley',()=>{const s=setup('catapult');s.time=0;s.entities[0].x=0;s.entities[0].y=.4;s.entities[0].life=10;s.entities[0].hp=1;s.entities[0].volley=0;const p=C.position(s,s.entities[0]);C.shoot(s,0,[0,1.4,0],[p[0],p[1]-1.4,p[2]]);C.advance(s,2);A.equal(s.entities.filter(n=>n.type==='fruit').length,0);});
test('No-input runs cannot report a boss victory; paused state is frozen',()=>{const s=C.create('duck-armada',true);s.mode='playing';for(let t=0;t<C.DURATION;t+=.025)C.advance(s,t);C.advance(s,C.DURATION);A.equal(s.mode,'escaped');A.equal(C.result(s).complete,false);s.mode='paused';const raw=JSON.stringify(s);C.advance(s,900);A.equal(JSON.stringify(s),raw);});
test('Complete simulated chapters exercise slicing, laser damage and proper outcomes',()=>{for(const ch of ['duck-armada','mothership']){const s=C.create(ch,true);s.mode='playing';for(let t=0;t<C.DURATION;t+=.025){C.advance(s,t,[0,1.4,0],[{active:true,center:[-.3,1.36,-.72],normal:[0,0,-1],raised:t-.1},{active:true,center:[.3,1.36,-.72],normal:[0,0,-1],raised:t-.1}]);
 for(const n of s.entities){const p=C.position(s,n);if(n.type==='fruit'&&p[2]>-1.5&&p[2]<-.6){const v=C.DIRS[n.dir],pose=a=>({a:[p[0]+v[0]*a,p[1]+v[1]*a,-.35],b:[p[0]+v[0]*a,p[1]+v[1]*a,-1.6]});C.slice(s,n.hand,pose(-.2),pose(.2),t-.04,t+.04);}if(n.type==='boss'&&C.open(s,n)){for(const h of[0,1])C.shoot(s,h,[0,1.4,0],[p[0],p[1]-1.4,p[2]]);}}
 A.ok(s.entities.length<=80);A.ok(s.events.length<=100);
 }C.advance(s,C.DURATION);A.equal(s.mode,'complete');A.ok(s.stats.slices>20);A.ok(s.stats.blocks>0);A.ok(s.stats.bossDamage>0);}});
test('New record reader validates input namespaces and ignores poisoned/malformed records',()=>{A.deepEqual(C.records('{bad'),{});A.deepEqual(C.records('{"__proto__":{"score":9,"wins":1}}'),{});A.deepEqual(C.records('{"duck-armada/gamepad/arcade":{"score":44,"wins":2}}'),{'duck-armada/gamepad/arcade':{score:44,wins:2}});A.notEqual(C.KEY,'prism-current.v1.records');});
