/* Component lifecycle fixtures. Browser acceptance still uses real input/UI. */
const {test}=require('node:test'),A=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('../river/core');
function definition(){let d;const c={RiverCore:C,document:{getElementById:()=>({focus(){}})},AFRAME:{registerComponent:(n,v)=>d=v},console};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../river/app.js','utf8'),c);return d;}
test('Pause releases pointer captures before allowing a modal interaction',()=>{const d=definition(),released=[],el={hasPointerCapture:id=>id===7,releasePointerCapture:id=>released.push(id)},s=C.create(),g={...d,phase:'playing',state:s,audio:{pause(){}},captures:new Map([[el,7]]),keys:new Set(['KeyR']),art:{weapon(){}},notice(){},sync(){},focus(){}};s.mode='playing';g.pauseRun('Paused');A.deepEqual(released,[7]);A.equal(g.captures.size,0);A.equal(g.phase,'paused');A.equal(g.state.mode,'paused');A.equal(g.mouse,null);A.equal(g.keys.size,0);});
test('A detached capture target cannot prevent safe pause and input reset',()=>{const d=definition(),el={hasPointerCapture(){throw Error('Detached pointer')}};const g={...d,captures:new Map([[el,1]]),keys:new Set(),art:{weapon(){}}};A.doesNotThrow(()=>g.clearInputs());A.equal(g.captures.size,0);});
test('Pending resume cannot revive an abandoned run',async()=>{const d=definition();let ready;const g={...d,phase:'paused',state:C.create(),serial:3,busy:false,immersive:false,audio:{offset:2,play:()=>new Promise(r=>ready=r)},sync(){},notice(){}};const p=g.resume();g.serial++;g.phase='menu';g.state=null;ready(true);await p;A.equal(g.phase,'menu');A.equal(g.state,null);});
test('XR combat rays originate at the visible blade tip and share its axis',()=>{const s=fs.readFileSync(__dirname+'/../river/xr.js','utf8');A.match(s,/normal=b\.clone\(\)\.sub\(a\)\.normalize\(\)/);A.match(s,/origin:b\.toArray\(\),direction:normal\.toArray\(\)/);});
test('A clear is keyed by the battle configuration, not changed menu preferences',()=>{const d=definition(),s=C.create('mothership',true);s.mode='complete';s.score=1337;s.bossDefeated=true;const g={...d,state:s,phase:'playing',chapter:'duck-armada',cruise:false,runMode:'vr',audio:{stop(){}},records:{},clearInputs(){},notice(){},sync(){},focus(){}};g.finish();A.equal(g.records['mothership/vr/easy/cruise'].score,1337);A.equal(g.records['duck-armada/vr/easy/arcade'],undefined);});
test('Changing XR difficulty abandons the old run rather than relabeling it',()=>{const s=fs.readFileSync(__dirname+'/../river/xr.js','utf8');A.match(s,/if\(i===7\)\{g.cruise=!g.cruise;g.cancel\(\)/);const app=fs.readFileSync(__dirname+'/../river/app.js','utf8');A.match(app,/if\(edge\[3\]&&this.phase==='menu'\)/);});
test('Rendered blade length follows its actual swept endpoints',()=>{const s=fs.readFileSync(__dirname+'/../river/art.js','utf8');A.match(s,/reach=d.length\(\)/);A.match(s,/w.blade.position.z=-\(reach\+\.06\)\/2/);A.match(s,/w.blade.scale.z=Math.max\(\.01,reach-\.06\)/);for(const reach of [.70,.72,1.25])A.ok(Math.abs(-(reach+.06)/2-(reach-.06)/2+reach)<1e-12);});
