const {test}=require('node:test'),A=require('node:assert/strict'),S=require('../graphics/spectral');
test('Malformed or future preferences choose bounded defaults',()=>{for(const x of ['{bad','null','[]','{"theme":"unknown"}'])A.deepEqual(S.preference(x),{theme:'opal',reactive:true});A.deepEqual(S.preference('{"theme":"solar","reactive":false}'),{theme:'solar',reactive:false});});
for(const name of ['classic','light','zero','AR/VR'])test(name+' explicitly excludes all new shader draws',()=>{const p=S.policy(name==='classic'?'classic':'opal',name==='light'?'light':'cinematic',name==='zero'?0:1,false,name==='AR/VR',true);A.equal(p.enabled,false);A.equal(p.reactions,false);});
test('Quiet mode retains still art without animation or hit ripples',()=>{A.deepEqual(S.policy('solar','balanced',.72,true,false,true),{enabled:true,motion:false,reactions:false});});
test('Ambient-only keeps motion but not hit reactions',()=>{A.deepEqual(S.policy('abyss','cinematic',1,false,false,false),{enabled:true,motion:true,reactions:false});});
test('The uniform impact pool remains six slots under sustained input',()=>{const p=new S.ImpactPool(),slots=p.items.slice();for(let i=0;i<1000;i++)p.add(i%2,[.2,1,-1.05],i*.07);A.equal(p.items.length,6);A.ok(slots.every((v,i)=>p.items[i]===v));A.equal(p.count,1000);A.ok(p.active(69.93)<=6);});
test('Invalid input and rapid repeat cannot allocate fake ripples',()=>{const p=new S.ImpactPool();A.equal(p.add(0,[0,1,-1],0),true);A.equal(p.add(1,[0,1,-1],.01),false);A.equal(p.add(9,[0,1,-1],1),false);A.equal(p.add(0,[NaN,1,-1],1),false);A.equal(p.count,1);});
test('Impacts expire and clearing a session prevents old reactions returning',()=>{const p=new S.ImpactPool();p.add(0,[10,1,-99],1);A.equal(p.items[0].x,3);A.equal(p.items[0].z,-10);A.equal(p.active(1.5),1);A.equal(p.active(2.26),0);p.clear();A.equal(p.count,0);A.equal(p.active(1.5),0);});
test('New shader programs have no sampled screen or camera textures',()=>{for(const code of Object.values(S.shaders))A.doesNotMatch(code,/sampler|texture2D|gl_FragCoord/);A.match(S.shaders.ground,/i<6/);A.match(S.shaders.coreFragment,/colorspace_fragment/);});
function fixture(){let freed=0,draws=0;const nodes=new Map();function node(value){return {value,checked:true,textContent:'',addEventListener(){},removeEventListener(){}};}nodes.set('spectral-theme',node('opal'));nodes.set('spectral-reactive',node(''));nodes.set('spectral-status',node(''));
 global.document={readyState:'complete',getElementById:id=>nodes.get(id),removeEventListener(){}};
 const store=new Map([['prism-current.v1.records','legacy']]);global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};
 class V{set(...a){this.values=a;return this;}}class Color{constructor(c){this.c=c;}getHex(){return this.c;}}
 class Group{constructor(){this.children=[];this.visible=true;}add(...a){for(const o of a){this.children.push(o);o.parent=this;}}traverse(fn){fn(this);for(const o of this.children)o.traverse?o.traverse(fn):fn(o);}removeFromParent(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=null;}}
 class Mesh extends Group{constructor(geometry,material){super();this.isMesh=true;this.geometry=geometry;this.material=material;this.position=new V();this.rotation={};this.scale=new V();}}
 class Material{constructor(p){Object.assign(this,p);}dispose(){freed++;}}
 class Geometry{dispose(){freed++;}}
 const T={Group,Mesh,ShaderMaterial:Material,PlaneGeometry:Geometry,Vector4:V,Color},group=new Group(),studio=new Group(),geo={},original={color:new Color(0x63eddd)},heart=new Mesh(geo,original);group.add(heart);const aurora=new Mesh({},{});studio.add(aurora);
 const art={T,group,studio,fx:{aurora:aurora.material,state:{quality:'cinematic',intensity:.72,reduced:false,immersive:false}},notes:[{heart}],colors:[0x63eddd,0xff839d],update(){draws++;heart.material=original;},burst(){},dispose(){}};
 const s=S.install(art,{});return {s,art,heart,original,aurora,store,nodes,get freed(){return freed},get draws(){return draws}};}
test('Installation uses three shared-geometry planes and no render targets',()=>{const f=fixture();A.equal(f.s.group.children.length,3);A.ok(f.s.group.children.every(x=>x.geometry===f.s.group.children[0].geometry));A.equal(f.s.status.extraRenderTargets,0);A.equal(f.s.materials.length,5);});
test('All background materials keep depth tests and never write opaque depth',()=>{const f=fixture();for(const m of f.s.materials.slice(0,3)){A.equal(m.transparent,true);A.equal(m.depthTest,true);A.equal(m.depthWrite,false);}});
test('Pause and quiet do not advance spectral motion',()=>{const f=fixture(),song={state:'playing',song:{bpm:104}};f.art.update(song,1,.016,false);const time=f.s.uniforms.uTime.value;song.state='paused';f.art.update(song,1,.016,false);A.equal(f.s.uniforms.uTime.value,time);f.art.fx.state.reduced=true;f.art.update(song,1,.016,false);A.equal(f.s.uniforms.uTime.value,0);A.equal(f.s.status.reactions,false);});
test('Real hit hook writes bounded floor coordinates and run changes clear them',()=>{const f=fixture(),song={state:'playing',song:{bpm:104}};f.art.update(song,1,.016,false);f.art.burst({hand:1},[.4,1.4,-1.05]);f.art.update(song,1.016,.016,false);A.equal(f.s.status.activeRipples,1);A.deepEqual(f.s.uniforms.uImpacts.value[0].values.slice(0,2),[.4,-5.95]);f.art.update(null,2,.016,true);A.equal(f.s.status.activeRipples,0);A.equal(f.store.get('prism-current.v1.records'),'legacy');});
test('Headset transition restores original cores and hides the new planes',()=>{const f=fixture(),song={state:'playing',song:{bpm:104}};f.art.update(song,1,.016,false);A.equal(f.heart.material,f.s.cores[0]);f.art.fx.state.immersive=true;f.art.update(song,1,.016,false);A.equal(f.s.group.visible,false);A.equal(f.heart.material,f.original);A.equal(f.aurora.visible,true);});
test('Disposal is idempotent and frees five materials and one shared geometry',()=>{const f=fixture();f.s.dispose();f.s.dispose();A.equal(f.freed,6);A.equal(f.s.status.disposed,true);A.equal(f.s.group.parent,null);});
