/* Content, telemetry and golden legacy regressions; not human reach tests. */
const {test}=require('node:test'),A=require('node:assert/strict'),crypto=require('node:crypto');
const C=require('../core'),M=require('../music'),T=require('../tidal-bloom'),P=require('../phrases'),legacy=require('./legacy-v030.json');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
test('Tidal Bloom has eight contiguous sections and a two-minute bounded arrangement',()=>{const s=C.chart('tidal-bloom');A.equal(s.sections.length,8);A.equal(s.sections[0].start,0);A.equal(s.sections.at(-1).end,s.duration);A.ok(s.duration>110&&s.duration<125);for(let i=1;i<s.sections.length;i++)A.equal(s.sections[i-1].end,s.sections[i].start);});
test('New charts are deterministic, mirrored by hand role and keep authored recovery gaps',()=>{for(const d of ['flow','pulse']){const c=T.chart(d);A.deepEqual(c,T.chart(d));A.ok(c.notes.every(n=>n.hand===(n.lane<2?0:1)));A.ok(c.notes.every(n=>n.row>=0&&n.row<=1&&n.dir>=0&&n.dir<=6));const rest=c.sections.find(p=>p.id==='stillwater');A.ok(!c.notes.some(n=>n.time>=rest.start&&n.time<rest.start+8*60/c.bpm));for(const h of [0,1]){const a=c.notes.filter(n=>n.hand===h);for(let i=1;i<a.length;i++)A.ok(a[i].time-a[i-1].time>=.5,'Same-hand recovery spacing');}for(let i=1;i<c.notes.length;i++)A.ok(c.notes[i].time>c.notes[i-1].time);}});
test('Authored Flow and Pulse have distinct density and Pulse has directional vocabulary',()=>{const f=T.chart('flow'),p=T.chart('pulse');A.ok(p.notes.length>f.notes.length*1.4);A.ok(new Set(p.notes.map(n=>n.dir)).size>=5);});
test('Arrangement contains returning melody and a real percussion-free breathing passage',()=>{const ev=T.events();A.ok(ev.length>500);A.ok(ev.every(e=>Number.isFinite(e.pitch)&&e.beat>=0&&e.beat<228&&e.duration>0&&e.velocity>0&&e.velocity<=1&&Math.abs(e.pan)<=1));A.ok(!ev.some(e=>['kick','snare','hat'].includes(e.part)&&e.beat>=112&&e.beat<144));for(const part of ['felt','glass','string','bass','kick','snare','hat'])A.ok(ev.some(e=>e.part===part));A.deepEqual(ev,T.events());});
test('Section lookup handles boundaries and legacy track phrases',()=>{const c=T.chart('flow');A.equal(P.current(c,0).id,'arrival');A.equal(P.current(c,c.sections[1].start).id,'glasswater');A.equal(P.current(c,c.duration).id,'release');const old=C.chart();A.equal(P.sections(old).at(-1).end,old.duration);});
test('Button timing is measured, not invented for misses; statistics reconcile',()=>{const c=T.chart('flow'),s=C.create(c,{mode:'keys'});s.state='playing';const n=c.notes[0];C.advance(s,n.time-.08);C.tap(s,n.lane,n.time-.06);C.advance(s,c.duration);const r=P.summary(s);A.equal(r.samples,1);A.equal(r.early,1);A.equal(r.centered,0);A.equal(r.late,0);A.ok(Math.abs(r.meanOffset+60)<1e-8);A.equal(r.sections.reduce((a,p)=>a+p.hits,0),s.hits);A.equal(r.sections.reduce((a,p)=>a+p.misses,0),s.misses);A.equal(Object.keys(s.judgmentDetails).length,c.notes.length);A.ok(Object.values(s.judgmentDetails).filter(d=>d.type==='miss').every(d=>d.offsetMs===null));});
test('Blade timing describes sampled contact and never changes quality scoring',()=>{const n={id:0,time:1,lane:1,row:0,hand:0,dir:0};const s=C.create({...C.chart(),notes:[n],duration:2});s.state='playing';C.advance(s,1);const p=C.position(n,1),pose=y=>({a:[p[0],p[1]+y,p[2]+.25],b:[p[0],p[1]+y,p[2]-.2]});C.slice(s,0,pose(.16),pose(-.16),.98,1.02);A.equal(s.hits,1);A.ok(Number.isFinite(s.judgmentDetails[0].offsetMs));A.equal(P.summary(s).samples,1);});
test('All-miss results have no false timing precision',()=>{const s=C.create(T.chart('flow'),{mode:'keys'});s.state='playing';C.advance(s,s.song.duration);const r=P.summary(s);A.equal(r.samples,0);A.equal(r.meanAbsolute,null);A.equal(r.meanOffset,null);A.ok(r.sections.filter(p=>p.notes).every(p=>p.accuracy===0));});
test('Read-only feedback does not mutate scores or judgments',()=>{const s=C.create(T.chart('pulse'));s.state='playing';C.advance(s,s.song.duration);const before=JSON.stringify(s);P.summary(s);P.sections(s.song);P.current(s.song,12);A.equal(JSON.stringify(s),before);});
for(const [k,expected]of Object.entries(legacy.charts))test('v0.3 chart and perfect-score regression: '+k,()=>{const [id,d]=k.split('/'),c=C.chart(id,d);A.equal(hash(JSON.stringify(c.notes)),expected.notes);A.equal(c.duration,expected.duration);const s=C.create(c,{mode:'keys'});s.state='playing';for(const n of c.notes){C.advance(s,n.time);C.tap(s,n.lane,n.time);}C.advance(s,c.duration);A.deepEqual(C.result(s),expected.result);});
for(const [id,expected] of Object.entries(legacy.audio))test('v0.3 audio buffers stay byte-identical: '+id,()=>{const r=M.render(C.chart(id),expected.rate);A.equal(hash(Buffer.from(r.left.buffer)),expected.left);A.equal(hash(Buffer.from(r.right.buffer)),expected.right);});
test('New soundtrack keeps output headroom, stereo detail and a silent final sample',()=>{const s=C.chart('tidal-bloom'),r=M.render(s,24000);A.ok(r.peak>.15&&r.peak<=.78);A.ok(r.rms>.025&&r.rms<.3);A.ok(r.left.every(Number.isFinite));A.ok(r.right.every(Number.isFinite));A.equal(r.left.at(-1),0);A.equal(r.right.at(-1),0);A.ok(r.left.some((v,i)=>Math.abs(v-r.right[i])>.002));});
