const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),C=require('../core'),U=require('../undertow'),M=require('../music');
const path=require('node:path');
for(const d of ['flow','pulse']){
 test('Undertow '+d+' has eight actual directions and no directionless notes',()=>{const c=C.chart('undertow',d);A.equal(c.notes.length,d==='flow'?164:286);A.equal(new Set(c.notes.map(n=>n.dir)).size,8);A.ok(c.notes.every(n=>n.dir!==6&&C.dirs[n.dir]));A.deepEqual(c,U.chart(d));A.ok(c.notes[0].time>=4*60/c.bpm);A.ok(c.notes[0].time<2);});
 test('Undertow '+d+' alternates hands, leaves return time and preserves hand sides',()=>{const c=U.chart(d);for(let i=1;i<c.notes.length;i++){A.notEqual(c.notes[i].hand,c.notes[i-1].hand);A.ok(c.notes[i].time>c.notes[i-1].time);}for(const hand of[0,1]){const a=c.notes.filter(n=>n.hand===hand);for(let i=1;i<a.length;i++)A.ok(a[i].time-a[i-1].time>=.45-1e-8);A.ok(a.every(n=>(n.lane<2?0:1)===hand));}});
 test('Undertow '+d+' completes with real correct-direction slices, including new upward diagonals',()=>{const song=U.chart(d),s=C.create(song,{mode:'slice'});s.state='playing';for(const n of song.notes){C.advance(s,n.time);const p=C.position(n,n.time),v=C.dirs[n.dir],pose=f=>({a:[p[0]+v[0]*f,p[1]+v[1]*f,p[2]+.15],b:[p[0]+v[0]*f,p[1]+v[1]*f,p[2]-.18]});const e=C.slice(s,n.hand,pose(-.07),pose(.07),n.time-.025,n.time+.025);A.equal(e[0]?.type,'hit','note '+n.id+' dir '+n.dir);}C.advance(s,song.duration);A.equal(s.hits,song.notes.length);A.equal(s.bad,0);A.equal(C.result(s).complete,true);});
}
test('New upward diagonals reject reversed or wrong-hand strokes',()=>{for(const dir of[7,8])for(const wrong of ['direction','hand']){const n={id:0,lane:1,row:0,hand:0,dir,time:1},s=C.create({...U.chart(),notes:[n],duration:2});s.state='playing';C.advance(s,1);const p=C.position(n,1),v=C.dirs[dir],pose=f=>({a:[p[0]+v[0]*f,p[1]+v[1]*f,p[2]+.1],b:[p[0]+v[0]*f,p[1]+v[1]*f,p[2]-.2]});const sign=wrong==='direction'?-1:1;C.slice(s,wrong==='hand'?1:0,pose(-.07*sign),pose(.07*sign),.975,1.025);A.equal(s.judged[0],'bad');}});
test('New score has drums, separate bass, harmony, hook, returns and sparse passages',()=>{const ev=U.events();for(const part of['kick','snare','clap','hat','bass','pad','chord','lead','arp','riser'])A.ok(ev.some(e=>e.part===part));A.ok(ev.every(e=>e.beat>=0&&e.beat<196&&e.duration>0&&e.velocity<=1));const busy=ev.filter(e=>e.beat>=64&&e.beat<96),quiet=ev.filter(e=>e.beat>=96&&e.beat<112);A.ok(busy.length/32>quiet.length/16);A.equal(U.sections().length,8);});
test('Full original Undertow render is finite, stereo, unclipped and ends at zero',()=>{const r=M.render(C.chart('undertow'),24000);A.ok(r.peak>.4&&r.peak<.78);A.ok(r.rms>.09&&r.rms<.25);A.equal(r.left.length,Math.ceil(U.chart().duration*24000));A.ok(r.left.every(Number.isFinite));A.ok(r.right.every(Number.isFinite));A.ok(r.left.some((v,i)=>Math.abs(v-r.right[i])>.01));A.equal(r.left.at(-1),0);A.equal(r.right.at(-1),0);});
test('Current app uses new content at startup and loads cached worker under a new URL',()=>{const base=path.join(__dirname,'..'),app=fs.readFileSync(path.join(base,'app.js'),'utf8'),html=fs.readFileSync(path.join(base,'index.html'),'utf8');A.match(app,/this.track='undertow';this.difficulty='pulse'/);A.match(html,/undertow.js\?v=0.9.0/);A.match(fs.readFileSync(path.join(base,'audio.js'),'utf8'),/music-worker.js\?v=0.9.0/);A.match(fs.readFileSync(path.join(base,'art.js'),'utf8'),/length:PrismCore.dirs.length/);});
test('New stage writes neither scores nor device data and excludes opaque AR',()=>{const s=fs.readFileSync(path.join(__dirname,'../graphics/pool-stage.js'),'utf8');A.doesNotMatch(s,/localStorage|createRenderTarget|new T.WebGLRenderTarget/);A.match(s,/selected&&!ar/);A.match(s,/art.group.position/);});
