const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../water-mission/core');
function go(s,x,z){let n=0;while(Math.hypot(x-s.player.x,z-s.player.z)>.16&&n++<6000){C.look(s,Math.atan2(-(x-s.player.x),-(z-s.player.z))-s.player.yaw,0);C.move(s,{forward:1},.025);}A.ok(n<6000,`Path blocked toward ${x},${z}: ${JSON.stringify(s.player)}`);}
test('The full mission is traversable by movement and interactions, including the submerged return',()=>{const s=C.create();s.mode='playing';go(s,5.4,1.2);A.equal(C.near(s).id,'power');A.ok(C.interact(s));go(s,0,-2);go(s,-5.7,-2.4);A.ok(C.interact(s));A.equal(s.stage,2);go(s,-4,-2.4);go(s,-4,-8);go(s,0,-12);go(s,0,-23);for(let i=0;i<48;i++)C.move(s,{down:1},.025);A.ok(s.player.y< -2.2);go(s,0,-37.5);A.ok(C.interact(s));A.equal(s.stage,3);go(s,0,-25);for(let i=0;i<60;i++)C.move(s,{up:1},.025);go(s,0,-12);go(s,-4,-8);go(s,-4,-2);go(s,2.5,3.7);A.ok(C.interact(s));A.equal(s.stage,4);A.equal(s.mode,'complete');A.equal(s.rescues,0);A.ok(s.elapsed>30);});
test('Empty input does not move the player',()=>{const s=C.create();s.mode='playing';C.move(s,{},.05);A.equal(s.player.x,0);A.equal(s.player.z,3);});
test('Gate cannot be bypassed without restoring power and drainage',()=>{const s=C.create();s.mode='playing';s.player={x:0,y:.15,z:-14,yaw:0,pitch:0};for(let i=0;i<500;i++)C.move(s,{forward:1},.02);A.ok(s.player.z>=-14.4);A.equal(C.interact(s),false);A.equal(s.stage,0);});
test('Submerged tunnel requires a real dive instead of surface traversal',()=>{const s=C.create('{"version":1,"stage":2}');s.mode='playing';go(s,0,-30);for(let i=0;i<100;i++)C.move(s,{forward:1},.02);A.ok(s.player.z> -31);});
test('Air loss returns safely without losing recovered objectives',()=>{const s=C.create('{"version":1,"stage":3}');s.mode='playing';s.player.y=-3;s.diving=true;s.oxygen=.02;C.move(s,{},.03);A.equal(s.stage,3);A.equal(s.rescues,1);A.equal(s.oxygen,32);A.ok(s.player.y>s.water);});
test('Pause freezes water, movement and oxygen',()=>{const s=C.create('{"version":1,"stage":2}');s.mode='paused';const prior=JSON.stringify(s);C.move(s,{forward:1,down:1},.05);A.equal(JSON.stringify(s),prior);});
test('Malformed saves and arbitrary coordinates cannot inject progress',()=>{for(const x of ['{bad','{"version":1,"stage":99}','{"version":2,"stage":3}','[]'])A.equal(C.create(x).stage,0);const s=C.create('{"version":1,"stage":2,"player":{"x":9000}}');A.equal(s.player.x,0);A.notEqual(C.KEY,'prism-current.v1.records');});
test('Bounds, view pitch and delta time remain bounded',()=>{const s=C.create();s.mode='playing';C.look(s,NaN,100);C.move(s,{side:Infinity},5000);A.equal(s.player.pitch,1.35);A.equal(s.player.x,0);A.equal(s.elapsed,.05);A.equal(C.inside(100,100),false);});
test('Ladder exits the basin while preserving the mission stage',()=>{const s=C.create('{"version":1,"stage":2}');s.mode='playing';s.player={x:4.7,y:.15,z:-3.9,yaw:0,pitch:0};A.equal(C.near(s).id,'ladder');C.interact(s);A.equal(s.player.y,1.65);A.equal(s.stage,2);});
