'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,p),'utf8'),data=JSON.parse(read('register.json'));
const sources=new Set(data.sources.map(s=>s.id)),ids=[...data.claims,...data.forecasts,...data.research_leads].map(r=>r.id);
test('follow-up has explicit source, claim, forecast and research counts',()=>{assert.equal(data.schema_version,1);assert.equal(data.sources.length,25);assert.equal(data.claims.length,9);assert.equal(data.forecasts.length,8);assert.equal(data.research_leads.length,4);assert.equal(new Set(ids).size,ids.length);});
test('all citations and secure links resolve',()=>{for(const r of [...data.claims,...data.forecasts,...data.research_leads])for(const id of r.source_ids)assert.ok(sources.has(id));for(const s of data.sources){assert.equal(new URL(s.url).protocol,'https:');assert.ok(s.access_scope.length>20);assert.equal(s.accessed,'2026-09-18');}});
test('institutional forecasts remain distinct from four new scenarios',()=>{const existing=data.forecasts.filter(f=>f.originator!=='Wiki research follow-up');assert.equal(existing.length,4);assert.equal(data.forecasts.length-existing.length,4);for(const f of data.forecasts){assert.equal(f.first_logged,'2026-09-18');assert.ok(f.original_issued<=f.first_logged);assert.ok(f.window_start<=f.window_end);assert.equal(f.outcome_status,'unassessed');assert.equal(f.theological_onset_date,null);for(const k of ['geography','forecast','assumptions_or_trigger','verification','qualification_or_alternative'])assert.ok(f[k].length>20);}});
test('no adoption or unique prophetic identity is silently inferred',()=>{assert.match(data.claims.find(c=>c.id==='gaza-coins').scope,/No official launch/);assert.match(data.claims.find(c=>c.id==='freedom-cities').scope,/speculative/);assert.match(data.claims.find(c=>c.id==='online-reception').scope,/not their truth/);assert.match(data.sources.find(s=>s.id==='hodayot').access_scope,/abstract only/);assert.deepEqual(data.assessments,[]);});
test('prior articles and original scenario notebook retain pinned bytes',()=>{for(const [file,digest]of Object.entries(data.preserved_prior_sha256)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',file))).digest('hex'),digest,file);}});
test('all inherited wiki route links have valid syntax',()=>{for(const r of [...data.claims,...data.research_leads])for(const link of r.wiki_links||[])assert.match(link,/^\.\.\/\.\.\/(san-reader\.html\?page=[a-z0-9-]+|scripture-concordance\/index\.html#[a-z0-9-]+)$/);});
test('reader parses and inserts source data as text with fallbacks',()=>{const html=read('index.html'),js=read('reader.js');assert.doesNotThrow(()=>new vm.Script(js));assert.match(js,/textContent/);assert.doesNotMatch(js,/innerHTML|eval\(|localStorage/);assert.match(html,/<noscript>/);assert.match(html,/href="register.json"/);assert.match(html,/role="status"/);assert.match(read('../reader.js'),/board-peace-followup\/index.html/);});

const indexPath=path.join(__dirname,'../../data/page-index.json');
if(process.env.INTEGRATED==='1')assert.ok(fs.existsSync(indexPath),'Main page index is required in integration testing');
test('actual main Wiki destinations resolve when running in the full repository',{skip:!fs.existsSync(indexPath)},()=>{const slugs=new Set(JSON.parse(fs.readFileSync(indexPath,'utf8')).map(p=>p.slug));for(const r of [...data.claims,...data.research_leads])for(const u of r.wiki_links||[]){const m=u.match(/san-reader\.html\?page=([a-z0-9-]+)/);if(m)assert.ok(slugs.has(m[1]),u);}});
