const {test}=require('node:test'),assert=require('node:assert/strict');const C=require('../core.js');global.VesperCore=C;const I=require('../input.js');
function step(s,n=400){for(let i=0;i<n;i++)C.step(s,1/90);}
test('Seeded layouts are deterministic, different across seeds, and change with sector',()=>{assert.deepEqual(C.generate('A',1),C.generate('A',1));assert.notDeepEqual(C.generate('A',1).edges,C.generate('B',1).edges);assert.notDeepEqual(C.generate('A',1).edges,C.generate('A',2).edges);});
test('100 procedural seeds have a connected graph, clear doorway crossings, reachable exit and walkable spawns',()=>{for(let i=0;i<100;i++){const w=C.generate('CLOISTER-'+i);assert.equal(w.rooms.length,9);assert.equal(w.edges.length,10);assert.equal(w.enemies.length,5);for(const r of w.rooms){assert.ok(C.route(w,1,r.id).length);assert.ok(C.walkable(w,[r.x,0,r.z]));}for(const [a,b]of w.edges){const p=w.rooms[a],q=w.rooms[b];for(let k=0;k<=40;k++)assert.ok(C.walkable(w,[p.x+(q.x-p.x)*k/40,0,p.z+(q.z-p.z)*k/40]),`${i} ${a}-${b} step ${k}`);}assert.ok(C.walkable(w,w.start));}});
test('Movement respects real wall collision and does not jump the gap between rooms',()=>{const s=C.create('BELL-01');for(let i=0;i<100;i++)C.move(s,.1,.1);assert.ok(C.walkable(s.world,s.p));const before=[...s.p];C.move(s,Infinity,0);assert.deepEqual(s.p,before);assert.equal(C.walkable(s.world,[10,0,10]),false);});
test('Swept arrows cannot tunnel through a thin occluder to hit an enemy behind it',()=>{const s=C.create('A');s.world.enemies=[{id:1,p:[0,1.6,-4],hp:70,maxHp:70,dead:false,aware:false,kind:'cantor',speed:0,cd:99}];s.world.solids=[{min:[-1,0,-2.1],max:[1,3,-2]}];C.fire(s,[0,1.65,2.8],[0,0,-1],1);step(s,50);assert.equal(s.kills,0);assert.equal(s.world.enemies[0].hp,70);});
test('Real arrow speed and damage increase with physical draw strength',()=>{const a=C.create('a'),b=C.create('a');C.fire(a,[0,1.65,2.8],[0,0,-1],.2);C.fire(b,[0,1.65,2.8],[0,0,-1],1);assert.ok(C.len(a.arrows[0].v)<C.len(b.arrows[0].v));assert.ok(a.arrows[0].damage<b.arrows[0].damage);});
test('A swept physical shot hits and kills a real target; kills cannot be counted twice',()=>{const s=C.create('a');s.world.solids=[];s.world.enemies=[{id:0,p:[0,1.05,-1],hp:70,maxHp:70,dead:false,kind:'cantor',speed:0,cd:99}];const dir=C.unit([0,-.25,-4]);assert.ok(C.fire(s,[0,1.65,2.8],dir,1));step(s,30);assert.equal(s.kills,1);assert.equal(s.hits,1);assert.ok(s.portalReady);step(s,30);assert.equal(s.kills,1);});
test('Special arrows consume finite ammo; misses do not restore ammunition',()=>{const s=C.create('a');const start=s.ammo.cinder;for(let i=0;i<start;i++)assert.ok(C.fire(s,[0,1.65,2.8],[0,0,-1],1,'cinder'));assert.equal(C.fire(s,[0,1.65,2.8],[0,0,-1],1,'cinder'),false);assert.equal(s.ammo.cinder,0);});
test('Invalid shots never create nonfinite projectiles',()=>{const s=C.create('a');for(const q of[NaN,Infinity,-1,.01])assert.equal(C.fire(s,[0,1.65,2.8],[0,0,-1],q),false);assert.equal(C.fire(s,[0,0],[0,0,-1],1),false);assert.equal(C.fire(s,[0,1,0],[0,0,-12],1),false);assert.equal(s.arrows.length,0);});
test('Blink travel requires an unobstructed actual floor, not empty space or a warden body',()=>{const s=C.create('a');assert.equal(C.blink(s,[10,0,10]),false);const e=s.world.enemies[0];assert.equal(C.blink(s,e.p),false);assert.equal(C.blink(s,[1,0,1]),true);assert.deepEqual(s.p,[1,0,1]);});
test('Blink is a projectile landing and cannot teleport through the wall it hits',()=>{const s=C.create('a');s.world.solids=[{min:[-1,0,-.2],max:[1,3,0]}];const before=[...s.p];C.fire(s,[0,1.65,2.8],C.unit([0,-.1,-1]),.5,'blink');step(s,100);assert.deepEqual(s.p,before);assert.ok(!s.events.some(e=>e.type==='blink'));});
test('A physical dodge or cover can avoid a bolt; damage uses actual head position',()=>{const s=C.create('a');s.world.enemies=[];s.world.solids=[];s.bolts=[{p:[-1,1.65,3],v:[8,0,0],life:1}];for(let i=0;i<30;i++)C.step(s,1/90,[0,.7,3]);assert.equal(s.health,100);s.bolts=[{p:[-1,.7,3],v:[8,0,0],life:1}];for(let i=0;i<30;i++)C.step(s,1/90,[0,.7,3]);assert.equal(s.health,88);});
test('Gate needs defeated wardens and proximity; one blessing creates a fresh seed-derived next sector',()=>{let s=C.create('a');const r=s.world.rooms[s.world.exit];s.p=[r.x,0,r.z-3.8];assert.equal(C.interact(s),false);s.world.enemies.forEach(e=>e.dead=true);C.step(s,1/90);assert.equal(C.interact(s),true);const old=s.world.edges;s=C.reward(s,'power');assert.equal(s.world.depth,2);assert.equal(s.power,1.12);assert.notDeepEqual(s.world.edges,old);assert.equal(s.phase,'playing');assert.equal(C.reward(s,'power'),null);});
test('Bow arms only after neutral, requires close nock, and releases the actual drawn vector',()=>{const b=new I.BowLatch();assert.equal(b.update([0,1,-.5],[0,1,.1],true).drawing,false);b.update([0,1,-.5],[0,1,-.45],false);assert.ok(b.update([0,1,-.5],[0,1,-.45],true).drawing);b.update([0,1,-.5],[0,1,.1],true);const r=b.update([0,1,-.5],[0,1,.1],false);assert.ok(r.shot.charge>.9);assert.deepEqual(r.shot.direction,[0,0,-1]);});
test('Tracking loss, pause and overextension cancel a pull instead of firing',()=>{for(const cause of['tracking','pause','stretch']){const b=new I.BowLatch();b.update([0,1,0],[0,1,.1],false);b.update([0,1,0],[0,1,.1],true);b.update([0,1,0],[0,1,.5],true);if(cause==='tracking')b.update(null,null,true);if(cause==='pause')b.update([0,1,0],[0,1,.5],true,false);if(cause==='stretch')b.update([0,1,0],[0,1,2],true);assert.equal(b.update([0,1,0],[0,1,.5],false).shot,null);}});
test('A trigger pressed away from the string cannot magically nock a distant arrow',()=>{const b=new I.BowLatch();b.update([0,0,0],[0,0,.5],false);assert.equal(b.update([0,0,0],[0,0,.5],true).drawing,false);assert.equal(b.update([0,0,0],[0,0,.6],false).shot,null);});
test('Shorter calibrated draw reduces reach without changing the aiming vector',()=>{const short=C.drawState([0,1,-.5],[0,1,0],.4),long=C.drawState([0,1,-.5],[0,1,0],.7);assert.ok(short.charge>long.charge);assert.deepEqual(short.direction,long.direction);});
test('Profile accepts only bounded local progression, not arbitrary fields',()=>{const p=I.cleanProfile({shards:Infinity,best:-5,depth:300,heart:'true',power:true,private:'ignored'});assert.equal(p.shards,100000);assert.equal(p.best,0);assert.equal(p.depth,99);assert.equal(p.heart,false);assert.equal(p.power,true);assert.equal(p.private,undefined);});

test('Beacon interaction opens the reward menu immediately, without another playing tick',()=>{
 const fs=require('node:fs'),vm=require('node:vm');let component;
 const context={VesperCore:C,VesperInput:I,AFRAME:{registerComponent(n,d){component=d;}},document:{getElementById(){return null;}},window:{addEventListener(){}}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),context);
 const game=C.create('BEACON');game.kills=5;game.portalReady=true;game.score=700;const gate=game.world.rooms[game.world.exit];game.p=[gate.x,0,gate.z-3.8];
 let saves=0,opened=0;
 const owner={game,practice:false,banked:0,profile:I.cleanProfile({}),lastPhase:'playing',bank:component.bank,profileSave(){saves++;},setPaused(v){assert.equal(v,true);opened++;this.paused=true;},toast(){}};
 component.interact.call(owner);assert.equal(game.phase,'reward');assert.equal(owner.lastPhase,'reward');assert.equal(owner.paused,true);assert.equal(owner.profile.shards,5);assert.equal(saves,1);assert.equal(opened,1);
 component.interact.call(owner);assert.equal(saves,1);assert.equal(opened,1);assert.equal(owner.profile.shards,5);
});
test('Practice and unopened beacons cannot enter or bank a reward',()=>{
 const fs=require('node:fs'),vm=require('node:vm');let component;
 const context={VesperCore:C,VesperInput:I,AFRAME:{registerComponent(n,d){component=d;}},document:{getElementById(){return null;}},window:{addEventListener(){}}};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),context);
 for(const practice of [true,false]){const game=C.create('NO-REWARD'),o={game,practice,toast(){},bank(){throw Error('Unexpected bank');},setPaused(){throw Error('Unexpected reward menu');}};component.interact.call(o);assert.equal(game.phase,'playing');}
});
