/* Adapter lifecycle fixtures use deliberately minimal scene/module collaborators.
 * They exercise production wiring, not Three/WebGL rendering or real XR. */
'use strict';
const test=require('node:test'),A=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const M=require('../currentworks-model'),C=require('../core'),Fire=require('../vendor/currentworks/fire');
class Vector{constructor(x=0,y=0,z=0){this.set(x,y,z);}set(x,y,z){Object.assign(this,{x,y,z});return this;}toArray(){return [this.x,this.y,this.z];}}
class Group{constructor(){this.children=[];this.position=new Vector();this.rotation={x:0};this.visible=true;}add(...items){for(const o of items){o.parent=this;this.children.push(o);}return this;}clear(){for(const o of this.children)o.parent=null;this.children=[];}removeFromParent(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=null;}}
class Resource{constructor(){this.disposals=0;}dispose(){this.disposals++;}}
class Material extends Resource{constructor(p){super();Object.assign(this,p);this.color={set:x=>{this.value=x;}};}}
class Mesh extends Group{constructor(geometry,material){super();this.geometry=geometry;this.material=material;}}
function fixture(options={}){const owned=[],canvas=new EventTarget(),T={Group,Scene:Group,Vector3:Vector,Mesh,MeshStandardMaterial:Material,TorusGeometry:Resource,OctahedronGeometry:Resource};
 const water={create(){const mesh=new Mesh(new Resource(),new Resource()),o={mesh,material:mesh.material,uniforms:{detail:{value:0}},stats:{},disposals:0,setQuality(q){this.stats.quality=q;},update(f){Object.assign(this.stats,f);mesh.visible=f.visible;},splash(){this.stats.splashes=(this.stats.splashes||0)+1;},reset(){this.stats.splashes=0;},dispose(){this.disposals++;}};owned.push(o);return o;}};
 const trees={create(){const o={group:new Group(),stats:{},disposals:0,prepare(){return options.pending||Promise.resolve();},update(f){Object.assign(this.stats,f);this.group.visible=f.visible;},reset(){},dispose(){this.disposals++;}};owned.push(o);return o;}};
 const fire={create(){const pool=new Fire.Pool(),o={group:new Group(),stats:{},disposals:0,prepare(){return options.fail?Promise.reject(Error('controlled shader failure')):Promise.resolve();},update(f){pool.update(f);Object.assign(this.stats,f);},emitter:(id,p)=>pool.emitter(id,p),emit:p=>pool.emit(p),stop:id=>pool.stop(id),reset:()=>pool.reset(),dispose(){this.disposals++;},pool};owned.push(o);return o;}};
 const g={T,game:C.create('BELL-01',1,{pilgrimage:{stage:0,tier:0}}),scene:{object3D:new Group(),camera:{},renderer:{domElement:canvas,compileAsync:()=>Promise.resolve()},components:{}},head:{object3D:{getWorldPosition(v){v.set(...g.game.head);return v;}}},threshold:{state:{phase:'game'}},tick(){},remove(){this.removed=true;}};
 const ctx={globalThis:null,module:{exports:{}},VesperCurrentworksModel:M,SVGNWater:water,SVGNTrees:trees,SVGNFire:fire,console:{warn(){}}};ctx.globalThis=ctx;vm.runInNewContext(fs.readFileSync(__dirname+'/../currentworks.js','utf8'),ctx);const api=ctx.module.exports.install(g);return {g,api,owned,canvas};}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
async function ready(f){f.g.tick();await settle();await settle();A.equal(f.api.state.ready,true);f.g.tick();}
test('Production adapter prepares once and repeated paused ticks never alter the complete simulation',async()=>{const f=fixture();await ready(f);const before=JSON.stringify(f.g.game),time=f.g.game.time;for(let i=0;i<30;i++)f.g.tick();A.equal(f.owned.length,5);A.equal(JSON.stringify(f.g.game),before);A.ok(f.api.water.every(w=>w.stats.time===time));A.ok(f.api.forests.every(w=>w.stats.time===time));A.equal(f.api.fire.stats.time,time);});
test('Late Tidelight initialization is wrapped, hidden only for supported chapters, and restored for legacy play',async()=>{const f=fixture();await ready(f);const t={root:{visible:true},current:{enabled:true},tick(){this.root.visible=this.current.enabled;}};f.g.scene.components.tidelight=f.g.tidelight=t;f.g.tick();t.tick();A.equal(t.root.visible,false);f.g.game=C.create('LEGACY');f.g.tick();t.tick();A.equal(t.root.visible,true);t.current.enabled=false;t.tick();A.equal(t.root.visible,false);});
test('AR and the foyer clear decorative ownership while retaining controller/game state',async()=>{const f=fixture();await ready(f);for(const kind of ['arMode','arExpedition','foyer']){if(kind==='foyer')f.g.threshold.state.phase='foyer';else f.g[kind]=true;const before=JSON.stringify(f.g.game);f.g.tick();A.equal(f.api.scene.visible,false);A.ok(f.api.water.every(w=>!w.mesh.visible));A.ok(f.api.forests.every(w=>!w.group.visible));A.equal(JSON.stringify(f.g.game),before);if(kind==='foyer')f.g.threshold.state.phase='game';else f.g[kind]=false;}f.g.tick();A.equal(f.api.scene.visible,true);});
test('Actual observer events are consumed once, excluded while hidden, and not replayed on return',async()=>{const f=fixture();await ready(f);const m=f.api.state.plan.modules[0];C.emit(f.g.game,'impact',{p:[m.x,0,m.z]});f.g.tick();A.equal(f.api.state.waterEvents,1);f.g.tick();A.equal(f.api.state.waterEvents,1);f.g.arMode=true;C.emit(f.g.game,'impact',{p:[m.x,0,m.z]});f.g.tick();f.g.arMode=false;f.g.tick();A.equal(f.api.state.waterEvents,1);});
test('Context loss releases owned objects, blocks re-preparation until restoration, and leaves simulation intact',async()=>{const f=fixture();await ready(f);const first=f.owned.slice(),before=JSON.stringify(f.g.game);f.canvas.dispatchEvent(new Event('webglcontextlost'));for(let i=0;i<3;i++)f.g.tick();A.ok(first.every(o=>o.disposals===1));A.equal(f.owned.length,5);A.equal(f.api.state.ready,false);f.canvas.dispatchEvent(new Event('webglcontextrestored'));await ready(f);A.equal(f.owned.length,10);A.equal(JSON.stringify(f.g.game),before);});
test('A failed graphics preparation falls back without repeated allocations or a stopped game',async()=>{const f=fixture({fail:true});f.g.tick();await settle();await settle();A.equal(f.api.state.ready,false);A.match(f.api.state.error,/controlled shader failure/);const count=f.owned.length;for(let i=0;i<10;i++)f.g.tick();A.equal(f.owned.length,count);A.ok(f.owned.every(o=>o.disposals===1));});
test('Removal during pending preparation cannot resurrect disposed graphics or remove unrelated scene nodes',async()=>{let finish;const f=fixture({pending:new Promise(r=>finish=r)}),sibling=new Group();f.g.scene.object3D.add(sibling);f.g.tick();await settle();f.g.remove();finish();await settle();await settle();A.equal(f.api.state.ready,false);A.equal(f.g.removed,true);A.ok(f.owned.every(o=>o.disposals===1));A.deepEqual(f.g.scene.object3D.children,[sibling]);});
