const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core'),B=require('../bestiary'),E=require('../encounters');
function travel(s,goal){let k=0;while(Math.hypot(s.p[0]-goal[0],s.p[2]-goal[2])>.005&&k++<2000){const dx=goal[0]-s.p[0],dz=goal[2]-s.p[2],l=Math.hypot(dx,dz),d=Math.min(.11,l);C.move(s,dx/l*d,dz/l*d);}A.ok(Math.hypot(s.p[0]-goal[0],s.p[2]-goal[2])<.01,JSON.stringify({at:s.p,goal}));}
function fixture(kind){const s=C.create('TRIAL');s.world.enemies=[E.training(kind)];s.world.solids=[];s.p=[0,0,3];s.head=[0,1.65,3];s.invuln=999;return s;}
function steps(s,t){for(let i=0;i<t*90;i++)C.step(s,1/90,s.head);}
test('25 areas retain five core wardens and include all twelve new orders',()=>{const w=C.generate('DOMINIONS');A.equal(w.rooms.length,25);A.equal(w.enemies.length,21);A.equal(w.enemies.filter(e=>e.required!==false).length,5);A.deepEqual([...new Set(w.enemies.filter(e=>e.required===false).map(e=>e.kind))].sort(),[...B.kinds].sort());A.equal(new Set(w.rooms.filter(r=>r.outer).map(r=>r.label)).size,16);A.equal(w.dominions.skyways.length,8);A.equal(w.architecture.routes.length,9);A.equal(w.dominions.towers.length,2);});
test('Every new gallery, high walk and crown is continuously traversable both ways over ten seeds',()=>{for(let seed=0;seed<10;seed++){const s=C.create('DOM-ROUTE-'+seed);s.world.enemies=[];for(const p of s.world.dominions.paths){s.p=[...p.points[0]];A.ok(C.walkable(s.world,s.p),p.label+' entry');for(const point of p.points.slice(1))travel(s,point);const top=s.world.dominions.towers.find(t=>t.label===p.label);if(top)A.ok(Math.abs(s.p[1]-6.4)<.01);for(const point of [...p.points].reverse().slice(1))travel(s,point);A.ok(Math.abs(s.p[1]-p.points[0][1])<.05,p.label+' return');}}});
test('Optional outer enemies do not block the original beacon',()=>{const s=C.create('GATE');s.world.enemies.filter(e=>e.required!==false).forEach(e=>e.dead=true);C.step(s,1/90);A.equal(s.portalReady,true);A.equal(s.world.enemies.filter(e=>!e.dead).length,16);});
test('All new trials are real, distinct, tracked opponents with finite health and committed windup',()=>{A.equal(Object.keys(E.names).length,15);for(const kind of B.kinds){const s=fixture(kind),e=s.world.enemies[0];e.p=[0,1.05,1.5];e.cd=0;steps(s,.15);A.ok(e.wind>0,kind);A.ok(e.aim.every(Number.isFinite),kind);A.equal(e.kind,kind);A.ok(e.hp>0);const frozenAim=[...e.aim];s.head[0]=1;steps(s,.15);A.deepEqual(e.aim,frozenAim,kind+' aim is committed');}});
test('New ranged orders produce distinct swept bolts, with frost and chain statuses',()=>{for(const [kind,count] of [['archer',1],['hexer',5],['abbess',2],['gaoler',1],['mirror',3],['widow',2]]){const s=fixture(kind);s.world.enemies[0].cd=0;steps(s,B.catalog[kind].wind+.03);A.ok(s.bolts.length>=count,kind+' real projectiles');A.ok(s.bolts.every(b=>[...b.p,...b.v].every(Number.isFinite)));if(['abbess','gaoler'].includes(kind))A.ok(s.bolts.every(b=>b.slow>0));}});
test('Walls block all new enemy acquisition and bolts',()=>{for(const kind of B.kinds){const s=fixture(kind),e=s.world.enemies[0];e.cd=0;e.aware=false;s.world.solids=[{min:[-4,0,.2],max:[4,4,.4]}];steps(s,2);A.equal(e.aware,false,kind);A.equal(s.bolts.length,0,kind);A.equal(s.hazards.length,0,kind);}});
test('Bomb and colossus telegraphs are delayed and a clear dodge avoids them',()=>{for(const kind of ['alchemist','colossus']){const s=fixture(kind),e=s.world.enemies[0];e.p=[0,1.05,1];e.cd=0;steps(s,B.catalog[kind].wind+.04);A.ok(s.hazards.length>0,kind);A.equal(s.health,100);s.invuln=0;s.p=[8,0,3];s.head=[8,1.65,3];steps(s,1.1);A.equal(s.health,100);A.equal(s.hazards.length,0);}});
test('Choir Leech heals an injured nearby ally, never resurrects dead enemies',()=>{const s=fixture('leech'),e=s.world.enemies[0];e.cd=0;const ally={...E.training('lancer'),id:1,p:[2,1.05,-1.8],hp:25,cd:99};s.world.enemies.push(ally);steps(s,1.5);A.ok(ally.hp>25);ally.dead=true;ally.hp=0;e.cd=0;steps(s,6);A.equal(ally.dead,true);A.equal(ally.hp,0);});
test('Mirror armor drops during its windup, recovery and freezing',()=>{const e=E.training('mirror');A.equal(E.guardActive(e),true);for(const field of ['wind','recovery','frozen']){e[field]=1;A.equal(E.guardActive(e),false);e[field]=0;}});
test('Player chill slows movement, expires, and blocked icy bolts cannot apply it',()=>{const s=fixture('abbess');s.world.enemies=[];s.invuln=0;s.bolts=[{p:[0,1.65,2],v:[0,0,8],life:1,slow:2.4,damage:12}];steps(s,.13);A.ok(s.playerSlow>0);const x=s.p[0];C.move(s,1,0);A.ok(Math.abs(s.p[0]-x-.55)<.01);steps(s,2.5);A.equal(s.playerSlow,0);});
test('Discovery and side rewards belong to simulation; practice never banks them',()=>{for(const unscored of [false,true]){const s=C.create('OBJECTIVES');s.world.enemies=[];s.unscored=unscored;for(const r of s.world.rooms.filter(r=>r.outer)){s.p=[r.x,0,r.z];C.step(s,1/90);}A.equal([...s.discovered].filter(id=>s.world.rooms[id].outer).length,16);A.equal(s.sideRewards.has('survey'),!unscored);const score=s.score;steps(s,.3);A.equal(s.score,score);}});
