/* TEST ONLY: emulates device poses and buttons. No game globals are modified.
 * The A-Frame renderer still receives stereo XR frames; hardware is not tested. */
(()=>{
 const pad=()=>({id:'Emulated Quest Touch',connected:true,mapping:'xr-standard',axes:[0,0,0,0],buttons:Array.from({length:6},()=>({pressed:false,touched:false,value:0}))});
 const state={deny:false,session:null,head:[0,1.65,0],hands:{left:[-.23,1.35,-.4],right:[.23,1.35,-.4]},missing:new Set(),quaternions:{},yaw:0};
 function transform(p,yaw=0){const c=Math.cos(yaw),s=Math.sin(yaw);return {position:{x:p[0],y:p[1],z:p[2]},orientation:{x:0,y:Math.sin(yaw/2),z:0,w:Math.cos(yaw/2)},matrix:new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,...p,1])};}
 function handTransform(hand){const p=state.hands[hand],q=state.quaternions[hand];if(!q)return transform(p);const [x,y,z,w]=q,xx=x*x,yy=y*y,zz=z*z,xy=x*y,xz=x*z,yz=y*z,wx=w*x,wy=w*y,wz=w*z;return {position:{x:p[0],y:p[1],z:p[2]},orientation:{x,y,z,w},matrix:new Float32Array([1-2*(yy+zz),2*(xy+wz),2*(xz-wy),0,2*(xy-wz),1-2*(xx+zz),2*(yz+wx),0,2*(xz+wy),2*(yz-wx),1-2*(xx+yy),0,...p,1])};}
 const projection=new Float32Array([1.6,0,0,0,0,1.5,0,0,0,0,-1.0001,-1,0,0,-.12,0]);
 class Space extends EventTarget{getOffsetReferenceSpace(){return this;}}
 class Session extends EventTarget{
  constructor(mode='immersive-vr'){super();this.mode=mode;this.environmentBlendMode=mode==='immersive-ar'?'alpha-blend':'opaque';this.visibilityState='visible';this.enabledFeatures=['local-floor'];this.renderState={depthNear:.06,depthFar:250};this.inputSources=['left','right'].map(hand=>({handedness:hand,targetRayMode:'tracked-pointer',profiles:['oculus-touch-v3','generic-trigger-squeeze-thumbstick'],targetRaySpace:{hand},gripSpace:{hand},gamepad:pad()}));this.started=false;this.ended=false;}
  requestReferenceSpace(){return Promise.resolve(new Space());}updateRenderState(s){Object.assign(this.renderState,s);}requestAnimationFrame(fn){if(this.ended)return 0;return requestAnimationFrame(t=>{if(this.ended)return;if(!this.started){this.started=true;const e=new Event('inputsourceschange');e.added=this.inputSources;e.removed=[];this.dispatchEvent(e);}const head=transform(state.head,state.yaw),views=['left','right'].map((eye,i)=>({eye,projectionMatrix:projection,transform:transform([state.head[0]+(i?.032:-.032),state.head[1],state.head[2]],state.yaw)}));fn(t,{session:this,getViewerPose:()=>({transform:head,views}),getPose:space=>state.missing.has(space.hand)?null:{transform:handTransform(space.hand),emulatedPosition:false}});});}cancelAnimationFrame(id){cancelAnimationFrame(id);}async end(){this.ended=true;this.dispatchEvent(new Event('end'));}
 }
 const xr=new EventTarget();xr.isSessionSupported=async mode=>['immersive-vr','immersive-ar'].includes(mode);xr.requestSession=async(mode)=>{if(state.deny)throw new DOMException('Test refusal','NotAllowedError');state.session=new Session(mode);return state.session;};Object.defineProperty(navigator,'xr',{value:xr,configurable:true});window.XRSession=Session;
 for(const type of[window.WebGLRenderingContext,window.WebGL2RenderingContext])if(type)type.prototype.makeXRCompatible=async()=>{};
 window.XRWebGLBinding=undefined;window.XRWebGLLayer=class{constructor(){this.framebuffer=null;this.scale=window.TEST_XR_PIXEL_SCALE||1;this.framebufferWidth=960*this.scale;this.framebufferHeight=640*this.scale;this.ignoreDepthValues=false;this.fixedFoveation=1;}getViewport(v){return {x:v.eye==='left'?0:480*this.scale,y:0,width:480*this.scale,height:640*this.scale};}};
 window.TestXR={state,orientation(hand,q){state.quaternions[hand]=q;},pose(hand,p){state.hands[hand]=p;},button(hand,i,on){const p=state.session.inputSources.find(s=>s.handedness===hand).gamepad;p.buttons[i]={pressed:on,touched:on,value:on?1:0};},axes(hand,x,y){state.session.inputSources.find(s=>s.handedness===hand).gamepad.axes=[0,0,x,y];},missing(hand,value){if(value)state.missing.add(hand);else state.missing.delete(hand);},hide(v){state.session.visibilityState=v?'hidden':'visible';state.session.dispatchEvent(new Event('visibilitychange'));}};
})();
