/* Deliberately isolated model fixtures; these are not device playthroughs. */
'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../core.js'),K=require('../field-kit-model.js'),Save=require('../pilgrim-save.js');
function game(){const s=C.create('KIT-TEST',1,{pilgrimage:{stage:0,tier:0}});s.head=C.add(s.p,[0,1.65,0]);return s;}
function fixture(){const s=game();s.p=[0,0,0];s.head=[0,1.65,0];s.world.solids=[];s.world.floors=[{x:0,z:0,w:30,d:30,y:0,type:'stone'}];s.world.ramps=[];s.world.enemies=[];return s;}
function advance(s,n=300){for(let i=0;i<n;i++)C.step(s,1/90,s.head);}
const meta={id:'kit-save-fixture',banked:0,receipt:{},yaw:0,pitch:0,focus:1};
test('A new expedition has finite supplies, no new objective or score',()=>{const s=game();a.deepEqual(s.fieldkit.stock,{mend:2,frost:2});a.equal(s.score,0);a.equal(s.targets.size,0);});
test('Drinking a vial restores at most 32 actual health and consumes one charge',()=>{const s=game();s.health=85;a.ok(K.drink(s,C));a.equal(s.health,100);a.equal(s.fieldkit.stock.mend,1);a.equal(s.fieldkit.drinks,1);a.equal(s.score,0);});
test('Full vitality, empty stock, death and unscored practice never consume a drink',()=>{for(const flag of['full','empty','dead','practice']){const s=game();s.health=40;if(flag==='full')s.health=100;if(flag==='empty')s.fieldkit.stock.mend=0;if(flag==='dead')s.phase='dead';if(flag==='practice')s.unscored=true;const before=JSON.stringify(s.fieldkit);a.equal(K.drink(s,C),false);a.equal(JSON.stringify(s.fieldkit),before);}});
test('An actual thrown healing flask impacts the floor and heals near its splash',()=>{const s=fixture();s.health=42;a.ok(K.launch(s,'mend',[0,1.2,-.1],[0,-1,0],C));advance(s,65);a.equal(s.fieldkit.flights.length,0);a.equal(s.health,74);a.equal(s.fieldkit.stock.mend,1);a.equal(s.fieldkit.throws,1);a.equal(s.arrows.length,0);});
test('Healing splash cannot cross a wall or heal through another floor',()=>{for(const elevated of[false,true]){const s=fixture();s.health=40;const p=elevated?[0,4,0]:[2,1.2,0];s.head=[...p];a.ok(K.launch(s,'mend',p,[0,-1,0],C));s.head=[0,1.65,0];if(elevated)s.world.floors.push({x:0,z:0,w:10,d:10,y:3,type:'stone'});else s.world.solids=[{min:[.75,0,-4],max:[.85,3,4]}];advance(s,90);a.equal(s.health,40);}});
test('A frost flask interrupts multiple actual enemy model states but not one behind masonry',()=>{const s=fixture();const base=s.world.enemies;const make=(id,p)=>({id,p,kind:'cantor',hp:100,maxHp:100,speed:0,cd:90,dead:false,aware:false,room:1,wind:0});s.world.enemies=[make(0,[0,1.05,-1]),make(1,[1,1.05,-1]),make(2,[2.1,1.05,-1])];s.world.solids=[{min:[1.7,0,-4],max:[1.8,3,4]}];a.ok(K.launch(s,'frost',[0,1.3,-.2],[0,-1,-2],C));advance(s,25);a.ok(s.world.enemies[0].hp<100);a.ok(s.world.enemies[1].hp<100);a.equal(s.world.enemies[2].hp,100);a.ok(s.world.enemies[0].frozen>0);a.equal(s.shots,0);a.equal(s.ammo.frost,6);});
test('Swept flask collision stops a fast throw at a thin wall',()=>{const s=fixture();s.world.solids=[{min:[-2,0,-.45],max:[2,3,-.44]}];a.ok(K.launch(s,'frost',[0,1.4,-.1],[0,0,-14],C));advance(s,6);const event=s.events.find(e=>e.type==='kit-splash');a.ok(event);a.ok(event.p[2]>-.45);a.equal(s.fieldkit.flights.length,0);});
test('Invalid or obstructed throw origins do not spend supplies',()=>{const s=game();const before=JSON.stringify(s.fieldkit);for(const [p,v]of[[[50,1,0],[0,0,1]],[[NaN,1,1],[1,0,0]],[s.head,[0,0,20]]])a.equal(K.launch(s,'frost',p,v,C),false);s.world.solids.push({min:[-.1,0,19.45],max:[.1,3,19.55]});a.equal(K.launch(s,'frost',[0,1.6,19],[0,0,-2],C),false);a.equal(JSON.stringify(s.fieldkit),before);});
test('Throwing past the available world consumes the thrown vial once, never teleports the player',()=>{const s=fixture();s.world.floors=[];const before=[...s.p];a.ok(K.launch(s,'frost',[0,1.6,0],[0,0,8],C));advance(s,450);a.equal(s.fieldkit.flights.length,0);a.equal(s.fieldkit.stock.frost,1);a.deepEqual(s.p,before);a.ok(s.events.some(e=>e.type==='kit-lost'));});
test('A real ordinary arrow breaks a cache seal but cannot remotely collect its loot',()=>{const s=game(),cache=K.anchors(s)[0],target=K.center(cache);s.fieldkit.stock.mend=0;const dir=C.unit(C.sub(target,s.head));a.ok(C.fire(s,s.head,dir,1,'plain'));advance(s,14);a.equal(s.fieldkit.caches[0],1);a.equal(s.fieldkit.stock.mend,0);a.equal(s.targets.size,0);});
test('Golden arrows do not break or collect cache seals',()=>{const s=game(),c=K.anchors(s)[0];const dir=C.unit(C.sub(K.center(c),s.head));a.ok(C.fire(s,s.head,dir,1,'blink'));advance(s,15);a.equal(s.fieldkit.caches[0],0);});
test('Nearby cache collection is bounded and one-time; a full kit leaves loot in place',()=>{const s=game(),p=K.center(K.anchors(s)[0]);s.head=C.add(s.p,[0,1.65,0]);const origin=[.4,1,19.7];a.ok(K.collect(s,0,origin,C));a.deepEqual(s.fieldkit.stock,{mend:3,frost:3});a.equal(s.fieldkit.caches[0],2);a.equal(K.collect(s,0,origin,C),false);const z=game();z.fieldkit.stock={mend:3,frost:3};a.equal(K.collect(z,0,origin,C),false);a.equal(z.fieldkit.caches[0],0);});
test('A distant or wall-obscured cache cannot be collected',()=>{const s=game();a.equal(K.collect(s,1,s.head,C),false);s.world.solids.push({min:[.5,0,18],max:[.6,3,22]});a.equal(K.collect(s,0,s.head,C),false);a.equal(s.fieldkit.caches[0],0);});
test('Kit stock, opened caches and an in-flight flask survive exact checkpoint round-trip',()=>{const s=game();K.open(s,0,C);K.launch(s,'frost',C.add(s.head,[0,0,-.1]),[0,0,-2],C);const cp=Save.capture(s,meta),loaded=Save.restore(cp).game;a.deepEqual(loaded.fieldkit,s.fieldkit);a.deepEqual(loaded.p,s.p);});
test('Legacy checkpoint without a field kit still loads without manufacturing saved charges',()=>{const s=game(),cp=Save.capture(s,meta);delete cp.state.fieldkit;const loaded=Save.restore(cp).game;a.equal(loaded.fieldkit,undefined);a.deepEqual(Save.capture(loaded,meta),cp);a.ok(K.ensure(loaded));a.deepEqual(loaded.fieldkit.stock,{mend:2,frost:2});});
test('Malformed field-kit saves reject extra fields, excessive stock, nonfinite vectors and duplicate flights',()=>{for(const change of[k=>k.freeGold=true,k=>k.stock.mend=4,k=>k.caches=[0],k=>{k.serial=1;k.throws=1;k.flights=[{id:1,type:'frost',p:[0,NaN,0],v:[0,0,0],life:1}];},k=>{k.serial=1;k.throws=1;const f={id:1,type:'mend',p:[0,1,0],v:[0,0,0],life:1};k.flights=[f,f];}]){const k=K.create();change(k);a.throws(()=>K.restore(k));}});
test('Progression carries remaining supplies and Provision adds at most one of each',()=>{const s=game();s.fieldkit.stock={mend:0,frost:3};s.fieldkit.caches=[2,2,1];a.deepEqual(K.next(s,'power').stock,{mend:0,frost:3});a.deepEqual(K.next(s,'supplies').stock,{mend:1,frost:3});a.deepEqual(K.next(s,'power').caches,[0,0,0]);});
test('Motion sampling supports a downward toss without artificial horizontal motion',()=>{const m=new K.Motion();m.sample([0,1,0],1);m.sample([0,.94,0],1.04);m.sample([0,.88,0],1.08);a.deepEqual(m.release([0,.82,0],1.12).map(x=>Math.round(x*10)/10),[0,-1.5,0]);});
test('A stationary release, tracking discontinuity and long sample gap do not throw',()=>{for(const kind of['still','jump','gap']){const m=new K.Motion();m.sample([0,1,0],1);m.sample([0,1,0],1.04);if(kind==='jump')m.sample([3,1,0],1.08);if(kind==='gap')m.sample([0,1,0],1.5);a.equal(m.release([0,1,0],1.12),null);}});
test('Both chapter cache locations are supported and clear for 32 seeds, including both gallery sides',()=>{for(let seed=0;seed<32;seed++)for(let stage=0;stage<2;stage++){const s=C.create('CACHE-'+seed,stage+1,{pilgrimage:{stage,tier:0}});for(const c of K.anchors(s)){a.ok(C.walkable(s.world,c.p,.12),JSON.stringify({seed,stage,c}));a.equal(C.floorAt(s.world,c.p),c.p[1]);}}});
