/* Isolated rule fixtures, not physical-device or end-to-end acceptance. */
'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../core.js'),M=require('../fieldwork-model.js'),S=require('../pilgrim-save.js');
function fixture(){const s=C.create('FIELDWORK');s.world={...s.world,enemies:[],solids:[],targets:[],pickups:[{id:'fixture-supply',p:[.3,1,-.5],kind:'frost',taken:false}],floors:[{x:0,z:0,w:30,d:30,y:0}]};s.p=[0,0,0];s.head=[0,1.65,0];return s;}
test('Direct reach accepts a nearby supply without requiring controller pointing alignment',()=>{const s=fixture(),p=M.target(s,[.3,1,-.3],[1,0,0]);a.equal(p.index,0);a.equal(p.near,true);a.equal(C.collectPickup(s,p.index,[.3,1,-.3],.55),true);a.equal(s.ammo.frost,9);a.equal(C.collectPickup(s,p.index,[.3,1,-.3],.55),false);});
test('A distant pull needs deliberate alignment and cannot cross a wall',()=>{const s=fixture();s.world.pickups[0].p=[0,1,-4];a.equal(M.target(s,[0,1,0],[0,0,1]),null);a.equal(M.target(s,[0,1,0],[0,0,-1],false),null);a.equal(M.target(s,[0,1,0],[0,0,-1]).near,false);s.world.solids.push({min:[-1,0,-2],max:[1,3,-1.8]});a.equal(M.target(s,[0,1,0],[0,0,-1]),null);a.equal(C.collectPickup(s,0,[0,1,0],7),false);});
test('Lost or implausible hand poses cannot take supplies',()=>{const s=fixture();for(const p of [null,[NaN,1,0],[8,1,0]])a.equal(M.target(s,p,[0,0,-1]),null);});
test('Full vitality remains available, with an explicit unusable pickup candidate',()=>{const s=fixture();s.world.pickups[0].kind='health';const pick=M.target(s,[.3,1,-.3],[1,0,0]);a.equal(pick.usable,false);a.equal(C.collectPickup(s,0,[.3,1,-.3],.55),false);a.equal(s.world.pickups[0].taken,false);s.health=85;a.equal(C.collectPickup(s,0,[.3,1,-.3],.55),true);a.equal(s.health,100);});
test('Contact collection covers visible chest-height supplies but not another floor',()=>{const s=fixture();s.world.pickups[0].p=[0,1.35,0];C.step(s,1/90,s.head);a.equal(s.ammo.frost,9);a.equal(s.world.pickups[0].taken,true);const t=fixture();t.world.pickups[0].p=[0,3.5,0];C.step(t,1/90,t.head);a.equal(t.world.pickups[0].taken,false);});
test('Manual pickup preference prevents contact rewards; neither mode sees through cover',()=>{const s=fixture();s.manualPickups=true;C.step(s,1/90,s.head);a.equal(s.world.pickups[0].taken,false);s.manualPickups=false;s.world.solids=[{min:[-.1,0,-.2],max:[1,3,-.1]}];C.step(s,1/90,s.head);a.equal(s.world.pickups[0].taken,false);});
test('Confirmation reports actual gains and retained ammunition totals',()=>{const s=fixture(),item=s.world.pickups[0],before={health:s.health,ammo:s.ammo.frost};C.collectPickup(s,0,[.3,1,-.3],.55);a.equal(M.confirmation(s,item,before),'Frost arrows +3 / 9 ready');});
test('Direct Archive entry has its original versioned stage and a valid scored checkpoint',()=>{const s=C.create('FIELDWORK',2,{pilgrimage:{stage:1,tier:0}});const cp=S.capture(s,{id:'fieldwork-fixture',banked:0,receipt:{},yaw:0,pitch:0,focus:3});a.equal(S.restore(cp).game.world.generator,'ashen-archive-1');a.equal(s.world.depth,2);});
