/* Pure model fixtures are explicitly separate from native device-input tests. */
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../core.js'),M=require('../goldwind-model.js');
const nock=[0,1.4,-.3],near=[0,1.4,-.3],pulled=[0,1.4,.3];
function ready(){const d=new M.Draw();d.update(nock,near,false,false,true,'frost');return d;}
function field(){return {world:{solids:[],floors:[{x:0,z:0,w:30,d:30,y:0}],enemies:[]},p:[0,0,0],head:[0,1.65,0],phase:'playing',time:0,events:[],shardCharges:2,maxShards:2,shardCD:0,shardRecharge:0,shardsUsed:0,invuln:0};}
function perform(d,travel=false){d.update(nock,near,!travel,travel,true,'frost');d.update(nock,pulled,!travel,travel,true,'frost');return d.update(nock,pulled,false,false,true,'frost');}
test('trigger acquires at nock and releases a latched damage type',()=>{const d=ready(),r=perform(d);assert.equal(r.shot.type,'frost');assert.ok(r.shot.charge>.9);assert.ok(r.shot.direction[2]<-.99);});
test('face-button draw is a separate golden arrow, not an equipment toggle',()=>{const d=ready();assert.equal(perform(d,true).shot.type,'blink');assert.equal(perform(d).shot.type,'frost');});
test('button pressed away from nock cannot acquire by dragging toward the bow',()=>{const d=ready();d.update(nock,[1,1.4,0],true,false,true,'plain');d.update(nock,near,true,false,true,'plain');d.update(nock,pulled,true,false,true,'plain');assert.equal(d.update(nock,pulled,false,false,true,'plain').shot,null);});
test('switching input source while drawing cancels and requires neutral',()=>{const d=ready();d.update(nock,near,true,false,true,'plain');d.update(nock,pulled,true,false,true,'plain');assert.ok(d.update(nock,pulled,true,true,true,'plain').cancelled);assert.ok(!d.update(nock,near,false,true,true,'plain').drawing);assert.ok(!d.update(nock,pulled,false,false,true,'plain').shot);assert.equal(perform(d,true).shot.type,'blink');});
test('held acquisition, missing pose, invalid pose and shield cancellation cannot fire',()=>{const d=new M.Draw();assert.ok(!d.update(nock,near,false,true,true,'plain').drawing);d.update(nock,near,false,false,true,'plain');d.update(nock,near,false,true,true,'plain');d.update(nock,pulled,false,true,true,'plain');d.update(nock,null,false,true,true,'plain');assert.ok(!d.update(nock,pulled,false,false,true,'plain').shot);d.update(nock,near,false,true,true,'plain');d.update(nock,pulled,false,true,false,'plain');assert.ok(!d.update(nock,pulled,false,false,true,'plain').shot);d.update(nock,[NaN,0,0],true,false,true,'plain');assert.equal(d.ready,false);});
test('equipment changing during a draw cannot silently change the projectile type',()=>{const d=ready();d.update(nock,near,true,false,true,'frost');d.update(nock,pulled,true,false,true,'cinder');assert.equal(d.update(nock,pulled,false,false,true,'cinder').shot.type,'frost');});
test('reaching over one metre cancels a draw rather than producing a stale shot',()=>{const d=ready();d.update(nock,near,true,false,true,'plain');d.update(nock,[0,1.4,2],true,false,true,'plain');assert.ok(!d.update(nock,pulled,false,false,true,'plain').shot);});
test('physical quiver availability excludes Blink and rejects locked or empty arrows',()=>{const s=C.create();assert.ok(M.available(s,'plain'));assert.ok(M.available(s,'frost'));assert.ok(!M.available(s,'blink'));assert.ok(!M.available(s,'volley'));s.ammo.frost=0;assert.ok(!M.available(s,'frost'));});
function thrown(points){const t=new M.Throw();t.update([0,1.2,0],false,0);let r;for(let i=0;i<points.length;i++)r=t.update(points[i],i<points.length-1,.04*(i+1));return r;}
test('disk gesture uses recent deliberate physical motion in its actual direction',()=>{const r=thrown([[0,1.2,0],[.10,1.2,0],[.20,1.2,0],[.3,1.2,0]]);assert.ok(r);assert.ok(r.velocity[0]>2);assert.equal(r.velocity[2],0);});
test('a stationary grip press and release is not a shard dash',()=>{assert.equal(thrown(Array.from({length:4},()=>[0,1.2,0])),null);});
test('throw tracking jumps, sparse samples, lost focus and backward clocks disarm',()=>{const t=new M.Throw();t.update([0,0,0],false,0);t.update([0,0,0],true,.04);assert.equal(t.update([4,0,0],true,.08),null);assert.equal(t.ready,false);t.update([0,0,0],false,.12);t.update([0,0,0],true,.16);assert.equal(t.update([.1,0,0],false,.18),null);t.update([0,0,0],true,.22);assert.equal(t.update([.2,0,0],false,1),null);assert.equal(t.ready,false);});
test('held grip on tracking acquisition never produces a throw',()=>{const t=new M.Throw();for(let i=0;i<5;i++)assert.equal(t.update([i*.1,1,0],true,i*.04),null);assert.equal(t.update([.5,1,0],false,.24),null);});
test('short disk travels in flight, then spends exactly one charge on supported impact',()=>{const s=field(),f=M.launchDisc(s,[0,1.2,-.4],[0,-1,-3]);assert.ok(f);assert.deepEqual(s.p,[0,0,0]);assert.equal(s.shardCharges,2);for(let i=0;i<150&&!f.done;i++)M.stepDisc(s,f,1/90);assert.ok(f.ok,f.reason);assert.ok(-s.p[2]>.75&&-s.p[2]<=4);assert.equal(s.shardCharges,1);assert.equal(s.shardsUsed,1);M.stepDisc(s,f,.04);assert.equal(s.shardCharges,1);});
test('disk hitting a wall cannot tunnel or consume a charge',()=>{const s=field();s.world.solids.push({min:[-2,0,-1.1],max:[2,3,-1]});const f=M.launchDisc(s,[0,1.2,-.3],[0,0,-3]);for(let i=0;i<120&&!f.done;i++)M.stepDisc(s,f,1/90);assert.equal(f.ok,false);assert.match(f.reason,/stone/);assert.deepEqual(s.p,[0,0,0]);assert.equal(s.shardCharges,2);});
test('disc relocation refuses gaps and occupied or distant destinations',()=>{const s=field();assert.equal(M.commitDisc(s,[0,0,-5]).ok,false);s.world.enemies=[{p:[0,1.05,-2],dead:false}];assert.equal(M.commitDisc(s,[0,0,-2]).ok,false);s.world.enemies=[];s.world.floors=[{x:0,z:0,w:8,d:1,y:0},{x:0,z:-2,w:8,d:1,y:0}];assert.equal(M.commitDisc(s,[0,0,-2]).ok,false);assert.deepEqual(s.p,[0,0,0]);});
test('AR, cooldown and invalid origin cannot launch movement disks',()=>{const s=field();s.world.ar=true;assert.equal(M.launchDisc(s,[0,1,0],[0,0,-3]),null);s.world.ar=false;s.shardCD=1;assert.equal(M.launchDisc(s,[0,1,0],[0,0,-3]),null);s.shardCD=0;assert.equal(M.launchDisc(s,[20,1,0],[0,0,-3]),null);});
test('relocating while a disk is flying cancels its pending movement',()=>{const s=field(),f=M.launchDisc(s,[0,1.2,-.4],[0,0,-3]);s.p=[1,0,0];M.stepDisc(s,f,.04);assert.equal(f.done,true);assert.equal(f.ok,false);assert.equal(s.shardCharges,2);});
test('ordinary generated and authored worlds retain supported disk rules',()=>{for(const upgrades of[{}, {returningBell:'returning-bell-1'},{returningBell:'returning-bell-2'}]){const s=C.create('BELL-01',1,upgrades);C.step(s,0,C.add(s.p,[0,1.65,0]));const dest=C.add(s.p,[0,0,-1]);const before=s.shardsUsed,r=M.commitDisc(s,dest);assert.ok(r.ok,r.reason);assert.equal(s.shardsUsed,before+1);}});
