const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core'),E=require('../encounters'),L=require('../architecture');
function fresh(kind='cantor'){const s=C.create('BELL-01'),e=E.training(kind);s.world.enemies=[e];return {s,e};}
function ticks(s,n){for(let i=0;i<n;i++)C.step(s,1/90,s.head);}
function aim(s,p,charge=.4,type='plain'){const dx=p[0]-s.head[0],dz=p[2]-s.head[2],d=Math.hypot(dx,dz),v=12+charge*24,v2=v*v,dy=p[1]-s.head[1],disc=v2*v2-9.8*(9.8*d*d+2*dy*v2),pitch=Math.atan((v2-Math.sqrt(disc))/(9.8*d)),dir=C.unit([dx/d*Math.cos(pitch),Math.sin(pitch),dz/d*Math.cos(pitch)]);return C.fire(s,s.head,dir,charge,type);}
test('Cantor announces, locks aim, then emits a bounded physical three-bolt spread',()=>{const {s,e}=fresh();e.cd=0;C.step(s,1/90);A.equal(e.phase,'winding');A.equal(s.bolts.length,0);const aim=[...e.aim];s.head=[2,1.65,3];ticks(s,94);A.deepEqual(e.aim,aim);A.equal(s.bolts.length,3);A.ok(Math.abs(s.bolts[0].v[0])<1e-8);A.ok(s.bolts[1].v[0]*s.bolts[2].v[0]<0);A.ok(e.recovery>0);});
test('A charging hound follows its announced line rather than homing into a dodge',()=>{const {s,e}=fresh('stalker');e.cd=0;C.step(s,1/90);A.equal(e.wind,.9);s.head=[2.5,1.65,3];ticks(s,90);A.ok(e.charge);A.equal(e.charge.dir[0],0);ticks(s,100);A.equal(s.health,100);A.ok(e.recovery>0);});
test('Hound charge stops at stone, never tunneling even at the maximum accepted step',()=>{const {s,e}=fresh('stalker');e.charge={dir:[0,0,1],left:6};s.world.solids.push({min:[-2,0,0],max:[2,3,.07],type:'test'});for(let i=0;i<50;i++)C.step(s,.04);A.ok(e.p[2]<-.39);A.equal(s.health,100);});
test('Sentinel frontal body shots deflect, but its exposed head remains hittable',()=>{const a=fresh('warden');a.e.cd=10;A.ok(aim(a.s,a.e.p));ticks(a.s,25);A.equal(a.e.hp,118);A.ok(a.s.events.some(e=>e.type==='enemy-deflect'));const b=fresh('warden');b.e.cd=10;A.ok(aim(b.s,C.add(b.e.p,[0,.62,0])));ticks(b.s,25);A.ok(b.e.hp<118);A.equal(b.s.headshots,1);});
test('Sentinel recovery and freezing remove guard rather than grant invisible armor',()=>{for(const field of['recovery','frozen']){const {s,e}=fresh('warden');e.cd=10;e[field]=2;A.equal(E.guardActive(e),false);A.ok(aim(s,e.p));ticks(s,25);A.ok(e.hp<118);}});
test('Cinder detonates against the floor and damages nearby targets without a direct hit',()=>{const {s,e}=fresh();e.p=[0,1.05,0];e.hp=1000;e.cd=100;s.head=[2,1,2];A.ok(C.fire(s,s.head,C.unit([0,-1,-2]),1,'cinder'));ticks(s,25);A.ok(s.events.some(e=>e.type==='explosion'));A.ok(e.hp<1000);A.equal(s.hits,0);A.equal(s.ammo.cinder,3);});
test('Cinder cannot damage an enemy through intervening cover',()=>{const {s,e}=fresh();e.p=[0,1.05,0];e.hp=1000;e.cd=100;s.head=[2,1,2];s.world.solids.push({min:[.8,0,-1],max:[1.2,3,1],type:'test-cover'});A.ok(C.fire(s,s.head,C.unit([0,-1,-2]),1,'cinder'));ticks(s,25);A.ok(s.events.some(e=>e.type==='explosion'));A.equal(e.hp,1000);});
test('Frost interrupts a charging enemy and keeps it stationary during the freeze',()=>{const {s,e}=fresh('stalker');e.hp=1000;e.cd=100;e.charge={dir:[0,0,1],left:4};A.ok(aim(s,C.add(e.p,[0,.62,0]),.35,'frost'));ticks(s,25);A.ok(e.frozen>0);A.equal(e.charge,null);const p=[...e.p];ticks(s,20);A.deepEqual(e.p,p);A.equal(e.phase,'frozen');});
test('Both stairs in both new lofts form a continuous traversable loop',()=>{const s=C.create('BELL-01');s.world.enemies=[];A.equal(s.world.architecture.lofts.length,2);for(const f of s.world.architecture.lofts){s.p=[...f.entry];for(let i=0;i<192;i++)C.move(s,0,-.05);A.ok(s.p[1]>3.19,JSON.stringify(s.p));for(let i=0;i<194;i++)C.move(s,.05,0);A.ok(s.p[0]>f.otherEntry[0]-.12);for(let i=0;i<192;i++)C.move(s,0,.05);A.ok(s.p[1]<.05);}});
test('Upper-loft supplies cannot be collected from the floor below',()=>{const {s}=fresh();s.world.enemies=[];const p=s.world.pickups.find(p=>String(p.id).startsWith('loft-'));s.p=[p.p[0],0,p.p[2]];ticks(s,1);A.equal(p.taken,false);s.p[1]=3.2;ticks(s,1);A.equal(p.taken,true);});
test('One hundred generated worlds preserve distinct lofts, safe entries and landing pads',()=>{for(let i=0;i<100;i++){const w=C.generate('HUNT-'+i);A.equal(w.architecture.lofts.length,2);for(const f of w.architecture.lofts){A.notEqual(f.room,1);A.notEqual(f.room,w.exit);A.ok(C.walkable(w,f.entry));A.ok(C.walkable(w,f.otherEntry));A.ok(C.walkable(w,f.pad,.42));A.equal(L.floorAt(w,f.pad),3.2);}}});

test('Sentinel cannot snap its guard through a turn to erase a flank',()=>{const {s,e}=fresh('warden');s.world.targets=[];e.cd=10;e.facing=[0,0,1];s.head=[0,1.65,-4.8];C.step(s,1/90);A.ok(e.facing[2]>.999);A.ok(aim(s,e.p));ticks(s,25);A.ok(e.hp<118);A.equal(s.events.some(e=>e.type==='enemy-deflect'),false);});
