const {test}=require('node:test'),a=require('node:assert/strict');
const C=require('../core.js'),O=require('../oath-model.js'),S=require('../pilgrim-save.js');
const api={...C,block(s,p){s.blocks++;},hurt(s,n){if(s.invuln===0)s.health-=n;}};
const meta={id:'pilgrim-oath-test',banked:0,receipt:{},yaw:0,pitch:0,focus:3};
function fresh(){return C.create('FIRST-BELL',1,{oath:true});}
function activate(s,n){s.oath.stage=n;s.oath.cleared=n;for(const e of s.world.enemies)if(e.oathWave<n){e.dead=true;e.hp=0;}const r=s.world.rooms[O.stages[n].room];s.p=[r.x,0,r.z+5.5];s.head=C.add(s.p,[0,1.65,0]);s.viewForward=[0,0,-1];s.oath.active=false;s.oath.rest=0;O.prepare(s,.04,api);}
test('Oath is opt-in; default world retains the 25 districts and 21 enemies',()=>{const s=C.create();a.equal(s.oath,undefined);a.equal(s.world.rooms.length,25);a.equal(s.world.enemies.length,21);});
test('An Oath has a connected three-court route, five real opponents and unchanged floor geometry',()=>{const s=fresh(),w=C.generate('FIRST-BELL');a.deepEqual(s.world.solids,w.solids);a.deepEqual(s.world.floors,w.floors);a.equal(s.world.enemies.length,5);a.equal(s.world.exit,17);for(let i=1;i<s.world.oath.route.length;i++)a.ok(s.world.links[s.world.oath.route[i-1]].includes(s.world.oath.route[i]));a.equal(s.world.oath.stations.length,3);});
test('Fifty deterministic seeds reserve clearance for every encounter actor and traversable station entry',()=>{for(let i=0;i<50;i++){const s=C.create('OATH-'+i,1,{oath:true});for(const e of s.world.enemies)a.ok(C.walkable(s.world,[e.p[0],0,e.p[2]],.72));for(const d of O.stages){const r=s.world.rooms[d.room];a.ok(C.walkable(s.world,[r.x,0,r.z+6],.42));}}});
test('Dormant future waves neither attack nor accept damage',()=>{const s=fresh();for(let i=0;i<200;i++)C.step(s,1/90);a.equal(s.bolts.length,0);a.ok(s.world.enemies.every(e=>!O.canTarget(s,e)));a.equal(O.damage(s,s.world.enemies[4],300,true,api),0);});
test('Arrival is proximity-driven with a full initial warning allowance',()=>{const s=fresh();activate(s,0);a.ok(s.oath.active);a.equal(s.oath.gap,.8);a.ok(s.world.enemies.slice(0,2).every(e=>e.cd>=1.3));a.equal(s.events.at(-1).type,'oath-arrival');});
test('Director spaces new attacks and bounds overlapping committed threats',()=>{const s=fresh();activate(s,0);s.oath.gap=0;const [e,f]=s.world.enemies;a.ok(O.canAttack(s,e,api));a.ok(!O.canAttack(s,f,api));s.oath.gap=0;e.wind=1;f.wind=1;a.ok(!O.canAttack(s,e,api));});
test('Offscreen fresh attacks wait rather than striking without a readable warning',()=>{const s=fresh();activate(s,0);s.oath.gap=0;s.viewForward=[0,0,1];a.equal(O.canAttack(s,s.world.enemies[0],api),false);});
test('An uncleared stage cannot be skipped by visiting a later court',()=>{const s=fresh(),r=s.world.rooms[17];s.p=[r.x,0,r.z];O.prepare(s,.04,api);a.equal(s.oath.stage,0);a.equal(s.oath.active,false);});
test('Clearing a wave grants one recovery beat and supplies exactly once',()=>{const s=fresh();activate(s,0);s.health=40;for(const e of s.world.enemies.slice(0,2)){e.dead=true;e.hp=0;}O.after(s,api);a.equal(s.oath.stage,1);a.equal(s.health,58);a.equal(s.ammo.frost,8);for(let i=0;i<20;i++)O.after(s,api);a.equal(s.health,58);a.equal(s.ammo.frost,8);a.equal(s.oath.rest,4.5);});
test('Bellkeeper weak-point windows matter and high damage cannot skip phases',()=>{const s=fresh();activate(s,2);const e=s.world.enemies[4];e.recovery=0;a.equal(O.damage(s,e,100,true,api),16);e.recovery=2;a.equal(O.damage(s,e,100,true,api),100);a.equal(O.damage(s,e,9999,true,api),e.maxHp/3);});
test('Phase transitions have no damage, clear boss-owned projectiles, and cancel charges',()=>{const s=fresh();activate(s,2);const e=s.world.enemies[4];e.hp=e.maxHp*2/3;e.bossMove={dir:[0,0,1],left:5};s.bolts=[{owner:e.id,p:[0,1,0],v:[0,0,1],life:3}];const hp=s.health;O.boss(s,e,.04,api);a.equal(e.bossPhase,2);a.ok(e.bossTransition>1.9);a.equal(e.bossMove,null);a.equal(s.bolts.length,0);a.equal(hp,s.health);a.equal(O.damage(s,e,100,true,api),0);});
test('Boss volleys use committed aim, bounded physical bolts and an actual recovery window',()=>{const s=fresh();activate(s,2);const e=s.world.enemies[4];e.cd=0;s.oath.gap=0;O.boss(s,e,.04,api);a.ok(e.wind>=1.5);const aim=[...e.aim];s.head[0]+=2;for(let i=0;i<40;i++)O.boss(s,e,.04,api);a.deepEqual(e.aim,aim);a.equal(s.bolts.length,3);a.ok(e.recovery>2);a.ok(s.bolts.every(b=>b.owner===e.id&&C.len(b.v)<=5.001));});
test('Boss charge ends safely at walls and offers a counter window',()=>{const s=fresh();activate(s,2);const e=s.world.enemies[4];e.bossPhase=2;e.hp=e.maxHp*.6;e.bossMove={dir:[1,0,0],left:7.5};const old=[...e.p];for(let i=0;i<80;i++)O.boss(s,e,.04,api);a.equal(e.bossMove,null);a.ok(C.walkable(s.world,[e.p[0],e.p[1]-1.05,e.p[2]],.72));a.ok(e.p[0]-old[0]<=7.51);});
test('Third phase ground attacks announce a finite delayed hazard, not instant damage',()=>{const s=fresh();activate(s,2);const e=s.world.enemies[4];e.bossPhase=3;e.hp=e.maxHp*.25;e.bossPattern=1;e.cd=0;s.oath.gap=0;const hp=s.health;O.boss(s,e,.04,api);for(let i=0;i<39;i++)O.boss(s,e,.04,api);a.equal(s.health,hp);a.equal(s.hazards.length,1);a.equal(s.hazards[0].life,1.4);a.equal(s.hazards[0].radius,2.3);});
test('Frost interrupts a boss attack but does not remove the three-phase structure',()=>{const s=fresh();activate(s,2);const e=s.world.enemies[4];e.wind=1;e.bossMove={dir:[1,0,0],left:3};e.frozen=.65;O.boss(s,e,.04,api);a.equal(e.wind,0);a.equal(e.bossMove,null);a.equal(e.bossPhase,1);a.ok(e.recovery>0);});
test('Oath saves restore stage, depleted supply, enemy attack state and boss timers exactly',()=>{const s=fresh();activate(s,2);const e=s.world.enemies[4];e.bossPhase=2;e.hp=e.maxHp*.58;e.bossMove={dir:[0,0,1],left:3};e.aim=[...s.head];e.aimFloor=0;s.ammo.frost=1;const cp=S.capture(s,meta),r=S.restore(cp).game;a.deepEqual(S.capture(r,meta),cp);});
test('Legacy full-expedition checkpoints retain their generator and restore without conversion',()=>{const s=C.create('REST-ACCEPT'),cp=S.capture(s,meta);a.equal(cp.generator,'hollow-dominions-1');a.ok(!('oath' in cp.state));a.deepEqual(S.capture(S.restore(cp).game,meta),cp);});
test('Malformed Oath state cannot forge stage rewards or inject a boss into a normal save',()=>{const s=fresh(),cp=S.capture(s,meta);cp.state.oath.stage=2;cp.state.oath.cleared=2;a.throws(()=>S.restore(cp),/history/);const base=S.capture(C.create(),meta);base.state.enemies[0].bossPhase=3;a.throws(()=>S.restore(base),/Boss/);});
test('A living boss keeps the beacon shut, and its defeat opens an ordinary blessing transition',()=>{const s=fresh();activate(s,2);C.step(s,1/90);a.equal(s.portalReady,false);const e=s.world.enemies[4];e.dead=true;e.hp=0;e.bossPhase=3;C.step(s,1/90);a.ok(s.portalReady);a.equal(s.oath.stage,3);const r=s.world.rooms[s.world.exit];s.p=[r.x,0,r.z-3.8];a.ok(C.interact(s));const n=C.reward(s,'supplies');a.ok(n.oath);a.equal(n.oath.stage,0);a.equal(n.world.depth,2);});
test('Nightfall remains opt-in and deterministic in the authored expedition',()=>{const s=fresh(),hard=C.create('FIRST-BELL',1,{oath:true,challenge:'nightfall'});a.ok(hard.world.enemies.every((e,i)=>e.hp===Math.round(s.world.enemies[i].hp*1.3)));a.deepEqual(hard.world.oath,s.world.oath);});
