'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../core.js'),S=require('../pilgrim-save.js'),P=require('../chronicle.js');
const meta=()=>({id:'test-pilgrim-run',banked:0,receipt:{},yaw:.4,pitch:-.1,focus:1.7});
const shot=s=>C.fire(s,s.head,[0,0,-1],.8,'plain');
function round(s=C.create('BELL-01'),m=meta(),p={}){const raw=S.encode(p,S.capture(s,m));const d=S.decode(raw);a.equal(d.ok,true,d.error);return d;}
function memory(){const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k),m};}
test('Checkpoint round trip recreates the same 25-room world without serializing geometry',()=>{const s=C.create('REST-01');const d=round(s);a.deepEqual(d.restored.game.world,s.world);a.ok(S.encode({},S.capture(s,meta())).length<18000);a.equal(d.restored.game.phase,'playing');});
test('Partial bow and hand poses are not serialized as input or firing actions',()=>{const s=C.create('BELL-01');s.shield={p:[0,1.2,2.5],normal:[0,0,-1]};s.events=[{seq:20,type:'kill'}];s.eventSeq=20;s.sparks=[{p:[0,1,1],life:.2,type:'frost'}];const d=round(s).restored.game;a.equal(d.shield,null);a.deepEqual(d.events,[]);a.deepEqual(d.sparks,[]);a.equal(d.eventSeq,0);a.equal(d.shots,0);});
test('Equipment state, finite arrows, vitality and cooldowns survive without refilling',()=>{const s=C.create();s.health=52;s.guard=31;s.shardCharges=1;s.shardCD=.2;s.blinkCD=.3;s.type='frost';s.weapon='crossbow';s.crossbow={loaded:false,reload:.42,reloadDuration:1.55};s.ammo.frost=2;const d=round(s).restored.game;for(const k of['health','guard','shardCharges','shardCD','blinkCD','type','weapon','crossbow','ammo'])a.deepEqual(d[k],s[k]);});
test('Live swept projectiles resume with identical positions, velocities and timers',()=>{const s=C.create();shot(s);s.bolts.push({p:[0,1.6,-2],v:[0,0,4.5],life:3,kind:'cantor'});C.step(s,1/90);const d=round(s).restored.game;for(let i=0;i<12;i++){C.step(s,1/90);C.step(d,1/90);}a.deepEqual(d.arrows,s.arrows);a.deepEqual(d.bolts,s.bolts);a.equal(d.time,s.time);a.equal(d.health,s.health);});
test('Committed windups and short charges resume rather than rerolling attacks',()=>{const s=C.create();const e=s.world.enemies[0];e.aware=true;e.wind=.7;e.windTotal=1;e.aim=[...s.head];e.phase='winding';const d=round(s).restored.game;a.deepEqual(d.world.enemies[0],e);});
test('Delayed hazards and their owner identities are preserved',()=>{const s=C.create();s.hazards=[{p:[0,0,3],radius:2.3,life:.6,kind:'alchemist',owner:9}];a.deepEqual(round(s).restored.game.hazards,s.hazards);});
test('Dead enemies, taken supplies and optional survey rewards cannot be recollected on reload',()=>{const s=C.create();s.world.enemies[1].dead=true;s.world.enemies[1].hp=-2;s.kills=1;s.orders.add(s.world.enemies[1].kind);s.world.pickups[4].taken=true;s.discovered.add(12);s.sideRewards.add('survey');const d=round(s).restored.game;a.ok(d.world.enemies[1].dead);a.ok(d.world.pickups[4].taken);a.ok(d.discovered.has(12));a.ok(d.sideRewards.has('survey'));a.equal(d.kills,1);});
test('Scored upper-floor checkpoints restore the same supported elevation across 30 seeds',()=>{for(let i=0;i<30;i++){const s=C.create('REST-'+i),t=s.world.architecture.tower;s.p=[...t.reward];s.head=C.add(s.p,[0,1.65,0]);a.equal(round(s).restored.game.p[1],6.4);}});
test('A pending blessing restores once without duplicating the sector award',()=>{const s=C.create();for(const e of s.world.enemies.filter(e=>e.required!==false)){e.dead=true;e.hp=0;}s.kills=5;s.portalReady=true;s.phase='reward';s.finished=true;s.sectors=1;const bank=P.bank({},s,{});const m={...meta(),banked:5,receipt:bank.receipt};const d=round(s,m,bank.profile);const again=P.bank(d.profile,d.restored.game,d.restored.meta.receipt);a.deepEqual(again.profile.stats,bank.profile.stats);const n=C.reward(d.restored.game,'supplies');a.equal(n.world.depth,2);a.equal(n.kills,5);});
test('Banking receipts and legacy purchases survive repeated continuations',()=>{const s=C.create();s.kills=5;s.hits=23;s.headshots=3;const b=P.bank({shards:8,heart:true,power:true},s);const m={...meta(),banked:5,receipt:b.receipt};let d=round(s,m,b.profile);for(let i=0;i<6;i++){const b2=P.bank(d.profile,d.restored.game,d.restored.meta.receipt);a.deepEqual(b2.profile.stats,b.profile.stats);d=round(d.restored.game,d.restored.meta,b2.profile);}a.ok(d.profile.heart&&d.profile.power&&d.profile.ricochet);a.equal(d.profile.shards,8);});
test('Nightfall rosters and ricochet supply transformations match the saved generator',()=>{const s=C.create('REST-NIGHT',3,{challenge:'nightfall',ricochet:true});const d=round(s).restored.game;a.deepEqual(d.world.enemies,s.world.enemies);a.deepEqual(d.world.pickups,s.world.pickups);a.ok(d.challenge);});
test('Practice, dead runs and AR cannot become scored expedition saves',()=>{for(const change of[s=>s.unscored=true,s=>s.world.ar=true,s=>s.phase='dead',s=>s.health=0]){const s=C.create();change(s);a.throws(()=>S.capture(s,meta()));}});
test('Damaged JSON, wrong checksum and unknown schemas are rejected without throwing into gameplay',()=>{for(const raw of['{','',JSON.stringify({payload:'{}',checksum:'bad'}),'x'.repeat(S.LIMIT+1)])a.equal(S.decode(raw).ok,false);});
test('Unknown generator, invalid position and impossible resource capacities are refused',()=>{for(const change of[d=>d.generator='future',d=>d.state.p=[999,0,999],d=>d.state.health=20000,d=>d.state.ammo.frost=-1,d=>d.meta.banked=4]){const d=S.capture(C.create(),meta());change(d);a.throws(()=>S.restore(d));}});
test('Prototype keys, nonfinite vectors, mismatched identities and unbounded arrays are rejected',()=>{for(const change of[d=>Object.defineProperty(d.state,'__proto__',{value:{},enumerable:true}),d=>d.state.head=[NaN,1,3],d=>d.state.enemies[0].kind='mirror',d=>d.state.arrows=Array(49).fill({})]){const d=S.capture(C.create(),meta());change(d);a.throws(()=>S.restore(d));}});
test('Two store instances refuse stale overwrite rather than duplicating the latest reward transaction',()=>{const m=memory(),x=new S.Store(m),y=new S.Store(m);a.ok(x.write({shards:8},null).ok);const stale=y.write({shards:3},null);a.equal(stale.ok,false);a.equal(S.decode(m.getItem(S.KEY)).profile.shards,8);});
test('Quota failure preserves the complete previous envelope and reports save failure',()=>{const m=memory(),x=new S.Store(m);a.ok(x.write({shards:4},S.capture(C.create(),meta())).ok);const prev=m.getItem(S.KEY);m.setItem=()=>{throw Error('QuotaExceededError');};a.equal(x.write({shards:9},null).ok,false);a.equal(m.getItem(S.KEY),prev);});
test('A failed legacy mirror does not roll back a valid atomic envelope',()=>{const m=memory(),write=m.setItem;m.setItem=(k,v)=>{if(k===S.PROFILE_KEY)throw Error('Mirror failed');write(k,v);};const x=new S.Store(m);a.ok(x.write({shards:11},null).ok);a.equal(S.decode(m.getItem(S.KEY)).profile.shards,11);});
test('Discarding a checkpoint keeps profile and records; corrupt slots need explicit discard',()=>{const m=memory();m.setItem(S.KEY,'bad json');const x=new S.Store(m);a.equal(x.write({shards:8},null).ok,false);a.ok(x.discard({shards:8,heart:true}).ok);const d=S.decode(m.getItem(S.KEY));a.equal(d.checkpoint,null);a.equal(d.profile.shards,8);a.ok(d.profile.heart);});
test('Nonexistent browser storage is a playable failure, not a constructor crash',()=>{const x=new S.Store({getItem(){throw Error('Denied');}});a.ok(x.error);a.equal(x.write({},null).ok,false);});
