const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js'),R=require('../ritual-model.js'),S=require('../resonance-score.js'),P=require('../chronicle.js');
function range(){const s=C.create('RITUAL-TEST');s.world.enemies=[];s.world.solids=[];s.world.pickups=[];s.world.targets=[];s.world.floors=[{x:0,z:0,w:40,d:40,y:0}];s.p=[0,0,0];s.head=[0,1.65,0];return s;}
test('Physical crossbow reload requires a fresh near-handle grab, backward pull, and release',()=>{const r=new R.ReloadGesture();assert.equal(r.update([0,.04,.06],true).active,false);r.update([0,.04,.06],false);assert(r.update([0,.04,.06],true).start);assert.equal(r.update([0,.04,.29],true).progress,1);assert.equal(r.update([0,.04,.29],false).complete,true);assert.equal(r.update([0,.04,.29],false).complete,false);});
test('Short draw reduces physical reload reach without enabling distant or partial grabs',()=>{let r=new R.ReloadGesture();r.update([1,0,0],false);assert.equal(r.update([1,0,0],true).active,false);r.update([0,.04,.06],false);r.update([0,.04,.06],false);r.update([0,.04,.06],true);r.update([0,.04,.18],true);assert.equal(r.update([0,.04,.18],false).complete,false);r=new R.ReloadGesture();r.update([0,.04,.06],false,true,true);r.update([0,.04,.06],true,true,true);r.update([0,.04,.2],true,true,true);assert(r.update([0,.04,.2],false,true,true).complete);});
test('Tracking loss, shield and lateral overextension cancel physical reload',()=>{for(const blocked of[true,false]){const r=new R.ReloadGesture();r.update([0,.04,.06],false);r.update([0,.04,.06],true);r.update([0,.04,.4],true);if(blocked)r.update(null,true,false);else r.update([.8,.04,.4],true);assert.equal(r.update([0,.04,.4],false).complete,false);}});
test('WebXR handedness gives opposite palm normals and a raised palm reveals the familiar',()=>{const a=Math.SQRT1_2,left=[0,0,a,a],right=[0,0,-a,a];assert(Math.abs(R.palmNormal(left,'left')[1]-1)<1e-8);assert(Math.abs(R.palmNormal(right,'right')[1]-1)<1e-8);for(const [q,h]of[[left,'left'],[right,'right']]){assert(R.palmVisible([.2,1.3,-.4],q,h,[0,1.65,0],[0,0,-1]));assert(!R.palmVisible([.2,1.3,.6],q,h,[0,1.65,0],[0,0,-1]));assert(!R.palmVisible([.2,.2,-.4],q,h,[0,1.65,0],[0,0,-1]));}assert(!R.palmVisible([.2,1.3,-.4],[0,0,0,1],'right',[0,1.65,0],[0,0,-1]));});
test('Tactical focus is bounded real-time reserve, never freezes the headset or grants permanent slowdown',()=>{const f=new R.Focus();f.open=true;assert.equal(f.scale,.2);for(let i=0;i<80;i++)f.update(.04,true);assert.equal(f.scale,1);assert.equal(f.remaining,0);f.open=false;for(let i=0;i<180;i++)f.update(.04,true);assert.equal(f.remaining,3);f.open=true;f.slow=false;assert.equal(f.scale,1);f.update(.01,false);assert.equal(f.open,false);assert.equal(R.radialIndex(0,-1,6,3),0);assert.equal(R.radialIndex(.9,.5,6,0),2);});
test('Manual pickups suppress proximity collection and permit one validated line-of-sight pull',()=>{const s=range();s.manualPickups=true;s.health=40;s.world.pickups=[{p:[0,.4,-.3],kind:'health',taken:false}];C.step(s,.02);assert.equal(s.health,40);assert.equal(s.world.pickups[0].taken,false);assert(C.collectPickup(s,0,[0,1.3,-.3],7));assert.equal(s.health,65);assert.equal(C.collectPickup(s,0,[0,1.3,-.3],7),false);assert.equal(s.events.filter(e=>e.type==='pickup').length,1);});
test('Pickup pulls cannot penetrate cover, reach from an untracked distant hand, or grant unknown resources',()=>{const s=range();s.world.pickups=[{p:[0,1,-3],kind:'frost',taken:false}];s.world.solids=[{min:[-2,0,-2],max:[2,3,-1.8]}];assert.equal(C.collectPickup(s,0,[0,1.2,-.2],7),false);s.world.solids=[];assert.equal(C.collectPickup(s,0,[0,1.2,-8],7),false);assert.equal(C.collectPickup(s,0,[0,1.2,-.2],NaN),false);s.world.pickups[0].kind='unknown';assert.equal(C.collectPickup(s,0,[0,1.2,-.2],7),false);});
test('Ricochet arrows have finite ammunition and at most two swept wall reflections',()=>{const s=range();s.ricochetUnlocked=true;s.ammo.ricochet=1;s.world.solids=[{min:[-2,0,-4],max:[2,4,-3.8]},{min:[-2,0,1],max:[2,4,1.2]}];assert(C.fire(s,[0,1.6,-.1],[0,0,-1],1,'ricochet'));assert.equal(s.ammo.ricochet,0);assert.equal(C.fire(s,[0,1.6,-.1],[0,0,-1],1,'ricochet'),false);let previous=s.arrows[0].damage;for(let i=0;i<40;i++)C.step(s,1/90);const events=s.events.filter(e=>e.type==='ricochet');assert(events.length>=1&&events.length<=2);assert(s.arrows.every(a=>a.damage<previous&&a.bounces>=0));for(let i=0;i<400;i++)C.step(s,1/90);assert(s.events.filter(e=>e.type==='ricochet').length<=2);assert.equal(s.arrows.length,0);});
test('Ricochet unlock, saved achievements and future loot preserve old progress without practice farming',()=>{let profile=P.clean({shards:17,heart:true,power:true,stats:{kills:6,headshots:3}});assert(profile.volley&&profile.quickwind);assert(!profile.ricochet);let run={hits:20};let bank=P.bank(profile,run,{},true);assert(!bank.profile.ricochet);bank=P.bank(profile,run);assert(bank.profile.ricochet);assert.equal(P.bank(bank.profile,run,bank.receipt).profile.stats.hits,20);const s=C.create('LOOT',1,bank.profile);assert.equal(s.ammo.ricochet,4);assert(s.world.pickups.some(p=>p.kind==='ricochet'));assert.equal(s.maxHealth,115);s.phase='reward';const next=C.reward(s,'supplies');assert(next.ricochetUnlocked&&next.world.pickups.some(p=>p.kind==='ricochet'));assert.equal(next.ammo.ricochet,7);});
test('Health remains discrete damage/healing state and does not passively regenerate',()=>{const s=range();s.health=37;for(let i=0;i<200;i++)C.step(s,.04);assert.equal(s.health,37);s.weapon='crossbow';s.crossbow.loaded=false;assert(C.reload(s,true));assert.equal(s.crossbow.reload,.48);assert.equal(C.reload(s,true),false);for(let i=0;i<60;i++)C.step(s,1/90);assert(s.crossbow.loaded);});
test('Original score has five complete distinct arrangements and every enemy has a warning vocabulary',()=>{assert.equal(Object.keys(S.themes).length,5);const melodies=new Set();for(const t of Object.values(S.themes)){assert.equal(t.chords.length,8);assert.equal(t.melody.length,32);assert(t.bpm>=55&&t.bpm<=85);melodies.add(JSON.stringify(t.melody));}assert.equal(melodies.size,5);assert.equal(Object.keys(S.enemyFamilies).length,15);for(const k of Object.keys(S.enemyFamilies))assert(S.recipes[S.cue({type:'enemy-windup',kind:k})]);assert.equal(S.cue({type:'shot',weapon:'crossbow',arrow:'plain'}),'crossbow');});
test('Audio settings sanitize malformed preferences without unbounded gain',()=>{const c=S.clean({master:99,music:-4,effects:'nonsense',ambience:.35,dynamic:'boom'});assert.equal(c.master,1);assert.equal(c.music,0);assert.equal(c.dynamic,'headphones');assert(Number.isFinite(c.effects));assert.equal(S.midi(69),440);});
