const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs');
const C=require('../core.js'),M=require('../returning-bell-model.js'),S=require('../pilgrim-save.js');
const make=()=>C.create('RETURNING-BELL',1,{returningBell:true});
const meta=()=>({id:'returning-bell-fixture',banked:0,receipt:{},yaw:0,pitch:0,focus:1});
function walk(s,x,z){let steps=0;while(Math.hypot(x-s.p[0],z-s.p[2])>.025&&steps++<3000){const d=[x-s.p[0],z-s.p[2]],length=Math.hypot(...d),before=[...s.p];C.move(s,d[0]/length*Math.min(.07,length),d[1]/length*Math.min(.07,length));s.head=C.add(s.p,[0,1.65,0]);M.step(s,C);a.ok(C.len(C.sub(s.p,before))>1e-7,'Blocked at '+s.p+' toward '+[x,z]);}a.ok(steps<3000);a.ok(C.walkable(s.world,s.p));}
function path(s,points){for(const p of points)walk(s,...p);}
const west=[[-4,8.5],[-14,8.5],[-14,0],[-14,-11.5]],gallery=[[-14,-21],[0,-21],[0,-24]],east=[[0,2],[7.8,1],[12,1],[13.8,-14],[12,-16],[12,-28],[0,-28],[0,-24]],service=[[0,-28],[20,-28],[20,-16],[20,8],[7.3,8]];
test('Authored layout has one immutable identity, seven purposeful regions and distinct legacy geography',()=>{const s=make();a.equal(s.world.generator,M.ID);a.equal(s.world.rooms.length,7);a.equal(C.create().world.rooms.length,25);a.equal(s.world.enemies.length,5);a.deepEqual(make().world,s.world);a.deepEqual([...s.discovered],[0]);});
for(const raised of [false,true])for(const opened of[false,true])test('Ground and gallery routes are physically traversable with screens '+raised+' and gate '+opened,()=>{for(const points of[[...west,...gallery],east]){const s=make();s.chapter.screensRaised=raised;s.chapter.gateOpen=opened;M.apply(s);path(s,points);a.ok(Math.abs(s.p[1]-3.2)<.001);a.equal(M.available(s,C),'bell');a.ok(C.interact(s));a.ok(s.chapter.bellRung);a.equal(s.kills,0);path(s,service);if(!opened){a.equal(M.available(s,C),'latch');a.ok(C.interact(s));}walk(s,0,8);a.equal(M.available(s,C),'refuge');a.ok(C.interact(s));a.equal(s.phase,'reward');a.equal(s.sectors,1);}});
test('The gallery winch visibly changes shared cover and shot collision and is reversible',()=>{const s=make();path(s,west);walk(s,-12.1,-11.5);a.equal(M.available(s,C),'winch');a.equal(C.segmentBlocked(s.world,[0,1.5,-10],[0,1.5,-16]),true);a.ok(C.interact(s));a.equal(s.chapter.screensRaised,true);a.equal(C.segmentBlocked(s.world,[0,1.5,-10],[0,1.5,-16]),false);a.ok(C.interact(s));a.equal(s.chapter.screensRaised,false);a.equal(C.segmentBlocked(s.world,[0,1.5,-10],[0,1.5,-16]),true);});
test('A blocked screen closure keeps the previous geometry and cannot trap an actor',()=>{const s=make();path(s,west);walk(s,-12.1,-11.5);C.interact(s);s.world.enemies[0].p=[0,1.05,-13];C.interact(s);a.equal(s.chapter.screensRaised,true);a.equal(s.events.at(-1).type,'returning-blocked');});
test('The return gate blocks bodies and shots, opens only from its service side and stays open on reload',()=>{const s=make();walk(s,4.8,8);a.equal(M.available(s,C),null);C.move(s,2,0);a.ok(s.p[0]<5.6);a.equal(C.segmentBlocked(s.world,[4,1.5,8],[8,1.5,8]),true);path(s,[[0,8],...west,...gallery,...service]);a.ok(C.interact(s));a.equal(s.chapter.gateOpen,true);a.equal(C.segmentBlocked(s.world,[4,1.5,8],[8,1.5,8]),false);walk(s,6,8);const d=S.restore(S.capture(s,meta())).game;a.deepEqual(d.chapter,s.chapter);a.deepEqual(d.world.solids,s.world.solids);walk(d,0,8);});
test('Screen state is reconstructed before validating a saved position in the cleared opening',()=>{const s=make();path(s,west);walk(s,-12.1,-11.5);C.interact(s);path(s,[[-14,0],[-14,8.5],[0,8],[0,2],[0,-13]]);const cp=S.capture(s,meta());a.ok(S.restore(cp).game.chapter.screensRaised);cp.state.chapter.screensRaised=false;a.throws(()=>S.restore(cp),/supported/);});
test('Real swept archery can ring the bell from inside the tower without an objective-route trigger',()=>{const s=make();path(s,[...west,...gallery.slice(0,2)]);const d=C.sub(s.world.targets[0],s.head),dist=Math.hypot(d[0],d[2]),v=36,v2=v*v,angle=Math.atan((v2-Math.sqrt(v2*v2-9.8*(9.8*dist*dist+2*d[1]*v2)))/(9.8*dist)),u=C.unit([d[0],0,d[2]]);a.ok(C.fire(s,s.head,[u[0]*Math.cos(angle),Math.sin(angle),u[2]*Math.cos(angle)],1));for(let i=0;i<100;i++)C.step(s,1/90);a.ok(s.chapter.bellRung);a.equal(s.phase,'playing');a.equal(s.kills,0);});
test('A genuine gallery Blink arc and the live projectile agree on the same elevated landing',()=>{const s=make();path(s,[[0,2],[-5.5,0],[-5.5,-7.5]]);let found=null;for(let charge=.16;charge<=.96&&!found;charge+=.08)for(let p=.1;p<1.25;p+=.03){const direction=[-Math.cos(p),Math.sin(p),0],origin=C.add(s.head,C.mul(direction,.18)),t=C.predictBlink(s,origin,direction,charge);if(t.ok&&t.destination[1]>3){found={direction,origin,charge,t};break;}}a.ok(found,'Visible gallery landing has a valid swept trajectory');a.ok(C.fire(s,found.origin,found.direction,found.charge,'blink'));for(let i=0;i<400&&s.blinks===0;i++)C.step(s,1/90);a.equal(s.blinks,1);a.ok(C.len(C.sub(s.p,found.t.destination))<.03);});
test('Closed tower facade prevents ringing the signal from the starting refuge',()=>{const s=make();a.equal(C.segmentBlocked(s.world,s.head,s.world.targets[0]),true);});
test('Chapter victory is outcome-based, nonrepeating and passes counters into retained Endless content',()=>{const s=make();path(s,[...west,...gallery]);C.interact(s);path(s,service);C.interact(s);walk(s,0,8);C.interact(s);a.equal(C.interact(s),false);a.equal(s.sectors,1);const cp=S.capture(s,meta()),d=S.restore(cp).game;a.equal(d.phase,'reward');const n=C.reward(d,'power');a.equal(n.chapter,undefined);a.equal(n.world.rooms.length,25);a.equal(n.sectors,1);a.equal(n.world.depth,2);});
test('Malformed chapter payloads, wrong identities and impossible outcomes are rejected',()=>{for(const alter of[c=>c.generator='returning-bell-99',c=>c.state.chapter.returned=true,c=>c.state.chapter.extra=2,c=>c.state.chapter.screensRaised='yes',c=>c.state.chapter.bellRung=true,c=>c.state.discovered.push(24),c=>c.state.chapter=null,c=>c.generator=S.GENERATOR]){const cp=S.capture(make(),meta());alter(cp);a.throws(()=>S.restore(cp));}});
test('The prior published Surestep checkpoint keeps exact old geography, resources and equipment',()=>{const cp=JSON.parse(fs.readFileSync(__dirname+'/fixtures/legacy-surestep-checkpoint.json','utf8')),d=S.restore(cp).game;a.equal(d.chapter,undefined);a.equal(d.world.rooms.length,25);a.equal(d.health,67);a.equal(d.ammo.frost,2);a.ok(d.ricochetUnlocked);a.equal(S.capture(d,cp.meta).generator,'hollow-dominions-1');});
test('AR surveys disclose only visited regions and cannot mutate the expedition',()=>{const s=make(),first=M.survey(s);a.deepEqual(first.discovered,[0]);path(s,west);const view=M.survey(s);a.ok(view.discovered.includes(3));a.ok(!view.discovered.includes(6));view.chapter.gateOpen=true;view.discovered.push(6);a.equal(s.chapter.gateOpen,false);a.ok(!s.discovered.has(6));a.deepEqual(M.survey(null).discovered,[0]);});
