'use strict';
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),S=require('../rosefire-shaders.js');
test('Rosefire normalizes malformed preferences without changing source objects',()=>{for(const v of [null,5,'bad',[],{}])a.equal(S.settings(v).mode,'balanced');const raw={mode:'cinematic',wet:false,rose:true,ward:false};a.deepEqual(S.settings(raw),raw);a.equal(S.settings({mode:'ultra'}).mode,'balanced');});
test('Off and Classic disable all added world and equipment effects',()=>{for(const p of [S.policy({mode:'off'}),S.policy({}, {materialMode:'classic'})])for(const key of ['enabled','world','wet','rose','ward','sky','wakes','cinematic'])a.equal(p[key],false,key);});
test('VR caps source count, ring pool and Cinematic detail without screen-space passes',()=>{const p=S.policy({mode:'cinematic'},{xr:true});a.equal(p.cinematic,false);a.equal(p.roseCount,2);a.equal(p.maxWakes,3);a.equal(p.ward,true);});
test('AR keeps only the requested equipment effect and never paints passthrough',()=>{const p=S.policy({mode:'cinematic'},{ar:true,xr:true});for(const key of ['world','wet','rose','sky','wakes','cinematic'])a.equal(p[key],false,key);a.equal(p.ward,true);a.equal(S.policy({ward:false},{ar:true}).ward,false);});
test('Reduced and effects-off policies freeze motion and remove landing echoes',()=>{for(const context of [{reduced:true},{effects:false}]){const p=S.policy({},context);a.equal(p.animated,false);a.equal(p.wakes,false);a.equal(p.rose,true);}});
test('Independent wet stone, stained light and ward controls are honored',()=>{const p=S.policy({wet:false,rose:false,ward:false});for(const key of ['wet','rose','ward'])a.equal(p[key],false);});
test('Nearest stained sources are bounded, finite, stable and distance-culled',()=>{const points=[[10,0,3,0],[1,1,4,.5],[-2,1,3,0],[90,0,3,0],[NaN,0,3,0]],copy=JSON.stringify(points);a.deepEqual(S.selectSources(points,[0,2,0],2),[points[1],points[2]]);a.equal(JSON.stringify(points),copy);a.equal(S.selectSources(points,[1000,0,1000]).length,0);});
test('Surface shader patch preserves normal-map and AO pipeline chunks',()=>{const shader={uniforms:{prior:1},vertexShader:'#include <common>\n#include <project_vertex>',fragmentShader:['common','color_fragment','roughnessmap_fragment','normal_fragment_maps','emissivemap_fragment'].map(c=>'#include <'+c+'>').join('\n')};const uniform={value:1};S.patch(shader,{uRFWet:uniform});a.equal(shader.uniforms.uRFWet,uniform);a.equal(shader.uniforms.prior,1);a.ok(shader.vertexShader.includes('instanceMatrix*rfP'));a.ok(shader.fragmentShader.includes('#include <normal_fragment_maps>'));a.ok(shader.fragmentShader.includes('abs(vRFWorld.y)<.12'));});
test('An incompatible upstream material shader is rejected explicitly',()=>{a.throws(()=>S.patch({uniforms:{},vertexShader:'',fragmentShader:''},{}),/chunk missing/);});
test('Sky and shield outputs keep the existing renderer color transform',()=>{for(const key of ['skyFragment','ward','wake']){a.ok(S[key].includes('tonemapping_fragment'));a.ok(S[key].includes('colorspace_fragment'));}});
test('Presentation module has no gameplay, storage-key, render-target or camera-pose replacement',()=>{const code=fs.readFileSync(require.resolve('../rosefire.js'),'utf8');for(const v of ['WebGLRenderTarget','new T.WebGLRenderer','vesperfall-profile-v1','vesperfall-expedition-v1','g.game=','g.build=','s.health=','s.score=','g.rig.position'])a.ok(!code.includes(v),v);a.ok(code.includes('Array.from({length:6}'));a.ok(code.includes("['blink','shard'].includes(e.type)"));});

test('Sector rebuilding retires all old landing timestamps before the new clock advances',()=>{let component;require('node:vm').runInNewContext(fs.readFileSync(require.resolve('../rosefire.js'),'utf8'),{RosefireShaders:S,AFRAME:{registerComponent:(name,c)=>{component=c;}}});const world={ar:true},wakes=[{born:2,mesh:{visible:true}},{born:200,mesh:{visible:false}}],context={g:{game:{world,eventSeq:81},arMode:true},j:{},wakes,stats:{builds:0}};component.rebuild.call(context);a.equal(context.world,world);a.equal(context.lastEvent,81);a.equal(context.stats.builds,1);for(const w of wakes){a.equal(w.born,-Infinity);a.equal(w.mesh.visible,false);for(const t of [0,2,200,100000])a.equal((t-w.born)/1.1<1,false);}});
