/* Isolated deterministic physics fixtures, not player-state browser acceptance. */
'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../core'),M=require('../sureflight-model'),E=require('../pilgrim-echoes-model'),S=require('../pilgrim-save');
function field(){const s=C.create('BELL-01');s.world={...s.world,floors:[{x:0,z:0,w:200,d:200,y:0}],solids:[],enemies:[],targets:[],dominions:false};return s;}
function tick(s,n){for(let i=0;i<n;i++)C.step(s,1/90,s.head);}
const wall={min:[-4,0,-.2],max:[4,5,0],type:'wall'};
function hit(b,p=[0,1.4,.02],v=[0,-1,-12],s=field()){s.world.solids.push(b);return {s,result:C.resolveBlink(s,{kind:'wall',box:b,p},v)};}
test('Wall impacts recover next to the hit face, never behind it',()=>{const {s,result:r}=hit(wall);a.ok(r.ok,r.reason);a.ok(r.p[2]>.28);a.ok(C.walkable(s.world,r.p));});
test('An exterior wall with no floor on the hit side does not strand the player in an abyss',()=>{const s=field();s.world.floors=[{x:0,z:-3,w:8,d:5,y:0}];a.equal(hit(wall,undefined,undefined,s).result.ok,false);});
test('A high wall hit can settle on the supported floor below on the same side',()=>{const {result:r}=hit({...wall,max:[4,12,0]},[0,9,.02]);a.ok(r.ok,r.reason);a.equal(r.p[1],0);a.ok(r.p[2]>.28);});
test('A ceiling underside cannot turn into a rooftop landing',()=>{const b={min:[-3,3,-3],max:[3,3.2,3],type:'roof'};a.equal(hit(b,[0,2.98,0],[0,8,0]).result.ok,false);});
test('A structural bridge rail accepts a supported narrow perch',()=>{const b={min:[-.1,0,-3],max:[.1,1,-1],type:'balustrade'},r=hit(b,[0,1.02,-2],[0,-8,0]);a.ok(r.result.ok,r.result.reason);a.equal(r.result.p[1],1);a.ok(C.walkable(r.s.world,r.result.p,.42));});
test('A stair railing hit from its side reaches the actual top, not a fictional nearby floor',()=>{const b={min:[-.1,2,-3],max:[.1,2.8,-1],type:'balustrade'},r=hit(b,[.12,2.3,-2],[-8,0,0]);a.ok(r.result.ok,r.result.reason);a.equal(r.result.p[1],2.8);});
test('Rail ascent is rejected if another ceiling occupies the body above it',()=>{const s=field();s.world.solids.push({min:[-2,1.4,-4],max:[2,2,-.5],type:'roof'});const b={min:[-.1,0,-3],max:[.1,1,-1],type:'balustrade'};a.equal(hit(b,[0,1.02,-2],[0,-8,0],s).result.ok,false);});
test('Rail sides cannot be used from below to pass through their underside',()=>{const b={min:[-2,3,-3],max:[2,3.3,-1],type:'balustrade'};a.equal(hit(b,[0,2.98,-2],[0,8,0]).result.ok,false);});
test('Wall fallback cannot descend through a roof into a hidden lower floor',()=>{const s=field();s.world.solids.push({min:[-3,2,.1],max:[3,2.3,2],type:'roof'});a.equal(hit(wall,[0,4,.02],[0,-1,-12],s).result.ok,false);});
test('Floor-edge recovery stays near the actual impact and has body clearance',()=>{const s=field();s.world.floors=[{x:0,z:0,w:4,d:4,y:0}];const r=C.resolveBlink(s,{kind:'floor',p:[1.98,0,0]},[1,-4,0]);a.ok(r.ok,r.reason);a.ok(r.p[0]<1.75);a.ok(C.len(C.sub(r.p,[1.98,0,0]))<1);});
test('Occupied impact can recover nearby without landing on a living monster',()=>{const s=field();s.world.enemies=[{p:[.7,1.05,0],dead:false}];const r=C.resolveBlink(s,{kind:'floor',p:[0,0,0]},[0,-8,0]);a.ok(r.ok,r.reason);a.ok(Math.hypot(r.p[0]-.7,r.p[2])>=1.25);});
test('No generic wall-top permission or movement through a closed shutter is introduced',()=>{const s=field(),b={min:[-2,0,-1],max:[2,4,1],type:'pilgrim-shutter'};s.world.solids.push(b);a.equal(C.landing(s,[0,4,0]).ok,false);a.equal(M.canPerch(b),false);});
test('Long-flight golden arrow physically lands after four seconds and matches preview',()=>{const s=field();s.world.floors.push({x:0,z:0,w:2,d:2,y:20});s.p=[0,20,0];s.head=[0,21.65,0];const d=C.unit([0,1,-.15]);const predicted=C.predictBlink(s,s.head,d,1);a.ok(predicted.ok,predicted.reason);a.ok(predicted.ticks>360);a.ok(C.fire(s,s.head,d,1,'blink'));tick(s,360);a.equal(s.blinks,0);a.ok(s.arrows.length);tick(s,180);a.equal(s.blinks,1);a.deepEqual(s.p,predicted.destination);});
test('Arrow fired from height is not destroyed at an arbitrary travel distance',()=>{const s=field();s.world.floors.push({x:0,z:0,w:4,d:4,y:90});s.p=[0,90,0];s.head=[0,91.65,0];const d=C.unit([0,.6,-1]);const p=C.predictBlink(s,s.head,d,1);a.ok(p.ok,p.reason);a.ok(Math.abs(p.destination[2])>50);C.fire(s,s.head,d,1,'blink');tick(s,1000);a.equal(s.blinks,1);a.deepEqual(s.p,p.destination);});
test('Missing ground below a shot produces an explained failure, not an invented rescue floor',()=>{const s=field();s.world.floors=[{x:0,z:0,w:2,d:2,y:0}];s.p=[0,0,0];s.head=[0,1.65,0];C.fire(s,s.head,[0,0,-1],1,'blink');tick(s,600);a.equal(s.blinks,0);a.equal(s.arrows.length,0);a.match(s.events.find(e=>e.type==='blink-denied').reason,/supporting surface/);});
test('Teleport immediately relocates the damage target with the actor',()=>{const s=field(),before=[...s.head],pos=[...s.p];a.ok(C.blink(s,[5,0,0]));a.deepEqual(s.head,C.add(before,C.sub(s.p,pos)));});
test('Saved legacy and new-generator rail perches restore their exact supported positions',()=>{for(const upgrades of[{}, {returningBell:'returning-bell-2'}, {pilgrimage:{stage:0,tier:0}}, {pilgrimage:{stage:1,tier:0}}]){const s=C.create('BELL-01',upgrades.pilgrimage?.stage===1?2:1,upgrades);const b=s.world.solids.find(b=>M.canPerch(b)&&b.type==='balustrade');const p=[(b.min[0]+b.max[0])/2,b.max[1],(b.min[2]+b.max[2])/2];a.ok(C.blink(s,p));const cp=S.capture(s,{id:'sureflight-fixture-0001',banked:0,receipt:{},yaw:0,pitch:0,focus:1});a.deepEqual(S.restore(cp).game.p,p);}});
test('Original floorplan signatures are unchanged by travel support',()=>{const s=C.create('BELL-01',1,{pilgrimage:{stage:0,tier:0}}),before=JSON.stringify(s.world);for(const b of s.world.solids.filter(M.canPerch))C.landing(s,[(b.min[0]+b.max[0])/2,b.max[1],(b.min[2]+b.max[2])/2]);a.equal(JSON.stringify(s.world),before);});
test('Floor messages fade in the final half second and disappear at two seconds',()=>{a.equal(E.opacity(0),1);a.equal(E.opacity(1499),1);a.equal(E.opacity(1750),.5);a.equal(E.opacity(2000),0);a.equal(E.opacity(9999),0);});
test('The two chapters provide distinct stable, supported story objects without rewards or new objectives',()=>{for(let stage=0;stage<2;stage++){const s=C.create('BELL-01',stage+1,{pilgrimage:{stage,tier:0}}),before=JSON.stringify(s),notes=E.anchors(s);a.equal(notes.length,3);for(const n of notes)a.ok(C.walkable(s.world,n.p));a.equal(JSON.stringify(s),before);}});
test('The story journal accepts known IDs only and bounds malformed local data',()=>{a.deepEqual(E.clean(['causeway-slate','causeway-slate','__proto__','unknown']),['causeway-slate']);a.deepEqual(E.clean({}),[]);});
