from pathlib import Path
import json,hashlib,subprocess
root=Path(__file__).resolve().parents[1]
pins=json.loads((root/'tools/skyglass-baselines.json').read_text())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for name,expected in pins.items():
 assert name.startswith(('planning/','tests/')) or '/' not in name
 assert sha(root/name)==expected['before'],'Original changed: '+name
def edit(name,old,new):
 p=root/name;s=p.read_text();assert s.count(old)==1,(name,old,s.count(old));p.write_text(s.replace(old,new))
edit('scene.mjs',"import {expeditionScene}","import {installCast} from './cast-scene.mjs';\nimport {installCloudShade} from './skyglass-shaders.mjs';\nimport {expeditionScene}")
edit('scene.mjs'," const luminous=installLuminousArt({scene,camera,renderer,quality,relays});", " const luminous=installLuminousArt({scene,camera,renderer,quality,relays});\n const cast=installCast({scene}),shade=installCloudShade(decks);let skyglassEnabled=true;\n scene.userData.skyglass={enabled:true,mode:quality,clock:0,motion:1};quayArt.ready.then(()=>shade.attach());")
edit('scene.mjs',"function update(state,dt,menu=false,reduced=false){expeditionArt.update", "function update(state,dt,menu=false,reduced=false){const xr=renderer.xr.isPresenting,mode=luminous.stats().requested;cast.update(state,dt,{menu,reduced,mode,xr});shade.update(state.time,{reduced,quality:mode,immersive:xr});Object.assign(scene.userData.skyglass,{enabled:skyglassEnabled,mode:xr?'low':mode,clock:reduced?0:state.time,motion:reduced?0:1});expeditionArt.update")
edit('scene.mjs',"setVisualMode:mode=>luminous.setMode(mode),", "setVisualMode:mode=>luminous.setMode(mode),setCastEnabled:v=>cast.setEnabled(v),setSkyglassEnabled:v=>{skyglassEnabled=!!v;shade.setEnabled(v);scene.userData.skyglass.enabled=!!v;},")
edit('scene.mjs',"visual:luminous.stats(),", "visual:luminous.stats(),cast:cast.stats(),skyglass:shade.stats(),")
edit('expedition-scene.mjs',"for(const b of s.drones){if(!b.humanoid||b.hp<=0||", "for(const b of s.drones){if(scene.userData.castHas?.(b.id)||!b.humanoid||b.hp<=0||")
edit('expedition-scene.mjs',"if(Math.hypot(e.escort.x-s.p.x,e.escort.z-s.p.z)<125){", "if(!scene.userData.castHas?.('surveyor')&&Math.hypot(e.escort.x-s.p.x,e.escort.z-s.p.z)<125){")
edit('foundry-kit.mjs',"import * as T from './vendor/three.module.js';", "import * as T from './vendor/three.module.js';\nimport {makeRiftMaterial} from './skyglass-shaders.mjs';")
edit('foundry-kit.mjs',"new T.MeshBasicMaterial({color:'#8be1d5',wireframe:true,transparent:true,opacity:.22,depthWrite:false})", "makeRiftMaterial()")
edit('foundry-art.mjs',"tavi.visible=!menu&&Math.hypot", "tavi.visible=!menu&&!scene.userData.castHas?.('tavi')&&Math.hypot")
edit('foundry-art.mjs',"dynamicCount=0;const c=k.companion;", "dynamicCount=0;const sky=scene.userData.skyglass;kit.materials.ghost.uniforms.clock.value=reduced?0:s.time;kit.materials.ghost.uniforms.motion.value=!reduced&&sky?.enabled!==false&&sky?.mode!=='low'?1:0;const c=k.companion;")
edit('app.mjs',"view.stats().visual.requested].join('|')", "view.stats().visual.requested,view.stats().cast.enabled,view.stats().skyglass.enabled].join('|')")

edit('tests/foundry-browser.py',"check(snap()['renderer']['foundry']['companionVisible'],", "check(snap()['renderer']['foundry']['companionVisible'] or any(a['id']=='tavi' for a in snap()['renderer']['cast']['actors']),")
edit('model.mjs',"VERSION='0.9.0'","VERSION='0.10.0'")
edit('app.mjs','Bellwether Blackout v0.9.0 ready - street combat, Arcade circuits, rooftop signal defense and a lasting district ending','Skyglass Cast v0.10.0 ready - animated human characters, spectral rifts and moving cloud light')
for old,new in [('Aether Reach · Bellwether Blackout','Aether Reach · Skyglass Cast'),('<i>0.9.0</i>','<i>0.10.0</i>'),('EXPEDITION 06 <span>BELLWETHER BLACKOUT</span>','EXPEDITION 07 <span>SKYGLASS CAST</span>'),('NEW / Bellwether Blackout.','NEW / Skyglass Cast. Animated people and luminous rifts join the city.'),('THE BELLWETHER BLACKOUT ADVENTURE.','THE SKYGLASS CAST UPDATE.')]:edit('index.html',old,new)
p=root/'release.json';j=json.loads(p.read_text());j.update(version='0.10.0',focus='Skyglass Cast: three licensed CC0 animated human models, bounded nearby cast with safe fallbacks, spectral rift surfaces and moving cloud light');p.write_text(json.dumps(j,indent=2)+'\n')
edit('tests/public-build.test.mjs',"const runtime=[", "const runtime=['cast-rig.mjs','cast-scene.mjs','skyglass-shaders.mjs',")
edit('tests/release-manifest.mjs',"export const files=", "const characters=JSON.parse(fs.readFileSync(path.join(root,'aether-reach/art/characters/manifest.json'),'utf8'));\nfor(const f of characters.files){if(path.basename(f.file)!==f.file)throw Error('Unsafe character path');if(createHash('sha256').update(fs.readFileSync(path.join(root,'aether-reach/art/characters',f.file))).digest('hex')!==f.sha256)throw Error('Character digest mismatch: '+f.file);}\nexport const files=")
edit('tests/release-manifest.mjs',"...['combat-gestures.mjs'", "...['cast-rig.mjs','cast-scene.mjs','skyglass-shaders.mjs','SKYGLASS-CAST.md','art/characters/manifest.json',...characters.files.map(f=>'art/characters/'+f.file),'combat-gestures.mjs'")
(root/'visual-settings.mjs').write_text("/* Local presentation preferences; never touches expedition/economy saves. */\nexport function installVisualSettings(view){\n const key='aether-reach.visual.v1';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}\n let mode=['prismatic','balanced','low'].includes(saved.mode)?saved.mode:view.stats().visual.requested;\n let characters=saved.characters!==false,skyglass=saved.skyglass!==false;\n function persist(){try{localStorage.setItem(key,JSON.stringify({version:1,mode,characters,skyglass}));}catch{}}\n view.setVisualMode(mode);view.setCastEnabled(characters);view.setSkyglassEnabled(skyglass);\n const grid=document.querySelector('.settings-grid'),label=document.createElement('label');label.textContent='Materials & effects';const select=document.createElement('select');select.id='visual-quality';select.setAttribute('aria-label','Materials and effects quality');for(const [value,text] of [['prismatic','Prismatic - refractive jewels & glass'],['balanced','Balanced - reflective glass, no refraction pass'],['low','Light - fewer effects, no shadows']]){const option=document.createElement('option');option.value=value;option.textContent=text;select.append(option);}select.value=mode;label.append(select);grid.append(label);\n select.onchange=()=>{mode=select.value;view.setVisualMode(mode);persist();};\n for(const [id,text,value,change] of [['visual-characters','Animated character models',characters,v=>{characters=v;view.setCastEnabled(v);}],['visual-skyglass','Skyglass rifts and moving cloud shade',skyglass,v=>{skyglass=v;view.setSkyglassEnabled(v);}]] ){\n  const row=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.id=id;input.checked=value;input.onchange=()=>{change(input.checked);persist();};row.append(input,document.createTextNode(' '+text));grid.append(row);\n }\n const note=document.createElement('p');note.className='fine';note.textContent='Nearby people use licensed animated models, with simpler silhouettes at distance or while loading. Light and immersive VR limit the animated cast and use static rift outlines; moving cloud shade is disabled. Reduced motion freezes decorative shader motion. Hardware performance remains unverified.';document.querySelector('#settings-dialog form').before(note);\n}\n")
p=root/'roadmap.json';j=json.loads(p.read_text());j.update(release='0.10.0 Skyglass Cast',updated='2026-09-12');tasks={t['id']:t for t in j['tasks']}
updates={'P02': {'status': 'In review', 'evidence': 'v0.10 adds creator-published CC0 female adventurer, armored guard and suited officer with real skeletons and clip blending. Complete authored first-person hands, custom character art and weapon reload animation remain open.', 'next': 'Inspect moving characters, hand/weapon alignment and role readability at game distances; continue original character production.'}, 'P03': {'status': 'In review', 'evidence': 'v0.10 adds original spectral rift and cloud-light shaders without extra render passes. City-wide architectural polish remains incomplete.', 'next': 'Review scene consistency and measure the Balanced, Light and immersive performance budgets on real hardware.'}, 'R04': {'evidence': 'v0.9 committed at cf1dc621dbc392be99380c7fbe51776b90ead068 after 201 tests and 28 full district browser checks. v0.10 must match the post-merge live runtime contract.', 'next': 'Record the v0.10 merge, Pages status and matching live-file hashes.'}}
for id,fields in updates.items():tasks[id].update(fields)
j['tasks'].extend([{'id': 'F03', 'phase': 'Presentation', 'title': 'Skyglass animated cast and bounded shaders', 'priority': 'P0', 'status': 'In review', 'depends': ['F01', 'P02'], 'acceptance': 'License-pinned local character assets, independent animated skeletons, visible fallbacks on failed loads, reduced-motion and Light/XR budgets, controller-accessible graphics options and real WebGL compile validation.', 'evidence': 'art/characters/manifest.json; cast-rig.mjs; cast-scene.mjs; skyglass-shaders.mjs; tests/cast.test.mjs; tests/skyglass-browser.py.', 'next': 'Record browser and publication evidence; keep physical hardware and player art approval separate.'}]);p.write_text(json.dumps(j,indent=2)+'\n')
edit('roadmap.html','Bellwether Blackout v0.9.0','Skyglass Cast v0.10.0')
edit('roadmap.mjs','Current production checklist / v0.9','Current production checklist / v0.10')
edit('planning/README.md','v0.9 plan','v0.10 plan')
subprocess.run(['python',str(root/'tools/render-production-plan.py')],check=True)
for name,expected in pins.items():assert sha(root/name)==expected['after'],'Integration differs: '+name
print('All existing-file integrations match the locally tested source.')
