'use strict';
const fs=require('node:fs'),path=require('node:path');
const data=JSON.parse(fs.readFileSync(path.join(__dirname,'notebook.json'),'utf8'));
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const href=(name,url)=>{const parsed=new URL(url,'https://v5ma.github.io/theology-wiki/research-expansion-20260918/');if(parsed.protocol!=='https:')throw Error('Unsafe source URL');return '<a href="'+esc(url)+'">'+esc(name)+'</a>';};
const records=data.evidence.map(r=>'<article class="record" id="'+esc(r.id)+'" data-kind="'+esc(r.kind)+'"><p class="meta">'+esc(r.kind)+'</p><h3>'+esc(r.title)+'</h3><p>'+esc(r.record)+'</p><p>Research implication: '+esc(r.implication)+'</p><p>Scope: '+esc(r.limits)+'</p><details><summary>Source links</summary>'+r.sources.map((s,i)=>'<p>'+href('Source '+(i+1),s)+'</p>').join('')+'</details></article>').join('\n');
const scenarios=data.scenarios.map(r=>'<article class="scenario" id="'+esc(r.id)+'"><p class="meta">Conditional scenario / registered '+r.registered+' / review '+r.review_date+'</p><h3>'+esc(r.geography)+'</h3><p>Trigger: '+esc(r.trigger)+'</p><p>Conditional projection: '+esc(r.conditional_projection)+'</p><p>Observe: '+esc(r.measure)+'</p><p>Alternative: '+esc(r.alternative)+'</p><p>Assessment: '+esc(r.status)+'. The review date is not a predicted event date.</p><p>'+r.evidence_ids.map(id=>href('Related evidence '+id,'#'+id)).join(' / ')+'</p></article>').join('\n');
const types=[...new Set(data.evidence.map(r=>r.kind))].sort();
const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Theology Wiki | Identity, agency and scarcity</title><meta name="description" content="Evidence constraints, attributed scriptural portrayals and dated 2027 scenarios linked to three full Theology Wiki articles."><style>\n'+
':root{color-scheme:dark;font:17px/1.65 system-ui,sans-serif;background:#111923;color:#eff3f7}*{box-sizing:border-box}body{max-width:1050px;margin:auto;padding:26px}a{color:#a6d4ee;text-underline-offset:3px}h1,h2,h3{line-height:1.25}h1{font-size:clamp(2rem,4vw,3rem)}header{border-bottom:1px solid #738495;padding:16px 0 24px}nav,.controls{display:flex;gap:18px;flex-wrap:wrap}article{margin:20px 0;padding:20px;border:1px solid #66798d;border-left:4px solid #a2bfd5;border-radius:4px;overflow-wrap:anywhere}.meta{color:#bdcedd}.notice{border:1px solid #66798d;padding:16px}label{display:flex;flex-direction:column;gap:4px}.controls{margin:20px 0;align-items:end}input,select,button{font:inherit;color:inherit;background:#243345;border:1px solid #9aabbc;border-radius:4px;padding:9px;max-width:100%}input{width:280px}summary,button{cursor:pointer}:focus-visible{outline:3px solid #f3d086;outline-offset:3px}[hidden]{display:none!important}section{margin:30px 0}footer{border-top:1px solid #738495;margin-top:30px;padding:20px 0}@media(max-width:540px){body{padding:16px}.controls{display:block}label{margin:12px 0}input{width:100%}article{padding:16px}}@media print{:root{background:white;color:black}a,.meta{color:black}.controls{display:none}article{break-inside:avoid}}\n'+
'</style></head><body><header><p class="meta">THEOLOGY WIKI / RESEARCH NOTEBOOK / SEPTEMBER 18, 2026</p><h1>Identity, divine agency and scarcity</h1><p>'+esc(data.scope)+'</p><nav>'+data.articles.map(a=>href(a.title,'../san-reader.html?page='+a.slug)).join('')+'</nav></header><main><section><h2>Three connected investigations</h2><p>The full arguments are integrated into the main Wiki articles above. The same source supplements remain available here as '+data.articles.map(a=>href(a.title,a.source)).join('; ')+'.</p><p class="notice">'+esc(data.earlier_material)+'</p><p>'+href('Downloadable evidence and scenario data','notebook.json')+' / '+href('Edition and preservation notes','README.md')+'</p></section><section id="evidence"><h2>Evidence, interpretation and constraints</h2><div class="controls"><label>Search reviewed records<input id="query" type="search"></label><label>Record type<select id="kind"><option value="">All types</option>'+types.map(t=>'<option value="'+esc(t)+'">'+esc(t)+'</option>').join('')+'</select></label><button id="reset" type="button">Reset</button></div><p id="count" role="status" aria-live="polite">14 evidence records are visible.</p><p id="empty" hidden>No evidence records match these filters.</p>'+records+'</section><section id="scenarios"><h2>Six conditional scenarios into 2027</h2><p>'+esc(data.forecast_rules)+'</p>'+scenarios+'</section><noscript><p>All records and source links remain readable without JavaScript.</p></noscript></main><footer><p>Source review and editorial registration: September 18, 2026. Textual testimony, philosophical interpretation and empirical forecasts retain their separate evidence requirements.</p></footer><script src="reader.js"></script></body></html>\n';
fs.writeFileSync(path.join(__dirname,'index.html'),html);console.log(JSON.stringify({evidence:data.evidence.length,scenarios:data.scenarios.length,mainArticles:data.articles.length}));
