import * as T from './vendor/three.module.js';
import {BUILDINGS,BONEYARDS,HARBORS,SALVAGE,RACE_GATES,EXTRA_ROADS,LAND_RADIUS,LESSONS,RANCH_BUILD,SCALE_REFERENCE,CoastRace,readRanch,saveRanch,distance,surfaceAt} from './ranch-data.js';
import {PENS,penState,insidePen,deterAnimal,speciesById} from './frontier-data.js?v=ranch1';
import {buildRanchWorld} from './ranch-world.js';
const $=id=>document.getElementById(id);
const fmt=s=>Number.isFinite(s)?Math.floor(s/60)+':'+(s%60).toFixed(1).padStart(4,'0'):'--';
export function calibrateResident(a){
 let size=new T.Box3().setFromObject(a.model).getSize(new T.Vector3());const nominal=SCALE_REFERENCE[a.species];
 if(nominal){const target=nominal*(a.pen==='north-nursery'?.65:1);a.model.scale.multiplyScalar(target/size.z);size=new T.Box3().setFromObject(a.model).getSize(new T.Vector3());a.radius=Math.max(.5,Math.min(4.8,size.x*.44));}
 a.model.userData.lengthMeters=size.z;a.model.userData.nominalLength=nominal||null;a.collisionHeight=Math.max(1,Math.min(5,size.y*.72));return a;
}
export function scaleNote(id){const n=SCALE_REFERENCE[id];return n?`Nominal adult model length: ${n} m, calibrated against the Natural History Museum Dino Directory. Nursery residents are smaller. Shape, gait and collision body remain stylized.`:'This species uses a gameplay-scale procedural model. Its proportions have not yet been calibrated against a fossil reconstruction.';}
export class RanchGame{
 constructor(ctx){this.ctx=ctx;this.s=readRanch(ctx.storage);this.world=buildRanchWorld(ctx.scene,ctx.physics);this.race=new CoastRace();this.activity=this.s.guided&&this.s.tutorial<LESSONS.length?'school':null;this.roundup=null;this.clock=0;this.notice=0;this.hornCool=0;this.feedbackUntil=0;this.baseline={...ctx.fleet.position};this.lastHit='Aim at a dinosaur: the colored halo confirms its response.';this.currentLesson=-1;
  this.installUI();window.addEventListener('dino-spectacle',e=>{const d=e.detail||{};if(d.type==='trade-buy')this.mark('trade');if(d.type==='crew-delivery'){this.s.crewDeliveries++;if(d.index===0){const p=PENS.find(p=>p.id==='armored-valley');penState(ctx.state,p).fed=true;}window.__dinoEconomy?.crewDelivery?.(d.index);this.save();}});
  window.__dinoRanch={get state(){return ctx.ranchSnapshot();},open:()=>this.open()};
 }
 save(){return saveRanch(this.ctx.storage,this.s);}
 reward(tag,credits,repeat=false){if(!repeat&&this.s.rewards.includes(tag))return; if(!repeat)this.s.rewards.push(tag);window.__dinoEconomy?.grant?.(credits,repeat?null:'ranch:'+tag);this.save();this.ctx.audio.mission?.();this.ctx.notify(`Assignment complete. ${credits} credits added to your Supply Exchange balance.`);}
 mark(id){if(!this.s.done.includes(id)){this.s.done.push(id);this.save();}while(this.s.tutorial<LESSONS.length&&this.s.done.includes(LESSONS[this.s.tutorial][0]))this.s.tutorial++;if(this.s.tutorial===LESSONS.length&&this.s.guided){this.s.guided=false;if(this.activity==='school')this.activity=null;this.reward('school',500);this.ctx.radio('Field school complete. Dispatch now offers coastal races, ranching, skyline archives and crew assignments.');}this.save();}
 start(){if(!this.s.welcomed){this.s.welcomed=true;this.save();this.ctx.info('YOUR FIRST RANGER SHIFT','Learn by doing.','<p>First, drive through the gold marker beyond the visitor center. Then dispatch teaches the horn, pressure hose, zapper, pen management, trading, boat and helicopter.</p><p>Your current assignment and controls always appear in the assignment panel. A / E interacts. Y / F leaves a vehicle. B closes every panel.</p><p>Open Menu and choose <b>Dispatch and guided lessons</b> whenever you need a demonstration, a different activity, or free exploration. Your old missions and saves are still here.</p>');}}
 installUI(){
  const style=document.createElement('style');style.textContent=`#ranch-status{position:fixed;top:315px;right:20px;width:min(290px,30vw);padding:12px 15px;z-index:12;background:#14372de8;border:1px solid #b4ccb25c;border-radius:10px;color:#e5e9cf;pointer-events:none;font:12px/1.45 system-ui}#ranch-status strong{display:block;color:#f8d58a;font-size:14px;margin-bottom:5px}#ranch-status small{display:block;color:#a7d1c1;margin-top:7px}.ranch-job{padding:14px;border:1px solid #8fae8455;border-radius:10px;margin:9px 0;background:#183c32}.ranch-job h3{margin:0;color:#f1d69b}.ranch-job p{margin:7px 0 12px;font-size:14px}.ranch-job button{margin:3px}.ranch-stats{color:#a9d5c1}.ranch-highlight{box-shadow:0 0 0 2px #f9d477,0 0 22px #f2bc4e66!important}.ranch-help{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}@media(max-width:780px){#ranch-status{top:220px;right:9px;width:180px;font-size:10px;padding:8px}#ranch-status strong{font-size:11px}.objective{max-width:calc(100vw - 230px)}}@media(max-width:540px){#ranch-status{top:auto;right:8px;bottom:180px;width:160px;max-height:135px;overflow:hidden}.objective{max-width:90vw}}`;
  document.head.appendChild(style);document.body.insertAdjacentHTML('beforeend','<aside id="ranch-status" hidden aria-live="polite"></aside><dialog id="ranch-dialog" aria-labelledby="ranch-title"><p class="eyebrow">RANGER DISPATCH / RANCH AND COAST</p><h2 id="ranch-title">Choose your next adventure.</h2><button class="primary" id="ranch-close">Return to the reserve / B</button><div id="ranch-jobs"></div><p class="pad-help">D-pad or left stick moves focus. A accepts. B closes. Right stick scrolls. All assignments have a map marker.</p></dialog><dialog id="ranch-lift" aria-labelledby="lift-title"><p class="eyebrow">MAINTENANCE LIFT</p><h2 id="lift-title">Choose a floor.</h2><button class="primary" id="lift-close">Cancel / B</button><div id="lift-floors" class="entry-list"></div></dialog>');
  for(const [parent,id] of [['#menu-dialog .menu-grid','menu-ranch'],['#outpost-dialog .entry-list','outpost-ranch']]){document.querySelector(parent)?.insertAdjacentHTML('afterbegin',`<button id="${id}">Dispatch and guided lessons</button>`);$(id).onclick=()=>this.open();}
  $('ranch-close').onclick=$('lift-close').onclick=()=>this.ctx.close();for(const id of ['ranch-dialog','ranch-lift']){$(id).addEventListener('cancel',e=>{e.preventDefault();this.ctx.close();});$(id).addEventListener('close',()=>this.ctx.input.clear());}
  $('ranch-jobs').onclick=e=>{const b=e.target.closest('[data-job]');if(b)this.choose(b.dataset.job);};
 }
 open(){const rivals=this.ctx.frontier.rivals||[];const crew=rivals.map(r=>`<p><b>${r.name}:</b> ${r.status||'On a scheduled reserve service run'}. Deliveries completed this shift: ${r.deliveries||0}.</p>`).join('');
  $('ranch-jobs').innerHTML=`<div class="ranch-job"><h3>Field school: ${this.s.tutorial} / ${LESSONS.length}</h3><p>One task at a time, with the exact controls and a destination. Follow lessons or freely explore; nothing erases your old progress.</p><button data-job="school">Resume guided lessons</button><button data-job="free">Free exploration</button></div><div class="ranch-job"><h3>Meridian Rangers: Crest Meadow roundup</h3><p>Four strays need to go home. This repeatable exercise opens the gate and moves only this pen's residents outside. Herd them, stock the feeder and close the gate. Earn 650 credits. Historical containment progress remains recorded.</p><p class="ranch-stats">Best roundup: ${fmt(this.s.bestRoundup)}</p><button data-job="roundup">Begin a roundup</button></div><div class="ranch-job"><h3>Coastal circuit: boat time trial</h3><p>Sail from the wetland through the west channel. Pass the start buoy at speed, then all 24 ocean gates in order for one complete lap. Pausing stops the clock. Gold: 3:30. Silver: 4:45. Bronze: finish. There is no damage or forced reset.</p><p class="ranch-stats">Personal best: ${fmt(this.s.bestLap)}</p><button data-job="race">Stage a coastal race</button></div><div class="ranch-job"><h3>Greenline Logistics: offshore salvage</h3><p>Use the boat to recover three floating supply crates with A / E. Deliver them at East Freight Pier. This is a boat-only supply mission worth 900 credits. Collected: ${this.s.salvage.length} / 3.</p><button data-job="salvage">Track offshore supplies</button></div><div class="ranch-job"><h3>Skyline recovery: rooftops and interiors</h3><p>Land on the institute, logistics atrium and biosecurity center. Exit onto the roof, inspect the skyline beacon and take the lift to the atrium. Recover each archive on foot for 400 credits. Records: ${this.s.records.length} / 3.</p><button data-job="skyline">Track skyline archives</button></div><div class="ranch-job"><h3>FossilWorks: boneyard field survey</h3><p>Discover three skeletal deposits in the expanded districts. Park outside and survey each specimen on foot. Completion earns 900 credits. Surveys: ${this.s.bones.length} / 3.</p><button data-job="bones">Track fossil sites</button></div><div class="ranch-job"><h3>The crews have jobs, too.</h3><p>Meridian replenishes the Armored Valley feeder. FossilWorks delivers casting supplies to Amber Mesa. Greenline restocks coastal freight. Their deliveries change local market pressure; stop beside a convoy and press A to contact it.</p>${crew}</div>`;
  this.ctx.show('ranch-dialog');
 }
 choose(id){this.race.cancel('Another assignment was selected.');this.roundup=null;this.activity=id==='free'?null:id;this.s.guided=id==='school';if(id==='school'&&this.s.tutorial>=LESSONS.length){this.s.tutorial=0;this.s.done=[];}
  if(id==='roundup'){const p=PENS.find(p=>p.id==='crest-meadow'),ps=penState(this.ctx.state,p);ps.open=true;ps.fed=false;let i=0;for(const a of this.ctx.animals.filter(a=>a.pen===p.id)){a.x=p.x+(i%2?3:-3);a.z=p.z+p.hz+7+i*4;a.origin={x:a.x,z:a.z};a.deter=0;a.stun=0;i++;}this.roundup={pen:p.id,elapsed:0,uses:0};this.ctx.notify('Roundup staged at Crest Meadow. The gold marker leads to the gate; guide the four strays home.');}
  if(id==='race'){this.race.start();this.ctx.notify('Race staged. Sail the west channel to the start buoy. The clock begins only when your boat crosses it.');}
  this.save();this.ctx.close();this.ctx.input.clear();
 }
 pauseTracking(){this.activity=null;this.s.guided=false;this.race.cancel();this.roundup=null;this.save();}
 task(){const {fleet,state}=this.ctx,p=fleet.position;
  if(this.activity==='school'&&this.s.tutorial<LESSONS.length){const [id,name,detail,t]=LESSONS[this.s.tutorial];let target=t;if(id==='boat'&&fleet.mode==='boat')target=RACE_GATES[0];if(id==='roof'&&fleet.mode!=='helicopter'&&surfaceAt(p)===0)target=fleet.vehicles.find(v=>v.type==='helicopter').drive.position;if(id==='interior'){const b=BUILDINGS[0];target=p.y>3?{x:b.x-12,z:b.z-9}:{x:b.x+13,z:b.z-10};}return {name,detail,target,done:this.s.tutorial,total:LESSONS.length};}
  if(this.activity==='roundup'){const pen=PENS.find(p=>p.id==='crest-meadow'),n=this.ctx.animals.filter(a=>a.pen===pen.id&&insidePen(a,pen,1)).length;return {name:'Crest Meadow roundup',detail:`${n} / 4 home. ${fmt(this.roundup?.elapsed||0)}. Herd from behind, fill the feeder, then close the gate. A / E operates the terminal.`,target:{x:pen.x+10,z:pen.z+pen.hz+5},done:n,total:4};}
  if(this.activity==='race'){return {name:this.race.running?'Coastal circuit: '+fmt(this.race.time):'Coastal circuit: staging',detail:this.race.running?`Next buoy ${this.race.index%24||'FINISH'} / 24. Personal best ${fmt(this.s.bestLap)}. RT sail / LS steer / LS click boost.`:'Board the boat at Wetland Dock, then sail west through the lit channel to the ocean start buoy.',target:fleet.mode==='boat'?RACE_GATES[this.race.index%24]:HARBORS[0],done:Math.min(24,this.race.index),total:24};}
  if(this.activity==='salvage'){const next=SALVAGE.find(q=>!this.s.salvage.includes(q.id));return {name:next?'Offshore supply recovery':'Deliver Greenline supplies',detail:next?'Use the boat. Stop beside the marked floating crate and press A / E.':'Sail to East Freight Pier and press A / E to deliver all three crates.',target:fleet.mode==='boat'?(next||HARBORS[1]):HARBORS[0],done:this.s.salvage.length,total:3};}
  if(this.activity==='bones'){const b=BONEYARDS.find(q=>!this.s.bones.includes(q.id));return {name:'FossilWorks field survey',detail:b?'Follow the road to the skeletal deposit. Park, exit with Y / F and examine the field case with A / E.':'All three boneyards surveyed. Choose another assignment in Dispatch.',target:b,done:this.s.bones.length,total:3};}
  if(this.activity==='skyline'){const b=BUILDINGS.find(q=>!this.s.records.includes(q.id));return {name:'Skyline archive recovery',detail:b?'Land on the marked roof, exit the helicopter, and use the maintenance lift to explore the interior on foot.':'All three archives recovered. Your records and rewards are saved.',target:b&&(fleet.mode==='foot'&&distance(p,b)<35?(p.y>3?{x:b.x-12,z:b.z-9}:{x:b.x+13,z:b.z-10}):b),done:this.s.records.length,total:3};}
  return null;
 }
 horn(){if(this.hornCool>0)return;this.feedbackUntil=this.clock+5;this.hornCool=1.1;const p=this.ctx.fleet.position;if(p.y>7){this.world.horn(p,this.ctx.state.settings.reduced);return;}const hits=this.ctx.animals.filter(a=>distance(a,p)<42);for(const a of hits)deterAnimal(a,p,'horn');this.world.horn(p,this.ctx.state.settings.reduced);this.s.hornHits+=hits.length;this.lastHit=`HORN / ${hits.length} dinosaurs moving away / 42 m range`;this.ctx.notify(this.lastHit);if(hits.length){this.mark('horn');if(this.roundup)this.roundup.uses++;}this.save();}
 shot(t,origin,dir,length,direct){this.feedbackUntil=this.clock+3;const {animals,physics,R,fleet,state}=this.ctx;let end={x:origin.x+dir.x*length,y:origin.y+dir.y*length,z:origin.z+dir.z*length},target=direct||null;
  if(!target){let best=length;for(const a of animals){const center={x:a.x,y:a.collisionHeight*.5,z:a.z},dx=center.x-origin.x,dy=center.y-origin.y,dz=center.z-origin.z,along=dx*dir.x+dy*dir.y+dz*dir.z,perp=Math.hypot(dx-dir.x*along,dy-dir.y*along,dz-dir.z*along);if(along<0||along>best+1.5||along>t.range||perp>Math.min(4,a.radius+.8))continue;
    const len=Math.hypot(dx,dy,dz),v={x:dx/len,y:dy/len,z:dz/len};const hit=physics.world.castRay(new R.Ray(origin,v),len+.3,true,undefined,undefined,fleet.actor.collider,fleet.actor.body);if(hit&&hit.collider.handle!==a.collider.collider(0).handle)continue;target=a;best=along;}
  }
  const hits=[];if(target){deterAnimal(target,origin,t.id);hits.push(target);state.toolHits[t.id]++;end={x:target.x,y:target.collisionHeight*.5,z:target.z};this.markOnce(t.id);if(this.roundup)this.roundup.uses++;
    if(t.id==='zapper'){for(const a of animals){if(a===target||distance(a,target)>7||hits.length>=3)continue;const d={x:a.x-target.x,y:a.collisionHeight*.5-end.y,z:a.z-target.z},len=Math.hypot(d.x,d.y,d.z);const hit=physics.world.castRay(new R.Ray(end,{x:d.x/len,y:d.y/len,z:d.z/len}),len+.2,true,undefined,undefined,target.collider.collider(0),target.collider);if(hit&&hit.collider.handle!==a.collider.collider(0).handle)continue;deterAnimal(a,origin,'zapper');hits.push(a);this.world.shot('zapper',end,{x:a.x,y:a.collisionHeight*.5,z:a.z},[a]);}}
    this.lastHit=(t.id==='water'?'PRESSURE HIT':'ZAPPER HIT')+' / '+hits.map(a=>speciesById(a.species).name).join(', ')+' / '+(t.id==='water'?'backing away':'charge interrupted');this.ctx.input.pulse(t.id==='water'?.12:.4,110);
  }else this.lastHit='NO HIT / Bring a dinosaur into the reticle. Solid walls block tools.';
  this.world.shot(t.id,origin,end,hits);return end;
 }
 candidate(){const p=this.ctx.fleet.position,mode=this.ctx.fleet.mode;if(Math.abs(this.ctx.fleet.actor.speed)>3)return null;
  if(mode==='boat'){for(const s of SALVAGE)if(!this.s.salvage.includes(s.id)&&distance(p,s)<15)return {kind:'ranch',label:'Recover floating supplies / A',type:'salvage',item:s};if(this.s.salvage.length===3&&!this.s.rewards.includes('salvage')&&distance(p,HARBORS[1])<34)return {kind:'ranch',label:'Deliver Greenline supplies / A',type:'deliver'};}
  if(mode==='foot'){
   for(const b of BUILDINGS){if(distance(p,{x:b.x-12,z:b.z-9})<3.4&&[0,6,b.h].some(y=>Math.abs(p.y-y-1)<1.4))return {kind:'ranch',label:'Use maintenance lift / A',type:'lift',item:b};if(p.y<b.h+3&&p.y>b.h&&distance(p,{x:b.x+10,z:b.z+8})<4)return {kind:'ranch',label:'Inspect skyline beacon / A',type:'roof',item:b};if(p.y<3&&distance(p,{x:b.x+13,z:b.z-10})<4)return {kind:'ranch',label:'Recover '+b.record+' / A',type:'record',item:b};}
   for(const b of BONEYARDS)if(distance(p,{x:b.x,z:b.z-4})<5)return {kind:'ranch',label:'Survey '+b.name+' / A',type:'bone',item:b};
  }
  for(const r of this.ctx.frontier.rivals||[])if(p.y<5&&distance(p,r.model.position)<12)return {kind:'ranch',label:'Contact '+r.name+' / A',type:'crew',item:r};return null;
 }
 interact(c){const b=c.item;if(c.type==='crew'){this.open();return;}if(c.type==='salvage'){this.s.salvage.push(b.id);this.ctx.notify(`Floating supplies recovered: ${this.s.salvage.length} / 3. Deliver all three at East Freight Pier.`);}
  else if(c.type==='deliver'){this.s.crewScore.greenline++;this.reward('salvage',900);this.activity=null;}
  else if(c.type==='lift'){this.liftBuilding=b;$('lift-title').textContent=b.name;$('lift-floors').innerHTML=[['Ground-floor archive',0],['Mezzanine gallery',6],['Rooftop helipad',b.h]].map(([name,y])=>`<button data-floor="${y}">${name}</button>`).join('');$('lift-floors').onclick=e=>{const el=e.target.closest('[data-floor]');if(!el)return;this.ctx.fleet.person.setActive(true,{x:b.x-12,y:Number(el.dataset.floor)+1.1,z:b.z-9});this.ctx.close();this.ctx.audio.tone(240,.18);this.ctx.save();};this.ctx.show('ranch-lift');return;}
  else if(c.type==='roof'){if(b.id===BUILDINGS[0].id)this.mark('roof');this.ctx.info('ROOFTOP OPERATIONS',b.name,'<p>Landing confirmed. The lit maintenance lift is near the back-left corner of this roof. Use A / E to choose the ground floor or mezzanine.</p><p>Find the archive in the back-right room. The narrow ground entrance is also usable on foot; vehicles remain outside.</p>');}
  else if(c.type==='record'){if(!this.s.records.includes(b.id))this.s.records.push(b.id);this.reward(b.id,400);if(b.id===BUILDINGS[0].id)this.mark('interior');this.ctx.info('ARCHIVE RECOVERED',b.record,'<p>The record is saved. The maintenance lift returns you to the rooftop helicopter, or leave through the ground-floor doorway.</p><p>Dispatch lists the other skyline archives and boneyards.</p>');}
  else if(c.type==='bone'){if(!this.s.bones.includes(b.id)){this.s.bones.push(b.id);this.ctx.notify('FossilWorks survey recorded: '+this.s.bones.length+' / 3.');}if(this.s.bones.length===3&&!this.s.rewards.includes('bones')){this.s.crewScore.fossilworks++;this.reward('bones',900);}this.ctx.info('BONEYARD FIELD SURVEY',b.name,'<p>Survey saved. These skeletal deposits are original stylized game scenery, not fossil-site reconstructions.</p><p>Return to your vehicle or continue exploring this outer district.</p>');}
  this.save();
 }
 update(dt,time){const {fleet,animals,state}=this.ctx,p=fleet.position;this.hornCool=Math.max(0,this.hornCool-dt);this.world.update(dt,time,p,fleet.mode,this.s,this.race,animals,state.settings.reduced);if(dt<=0)return;this.clock+=dt;
  if(fleet.mode!=='foot'&&distance(p,{x:0,z:38})<9)this.markOnce('drive');
  if(fleet.mode==='boat'&&distance(p,RACE_GATES[0])<30)this.markOnce('boat');
  if(fleet.mode==='foot'&&surfaceAt(p)===BUILDINGS[0].h&&Math.abs(p.x-BUILDINGS[0].x)<22)this.markOnce('roof');
  const pen=PENS.find(x=>x.id==='crest-meadow'),ps=penState(state,pen),home=animals.filter(a=>a.pen===pen.id&&insidePen(a,pen,1)).length;
  if(ps.fed)this.markOnce('feed');if(home===4&&!ps.open&&ps.fed)this.markOnce('pen');
  if(this.roundup){this.roundup.elapsed+=dt;if(home===4&&!ps.open&&ps.fed&&this.roundup.uses>0&&this.roundup.elapsed>5){const score=this.roundup.elapsed;this.s.bestRoundup=this.s.bestRoundup===null?score:Math.min(score,this.s.bestRoundup);this.s.crewScore.meridian++;this.roundup=null;this.activity=null;this.reward('roundup',650,true);this.ctx.radio('Four residents safe. Roundup completed in '+fmt(score)+'. Historical containment progress preserved.');}}
  const e=this.race.step(p,fleet.mode,dt,Math.abs(fleet.actor.speed));if(e){this.ctx.audio.tone(e.type==='finish'?880:660,.12);this.ctx.input.pulse(.2,120);if(e.type==='finish'){this.s.bestLap=this.s.bestLap===null?e.time:Math.min(this.s.bestLap,e.time);this.activity=null;this.reward('race',e.medal==='Gold'?750:e.medal==='Silver'?500:300,true);this.ctx.radio(`${e.medal} lap: ${fmt(e.time)}. Best: ${fmt(this.s.bestLap)}. Start another run in Dispatch.`);this.save();}else this.ctx.notify(e.type==='start'?'GO! Coastal lap started. Follow the numbered gold buoy.':'Buoy '+e.index+' / 24 cleared. '+fmt(this.race.time));}
  if(this.activity==='race'&&!this.race.active){this.activity=null;if(this.race.reason)this.ctx.notify(this.race.reason);}
 }
 markOnce(id){if(!this.s.done.includes(id))this.mark(id);}
 hud(){const s=$('ranch-status'),task=this.task();s.hidden=!this.ctx.started();s.innerHTML=`<strong>${this.activity==='race'&&this.race.running?'LAP '+fmt(this.race.time):'RANCH AND COAST'}</strong>${this.clock<this.feedbackUntil?this.lastHit:task?task.name:'Menu / Dispatch lists your available activities.'}<small>${task?'Follow the gold assignment marker.':'Menu / Dispatch chooses races, roundups, crew jobs and lessons.'}</small>`;
  if(this.activity==='school'&&this.currentLesson!==this.s.tutorial){this.currentLesson=this.s.tutorial;document.querySelectorAll('.ranch-highlight').forEach(e=>e.classList.remove('ranch-highlight'));const id=LESSONS[this.s.tutorial]?.[0];const el=id==='water'||id==='zapper'?document.querySelector('.equipment'):id==='boat'||id==='roof'?$('board-button'):$('interact-button');el?.classList.add('ranch-highlight');if(task)this.ctx.radio(task.name+'. '+task.detail);}
 }
 drawMap(ctx,to,k,full){ctx.fillStyle='#377b84';ctx.beginPath();ctx.arc(...to(0,0),535*k,0,7);ctx.arc(...to(0,0),LAND_RADIUS*k,0,7,true);ctx.fill('evenodd');const [x,z]=to(-478,-170);ctx.fillRect(x,z,256*k,36*k);
  for(const [items,color] of [[BUILDINGS,'#9ce4d0'],[BONEYARDS,'#ead7af'],[HARBORS,'#96d9fc']])for(const b of items){const [x,z]=to(b.x,b.z);ctx.fillStyle=color;ctx.fillRect(x-3,z-3,6,6);if(full){ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText(b.name,x,z-7);}}
  if(this.race.active){for(const [i,b] of RACE_GATES.entries()){ctx.fillStyle=i===this.race.index%24?'#ffe09a':'#73bebf';ctx.beginPath();ctx.arc(...to(b.x,b.z),i===this.race.index%24?6:2.5,0,7);ctx.fill();}}
  if(this.activity==='salvage')for(const s of SALVAGE)if(!this.s.salvage.includes(s.id)){ctx.fillStyle='#ffc779';ctx.fillRect(...to(s.x,s.z),5,5);}
  for(const r of this.ctx.frontier.rivals||[]){ctx.fillStyle='#d5a4ed';ctx.beginPath();ctx.arc(...to(r.model.position.x,r.model.position.z),3,0,7);ctx.fill();if(full){ctx.font='9px sans-serif';ctx.fillText(r.name,...to(r.model.position.x,r.model.position.z-7));}}
 }
 snapshot(){return {build:RANCH_BUILD,activity:this.activity,progress:JSON.parse(JSON.stringify(this.s)),race:{active:this.race.active,running:this.race.running,index:this.race.index,time:this.race.time},effects:this.world.stats,task:this.task(),scales:this.ctx.animals.filter(a=>SCALE_REFERENCE[a.species]).map(a=>({uid:a.uid,id:a.species,length:a.model.userData.lengthMeters})),crews:(this.ctx.frontier.rivals||[]).map(r=>({name:r.name,status:r.status,deliveries:r.deliveries,x:r.model.position.x,z:r.model.position.z}))};}
}
