import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/addons/loaders/GLTFLoader.js';
import {clone} from './vendor/addons/utils/SkeletonUtils.js';
import {label} from './ranger-art.js';
import {makePerson as fallbackPerson} from './frontier-art.js?v=herds1';
import {Fieldlight} from './fieldlight.js?v=crew1';
import {CREW,CREW_BUILD,readCrew,saveCrew,meetCrew,contactAllowed} from './crew-data.js';
export {CREW_BUILD} from './crew-data.js';
const $=id=>document.getElementById(id),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export class ReserveCrew{
 constructor(ctx){
  this.ctx=ctx;this.s=readCrew(ctx.storage);this.time=0;this.ready=false;this.loadError=null;this.selected=null;this.assets=null;this.avatar=null;this.fieldlight=new Fieldlight(ctx.scene,ctx.signatureWorld);this.fieldlight.apply(this.s.fieldlight);
  this.people=CREW.map((def,i)=>{const root=new T.Group();root.position.set(def.x,0,def.z);ctx.scene.add(root);const fallback=fallbackPerson();root.add(fallback);const sign=label(def.name.toUpperCase()+' / '+def.role.toUpperCase(),10,1);const badge=new T.Sprite(new T.SpriteMaterial({map:sign.material.map,depthWrite:false}));badge.position.y=3.1;badge.scale.set(6.5,.65,1);root.add(badge);const ring=new T.Mesh(new T.RingGeometry(.72,.82,28),new T.MeshBasicMaterial({color:def.color,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.06;root.add(ring);return {...def,root,fallback,badge,mixer:null,actions:null,move:false,phase:i,loaded:false};});
  this.installUI();this.loading=this.load();
 }
 save(){return saveCrew(this.ctx.storage,this.s);}
 async load(){try{
  const [gltf,male,female]=await Promise.all([new GLTFLoader().loadAsync(new URL('./assets/crew/ranger.glb',import.meta.url).href),new T.TextureLoader().loadAsync(new URL('./assets/crew/male.png',import.meta.url).href),new T.TextureLoader().loadAsync(new URL('./assets/crew/female.png',import.meta.url).href)]);
  for(const texture of [male,female]){texture.colorSpace=T.SRGBColorSpace;texture.flipY=false;texture.anisotropy=2;}
  this.assets={gltf,male,female};for(const p of this.people){const rig=this.createHuman(p.skin);p.root.remove(p.fallback);p.human=rig.root;p.mixer=rig.mixer;p.actions=rig.actions;p.root.add(rig.root);p.loaded=true;}this.ready=true;this.applyAvatar();
 }catch(e){this.loadError=String(e?.message||e);console.warn('Dino Atlas crew assets unavailable; procedural rangers remain usable.',e);}}
 createHuman(skin){const a=this.assets,root=new T.Group(),model=clone(a.gltf.scene);root.add(model);const size=new T.Box3().setFromObject(model).getSize(new T.Vector3());model.scale.multiplyScalar(1.85/Math.max(.1,size.y));const b=new T.Box3().setFromObject(model);model.position.y-=b.min.y;model.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.material.map=a[skin];m.material.roughness=.88;m.castShadow=true;m.receiveShadow=true;m.frustumCulled=false;}});
 const mixer=new T.AnimationMixer(model),idle=mixer.clipAction(a.gltf.animations.find(c=>c.name==='Idle')),run=mixer.clipAction(a.gltf.animations.find(c=>c.name==='Run'));idle.play();run.play();run.setEffectiveWeight(0);return {root,mixer,actions:{idle,run}};}
 applyAvatar(){if(this.avatar){this.ctx.scene.remove(this.avatar.root);this.avatar.mixer.stopAllAction();this.avatar.mixer.uncacheRoot(this.avatar.mixer.getRoot());this.avatar.root.traverse(m=>{if(m.isMesh)m.material.dispose();});this.avatar=null;}if(this.ready&&this.s.avatar!=='classic'){this.avatar=this.createHuman(this.s.avatar);this.ctx.scene.add(this.avatar.root);}this.save();}
 installUI(){
  document.body.insertAdjacentHTML('beforeend',`<dialog id="crew-dialog" aria-labelledby="crew-title"><p class="eyebrow">THE PEOPLE OF DINO ATLAS</p><h2 id="crew-title">Meet your reserve team.</h2><button class="primary" id="crew-close">Return to the reserve / B</button><p id="crew-intro">Find named rangers beside the outposts and Northstar. Leave your vehicle with Y, approach and press A to talk. Staff can point you to real assignments, not just scenery.</p><div id="crew-roster" class="entry-list"></div><div class="entry-list"><button id="crew-tour">Track crew introductions</button><button id="crew-report">File introductions report</button><button id="crew-clear">Stop tracking introductions</button></div><div class="settings"><label>Environment shaders <select id="crew-shaders"><option value="fieldlight">Fieldlight / water and research glass</option><option value="classic">Classic / original materials</option></select></label><label>On-foot ranger <select id="crew-avatar"><option value="male">Field ranger / male skin</option><option value="female">Field ranger / female skin</option><option value="classic">Original procedural ranger</option></select></label></div><p>Character model, skins and idle/run clips: Kenney, CC0. Locally hosted, with no asset-service account. Fieldlight shaders are original additions, not ray-traced reflections. Reduced Motion freezes decorative shader animation.</p><p class="pad-help">D-pad navigates. A selects. Left/right adjusts settings. B closes. X remains reload during play.</p></dialog><dialog id="crew-talk" aria-labelledby="crew-talk-title"><p class="eyebrow" id="crew-talk-role"></p><h2 id="crew-talk-title"></h2><p id="crew-talk-copy"></p><button class="primary" id="crew-talk-job">Show the assignment</button><button id="crew-talk-close">Back to patrol / B</button></dialog>`);
  document.querySelector('#menu-dialog .menu-grid').insertAdjacentHTML('afterbegin','<button id="menu-crew">Reserve crew and Fieldlight</button>');$('menu-crew').onclick=()=>this.open();$('crew-close').onclick=$('crew-talk-close').onclick=()=>this.ctx.close();
  $('crew-shaders').value=this.s.fieldlight?'fieldlight':'classic';$('crew-shaders').onchange=e=>{this.s.fieldlight=e.target.value==='fieldlight';this.fieldlight.apply(this.s.fieldlight);this.save();};$('crew-avatar').value=this.s.avatar;$('crew-avatar').onchange=e=>{this.s.avatar=e.target.value;this.applyAvatar();};
  $('crew-roster').onclick=e=>{const el=e.target.closest('[data-crew]');if(el){this.trackId=el.dataset.crew;this.beginTour();}};$('crew-tour').onclick=()=>{this.trackId=null;this.beginTour();};$('crew-clear').onclick=()=>{this.s.tour=false;this.save();this.ctx.close();};$('crew-report').onclick=()=>this.report();$('crew-talk-job').onclick=()=>this.job();
  for(const id of ['crew-dialog','crew-talk']){$(id).addEventListener('cancel',e=>{e.preventDefault();this.ctx.close();});$(id).addEventListener('close',()=>this.ctx.input.clear());}
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-job],[data-track],#campaign-track,#pen-track,#aaa-director-start,#aaa-director-resume,#herds-study-start,#northstar-start,#northstar-restart')){this.s.tour=false;this.save();}},true);
 }
 beginTour(){this.ctx.director.suspend();this.ctx.herds.pause();this.ctx.northstar.pause();this.ctx.ranch.pauseTracking();this.s.tour=true;this.save();this.ctx.close();this.ctx.radio('Meet the staff on foot. Follow the gold marker, park, press Y to exit and A to talk. Seven introductions unlock a one-time 600-credit report at Mara.');}
 open(){this.refresh();this.ctx.show('crew-dialog');}
 refresh(){ $('crew-roster').innerHTML=CREW.map(p=>`<button data-crew="${p.id}"><b>${p.name}</b> / ${p.role}<small> ${this.s.met.includes(p.id)?'MET':'NOT YET MET'} / Pin destination</small></button>`).join('');$('crew-report').disabled=this.s.met.length!==CREW.length||this.s.reported||!this.nearMara();$('crew-report').textContent=this.s.reported?'Introductions report already filed':'File report with Mara / 600 credits';}
 nearMara(){const p=this.people[0];return contactAllowed(this.ctx.fleet.position,p.root.position,this.ctx.fleet.mode,this.ctx.fleet.actor.speed);}
 report(){if(this.s.reported||this.s.met.length!==CREW.length||!this.nearMara())return;const economy=window.__dinoEconomy;if(!economy?.grant){this.ctx.notify('Supply ledger is not ready yet. The report has not been consumed.');return;}const paid=economy.grant(600,'aaa:crew-introductions');this.s.reported=true;this.s.tour=false;this.save();this.ctx.info('CREW NETWORK ESTABLISHED','You know who to call.',`<p>All seven staff introductions are recorded.</p><p>${paid?'600 credits added to your existing supply balance.':'This report reward was already recorded; it is not paid twice.'}</p><p>Speak to staff to revisit their assignments. Old cargo, missions and discoveries are unchanged.</p>`);}
 candidate(){const f=this.ctx.fleet;const people=this.people.filter(p=>contactAllowed(f.position,p.root.position,f.mode,f.actor.speed)).sort((a,b)=>dist(a.root.position,f.position)-dist(b.root.position,f.position));if(!people.length)return null;const p=people[0];return {kind:'crew',person:p,label:p.id==='mara'&&this.s.met.length===CREW.length&&!this.s.reported?'File crew introductions report / A':'Talk to '+p.name+' / A'};}
 interact(c){const p=c.person;if(p.id==='mara'&&this.s.met.length===CREW.length&&!this.s.reported){this.report();return;}this.selected=p;meetCrew(this.s,p.id);if(this.trackId===p.id)this.trackId=null;this.save();$('crew-talk-title').textContent=p.name;$('crew-talk-role').textContent=p.role.toUpperCase();$('crew-talk-copy').textContent=p.line;$('crew-talk-job').textContent=p.job==='canopy'?'Open Canopy Circuit briefing':'Open '+({field:'Living Herds field study',roundup:'Crest Meadow roundup',salvage:'offshore salvage',storm:'Storm Response briefing',bones:'boneyard survey',race:'coastal boat race'}[p.job]);this.ctx.audio.tone?.(440,.07);this.ctx.show('crew-talk');}
 job(){if(!this.selected)return;this.s.tour=false;this.save();const j=this.selected.job;if(j==='canopy')this.ctx.northstar.open();else if(j==='field')this.ctx.herds.open();else if(j==='storm')this.ctx.director.open();else{this.ctx.northstar.pause();this.ctx.herds.pause();this.ctx.ranch.choose(j);}}
 task(){if(!this.s.tour)return null;const p=this.people.find(p=>p.id===this.trackId)||this.people.find(p=>!this.s.met.includes(p.id))||this.people[0];return {name:this.s.met.length===CREW.length?'Report to Chief Ranger Mara':'Meet '+p.name,detail:this.s.met.length===CREW.length?'Return on foot to Mara at the visitor center and press A to file the one-time report.':'Meet your '+p.role.toLowerCase()+'. Follow the marker. Park, exit with Y / F, and press A / E to speak.',target:p.root.position,done:this.s.met.length,total:CREW.length};}
 update(dt,time){this.time+=dt;const {fleet,settings,personModel}=this.ctx,f=fleet.position;this.fieldlight.update(dt,settings.night,settings.reduced);
  for(const p of this.people){const gap=dist(f,p.root.position);p.root.visible=gap<95;p.badge.visible=gap<24;let moving=false;
   if(dt>0&&gap>=5.5){const cycle=(this.time+p.phase*4)%22;moving=cycle<6;const z=p.z+(moving?cycle<3?cycle*.5:(6-cycle)*.5:0),next=new T.Vector3(p.x,0,z),delta=next.clone().sub(p.root.position);if(delta.length()>.01){const hit=this.ctx.physics.world.castRay(new this.ctx.R.Ray({x:p.root.position.x,y:1,z:p.root.position.z},delta.clone().normalize()),delta.length()+.3,true,undefined,undefined,undefined,undefined,c=>!c.parent()||c.parent().isFixed());if(!hit){p.root.position.copy(next);p.root.rotation.y=delta.z>0?0:Math.PI;}else moving=false;}}
   if(dt>0&&gap<5.5)p.root.rotation.y=Math.atan2(f.x-p.root.position.x,f.z-p.root.position.z);
   if(p.mixer&&p.root.visible){p.actions.run.setEffectiveWeight(moving?1:0);p.actions.run.setEffectiveTimeScale(.48);p.actions.idle.setEffectiveWeight(moving?0:1);p.mixer.update(dt);}p.move=moving;
  }
  if(this.avatar){this.avatar.root.visible=fleet.mode==='foot';if(fleet.mode==='foot'){personModel.visible=false;this.avatar.root.position.set(f.x,f.y-.9,f.z);this.avatar.root.rotation.y=personModel.rotation.y;const moving=Math.abs(fleet.actor.speed)>.2;this.avatar.actions.run.setEffectiveWeight(moving?1:0);this.avatar.actions.idle.setEffectiveWeight(moving?0:1);this.avatar.actions.run.setEffectiveTimeScale(Math.min(1.7,Math.max(.3,Math.abs(fleet.actor.speed)/4)));this.avatar.mixer.update(dt);}}
 }
 drawMap(ctx,to,k,full){for(const p of this.people){const [x,z]=to(p.root.position.x,p.root.position.z);ctx.fillStyle=this.s.met.includes(p.id)?'#b2dfcb':'#f4ce8a';ctx.beginPath();ctx.arc(x,z,full?3.5:3,0,7);ctx.fill();if(full&&this.s.tour){ctx.font='10px sans-serif';ctx.fillText(p.name,x,z+12);}}}
 snapshot(){return {build:CREW_BUILD,ready:this.ready,loadError:this.loadError,progress:{...this.s,met:[...this.s.met]},fieldlight:this.fieldlight.snapshot(),clips:this.assets?.gltf.animations.map(c=>({name:c.name,duration:c.duration}))||[],people:this.people.map(p=>({id:p.id,name:p.name,role:p.role,x:p.root.position.x,z:p.root.position.z,loaded:p.loaded,moving:p.move,bones:p.human?.getObjectByProperty('isSkinnedMesh',true)?.skeleton.bones.length||0})),avatar:this.avatar?this.s.avatar:'classic',task:this.task()};}
}
