import * as T from './vendor/three.module.js';import R from './vendor/rapier.mjs';
import {initPhysics,ParkPhysics} from './ranger-physics.js';import {RangerInput,focusable} from './ranger-input.js?v=grounded1';
import {RangerTools} from './ranger-tools.js';import {RangerAudio} from './ranger-audio.js';
import {makeResident,makeTool} from './frontier-art.js';import {animateResident} from './herd-rig.js';import {animateRangerBody} from './ranger-body.js';
import {DioramaXR} from './diorama-xr.js';import {mergeMotion} from './xr-actions.js';import {buildTidegate} from './tidegate-world.js';import {TidegateFleet} from './tidegate-actors.js';
import {TIDEGATE_BUILD,POINTS,ROUTES,BOUNDS,clamp,gap,canWalk,readDistrict,saveDistrict,applyDistrict,nextTask,stepHerd} from './tidegate-core.js';
const $=id=>document.getElementById(id);
export async function bootTidegate(){
 await initPhysics();let storage=null;try{storage=localStorage;}catch{}
 const state=readDistrict(storage),physics=new ParkPhysics(),scene=new T.Scene(),canvas=$('park');
 const renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.3));
 const camera=new T.PerspectiveCamera(50,1,.03,420),world=buildTidegate(scene,physics,state),fleet=new TidegateFleet(physics,world,state,notify),tools=new RangerTools(state),audio=new RangerAudio();
 let started=false,xr=null,yaw=0,pitch=.62,zoom=24,time=0,last=performance.now(),acc=0,uiClock=0,saveClock=0,toastTimer=0,candidate=null,drag=null,reduced=false;
 const modal=()=>document.querySelector('dialog[open]')||(!started?$('intro'):null),paused=()=>!!modal()||document.hidden||!!xr?.invisible;
 const input=new RangerInput({action,modal,mode:()=>fleet.mode,onDevice:d=>document.body.dataset.input=d,onDisconnect:()=>{show('menu-dialog');notify('Controller disconnected. Release controls after reconnecting, then close the menu.');}});input.vibration=true;
 function resize(){if(renderer.xr.isPresenting)return;renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}resize();addEventListener('resize',resize);
 camera.position.set(-54,35,67);camera.lookAt(6,0,3);
 const animals=Array.from({length:4},(_,i)=>{const a={uid:'tidegate-herd-'+i,index:i,species:'triceratops',kind:'trike',color:[0xa18a69,0x879576,0x9a9e7d,0xb1a17a][i],scale:.62,radius:1.6,x:21+(i%2)*4,z:23+Math.floor(i/2)*4,angle:Math.PI/2,phase:i*.7,mood:'roaming',alert:0,speed:0};a.model=makeResident(a);a.collider=physics.animal(a.radius,a.x,a.z,2);world.root.add(a.model);return a;});
 const toolModel=makeTool();world.root.add(toolModel);const beam=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineBasicMaterial({color:0x99e4ed,transparent:true,opacity:1}));beam.frustumCulled=false;beam.visible=false;world.root.add(beam);let beamAge=5;
 function notify(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4700);}
 function save(){if(fleet.mode==='foot'&&canWalk(fleet.position,state))state.position={...fleet.position};if(!saveDistrict(storage,state))notify('This browser could not save Tidegate progress. Classic Reserve saves have not been changed.');}
 function show(id){for(const d of document.querySelectorAll('dialog[open]'))d.close();input.clear();const d=$(id);d.showModal();focusable(d)[0]?.focus({preventScroll:true});if(id==='map-dialog')drawMap();}
 function close(){const d=document.querySelector('dialog[open]');if(d)d.close();input.clear();if(!started)$('start-button').focus({preventScroll:true});else canvas.focus({preventScroll:true});}
 for(const d of document.querySelectorAll('dialog')){d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('close',()=>input.clear());}
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);
 const targets=[{id:'observe',...POINTS.overlook,y:6.4,label:'Observe the herd route'},{id:'feed',...POINTS.feeder,y:1.1,label:'Stock / close shelter feeder'},{id:'repair',...POINTS.gearbox,y:1.3,label:'Align the bridge gearbox'},{id:'sluice',...POINTS.sluice,y:1.3,label:'Reverse the sluice'},{id:'bridge',...POINTS.bridge,y:1.2,label:'Lower the service bridge'},{id:'report',...POINTS.report,y:1.0,label:'File report / restock'}];
 function findCandidate(){const p=fleet.position;candidate=null;for(const t of targets){if(gap(t,p)>3.3||Math.abs(p.y-t.y)>2.2)continue;const origin=new T.Vector3(p.x,p.y+.3,p.z),dest=new T.Vector3(t.x,t.y,t.z),dir=dest.clone().sub(origin),len=dir.length();if(len>.02){dir.normalize();const hit=physics.world.castRay(new R.Ray(origin,dir),len,true,undefined,undefined,fleet.actor.collider,fleet.actor.body);if(hit&&hit.timeOfImpact<len-1.0)continue;}candidate=t;break;}return candidate;}
 function interact(){if(paused())return;const c=findCandidate();if(!c){notify('Move the ranger within reach of an entrance, control or observation point.');return;}if(Math.abs(fleet.actor.speed)>3){notify('Stop to work safely.');return;}
  const result=applyDistrict(state,c.id,{animals,player:fleet.position,boat:fleet.vehicles.find(v=>v.type==='boat').drive.position,mode:fleet.mode});if(c.id==='report'&&fleet.mode==='foot')tools.refill();notify(result.message);if(result.changed){save();input.pulse(.15,90);}world.update(0,time,state,fleet.position,xr?.diorama);ui();
 }
 function action(key){
  if(key==='back'){close();return;}if(key==='menu'){modal()&&started?close():show('menu-dialog');return;}if(key==='map'){if($('map-dialog').open)close();else show('map-dialog');return;}if(key==='journal'||key==='operations'){show('notes-dialog');return;}
  if(key==='tabPrev'||key==='tabNext'){if(modal())input.navigate(key==='tabNext'?1:-1);return;}if(!started||paused())return;
  if(key==='interact')interact();else if(key==='board'){if(fleet.board()){input.clear();save();}}
  else if(key==='reload'){if(!tools.reload())notify('No reload needed, or no reserve. Restock at the home outpost.');}
  else if(key==='nextTool'||key==='prevTool')tools.switch(key==='nextTool'?1:-1);
  else if(key==='water'||key==='zapper'){state.tool=key==='water'?0:1;tools.reloadLeft=0;tools.reloadTool=null;}
  else if(key==='horn'){for(const a of animals)if(gap(a,fleet.position)<42)a.alert=Math.max(a.alert,3);audio.horn();notify('The herd is alert and moving toward refuge. Give it space to settle.');}
  else if(key==='camera'){if(xr?.active)xr.toggleView();else zoom=zoom>20?16:28;}
  else if(key==='recover'&&fleet.current){fleet.current.drive.reset(fleet.current.spawn);notify('Vehicle recovered without damage.');}
 }
 $('start-button').onclick=()=>{started=true;$('intro').hidden=true;$('hud').hidden=false;input.clear();canvas.focus({preventScroll:true});last=performance.now();notify('The orange crane is home. The amber mast is your destination. Choose an approach, not a checklist.');};
 $('intro-settings').onclick=()=>show('menu-dialog');$('menu-button').onclick=()=>show('menu-dialog');$('menu-map').onclick=$('map-button').onclick=()=>show('map-dialog');$('menu-notes').onclick=()=>show('notes-dialog');$('interact-button').onclick=interact;$('board-button').onclick=()=>action('board');$('reload-button').onclick=()=>action('reload');
 $('resupply').onclick=()=>{if(gap(fleet.position,POINTS.report)>5&&gap(fleet.position,POINTS.gearbox)>5){notify('Resupply at the home outpost or inside the pump house.');return;}tools.refill();save();notify('Water tank and zapper batteries replenished.');};
 $('quality').onchange=e=>{const low=e.target.value==='low';renderer.setPixelRatio(low?.8:Math.min(devicePixelRatio||1,1.3));renderer.shadowMap.enabled=!low;resize();};$('reduced').onchange=e=>reduced=e.target.checked;
 $('sound-toggle').checked=audio.settings.enabled;$('sound-toggle').onchange=async e=>{try{if(e.target.checked!==audio.settings.enabled)await audio.toggle();}catch{e.target.checked=false;notify('Audio could not start in this browser.');}};
 for(const b of document.querySelectorAll('[data-drive]')){b.onpointerdown=e=>{e.preventDefault();if(paused())return;b.setPointerCapture(e.pointerId);input.touch.add(b.dataset.drive);};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>input.touch.delete(b.dataset.drive));}
 canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{if(paused())return;canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY};input.mouseAim=e.button===2;input.mouseFire=e.button===0;};canvas.onpointermove=e=>{if(!drag||paused())return;yaw-=(e.clientX-drag.x)*.005;pitch=clamp(pitch+(e.clientY-drag.y)*.004,.2,1.15);drag={x:e.clientX,y:e.clientY};};for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>{drag=null;input.mouseAim=false;input.mouseFire=false;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom+e.deltaY*.02,9,45);},{passive:false});
 addEventListener('blur',()=>{input.clear();if(started&&!modal())show('menu-dialog');});document.addEventListener('visibilitychange',()=>{input.clear();if(document.hidden&&started&&!modal())show('menu-dialog');});addEventListener('pagehide',save);
 function rayTarget(ray){const hit=physics.world.castRay(new R.Ray(ray.origin,ray.direction),6000,true,undefined,undefined,fleet.actor.collider,fleet.actor.body);if(!hit)return null;return ray.origin.clone().addScaledVector(ray.direction,hit.timeOfImpact);}
 xr=new DioramaXR({scene,worldRoot:world.root,renderer,camera,fleet,storage,input,modal,action,yaw:()=>yaw,notify,restoreSize:resize,rayTarget,build:TIDEGATE_BUILD});
 function shoot(){const tool=tools.fire();if(!tool)return;const p=fleet.position,forward=new T.Vector3(-Math.sin(yaw),-.035,-Math.cos(yaw)),origin=new T.Vector3(p.x,p.y+.35,p.z).addScaledVector(forward,1);const ray=xr.active?xr.aimFrom(origin,forward):{origin,direction:forward};const hit=physics.world.castRay(new R.Ray(ray.origin,ray.direction),tool.range,true,undefined,undefined,fleet.actor.collider,fleet.actor.body),length=hit?hit.timeOfImpact:tool.range;
  if(hit){const a=animals.find(a=>a.collider.collider(0).handle===hit.collider.handle);if(a)a.alert=Math.max(a.alert,tool.id==='water'?3:4);}
  const end=new T.Vector3().copy(ray.origin).addScaledVector(ray.direction,length),v=beam.geometry.attributes.position;v.setXYZ(0,ray.origin.x,ray.origin.y,ray.origin.z);v.setXYZ(1,end.x,end.y,end.z);v.needsUpdate=true;beam.material.color.setHex(tool.color);beamAge=0;
 }
 function groundAt(x,z,fallback){const hit=physics.world.castRay(new R.Ray({x,y:fallback+.5,z},{x:0,y:-1,z:0}),1,true,undefined,undefined,fleet.person.collider,fleet.person.body);return hit?fallback+.5-hit.timeOfImpact:fallback;}
 function drawMap(){const cv=$('fullmap'),c=cv.getContext('2d'),k=4.7,to=p=>[cv.width/2+p.x*k,cv.height/2+(p.z-3)*k];c.fillStyle='#274c46';c.fillRect(0,0,cv.width,cv.height);c.fillStyle='#4c9298';c.fillRect(...to({x:-9,z:-46}),18*k,98*k);
  for(const r of ROUTES){c.strokeStyle=r.id==='observation'?'#e6cc8b':r.id==='water'?'#aadcea':'#bbcba2';c.lineWidth=r.id==='water'?3:2;c.beginPath();r.nodes.forEach((n,i)=>i?c.lineTo(...to(POINTS[n])):c.moveTo(...to(POINTS[n])));c.stroke();}
  for(const [id,p] of Object.entries(POINTS)){if(['roof','report','northBridge','westDock','eastDock'].includes(id))continue;const [x,z]=to(p);c.fillStyle='#eed6a0';c.beginPath();c.arc(x,z,4,0,7);c.fill();c.font='12px sans-serif';c.fillStyle='#f1f3df';c.fillText(id.toUpperCase(),x+7,z-5);}
  if(state.bridge){c.strokeStyle='#f4deb0';c.lineWidth=6;c.beginPath();c.moveTo(...to({x:-12,z:24}));c.lineTo(...to({x:12,z:24}));c.stroke();}if(state.drained){c.fillStyle='#c6c9a4';c.fillRect(...to({x:-9,z:-12}),18*k,8*k);}
  for(const a of animals){c.fillStyle='#d8ab7b';c.beginPath();c.arc(...to(a),3,0,7);c.fill();}c.fillStyle='#ffffff';c.beginPath();c.arc(...to(fleet.position),5,0,7);c.fill();
 }
 function ui(){const t=nextTask(state);$('mission-title').textContent=t.title;$('mission-copy').textContent=t.text;$('district-status').textContent='Gearbox '+(state.gearbox?'aligned':'offline')+' / bridge '+(state.bridge?'open':'raised')+' / lock '+(state.drained?'drained':'flooded');$('tool-name').textContent=tools.tool.name;$('ammo').textContent=Math.floor(state.ammo[state.tool])+' / '+state.reserve[state.tool];$('reload-status').textContent=tools.reloadLeft>0?'Reloading '+tools.reloadLeft.toFixed(1)+' s':'D-pad left: water / right: zapper';$('vehicle-mode').textContent=fleet.mode.toUpperCase();findCandidate();$('interact-label').textContent=candidate?.label||'Explore the district';$('interact-button').disabled=!candidate;$('reticle').hidden=fleet.mode!=='foot';if($('map-dialog').open)drawMap();}
 function frame(now){const dt=Math.min(.08,Math.max(0,(now-last)/1000));last=now;const controls=mergeMotion(input.sample(dt),xr.update(dt));if(xr.active){yaw=xr.controlYaw??yaw;controls.lookX=controls.lookY=0;}const live=paused()?0:dt;
  if(live){yaw-=controls.lookX*dt*2;pitch=clamp(pitch+controls.lookY*dt,.2,1.15);acc+=live;let steps=0;while(acc>=1/60&&steps++<5&&!paused()){time+=1/60;tools.tick(1/60);for(const a of animals){stepHerd(a,1/60,time,state);a.collider.setNextKinematicTranslation({x:a.x,y:1,z:a.z});}fleet.step(controls,1/60,time,yaw);physics.world.step();fleet.after(1/60);if(controls.fire)shoot();acc-=1/60;}saveClock+=live;if(saveClock>5){saveClock=0;save();}}
  else acc=0;
  fleet.sync(live);const person=fleet.personModel;person.visible=fleet.mode==='foot'&&(!xr.active||xr.diorama);if(person.visible)animateRangerBody(person,fleet.person,live,time,{reduced,aiming:controls.aim,groundAt});
  for(const a of animals){a.model.position.set(a.x,0,a.z);a.model.rotation.y=a.angle;animateResident(a,live,time,reduced);}
  const p=fleet.position;toolModel.visible=fleet.mode==='foot'&&(!xr.active||xr.diorama);toolModel.position.set(p.x-.5*Math.sin(yaw)+.3*Math.cos(yaw),p.y+.35,p.z-.5*Math.cos(yaw)-.3*Math.sin(yaw));toolModel.rotation.y=yaw+Math.PI;
  beamAge+=live;beam.visible=beamAge<.12;beam.material.opacity=Math.max(0,1-beamAge/.12);world.update(live,time,state,p,xr.diorama);audio.update(fleet.actor.speed,!!live&&fleet.mode!=='foot');
  if(started&&!xr.active){const focus=new T.Vector3(p.x,p.y+.8,p.z),desired=new T.Vector3(p.x+Math.sin(yaw)*zoom*Math.cos(pitch),p.y+zoom*Math.sin(pitch),p.z+Math.cos(yaw)*zoom*Math.cos(pitch));const dir=desired.clone().sub(focus),length=dir.length();dir.normalize();const hit=physics.world.castRay(new R.Ray(focus,dir),length,true,undefined,undefined,fleet.actor.collider,fleet.actor.body);if(hit)desired.copy(focus).addScaledVector(dir,Math.max(1.2,hit.timeOfImpact-.3));camera.position.lerp(desired,reduced?1:1-Math.exp(-dt*8));camera.lookAt(focus);}
  uiClock+=dt;if(uiClock>.12){uiClock=0;ui();}if(xr.active){xr.position();xr.render();}else renderer.render(scene,camera);
 }
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();show('menu-dialog');notify('Graphics context interrupted. Your last Tidegate checkpoint is preserved; reload to restore rendering.');});
 const debug={get state(){return {build:TIDEGATE_BUILD,ready:true,started,paused:paused(),position:{...fleet.position},mode:fleet.mode,yaw,progress:JSON.parse(JSON.stringify(state)),candidate:candidate?.id||null,animals:animals.map(({species,x,z,mood,alert})=>({id:species,x,z,mood,alert})),xr:xr.snapshot(),drawCalls:renderer.info.render.calls};}};
 if(new URLSearchParams(location.search).get('test')==='1')Object.assign(debug,{xr,world,camera,renderer,physics,fleet,input,tools,animals,progress:state,show,action});window.__tidegate=debug;window.__dinoRanger={get state(){return {...debug.state,tool:tools.tool.id,ammo:[...state.ammo],reloading:tools.reloadLeft};}};
 $('start-button').disabled=false;$('start-button').textContent=state.position||state.gearbox?'Continue Tidegate Crossing':'Enter Tidegate Crossing';$('load-status').textContent='Ready. A selects; Settings offers first-person VR, VR diorama and AR diorama.';$('start-button').focus({preventScroll:true});ui();renderer.setAnimationLoop(frame);
}
