"""Apply reviewed safety fixes exactly; refuse unknown source or scope."""
from pathlib import Path
import hashlib
root=Path('svgn-planet/lantern')
checks={'core.mjs': {'before': '9bbbae0e74ccf51a190e3f3d8b7876afe0992ab2a5ca10b394f46192608fd2c4', 'after': '7d0d1b5c24b118bc289168b4e584a6dff048575cf132a9f19ebd81da18b4f344'}, 'view.mjs': {'before': '1652e3ea3c46bc7d2e506b78c2d1d1475cb1201418d9181951c1fb6782ebd243', 'after': '3de9649d2fc48999442f5ba62039a962aba7f62e981f2e24ef2a4eeb7db6843a'}, 'xr.mjs': {'before': '96dbb3e9cb6ee13de3a58dde357f0c8ab8ab757473a066e09bc984d0e10b9ec0', 'after': 'ff7d85f2b9f7bb3b4cffb72c643f8ccc3bbeffbb8134d748bf7e1f6e7ee33aac'}}
edits=[['core.mjs', 'const text=JSON.stringify(serialize(s));parse(text);\n try{', "let text;try{const payload=serialize(s);if(payload.y< -3||payload.y>8){[payload.x,payload.y,payload.z]=s.safe;payload.ride='foot';}text=JSON.stringify(payload);parse(text);"], ['core.mjs', 'x:s.porterYield>0?-22:-19.4', 'x:s.porterYield>0?-23:-18.25'], ['core.mjs', "if(name!=='interact'&&name!=='throw')return;", "if(name==='throw'){s.paper={x:s.x,y:s.y+1.1,z:s.z,dx:-Math.sin(s.yaw),dz:-Math.cos(s.yaw),t:0};say(s,'Practice paper thrown. Workshop parcels need a handoff at the receiving bench.');return;}\n if(name!=='interact')return;"], ['core.mjs', 'if(s.transition){s.transition.t+=dt/2;if(s.transition.t>=1){s.water=s.transition.to;', "if(s.paper){s.paper.t+=dt;if(s.paper.t>1.1)s.paper=null;}\n if(s.transition){s.transition.t+=dt/2;if(s.transition.t>=1){if(inside(s.x,s.z,canal)||s.ride==='boat'){s.transition=null;say(s,'Sluice paused: clear the channel first. The safe water level is unchanged.');return;}s.water=s.transition.to;"], ['view.mjs', 'batch(decor);', 'batch(decor);batch(lowGroup);for(const g of world.children)if(g!==decor&&g!==lowGroup&&g.isGroup&&g.children.some(m=>m.geometry===boxGeo))batch(g);'], ['view.mjs', 'new T.SphereGeometry(.035,12,8)', 'new T.SphereGeometry(.12,12,8)'], ['view.mjs', 'const side=i?-1:1', 'const side=i?1:-1'], ['view.mjs', 'const people=[', 'const flyingPaper=box(world,0xf5e7c5,0,0,0,.25,.025,.16);flyingPaper.visible=false;\n const people=['], ['view.mjs', 'gate.visible=!s.gate;', 'flyingPaper.visible=!!s.paper;if(s.paper){const p=s.paper;flyingPaper.position.set(p.x+p.dx*p.t*6,p.y+Math.sin(p.t*Math.PI)*.5-p.t*.8,p.z+p.dz*p.t*6);flyingPaper.rotation.set(p.t*8,p.t*3,p.t*5);}\n  gate.visible=!s.gate;'], ['xr.mjs', 'clamp,lineClear', 'clamp,lineClear,support,floorHeight'], ['xr.mjs', "let rows=[],panelSignature=''", "let rows=[],focused=-1,panelSignature=''"], ['xr.mjs', "ctx.fillStyle='#365865';ctx.fillRect(r.x,r.y,r.w,r.h);", "ctx.fillStyle=rows.indexOf(r)===focused?'#628782':'#365865';ctx.fillRect(r.x,r.y,r.w,r.h);"], ['xr.mjs', 'rig.position.set(state.x-offset.x,state.y+1.65-offset.y,state.z-offset.z);', 'const floor=support(state,state.x,state.z,state.y),eyeY=state.lift?state.y:floor?floorHeight(floor,state.z):state.safe[1];rig.position.set(state.x-offset.x,eyeY+1.65-offset.y,state.z-offset.z);'], ['xr.mjs', 'if(hooks.paused())input={x:0,y:0,boost:false,brake:true};', 'if(hooks.paused()||view.curtain.visible)input={x:0,y:0,boost:false,brake:true};'], ['xr.mjs', 'return {enter,update,clear,setMode,settings,exit', 'return {enter,update,clear,setMode,settings,navigate:(direction,accept,back)=>{if(!session||!hooks.paused())return;if(back){hooks.pause(false);return;}if(direction)focused=(Math.max(0,focused)+direction+rows.length)%rows.length;if(accept){const row=rows[Math.max(0,focused)];row?.fn?.();selections++;}lastPaint=0;},exit']]
for name,digests in checks.items():
 path=root/name
 text=path.read_text()
 sha=hashlib.sha256(text.encode()).hexdigest()
 if sha==digests['after']:continue
 assert sha==digests['before'],f'Unexpected source: {name}'
 for n,a,b in edits:
  if n==name:
   assert text.count(a)==1,(name,a,text.count(a))
   text=text.replace(a,b)
 assert hashlib.sha256(text.encode()).hexdigest()==digests['after'],name
 path.write_text(text)
 print(name,digests['after'])
